dcos/dcos-ui

README.md
Adjust the load DC/OS URL, as it will not resolve to 192.168.65.90 (http://m1.dcos) without an extra undocumented configuration step.
=> Adjust local DC/OS URL

src/js/constants/ServiceStatus.js, src/js/constants/StatusLabels.js, src/js/structs/Service.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/Service-test.js, src/js/structs/__tests__/ServiceTree-test.js
This adds getStatus to the service and the serviceTree structs as this is mandatory for the status bars on the service table. It does only support a small set of statuses to keep this PR small and the rest will be issued in another PR later.
=> Feature add status to service and service tree structs 

src/js/components/RepositoriesTable.js, src/styles/components/typography.less
In collaboration with the designers we came to the conclusion to always show the full URL and break it into multiple lines in the table, if there is not enough space. An added benefit with this is that people now can copy the whole URL if needed.
Also, the URL field will now take up 'the rest of the space' in the table, if there is any left.
Small screen:
Bigger screen:
=> Always show full url in table, ref. DCOS-6085

src/js/components/FilterButtons.js, src/js/components/__tests__/FilterButtons-test.js
Refactor the `FilterButtons` component, to make the `filterByKey` prop optional, as the item list could also be a plain list of values.
=> Make the FilterButtons filterByKey prop optional

src/js/components/FilterBar.js, src/js/components/__tests__/FilterBar-test.js
Introduces the `FilterBar` component to wrap component children in `filter-bar` styles. The `rightAlignLastChild` and `rightAlignLastNChildren` props are optional parameters to right-align items in the FilterBar. 
Depends on https://github.com/dcos/dcos-ui/pull/6
=> Introduce FilterBar component

package.json
Plugin testing is broken since upgrading `babel-jest`. This should fix.
=> Fix broken testing task

src/js/components/ClickToSelect.js, src/js/components/__tests__/ClickToSelect-test.js, src/js/components/modals/CliInstallModal.js, src/js/components/modals/VersionsModal.js
This PR introduces the `ClickToSelect` Component. 
Usage: wrap a component with `ClickToSelect` to cause browser highlights of the components contents when clicked.
=> Introduce & Use ClickToSelect Component

src/js/constants/TaskStates.js, src/styles/components/icons.less, src/styles/components/typography.less
Introduce task killing state (`TASK_KILLING`) which was added in Mesos 0.28.0. This should fix issues with undefined task `stateTypes`.  I'm using the task killed icon for now, but I'm happy to replace it if you guys have a better one for me.
**Mesos Changelog**
https://github.com/apache/mesos/blob/4d2b1b793e07a9c90b984ca330a3d7bc9e1404cc/site/source/blog/2016-03-17-mesos-0-28-0-released.md
/closes DCOS-6528
/cc @silverem2 @leemunroe
=> Add task killing state

README.md
Add the proxy_buffering nginx directive to ~~increase~~ decrease assets loading time and add explicit instructions to get started on the Vagrant DC/OS setup.
=> Add missing instructions for DC/OS Vagrant setup

src/js/components/ServiceDetail.js, src/js/components/ServiceDetailTaskTab.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceDetailTaskTab-test.js
Refactor the service detail and move the tasks view into it's own component - this enables us to only poll the Mesos state, while a user is looking at the tasks list.
=> Refactor the service detail task view

src/js/structs/List.js, src/js/structs/Tree.js, src/js/structs/__tests__/List-test.js, src/js/structs/__tests__/Tree-test.js
Add optional `filterProperties` parameter to the list and tree struct `filterItemsByText` method. This allows the flexible definition of filter properties whenever you want to filter.
/cc @aldipower
=> Adjust the List and Tree filterItemsByText method

src/js/components/ServiceInfo.js
⚡ Dependent on #61⚡ 
This adds the HealthBar to the Service Detail sub header.
=> Feature add health bar to service detail

src/js/components/ServiceSearchFilter.js, src/js/pages/ServicesPage.js, src/js/stores/DCOSStore.js, src/js/stores/MarathonStore.js, src/js/structs/List.js, src/js/structs/Tree.js, src/js/structs/__tests__/CompositeState-test.js, src/js/structs/__tests__/ServiceTree-test.js, tests/servicesPage/ServiceSearchFilter-cy.js, tests/servicesPage/SidebarFilter-cy.js
This reintroduces the service page text search, which enables a search of the complete Marathon Services (Groups, Apps).
The search is stored as a query param and AND-connected to the sidebar filters.
The search field could be placed anywhere in the application, so it's basically a global search placed locally.
Thx @kennyt for the help and preliminary work.
=> Feature - Service page text search

src/js/pages/ServicesPage.js, src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/services/DeploymentsTab.js, src/js/pages/services/ServicesTab.js, src/js/routes/services.js
This PR introduces a tabbed navigation to the services page, and splits the functionality previously in `ServicesPage` out to `ServicesTab`. The `DeploymentsTab` currently only shows an empty state. 
Note that in order to avoid conflicts (eg with a service named `deployments`) the service detail routes have been updated to use the `service` prefix, eg `/services/web-server` is now accessible at `/service/web-server`.
=> Add tab for deployments

src/js/pages/universe/PackagesTab.js
The packages tab search field was calling `filterItems` instead of `filterItemsByText`, with the result that the search field was broken:
=> Fix packages search field

src/js/pages/services/ServicesTab.js
This PR ensures that the query params reflect the user filter selection automatically persisted by the `SaveStateMixin`. 
(ignore the `Breadcrumb` text in the gif)
=> Update query params to reflect user saved state

src/js/mixins/__mocks__/QueryParamsMixin.js, src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/services/ServicesTab.js, src/js/stores/__mocks__/UserSettingsStore.js
This PR fixes the bug highlighted in this comment: https://github.com/dcos/dcos-ui/pull/92#discussion_r61952582
Previously, query parameters were not shown in the URL even though they persisted over navigation.
=> Fix services tab query param persistence

jest/gen-config.js, package.json, src/js/plugin-bridge/__mocks__/Loader.js, webpack/webpack.config.babel.js
`npm config set` doesn't work in CI where we have protected user directories `/Users/[username]/..`.
To honor setting npm config via environment variables, we cannot have underscores in our keys because they get converted to hyphens and therefore do not override the npm config.
=> Make npm honor environment variables

webpack/webpack.dev.babel.js
The new Webpack setup is awesome but a tad verbose ;) This PR reduces the amount of output for easier reading.
From:
To:
Example with errors:
Cheers!
=> Reduce amount of webpack console output

src/js/structs/List.js, src/js/structs/__tests__/List-test.js
This PR adds an optional `type` property to `List`, in order to avoid having to enforce typing in each subclass of `List` (eg [here](https://github.com/dcos/dcos-ui/blob/master/src/js/structs/NodesList.js#L11-L18) in `NodeList`). 
If the `type` property is present, `List` will enforce typing on instantiation and when an item is added.
=> Optionally enforce types on List.

src/js/structs/Deployment.js, src/js/structs/DeploymentsList.js, src/js/structs/__tests__/Deployment-test.js
This PR introduces a 'struct' for the `Deployment` type, in preparation for a second PR which will introduce the `Deployment` to the `MarathonStore`
This PR must be merged before #136.
=> Introduce struct for deployments

src/js/components/SidePanels.js, src/js/components/UnitHealthNodesTable.js, src/js/components/__tests__/SidePanels-test.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/UnitsHealthTab.js, src/js/routes/factories/system.js
System Health side panels get an upgrade to full page ✨
depends on: 
- https://github.com/dcos/dcos-ui/commit/45908c02b13614f82ca5d3032b1f741bd85f9747 for correctly inverse styled dropdown
- https://github.com/dcos/dcos-ui/pull/82 for headers
notes:
- The top tabs are to be removed in detail views in the future, when the breadcrumbs are introduced.
`/system/overview/components`
`/system/overview/components/<component>`
`/system/overview/components/<component>/nodes/<node>`
=> [Feature] System Health sidepanels upgrade to full page

src/js/components/ComponentList.js, src/js/components/SidePanels.js, src/js/components/UnitHealthNodesTable.js, src/js/components/__tests__/SidePanels-test.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/UnitsHealthTab.js, src/js/routes/dashboard.js, src/js/routes/factories/system.js
Before: 
- component health side panels would overlay the dashboard page when targeted from the dashboard component health widget
After:
- dashboard component health widget links redirect to `/system/overview/components` page
Depends on https://github.com/dcos/dcos-ui/pull/84
=> [Feature] Redirect Dashboard Health

tests/_fixtures/secrets/policies.json, tests/_fixtures/secrets/policy.json, tests/_fixtures/secrets/secret.json, tests/_fixtures/secrets/secrets.json
No more policies.
According to [this spec](https://github.com/mesosphere/dcos-security/blob/master/secrets/docs/apispec-swagger.yaml)
=> [EASY REVIEW] Update secrets fixtures

src/js/events/ServicePlanActions.js
@MatApple Let me know if you'd prefer to do this in some other way, but `ServicePlanStore` expects the dispatched `serviceID` to not be URI encoded.
=> Preserve serviceID format when dispatching actions

src/js/mixins/TabsMixin.js, src/js/utils/TabsUtil.js, src/js/utils/__tests__/TabsUtil-test.js
This PR updates the tab utility so that instead of making a tab active when its name exists anywhere in the route, it only makes the tab active when its name exists at the start of the route. 
- The tab named `universe-packages` will be active with either of the routes `universe-packages` or `universe-packages-detail`.
- The tab named `services` will be active with `services` and `services-detail` but not with `-services-deployment`. 
This PR provides the basis for the fix in #166
=> Only highlight tab on prefix match

TESTING.md
Cypress package rename! https://docs.cypress.io/docs/deprecations#section-cypress-package-renamed
Also added additional clarifying instructions.
=> Update Cypress install instructions in test readme

src/styles/layout/media-object.less
When dropdowns are not direct children, but still children these introduced styles will still take effect, but they shouldn't.
Before:
After:
=> Make dropdown menu fix only work for direct children

src/js/components/PageHeader.js, src/js/components/__tests__/PageHeader-test.js
PageHeader was using the `classnames` API correctly, but classes were not actually being removed because we weren't using the `dedupe` version.
```
// Without dedupe:
classnames('class-1 class 2', {'class-1': false})
> 'class-1 class 2'
// With dedupe:
classnames('class-1 class 2', {'class-1': false})
> 'class-1'
```
=> De-dupe PageHeader classnames attributes

src/js/components/charts/ProgressBar.js, src/js/components/charts/__tests__/ProgressBar-test.js, src/styles/components/progressbar.less
The resource bars on the Node Table were not always animating and displaying values properly (for example, when loading the UI in a different page and navigating to the Node page). This fix animates transform rather than width which will render properly on page changes.
=> Bug: Node Table resource bar animation

src/styles/components/filter-bar.less
Adding filter bar offset, to remove extra padding for filter bar if not needed.
Example use in the modal header:
Before:
After:
=> Adding filter bar offset, to remove extra padding if necessary

src/js/components/Sidebar.js, src/js/pages/JobsPage.js, src/js/pages/jobs/JobsTab.js, src/js/routes/index.js, src/js/routes/jobs.js, tests/pages/jobs/JobsOverview-cy.js
All this PR accomplishes is to establish the Jobs overview page and routes. Consider it as the first step towards having the various Jobs views.
=> Establish Jobs page and routes

src/js/utils/SchemaUtil.js
This adds the possibility to add a text area with a schema to the advanced config, this is needed for the command field in the `deploy a service` modal. With that minor change it is possible to configure a multiline field which embraces the form field for textareas from the reactjs components.
There is also a PR on the reactjs components to remove the keydown listener which blurs on enter.(mesosphere/reactjs-components/pull/255)
This is a dependency for #212
=> Add textarea to SchemaUtil

src/js/structs/List.js
This PR addresses concerns over performance problems with untyped list initiation. I ran a couple of benchmarks - initiating a `NodesList` (untyped, inherits from `List`) of 1,000 items
- Before: `1,653 ops/sec`
- After: `3,395 ops/sec`
=> Only cast list items if type is set

src/js/components/SidebarFilter.js
Just a quick hotfix to have a somewhat usable Services page when on smaller screens. 
A proper RWD implementation will follow later (captured in MARATHON-1060).
=> Quickfix for RWD in Services tab

src/js/components/FormModal.js
This will allow us to extend the `FormModal`'s content classes, which I need for an upcoming PR.
=> Allow extendable classes in FormModal

src/js/components/PageHeader.js
This class was added to `PageHeader`, and needs to be removed in these special cases when there are no tabs. 
For example, 
before:
after:
=> Bug - Give PageHeader correct padding when it has no tabs

src/js/components/StatusBar.js, src/js/components/__tests__/StatusBar-test.js
In ServicesPage, the `StatusBar` component was not showing value because of previously changed styles that animated `transform` rather than `width`. This PR updates `StatusBar` accordingly.
=> Bug - StatusBar value not showing

src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
Extend the service struct with a couple of get functions, those are needed for the deploy a service modal.
Also introducing a `ServiceUtil.js` this contains for now 3 functions:
- `convertFormModelToService` - This function is creating a `Service` object from the a `formModel` which is provided by the `AdvancedConfig` component.
- `createFormModelFromSchema` - This is creating a `formModel` with a given `Schema` and `Service`.
- `getAppDefinitionFromService` - This is creating a marathon `appDefinition` from a `Service` Object. 
This is a dependency for #212
=> Extend service struct

src/js/components/Page.js
This bug happened when scrolling is set to `always` on Mac and the content flowed off the page (note the lack of margin under the secondary tabs):
To fix I removed `flex-shrink` so the page doesn't force all the children to shrink. 
I have checked the pages but I'd love a second glance! <3
Shoutout to @jfurrow for his champion css debug insight as always ✨
=> Bug - Disappearing padding from pages

src/js/components/AdvancedConfig.js, src/js/components/SchemaForm.js
This introduces the capability of adding a header to the `advancedConfig` component. This is needed to show a generic title instead of the package name and version.
This is a dependency for #212
=> Add HeaderText to AdvancedConfig

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js
`DCOSStore` is a singleton. The `storeID` property was defined statically. `StoreMixin` accesses its store's `storeID` property naively - in this case from an instantiated `DCOSStore` rather than from its constructor. 
This meant that the `StoreMixin`'s inflection methods weren't able to assemble the correct method name, and components which used the mixin and implemented `onDcosStoreChange` never had their listener methods called. 
This PR resolves that issue by moving `storeId` to the instance.
=> Fix DCOSStore/StoreMixin behaviour

npm-shrinkwrap.json, package.json
This adds `react-ace` as an dependency which will be used for the `JSON` editor.
=> Add React ace component

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js, src/js/structs/Deployment.js, src/js/structs/__tests__/Deployment-test.js
Note that this work is based off a feature branch (`deployments-table`).
This PR adds the `affectedServices` field to `Deployment`. This field is populated by `DCOSStore` when it receives deployments data from `MarathonStore`. If it is not populated and something attempts to access it, it will error rather than show bad data. 
Once this is merged, the whole services table can be populated using only the output from `DCOSStore.deploymentsList`.
=> [1/6] Deployments Table - Deployment struct updates

src/js/structs/JobTree.js, src/js/structs/__tests__/JobTree-test.js
---
ℹ️   _This branch depends on changes that will be introduced with #250, thus it will fail until the respective branch is merged._
---
Introduce basic job tree struct – this struct will be used to type and abstract the Chronos API response. It provide the needed functionality to parse and create sub trees (if needed), to insert jobs in the correct location based on id/path matching.
=> Introduce job tree struct

src/js/components/modals/ServiceGroupFormModal.js
Fix the Create Group modal form to reproduce existing behaviour in Marathon UI.
Extract the parent group ID from the input field itself and show indication of target group in the modal header itself.
Example:
cc @MatApple and @leemunroe
=> Extract parent group id from input field

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js
Note that this work is based off a feature branch (`deployments-table`).
This PR relies on ~~#241~~ and ~~#215~~ (but may be merged before ~~#215~~ without issue). 
This PR adds a notification badge to the Deployment tab. 
Testing:
```bash
git checkout feature/deployment-tab-badge
curl "https://patch-diff.githubusercontent.com/raw/dcos/dcos-ui/pull/215.patch" | git apply
```
(Note - no longer necessary following rebase)
=> [3/8] Deployments Table - Add badge to deployments tab

src/js/components/Breadcrumb.js, tests/pages/services/ServiceSearchFilter-cy.js
A number of updates to `Breadcrumb` based on my attempt to use `Breadcrumb`
- trimmed down `buildCrumb` default function to keep parsing minutia external to that function so overriding this function with a prop requires less repeated code
- explicitly set the `buildCrumb` default function in `defaultProps`
- added `buildCrumbCustomParams` prop to supply custom parameters to `buildCrumb` function for custom labels. This prop also helps trigger `shouldComponentUpdate` when custom params are updated
=> Updates to Breadcrumb

src/js/components/TaskView.js
I am not interested in completed tasks at the first point, so I've set the initial filter state to 'active'.
=> [MERGE or PURGE] Show active tasks as initial state

jest/gen-config.js, src/js/stores/BaseStore.js, src/js/stores/__tests__/BaseStore-test.js
This base store will be extended by all other stores and it's intended to replace the `Store.create` util as well as the GetSet mixin.
=> [ES6 class] Introduce base store

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js, src/js/structs/Deployment.js, src/js/structs/__tests__/Deployment-test.js
`ServicesList` is actually a list used for instances of `Framework`, not `Service`. In order to avoid casting our non-framework services to frameworks, let's use an array to hold services on deployments instead of a `List`.
=> [2/8] Deployments Table - Don't use ServicesList to list services

README.md
This is so that people aren't confused when writing new code which modules they should use as examples.
=> Adds module type examples

src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/services/DeploymentsTab.js, src/js/stores/DCOSStore.js
Note that this work is based off a feature branch (`deployments-table`).
This PR relies on ~~#241~~ and ~~#248~~ (it may be merged before #248 without issue)
The intention of the PR is to keep the behaviour of the deployments table exactly the same, but making use of the `DCOSStore` instead of the `MarathonStore`. 
Testing:
```bash
git checkout feature/deployment-dcos-store
curl "https://patch-diff.githubusercontent.com/raw/dcos/dcos-ui/pull/248.patch" | git apply
```
Note: the above is no longer necessary since the merge of #248
=> [4/8] Deployments Table - Use DCOSStore instead of MarathonStore

src/js/stores/ChronosStore.js, src/js/stores/__tests__/ChronosStore-test.js
Move the `storeID` getter to the instance, as the StoreMixin accesses storeIDs as a property of the stores not the constructors.
=> Fix ChronosStore storeID getter

npm-shrinkwrap.json, package.json, src/js/plugin-bridge/PluginModules.js, src/js/plugin-bridge/PluginSDK.js
---
~~⚠️ This PR will fail until @orlandohohmeier's PR has merged~~
~~⚠️ Is dependent on this PR https://github.com/dcos/mesosphere-shared-reactjs/pull/4~~
⚠️ All plugins that depends on this needs to update their stores to use `addStoreConfig` in stead of `createPluginStore`
---
This PR is removing the concept of `createPluginStore` and replacing it with `addStoreConfig` to be used in the plugin stores.
To test this out `git checkout mlunoe/plugin-store-es6-update-test`
=> [ES6 class] Update plugin store es6

src/styles/components/user-dropdown-menu.less
Previously I had naively toggled the user `dropup` menus for all breakpoints. With this PR, the `sidebar-footer-user-dropdown` will be hidden from a viewport width of `0` up to `screen-small`, displayed from `screen-small` to `screen-medium`, and from there the toggle class `is-expanded` will determine its visibility.
=> Fix sidebar toggle button display problems

npm-shrinkwrap.json, package.json
Updating mesosphere-shared-reactjs to version 0.0.17, which will provide us with the functionality of using es6 classes as first argument of ClassUtil, to be extended by a child es6 class
See PR here: https://github.com/dcos/mesosphere-shared-reactjs/pull/8
=> Update mesosphere-shared-reactjs v0.0.17

src/js/constants/ServiceSchema.js
This removes the default value from the schema. Because the fieldInput is only accepting string values.
=> Remove default values from the ServiceSchema

src/js/events/ChronosActions.js, src/js/structs/Job.js, src/js/structs/JobTree.js, src/js/structs/__tests__/Job-test.js, src/js/structs/__tests__/JobTree-test.js, src/js/utils/ChronosUtil.js, src/js/utils/__tests__/ChronosUtil-test.js
This moves chronos jobs data to a reducer-like function that will restructure before passing it to the application
This comment spawned a larger conversation about what we should and should not do in the structs. We decided to move the whole building of the tree to a 'reducer'-like function that is being used in the actions before the struct is being created. That way we can handle any malformed data gracefully before handing it off to the struct:
https://github.com/dcos/dcos-ui/pull/250#discussion_r64840695
Ping team: @MatApple @daiyiwhale @kennyt @rcorral @jfurrow @orlandohohmeier @philipnrmn @pierlo-upitup @Poltergeist @aldipower
=> Move chronos jobs data to a reducer-like function

jest/setupTestFramework.js, src/js/pages/__tests__/DeploymentsTab-test.js, src/js/stores/__tests__/ChronosStore-test.js
Previously we were running `jasmine.clock().install()` in `setupTestFramework`, which worked for some tests, but one of those tests altered the behavior of timing functions for all subsequent tests.
This PR will "uninstall" all application timers (which are created with `global.setTimeout` and `global.setInterval`), then "install" the mock Jasmine timers. It looks funny to see the `uninstall` and `install` methods called consecutively, but it's necessary as far as I can tell due to our use of `global.set{Interval|Timeout}`. Read about it here: https://github.com/jasmine/jasmine/issues/895#issuecomment-127370465
=> Move jasmine.clock installation to specific tests

src/js/constants/ServiceSchema.js, src/js/utils/SchemaUtil.js, src/js/utils/ServiceUtil.js
This adds a select field to the SchemaForm
It also adds the network dropdown to the container settings section of the create modal.
=> Add select field to SchemaForm

src/js/utils/SchemaUtil.js
So in the `ServiceSchema` if you made the `title` in `General` into `WTF???` it would look like this: 
@Poltergeist @aldipower
=> Allow use of title for schema tabs

src/js/components/modals/ServiceFormModal.js
When deploying a service from JSON mode, the jsonDefinition is:
```
{
"service": {
"_itemData": {
"container": {
"docker": {}
},
"mem": 32,
"cpus": 0.2,
"cmd": "sleep 10000",
"id": "fadfa"
},
"container": {
"docker": {}
},
"mem": 32,
"cpus": 0.2,
"cmd": "sleep 10000",
"id": "fadfa"
},
"model": {
"Container Settings": {},
"General": {
"cmd": "sleep 10000",
"mem": 32,
"cpus": 0.2,
"id": "fadfa"
}
},
"jsonMode": true,
"jsonDefinition": "{\n  \"id\": \"fadfa\",\n  \"cpus\": 0.2,\n  \"mem\": 32,\n  \"instances\": 1,\n  \"cmd\": \"sleep 10000\"\n}",
"errorMessage": null
}
```
We can see that there is a `jsonDefinition` inside `jsonDefinition`, and this inside `jsonDefinition` is what createService function should use.
=> Fix an error when deploying service from JSON mode

src/js/events/MarathonActions.js, src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/__tests__/fixtures/MockMarathonResponse.json, src/js/stores/MarathonStore.js, src/js/stores/__tests__/DCOSStore-test.js, src/js/stores/__tests__/MarathonStore-test.js, src/js/stores/__tests__/fixtures/MockMarathonResponse.json, src/js/structs/ServiceTree.js, src/js/structs/__tests__/ServiceTree-test.js, src/js/utils/MarathonUtil.js, src/js/utils/__tests__/MarathonUtil-test.js
Introduce parse groups util and move Marathon data parsing to a "reducer-like" function that will restructure the data before passing it to the application. This applies the new pattern introduced in #269 to the Marathon (`ServiceTree`) data.
/cc @mlunoe
=> Introduce Marathon parse groups util

src/js/components/SideTabs.js, src/js/utils/SchemaUtil.js
With the introduction of the new title attribute for schema sections there was a bug introduced which made it impossible to navigate to a section with a title attribute.
=> Fix SchemaForm SideTabs

src/js/events/MarathonActions.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js
Fetch service task (last) failure data alongside groups and provide getter - this is needed to implement the service debug tab.
/cc @mlunoe
=> Introduce service task failure data

src/js/utils/MarathonUtil.js, src/js/utils/__tests__/MarathonUtil-test.js
Extend `MarathonUtil` to parse volume data (container, tasks) into a service volume property.
=> Parse Marathon volumes into service property

npm-shrinkwrap.json, package.json
This release includes two changes:
https://github.com/mesosphere/reactjs-components/pull/280: Form return updated model on change
https://github.com/mesosphere/reactjs-components/pull/279: Making form element classes more customizable
No changes to dcos-ui needed
=> Update reactjs-components to v0.14.0-beta.26

src/js/utils/MarathonUtil.js, src/js/utils/__tests__/MarathonUtil-test.js
Fixes this issue:
Bug introduced here: https://github.com/dcos/dcos-ui/pull/327
=> Do not throw when localVolumnes is not defined on marathon task

src/js/constants/ServiceStatus.js, src/js/constants/ServiceStatusLabels.js, src/js/constants/ServiceStatusTypes.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js
This prevents exceptions when none of the existing statuses match.
=> Introduce n/a status as a fallback

src/styles/components/multiple-form.less, src/styles/components/side-tabs.less, src/styles/layout/modal.less
Large:
Medium:
Small:
Mini:
And no changes to other modal forms:
=> Cleanup styles for form elements in modals

src/js/components/ExpandingTable.js, src/js/components/__tests__/ExpandingTable-test.js
This will be used in the Job detail view, which I'll open a PR for soon. Integration tests in that PR will further test the functionality of this table.
Continued from https://github.com/dcos/dcos-ui/pull/299, we decided to move forward with this as it is now. When the other tables are introduced, we will evaluate combining them into a single component.
=> Add ExpandingTable

src/styles/components/icons.less
SVG icons being clipped without `display: block property`
=> Display svg icons correctly

src/js/structs/ServiceTree.js
Please merge before https://github.com/dcos/dcos-ui/pull/349
This fixes an exception in the Service page when groups without a defined status are returned.
=> Hotfix for service tree without status

src/js/components/NestedServiceLinks.js, src/js/plugin-bridge/PluginModules.js, src/styles/components/nested-service-links.less, src/styles/index.less
Splits an AppId into a bunch of links to the service and parent groups. Optionally takes a taskId, creating clickable links for the task and parent service/groups.
Currently restricted to use within a table cell using existing classes. Could be altered without much trouble to work outside of a table but I don't currently see where we'd do that.
=> Add Nested Service Links Component

src/js/components/ServiceInfo.js
This hides the Suspend action in the dropdown if the service has 0 instances (is already suspended).
=> Feature - 1066 Service actions - Hide suspend

scripts/validate-tests
Change the validation pattern to check for the new Jasmin 2 `fit` instead of the old `it.only`.
Run the following command to test the script. It should echo "valid" if there is no `f(it|describe)` nor `(context|it).only` and "invalid" if you add "f" or "only" to one of the tests.
```
eval scripts/validate-tests && echo "valid" || echo "invalid"
```
=> Adjust validate-tests script

src/js/pages/SystemPage.js, src/js/structs/CompositeState.js
So that if the Marathon response comes before Mesos there's no error.
=> Adds defaults to composite sate.

src/js/components/ServiceDetail.js, src/js/components/modals/ServiceScaleFormModal.js
This implements the dialogs/confirm-boxes for the service actions (scale, suspend, destroy).
There is no real action behind them, this will follow next.
Destroy:
Scale:
Suspend:
=> Feature - 1066 Service Actions dialogs

src/js/events/ChronosActions.js, src/js/utils/ChronosUtil.js, src/js/utils/__tests__/ChronosUtil-test.js, tests/_fixtures/chronos/jobs.json
Align `ChronosUtil.parseJobs` and the fetch jobs calls with the latest API adjustments:
* Fix fetchJobs activeRuns embed param
* Change the job id/namespace matching to the new id pattern
* Add missing embed schedules param
/cc @jfurrow
=> Update job tree parsing

tests/_fixtures/chronos/jobs.json
Adjust jobs fixture as the `nextScheduledRunAt` is no longer part of the job status but the schedule (`nextRunAt`).
/cc @jfurrow
=> Update jobs fixture

src/js/components/Page.js, src/js/components/PageHeader.js, src/js/components/ServiceInfo.js, src/js/components/SidebarToggle.js, src/js/components/TaskDetail.js, src/js/components/__tests__/ServiceInfo-test.js, src/styles/components/page-header.less, src/styles/components/scrollbar.less, src/styles/layout/page.less, src/styles/variables/variables-layout.less, src/styles/variables/variables-z-index.less, tests/pages/jobs/JobsOverview-cy.js, tests/pages/system/overview/components/UnitsHealthTab-cy.js, tests/pages/universe/installed/InstalledPackagesTab-cy.js
The `PageHeader` component was a little difficult to work with previously, due to its inheritance of multiple unrelated style components. This PR introduces styles specifically for the `PageHeader` that more closely match the design. Its behavior at smaller viewport widths is more consistent as well.
I also decided to change the classname of our page's tabbed navigation, which was previously called `page-header`. I think this will help clarify the roles of the elements.
=> Refactor PageHeader component

src/js/components/ServiceSidebarFilters.js, src/js/constants/ServiceFilterTypes.js, src/js/constants/ServiceOther.js, src/js/constants/ServiceOtherLabels.js, src/js/constants/ServiceOtherTypes.js, src/js/pages/services/ServicesTab.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/ServiceTree-test.js, tests/pages/services/SidebarFilter-cy.js
This adds support for the OTHER sidebar filters. 
This group of filters is meant for miscellaneous criteria, for example `Universe` (only show Frameworks) and `Volumes` (apps with attached volumes).
=> Introduce OTHER sidebar filters

src/js/schemas/service-schema/ContainerSettings.js, src/js/utils/ServiceUtil.js
This adds the two checkbox fields to the docker section of the Service Schema
=> [ServiceSchema] Add checkbox fields to docker section

src/js/components/ServicesBreadcrumb.js, src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/services/DeploymentsTab.js, src/styles/components/deployments-table.less, src/styles/components/tree-list.less, src/styles/index.less
This PR introduces services to the deployments tables and adds styles for them. The `tree-list` will hopefully eventually be contributed upstream to Canvas-UI, but for the moment has been added as a dcos-ui specific component. 
__NB: I have had to create a new feature branch after the last one got badly out of synch. See #370 for more detail.__
=> [5] Deployments Table - Introduce service rows

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js
Previously, we assumed that groups data was available from the Marathon store when we populated the DCOS Store with deployments data. This was not only bad in theory but also in practice, as the deployments endpoint is significantly quicker than the groups endpoint and the race condition thus created was almost always tripped.
This PR:
Outside the scope of this feature we should either update the name of the `dataProcessed` attribute of `DCOSStore` to reflect that it only relates to groups data, or extend it so that it is only true when all endpoints have returned some data, or (my preference) remove it entirely, since IMO components should not have to perform any sort of introspection against stores.
=> [6] Deployments Table - improve data interpolation

src/js/components/TaskDirectoryTable.js, src/js/utils/DateUtil.js, src/js/utils/ResourceTableUtil.js
Previously the method `msToRelativeTime` expected seconds, now it will take milliseconds as its name suggests
=> Use ms in DateUtil#msToRelativeTime instead of seconds

src/js/utils/DateUtil.js, src/js/utils/__tests__/DateUtil-test.js
This passes a boolean to `moment#fromNow` which will suppress the suffix when set to `true`. It defaults to `false`, which behaves the same way it did before.
Tests passing locally:
=> Allow suffix suppression in DateUtil#msToRelativeTime

webpack/webpack.production.babel.js
Fixes missing table borders in minified CSS. Bug in cssnano http://cssnano.co/optimisations/#mergelonghand
=> Fix missing table borders in minified CSS

src/js/components/JobForm.js
Introduce a job form component – it's mainly needed to work around an issue (DCOS-7669) with the schema form, but might also serve other needs in the future.
/cc @kennyt @Poltergeist
=> Introduce job form component

npm-shrinkwrap.json, package.json, src/img/components/icons/pages.svg, src/js/components/Sidebar.js, src/js/pages/JobsPage.js
This allows us to specify both SVG components and strings as page icon. This should only be necessary for a short time until we move all icons to SVG.
Also depends on #414
=> [2 of 2] Render SVG sidebar icons if they exist

npm-shrinkwrap.json, package.json
This will allow us to load all SVG icons without having to manually covert them to React components. In a future PR, all icons in the application will be replaced with SVGs using this loader.
Example:
`import IconAdd from 'babel!svg-react!../img/icons/icon-add.svg?name=IconAdd';`
Read more here: https://github.com/jhamlet/svg-react-loader
=> [1 of 2] Add svg-react-loader

src/js/pages/services/DeploymentsTab.js, src/styles/components/deployments-table.less, src/styles/components/tree-list.less
This PR brings the styling of the deployments table into line with the designs. 
Before and after:
NB: this PR depends on #388
=> [8] Deployments Table - styling

src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/services/DeploymentsTab.js, src/js/stores/MarathonStore.js, src/js/structs/Deployment.js, src/js/structs/__tests__/Deployment-test.js
This functionality was added after talking with @leemunroe 
This PR introduces a distinction between a starting and a non-starting deployment. A deployment is considered to be starting if it deploys a service for the first time (or in more exact terms, if one of its actions is of type `StartApplication`)
When a deployment starts an application, rolling it back also deletes the linked service. We felt that this was not sufficiently well telegraphed to the user, and that both the rollback link and the accompanying modal should reflect this. 
This PR therefore
NB this PR depends on #401
=> [9] Deployments Table - rollback and remove for 'starting' deployments

src/js/components/Breadcrumbs.js, src/js/components/Page.js, src/js/components/PageHeader.js, src/js/pages/ServicesPage.js, src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/nodes/NodeDetailPage.js, src/js/pages/services/ServicesTab.js, src/js/routes/nodes.js, src/js/routes/services.js, src/js/utils/RouterUtil.js, src/styles/components/breadcrumbs.less, src/styles/layout/page.less, tests/_fixtures/chronos/jobs.json
---
~~⚠️ Dependent on this branch: https://github.com/dcos/dcos-ui/pull/358~~
~~ℹ️ REVIEWER LOOK HERE (diff between this and its depending branch): https://github.com/dcos/dcos-ui/compare/mlunoe/make-task-detail-tabs-routable...mlunoe/bug-fix-log-view-scroll?expand=1~~
---
Node Detail Page log tab scrolls within log view:
Scrolls whole page on any other nodes detail page
Service Detail Page log tab scrolls within log view:
Scrolls whole page on any other service detail page
=> [Log View Bug] Bug fix: log view scroll

src/js/components/SchemaForm.js, src/js/schemas/service-schema/Labels.js, src/js/utils/SchemaFormUtil.js
This fixes multiple row adding. So if there is no field present the next field is added right above the button and not at the beginning of the field.
For clarification here the bug in action:
=> Fix multiple row adding

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
These structs will be later used by the Jobs table.
This PR introduces two methods on the `Jobs` struct:
* `#getLastRunStatus` retrieves the status and time of the most recent run
* `#getScheduleStatus` retrieves the status of the schedule
=> [Jobs Table: 1 of 2] Add additional structs for Jobs table

src/js/components/ServiceForm.js, src/js/components/modals/ServiceFormModal.js, src/styles/components/multiple-form.less
This adds the mappings from `marathon-ui` for the `errorMessages` to give a cleaner display of the path.
=> Change form error logic and styling

src/js/components/ServiceDetailDebugTab.js, src/js/components/TaskStatsTable.js, src/js/structs/TaskStat.js, src/js/structs/TaskStats.js, src/js/structs/__tests__/TaskStat-test.js, src/js/structs/__tests__/TaskStats-test.js, src/js/utils/DateUtil.js
---
~~⚠️ Dependent on this PR: https://github.com/dcos/dcos-ui/pull/381
ℹ️ Reviewer look here for the diff between the two branches: https://github.com/dcos/dcos-ui/compare/mlunoe/add-service-debug-tab...mlunoe/add-service-debug-tab-stats-table?expand=1~~
---
Task with no statistics (the scenario will happen for each section, when information is not available):
=> [2 of 2 Debug Tab] Add service debug tab stats table

src/js/components/ServiceSidebarFilters.js, src/js/components/SidebarLabelsFilter.js, src/js/constants/ServiceFilterTypes.js, src/js/pages/services/ServicesTab.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/ServiceTree-test.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js, src/styles/components/service-sidebar.less, tests/pages/services/SidebarFilter-cy.js
This adds the sidebar labels filter to the Services Page.
Verified by @leemunroe ™️ 
NOTES
----
I am having trouble getting the dropdown ellipsis styling to look right
OUT OF SCOPE
----
=> Service page: Sidebar Labels filter

src/js/pages/JobsPage.js, src/js/pages/ServicesPage.js, src/js/pages/SystemPage.js, src/js/pages/UniversePage.js, src/js/plugin-bridge/PluginModules.js, src/js/routes/factories/system.js, src/js/routes/jobs.js, src/js/routes/nodes.js, src/js/routes/services.js, src/js/routes/universe.js, src/js/utils/RouterUtil.js
This hides the Page navigation tabs and the sub tabs when configured to do so.
=> Hide Header Navigation on Detail Pages

src/js/components/modals/ServiceFormModal.js, src/js/schemas/service-schema/ContainerSettings.js, src/js/schemas/service-schema/General.js, src/js/utils/SchemaFormUtil.js, src/js/utils/SchemaUtil.js, src/js/utils/ServiceUtil.js, src/styles/components/multiple-form.less
~~This is based on #410~~ [~~un~~merged™️]
>This adds the functionallity to have multiple fields in one line.
It converts the schema to the right definition. In the model however
those groups are omitted because they are onlye needed for the view
layer
=> Add form groups

src/js/pages/jobs/JobsTab.js
Make sure we're only rendering the job detail view, if we're actually looking at a job.
/cc @jfurrow
=> Fix job tree rendering

src/js/pages/services/ServicesTab.js
ref to why this is being done: https://github.com/dcos/dcos-ui/pull/416#issuecomment-226187779
=> Always show the services breadcrumb.

src/js/components/modals/ServiceFormModal.js, src/js/pages/services/ServicesTab.js, tests/_fixtures/marathon-1-group/groups.json, tests/_support/spec_helper.js, tests/pages/services/ServiceFormModal-cy.js
This adds the current group to the create modal so that the application id is prefilled with the current group id.
The regular expression `/^(\/.+)$/` is looking for the beginning of the string and matches if the string starts with a `/` and does contain more characters after the slash. This is combined into a group and then replaced with the first group which is the complete string and a `/` is appended. This is needed because in most case a path like `/group/another-group` will be given by `getId` except on root then the return value of `getId` would be `/` so in most cases we want to append a `/` so that the user can begin typing the id of their application.
another approach could be this
```JS
let applicationId = item.getId();
if (applicationId !== '/') {
applicationId = applicationId …
```
=> Add current group to the the app id field in the create modal

src/js/utils/ReactSVG.js
Forces the `fillRule` prop, generated by `svg-react-loader`, to be rendered as `fill-rule`. This is necessary for SVG icons in React 0.14, but can be removed in React 15.x.
In all its glory...
=> Transform fillRule attribute to fill-rule

src/styles/components/multiple-form.less
Removes the requirement of `form-element-inline` to be inside of `horizontal-center`.
Example:
=> Reduce specificity of form-element-inline

jest/preprocessor.js
Icons will break tests because they need to be run through a Webpack loader first. This replaces all icons with empty React elements.
Huge thanks to @rcorral for the help here!
=> [0 of n: Icons] Replace icons in tests with empty React elements

src/js/utils/JobUtil.js, src/js/utils/__tests__/JobUtil-test.js
Add a concurrency policy to the job schedule if it's undefined, as a schedule without a policy is invalid.
This is a hotfix, and we will replace it with a schedule struct that has proper defaults. We will also provide this as an option in the create/edit modal once we support other policies.
=> Add concurrency policy to schedule

src/js/schemas/service-schema/General.js, src/js/utils/ServiceUtil.js, tests/pages/services/ServiceFormModal-cy.js
This adds default values to the Service Schema according to the marathon ui values.
```JSON
{
"id": null,
"cmd": null,
"cpus": 1,
"mem": 128,
"disk": 0,
"instances": 1
}
```
=> Add default values to the service deploy modal schema

src/js/pages/network/VirtualNetworksTable.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetailsTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/task-details/TaskDetail.js, src/js/pages/task-details/TaskDetailsTab.js, src/js/routes/factories/network.js, src/js/stores/MesosStateStore.js, src/js/utils/MesosStateUtil.js, src/js/utils/TaskUtil.js, src/js/utils/VirtualNetworkUtil.js, src/js/utils/__tests__/MesosStateUtil-test.js, src/js/utils/__tests__/TaskUtil-test.js
Sorry for the big PR, needed to work fast to get these final features in :disappointed_relieved:
In MesosStateUtil.js always return `true` in line 43 to see tasks show up.
And in VirtualNetworkTaskTab.js on line 204 you can add this line to see port mappings:
```
task.container = {'type':'DOCKER','docker':{'image':'busybox','network':'USER','port_mappings':[{'host_port':23409,'container_port':23409,'protocol':'tcp'},{'host_port':10003,'container_port':10003,'protocol':'tcp'}, {'host_port':10003,'container_port':10003,'protocol':'tcp'}, {'host_port':10003,'container_port':10003,'protocol':'tcp'}, {'host_port':10003,'container_port':10003,'protocol':'tcp'}, {'host_port':10003,'container_port':10003,'protocol':'tcp'}, {'host_port':10003,'container_port':10003,'protocol':'tcp'}, …
```
=> Adding Virtual Network detail tab with task detail

src/js/components/Icon.js
This is a simple component to make using icons as simple as possible (hopefully). The only thing that may be confusing is the `family` vs. `size` props. From @ashenden's "ICONS ICONS ICONS" email:
>Though our names imply size (e.g. "icon-small”) we think of them as a collection/family.  We could very well call these “icon-banana” or “icon-little-outline-style".  The name is only useful for letting us quickly relate the icons in this collection to each other.  It just so happens that those same names map nicely to the sizes we have in product.
For now we have only four families. If you need an icon larger than `meidum`, then use the `medium` family and whatever size you need.
What size/family do you think should be default? I've defaulted to `medium` but I'm not sure what's best.
=> [3 of n: Icons] Introduce Icon component

src/js/components/ServiceInfo.js
Things changed at another place, so this applies now.
Before:
After:
=> Fix action buttons vertical alignment

src/js/schemas/service-schema/General.js
This should fix the defaults in the schema. Parsing those values in the getter to a string with the default value of `'0'` didn't worked very fine. I am now referencing the default.
Unit tests pass
Integration tests still running
=> Fix defaults in schema

src/js/components/ServiceDetailConfigurationTab.js, src/js/components/modals/ServiceFormModal.js, tests/_support/spec_helper.js, tests/pages/services/ServiceVersions-cy.js
@ashenden Is there an straight-forward way of putting a gap between the dropdown and the edit button?
I've already invested some time to solve this actually easy problem, but gave up to proceeded with the implementation of functionality.
I don't want to add a specific class only for that.
Maybe you have a hint?
=> Feature - Service versions rollback buttons

src/js/components/HostTable.js, src/js/components/Sidebar.js, src/js/pages/DashboardPage.js, src/js/pages/JobsPage.js, src/js/pages/NetworkPage.js, src/js/pages/ServicesPage.js, src/js/pages/SystemPage.js, src/js/pages/UniversePage.js, src/styles/layout/sidebar.less
This PR introduces the sidebar icons. It also removes the logic in the sidebar which rendered both SVG icons and sprited icons, and fixes the opacity that was previously applied to the sprited icons.
=> [4 of n: Icons] Implement sidebar icons

src/js/pages/task-details/TaskDetail.js, src/js/routes/factories/network.js, src/js/routes/nodes.js, src/js/routes/services.js
Use the route definition (`Route.prototype.children`) instead of configuring a set of tabs that must match the corresponding route configurations. This prevents configuration errors and enables us to
reuse the task detail in more places (e.g. jobs)
=> Refactor the task detail tab configuration

src/js/utils/SchemaFormUtil.js
Array values in service form will no longer reverse when switching from json/form
=> Make sure to add to firstIndex in order to not accidentally reverse values

src/js/components/DisplayPackagesTable.js, src/js/components/HostTable.js, src/js/components/PackagesTable.js, src/js/components/ServicesTable.js, src/js/components/TaskDirectoryTable.js, src/js/pages/jobs/JobsTable.js, src/js/utils/TaskUtil.js, src/styles/components/icons.less, src/styles/components/tables.less
Previously we gave ALL `.icon` elements inside `table`s a margin, and the CSS was very specific.
I've introduced new classes, `.icon-margin-right` and `.icon-margin-left` and applied them where we relied on the general class for margins.
=> [1 of 4: Icons] Remove high-specificity icon styles

src/js/schemas/service-schema/General.js
This adds a link to the Universe page to the General service form.
I've tried to use the react-router-Link-component, but this doesn't work out because there is no `context.router` in the `General.js`-object.
Kind of overengineered!
=> Add universe link to service form

src/js/components/modals/ServiceFormModal.js
http://cl.ly/1l1k2b0V3D3M
Thsi removes the error message when a change in JSON mode is happening.
=> Remove errormessage after json change

src/js/components/HealthBar.js, src/js/components/ServicesTable.js, src/styles/components/service-table.less, src/styles/components/statusbar.less
Here's another stab. I spoke with ashenden and we decided to display the total number of tasks in the tooltip at smaller viewport widths.
This also handles much larger numbers of tasks.
=> Improve ServiceTable responsiveness, v2

src/js/components/SidebarToggle.js, src/styles/layout/page.less
Per @ashenden's request, here's a new menu toggle button:
Relevant commit: 6e05e1fd6d8e4e49a76dcbe18f88e949f1c32691
=> [4 of 5: Icons] Implement new sidebar menu toggle icon

src/js/schemas/ServiceSchema.js
This changes the order of the subnavigation links and puts the optional part at the end.
=> Change order of the subnavigation

src/js/components/modals/ServiceFormModal.js
Ci test `Service Versions Configuration Tab opens correct edit modal of the selected service version` is failing rest passes I try to find out what is the problem there and fix it in another PR. +=> #538
=> Fix force update on service modal

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
Report:
```
https://www.dropbox.com/s/czcjqqa7wxucz3f/Screenshot%202016-06-24%2017.27.09.png?dl=0
This generates:
https://www.dropbox.com/s/79l69cymf0h34ko/Screenshot%202016-06-24%2017.27.31.png?dl=0
Which is missing the VIP.
```
Note that the first screenshot shows host mode, I believe this to be an error in the report based on the most recent requirements I have of the modal -> JSON transformation. I have therefore fixed VIP addition in User mode. 
New behaviour:
- User mode is correctly detected (previously required `networkType=user`, now requires `networkType≠bridge|host`
- VIP label is added in user mode.
Limitation:
It's still not clear where the VIP IP address is added, so I've set it to 0.0.0.0 in a constant.
=> Add VIP fields to portMappings in user mode

src/js/components/ServiceSidebarFilters.js
Add the `flex-no-shrink` class to ensure that the service sidebar filters don't shrink to smaller than their their content's default minimum size.
| Before | After |
|:---------:|:---------:|
| <img width="1438" alt="" src="https://cloud.githubusercontent.com/assets/647035/16384662/1e7301f0-3c8a-11e6-90ad-97e7b42610ec.png"> | ![](https://cloud.githubusercontent.com/assets/647035/16384646/092883f6-3c8a-11e6-949c-d7855ffd0931.png) |
=> DCOS-8000 - Ensure that the sidebar filters have the correct width

src/js/pages/system/UnitsHealthDetail.js
This will prevent a bug where the path to the image might be incorrect.
=> DCOS-7920: Use Webpack import instead of relying on referencing location

src/styles/components/user-dropdown-menu.less, src/styles/layout/sidebar.less
The width of the user dropup menu was not matching the sidebar with. This fixes that.
As an aside, the way we are setting the width of the sidebar for mobile devices is really strange to me (the negative margin value which matches the positive padding feels very hacky) and I'd like to simplify it. I created a tech-debt task for that.
=> Fix user dropup menu width inconsistency

src/js/schemas/service-schema/ContainerSettings.js, src/js/schemas/service-schema/HealthChecks.js, src/js/schemas/service-schema/Networking.js, src/js/utils/SchemaUtil.js, src/styles/components/multiple-form.less
This PR enables `SchemaForm` checkboxes to be rendered with a label inside the `<label>` element. 
The properties that are changed may be a little confusing, but `SchemaUtil` previously would override the `showLabel` property on all `SchemaForm`s, which is what gets displayed on top of a checkbox, whereas the `label` property renders within the `<label>` element.
Before:
After:
=> Allow checkbox labels to be rendered

src/js/components/TaskTable.js
Unfortunately there is also a bug in the `Table` component, so `reactjs-components` needs a new release before this property will actually take effect. https://github.com/mesosphere/reactjs-components/pull/294
=> DCOS-7919: Sort TaskTable descending by default, newest tasks at top

src/styles/components/page-header.less
This PR fixes the positioning of the `:after` element. Thomas saw the bug in the dev channel Chrome, I saw it in IE.
Before:
After:
=> Explicitly set PageHeader border position

src/styles/components/dropdown-menus.less
=> Prevent dropdown toggle from wrapping

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
This PR 
- introduces VIP labels to portDefinitions in host mode
- fixes the VIP labels in user mode (previously was always 0.0.0.0)
- extends the user mode VIP labels to bridged mode
VIP labels are now constructed from the app ID and the specified port.
=> VIPs in modal

src/styles/layout/foundation.less
Without a `min-height` of `0`, Firefox doesn't allow the containers to shrink beyond their intrinsic height.
Before:
After:
=> Force Firefox to obey flex-shrink

src/js/components/SchemaForm.js
This PR adjusts the sub-headers in schema forms.
Before:
After:
=> Adjust sub-header

src/js/schemas/service-schema/Volumes.js
It was abbreviated before because there wasn't enough space. there is enough space now due to RJSC changes not counting JSX elements into width calculation
=> Don't use abbreviations for docker volumes

src/styles/components/multiple-form.less
Overrides the default column padding for columns within `.multiple-form-modal` for all screen sizes.
=> Reduce multiple form column padding

src/js/constants/JobStates.js, src/js/pages/jobs/JobsTable.js, src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
The Jobs table wasn't making use of the `JobStates` constant previously.
Before:
After:
=> DCOS-8167: Properly handle Job status

src/js/pages/jobs/JobsTab.js
We weren't listening for these events previously, so the table didn't update when a new job was added, nor when the job list was fetched.
=> Listen for Job events in JobsTab

src/js/pages/jobs/JobsTable.js
Don't render the status for job groups/trees, as they don't have a state yet.
=> Adjust jobs table status render method

src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js
they didn't want it on the task detail, but really wanted the information shown on the virtual networks tasks table. the agent ip column was always `N/A` even though the data was there. this fixes that
=> Fix the agent IP path for tasks

src/js/components/modals/ServiceFormModal.js, src/js/utils/ServiceUtil.js
This adds the nice error message from marathon which is provided if the user adds a network or local volume to an already existing application.
This is currently not possible in marathon. It is only possible to add volumes to a new service. In this PR the automatic addition of updateStrategy and residency is prevented while editing a configuration.
=> DCOS-8138 & DCOS-8139: volumes error messages while editing an application

src/js/schemas/service-schema/Networking.js
To test this create an app with ports defined in bridge mode e.g. port `80` and then edit the app go either to the network tab which should show the defined port or check the json in the json form.
=> DCOS-8207: Fix port transformation to priotize on port mappings

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
This will default set the hostPort to 0 which will make it possible to deploy a bridged application with any port not only free ones.
=> DCOS-8187: Prevent hostPort to be set

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
Before when the user opened the deploy service modal and toggled to the JSON mode one port was set by default. This fix makes sure that only ports with a set name or lbPort are added.
=> Ensure ports are only added if either name or lbPort is set

src/js/pages/jobs/JobsTab.js
The empty page now says:
` Create both one-off or scheduled jobs to perform tasks at a predefined interval.`
instead of
`Jobs aren't available yet.`
cc @leemunroe for a nod.
=> Update empty Jobs page CTA

src/js/components/modals/JobFormModal.js, tests/pages/jobs/JobActions-cy.js
Change `Deploy` button labels to better describe the create/update in Jobs.
Before:
After:
cc @leemunroe
=> DCOS-8267 - Use better wording for create modal

src/styles/components/breadcrumbs.less
Adjusts the spacing around breadcrumbs in an effort to tighten up that space.
Before
After
=> Adjust vertical padding for breadcrumbs

src/styles/components/breadcrumbs.less
Uses `@base-spacing-unit` from this PR: https://github.com/dcos/dcos-ui/pull/625
I swore I saw the use of the variable in the LESS file, but either I'm crazy or somebody accidentally force-pushed and reverted the change.
=> Use spacing variable in breadcrumbs

webpack/webpack.production.babel.js
Part 1: Make sure fixtures aren't bundled in build.
Part 2 will come later. That includes moving fixture assignment to the dev server.
=> Don't include fixtures in build

src/js/components/CollapsingString.js, src/styles/components/collapsing-string.less, src/styles/index.less
The user specifies a number of characters that should not be truncated at the end of the string, or the default of 15 characters is used.
I opted not to use `classnames/dedupe` here because I thought the performance hit would not be worth it, as I don't expect we'll need to override these classnames. But let me know if you feel otherwise!
=> DCOS-7823: Introduce collapsing string component

src/styles/layout/foundation.less
All content overflow is handled within `div#canvas`, which will always fill the viewport, so this shouldn't be a problem. It prevents the ugly scrollbar from appearing when the user dropup menu is animating closed. I tested this in all browsers, but please try to break it.
=> Apply overflow: hidden to body

src/js/structs/List.js
Properly define `filterProperties` as optional.
=> Fix List documentaiton

src/js/structs/Job.js, src/js/structs/JobRun.js, src/js/structs/JobRunList.js, src/js/structs/__tests__/Job-test.js, src/js/structs/__tests__/JobRun-test.js, src/js/structs/__tests__/JobRunList-test.js
Adjust the job run and job run list struct naming as they will serve as the base class for all job runs, including old once (history).
=> Rename job run structs

src/js/components/CollapsingString.js
Previously the string would collapse if the string width matched exactly the parent width. This is not desirable.
=> [1 of 3: CollapsingString] Use greater than, not greater than or equal to

src/js/components/TaskTable.js
This PR fixes the order of the columns in the service detail page.
=> DCOS-8106: Fix column order on service detail page

src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js
In virtual networks we are displaying Container IP not Agent IP. This PR changes the name of the column to be correct
=> Rename AGENT IP column to CONTAINER IP

src/js/components/ConfigurationView.js, src/js/components/modals/ServiceFormModal.js, src/js/schemas/service-schema/ContainerSettings.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
For some reason the previous implementation converted docker parameters to a record-like object, which produced an error when creating an app:
Docker Parameters should instead be an array of `{key: k, value: v}` objects as per the Marathon Docs: 
https://mesosphere.github.io/marathon/docs/native-docker.html
This PR does the following:
- intercept and use correct top-level dockerParameters mapping for server-side error
- treat docker parameters as an array
- add some basic unit tests
Full workflow GIF:
Tests are passing locally.
=> DCOS-8463: handle docker params as an array of objects

src/js/components/ServiceInfo.js, tests/pages/services/ServiceActions-cy.js
This PR does remove the scale option from the dropdown and adds a clear call to action button for the scale function.
=> DCOS-8466: add scale button to service detail page

src/js/structs/Service.js
If a service has 0 `instances` configured the service state will be set to suspended.
=> DCOS-8440: Add suspended state if service has 0 instances configured

src/js/components/DescriptionList.js
Previously, only strings could be rendered in DescriptionList `dt` because it was required to be a valid key value in an object. This PR extends the capabilities of DescriptionList so that `dt`s can contain components.
=> Allow components to be rendered in DescriptionList dt

src/js/components/FilterHeadline.js
Bring `FilterHeadline` to es6 and add a new prop that forces showing the `clear` button for clearing the filters even if `n of n` objects are being displayed.
before 
after
=> DCOS-8052: Refactor FilterHeadline

src/js/components/CollapsingString.js
@kennyt had the great suggestion of using 1/3rd of the length of the string as the default number of characters to display, instead of the arbitrary 15 I had selected previously.
=> Use 1/3rd of the end of the string by default

src/js/components/MarathonTaskDetailsList.js, src/js/components/__tests__/MarathonTaskDetailsList-test.js, src/js/utils/TaskUtil.js, src/js/utils/__tests__/TaskUtil-test.js, tests/pages/jobs/JobDetails-cy.js, tests/pages/services/ServiceFormModal-cy.js
- Showing IPs even if ports are not defined (new feature)
- Using task ports as fallback for service ports not being available (unchanged)
- Using task host as fallback for ipAddresses if not available (behaviour changed)
=> Show ip addresses for task when using ip per task

src/js/components/DisplayPackagesTable.js, src/js/components/modals/InstallPackageModal.js, src/js/events/CosmosPackagesActions.js, src/js/events/__tests__/CosmosPackagesActions-test.js, src/js/pages/universe/PackageDetailTab.js, src/js/pages/universe/PackagesTab.js, src/js/pages/universe/__tests__/PackageDetailTab-test.js, src/js/stores/__tests__/CosmosPackagesStore-test.js, src/js/stores/__tests__/fixtures/MockPackageDescribeResponse.json, src/js/structs/UniverseInstalledPackagesList.js, src/js/structs/UniversePackage.js, src/js/structs/__tests__/UniverseInstalledPackagesList-test.js, src/js/structs/__tests__/UniversePackage-test.js, tests/_fixtures/cosmos/package-describe.json
This PR updates to use the new v2 API endpoints for `/describe` and `/install`
It does not introduce an immediate visual change. Everything should work as before, but the API responses for `/describe` and `/install` changed slightly.
The change is only concerned with Universe actions. Especially pages using `/describe` and `/install`
=> Update to cosmos v2 for available endpoints

src/js/components/ServiceDetail.js
Objections were made against the "?" that seemed like a query parameter.
Before:
After:
=> Alter service destroy message to better emphasize service

src/js/structs/CompositeState.js, src/js/structs/__tests__/CompositeState-test.js
Bug report (credit @MatApple):
This PR introduces a check that data is not null before attempting to iterate on it.
=> Handle null node health data gracefully

src/js/components/SchemaForm.js, src/js/components/ServiceForm.js, src/js/components/modals/InstallPackageModal.js, src/js/utils/SchemaUtil.js, src/js/utils/__tests__/SchemaUtil-test.js
A much much needed change for schema utils. The functionality is the same. The only thing that changes is instead of taking an insane amount of arguments in a specific order, it now takes an options object which it will derive the needed arguments
=> Allow schema utils to take options

src/js/components/FilterHeadline.js, src/js/components/ServicesTable.js, src/js/pages/services/ServicesTab.js, src/styles/components/breadcrumbs.less, src/styles/components/tables.less, src/styles/variables/variables-tables.less
Bug report: 
> If I search or apply a filter to services, the table/layout shifts, which is jarring and looks like a mistake.
> ![](https://s3.amazonaws.com/f.cl.ly/items/3l2Y2Z2n2G0S1k2N0e2H/Screen%20Recording%202016-07-11%20at%2003.13%20PM.gif?v=d9511b48)
> I think there are 2 issues here:
> 1. The title/breadcrumb is changing style - let's keep it the same i.e. where it changes from "Services" to "Showing 9 of 13 Services", keep this the same font size
> 2. The row height changes due to adding the service location - ideally we can keep the row the same height, similar to how Marathon works today
With this PR:
=> Fix layout on service search results view

src/js/components/PageHeader.js, src/js/components/ServiceInfo.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceInfo-test.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/task-details/TaskDetail.js, src/styles/components/page-header.less, tests/pages/jobs/JobDetails-cy.js, tests/pages/nodes/node/NodeDetail-cy.js, tests/pages/services/TasksTable-cy.js, tests/pages/services/VolumesTable-cy.js, tests/pages/system/overview/components/UnitsHealthTab-cy.js
Per @ashenden's request, the `PageHeader` will now vertically align the icon, text heading, and action buttons. The sub-heading is now left-aligned underneath all three of these elements.
Relevant integration tests passing:
=> Refactor PageHeader

src/js/pages/jobs/JobRunHistoryTable.js, tests/pages/jobs/JobDetails-cy.js
1. Show the actual count of job history
2. sort the runs by `Started`, in descending order instead of by `Status`
*before*:
*after*:
=> Misc. Jobs history fixes

src/js/utils/MesosSummaryUtil.js
The ball still jumps due to the implementation of the ball not animating in the beginning. Feel free to test this.
=> Graphs no longer jump on load

npm-shrinkwrap.json, package.json
We need `canvas-ui` explicitly defined as a dependency because `reactjs-components` expects it to exist in this repository. We need to remove this when `reactjs-components` moves over to `cnvs`.
I also ran shrinkwrap to add `cnvs`.
=> [CNVS Upgrade] Fix dependency definitions

src/js/components/DescriptionList.js
Integration tests passing on a frankie branch, which includes this:
=> Use break-word classname for DescriptionList key

src/styles/components/breadcrumbs.less
Integration tests passing on a frankie branch, which includes this:
=> DCOS-8374: Explicitly set breadcrumb flex-basis for Safari

src/js/pages/services/ServicesTab.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/ServiceTree-test.js
This changes the way services are filtered. This delivers a less verbose list.
=> DCOS-8421: Change the way services are filtered on id search

tests/pages/jobs/JobDetails-cy.js
The expandable row wasn't necessarily the last row in the table. This ensures that it only selects elements which are expandable.
=> Fix failing integration test

src/js/schemas/service-schema/EnvironmentVariables.js
Prevents undefined key/values being set when we build the model and update the definition.
Example of what would happen if you set a container image and command.
=> Fix undefined environment variable

src/js/components/FilterByService.js, src/js/components/HealthTab.js, src/js/components/UnitHealthDropdown.js, src/js/pages/NodesPage.js, src/js/pages/system/UnitsHealthDetail.js
Dropdowns were not being reset when search filters were cleared. This PR fixes that.
before:
(Dropdown still shows 'Unhealthy' after filter is cleared)
after:
(Dropdown resets to default text 'Filter By Service' after filter is cleared)
=> DCOS-8375: Reset dropdown filters on filter clear

src/js/components/ServiceInfo.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceInfo-test.js
Original bug report:
> https://www.dropbox.com/s/n404b53m1i6ustf/Screenshot%202016-07-08%2011.58.50.png?dl=0
> This is in the middle of a deployment. I'd like to see something to know that marathon's still trying to do something.
Implementation:
=> Show service status, not health, in service info

.eslintrc, src/js/utils/Validator.js
We can safely remove these escapes. It doesn't have any effect on functionality. http://eslint.org/docs/rules/no-useless-escape
=> Enable eslint no useless escapes

src/js/components/ServicesTable.js, src/js/utils/ResourceTableUtil.js, src/styles/components/tables.less
Feature request:
> https://www.dropbox.com/s/cy834bpvqp5zq2i/Screenshot%202016-07-08%2011.52.40.png?dl=0
> What are the different states? The marathon UI has a nice standard of showing an info bubble next to puzzling concepts.
In action:
=> Info bubble to explain what service status means

src/js/components/TaskStatsTable.js
Updates columns in Service Debug Table. Removed `Average Seconds` column, renamed `Median Seconds` -> `Median Lifetime`. Introduced new number rounding to report minutes when time is > 3600 secs.
Examples of new number rounding:
=> Remove Average column in debug table, update header name and number rounding

src/js/components/ServicesTable.js
Prevents health bar in services table from caching previous props and animating.
[DCOS-8542](https://mesosphere.atlassian.net/browse/DCOS-8544)
Before:
After fix:
=> Fix animating of healthbar in service table

src/js/schemas/service-schema/General.js, src/js/utils/ResourceValidatorUtil.js, src/js/utils/__tests__/ResourceValidatorUtil-test.js
---
ℹ️  You will see these validation errors only on the second click or after switching the tabs. This is know issue which will hopefully be fixed with https://github.com/mesosphere/reactjs-components/pull/303. 
/cc @kennyt
=> DCOS-8058: Add client side resource validation

src/js/pages/services/ServicesTab.js
Reset the local state when query params representing a filter are reset externally:
Relevant integration tests are passing.
=> DCOS-8464 Reset filters when query params are removed

src/js/components/HealthBar.js, src/styles/components/tooltip.less
=> Pad out tooltip content on Services StatusBar

src/js/stores/MetadataStore.js
Make sure we only route to major doc versions. No patch versions or prerelease (anything after `-`)
=> Fix docs version formatting

src/js/components/SidebarLabelsFilter.js, src/styles/components/buttons.less
Fixes dropdown arrow alignment in Safari.
Before:
After:
=> Fix dropdown arrow in Safari

src/js/components/modals/ServiceFormModal.js, tests/pages/services/ServiceActions-cy.js
This button is too big, the designers have placed it on a restrictive diet.
=> DCOS-8546: Reduce text on gargantuan button

src/js/pages/services/ServicesTab.js
before it was: "showing 3 of 11 services". designers wanted to simply show this
=> Change global service search headline

src/js/routes/jobs.js
Always show the header navigation for Jobs
=> Show jobs header navigation when inside jobs group

src/styles/components/badges.less, src/styles/components/progressbar.less
This adds the candy stripe animation also to the staging bar healthbar in the services section.
=> DCOS-8479: Add staged animation to healthbar

src/js/components/modals/ServiceScaleFormModal.js
This shows a more detailed error on scale if `object is not valid` is the error message which is provided by marathon.
=> DCOS-8371: Add detailed error message on scale

src/styles/components/page-header.less
This PR adjsuts flex properties to account for the `CollapsingString` component which will be used to render the heading string in `PageHeader`.
Previously the page header didn't shrink reliably because we allowed it to spill to multiple lines. Also, the icon and action buttons would shrink, when they shouldn't.
By itself, this PR shouldn't introduce any visible changes. But here's a screenshot of it in use with the `CollapsingString` component:
(imagine that's a very long string instead of just the text `marathon-user` repeated many times)
=> [2 of 3: CollapsingString] Adjust PageHeader styles for use with CollapsingString

src/js/components/SidebarFilter.js
If there are no services with a N/A status this status isn't shown anymore in the status filters sidebar.
Dependend on PR #762
=> DCOS-8075 - Remove NA from status filter if empty

src/js/components/modals/ServiceFormModal.js, src/js/config/Config.js, src/styles/components/ace-editor.less, src/styles/components/tooltip.less, src/styles/index.less
[DCOS-8445](https://mesosphere.atlassian.net/browse/DCOS-8445). Until we figure out how to do contextual help globally, this is what we've got. Currently configure the docs endpoint in Config.js. Perhaps these docs will end up living in dcos.io at some point.
=> Add Help tooltip to JSON editor in Service Modal

src/js/components/ServiceForm.js
This is mostly @MatApple work, thanks again for jumping on this one. 
What it does is removing the docker volumes from the volumes section if no docker image is provided.
=> DCOS-8087: hide docker volumes if no container image is provided

src/js/schemas/service-schema/ContainerSettings.js, src/js/utils/ContainerValidatorUtil.js, src/js/utils/__tests__/ContainerValidatorUtil-test.js
---
ℹ️  You will see this validation error only on the second click or after switching the tabs. This is know issue which will hopefully be fixed with https://github.com/mesosphere/reactjs-components/pull/303.
=> DCOS-8058: Add client side container validation

src/js/components/JobForm.js, src/js/components/modals/JobFormModal.js
This will remove the id field in edit mode of the job form modal and add the job name to the title.
=> DCOS-8722: Remove the id in edit mode from the jobs form add job name to title

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js
This PR introduces a check on every queue update to make sure that services are not incorrectly marked as queued. This fixes several apparent bugs in which service metadata appeared to have become out of date. 
Before/after:
=> Fix for out-of-date service status

src/js/pages/jobs/JobsTable.js
Fixes failing integration tests.
=> Call #getSchedules only if we are rendering a job

src/js/components/TaskTable.js, src/js/constants/TaskTableHeaderLabels.js, src/js/utils/ResourceTableUtil.js
So,
Mesos tasks don't carry the Marathon version, so there is no right way to have this information for a completed task. The right solution to this would be that either Mesos starts storing the version info (maybe as a label) or Marathon starts keeping track of completed tasks.
The only possible solution without any major change is to take the Mesos Task ID and use it to grab the equivalent Marathon Task which contains the `version` we need to render the value. This means, however, that we can't display the version of completed tasks.
So when looking at the full, unfiltered task list, this means:
@leemunroe @pyronicide @air can you please chime in and let us know if this is good enough for 1.8 ?
=> DCOS-8432 Add version column to Tasks list

src/js/schemas/service-schema/Networking.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
This will prevent dcos-ui to change the ports of applications which have a port associated with them. In other words if an application got a port set (random or not random) that this port will be kept on edit.
=> DCOS-8762: Fix port reasigning on edit

src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/services/DeploymentsTab.js, src/js/stores/DCOSStore.js, src/js/structs/Deployment.js
**Background** - when a service is deploying for the first time, rolling back its deployment removes the service configuration. When this happens it's possible for a deployment to exist with references to services which no longer exist in the `MarathonStore`/`DCOSStore`. 
**Previous behaviour** - the deployment was shown but the deleted services were not.
**New behaviour** - the deployment is show and the deleted service IDs are also shown.
Paired with @mlunoe
=> Show stale service IDs on deployments

src/js/components/modals/ServiceFormModal.js
In the case the plugins add fields to the service form and it errors in the backend, we allow the plugins to catch that
=> Add hooks for plugins in service form errors

src/js/stores/MesosStateStore.js, src/js/stores/__tests__/MesosStateStore-test.js
This is the simplest possible implementation of a task ID cache - we simply memoize in order to make repeated calls to `getTaskByTaskID(taskID)` inexpensive. 
Potential improvements: smarter cache-busting (we bust on every poll at present); denormalization on data load.
=> Memoize task IDs

Authors.md
I changed `Current Maintainer` to `Contributor`. If you guys only want maintainers in the file, feel free to remove me
=> Remove Kenny from maintainer list

src/js/components/ServiceDetailConfigurationTab.js, src/js/components/SidebarLabelsFilter.js, src/styles/components/buttons.less, src/styles/components/dropdown-menus.less
Firefox doesn't support `display: flex;` for `button` elements ([read about it](https://bugzilla.mozilla.org/show_bug.cgi?id=984869#c2)), so this circumvents the issue by adding additional DOM nodes which receive the appropriate `flex` properties.
Tested in IE10/Edge, Safari, Firefox, and the ever-so-lovely Chrome.
=> Fix split-content-button for Firefox

src/js/schemas/service-schema/Volumes.js
`Add Network Volume` > `Add External Volume`
`Docker Volumes` > `Docker Container Volumes`
`External Name` > `Volume Name`
Changes reflect Marathon today, and we no longer refer to external as network volumes.
=> Copy changes to volumes tab

src/js/components/SidebarFilter.js
This sorts the sidebar filters by the order of the labels instead of the filter values.
=> DCOS-8067 - Sort sidebar filter by label order

src/js/components/ServiceSidebarFilters.js, src/js/structs/ServiceTree.js
the filtering now matches marathon-ui exactly. please try it out
before, the sidebar filtering would include groups. we no longer do that (unless you're doing a global search with the search string)
we also search through all the children now
=> Fix service table filtering

src/js/components/charts/TimeSeriesChart.js, src/styles/components/charts/index.less
Before:
After:
Done in collaboration with @jfurrow
=> Add unusccessful block for time series charts

src/js/components/ServiceForm.js
When creating a new service, invalid field values are not flagged to the user until the deploy button is hit twice. 
This fix is terrible, let's not use it.
=> Worst-case-scenario fix for deploy button issue

src/js/events/TaskDirectoryActions.js
This timeout for node state can be increased because it is specific to a single node. We do not rely on this data for any charting. A cluster on the other side of the world will take up to ~3.5 seconds to respond to node state requests and thus make any task related view fail.
State requests to master take <= 1.5 seconds so no need to change behavior there.
Top request is made to master `/mesos/master/state`
Bottom request is made to a node directory `/agent/75784894-fdf8-4119-8d64-b618167ebc5d-S0/slave(1)/state`
=> Increase timeout for node state as server can take a while to respond

src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js
This is a quick fix to not have nested header element. We need to look into making the modal header able to do what we need it to do, and this is a symptom of it.
=> Using the h4 class to not have nested header elements

src/js/components/MesosLogView.js
Before (I am not controlling being kept in the bottom - only trying to scroll back up):
After (I am controlling the scroll, every scroll direction is controlled by my interaction):
=> Using correct height measurement

src/js/pages/services/DeploymentsTab.js, src/styles/components/deployments-table.less
NB: I've used the existing progress bar styles for the deployments progress bar, which aren't exactly the same as the design. I'd like to update all progress bars to SVG eventually in order to address the disparity there. 
Design:
Implementation:
=> Show progress bars in deployments

npm-shrinkwrap.json, package.json, plugins/oauth/components/UserDropup.js, src/js/components/FilterByFormTab.js, src/js/components/FilterByService.js, src/js/components/FilterByTaskState.js, src/js/components/ServiceDetailConfigurationTab.js, src/js/components/ServiceInfo.js, src/js/components/ServicesTable.js, src/js/components/SidebarLabelsFilter.js, src/js/components/UnitHealthDropdown.js, src/js/components/modals/ActionsModal.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/system/OrganizationTab.js, src/js/pages/task-details/TaskLogsTab.js, src/styles/components/dropdown-menus.less
Here's the scroll event handler working with both native overlay scrollbars and Gemini overlay scrollbars:
Native:
Gemini:
=> DCOS-8588: Allow dropdown menus to appear outside of scrolling containers

src/js/components/charts/ResourceBarChart.js
=> DCOS-8637: Remove flush-bottom from resource bar chart's panel options

src/js/constants/JobTableHeaderLables.js, src/js/events/MetronomeActions.js, src/js/pages/jobs/JobsTable.js, src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js, tests/_fixtures/metronome/jobs.json
The API introduced a change where the status property is removed and we
need to embed the history to grab the last run status.
Relevant tests are passing:
=> DCOS-8392 Update Jobs struct to get last run status from history

src/js/components/ManualBreadcrumbs.js
=> Fix breadcrumb item filter logic

src/js/components/TaskView.js
Bug fix for TaskTable checkboxes not updating when task table gets new tasks/loses tasks:
=> DCOS-8414: Recalibrate checkboxes when filtered tasks changes

src/styles/components/filter-bar.less
This PR introduces variables for the padding & margins on `filter-bar-item`. Vertical spacing should be the exact same, but the horizontal spacing now uses the `@button-collection-spacing` variable family.
After:
=> DCOS-8567: Use button-collection variables instead of custom spacing

src/js/components/AccessDeniedPage.js
Update documentation link and text:
Before the link was not working, now it points to where the enterprise and open documentation will appear
=> Update documentation link and text

src/styles/components/progressbar.less
Adding the animated progress bar for the `over-capacity` CSS state in the status progress bar.
=> DCOS-8479: Adding over-capacity animation on the css

src/styles/components/dropdown-menus.less
This is an intermediary fix for the "wide dropdown" so that it doesn't render off the viewport. A real fix needs to be introduced in `reactjs-components`, which I have documented here: https://mesosphere.atlassian.net/browse/DCOS-8991
Before:
After:
=> Fix wide dropdown width

src/js/components/ServiceDetailTaskTab.js, src/js/stores/MesosStateStore.js, src/js/stores/__tests__/MesosStateStore-test.js
Changing to use `DCOS_PACKAGE_FRAMEWORK_NAME` instead of determining the mesos framework name from `appId`
Here are all the tasks in mesos:
Before:
After:
=> Using service name in stead of creating mesos name

src/styles/layout/grid.less
This PR makes use of the `.make-row` mixin in Canvas, which just applies a negative horizontal margin with the provided variable. We had just forgotten to do this in the past, so when the column padding increased at `@screen-x-large`, the row's negative margin did not increase accordingly.
=> DCOS-8593: Use .make-row mixin for screen-x-large

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
The `JSON.stringify` function is dropping keys with `undefined` values. This pull request makes sure that no environment variable value is in this state.
=> DCOS-8978: Fixing bug that drops empty environment variables

src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/services/DeploymentsTab.js
Original bug report:
> Deployments shouldn't render till we have the list from the API	
> ![](https://cl.ly/2P3C223x1v0N/Screen%20Recording%202016-07-28%20at%2011.06%20AM.gif)
Implementation:
=> Show loading gif on deployments page

src/js/schemas/job-schema/General.js, src/js/utils/JobUtil.js
=> DCOS-8394 Group resources in job form modal

src/js/pages/jobs/JobDetailPage.js
Change the Jobs detail page dropdown menu to non-inverse style, to match the dropdowns in Services page.
=> DCOS-8905: Jobs detail dropdown style

npm-shrinkwrap.json, package.json
Changes in this update:
- Store util have been removed. Was no longer being used (https://github.com/dcos/mesosphere-shared-reactjs/pull/12)
- StoreMixin have stricter checking whether the lister details for components using it (https://github.com/dcos/mesosphere-shared-reactjs/pull/10)
=> Updating mesosphere-shared-reactjs to version 0.0.19

src/js/components/ConfigurationView.js, src/js/components/modals/ServiceFormModal.js, src/js/constants/ServiceConfig.js, src/styles/components/multiple-form.less
This adds support for the Unicon feature. It will lock you into JSON mode as soon as you provide a config which is not parseable in the form.
If you want to test this please ask me directly.
=> DCOS-8857 & DCOS-9112 & DCOS-9113 & DCOS-9111 Unicon support

npm-shrinkwrap.json, package.json
=> Version bump reactjs-components@0.14.0.bet-40

src/js/events/MesosSummaryActions.js
This will make sure to fall back to `mesos/summary` endpoint if the data from history server doesn't validate according to this crude test.
More will be done to validate the data that is received from the server later.
=> Adding crude test of history server data in MesosSummaryActions

src/styles/components/progressbar.less
Philip(p)s! I need your help...will this be a problem with the progressbars in the services page?
I'm fixing this because it was causing the disk progressbars in the Nodes page to look like the overcapacity ones.
See:
=> Fixes color for disk.

src/js/components/CosmosErrorMessage.js, src/js/components/__tests__/MesosLogView-test.js, src/js/components/modals/__tests__/InstallPackageModal-test.js, src/js/pages/task-details/__tests__/TaskDetail-test.js, src/js/pages/universe/__tests__/PackageDetailTab-test.js, tests/pages/universe/packages/PackagesTab-cy.js
Spelling error in the Cosmos error modal, thanks to @ssk2 for the report. 
I also fixed up the same error in some of the tests while I was at it.
=> Fix spelling of 'occurred'

src/styles/components/scrollbar/styles.less, src/styles/layout/page/styles.less
This fixes the Gemini Scrollbar content when native overlay scrollbars are enabled. The rest of `page/styles.less` still needs to be audited, but I'd like to wait until more of the components have been audited.
=> [CNVS Upgrade] Add flex properties for .page-body's scroll container

src/styles/components/badges.less
Related to #890 , adds the over-capacity animation to the legend dot too.
=> DCOS-8479: Adding over-capacity animation to the dot

src/js/components/CheckboxTable.js, src/js/pages/jobs/JobRunHistoryTable.js
Exclude the non-running `jobRuns` from being selected and stopped, which would produce a 404 error.
=> DCOS-8945 Allow excluding certain items from being selected in checkbox table

src/js/components/modals/ServiceFormModal.js
This removes the jsonDefinition from the serviceFormModal.
=> DCOS-9118: Refactor service form modal to only keep service in state

src/js/components/BreadcrumbSegmentLink.js, src/js/pages/universe/PackageDetailTab.js, src/js/pages/universe/__tests__/PackageDetailTab-test.js, src/js/routes/universe.js
This PR fixes a few things:
* Fix breadcrumb route to universe package.
* Allows passing any additional parameter to BreadcrumbSegmentLink through `this.props.route`
* Fixes request to fetch package description, the version was being accessed incorrectly.
=> Fix breadcrumb route to universe package.

src/js/components/ServiceForm.js
The `validateForm` hack committed in #868 is no longer necessary. 
Kill it with fire.
=> Remove duplicate validateForm hack

src/js/stores/VisibilityStore.js
The problem was that if you switched between dcos tab and another tab in your browser and back to dcos, we wouldn't clear the timeout and after 30 seconds `isInactive` would be set to false, halting all ajax requests.
ps. this was fun to debug.
cc/ @MatApple
=> Fixes visibility store so that it doesn't set isInactive as false when it is active.

src/js/components/SidebarFilter.js, src/styles/components/service-sidebar.less
This makes a bit more obvious the fact that a filter without items is disabled.
=> DCOS-8568: Making inactive filter items fade 50%

src/styles/components/scrollbar.less
This PR fixes a bug where the page component content (`.page-content`) wouldn't grow to fill its parent when the user's OS has native overlay scrollbars.
I tested it in Chrome, Firefox, Safari, and IE11/Edge, but this seemingly innocuous change has the potential to break scrolling so it's worth being tested by others.
On OS X, you can toggle the overlay scrollbars vs. "normal" scrollbars in System Preferences > General:
If you're using a mouse, set it to "when scrolling" and you'll get overlay scrollbars. If you're using a trackpad, set it to "Automatically..." or "when scrolling."
=> Fix hidden page content due to shrinking page content

CONTRIBUTING.md, package.json, webpack/webpack.config.babel.js, webpack/webpack.dev.babel.js
This PR introduces a script which disables eslint and `react-hot-loader`. This is necessary when using `npm link` with a local copy of `reactjs-components`.
Disabling eslint prevents linting the transpiled source, and disabling `react-hot-loader` is necessary due to our use of getters in `reactjs-components`. Read more about it here: https://github.com/gaearon/react-hot-loader/issues/131
=> Add checks for node environment variables for use with symlinked reactjs-components

package.json
Adjust the npm lint script to disable globbing (`set -f`) as this should be handled by eslint. I also adjusted it to only lint src/js by default.
=> Fix npm lint script

package.json
---
~~⚠️ The test fail due to linting errors which will be fixed by #975 and #977~~ Merged!
---
Adjust the npm lint script to disable globbing (`set -f`) as this should be handled by eslint to make it works in all environments. I also adjusted it to only lint `src/js` by default.
=> [Eslint] Fix npm lint script

.eslintrc
This PR removes jsx-quotes eslint rule and uses Airbnb's settings
=> [Eslint] Remove jsx-quotes eslint rule, use Airbnb's settings

src/js/components/Sidebar.js
Swap order of DC/OS sidebar icons to match the ordering in Enterprise.
=> DCOS-9023: Sidebar icon out of order

src/js/pages/services/ServicesTab.js
Avoids costly re-render of services tab when marathon store updates.
Before:
After:
=> Improve task table performance

src/js/components/SchemaForm.js, src/js/components/ServiceForm.js, src/js/schemas/service-schema/Networking.js, src/js/utils/FormUtil.js, src/js/utils/SchemaFormUtil.js, src/js/utils/__tests__/FormUtil-test.js
~~Related PR: https://github.com/dcos/dcos-ui/pull/561~~
~~This PR doesn't solve the whole problem, but makes it a little better, i.e. only happen for one field~~
This PR fixes a small issue, user would loose focus in the create service form when entering new ports.
=> Making sure we are not loosing focus in service form network tab

src/js/components/CollapsibleErrorMessage.js, src/js/components/CosmosErrorMessage.js, tests/pages/system/overview/components/AddRepositoryFormModal-cy.js
Here is the message displaying (as it was before):
However, now it has the appropriate classes on the element 😄 
It also adds a missing required field in the repository modal for an integration test
=> Bug fix: Universe error message integration tests

src/js/components/TaskTable.js, src/js/components/__tests__/TaskTable-test.js
Previously, task health status was being inferred from the presence of the Mesos state.json endpoint in `frameworks[].tasks[].statuses[].healthy`. This is not guaranteed to be present. Separately, task health and running status were being conflated such that where a task was in an unhealthy state (eg Killing) the Running state was being shown. 
This PR:
- introduces a fallback on the Marathon health checks where the Mesos task healthy property is not present
- adds a 'Healthy' and 'Unhealthy' label to the status column
- cleans up the state badges classes so that running and unhealthy do not conflict
This PR resolves https://dcosjira.atlassian.net/browse/DCOS-290
Before:
After:
_NB a separate bug is present in these screenshots where over-capacity tasks are counted twice. This is outside …
=> Show task health state in detail page

src/js/components/__tests__/ServiceInfo-test.js, src/js/structs/Framework.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js, src/js/utils/FrameworkUtil.js
Some service icons were missing. It turns out that some Applications carry their icons in their `DCOS_PACKAGE_METADATA` label even though they are not a Framework. And so we will generalise the Service struct (from which both Framework and Application inherit) to check for a metadata label when rendering an icon.
Original PR: https://github.com/dcos/dcos-ui/pull/949 caused a circular dependency, this PM avoids that problem.
=> DCOS-9054: Service icons not displaying

src/js/stores/SidebarStore.js
When rendering many dial chars, the Chart component listens to sidebar width change. If there's many charts, it'll throw a warning.
=> Fix max listeners limit.

src/js/components/modals/ServiceFormModal.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
The Service Form JSON view seems to remove empty (undefined, null) labels. This PR changes null and undefined values to an empty string `''` which works.
=> DCOS-9431: Add support for labels without a value

src/js/structs/ServiceTree.js
This fixes the volume filter on the service table. It wasn't showing services with defined volumes.
=> DCOS-9274: Fix volumes filter

src/js/components/ServicesTable.js, src/js/constants/Links.js, src/js/utils/ResourceTableUtil.js
This adds a link to the marathon docs which explains the status column in more detail.
=> DCOS-8081: Add Link to status documentation to the status column header

src/js/components/modals/ServiceFormModal.js
This disables the form if a vip config is provided which does not contain the current service id.
=> DCOS-9292: Prevent vip being overwritten by accident

src/js/components/modals/ServiceFormModal.js
As discussed here: https://github.com/dcos/dcos-ui/pull/995#issuecomment-242742619
I added the dynamic update of the info warning in the JSON mode if a config is not able to be rendered in the form.
=> [Service Form Modal]: Add info warning also on change

src/js/pages/task-details/TaskDetailsTab.js
Explicitly name task id, to avoid confusion.
=> Explicitly name task id, to avoid confusion

src/js/components/ServiceForm.js
[DCOS-9119](https://mesosphere.atlassian.net/browse/DCOS-9119)
The expected behavior is that when a user checks the "Discovery" box that the blue icon and the information that accompanies it would display.
Currently, it is always being displayed which is not expected. This PR ensures the info is only displayed when a discovery checkbox is checked.
=> Remove network discovery text when discovery not checked

src/js/utils/__tests__/SchemaUtil-test.js, tests/_fixtures/cosmos/package-describe.json
We are already using the `title` attribute in Universe Package configs, this PR is to affirm this to fixtures and tests.
=> Affirm Universe Package config `title`s are utilised with tests and fixtures

plugins/oauth/components/LoginPage.js
Adding security warning so developer knows to update authHost config when using different auth host domain. Previously silent, early abort from login flow led to confusion.
=> Add warning for auth0 config mismatch

src/js/pages/NetworkPage.js
Allows plugins to delay the rendering of the Network page by returning a Promise in a filter. Page will render when the Promise has resolved.
By default the page will not be delayed.
=> Add hooks for additional loading criteria to network page

src/js/components/CheckboxTable.js, src/js/components/TaskTable.js, src/js/components/__tests__/TaskTable-test.js, src/js/stores/MesosStateStore.js, src/js/stores/__tests__/MesosStateStore-test.js
this PR addresses the issue with a possibility to check and kill tasks that haven't been started by marathon. The issue is resolved by adding additional field `startedBy` with the name of a framework, i.e. `spark` that actually started the task, so we can use that information to filter out non-marathon tasks.
Additionally this PR fixes the way how CheckboxTable component renders the heading checkbox when there are disabled items.
=> DCOS-9285: Disable checkboxes for non-marathon tasks

npm-shrinkwrap.json, package.json, src/js/schemas/job-schema/Schedule.js, src/js/utils/SchemaUtil.js
---
~~⚠️ Is dependent on this reactjs-components feature: https://github.com/mesosphere/reactjs-components/pull/335~~ Merged. This PR is now updated with the new reactjs-components version 0.15.0-beta.1
---
This PR adds a help block for the cron input field
=> Add help block to cron job field

src/js/components/ServiceForm.js, src/js/schemas/service-schema/Networking.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
* Add service address documentation to the networking tab
* Rename discovery to load balanced 
💜  @jfurrow @mlunoe thanks a bunch for the `formElementClass` pointer
/cc @leemunroe
=> DCOS-9148: Improve networking tab usability

src/js/components/ComponentList.js, tests/_fixtures/unit-health/units.json
Previously, the Component Health widget was sorted in this way:
- Health
- Unhealthy
- Idle
- N/A
We want to expose the Unhealthy components, so now it is sorted:
- Unhealthy
- Healthy
- Idle
- N/A
=> DCOS-9356: Sort component health widget by health

src/js/components/modals/ServiceFormModal.js
This makes sure `ServiceFormModal` properly checks if the component should update.
This fixes a bug encountered when the form is in JSON edit mode. Previously, when a warning message is visible (ex. the JSON string contains unhanded attributes), the components updates on every character type, making Ace editor replace it's contents on every key press - effectively prohibiting further edit of it's contents.
=> Properly checking if error/warning messages have changed

src/js/constants/ServiceConfig.js
This adds framework fields from the state summary to the service config blacklist. To remove them from the service json in the service form.
=> DCOS-9604: Add Framework fields to service config blacklist

src/js/components/HealthBar.js, src/js/components/ServiceInfo.js, src/js/components/ServicesTable.js, src/js/components/__tests__/ServiceInfo-test.js
This PR does remove over capacity from the statusbar because the number was not clear to the user. There is now a text added next to the total task count if a service is over capacity.
Also the over capacity line is still in the tooltip.
over capacity:
within capacity:
/cc @leemunroe @silverem2
=> DCOS-9248: Remove overcapacity from bar

src/js/utils/ServiceUtil.js
This PR will make sure that the ipAddress field in the config is removed if the user selects a different option from the dropdown.
=> DCOS-9498: Remove ipAddress on network switch to HOST

src/js/components/ServiceForm.js, src/js/utils/ServiceUtil.js
Renames discovery to loadBalanced that was missed and ensures there's no port definitions when setting up a VIP.
=> Fixes network tab

src/js/schemas/service-schema/General.js, src/js/structs/Framework.js, src/js/structs/__tests__/Framework-test.js
With this PR we are adding TASKS_RUNNING for frameworks from the mesosSummary to a running Framework.
=> DCOS-9104: Add Tasks started by a framework to the taskList

src/js/events/MetronomeActions.js, src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
This changes the emebed parameter for the jobs request and we only request the history
summary from metronome now. This will remove a lot of overhead in request size for
clusters which are using a lot of jobs.
=> DCOS-8898: Change history embed with historySummary embed on jobs request

src/js/components/ServiceForm.js
Adjust `getExposeNetworkingCheckboxes` method to define a  checkbox prop
ID. Without this ID the`FormUtil.removePropID` method (used by the remove row button)  fails to remove the respective fields.
This change fixes an issue where it was impossible to remove endpoints
in the networking tab.
=> Properly set the expose network checkbox prop ID

src/js/components/SchemaForm.js, src/js/components/modals/__tests__/InstallPackageModal-test.js, tests/_fixtures/cosmos/package-describe.json
We are styling the nested schema form configs in the following way:
```
Tier 1 (which is currently the nav and the page header) should be an H2
Tier 2 an H3
Tier 3 an H4
Tier 4 an H5
```
Before:
After:
=> DCOS-8360: deeper nesting styles of schema forms

src/js/pages/task-details/TaskDetail.js, src/js/pages/task-details/__tests__/TaskDetail-test.js, src/js/stores/TaskDirectoryStore.js
This PR fixes a problem where the log for a file in a nested folder would never load.
This was due to the path not being updated when requesting a directory in a different path. This would in turn not emit events as the path stored vs. returned would be different
=> Updating innerPath as soon as we start polling for a new directory

src/js/components/modals/ServiceFormModal.js, src/js/pages/services/ServicesTab.js
_Not addressing pod-only problem, but is needed for a feature on the pods UI._
The `id=` property was causing some troubles on some new implementation that I am working on and it didn't look good eitherwise. Suggested a modification.
=> Removing id property from ServiceFormModal

src/js/components/ExpandingTable.js
This flag is useful when searching on the child elements of the `ExpandingTable` and you want to expand the entire table to make the items accessible. This should not discard the current selected item state.
=> Adding expandAll property on ExpandingTable

npm-shrinkwrap.json, package.json, src/js/schemas/job-schema/Labels.js, src/js/utils/FormUtil.js, src/js/utils/JobUtil.js, src/js/utils/__tests__/FormUtil-test.js
---
ℹ️ Related to this PR (for history): https://github.com/dcos/dcos-ui/pull/916
~~⚠️ Dependent on this PR: https://github.com/mesosphere/reactjs-components/pull/348~~
---
This PR fixes a bug where the model generation would not know which field was which (due to name/key mixup).
It makes use of the key option in Forms introduced in this PR https://github.com/mesosphere/reactjs-components/pull/348 to assign a separate key to duplicable (label) definitions, but keeping the name unique, so the add/remove functionality still works.
Before:
After:
This PR includes a reactjs-components update. The only change added since last release was this PR: https://github.com/mesosphere/reactjs-components/pull/348
=> Bug fix: using unique name and indexed key in schema forms, ref. DCOS-9699

src/js/components/modals/JobFormModal.js
This PR fixes a missing import in the JobFormModal file ~~from this PR: https://github.com/dcos/dcos-ui/pull/950~~
~~Specific commit: https://github.com/dcos/dcos-ui/pull/950/commits/4df93a7d81ace2262f486f34c258368ebc38e064~~
Apparently what happened is that the import was removed here: https://github.com/dcos/dcos-ui/commit/d0bab83745ce2346f5485219b195b913e8f07887 in the `feature/pods` branch, and then in master some more entries using the same function was added here: https://github.com/dcos/dcos-ui/pull/907
So when the `feature/pods` branch was rebased by me it added new uses of the function without having the import.
=> Adding missing import for cleanJobJSON

src/styles/components/status-dots/styles.less
Defining a status dot's size based on the `font-size` and `line-height` meant using decimal values for heights and widths. This resulted in oval-ish shaped status dots, because `border-radius` doesn't play nicely with decimal values. This PR defines static integer dimensions for all screen sizes.
Before:
After:
=> [CNVS Upgrade] Fix Status Dot border radius

src/js/components/FilterByService.js, src/js/components/FilterHeadline.js, src/js/components/FilterHealth.js, src/js/components/FilterInputText.js, src/js/components/HealthTab.js, src/js/components/JobSearchFilter.js, src/js/components/ServiceDetailTaskTab.js, src/js/components/ServiceSearchFilter.js, src/js/components/TaskView.js, src/js/pages/NodesPage.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/jobs/JobsTab.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/nodes/NodeDetailPage.js, src/js/pages/services/ServicesTab.js, src/js/pages/system/OrganizationTab.js, src/js/pages/system/RepositoriesTab.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthTab.js, src/js/pages/task-details/TaskLogsTab.js, src/js/pages/universe/InstalledPackagesTab.js, src/js/pages/universe/PackagesTab.js, src/styles/components/badges/styles.less, src/styles/components/icons/styles.less, src/styles/components/list/styles.less, src/styles/components/status-dots/styles.less
This PR removes a bunch of the `inverse` classes and properties that were applied throughout the app. You'll probably want to look at this with the changes to `badges` in this PR: https://github.com/dcos/dcos-ui/pull/1026/files
_The text input element sizes will be addressed by @ashenden in a future PR._
=> [CNVS Upgrade] Update styles & classnames for filter bars

webpack/webpack.dev.babel.js
https://github.com/erikras/react-redux-universal-hot-example/issues/616#issuecomment-159953813
Before:
<pre>
delta:dcos-ui ml (master)$ npm start
...
content is served from /Users/ml/Mesosphere/dcos-ui/build
<b>Time: 68228ms</b>
chunk    {0} index.js (main) 9.86 MB [rendered]
Child html-webpack-plugin for "index.html":
chunk    {0} index.html 200 kB [rendered]
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
<b>Time: 9482ms</b>
chunk    {0} index.js, 0.17c12013250a06570382.hot-update.js (main) 9.86 MB [rendered]
Child html-webpack-plugin for "index.html":
chunk    {0} index.html 200 kB
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
<b>Time: 3639ms</b>
chunk    {0} index.js, 0.6e5a4047e21c3640a600.hot-update.js (main) 9.86 MB [rendered]
Child html-webpack-plugin …
=> Use inline cheap source maps for development mode

plugins/tracking/__tests__/TrackingPlugin-test.js, plugins/tracking/hooks.js, src/js/stores/MetadataStore.js
This will give us the version of DCOS when errors are logged to TrackJS.
=> Version TrackJS errors.

src/js/utils/__tests__/ApplicationUtil-test.js
Refactor the tests using jasmine `clock` to fix reliability issues due to timeouts.
=> Fix  ApplicationUtil test reliability issues

src/js/components/CheckboxTable.js, src/js/components/TaskTable.js, src/js/components/__tests__/TaskTable-test.js, src/js/stores/MesosStateStore.js, src/js/stores/__tests__/MesosStateStore-test.js
Reverts dcos/dcos-ui#1021
Hey guys - This PR needs to be reverted as it's mutating data and it doesn't work when viewing the tasks table through the Nodes page. We need to rethink this solution so that we use a method on the struct or a Util to determine if the task was started through Marathon.
We'll likely reuse some of this code. Anyone feel free to give this another stab.
=> Revert "DCOS-9285: Disable checkboxes for non-marathon tasks"

src/js/components/ServiceDetailConfigurationTab.js, src/js/structs/Application.js, src/js/structs/ApplicationSpec.js, src/js/structs/Framework.js, src/js/structs/FrameworkSpec.js, src/js/structs/__tests__/Application-test.js, src/js/structs/__tests__/ApplicationSpec-test.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
This PR separates `Application` struct to `Application` + `ApplicationSpec`.
The first is used when we need to inspect the *status of a running instance*, while the latter is used when we *create or edit* an application.
=> [Pods] DCOS-9613: 1/2 Separating Application to ApplicationSpec

src/js/components/ServiceDetail.js, src/js/components/ServiceDetailConfigurationTab.js, src/js/components/modals/ServiceFormModal.js
---
~~⚠️  Depends on #1052~~ Merged
---
This PR makes `ServiceFormModal` operate on service spec and not on the service instance itself (that is now considered to carry the status information)
=> [Pods] DCOS-9613: 2/2 Adapting ServiceFormModal to work with ServiceSpec

npm-shrinkwrap.json, package.json
The `0.15.0-beta.5` version just includes the adjusted styles for `.content-editable` elements. https://github.com/mesosphere/reactjs-components/pull/350
=> Version bump reactjs-components 0.15.0-beta.5

src/js/components/ServiceDetailConfigurationTab.js, src/js/components/modals/ServiceDestroyModal.js, src/js/components/modals/ServiceFormModal.js, src/js/components/modals/ServiceRestartModal.js, src/js/components/modals/ServiceScaleFormModal.js, src/js/components/modals/ServiceSuspendModal.js, src/js/events/MarathonActions.js, src/js/events/__tests__/MarathonActions-test.js
Adjust the service actions to support pods. I added mocked versions to enable proper testing.
_Please excuse the rather large number of changes. I figured it might be easier to land this with only one PR instead of a number smaller ones as I'm on vacation and wouldn't be able to do the rebase dance._
=> [Pods] Adjust service actions to support pods

webpack/webpack.config.babel.js, webpack/webpack.dev.babel.js
This PR moves the webpack `eslint` loader to `webpack.dev.babel`. In production, `eslint` is run before the assets are compiled via a separate npm script.
@mlunoe and I paired on this.
=> Move eslint to dev webpack build

src/js/components/CheckboxTable.js, src/js/components/TaskTable.js, src/js/components/__tests__/TaskTable-test.js, src/js/events/MesosStateActions.js, src/js/utils/MesosStateUtil.js, src/js/utils/__tests__/MesosStateUtil-test.js
In this PR I implemented the after merge comments from @mlunoe https://github.com/dcos/dcos-ui/pull/1021 regarding the place of the scheduler name assigning logic. So the logic has been moved to the `MesosStateActions` as a central place, where the data comes in into the app, therefore the data will be consistent across the whole app.
Works on the Services page and on the Nodes page as pointed out by @rcorral in https://github.com/dcos/dcos-ui/pull/1066
I also moved the CheckboxTable fix as well.
=> DCOS-9285: Move scheduler name assignment to MesosStateActions

src/js/components/PodDetail.js, src/js/components/PodHeader.js, src/js/components/modals/ServiceDestroyModal.js, src/js/components/modals/ServiceScaleFormModal.js, src/js/components/modals/ServiceSuspendModal.js, src/js/constants/PodActionItem.js
---
~~⚠️  Depends on #1071~~
~~⚠️  Depends on #1070~~
---
This PR introduces the action buttons and links them to the appropriate pod-specific store actions.
_WIP: Using this PR as a base in order to integrate the `ServiceFormModal` in a separate PR_
=> [Pods] Adding pod actions to pod-specific views

src/js/components/PodContainerTerminationTable.js, src/js/components/PodDebugTabView.js, src/js/components/PodDetail.js, src/js/structs/Pod.js, src/js/structs/PodContainerTerminationHistory.js, src/js/structs/PodTerminationHistory.js, src/js/structs/PodTerminationHistoryList.js, tests/_fixtures/marathon-pods/groups.json
---
~~⚠️ Requires #1071 to be merged~~ Merged!
---
This PR implements the DebugTab view. It shows the time of the last change, and it also extracts last termination information according to this spec: https://github.com/mesosphere/marathon/blob/feature/pods/docs/docs/rest-api/public/api/v2/types/podStatus.raml#L217
=> [Pods] Fleshing out PodDebugTabView

src/js/components/Panel.js, src/js/components/__tests__/Panel-test.js
Velocity won't properly report the status of the unit tests because this still relies on the `cnvs-upgrade/master` branch of both `reactjs-components` and the plugins repository, but you can see them passing locally:
=> [CNVS Upgrade] Fix broken unit tests

src/js/events/MarathonActions.js
Adding `embed=group.pods` on the `MarathonActions` in order to fetch pod-related details.
=> [Pods][Testing] Adding embed=group.pods

src/js/components/ConfigurationView.js, src/js/utils/MarathonConfigUtil.js, src/js/utils/ServiceConfigUtil.js, src/js/utils/__tests__/ServiceConfigUtil-test.js
Extracting utility functions from ConfigurationView to MarathonConfigUtil. To slim down the component and improve code reusability. MarathonConfigUtil is going to be used in Pods configuration view as well. 
Refactoring has been done by @wavesoft had to split some commits in order to slice #1111 in smaller yet meaningful chunks.
Part of the ticket: https://mesosphere.atlassian.net/browse/DCOS-9823
=> [Pods] Extract MarathonConfigUtil from ConfigurationView

npm-shrinkwrap.json, package.json, src/js/components/DescriptionList.js, src/js/pages/nodes/NodeDetailTab.js
This PR is simply adds the pure render mixin to the NodeDetailTab and its only child, DescriptionList.
=> [Nodes Page] Purify node detail view

src/js/components/TaskTable.js, src/js/components/__tests__/TaskTable-test.js
This PR restricts selection of a completed task in the TasksTable and you can’t kill a task if you can’t select it :)
Ticket: https://mesosphere.atlassian.net/browse/DCOS-9906
=> DCOS-9906: Disallow completed task selection

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
---
ℹ️ This fix is for 1.8 only as the respective components have changed drastically. Please see #1136 for the respective master fix.
---
Adjust the service util to use the provided host port data from the JSON definition for `user` networks.
Fixes DCOS-9948
=> DCOS-9948 (1.8): Fix host port handling for `user` network

src/js/schemas/service-schema/Networking.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
--- 
ℹ️ This fix is for 1.8 only as the respective components have changed drastically. Please see #1134 for the respective `master` fix.
⚠️ Don't merge this PR until the network team has verified that this behavior is correct!
---
Add a hidden host and service port field to the service network schema and adjusted the service util to keep the host and service port data from the JSON definition for bridged networks.
Fixes DCOS-9937
=> DCOS-9883 (1.8): Fix service form port handling

src/js/components/modals/ServiceFormModal.js
Adjust the service form JSON toggle handler method to use the current service  spec instead of the original one as we otherwise lose changes from the JSON editor.
/closes DCOS-9921
=> DCOS-9921: Fix service form JSON toggle spec handling

src/js/components/ServicesTable.js, src/js/components/__tests__/ServicesTable-test.js, src/js/structs/Application.js, src/js/structs/__tests__/Application-test.js
Sum up the resources in the service table to represent the actual resources needed and not the once configured for an application.
=> DCOS-9955: Sum resources in the services table

src/styles/components/pod-instances-table.less, src/styles/index.less
This PR adds `vertical-align: top` to the pod-instances-table cells. I decided to go with having `td` in `.less` over adding a default class like `columns-select` to `ResourceTableUtil` because `ResourceTableUtil` is being used like everywhere.
https://mesosphere.atlassian.net/browse/DCOS-9893
*Before* checkbox and version are vertically aligned in the middle:
*After* checkbox and version are vertically aligned at the top:
=> [Pods] DCOS-9893: Align pod instances table cells at the top

src/js/schemas/service-schema/Networking.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
---
ℹ️ This fix is for `master` only as the respective components have changed drastically. Please see #1133 for the respective 1.8 fix.
⚠️ Don't merge this PR until the network team has verified that this behavior is correct!
---
Add a hidden host and service port field to the service network schema and adjusted the service util to keep the host and service port data from the JSON definition for bridged networks.
Fixes DCOS-9937
=> DCOS-9883 (master): Fix service form port handling

npm-shrinkwrap.json, package.json
---
ℹ️ Related to this PR: https://github.com/dcos/dcos-ui/pull/1073
---
Only change in this release is the removal of GetSetMixin, which is not being used anywhere: https://github.com/dcos/mesosphere-shared-reactjs/pull/20
=> Updating mesosphere-shared-reactjs to version 0.0.23

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
---
ℹ️ This fix is for `master` only as the respective components have changed drastically. Please see #1137 for the respective 1.8 fix.
---
Adjust the service util to use the provided host port data from the JSON definition for `user` networks.
Fixes DCOS-9948
=> DCOS-9948 (master): Fix host port handling for `user` network

src/js/components/PodContainerSpecView.js
This PR fixes the situation when marathon provides null instead of not providing anything for an optional property.
=> [Pods] Replace defaults with an explicit check

src/js/components/ServerErrorModal.js, src/js/components/modals/ServiceActionModal.js, src/js/components/modals/ServiceDestroyModal.js, src/js/events/MarathonActions.js, src/js/stores/MarathonStore.js
It looks like when destroying a service, we never properly checked for errors in order to prompt for force-destroy. This PR:
* Introduces the `force` option to `destroyGroup` and `destroyService`.
* Makes the error message a bit more generic
=> DCOS-9995: Adding support for force=true on destroy

npm-shrinkwrap.json, package.json
The update to `stylelint-config-dcos` fixes a dependency that was erroneously marked as a `devDependency`.
=> [CNVS Upgrade] Update stylelint config to v0.0.2

src/js/components/PodContainerSpecView.js
This PR addresses the differences between app port definitions and pod container endpoints. It seems like they used to be pretty similar that’s why we went ahead and extracted `ServiceConfigUtil`. But they have recently changed.
Keeping in mind those differences we might want to roll back the `ServiceConfigUtil .getPortDefinitionGroups` extraction.
The other reason why I decided not to implement links to load balanced endpoints is because there seems to be a bug in the way how we handle groups of apps/pods I discovered and will file in Jira.
=> [Pods] Display container endpoints

src/js/components/PodInstancesTable.js, src/js/components/__tests__/PodInstancesTable-test.js
Removing checkboxes from `PodInstancesTable`. However I am keeping the logic of the `CheckboxTable` since this is something we will roll-back into when we have the per-instance kill functionality.
=> [Pods] DCOS-9986: Using Table instead of CheckboxTable on PodInstancesTable

src/js/components/PodInstancesTable.js, src/styles/components/pod-instances-table.less
This PR adds a link to a task's logs.
ℹ️  when testing it please note that Logs view seems not to be working in general. So you don't see any logs under the Log tab.
https://mesosphere.atlassian.net/browse/DCOS-9894
/cc @leemunroe
=> [Pods] Add quick link to logs to task rows

src/js/structs/Deployment.js, src/js/structs/__tests__/Deployment-test.js
Adjust `Deployment` struct to include affected pods in deployment list.
Closes DCOS-10010
=> [Pods] DCOS-10010: Include affected pods in deployment list

src/js/components/PodInstancesTable.js, src/js/structs/PodContainer.js, src/js/structs/__tests__/PodContainer-test.js
This PR is a temporary solution until https://mesosphere.atlassian.net/browse/DCOS-10098 is addressed. It will automatically switch on using the new data when they become available.
In detail: We encountered a case were a pod contains a container not part of the `spec` (ex. you edit the spec and remove a container, but it is still present in the instances for some time). Therefore, we were not able to get the resource information from the spec and the UI was failing. This PR uses by default the `resources` information from the container itself and for the transient period until the issue is addressed it will also use the information from the spec if available.
=> [Pods] DCOS-10100: Getting resource details from spec when available

src/js/events/TaskDirectoryActions.js, src/js/events/__tests__/TaskDirectoryActions-test.js, src/js/utils/MesosStateUtil.js, src/js/utils/__tests__/MesosStateUtil-test.js
Introduce and integrate a new util to get the task directory from Mesos state which is capable of handling nested task groups (pods).
Closes DCOS-9984
=> [Pods] DCOS-9984:  Adjust task directory path handling to support pods

src/js/components/PodHeader.js, src/js/structs/Pod.js
Showing the deploying animation on the health bar in the pod detail view, as already shown like so on the services table list.
=> [Pods] DCOS-10076: Pod health bar inconsistency between services table and pod detail

src/js/components/PodDebugTabView.js
The debug tab renders incorrectly the `lastChanged` instead of `lastUpdated` in the Last Changes -> Configuration label. Fixed with this PR.
=> [Pods] Using lastUpdated instead of lastChanged

src/js/components/PodInstancesTable.js, src/styles/components/pod-instances-table.less
With this PR less important columns in the pod's instances table will be hidden on the smaller screens as we do for the regular app tasks table. In addition to that I introduced min-/max-width to make use of the empty space as stated in the ticket.
=> [Pods] DCOS-9895: Have Pod and task tables use up available space before truncating

src/js/utils/MesosStateUtil.js
The marathon task response is different between a `pod` and an `application`. This PR makes `getTasksFromVirtualNetworkName` aware of the pod structure in order for them to appear on the Virtual Networks table:
For reference, the differences on the task responses are:
Pods:
App:
=> [Pods] DCOS-10089: Including pods on getTasksFromVirtualNetworkName

src/js/components/PodInstancesTable.js, src/js/components/__tests__/PodInstancesView-test.js, src/js/structs/PodInstance.js, src/js/structs/__tests__/PodInstance-test.js
Making sure we always show the total count of resources, as received from marathon (instead of summing-up the current values of the view, ex. when a filter is applied).
=> [Pods] DCOS-10099: Getting total resources from instance information

src/js/components/PodNetworkSpecView.js
This PR addresses the issue of using `network` as `labels` because of a bug in destructuring.
=> [Pods] DCOS-10183: Fix network labels destructuring

src/js/structs/ServiceTree.js
This bug addresses an issue were pods inside groups were not visible when the `Pods` filter was active on the services list.
=> [Pods] DCOS-10180: Recursively showing pods in groups

src/js/components/modals/ServiceFormModal.js
This PR moves the JSON-only warning message from the `ServiceFormModal` header inside a tooltip in the JSON toggle button.
=> DCOS-10087: Replacing warning message with toggle button tooltip

src/styles/components/scrollbar/styles.less
This PR fixes the scrollbar behavior when native overlay scrollbars are used.
This is fixed in this PR: https://github.com/dcos/dcos-ui/pull/1157 but even when that merges, the new components won't be implemented.
Before:
After:
=> [CNVS Upgrade] Fix native overlay scrollbars

src/js/components/DescriptionList.js
This fixes the `DescriptionList` classname discrepancy, but there's an `!important` in CNVS that will cause these to look misaligned still. I submitted a PR to CNVS to fix that here: https://github.com/mesosphere/canvas/pull/27
=> [CNVS Upgrade] Update DescriptionList flex classname

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
---
ℹ️ This fix is for 1.8 only please see #1213 for respective master fix.
---
Adjust the service util to always use the provided service port data from the JSON definition.
Fixes DCOS-10394
=> DCOS-10394 (1.8): Adjust util to use the provided service port

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
---
ℹ️ This fix is for master only see #1212 for the respective 1.8 fix.
---
Adjust the service util to always use the provided service port data from the JSON definition.
Fixes DCOS-10394
=> DCOS-10394 (master): Adjust util to use the provided service port

src/js/components/PodInstancesView.js, src/js/components/ServiceDetail.js, src/js/components/ServiceDetailTaskTab.js, src/js/components/ServiceInfo.js, src/js/components/ServicesTable.js, src/js/components/TaskView.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceInfo-test.js, src/js/constants/TaskTableHeaderLabels.js
This PR addresses task naming issues:
* On the collection view `Tasks` are now called `Instances` on the pods (I don't have a large enough screen to get a screenshot of this)
* On the pod instance detail view, the filter header shows `Showing X of X Instances` instead of tasks.
=> DCOS-9891: Renaming Tasks to Instances in pods

src/js/components/TaskTable.js
Don't cache the task log cells as otherwise the links will all point to the same task detail.
Closes DCOS-10443
=> DCOS-10443: Deactivate task log cell caching

src/js/components/PodInstancesView.js, src/js/components/charts/ResourceChart.js, src/js/pages/nodes/NodeDetailTaskTab.js
`inverseStyle` is `false` in these components, which is now what we'd like to use, so I've removed these props to rely on the defaults.
=> [CNVS Upgrade] Relying on inverseStyle property defaults

src/styles/components/tooltip/styles.less, src/styles/layout/styles.less, src/styles/variables/variables-z-index.less
This PR re-enables the tooltip and sets the `z-index` properly.
This PR needs to merge before tooltips will be visible in modals: https://github.com/dcos/dcos-ui/pull/1147
=> [CNVS Upgrade] Fix tooltip styles

src/styles/components/dropdown-menus/styles.less, src/styles/variables/variables-z-index.less
This PR ensures that the z-index of the dropdown is above the modal.
This is in anticipation of this change to reactjs-components: https://github.com/mesosphere/reactjs-components/pull/367
=> [CNVS Upgrade] Fix dropdown menu z-index

src/js/components/PodInstancesTable.js, src/js/components/PodInstancesView.js, src/js/components/PodViewFilter.js, src/js/components/__tests__/PodInstancesTable-test.js
This PR re-enables the checkboxes on the `PodInstanceTable` and it also properly handles the event to show the `Kill` and `Kill and Scale` buttons.
(Note that the `scale` option will be available soon: https://mesosphere.atlassian.net/browse/DCOS-10110 )
=> [Pods] DCOS-10108 [1/3]: Adding support for onSelectionChange on the instances table

src/js/components/ServicesTable.js, src/styles/content/tables/styles.less
This PR fixes the icons in the `ServicesTable`. It should look something like this when the icon color PR and `table-cell-flex-box` PRs get merged...
=> [CNVS Upgrade] Fix ServicesTable hover icons

src/js/components/ConfigurationView.js, src/js/utils/Util.js, src/js/utils/__tests__/Util-test.js
With this PR we will be displaying a docker container port mappings like this:
⚠️  new `Util.filterEmptyValues` has been added. That function removes keys with empty values from an Object using `ValidatorUtil.isEmpty`. All the usages will be migrated in a separate PR.
=> DCOS-9918: Improve containers port mapping

src/js/components/PodInstancesTable.js, src/js/components/PodInstancesView.js, src/js/stores/MesosStateStore.js, src/js/stores/__tests__/MesosStateStore-test.js, src/js/structs/Pod.js, src/js/structs/Service.js, src/js/structs/__tests__/Pod-test.js, src/js/structs/__tests__/Service-test.js, src/js/utils/MesosStateUtil.js, src/js/utils/PodUtil.js, src/js/utils/__tests__/MesosStateUtil-test.js, src/js/utils/__tests__/PodUtil-test.js, src/js/utils/__tests__/fixtures/MesosStateWithHistory.js
This PR uses the mesos state endpoint to extend the list of instances in the `PodInstancesView` to include completed instances.
=> [Pods] DCOS-10321: Including completed pod instances on summary view

src/js/components/PodInstancesView.js
This makes sure an empty action won't reach the `KillPodInstanceModal` by separating the `action` from the `open` state into two separate state variables.
=> [Pods] DCOS-10592: Ensuring KillPodInstanceModal action is always defined

src/js/components/ServiceDetailConfigurationTab.js, src/js/components/ServiceSpecView.js, src/js/components/__tests__/ServiceDetailConfigurationTab-test.js, src/js/components/__tests__/ServiceSpecView-test.js
Renaming `ConfigurationView` to `ServiceSpecView` in order to be consistent with the naming used on `PodSpecView`
=> DCOS-9919: Renaming ConfigurationView to ServiceSpecView

src/js/components/PodInstancesTable.js
This PR disables row items on pod instances that are not running.
=> [Pods] DCOS-10597: Hiding checkbox on non-running instances

src/styles/components/status-bar/styles.less, src/styles/components/status-dots/styles.less, src/styles/components/typography/styles.less
This PR uses light colors for status bars & dots.
Examples (the text may not match the color status in these screenshots):
=> [CNVS Upgrade] Fix dark status bar & dot backgrounds

src/js/components/NewPage.js, src/js/components/NewPageBody.js, src/js/components/NewPageHeader.js, src/js/components/NewPageHeaderActions.js, src/js/components/NewPageHeaderBreadcrumbs.js, src/js/components/NewPageHeaderTabs.js, src/styles/components/icons/styles.less, src/styles/components/list/styles.less, src/styles/components/page-header/styles.less, src/styles/layout/page-body/styles.less, src/styles/layout/page-header/styles.less, src/styles/layout/page/styles.less
This PR introduces the `NewPage*` components (to be renamed to ~~`New`~~`Page*` later).
In the new modularized UI, the `container` components will determine which data is available to each `PageHeader` component. Until then, this will not be implemented to avoid unnecessarily reworking our previous components.
Here's how I'm proposing `PageHeader`'s API will look:
```jsx
<PageHeader
actions={[
{
className: 'button-primary',
clickHandler: () => console.log('hi'),
label: 'Open Service'
},
{
className: 'button-stroke',
clickHandler: () => console.log('hello'),
label: 'Scale'
}
]}
breadcrumbs={[
{
iconID: 'services',
label: 'Services',
submenu: [
{
iconID: 'services',
label: 'Services',
routeName: 'services-overview'
},
{
label: 'Deployments',
routeName: 'services-deployments'
}
]
},
{
label: …
```
=> [CNVS Upgrade] Introduce new PageHeader components

plugins/banner/hooks.js, src/js/components/NodesTable.js, src/js/components/ServicesTable.js, src/js/components/SidebarFilter.js, src/js/components/SidebarLabelsFilter.js, src/js/components/TaskStatsTable.js, src/js/components/TaskTable.js, src/js/pages/services/DeploymentsTab.js, src/js/utils/ResourceTableUtil.js, src/styles/layout/overlay.less
These responsive classes are named incorrectly in the published version of CNVS. I submitted two PRs to CNVS to fix them, one of which has already merged. I don't currently have access to publish the NPM module. So if you'd like to test this, you'll need to `npm link` this branch of CNVS: https://github.com/mesosphere/canvas/pull/29
This PR updates all of the `hidden-*` classes. It's not exactly a one-to-one update, due to the following:
1. All screen sizes were renamed in CNVS, so `mini` became `small`, `small` became `medium`, `medium` became `large`, and `large` became `jumbo`.
2. Previously `hidden-small` and `hidden-medium` would hide elements only within the range of that breakpoint.
3. Previously `hidden-mini` hid elements at `mini` and below, and `hidden-large` hid elements at …
=> [CNVS Upgrade] Fix hidden-* classes

src/styles/vendor/cnvs/components/form/form-control/variables.less, src/styles/vendor/cnvs/styles.less
This PR assigns default CNVS `form-control-height-*` variables to the `button-height-*` variables.
=> [CNVS Upgrade] Fix input element height

src/styles/components/detail-view-header/styles.less
This PR is from a missing commit (my mistake) which has been on my `frankenstein` branch, but not `cnvs-upgrade/master`.
It does the following:
1. Moves the border to the inside the `DetailViewHeader` component
2. Stacks the border underneath the `.menu-tabbed`
3. Removes the bottom margin of the `.menu-tabbed` and adds top margin.
=> [CNVS Upgrade] Fix tabs in DetailViewHeader

src/js/components/ServiceSidebarFilters.js, src/js/components/ServicesTable.js, src/styles/components/service-table/styles.less
This helps match the behavior of the current behavior of the `ServicesTable` and `ServiceSidebarFilters`. It's still not exactly the same due to the behavior of the navigation sidebar, but that will be addressed in a future PR.
=> [CNVS Upgrade] Improve ServicesTable responsiveness

plugins/nodes/src/js/components/NodesGridView.js, plugins/nodes/src/js/components/NodesTable.js, plugins/nodes/src/js/pages/NodesOverview.js, plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js, plugins/nodes/src/js/pages/nodes/nodes-grid/NodesGridContainer.js, plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js, plugins/nodes/src/js/routes/nodes.js, src/js/mixins/QueryParamsMixin.js, src/js/mixins/__tests__/QueryParamsMixin-test.js
⚠️  This PR depends on #1218
This PR:
- introduces routing for the nodes page filters
- separates the node table and node grid views into container and component
~~Testing this PR will require the `cnvs-upgrade` branch in `reactjs-components` checked out and linked locally, and use of the `REACT_JS_COMPONENTS_LOCAL=true` EV.~~
=> [Nodes Page] modularize the nodes overview page

plugins/nodes/src/js/components/HealthTab.js, src/js/components/FilterBar.js, src/js/components/FilterHeadline.js, src/js/components/UnitHealthDropdown.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/units-health-node-detail/NodeInfoPanel.js, src/js/pages/system/units-health-node-detail/UnitsHealthNodeDetailPanel.js
⚠️ This PR depends on #1218
This PR separates the tabs in the nodes detail page into container and component. 
~~Testing this PR will require the `cnvs-upgrade` branch in `reactjs-components` checked out and linked locally, and use of the `REACT_JS_COMPONENTS_LOCAL=true` EV.~~
=> [Nodes Page] Nodes detail page

src/js/structs/ServiceTree.js
Return the matching service instance instead of creating a new one using the abstract service struct.
Fixes DCOS-10624
=> DCOS-10624: Adjust get service by task id getter

src/js/components/PodInstancesTable.js, src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js
The DCOS change event is fired whenever one of the depended stores (e.g. Marathon) fires a change event; this results in an unnecessarily high amount of change events due to the unregular nature of those updates.
This PR introduces methods to debounce change event calls (max 4x per second), which significantly improves the overall performance.
_Please note that we besides reducing the number of change event calls also need to address the high number of network request as well as the large number of stacked calls._
**Before**
**After**
=> Debounce DCOSStore events

src/js/utils/JestUtil.js
This PR trims the output of `JestUtil.Trimming`, since on tests we don't really care about heading/tailing spaces.
=> JestUtil: Trimming mapTextContent result

src/js/constants/ExecutorTypes.js, src/js/utils/MesosStateUtil.js, src/js/utils/__tests__/MesosStateUtil-test.js
Align the util with the latest Mesos API advancements as the "pod" task data changed which resulted in wrong paths. It also no longer necessary to iterate over the list of tasks as we already have all the bits to construct the paths.
Closes DCOS-10807
=> Adjust the Mesos task path util

src/styles/components/expanding-table/styles.less
The expanding table relies on consistent `line-height` to render these items in "rows." Thus we need to enforce `white-space: nowrap` and apply a specific `line-height` until a better solution exists (ie. the `ExpandingTable` actually renders additional rows when a row is expanded).
The `inline-block` on the `a` tags resulted in extra whitespace being rendered around the element, whereas the default (`inline`) does not result in the extra whitespace. This change doesn't seem to cause any problems wth either instance of `ExpandingTable`, so I just removed it.
#1261 needs to merge before you'll be able to expand any elements in the PodInstances table.
Before:
After:
=> [CNVS Upgrade] Fix expanding table styling

src/js/components/CollapsingPanel.js, src/js/components/CollapsingPanelContent.js, src/js/components/CollapsingPanelHeader.js, src/js/components/__tests__/CollapsingPanel-test.js, src/styles/components/panel/collapsing/styles.less, src/styles/components/panel/collapsing/variables.less, src/styles/index.less
This implements a very rudimentary collapsing panel, for use in the service create workflow.
I didn't invest any energy to make it match the mockups perfectly because apparently the mockups are not final. This just gives the developers something to work with.
=> [CNVS Upgrade] Introduce the collapsing panel component

src/js/utils/JestUtil.js
This PR introduces the `JestUtil. mockTimezone` function that can be used to provide the default timezone to be used by the `Date` object.
(Since unfortunately `jest.clock` does not provide this functionality)
=> JestUtil: Adding mockTimezone

plugins/services/src/js/components/PodInstancesTable.js
This PR removes unnecessary classes in the `Link` elements and adds the proper classes for the desired styling.
Before:
After:
=> [CNVS Upgrade] Fix link styles in PodInstancesTable

src/js/events/MarathonActions.js
Fixing a bug with the `Kill` pod instance button. Apparently:
* ~~The pod spec is wrong, the correct endpoint is `/{id}::instance` (without tailing `s`)~~ fixed in marathon 1.4.0-snap16
* The pod `id` is actually a full path, without the heading slash. It should be injected as a URL component, without escaping
__Hold merge:__ Until marathon fixes the endpoint to `::instances` again.
=> [Pods] DCOS-10594: Fixing killPodInstance endpoint

src/js/utils/MesosStateUtil.js, src/js/utils/__tests__/MesosStateUtil-test.js
This PR makes sure that the pod instances composed from `completed_tasks` have the correct ID.
Previously:
Now:
=> [Pods] Properly composing instance id

src/js/structs/ApplicationSpec.js, src/js/structs/__tests__/ApplicationSpec-test.js
Make sure that the `ApplicationSpec` health check getter returns "cloned" objects so that no one is accidentally mutating them. This change resolves an issue where the service form cancel button isn't working due to unwanted mutations.
Closes DCOS-10421
=> DCOS-10421: Adjust the Spec health check getter

src/js/components/modals/FullScreenModal.js, src/styles/components/modal/full-screen/styles.less, src/styles/components/modal/styles.less
This PR fixes a bug I introduced in https://github.com/dcos/dcos-ui/pull/1257 wherein the modals stopped rendering the Gemini scrollbar when appropriate.
By giving the property `display: flex` to all `.modal-body-wrapper` elements, it meant the child of `.modal-body-wrapper` (`.modal-body`) had the same height as its parent. This breaks the modal's logic which compares the height of these two elements to determine when to render Gemini.
=> [CNVS Upgrade] Fix modal body content flex properties

plugins/services/src/js/schemas/service-schema/Networking.js, src/js/components/SchemaForm.js, src/styles/components/form-elements/styles.less, src/styles/components/multiple-form/styles.less
This PR fixes some of cosmetic issues with the new Service Create modal.
* Introduce temporary hacks to reduce the padding on these input fields and make them usable. Between the larger padding on input fields, the checkbox label being all caps, and larger padding on the modal itself, some of the input fields were too narrow.
* Applies `button-narrow` to the delete button for these duplicable rows.
* Moves the border of the tabs to an inset box-shadow so that the right edge of the active indicator on the tabs renders on top of the border.
Before:
After:
=> [CNVS Upgrade] Service Create modal touchup

plugins/services/src/js/services/ServicesContainer.js
This PR fixes the regex for the Services sidebar sub-menu item.
Before (when Deployments was active, Services also appeared active):
After:
=> [CNVS Upgrade] Fix services sidebar active test

src/js/components/AlertPanel.js
This PR moves the AlertPanel's title into the content are of the panel itself. This gives space between the icon and title with the content area's padding, and then gives space between the heading and the content with the heading's margin.
=> [CNVS Upgrade] Move AlertPanel title to panel's content

src/styles/components/menu-tabbed/styles.less
This PR fixes a bug I introduced with my vertical tabs. Both vertical and horizontal tabbed menus need their children to have a bottom margin of 0.
=> [CNVS Upgrade] Fix bottom-margin on tabs

plugins/nodes/src/js/components/NodesGridView.js, plugins/nodes/src/js/pages/nodes/nodes-grid/NodesGridContainer.js, src/js/components/charts/ResourceBarChart.js, src/styles/components/charts/styles.less, src/styles/components/nodes-grid-view/styles.less
This PR fixes up the Nodes view:
* I fixed the double padding between the panel header and the panel content in the `ResourceBarChart`
* I fixed the dark graph colors in the nodes grid view
* I moved the width and margin properties of the nodes grid sidebar to the sidebar itself rather than random children (it was confusing)
* I fixed some erroneously defined transition properties, so toggling the task list will transition as intended
* I replaced the old, yucky, native `input` checkbox with the new, yummy, fancy checkbox from reactjs-components.
The `FilterHeadline` margins seem a little tight, but that's everywhere in the app, so I'll address that in a future PR.
=> [CNVS Upgrade] Fix up the nodes view

src/js/constants/TransactionTypes.js, src/js/structs/Transaction.js, src/js/structs/__tests__/Transaction-test.js
This is adding the support of type validation in the `Transaction`s 
I choose to use `Symbols` as values over `Strings` since they are unique and can not produce bugs because we just pass in Strings. 
If a invalid type is added a TypeError will be thrown, which should give enough information.
About the `DEL` type, this type is currently just in there for testing purposes it might be that this will be removed/replaced at a later time.
=> Validation of batch types

src/js/structs/Transaction.js, src/js/utils/ParserUtil.js, src/js/utils/__tests__/ParserUtil-test.js
This adds a ParserUtil which contains a function named combineParsers with this function it is possible to create a composable set of parsers which will return a flat list of items. In our use case this will be a set of transactions.
The util can be used like this:
```JS
const parser = ParserUtil.combineParsers([
function (state) {
return {
type: SET,
path: 'id',
value: state.id
},
function (state) {
return {
type: SET,
path: 'cmd',
value: state.cmd
};
}
]);
const appDefinition = {
id: 'test',
cmd: 'sleep 100;'
};
console.log(parser(appDefinition));
// Will resolve into: 
// [
//   {
//     type: SET,
//     path: 'id',
//     value: 'test'
//   },
//   {
//     type: SET,
//     path: 'cmd',
//     value: 'sleep 100;'
//   }
// ]);
```
A more complex example with some nesting is also …
=> Add Parser Util

src/js/pages/DashboardPage.js, src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/__tests__/JobsTab-test.js, src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/jobs/JobsTab.js, src/js/pages/services/DeploymentsTab.js, src/js/pages/services/ServicesTab.js, src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js
---
⚠️  *This fix probably also needs to land in 1.9*
---
Rename the `dataProcessed` to `serviceDataReceived` to reflect it's meaning and introduce a new job specific data received getter to entangle the Job and Service behavior.  This changes will make sure that we don't block the Job table rendering in case we didn't get any Service data, which in some cases resulted in an unusable UI.
Closes DCOS-11060
=> DCOS-11060: Adjust the DCOSStore data received flags

src/js/utils/__tests__/RouterUtil-test.js
This PR removes named routes from RouterUtil-test, so we won't be confused.
=> Remove named routes from tests

plugins/services/src/js/components/TaskDirectoryTable.js
This PR fixes the styling of the links in the `TaskDirectoryTable`
=> Fix TaskDirectoryTable links

src/js/components/ConfigurationMapSection.js, src/styles/components/configuration-map/styles.less, src/styles/components/configuration-map/variables.less
This PR removes the utility classes for `ConfigurationMapSection` based on @MatApple's suggestion here: https://github.com/dcos/dcos-ui/pull/1304/files/a040845dba717d9022639c8f91bb3d594e5b9a2c#r85980690
=> Use single classname for ConfigurationMapSection

src/js/components/form/FieldError.js, src/js/components/form/FieldHelp.js, src/js/components/form/FieldInput.js, src/js/components/form/FieldLabel.js, src/js/components/form/FieldTextarea.js, src/js/components/form/FormGroup.js
This PR introduces two fields; FieldInput and FieldTextarea.
They are both fairly simple; they do not hold state and are only concerned with rendering
Example usage:
```js
class ServiceFormSection extends Component {
getIDHelpBlock() {
return (
<span>
{"Include the path to your service, if applicable. E.g. /dev/tools/my-service. "}
<a href="https://mesosphere.github.io/marathon/docs/application-groups.html" target="_blank">
More information
</a>.
</span>
);
}
render() {
let {data, errors} = this.props;
return (
<form className="flex row" onChange={this.handleChange}>
<FormGroup className="column-8">
<FieldLabel>
SERVICE NAME <span className="text-danger">*</span>
</FieldLabel>
<FieldInput
name="id"
type="text"
value={data.id} />
<FieldHelp>{this.getIDHelpBlock()}</FieldHelp> …
```
=> [Service create form 1 of 2] Introduce fields: input and textarea

plugins/nodes/src/js/components/NodesGridView.js, plugins/nodes/src/js/components/NodesTable.js, plugins/nodes/src/js/pages/nodes/NodeDetailPage.js, plugins/services/src/js/components/MesosLogView.js, plugins/services/src/js/components/ServiceList.js, plugins/services/src/js/pages/services/DeploymentsTab.js, plugins/services/src/js/pages/task-details/TaskDetail.js, plugins/services/src/js/service-configuration/ServiceSpecView.js, src/js/components/Loader.js, src/js/components/modals/InstallPackageModal.js, src/js/pages/NetworkPage.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobsTab.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/system/OverviewDetailTab.js, src/js/pages/system/RepositoriesTab.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/UsersTab.js, src/js/pages/universe/InstalledPackagesTab.js, src/js/pages/universe/PackageDetailTab.js, src/js/pages/universe/PackagesTab.js, src/styles/components/loaders/styles.less, src/styles/components/loaders/variables.less
This PR removes the wrapping `div` that we used in conjunction with the `Loader` component almost everywhere. We don't need it because it adds extra margin where it shouldn't in 99% of the cases.
In the future, if we do decide to add margin or padding, we can do so in the `Loader` component itself and it'll just work everywhere :)
=> Fix loading indicators! 🕸 

plugins/services/src/js/services/ServiceSidebarFilters.js
This prevents the `name` column from being completely illegible at some viewports.
=> Hide ServiceSidebarFilters at larger screen sizes

src/js/components/modals/ServiceRestartModal.js, src/js/components/modals/ServiceSuspendModal.js
This PR fixes the error handling on the `ServiceSuspendModal`. Previously, when a service/pod was in a deploying state and a user clicks `Suspend`, the UI was just greying-out.
_Taking the opportunity to fix the same issue with the `ServiceRestartModal` on the services_
=> DCOS-10490: ServiceSuspendModal: Properly handling error responses

src/styles/content/tables/styles.less, src/styles/content/tables/table-simple/styles.less, src/styles/content/tables/table-simple/variables.less, src/styles/index.less
This PR:
* sets `vertical-align: top` for all `table` elements (as far as I can tell, all tables that rely on `vertical-align: middle` have explicitly declared this)
* adds a `table-break-word` class
* adds a `table-simple` style variant which looks like this:
=> Improve table styling

src/js/components/ConfigurationMapHeading.js, src/styles/components/configuration-map/styles.less, src/styles/components/configuration-map/variables.less
This PR:
* applies the `short-top` class to all `ConfigurationMapHeading` components where `level === 2`
* applies the `@neutral` color to each `ConfigurationMapLabel` element
* assigns the width for the `ConfigurationMapLabel` elements to a variable for re-use in the neighboring tables
=> Improve ConfigurationMap styling

jest/preprocessor.js, package.json, src/js/constants/DSLCombinerTypes.js, src/js/constants/DSLFilterTypes.js, src/js/structs/DSLASTNodes.js, src/js/utils/DSLParserUtil.js, src/resources/grammar/SearchDSL.jison, src/resources/grammar/__tests__/SearchDSL-test.js, webpack/webpack.config.babel.js
This PR introduces the Dynamic Search Language (DSL) grammar and parser based on JISON. More PRs are about to come that will use this base implementation.
- Pluggable architecture for the search plugins ([placeholder](https://github.com/dcos/dcos-ui/pull/1299/files#diff-e09e16137d96dd9c89e78576433d8e1bR68))
- Adding support for merging 2 lists and de-duplicating their contents ([placeholder](https://github.com/dcos/dcos-ui/pull/1299/files#diff-e09e16137d96dd9c89e78576433d8e1bR41))
- The DSL grammar as a JISON specification
- The `DSLParserUtil` that exposes the functions used by JISON to compose the AST
- Constants and structures shared by the `DSLParserUtil` and the parser users
1. `text` : Fuzzy text matching
2. `"text"` : Exact string matching
3. `attrib:value` : Attribute-based …
=> DCOS-10470 [DSL 1]: Adding grammar support

plugins/services/src/js/services/ServicesTable.js
=> Fix text overflow behavior in services table

plugins/services/src/js/tasks/ServiceTasksContainer.js
Throttles the updates to task table. Once relay lands - DCOSStore will no longer be used so this is just a temporary solution.
=> [Services 4] Throttle task table update for Service

plugins/services/src/js/components/modals/KillPodInstanceModal.js, plugins/services/src/js/components/modals/KillTaskModal.js, plugins/services/src/js/components/modals/ServiceDestroyModal.js, plugins/services/src/js/components/modals/ServiceFormModal.js, plugins/services/src/js/components/modals/ServiceGroupFormModal.js, plugins/services/src/js/components/modals/ServiceRestartModal.js, plugins/services/src/js/components/modals/ServiceScaleFormModal.js, plugins/services/src/js/components/modals/ServiceSuspendModal.js, plugins/services/src/js/pages/services/DeploymentsTab.js, src/js/components/FormModal.js, src/js/components/RepositoriesTable.js, src/js/components/ServerErrorModal.js, src/js/components/__tests__/ServerErrorModal-test.js, src/js/components/modals/ActionsModal.js, src/js/components/modals/AddRepositoryFormModal.js, src/js/components/modals/CliInstallModal.js, src/js/components/modals/ErrorModal.js, src/js/components/modals/IdentifyModal.js, src/js/components/modals/JobFormModal.js, src/js/components/modals/JobStopRunModal.js, src/js/components/modals/ModalHeading.js, src/js/components/modals/UserFormModal.js, src/js/components/modals/VersionsModal.js, src/js/components/modals/__tests__/VersionsModal-test.js, src/js/plugin-bridge/PluginModules.js, src/styles/components/multiple-form/styles.less
This PR aims to standardize modal headings, by doing the following:
* Implements a `ModalHeading` component with the most common defaults
* Moves the headings to actual `header` prop of the `Modal` component, wherever possible (this was not possible for some of the modals, like the `InstallPackage` modals, due to the way their content changes)
* Removes `.modal-header-title` styling which served little purpose
=> Standardize modal headings

src/js/routes/index.js
This PR fixes a regression that user sees 'access denied' page when visiting a cluster for the first time. The solution is to move the root redirect under the `Authenticated` component so the UI will be able to check on the login status first and then redirect.
🙇
=> DCOS-11291: Fix 'access denied' page when visiting a cluster for the first time

plugins/nodes/src/js/routes/nodes.js, plugins/services/src/js/components/VolumeTable.js
This PR fixes links to the Volume Detail view from all locations:
- Services
- Service/Volumes
- Nodes/Task/Volumes
PS. I do agree that we should refactor the way we detect current location, I'd rather see HOC pushing this piece of config down to `VolumeTable`
🙇
=> DCOS-11391: Fix Links to Volume Detail

.gitignore, package.json, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, scripts/pre-install, scripts/utils/marathon, src/js/utils/DataValidatorUtil.js, src/js/utils/__tests__/DataValidatorUtil-test.js, src/resources/raml/README.md
This PR uses the `raml-validator-loader` webpack loader to translate RAML documents to javascript validation functions and then uses them to validate the form contents.
To test:
```
npm run raml-update
```
_NOTE: I have embedded the `raml-validator-loader` project with the 528b2ab commit. Ideally it should be moved on a separate project and that commit should be removed, but until we have settled with the management stuff it will stay here_
**To check only the interesting changes check [this diff here](https://github.com/dcos/dcos-ui/compare/master...862cc88d104073a6207b843fc0496586a3d1c478)**
=> DCOS-10975: Form validation based on RAML spec

webpack/webpack.config.babel.js
Forgot to make webpack load `.raml` files with the `raml-validator-loader` by default.
=> Fix: Adding .raml file loader

src/js/components/form/FieldError.js, src/js/components/form/FieldHelp.js, src/js/components/form/FieldInput.js, src/js/components/form/FieldLabel.js, src/js/components/form/FieldTextarea.js, src/js/components/form/FormGroup.js
Example use case:
```js
<FormGroup showError={false}>
<FieldLabel>
<FieldInput
checked={false}
name="checkbox-1"
type="checkbox"
value="foo" />
This is the first checkbox
<FieldHelp>Help me once!</FieldHelp>
</FieldLabel>
<FieldLabel>
<FieldInput
checked={false}
name="checkbox-2"
type="checkbox"
value="bar" />
This is the second checkbox
<FieldHelp>Help me twice!</FieldHelp>
</FieldLabel>
<FieldLabel>
<FieldInput
checked={true}
name="checkbox-3"
type="checkbox"
value="bar" />
This is the thrid checkbox
<FieldHelp>Help me thrice!</FieldHelp>
</FieldLabel>
<FieldError>Here is an error</FieldError>
</FormGroup>
```
If you want to see them in action, check out this PR: https://github.com/dcos/dcos-ui/pull/1346
=> Introducing radio button and checkbox form fields

plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/service-configuration/NetworkingServiceConfigSection.js
This PR ties current efforts on the create/edit flow for services together, see it in action here:
Here is the changes you need to make to `ServiceModals` to activate the new flow:
```
- import ServiceFormModal from './ServiceFormModal';
+ import NewCreateServiceModal from './NewCreateServiceModal';
@@ -65,7 +65,7 @@ class ServiceModals extends React.Component {
};
return (
-      <ServiceFormModal
+      <NewCreateServiceModal
@@ -102,10 +102,10 @@ class ServiceModals extends React.Component {
}
return (
-      <ServiceFormModal
+      <NewCreateServiceModal
-        isEdit={false}
+        isEdit={true}
```
=> Tying new service create edit flow together

src/js/utils/JSONUtil.js, src/js/utils/__tests__/JSONUtil-test.js
This PR adds a `pos` attribute on the JSON tokens, containing the starting, ending offset of each token in the source string. This is particularly useful on tokens that are on the same line.
=> JSONUtil: Adding `position` attribute on JSON tokens

plugins/services/src/js/components/modals/ServiceScaleFormModal.js
This PR fixes the width of the input field in the `ServiceScaleFormModal`. The `column-2` class was constraining the width of the element which was already inside a `column-12` element.
Before:
After:
=> Fix ServiceScaleFormModal textbox

src/js/components/Sidebar.js
⚠️  merge the plugins first https://github.com/mesosphere/dcos-ui-plugins-private/pull/451
---
This PR re-enables Sidebar ACL filtering as it went missing in this commit https://github.com/dcos/dcos-ui/commit/b559575a39caf39407bca39984bd3045ddd14a82
=> DCOS-11363: Bring ACL menu filter back

plugins/services/src/js/events/TaskDirectoryActions.js, src/js/events/CosmosPackagesActions.js, src/js/events/MesosStateActions.js
Depends on https://github.com/dcos/mesosphere-shared-reactjs/pull/24
We no longer need to set "long enough" timeouts on endpoints where 2 seconds is not enough, because RequestUtil no longer imposes default timeouts. The only request that we want to time out after 2 seconds is the request made in `MesosStateSummary`.
=> DCOS-9773: Stop assuming RequestUtil has a default timeout

plugins/oauth/hooks.js
Since we've split system page into several pages and it doesn't exist anymore we don't need this filter.
=> Remove obsolete `system-organization-tabs` filter

BEST_PRACTICES.md
This PR adds a link to our CSS styleguide in `BEST_PRACTICES.md`.
=> Add link to CSS styleguide

src/js/components/JSONEditor.js, src/js/utils/JSONEditorUtil.js, src/js/utils/__tests__/JSONEditorUtil-test.js
This PR address some corner cases in the JSONEditor. Namely: the diff and sort algorithms were incorrectly treating `null` values as legit objects.
In addition this PR tries also fixes some minor issues:
* Errors with no paths and errors with missing paths always appear on line 1
* Initial `prop` values are now correctly handled
=> DCOS-11609: Fixing JSONEditor corner cases

plugins/nodes/src/js/pages/nodes/breadcrumbs/NodeDetailBreadcrumb.js, plugins/nodes/src/js/routes/nodes.js, plugins/services/src/js/containers/services/ServiceTreeView.js, plugins/services/src/js/containers/services/ServicesContainer.js, plugins/services/src/js/containers/volume-detail/VolumeDetail.js, plugins/services/src/js/routes/services.js, src/js/components/BreadcrumbSegment.js, src/js/components/BreadcrumbSegmentLink.js, src/js/components/Breadcrumbs.js, src/js/components/__tests__/BreadcrumbSegment-test.js, src/js/components/__tests__/Breadcrumbs-test.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/routes/components.js, src/js/routes/jobs.js
:warning: Depends on https://github.com/mesosphere/dcos-ui-plugins-private/pull/452
---
This PR introduces a recursive function that searches for a route in react-router routes definition.
That patches Breadcrumb component to a state where it is working again.
You can also see that I had to put some additional info into the routes declaration.
=> DCOS-11455: Breadcrumbs

webpack/modules/raml-validator-loader/lib/raml-validator-loader.js, webpack/modules/raml-validator-loader/package.json, webpack/modules/raml-validator-loader/src/GeneratorContext.js, webpack/modules/raml-validator-loader/src/__tests__/RAMLValidator-test.js, webpack/modules/raml-validator-loader/src/generators/HighOrderComposers.js, webpack/modules/raml-validator-loader/src/payloads/RAMLError.js
* **Enhancement:** Introducing compiler flags
* **Enhancement:** Setting `patternPropertiesAreOptional: true` by default, so empty objects with pattern properties does not raise an error
* **Enhancement:** Hiding all dynamically-generated types in an internal object and exposing only types present in the raml file
* **Fix:** Making the `path` and `message` properties of the `RAMLError` enumerable so they can be compared with `deepEqual`
=> Update raml-validator-loader to v0.1.3

src/js/components/Sidebar.js
⚠️  Depends on https://github.com/mesosphere/dcos-ui-plugins-private/pull/457
---
This PR utilizes a new hook to filter secondary navigation in the sidebar
=> DCOS-11363: Add secondary level navigation filter

plugins/services/src/js/utils/CreateServiceModalFormUtil.js, plugins/services/src/js/utils/__tests__/CreateServiceModalFormUtil-test.js
This PR introduces a utility function used by the `NewCreateServiceModalForm` to update the JSON content in the smartest way possible. This happens in two phases:
1. The form uses the batch reducers to create a "UI patch" to the JSON
2. It uses the `applyPatch` function apply the patch to the current JSON state
This function follows these principles:
1. An "empty" value in the patch removes the field.
2. The previous statement is not applied when the respective `data` field already contains an "empty" value. In that case, the original "empty" data value is perserved.
3. If both `data` and `patch` have a value in a field, but with different types, the value from `data` is preferred.
=> DCOS-11605: Introducing applyPatch utility function to the form

plugins/services/src/js/utils/CreateServiceModalFormUtil.js, plugins/services/src/js/utils/__tests__/CreateServiceModalFormUtil-test.js
This PR makes sure `CreateServiceModalFormUtil.applyPatch` is called recursively in order to remove objects that become empty after the first pass. For example:
For example given an input:
```js
{
"object": {
"value": ""
}
}
```
Previously was producing:
```js
{
"object": {
}
}
```
But now it produces:
```js
{
}
```
=> DCOS-11638: Fixing recursive application of applyPatch

src/js/components/form/FieldLabel.js, src/styles/components/form-elements/styles.less
This PR adds ability for `FieldLabel` elements to match the height of `input` elements. This is useful for implementing the following design:
Note: Right now the `@form-control-height` only has a `large` screen variant, so that's the only media query you'll see here.
=> Allow field label to match input height

plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
This PR makes sure the service configuration is properly maintained when switching between service editing mode and review page.
When #1401 lands, it will also disable the `Review & Run` button when there are errors on the form.
=> DCOS-11659: Properly handling state between form edit & review screens

src/js/components/modals/FullScreenModalHeaderActions.js
This PR adds support for a `disabled` property to the `FullScreenModalHeaderActions` buttons.
=> FullScreenModalHeaderActions: Adding `disabled` prop

src/js/components/Breadcrumbs.js, src/js/components/Sidebar.js
This PR fixes a couple of issues that emerges on an open cluster:
`Uncaught TypeError: Cannot read property 'reduce' of undefined(…)` in Sidebar.js
`Uncaught TypeError: Cannot read property 'length' of undefined(…)` in Breadcrumbs.js
=> Fix issue where routes might be undefined

plugins/services/src/js/reducers/serviceForm/HealthChecks.js, plugins/services/src/js/reducers/serviceForm/__tests__/HealthChecks-test.js
If you switch to HTTP protocol and check the HTTPS checkbox and then switch to protocol COMMAND and then beck to HTTP the HTTPS setting would be lost. This PR adds the feature to keep the value saved.
=> Add the capability to save HTTPS for healthChecks

src/js/events/AuthActions.js, src/js/events/__tests__/AuthActions-test.js
This PR allows us to provide a specific `target` when we perform a login action.
Which will be handled by the `IAM` service
=> DCOS-9609: Pass target param down to the auth service

plugins/services/src/js/components/forms/HealthChecksFormSection.js
=> Fix health-check advanced section label

foundation-ui/index.js, foundation-ui/mount/index.js, src/js/plugin-bridge/Loader.js, src/js/plugin-bridge/PluginModules.js
[1/3] : https://github.com/dcos/dcos-ui/pull/1413
[2/3] : https://github.com/dcos/dcos-ui/pull/1414
[3/3] : https://github.com/dcos/dcos-ui/pull/1418
This PR exposes `MountService` on the `foundation-ui` package
and the whole `foundation-ui` on the plugin-bridge
I removed Mount from mount/index to resolve a circular dependency in Mount.js
I'm open to a better solution.
Usage:
```
const {MountService: {Mount, MountService}} = SDK.get('foundation-ui');
```
=> [1/3]: Expose MountService

plugins/services/src/js/components/modals/CreateServiceJsonOnly.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalServicePicker.js, plugins/services/src/js/constants/NewPodDefaults.js, src/styles/index.less, src/styles/views/create-service-modal/styles.less, src/styles/views/create-service-modal/variables.less
This is the first PR for the separate JSON flow that cleans-up the `NewCreateServiceModalServicePicker`, keeping only the 3 acceptable options for now, and adding a placeholder for the JSON-only view.
@jfurrow I tried to center the buttons for making them look like the design, but I didn't want to mess-up the CSS. Can you have a look? https://mesosphere.invisionapp.com/d/main#/console/9042004/193660846/preview
=> DCOS-10987: [1/2] Separate JSON Flow

src/js/components/form/index.js, src/js/plugin-bridge/Loader.js, src/js/plugin-bridge/PluginModules.js
[1/3] : ~~https://github.com/dcos/dcos-ui/pull/1413~~ 💪 
[2/3] : https://github.com/dcos/dcos-ui/pull/1414
[3/3] : https://github.com/dcos/dcos-ui/pull/1418
This PR exposes `components/form/*` on the plugin bridge as I need them in plugins.
Usage:
```
const SDK = getSDK();
const {
FieldError,
FieldInput,
FieldLabel,
FieldSelect,
FormGroup
} = SDK.get('form-elements');
```
=> [2/3]: Expose components/form on plugin-bridge

src/js/components/modals/JobFormModal.js
Fix the wipe of unknown values from the job form.
Example JSON
```JSON
{
"description": "Example Application",
"id": "prod.example.app",
"labels": {
"location": "olympus",
"owner": "zeus"
},
"run": {
"artifacts": [
{
"uri": "http://foo.test.com/application.zip",
"extract": true,
"executable": true,
"cache": false
}
],
"cmd": "nuke --dry --master local",
"args": ["nuke", "--dry", "--master", "local"],
"cpus": 1.5,
"mem": 32,
"disk": 128,
"docker": {
"image": "foo/bla:test"
},
"env": {
"MON": "test",
"CONNECT": "direct"
},
"maxLaunchDelay": 3600,
"restart": {
"activeDeadlineSeconds": 120,
"policy": "NEVER"
},
"user": "root",
"volumes": [
{
"containerPath": "/mnt/test",
"hostPath": "/etc/guest",
"mode": "RW"
}
]
}
}
```
Fix DCOS-11482
=> DCOS-11482 Fix Jobs unknown values wipe

webpack/modules/raml-validator-loader/lib/raml-validator-loader.js, webpack/modules/raml-validator-loader/package.json, webpack/modules/raml-validator-loader/src/Generator.js, webpack/modules/raml-validator-loader/src/__tests__/RAMLValidator-test.js, webpack/modules/raml-validator-loader/src/__tests__/utils/ValidatorUtil.js, webpack/modules/raml-validator-loader/src/generators/NativeValidators.js, webpack/modules/raml-validator-loader/src/utils/RAMLUtil.js
* **Fix:** Fixed a bug that incorrectly resolved supertype name
* **Internals:** Renaming `ctx` to `context`
* **Fix:** Handling some cases that ended up creating validators with `null` name
* **Fix:** Assuming `null` not to be a valid object value
* **Enhancement:** Exposing error messages, making them overridable by the user
* **Internals:** Re-arranging tests code
=> Update raml-validator-loader to v0.1.5

npm-shrinkwrap.json, package.json, plugins/services/src/js/components/modals/CreateServiceJsonOnly.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/constants/NewPodDefaults.js, plugins/services/src/js/utils/ServiceUtil.js, src/js/components/JSONEditor.js, src/styles/components/modal/full-screen/styles.less
---
⚠️  Depends on https://github.com/dcos/dcos-ui/pull/1408
---
This PR introduces the first draft of the json-only editor view. There is proper error validation and integration with the review screen.
The following things are missing:
=> DCOS-10987: [2/2] Separate JSON Flow

src/styles/index.less, src/styles/layout/grid/styles.less, src/styles/layout/grid/variables.less
This PR:
* allows `flush` family of classes to remove padding from columns
* adds a `column-auto` class which will receive the same padding as all columns, but has no defined width
Both of these are necessary for the following mockup:
=> Extend column styling to include flush columns and automatic widths

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
According to the design we shouldn't capitalize these labels, but I guess that's a bigger topic.
=> DCOS-11672: Add `recommended` to the Docker option

plugins/services/src/js/utils/DeclinedOffersUtil.js, plugins/services/src/js/utils/__tests__/DeclinedOffersUtil-test.js
Change the `acceptedResourceRoles` and  `constraints` path to be in line with Marathons app type definition.
For detailed app type definition, please see:
https://github.com/mesosphere/marathon/blob/6db4d9980af15b45bc3c8647335f39deef3f49bf/docs/docs/rest-api/public/api/v2/types/app.raml
=> Align declined offers util with Marathon API

src/js/components/form/FormGroupContainer.js, src/styles/components/form-elements/styles.less, src/styles/variables/variables-z-index.less
This PR:
* Renames `.form-remove` to `.form-group-container-action-button`
* Gives a z-index to `.form-group-container-action-button` to prevent it from rendering below sibling elements
=> Add z-index to FormGroupContainer's remove button

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
In a previous PR I introduced the `appConfig` state variable that contains the current JSON object (useful when comparing incoming properties and making sure the component is not updated if it's fed the same data)
However I forgot to update `appConfig` in two cases: when an item was pushed or removed from the batch. This PR fixes this.
=> DCOS-11693: Fixing appConfig update issues

plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/utils/ServiceUtil.js, plugins/services/src/js/utils/__tests__/ServiceUtil-test.js
This PR ensures that the `NewServiceFormModal` components always work on the correct data. 
In particular, when a `Pod` instance is given, it should operate on it's `PodSpec` contents an not on the `Pod` instance itself.
=> DCOS-11735: Properly handling Pods in the Service

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
This PR addresses a bug within the `NewCreateServiceModalForm` that raises an error when the user edits/blurs away from a field without a name.
=> DCOS-11727: Not handling events from fields without name

src/styles/layout/sidebar/styles.less, src/styles/layout/sidebar/variables.less
This PR... 
* removes the CNVS mixins used in the sidebar and replaces with the necessary properties
* removes `null` sidebar variables
* removes old CSS for the version info in the sidebar
=> [Sidebar: 2 of 4] Remove mixins in favor of actual CSS properties

plugins/services/src/js/pages/task-details/TaskDetail.js, plugins/services/src/js/schemas/service-schema/Networking.js, src/js/components/Sidebar.js, src/js/pages/NetworkPage.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/VirtualNetworksTable.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/routes/factories/network.js, src/js/utils/VirtualNetworkUtil.js
⛔️  Blocks https://github.com/mesosphere/dcos-ui-plugins-private/pull/463
---
This PR changes strings and reorganizes the sidebar to match the latest mockups.
The following routes have been renamed:
`/network/` -> `/networking/`
`/network/virtual-networks/` -> `/networking/networks/`
=> DCOS-11743: Networking section IA restructure

plugins/services/src/js/reducers/serviceForm/HealthChecks.js, plugins/services/src/js/reducers/serviceForm/__tests__/HealthChecks-test.js, plugins/services/src/js/service-configuration/HealthChecksServiceConfigSection.js, scripts/pre-install
This adds the Health checks to the review screen. It also introduces the new format for Command Healthchecks which is for marathon. 1.4.0
```JSON
{
"protocol": "COMMAND",
"command": {
"command": "sleep 100; exit 0"
}
}
```
Right now the validator will complain that the advanced settings are not set but in the RAML they have a default value provided. I talked offline with @wavesoft and we decided that in that case the values are not required.
=> DCOS-11678: health check review screen

src/js/components/modals/FullScreenModal.js
This PR needs a change in `reactjs-components` to merge (https://github.com/mesosphere/reactjs-components/pull/374), hence the `hold merge` label. Please refer to that PR for the description of the problem & solution.
Update: https://github.com/mesosphere/reactjs-components/pull/374 has merged!
=> Fix state loss in FullScreenModal

plugins/services/src/js/components/ServiceConfigDisplay.js
Change the default config display component registration to better explain the component priorities and ensure that the component registration happens only once.
/cc @wavesoft @nLight @Poltergeist
=> Adjust config display component registration

npm-shrinkwrap.json, package.json
Notable changes:
* Toggle display property for caret (https://github.com/mesosphere/reactjs-components/commit/d0b7d6902e4bfa156ce930300ba0e6a47553dee6)
* Making modals stack on top of each other when multiple are open (https://github.com/mesosphere/reactjs-components/commit/5507ed47161bd2aa3ae56041acbf279e78682b1d)
* Allow setting classes on Gemini in Modals (https://github.com/mesosphere/reactjs-components/commit/40f97303078943127ce5db27f55845818574ad3c)
* Allow passing height to ModalContents (https://github.com/mesosphere/reactjs-components/commit/bb265d92243cfc97a747cb6486d6fbd486444e73)
* Add block class for tooltip (https://github.com/mesosphere/reactjs-components/commit/68e34d04ab90dd52a488c1a2ff080075012044ee)
=> Update reactjs-components to 0.16.0-beta.5

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/constants/ContainerConstants.js, plugins/services/src/js/constants/VolumeConstants.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/JSONParserReducers.js, plugins/services/src/js/reducers/serviceForm/Container.js, plugins/services/src/js/reducers/serviceForm/Docker.js, plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js, plugins/services/src/js/structs/ApplicationSpec.js, plugins/services/src/js/utils/ServiceUtil.js, src/js/utils/ParserUtil.js
This changes the way how the container reducers work.
With a following PR I will disable fields depending on the runtime environment.
=> DCOS-11759: [1/?] change container reducer workflow

plugins/services/src/js/schemas/service-schema/EnvironmentVariables.js, src/js/components/form/FieldHelp.js, src/styles/components/typography/styles.less
This PR...
* Adds the `textTransform` prop to `FieldHelp` and defaults to `none`
* Renames the `upper-cased` class to `text-uppercase` to better match related classes
* Introduces `text-no-transform` to remove text transformation when needed
=> Create text transformation classes

src/styles/components/modal/login/styles.less, src/styles/components/modal/variables.less
CNVS now uses `border` instead of `box-shadow` for the separations between a modal's header and footer.
This PR removes an outdated variable override which caused a `box-shadow` to render in addition to the `border`.
It also removes the overrides in the login modal to reflect the new properties.
=> Fix modal header borders

plugins/services/src/js/components/modals/NewCreateServiceModalServicePicker.js
This PR removes the `Multi-Container (Pod)` option from the UI and updates the language accordingly.
=> DCOS-11792: Remove pods language and button from UI

src/js/components/Sidebar.js, src/styles/layout/sidebar/styles.less, src/styles/variables/variables-z-index.less
This PR fixes the Sidebar z-index issue. I also renamed `sidebar-overlay` to `sidebar-backdrop` to match the same concept in the `Modal`.
I removed the use of `extend` because the `modal-backdrop` is defined higher in the source order than `sidebar-backdrop`, so the specificity was impossible to override without `!important` and I would feel gross for doing that.
=> Fix Sidebar z-index

plugins/services/src/js/components/ServiceConfigDisplay.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js
This PR removes layout divs from the `ServiceConfigDisplay` component so that its parent can use whatever it wants.
=> Make layout classes optional in ServiceConfigDisplay

src/styles/components/tooltip/styles.less, src/styles/components/tooltip/variables.less
These tooltips were obnoxiously huge IMO. @ashenden @leemunroe What do you think?
Before:
After:
=> Reduce tooltip font size

plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js
Return `<noscript />` if no env is defined as functional components always need to return something in order to properly update.
=> Fix pod env review section

plugins/services/src/js/utils/DeclinedOffersUtil.js, plugins/services/src/js/utils/__tests__/DeclinedOffersUtil-test.js
This PR will begin the accumulation of a pod's resource with the values defined in `executorResources`
cc @orlandohohmeier
=> DCOS-11822: Add executorResources to total number of requested resources

plugins/services/src/js/utils/ServiceUtil.js
---
⚠️  #1450 needs to land first
---
This PR changes the service `isEqual` util, to only compare the service specs as everything else is status information and bound to frequent changes. Without this change we end up with unwanted updates of the service form which sometimes resulted in data loss.
Closes DCOS-11813
=> DCOS-11813: Fix edit pod interaction

plugins/services/src/js/components/forms/ContainerServiceFormSection.js
This fixes an issue in the ContainerServiceFormSection which resulted in throwing errors, because there where no keys on jsx elements in an array.
=> Fix ContainerServiceFormSection

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/reducers/serviceForm/Container.js, plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js
This PR introduces a feature where certain fields are disabled depending on the runtime environment. This needs also to be applied to the networking section as soon as it is done.
Mesos Runtime
UCR Runtime:
Docker Runtime:
=> DCOS-11759: [2/2] disable fields in Container, Health Checks and Volumes section

.eslintrc, plugins/nodes/src/js/pages/nodes/nodes-grid/NodesGridContainer.js, plugins/services/src/js/components/modals/NewCreateServiceModalServicePicker.js, plugins/services/src/js/containers/volume-detail/TaskVolumeContainer.js, plugins/services/src/js/service-configuration/PodNetworkConfigSection.js, src/js/components/TabButton.js, src/js/pages/jobs/JobsTab.js, src/js/routes/universe.js
This PR enables `no-undef` eslint rules and fixes all the bugs we had while having it off :trollface:
=> Enable no-undef eslint rule

scripts/utils/git
This PR doesn't prompt the user if the given git hook already exists and it's identical with the script we are about to install.
=> Not installing git hooks if files are the same

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js, plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesContainer-test.js, plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js, src/styles/components/pod-instances-table/styles.less
This PR fixes the `PodInstancesTable` layout. I've applied widths and responsiveness in a way that we haven't done before, so I'm interested to see what you guys think.
Instead of applying `hidden-*` classes and using inline `style` props, it uses classnames and external CSS. I think it's easier to reason about and it would allow us to change the width of certain columns in media queries. There would be a little extra work when creating new tables, but I think it's worth it. I'd be happy to apply this to the rest of the tables in the UI, if you all like it! :)
---
In an unrelated note, for some reason when I apply the `pod-instances-table-column-primary` class to the related `col` in the `colgroup`, the sorting of the table gets reversed in one of the tests. WTF??? Am I missing something? …
=> DCOS-11823: Fix PodInstancesTable layout

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
This PR removes flags and checks that we don’t have time to do properly. So we will run the complete ramp validation on every form change. Otherwise I could run a service without providing ID etc. And the form validation didn’t work for me in general, only JSON editor validation worked.
=> Run the complete validation on each blur. Always.

webpack/modules/raml-validator-loader/lib/raml-validator-loader.js, webpack/modules/raml-validator-loader/package.json, webpack/modules/raml-validator-loader/src/GeneratorContext.js, webpack/modules/raml-validator-loader/src/__tests__/RAMLValidator-test.js, webpack/modules/raml-validator-loader/src/generators/HighOrderComposers.js
- **Change**: The path of missing property errors now points to the actual missing field.
- **Change**: This feature is controlled through the `missingPropertiesOnTheirPath` option flag
=> Upgrading raml-validator-loader to v0.1.6

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js, plugins/services/src/js/containers/tasks/TaskTable.js
Fix link to a log tab from a service tasks table // cc @mlunoe
=> Fix link to a logs Tab from the service tasks table

src/js/components/Sidebar.js, src/js/constants/UserSettings.js, src/js/mixins/SaveStateMixin.js, src/js/stores/SidebarStore.js
This PR fixes a bug with saving the sidebar's state in local storage. The state of the sidebar is held within `SidebarStore`, so all logic for saving to local storage has been moved there.
This also fixes an ugly bug where if you've cleared your local storage for DC/OS UI and log in to your cluster, an error in the sidebar prevented the dashboard from rendering entirely. 🐛
=> Fix sidebar's dock/undocked local storage saving

plugins/services/src/js/service-configuration/PodLabelsConfigSection.js
This PR allows the `labels` value to be `null`.
=> Handle null value for labels key

src/js/components/JSONEditor.js
This PR is fixing some issues the #1471 is introducing. In detail, when the JSON editor cannot find a token on the given path, it will try the parent paths until it reaches the root.
=> JSONEditor: Better handling of error paths

src/js/components/PageHeaderActionsMenu.js, src/styles/components/page-header/styles.less
This PR introduces a component called `PageHeaderActionsMenu` which is really just a wrapper for the `Dropdown`. Here's how I propose it works:
```jsx
<PageHeaderActionsMenu>
<span clickHandler={() => console.log('hello')}>
Hello!
</span>
<span clickHandler={() => console.log('goodbye')}>
Goodbye!
</span>
</PageHeaderActionsMenu>
```
Each child of `PageHeaderActionsMenu` will be rendered as an item in the `Dropdown` without being modified. When selected, it will call the child's `clickHandler` prop.
Sneak peek:
---
@philipnrmn In the new `PageHeader` component, this should be wrapped inside `div.button-collection.flush-bottom`, which will provide the proper layout for a neighboring action button. Here's an example of how that markup might look:
```jsx
<div className="page-header-actions"> …
```
=> Introduce PageHeaderActionsMenu component

npm-shrinkwrap.json, package.json
This update includes a fix for checkboxes and radio buttons; they all use the new CNVS styling now.
=> Update to reactjs-components@0.16.0-beta.6

src/styles/components/pod-instances-table/styles.less
TIL, we shouldn't use `table-layout: fixed` if we're going to hide columns at certain breakpoints. Not sure why I didn't see this behavior earlier...
Before:
After:
=> Fix PodInstanceTable column layout

src/js/components/PageHeaderActionsMenu.js
This builds on the work in #1481 and fixes two small errors:
- the `anchorRight` property was not being passed to the `Dropdown`, so the dropdown on the right of the page header was appearing off the screen.
- the `clickHandler` child property was not updated to `onItemSelect` everywhere, so it defined actions were not working.
=> Two small fixes for the kebab menu

src/js/components/NewPageHeader.js, src/js/components/NewPageHeaderActions.js, src/js/components/NewPageHeaderBreadcrumbs.js, src/js/components/NewPageHeaderTabs.js, src/js/components/Page.js, src/js/utils/TemplateUtil.js, src/js/utils/__tests__/TemplateUtil-test.js
This PR introduces the new Page Header components. In order to keep noise low, I've stayed relatively faithful to the original interface of the components. 
The page header is wrapped in a utility component and added to the Page namespace in order to allow subclasses of Page to override it. 
The intent is to allow every view to control its header by defining itself as a page, eg
```
<Page>
<Page.Header breadcrumbs={...} />
{usual page content here}
</Page>
```
=> [1/11] Page template headers

src/js/components/DSLInputField.js, src/js/components/SearchDSLInputField.js
_This PR fixes #1479_
This is the low-level `<SearchDSLInputField />` component, following closely the `<FilterInputText />` styling and props.
Update, adding `hasErrors` and `hasDropdown`:
You can test this by adding it in `ServiceTreeView`:
```jsx
class ServiceTreeView extends React.Component {
constructor() {
super(...arguments);
this.state = {value: ''};
}
...
render() {
...
<DSLInputField  
onChange={(value) => this.setState({value})}
value={this.state.value} />
...
}
}
```
=> DCOS-10470: [2/10] Introducing the DSLInputField

src/js/routes/index.js
I kept NotFoundPage Route being a child of Index while keeping it away from being in the main routes array.
Otherwise plugins routes go after the glob * NotFoundPage Route and therefore become unreachable.
=> Fix 404 for all the plugins

src/resources/grammar/SearchDSL.jison, src/resources/grammar/__tests__/SearchDSL-test.js
---
~~⚠️  Depends on #1491~~
---
[Diff between 1491 & This](https://github.com/dcos/dcos-ui/pull/1493/commits/f8c3b781c73bd122ab482e0d6bb8567672d5c697)
This PR Makes the JISON specifications a bit more tight regarding the multi-value attributes. In particular:
Introducing `TIGHT_COMMA` token that makes sure there is no whitespace around it, in order to differentiate between:
* Multi vlaues: `label:a,b,c`
* Multiple tokens: `label:a, label:b`
=> DCOS-10470: [3/10] Fixing DSL JISON specs

src/js/components/NewPageHeader.js, src/js/components/NewPageHeaderActions.js, src/js/components/Page.js, src/js/components/PageHeaderActionsMenu.js
This PR allows the add button in the page header to be a dropdown with multiple add actions. It also introduces a default prop in `PageHeaderActionsMenu` for the icon ID.
You can pass an array of objects as follows:
```jsx
<Page.Header addButton={[
{onItemSelect: modalHandlers.createService, label: 'Run a Service'},
{onItemSelect: modalHandlers.createService, label: 'Run a Better Service!'}
]} />
```
=> Allow multiple add actions in PageHeaderActions

src/styles/components/tooltip/styles.less
This PR implements two changes:
* The `will-change` property on the tooltip itself which should force hardware acceleration even when the tooltip is not being animated
* A specific anti-aliasing property to prevent the browser from switching on the fly
You may be wondering what the vendor prefixes are doing here! Autoprefixer doesn't currently handle these, so the vendor prefixes are sanctioned by Stylelint.
=> DCOS-11728: Force hardware acceleration for tooltips

plugins/services/src/js/components/ServiceBreadcrumbs.js, plugins/services/src/js/containers/pod-detail/PodDetail.js, plugins/services/src/js/containers/service-detail/ServiceDetail.js, plugins/services/src/js/containers/service-detail/__tests__/ServiceDetail-test.js, plugins/services/src/js/containers/services/ServiceTreeView.js, plugins/services/src/js/containers/services/ServicesContainer.js, plugins/services/src/js/pages/ServicesPage.js, plugins/services/src/js/pages/__tests__/DeploymentsTab-test.js, plugins/services/src/js/pages/services/DeploymentsTab.js, plugins/services/src/js/pages/task-details/TaskDetail.js, plugins/services/src/js/pages/task-details/__tests__/TaskDetail-test.js, src/js/utils/JestUtil.js, src/styles/components/page-header/styles.less
---
⚠️   _This branch depends on features that will be introduced with #1482 and #1498_
---
This PR adopts the new headers introduced in #1482 and uses them in the Service pages. 
Known issues (will be remedied outside this PR):
- Breadcrumbs do not yet collapse
- Non-routed tabs do not get an active state
=> [2/11] New headers for service pages

scripts/pre-install, scripts/utils/marathon
Change the Marathon variable/constant names to make it obvious that one needs to reference the proper Marathon _version_ not the _tag_.
/cc @wavesoft
=> Rename Marathon version var/const names

scripts/utils/git
Adjust the install hook helper to properly check if a hook is already "linked" and only run the install if the hook isn't linked.
=> Improve the git hook helper

src/js/components/ServerErrorModal.js, src/styles/components/modal/server-error/styles.less, src/styles/components/modal/server-error/variables.less, src/styles/index.less
ServerErrorModal now renders with a higher z-index than all other modals. This is important to show errors for modals that do not handle the errors themselves.
=> Ensure ServerErrorModal renders on top of any other open modal

src/js/components/NewPageHeader.js, src/js/components/NewPageHeaderActions.js, src/js/components/NewPageHeaderBreadcrumbs.js, src/js/components/PageHeaderActionsMenu.js, src/styles/components/page-header/styles.less, src/styles/components/page-header/variables.less
This PR cleans up the page header styles and applies them to the new components. It also adds the `SidebarToggle` component from the old page header. :arrow_left: :arrow_right:
=> Page header styling updates

plugins/services/src/js/pages/task-details/ServiceTaskDetailPage.js
This builds on work merged in #1483, moving service-specific code in the TaskDetail panel to a ServiceTaskDetailPage to clear the way for Jobs- and Network- TaskDetailPage.
=> [8/11] Create service-specific task detail page

src/js/components/AccessDeniedPage.js
This PR simplifies the classes applied in `AccessDeniedPage` and adds `application-wrapper` which is meant to wrap everything in DC/OS UI.
💩 Before:
✨ After:
=> Fix access denied page styling

src/js/components/Sidebar.js
This PR hides empty sidebar sections if there are no menu items available (e.g. if a user has limited permissions).
Before:
After:
=> DCOS-11817: Hide empty sidebar sections

src/js/components/Sidebar.js
This PR changes the event listener's target to the `sidebar-wrapper` which is the only sidebar element that affects the page's layout.
=> DCOS-11941: Change Sidebar's transitionend event target

src/styles/layout/sidebar/styles.less, src/styles/variables/variables-z-index.less
This PR removes the offset of the page content when the sidebar's visibility is toggled (per @ashenden's request).
Before:
After:
=> DCOS-11854: Sidebar's visibility no longer affects page content

plugins/services/src/js/containers/pod-detail/PodDetail.js, plugins/services/src/js/containers/service-detail/ServiceDetail.js, src/js/components/NewPageHeaderTabs.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js
This PR adds active state to routed and unrouted tabs. 
Before:
After:
=> Show active state on tabs

src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskPage.js
This PR replaces the cluster icon in network detail pages with the network icon.
=> Replace cluster icon in network detail pages with network icon

src/js/pages/system/RepositoriesTab.js
=> Fix typo in Repositories breadcrumbs

plugins/services/src/js/constants/TaskStates.js
This PR adds missing task states.
This is a quickfix™
We should consider having a function returning `{stateTypes, displayName}` instead of object lookup so we could work around a new missing task state. Sadly proxies are still missing in IE.
=> DCOS-11958: Add missing task states

plugins/services/src/js/utils/PodUtil.js, plugins/services/src/js/utils/__tests__/PodUtil-test.js
Implement calls to filter the combined (current and historical) list of pod containers to remove potential duplicates. 
This will fix issues with oscillating pod container data which was caused by duplicated containers.
Fixes DCOS-11961
=> DCOS-11961: Fix historical pod instance merge

src/styles/components/form-elements/styles.less, src/styles/components/multiple-form/styles.less
This PR fixes the inline radio buttons.
We had a clash of classes going on here; the `form-element-inline` class is defined in `reactjs-components` and is meant for textboxes that don't look like textboxes until you begin editing them (the name should better reflect this, but that's not the issue at hand). I changed the class to `form-control-inline` to better align with the rest of our `form-control` family of classes.
=> DCOS-11910: Fix inline form controls

src/js/components/ClusterHeader.js, src/js/components/Sidebar.js
This PR allows an `onUpdate` callback function to be passed to the `ClusterHeader` component. This is necessary for the `Sidebar` because the `ClusterHeader`'s size will update when it receives the IP address of the cluster. When this happens, the height of the neighboring Gemini container needs to be updated.
A symptom of this was the Sidebar's dock icon rendering slightly off the viewport.
Before:
After:
=> DCOS-11939: Pass update callback to ClusterHeader

src/js/components/ExpandingTable.js, src/styles/components/deployments-table/styles.less, src/styles/components/pod-instances-table/styles.less, src/styles/content/tables/styles.less
This PR adjusts table cell alignment in several ways. Here's what's up:
* Adds classes for vertically aligning table cells `top`, `middle`, or `bottom`
* Adds `alignCells` prop to `ExpandingTable` and defaults to `top`
* Removes all of the places we specified vertical alignment contextually, because this is now handled by the `ExpandingTable` itself
* Resets default alignment for all table cells to `vertical-align: middle`
=> DCOS-11539: Adjust table cell alignment

src/js/plugin-bridge/Hooks.js, src/js/plugin-bridge/__tests__/Hooks-test.js
Fixes bug where removing a listener mid-execution of listeners, would cause subsequent listener to not get called as array was mutated.
=> Fixes bug where listeners would not get called under some conditions

plugins/services/src/js/components/LogView.js, plugins/services/src/js/pages/task-details/TaskLogsTab.js, src/js/events/SystemLogActions.js, src/js/events/__tests__/SystemLogActions-test.js, src/js/stores/SystemLogStore.js, src/js/utils/SystemLogUtil.js
This PR fixes a few bugs for the log view, that should now:
1. Close open connections when done viewing a log file.
2. Handle when the logs take up _more_ vertical space than container better
3. Handle when the logs take up _less_ vertical space than container (including requesting to see if we have reached the top)
4. Handle receiving duplicate logs (requesting previous logs with `skip_prev` was buggy, so we are using `read_reverse` instead).
=> Bug fix: Duplicate logs from range request, ref. DCOS-11818, DCOS-11819, DCOS-11820

src/js/pages/DashboardPage.js
Without the page header, there's no way to toggle the sidebar's visibility. This is especially bad for mobile devices because there's literally no way to navigate the app. This was approved by design as a quick fix.
=> Add page header to dashboard

.editorconfig
Change the continuation indent size from 4 to 2 as an indentation of 4 often was pointed out as a stylistic issues during reviews.
/cc @dcos/frontend
=> Adjust the  continuation indent size

plugins/services/src/js/reducers/serviceForm/Containers.js
This fixes the structure of the image field in containers from
```JSON
{
"image": "imagename"
}
```
to 
```JSON
{
"image": {
"id": "imagename",
"kind": "DOCKER"
}
```
My understanding is that we currently only support `DOCKER` images.
=> [multi container]: Container image format

plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
This introduces the review screen by correctly comparing the service to podSpec instead of pod
based on #1547
=> [multi container] Fix / implement review screen

plugins/services/src/js/components/dsl/ServiceHealthDSLSection.js, plugins/services/src/js/components/dsl/ServiceStatusDSLSection.js, plugins/services/src/js/containers/services/ServicesContainer.js, plugins/services/src/js/filters/ServiceAttributeHealthFilter.js, plugins/services/src/js/filters/ServiceAttributeIsFilter.js, plugins/services/src/js/filters/ServiceNameTextFilter.js, plugins/services/src/js/filters/__tests__/ServiceAttributeHealthFilter-test.js, plugins/services/src/js/filters/__tests__/ServiceAttributeIsFilter-test.js, src/js/structs/DSLASTNodes.js, src/js/structs/DSLExpressionPart.js, src/js/structs/DSLFilter.js, src/js/structs/__tests__/DSLExpressionPart-test.js, src/js/utils/DSLParserUtil.js, src/js/utils/DSLUpdateUtil.js, src/js/utils/DSLUtil.js, src/js/utils/__tests__/DSLParserUtil-test.js, src/js/utils/__tests__/DSLUpdateUtil-test.js, src/js/utils/__tests__/DSLUtil-test.js
---
⚠️  _This branch includes features that will be introduced with #1549, don't merge before the respective branch landed._
---
Change all DSL variable and class names from `attrib` to `attribute` to improve readability.
See [diff here](https://github.com/dcos/dcos-ui/compare/ic/feat/DCOS-10470-new-dsl-components-9...orlandohohmeier/refactor/adjust-dsl-class-and-variable-names)
/cc @wavesoft
=> Rename variable/class names to improve readability

plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/constants/NewPodDefaults.js, plugins/services/src/js/reducers/serviceForm/Containers.js, plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js
Adjust the multi-container default names to ensure they are in line with the API requirements. It also aligns the default spec with the generated ones.
=> Fix container name defaults
