dcos/dcos-ui

npm-shrinkwrap.json
package.json

DCOS-12149: Remove underscore dependency

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/MultiContainerNetwork.js

As it turned out the endpoint name is not optional, this pr adds the field back for the hose mode.
https://www.youtube.com/watch?v=bupagiROLV8

[Multi-container] endpoint name

---

plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerNetwork-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js
src/js/structs/Batch.js
src/js/structs/__tests__/Batch-test.js

Based on #1573
This Introduces the endpoints tests for `JSONReducers` and `FormReducers`.
And also the network reducer got some tests.
On the way I fixed some issues which would never occur except in test cases.
For example set the path for the initial transaction in the batch.

[multi container] endpoint tests

---

src/js/components/DSLInputField.js

This PR de-bounces the user typing on the input field for 500ms before applying the filter, optimising the update performance.

DCOS-12036: De-bounce DSL input

---

src/js/utils/ScrollbarUtil.js

This PR adds a `null` check for `containerRef`.

Bugfix: Add null check for containerRef in ScrollbarUtil

---

.eslintrc

This PR enables 2 eslint rules to tame ternary:
`no-nested-ternary` - ensures that we don't nest them
`no-unneeded-ternary` - ensures that we don't do `value ? true : false` stuff
`multiline-ternary` is off to explicitly show that we don't yet have a decision on whether we always break a ternary into multiple lines them or we always use single line. So both are allowed. http://eslint.org/docs/rules/multiline-ternary

DCOS-12147: Allow ternary operator

---

plugins/services/src/js/components/ServiceConfigEnvironmentVariablesSectionDisplay.js
plugins/services/src/js/components/ServiceConfigPlacementConstraintsSectionDisplay.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/service-configuration/GeneralServiceConfigSection.js
plugins/services/src/js/service-configuration/HealthChecksServiceConfigSection.js
plugins/services/src/js/service-configuration/LabelsServiceConfigSection.js
plugins/services/src/js/service-configuration/NetworkingServiceConfigSection.js
plugins/services/src/js/service-configuration/PodNetworkConfigSection.js
plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js
plugins/services/src/js/service-configuration/PodStorageConfigSection.js
plugins/services/src/js/service-configuration/StorageServiceConfigSection.js
plugins/services/src/js/utils/ServiceConfigDisplayUtil.js

This PR fixes a few small issues with the config review and displays 'Not Configured'/'Not Supported' for empty values, rather than `--`.
Before:
After:

Display not supported not configured for empty fields, ref. DCOS-11676

---

src/styles/components/dropdown-menus/styles.less

Firefox doesn't treat pseudo-elements as regular flex elements, so I've decided to change `.dropdown-toggle` elements to `inline-block` rather than `inline-flex`. Here's a codepen to illustrate the issue: http://codepen.io/yeahjohnnn/pen/ObBOBG

DCOS-12130: Use inline-block for dropdown-toggle elements

---

plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js

Adjust the residency rule to properly look for persistent volumes.

Fix Marathon residency validator

---

src/styles/components/status-bar/styles.less

DCOS-11988: Right-align resource graphs in nodes table

---

webpack/plugins/svg-compiler-plugin.js

This PR uses `<defs>` instead of `<symbol>` for the SVG sprite. This fixes SVGs that use gradients in Firefox and doesn't break them in other browsers (even IE11 and Edge)!

DCOS-12205: Use defs instead of symbol in SVG sprite

---

plugins/services/src/js/reducers/JSONConfigReducers.js
plugins/services/src/js/reducers/JSONParserReducers.js
plugins/services/src/js/reducers/serviceForm/Residency.js
plugins/services/src/js/reducers/serviceForm/__tests__/Residency-test.js

If one adds a local persistent volume also the residency has to be set. As we do not have any field in the form representing this. We only have a `JSONReducer` and `JSONParser` for this.
The erros which you see in the animation is addressed by: #1601

[local volumes] add residency if needed

---

src/styles/components/configuration-map/styles.less
src/styles/components/configuration-map/variables.less

This PR forces text to wrap in configuration map labels.
I also cleaned up the `@base-spacing-unit` variable modifications. 👦 🎽

DCOS-11979: Force text wrap in configuration map component

---

src/js/components/modals/InstallPackageModal.js
src/styles/components/modal/install-package/styles.less

This PR fixes the problems that were present in Firefox and Safari. Previously, Safari wouldn't render anything in this form, and it wouldn't scroll in Firefox.
The combination of `TabForm` + `SchemaForm` + `GeminiScrollbar` in a modal is super fragile, so the fix is not obvious.
Before (Safari):
After (Safari):

DCOS-11395: Fix scroll behavior in advanced package installation form

---

plugins/services/src/js/components/dsl/ServiceHealthDSLSection.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/filters/ServiceAttributeHealthFilter.js
plugins/services/src/js/filters/ServiceAttributeNoHealthchecksFilter.js
plugins/services/src/js/filters/__tests__/ServiceAttributeNoHealthchecksFilter-test.js
plugins/services/src/js/structs/Service.js

---
⚠️  ~Depends on #1564~ Merged
---
This PR renames `health:` health-check attribute to:
* `health:healthy` -> `is:healthy`
* `health:unhealthy` -> `is:unhealthy`
* `health:na` -> `no:healthchecks`
* `health:idle` -> Removed

DCOS-12063: Changing the labels for healthchecks DSL filter

---

plugins/services/src/js/pages/services/DeploymentsTab.js
src/js/components/NestedServiceLinks.js
src/styles/components/nested-service-links/styles.less

This PR...
* Removes superfluous classes passed from `DeploymentsTab`'s to `NestedServiceLInk` (these classes are meant to be assigned directly to the links, and this is done inside the `NestedServiceLInk` component itself)
* Removes superfluous `flex` classes in the `NestedServiceLInks` component (the flex properties are supplied by the `table-cell-flex` classes)
* Ensures the `table-cell-value` elements don't grow to fill its parent

DCOS-11772: Fix NestedServiceLinks styling

---

scripts/pre-commit

Change the task order to first lint all files and then run the tests to catch stylistic issues faster, as the tests might take some time to run.
/cc @mlunoe

Adjust the pre-commit task order

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
src/js/components/form/FormRow.js
src/js/components/form/index.js
src/styles/components/advanced-section/styles.less
src/styles/components/advanced-section/variables.less
src/styles/components/form-elements/form-group/styles.less
src/styles/components/form-elements/form-group/variables.less
src/styles/components/form-elements/form-row/styles.less
src/styles/components/form-elements/form-row/variables.less
src/styles/index.less

This PR aims to improve the consistency of the spacing in the service creation modal. Originally I intended to create a `FormSection` component, but it is @ashenden's intentions for the margin on headings in the form to create the desired visual spacing.
I created a `FormRow` component which should be used to wrap `FormGroup` elements. Doing so will apply a negative bottom margin on the `FormRow` element to offset the margins applied by `FormGroup` children. This means that `FormRow` must always contain `FormGroup` elements.
The structure of all form sections should be as follows (of course with any number of `FormRow` or `FormGroup` elements):
```jsx
/* Notice the .flush-top on the first heading. */
<h2 className="short-bottom flush-top">Top-level Heading</h2>
<FormRow>
<FormGroup /> …
```

DCOS-11803: Improve consistency of service creation modal spacing

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/JSONParserReducers.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/Network.js
plugins/services/src/js/reducers/serviceForm/__tests__/Network-test.js

This PR:
* Enables USER network for Mesos runtime, as it turned out to be available.
* Introduces an initial transaction that sets `container.type` to `NONE`. 
Otherwise setting the network type would also create a `container` section.
* Fixes a typo/bug handling `groups` section in `ipAddress` properly.
As you can see it does 3 things, which could be bad if they weren't closely related, though I still can extract 2 PRs if you insist.
Example definition:
```JSON
{
"id": "/mesos-user-network",
"cmd": "sleep 1000",
"cpus": 0.1,
"mem": 128,
"disk": 0,
"ipAddress": {
"networkName": "dcos"
}
}
```

DCOS-9749: Enable USER network for Mesos runtime

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

Our default definition has `gpus: 0` which blocks a user from selecting Docker Runtime. But Marathon and Mesos process `gpus: 0` fro Docker correctly. So we shouldn't block it as well.

DCOS-12144: Allow gpus=0 for Docker

---

plugins/services/src/js/components/LogView.js
src/js/events/SystemLogActions.js
src/js/events/__tests__/SystemLogActions-test.js

This PR fixes a bug where it would not reverse the received data, when reading in reverse order.
It also makes sure to always check if we are at the top of the logs, so we don't get stuck at a perceived infinite load at the top.
To test this out, deploy some service that has more than a page of logs and try to page to the top

Re-adding missing reverse of data, when reading reverse

---

src/js/constants/LogFields.js
src/js/stores/SystemLogStore.js
src/js/stores/__tests__/SystemLogStore-test.js
src/js/utils/DateUtil.js
src/js/utils/__tests__/DateUtil-test.js

This PR introduces a new format for log lines that follows the CLI (see here https://github.com/dcos/dcos-cli/pull/817/files#diff-8f3b06e62cf338c8e4e2ac6414447d26R260):

Formatting messages to be equal to CLI format

---

plugins/services/src/js/structs/ApplicationSpec.js

This PR removes an old functionality from the `ApplicationSpec.toJSON` that prohibits instances of type `MESOS` and having an `docker.image` property to scale properly.

DCOS-12327: Removing toJSON from ApplicationSpec

---

plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/TasksView.js
src/js/stores/MesosStateStore.js

Scheduler tasks don't like to be stopped so we disable the stop button if one is selected.
~~@leemunroe - should we hide this button or disable it? If we disable it, I presume we'd also want a tooltip to explain why.~~
**UPDATE**: The stop button is now disabled with a tooltip.
https://mesosphere.atlassian.net/browse/DCOS-10693

DCOS-10693: Prevent stop action for scheduler tasks

---

tests/smoke-cy.js

Open to suggestion on how to fix this, but right now the Config.js file gets bundled with the application and that's where we tell the application how much time to wait before rendering.

Removes integration test that doesn't pass consistently as application loads too fast.

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js

Fixes the checkboxes in the container settings:

Fixing wrong boolean check for container checkboxes

---

plugins/services/src/js/components/VolumeTable.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/volume-detail/VolumeDetail.js

This PR fixes a small bug where the Volumes tab would throw an error when selected. It also adds the `Page` and `Page.Header` component to the `VolumeDetail` page.

Fix Volumes tab bug

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js

This PR moves the locked-icon tooltips from the field label just the icon itself.

DCOS-11855: Move tooltip to icon instead of label

---

src/js/pages/universe/PackageDetailTab.js
src/styles/views/packages/styles.less

The `flush-left` class was removing both margin and padding from the badge.

Fix badge styling on PackageDetail header

---

tests/pages/services/ServicesTab-cy.js

**Note:** Tabs are no longer present (Services|Deployments), hence the deleted test.

Fixing integration tests for ServicesTab

---

src/styles/components/panel/styles.less

This PR fixes a bug where the `:before` and `:after` pseudo elements from `.row` were rendering in Safari and causing the `.panel-grid` children to wrap in Safari.
Before:
After:

DCOS-11886: Prevent .row styles from mucking with .panel-grid children

---

src/js/components/modals/InstallPackageModal.js

This PR fixes some classes that were missed when the `reactjs-components` modals were refactored.
Before:
After:

DCOS-11398: Fix padding in CLI-only package alert modal

---

plugins/services/src/js/pages/task-details/TaskDetail.js

This PR fixes a bug where the Breadcrumbs where removed from the file viewer here: https://github.com/dcos/dcos-ui/commit/ba2595e15c200cd3f26cbf25455ecbb9a8e2e15c#diff-5652f87ace9e089ce90959891680d61dL331
It also corrects how the breadcrumbs work when navigating files:

Breadcrumbs not functioning properly after routes got changed, ref. DCOS-11768 and DCOS-12143

---

plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js

This PR adds a check for the situation when a protocol field is missing from the port mappings

DCOS-12224: Handle missing protocol in app definition

---

docker-compose.yml

To use host resources, this avoids Chrome crashing in container due to it not GCing on time.

Adds flag to docker container.

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

I could not find any other conspicuous Britishisms in the codebase.

Replace British 'behaviour' with American 'behavior'

---

.eslintrc
plugins/services/src/js/reducers/JSONConfigReducers.js
plugins/services/src/js/reducers/serviceForm/RequirePorts.js
plugins/services/src/js/reducers/serviceForm/__tests__/RequirePorts-test.js

This PR adds missing `requirePorts` field when a user specifies a hostPort for her Docker app with a Bridge network. This field is important because otherwise Marathon ignores specified hostPort and uses a random one.

DCOS-12404: Add missing requirePorts field

---

src/js/constants/JobResources.js
src/js/schemas/job-schema/General.js
src/js/structs/Job.js
src/js/structs/__tests__/Job-test.js
src/js/utils/__tests__/JobUtil-test.js

Introduce job resource defaults and use the new constants instead of Mesos constants to properly define job defaults that match the API.
Closes DCOS-9310

DCOS-9310: Adjust default job memory

---

src/js/components/DisplayPackagesTable.js

---
ℹ️ This is the same fix as for master here: https://github.com/dcos/dcos-ui/pull/1689
---
Before:
After:

Adjusting the scroll container listener to be the page content

---

src/js/components/breadcrumbs/JobsBreadcrumbs.js
src/js/pages/jobs/JobDetailPage.js

This PR introduces a status field to the jobs breadcrumbs, allowing an arbitrary job status to be shown. 
The jobs page uses this to show the status of the longest running task associated with a job. This is the same behaviour as the earlier jobs detail page header.

Show job status in job detail page header

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js

---
⚠️  ~~_This branch depends on changes that will be introduced with #1566_~~
---
Improve `MesosStateStore` scheduler task handling by introducing a new method to retrieve the list of scheduler tasks and simplifying the existing methods. These changes will reduce the number of `framework`/`task` list iterations. 
/cc @MatApple

Opimize mesos state store scheduler handling

---

src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js

Improving package search, so `ch` does not match Apache, since we are using startsWith:

Improving the package search, ref. DCOS-5779

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/ServiceStatusWarning.js
plugins/services/src/js/components/ServiceStatusWarningWithDebugInstruction.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/utils/DeclinedOffersUtil.js

This PR displays the rejected offers warning icon & tooltip in the service breadcrumb and moves the corresponding code to a separate component.

DCOS-12274: Show rejected offers warning in service breadcrumb

---

src/js/components/DisplayPackagesTable.js

Reverts dcos/dcos-ui#1689
Fix being applied here: https://github.com/dcos/dcos-ui/pull/1699

Revert "Adjusting the scroll container listener to be the page content"

---

plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/constants/HealtCheckProtocols.js
plugins/services/src/js/reducers/serviceForm/HealthChecks.js
plugins/services/src/js/reducers/serviceForm/__tests__/HealthChecks-test.js
plugins/services/src/js/utils/HealtCheckUtil.js
plugins/services/src/js/utils/__tests__/HealthCheckUtil-test.js

This adds the support for healthchecks without a known protocol. We will omit those from the form

Add Support for health checks with unknown protocols

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

Changed copy from `SERVICE NAME` to `SERVICE ID` which now aligns with the config section (REVIEW & RUN).

Service name > Service ID in service create form

---

plugins/services/src/js/components/forms/HealthChecksFormSection.js

~~BASED on #1670~~ Merged
Added support for healthchecks with unknown protocol in the ui. There might come design suggestion for this feature. With this PR it will be possible to delete healthchecks with unknown protocols from the form.
\cc @leemunroe

show healthchecks with unknown values

---

npm-shrinkwrap.json
package.json

This PR contains a fix for VirtualList scroll event not bubbling: https://github.com/mesosphere/reactjs-components/pull/384
And cnvs peer requirement update to 1.1.4: https://github.com/mesosphere/reactjs-components/pull/379

Updating reactjs-components to v0.16.0-beta.8

---

src/js/constants/JobResources.js
src/js/schemas/job-schema/General.js
src/js/structs/Job.js
src/js/structs/__tests__/Job-test.js
src/js/utils/__tests__/JobUtil-test.js

Introduce job resource defaults and use the new constants instead of Mesos constants to properly define job defaults that match the API.
Closes DCOS-9310

DCOS-9310: Backport default job memory adjustment

---

plugins/services/src/js/service-configuration/PodNetworkConfigSection.js
plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
plugins/services/src/js/utils/ServiceConfigUtil.js
plugins/services/src/js/utils/__tests__/ServiceConfigUtil-test.js

This PR ensures that we display a service address on the review screen and on the config tab only when we have a VIP_* port and `Not Configured` otherwise.
Since our old form is gone that util wen orphan, so I've reused some pieces of code in there and deleted obsolete bits: plugins/services/src/js/utils/ServiceConfigUtil.js

DCOS-12657: Display service name only when VIP_* labels exist

---

src/js/pages/system/OverviewDetailTab.js

ℹ️ See https://github.com/dcos/dcos-ui/pull/1652#issuecomment-269611508 before reviewing
This PR adds hooks to the `OverviewDetailTab` in order to allow plugins to
- manipulate the store_listeners hash
- add their own callbacks on componentDidMount
- manipulate the data for the cluster details `dt` element

DCOS-11493:Add hooks to OverviewDetailTab

---

plugins/services/src/js/utils/ServiceUtil.js

- createSpecFromFormModel
- createSpecFromDefinition
- createFormModelFromSchema
close DCOS-9031

DCOS-9031: Deprecate outdated functions from ServiceUtil

---

src/js/stores/SystemLogStore.js
src/js/stores/__tests__/SystemLogStore-test.js

---
ℹ️ Related PR #1615
---
This PR removes metadata from the logs so we only display `timestamp: MESSAGE` to give more room in the view.

DCOS-12667: Removing redundant metadata from log view, only date and MESSAGE remains

---

src/resources/grammar/SearchDSL.jison

This PR uses `var` instead of `let` in the JISON parser generator because this won't be transpiled by Babel. This fixes an error thrown in any browser that doesn't support the use of `let` variable declarations.

DCOS-12847: Use var instead of let in JISON parser

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js

This PR adds a delayed redirect after a service got destroyed via the `ServiceDestroyModal`.
We have to delay the redirect because Router redirects faster than our code manages to close the modal which results in the Modal inviting you to destroy the root `/` group as well.

DCOS-11957: Add redirect after destroying a service

---

src/js/components/AccessDeniedPage.js

This fixes a bug in Safari where the absence of `flex-grow: 1` prevented the content from being visible, so it was just a blank white page.
After:

DCOS-12431: Apply flex class to AccessDeniedPage

---

src/js/stores/SystemLogStore.js
src/js/stores/__tests__/SystemLogStore-test.js
src/js/utils/DateUtil.js

This PR changes the format of the log timestamp to be `YYYY-MM-DD hh:mm:ss: MESSAGE` e.g. `2017-01-04 06:16:31: Some log message`

Updating log timestamp format

---

webpack/webpack.config.babel.js

`global` is not defined here because it runs outside of the webpack bundle, so we need to use `window` instead.

Use window instead of global in webpack post loader

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

Increases the width of the Service ID field. Why?
* More space for the help text so it doesn't wrap
* Vertical alignment with the fields further down
* More space when working with IDs that contain long group names
* Instances doesn't need to be that wide
Before
After
cc @jfurrow

Increase width of Service ID input field on create flow

---

plugins/services/src/js/service-configuration/ServiceHealthChecksConfigSection.js
plugins/services/src/js/utils/ServiceConfigDisplayUtil.js
src/js/utils/MomentJSConfig.js

This PR addresses the issue with seconds not being displayed in the Health checks review section.
The reason was that `moment.js` library doesn't display the amount of seconds by default like it's not that relevant.
ℹ️  Please note `.humanize()` method doesn't only display seconds by default but it also makes some assumptions on how to round up the numbers. I.e. it will display `a minute` for a value > 45 seconds and `an hour` for a value > 50 minutes. We might want to correct that as well.
Before:
After:

DCOS-12464: Display seconds in the health checks review section

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesContainer-test.js
plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
plugins/services/src/js/containers/tasks/TaskTable.js
src/styles/components/pod-instances-table/variables.less
src/styles/components/task-table/styles.less
src/styles/components/task-table/variables.less
src/styles/index.less

This PR applies column width and display properties to the `TaskTable` via CSS. It uses the same styles that were previously used only for the `PodInstancesTable`. Therefore I renamed the stylesheets and classes to `task-table` and implemented them in the `PodInstancesTable` as well as the `TaskTable`.

DCOS-12222: Apply task table column widths via CSS

---

npm-shrinkwrap.json
package.json
src/js/components/modals/IdentifyModal.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js

Double-check I did the shrinkwrap update correctly please.
Notable updates:
* Updated .button-flush with directional modifiers
* Fixed disabled buttons of type *-link
* Adjusted background of .form-control and .form-control-toggle
* Updated background style of .form-control style variants
* URI encode inline SVG strings
* Updated styling of `disabled` state for `form-control` component
Full diff here for reviewers: https://github.com/mesosphere/cnvs/compare/4e301e8951b74b7c4d6f959ef255651f7da6a11d...d2eb4d1477a0aab827071db210a7c638f9b3cc45

Updated CNVS from 1.1.4 to 1.1.6

---

plugins/services/src/js/reducers/serviceForm/Volumes.js
plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js

Host volumes should only be rendered if the
runtime type is MESOS or DOCKER or a docker image
has been set
close DCOS-12289

DCOS-12289: Fix json generation for host volumes

---

plugins/services/src/js/containers/tasks/TaskTable.js
src/styles/components/task-table/styles.less

This PR fixes the following:
* the `TaskTable`'s key for the `host` column was incorrect, so the class wasn't being applied properly
* the responsiveness has been adjusted so that the `host` column appears at screen size medium and up, rather than large and up

Fix TaskTable column responsiveness

---

src/styles/components/buttons/styles.less

This PR unsets the `display: inline-flex` property applied by CNVS. `button` elements cannot be flex containers in some browsers (notably Safari).
Before:
After:
I submitted an issue for CNVS here: https://github.com/mesosphere/cnvs/issues/83

DCOS-12773: Fix button text alignment in Safari

---

npm-shrinkwrap.json
package.json

Changes:
* ~~bubble scroll events from `VirtualList` https://github.com/mesosphere/reactjs-components/pull/384~~
* removed keydown mixin resulting in dramatic performance improvements https://github.com/mesosphere/reactjs-components/pull/380
* updated CNVS to 1.1.6 https://github.com/mesosphere/reactjs-components/pull/381

Update reactjs-components to 0.16.0-beta.9

---

src/styles/components/typeahead/styles.less
src/styles/components/typeahead/variables.less

This PR fixes the alignment of the typeahead dropdown and removes some outdated margin overrides.
Before:
After:

DCOS-12618: Fix typeahead dropdown alignment

---

plugins/services/src/js/components/TaskDirectoryTable.js

Adds the `clickable` class to an `a` tag without an `href`

Display pointer cursor for directories in TaskDirectoryTable

---

src/js/components/JobSearchFilter.js
src/js/pages/__tests__/JobsTab-test.js
src/js/pages/jobs/JobsTab.js

This PR removes the `QueryParamsMixin` and `SaveStateMixin` (for consistency) from the `JobsTab`, and fixes an issue where letters were dropped when typing in the Jobs search filter.
In detail:
* `QueryParamsMixin` is not using the `nextProps` coming from the `componentWillReceiveProps` in order to synchronize the component state from the query parameters, and
* Mix-ins are considered deprecated, therefore I didn't fix the problem there, rather I re-used the same approach as from the `ServicesContainer`
* `SaveStateMixin` was racing the `QueryParamsMixin` and causing another set of problems. However I do agree that we are losing some of the functionality and perhaps has to be re-introduced in another way (without using mix-ins).

DCOS-12642: Fixing lost characters when typing in Jobs filter

---

src/styles/components/banner-plugin/styles.less
src/styles/components/breadcrumbs/styles.less
src/styles/components/collapsing-string/styles.less
src/styles/components/page-header/styles.less
src/styles/components/typography/styles.less
src/styles/content/tables/styles.less

This PR resets the `line-height` for all elements that use the `text-overflow` property. This prevents the descenders from being clipped in some browsers.
Before:
After:
Before:
After:

DCOS-12415: Fixed clipped descenders in elements that use text-overflow

---

plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js

* Uses `Host Port` for the column heading rather than the vague `Port`
* Adds a `Container Port` column when network type is anything but `HOST`
* Fixes the service address string concatenation when network type is anything but `HOST`

DCOS-12661: Differentiate between Host and Container Port

---

plugins/services/src/js/components/forms/NetworkingFormSection.js

Switching a Mesos Runtime app Network type leaves you with a wrong form for service endpoints
This PR fixes demonstrated behavior:

DCOS-12660: Default network type to HOST

---

plugins/services/src/js/service-configuration/PodContainerConfigSection.js
plugins/services/src/js/service-configuration/PodGeneralConfigSection.js

I am quite confident this was fixed in one of my past PRs but I could have forgotten to push... this PR makes sure no `0`s appear when a conditional rendering case fails to match because of number 0.

Fixing conditional rendering on pod sections

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/pages/task-details/TaskLogsTab.js
src/js/stores/SystemLogStore.js
src/js/stores/__tests__/SystemLogStore-test.js

Logs 1 of 2 PR: https://github.com/dcos/dcos-ui/pull/1736
Logs 2 of 2 PR: https://github.com/dcos/dcos-ui/pull/1745
This PR also resolves: DCOS-12737
This PR fixes a few issues related to the same thing - making the paging become smoother:
- It initializes the logs no matter what response comes from the server, so we do not see 'Empty Log' when there is an error.
- It stop debouncing `componentDidUpdate` in  the log view, so it actually goes to bottom initially
- It removes log window so the position calculation in `componentDidUpdate` continues to work
- It lets the container handle when to retrieve a previous page, instead of assuming an ongoing request when at the top.
Initially, the paging goes pretty fast, but eventually the journald bug manifests and loading becomes increasingly …

[Logs 1 of 2] DCOS-12769: Make paging in log view a bit snappier

---

foundation-ui/mount/Mount.js

This PR fixes the `Mount`'s `wrapper` `propTypes` definition. I believe this is the intended behavior, as the `wrapper` prop is passed as the first argument to `React.createElement` which can only be a string, function, or class (in this case, `PropTypes.func` covers both a function and class).
cc @mlunoe @orlandohohmeier

Fix Mount's wrapper propType

---

foundation-ui/mount/__tests__/Mount-test.js
foundation-ui/utils/ReactUtil.js
foundation-ui/utils/__tests__/ReactUtil-test.js

This PR prevents `Mount` from wrapping a singular registered component component.
This is necessary for me to predictably render the grid of options in the create service modal. I'm fairly confident it's desirable everywhere because it doesn't force any component to be wrapped, unless there are more than 1 components to render, or the owner of `Mount` has explicitly declared it.
cc @orlandohohmeier I discussed this offline with @mlunoe, but it would be nice if you could review this as well.

Prevent Mount component from wrapping singular registered child components

---

plugins/services/src/js/components/ServiceStatusWarning.js
plugins/services/src/js/containers/pod-debug/PodDebugContainer.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
plugins/services/src/js/utils/DeclinedOffersUtil.js

This PR hides the declined offers funnel & table data from a service's debug tab until the service has been waiting or over 5 minutes.

DCOS-12405: Conditionally show declined offers funnel &table

---

src/resources/grammar/SearchDSL.jison

This PR removes the desctructuring assignment which was causing `UglifyJS` to throw an error. This file is not transpiled so we can't use ES6 features here.

DCOS-12867: Fix un-minified JS in production build

---

tests/_fixtures/1-app-for-each-health/summary.json
tests/_support/index.js
tests/pages/nodes/NodesPage-cy.js

Adding integration tests for nodes page

---

src/js/components/form/FieldError.js
src/js/components/form/FieldHelp.js

This PR uses `.form-control-feedback` classes for both errors and help text. This results in both being red in color when there's an error, but that will be handled separately.
~~(hold until https://github.com/dcos/dcos-ui/pull/1691 merges)~~
Related PRs:
https://github.com/dcos/dcos-ui/pull/1691
https://github.com/mesosphere/cnvs/pull/68
https://github.com/mesosphere/reactjs-components/pull/381#issuecomment-269245976

DCOS-11911: Use new classes for errors and help text

---

plugins/services/src/js/pages/task-details/TaskLogsTab.js
src/js/utils/SystemLogUtil.js
src/js/utils/__tests__/SystemLogUtil-test.js

Resolves DCOS-12761 as well.
This PR updates the download endpoint for the logs:
Please review using a cluster from this PR: https://github.com/dcos/dcos/pull/1122

DCOS-12858: Update download endpoint for logs

---

src/js/pages/jobs/JobDetailPage.js

The error screen in the Jobs page was not wrapped in a `<Page />` component. This PR fixes this.
Closes DCOS-12741

DCOS-12741: Wrapping jobs error page in a <Page/>

---

plugins/services/src/js/components/forms/NetworkingFormSection.js

This PR fixes a bug where the form displays the `containerPort` field when the network type has not yet been defined.

Hide containerPort field if network type is not defined

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Steps to reproduce:
1. Set the runtime to DOCKER
2. Check `forcePullImage`
3. Change to runtime to UCR
4. `forcePullImage` will still show up in the JSON
Before:
After:
This PR fixes that issue by letting the individual container settings handle their own results over using simpleReducers.

Fix forcePullImage bug, where it would show up in JSON when runtime is UCR

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This PR adds a heading to the Containers section in a multi-container form.
Before:
After:

DCOS-12971: Add heading to Containers section

---

src/styles/components/badges/styles.less
src/styles/components/badges/variables.less
src/styles/index.less

This PR adds styling for `.badge` elements when nested inside buttons and dropdown list items.

DCOS-11754: Style badges inside buttons

---

plugins/services/src/js/service-configuration/PodNetworkConfigSection.js
plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js

This PR changes the _Not Configured_ text to _Not Enabled_ for disabled LB service endpoints.

DCOS-12480: Display 'Not Enabled' for disabled service endpoints

---

src/js/pages/system/OverviewDetailTab.js

This PR adds the `General` heading and a `Public IP` entry to the cluster details page.

DCOS-12449: Add Public IP to cluster details page

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
src/js/components/JSONEditor.js

This PR fixes JSONEditor tab nav issue and removes tabindex from the documentation link so that it doesn't get in the way.
I also extracted a CNVS issue of missing :focus selectors: https://mesosphere.atlassian.net/browse/DCOS-13175

DCOS-12458: Fix keyboard tab navigation

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Why:
* otherwise these's no way applyPatch can delete portMappings. General idea that it's applyPatch's job to remove empty values, reducers should return all of them
DCOS-13075 #close

DCOS-13075: Keep empty values on `docker` field

---

plugins/services/src/js/containers/tasks/ServiceTasksContainer.js
plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/TasksView.js

This PR disables the task restart button when the service is deploying.
Here's the tooltip that appears:

DCOS-9159: Disable tasks' restart button while its service is deploying

---

foundation-ui/utils/ReactUtil.js

Not a big deal, just spelling ReactUil -> ReactUtil

Spelling: ReactUil -> ReactUtil

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/validators/MarathonAppValidators.js

This PR introduces a validator that emits an error when `uris` and `fetch` is defined, prompting the users to use `fetch` in favour of `uris`.

DCOS-10182: Adding deprecation warning for `uris`

---

plugins/services/src/js/components/LogView.js

This PR removes word wrapping from logs.
Before:
After:

DCOS-8852: Remove word-wrap logs

---

plugins/services/src/js/containers/services/ServicesTable.js
src/styles/components/service-table/styles.less

This PR moves the column width and visibility styles for the `ServicesTable` to its an external stylesheet, following the same pattern as other tables the UI.
It also:
* increases the width of the resources columns to prevent text wrapping
* removes the `@base-spacing-unit * x` math for the status column width and instead uses explicit pixel values

DCOS-12560: Move column style properties to external stylesheet

---

src/styles/components/configuration-map/styles.less

This PR forces text to overwrap in the `.configuration-map-label` and `.configuration-map-table-label` classes.
Before:
After:

DCOS-13282: Force text wrapping in configuration-map-labels

---

plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/utils/ServiceConfigUtil.js
plugins/services/src/js/utils/__tests__/ServiceConfigUtil-test.js
src/js/constants/Networking.js

This PR addresses the issue of the load balanced checkbox not removing VIP label from the app definition. It also keeps all non-VIP labels there as it is what we want to do according to the documentation.

DCOS-13109: Fix Load balanced checkbox for USER network

---

plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/ApplicationSpec.js
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/__tests__/Application-test.js
plugins/services/src/js/structs/__tests__/Service-test.js

This PR tries to move the `cleanServiceJSON` to the most appropriate place, in order for it to be called only when it makes sense and not every time.
Ideally, I would put it in `createServiceFromResponse` , but I thought that `Application` **can** contain additional ("state"?) information, but `ApplicationSpec` **should not**.

DCOS-13184: Moving cleanServiceJSON to the correct place

---

README.md

That one appeared during the on-site session. In README we ask for node 4.x and npm 3.x but we test for 4.4.x and 3.9.x respectively. Since node 4.7.2 and npm 3.10.10 are available our README requirement is wrong.

Be more specific on the required versions of node and npm

---

foundation-ui/stores/DCOSStore.js
foundation-ui/stores/__tests__/DCOSStore-test.js
plugins/nodes/src/js/pages/nodes/NodeDetailTaskTab.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/volume-detail/ServiceVolumeContainer.js
plugins/services/src/js/containers/volume-detail/TaskVolumeContainer.js
plugins/services/src/js/pages/__tests__/DeploymentsTab-test.js
plugins/services/src/js/pages/services/DeploymentsTab.js
src/js/pages/DashboardPage.js
src/js/pages/__tests__/JobsTab-test.js
src/js/pages/jobs/JobsTab.js

---
ℹ️   _This PR basically cherry-picks a DC/OS UI 1.8 fix (#1303) into master, which wasn't forwarded earlier due to the planned GraphQL refactoring._
---
Rename `dataProcessed` to `serviceDataReceived` and introduce a new job specific data received getter to entangle the Job and Service data received/processed behavior. This changes will make sure that we don't block the Job table rendering in case we didn't get any Service data,
which in some cases resulted in an unusable UI.
Closes DCOS-11160

DCOS-11160: Adjust the DCOSStore data received flags

---

plugins/services/src/js/components/modals/CreateServiceJsonOnly.js
src/js/components/JSONEditor.js
src/styles/components/modal/full-screen/styles.less
src/styles/components/modal/full-screen/variables.less

Change the fullscreen modal side panel positioning to use position `right` instead of transform `translateX` as `transform` creates a new stacking context and the containing block is changing the context which results in "wrong" positions.
For more details please see:
https://drafts.csswg.org/css-transforms-1/#transform-rendering
With this change in place we no longer need the hacks to correct the Ace editor tooltip position, as position fixed (used to position the tooltip) is working as expected.

Fix Ace editor tooltip positioning

---

src/js/components/modals/InstallPackageModal.js

Previously, when a CLI-only package was selected in the package page, selecting a regular package would result in the CLI-only warning appearing until the new modal content loaded in. This was due to a combination of the CosmosStore holding state based on the UI, and the isLoading state in the modal not properly being reflected. See this [moving picture](https://cl.ly/373R341y1l1q) for the bug in action.

Fix package installation modal loading state

---

plugins/services/src/js/utils/MarathonErrorUtil.js
plugins/services/src/js/utils/__tests__/MarathonErrorUtil-test.js

This utility exposes the `MarathonErrorUtil.parseErrors` function that normalises whatever marathon error response into an internal representation of an array of error messages.
_This PR implements the `Marathon Error Parsing` task in the spec document: https://docs.google.com/document/d/1kwdPxBo3UlRZvMxLLIUqSZqLlUJitEuIAWderUgWY1c/edit#heading=h.thdpdh4mx6uj_

DCOS-13362: [1/7] Error Normalisation: Introduce MarathonErrorUtil

---

src/js/structs/Job.js

This PR fixes a bug that occurs if somebody pastes a wrongly-formatted job spec, that uses `schedules: { }` instead of `schedules: [ {} ]`.
For example, as seen [here](https://dcos.io/docs/1.9/usage/jobs/getting-started/):
```json
{
"id": "myjob",
"description": "A job that sleeps regularly",
"run": {
"cmd": "sleep 20000",
"cpus": 0.01,
"mem": 32,
"disk": 0
},
"schedules": {
"id": "sleep-schedule",
"enabled": true,
"cron": "20 0 * * *",
"concurrencyPolicy": "ALLOW"
}
}
```

DCOS-13238: Ensuring Job.getSchedules always returns an array

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js

⚠️ There's no green light to 24x24 icon, due to the time lag. Yet I like how it looks and think that this will be the decision. Anyways please check the discussion before hitting that merge button https://mesosphere.atlassian.net/browse/DCOS-12974
---
This PR 
1. adds margin between the network type dropbox and the header
2. reduces size of the container icon
Before:
After:

DCOS-12974: Use smaller container icon

---

plugins/nodes/src/js/pages/nodes/NodeDetailPage.js

Sometimes going to the Node detail page would throw an exception because the request for mesos state took too long and we weren't waiting for it before rendering.

Waits till we receive mesos state.json before rendering Node detail.

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js

This PR adds tooltips and help text aligning it with the docs

Aligning environment section with doc help text and tooltips

---

src/styles/components/charts/styles.less
src/styles/components/nodes-grid-view/styles.less
src/styles/components/scrollbar/styles.less
src/styles/components/tooltip/styles.less
src/styles/layout/header/styles.less
src/styles/variables/variables-z-index.less
src/styles/vendor/cnvs/layout/variables.less

Includes the single-line commit from #1838 
This PR removes unused `z-index` variables and consolidates their assignment. It also moves all rogue `z-index` property assignments that weren't using a variable (except one in `service-sidebar` which needs to be removed entirely).

Clean up z-index variable assignments

---

src/styles/variables/variables-z-index.less

Tooltips will now render above dropdown menus.

DCOS-12594: Give tooltips a higher z-index than dropdowns

---

plugins/services/src/js/utils/HostUtil.js
plugins/services/src/js/utils/__tests__/HostUtil-test.js

Introduce a new `stringToLabel` util and change the way the `stringToHostname` util works to align them with the respective DC/OS component. The new implementation follows RFC-952 and mirrors the `dcos/mesos_state`  implementation.
Please see dcos/mesos_state#22 as well as dcos/mesos_state#21 for improved/added test cases which illustrate how `dcos/mesos_state` is transform strings.
Closes DCOS-11890

DCOS-11890: Fix the string to hostname util

---

plugins/services/src/js/constants/ServiceErrorTypes.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js

---
~⚠️  This PR depends on #1830 - ( [See the diff](https://github.com/dcos/dcos-ui/compare/ic/feat/error-message-refactoring-1...ic/feat/error-message-refactoring-2?expand=1) )~
---
This commit ensures that the response from MarathonAppValidators complies with the structured agreed in the spec document.
_This PR implements the `Normalize internal error structure` task in the spec document: https://docs.google.com/document/d/1kwdPxBo3UlRZvMxLLIUqSZqLlUJitEuIAWderUgWY1c/edit#heading=h.thdpdh4mx6uj_

DCOS-13362: [2/7] Error Normalisation : Adapt MarathonAppValidators

---

src/js/utils/DataValidatorUtil.js
src/js/utils/__tests__/DataValidatorUtil-test.js

---
⚠️  This PR depends on #1832 - ( [See the diff](https://github.com/dcos/dcos-ui/compare/ic/feat/error-message-refactoring-2...ic/feat/error-message-refactoring-3?expand=1) )
---
This commit ensures that DataValidatorUtil.errorArrayToMap will behave properly when fed an empty path to the error message. Currently there were some issues in the way the functional lenses were setting the path.
_This PR implements the `Normalize internal error structure` task in the spec document: https://docs.google.com/document/d/1kwdPxBo3UlRZvMxLLIUqSZqLlUJitEuIAWderUgWY1c/edit#heading=h.thdpdh4mx6uj_
Closes DCOS-13223

DCOS-13362: [3/7] Error Normalisation: Handling empty paths in DataValidatorUtil

---

src/js/components/FluidGeminiScrollbar.js

Change the `componentWillUnmount` method to use `Node.prototype.removeChild` as `ChildNode.prototype.remove` is still experimental and not supported by the Internet Explorer.
Closes DCOS-13456

DCOS-13456: Fix fluid gemini scrollbar stylesheet handling

---

src/js/utils/HostUtil.js
src/js/utils/__tests__/HostUtil-test.js

---
ℹ️   _This branch backports changes introduced with #1809 to `release/1.8`_
---
Introduce a new `stringToLabel` util and change the way the `stringToHostname` util works to align them with the respective DC/OS component. The new implementation follows RFC-952 and mirrors the `dcos/mesos_state`  implementation.
Please see dcos/mesos_state#22 as well as dcos/mesos_state#21 for improved/added test cases which illustrate how `dcos/mesos_state` is transform strings.
Closes DCOS-11890

DCOS-11890: Adjust string to hostename util

---

src/js/components/JSONEditor.js
src/js/components/__tests__/JSONEditor-test.js

---
~⚠️  _This branch depends on changes that will be introduced with #1831._~
---
Adjust the JSON Editor change handling to properly handle interfering prop updates triggered by the surrounding components.
* Introduces a new method to get the JSON "state" from the JSON text
* Change the update JSON state method to only assign new properties
* Reorder the handle change statements to prevent interfering updates
Closes DCOS-13195

DCOS-13195: Adjust the JSON Editor change handling

---

src/styles/components/icons/styles.less

This PR fixes a bug that I introduced in this PR: https://github.com/dcos/dcos-ui/pull/1782
I wrote the CSS for a situation that I ended up not using, and the style I created is overly generic for its intended purpose anyway.
Before:
After:

Fix nested icon styling

---

src/styles/content/tables/styles.less

This PR fixes the purple `:hover` color for table cell links.
Before:
After:

Fix table link styling

---

src/styles/components/tooltip/styles.less

Before, note overlarge font and unreadable grey colour:
After:

Fix jobs tooltip styles

---

src/js/components/modals/IdentifyModal.js
src/js/components/modals/InstallPackageModal.js
src/js/components/modals/JobFormModal.js

This PR removes the `.button-large` classes from the UI.
After this PR, they'll only exist in `ServiceFormModal` (which needs to be removed in a separate PR :fire:) and some of the `/styles/` components, which are there intentionally.

DCOS-12573: Remove .button-large classes from UI

---

src/js/components/ServiceForm.js

⚠️  Some 1.8 codebase here, PR targets 1.8
---
When we have a container app with a Bridge network and want to go to HOST network the UI would just discard ports from `portDefinitions` and put `containerPort` instead which can result in a conflict.
This PR ensures that the UI, as requested, keeps host ports and discards container ports instead.
Since we don't have access to the `portDefinitions` field in the `ServiceForm` I'm using `servicePort` which is always equal to a `portDefinitions[*].port`

DCOS-11559: Keep host ports when switching a container network to HOST

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/validators/MarathonAppValidators.js

This validator ensures that the container volumes do not contain '/' in the
containerPath property.

DCOS-12442: Adding containerVolmesPath validator

---

plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js

This PR changes the layout in the `MultiContainerHealthChecksFormSection` in order to make it similar to the `MultiContainerNetworkingFormSection`.
_Note that the `+ADD HEALTH CHECK` button is broken in master. #1728 fixes this bug_
Before:
After:

Fixing styling of MultiContainerHealthChecksFormSection

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/PortMappings.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortDefinitions-test.js
plugins/services/src/js/service-configuration/PodNetworkConfigSection.js
plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
plugins/services/src/js/utils/ServiceConfigUtil.js
plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/ServiceConfigUtil-test.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js

This PR ensures we display a consistent and hopefully correct value for a service address across the UI.
To make it possible:
- VIP label generation function has been extracted
- Multi and Single container network forms have been changed
- Multi and Single container config review screens have been changed
Additionally I've made more strict the rule of checking if a VIP has been changed by a user, yet there's an outstanding issue I decided to extract https://mesosphere.atlassian.net/browse/DCOS-13394

DCOS-12703: Display correct service address across the UI

---

plugins/services/src/js/components/DeclinedOffersTable.js
plugins/services/src/js/components/RecentOffersSummary.js
src/styles/components/funnel-graph/styles.less
src/styles/components/funnel-graph/variables.less

This PR adds a key to the funnel graph and changes the default sort to `hostname`. It also fixes a bug with the bar graph widths that @leemunroe pointed out.

DCOS-12651 DCOS-12414: Declined Offers: Add funnel graph key & adjust table sorting

---

src/js/components/Sidebar.js
src/styles/layout/sidebar/styles.less
src/styles/layout/sidebar/variables.less

This PR makes the sidebar dock icon visible at all times by moving it outside of the sidebar's navigation scroll container.
It also adds the `inverse` class on the sidebar's scroll container to properly style the scrollbars on the dark background. (not sure how I missed this before)
Before:
After:

DCOS-12595: Move sidebar dock icon outside navigation list scroll container

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Apparently mesos does not support MESOS containerizer and the `portMapping` property to be present in the `docker` object. This PR ensures this does not happen

DCOS-13246: Disabling portMapping when using MESOS + Virtual Network

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js

This PR adds support for multiple values in protocol array field. To achieve it I replaced radio buttons with checkboxes and changed underlying data format and logic. I also changed the order of checkboxes, so that single and multi container forms match.
As Mesos doesn't restrict any specific values in the array, nor does the Marathon, I also enhanced this logic. So that @philipnrmn could use GOPHER :) 
Depends on the Single-container version: #1820

DCOS-12628: Allow tcp & udp simultaneously for multi container

---

foundation-ui/stores/DCOSStore.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/components/modals/ServiceModals.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-configuration/ServiceConfigurationContainer.js
plugins/services/src/js/containers/service-configuration/__tests__/ServiceConfigurationContainer-test.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/service-detail/__tests__/ServiceDetail-test.js
plugins/services/src/js/containers/services/ServiceTreeView.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/routes/services.js
plugins/services/src/js/service-configuration/ServiceConfigDisplay.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/utils/ServiceUtil.js
src/js/components/modals/FullScreenModal.js

Service Modal Routes 1 of 3: https://github.com/dcos/dcos-ui/pull/1828
Service Modal Routes 2a of 3: https://github.com/dcos/dcos-ui/pull/1853
Service Modal Routes 2b of 3: https://github.com/dcos/dcos-ui/pull/1871
Partly closes: DCOS-12423
Essentially this PR should not make a difference in functionality, other than the `NewCreateServiceModal` now is routed with `/create` and `/edit:version` routes.
One thing to note is that it is possible to go to a group route and then add `/edit` at the end, which will open the modal in an edit mode. It is possible to change the group into an application if it is empty, otherwise Marathon will complain and provide a reasonable error message:
Since this is actually possible, I chose to leave it as is. Also, I don't expect many people will enter that …

[Service Modal Routes 1 of 3] DCOS-12423: Adding routes to the service create modal

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
src/js/components/form/AddButton.js
src/js/components/form/AdvancedSectionLabel.js
src/js/components/form/index.js
src/styles/components/advanced-section/styles.less
src/styles/components/advanced-section/variables.less

This PR introduces an `AddButton` component for forms which produces the proper classnames. It's meant to be implemented on any form that has an `Add` button for duplicable field sets.
It also fixes the inconsistency between the `AdvancedSectionLabel` component and the `AddButton` component.

DCOS-12581: Create and implement AddButton component

---

src/js/components/ClipboardTrigger.js

1 of 3: #1822 
2 of 3: #1826 — [diff between 1 and 2](https://github.com/dcos/dcos-ui/compare/john/feature/extend-clipboard-trigger...john/DCOS-12462/new-user-account-menu-components?expand=1)
3 of 3: #1827  — [diff between 2 and 3](https://github.com/dcos/dcos-ui/compare/john/DCOS-12462/new-user-account-menu-components...john/DCOS-12462/sidebar-user-account-menu?expand=1)
This PR extends the functionality of the `ClipboardTrigger` component. It allows custom trigger buttons instead of just the clipboard icon and adds an optional `onTextCopy` callback.
I also removed the Safari exclusion because Safari 10 supports the Clipboard API. As of December 2016, Safari 10 is at 2.92% global usage while Safari 9.0 + 9.1 is at 1.37% combined (and dropping quickly: …

[1 of 3: User Account Menu] DCOS-12462: Extend ClipboardTrigger functionality

---

src/js/components/Sidebar.js

Previously, if you loaded the UI at a route other than `/`, and that route was a nested item (e.g. `/universe/packages`), the sidebar would not show the parent item as expanded.
Now, the Sidebar adds the parent route to `state.expandedItems` in `componentWillMount` so it will be expanded when it renders.

DCOS-12565: Add chosen route to expandedItems at mount

---

src/js/components/UserAccountDropdownTrigger.js
src/styles/components/dropdown-menus/styles.less
src/styles/components/dropdown-menus/variables.less
src/styles/components/user-account-dropdown/styles.less
src/styles/components/user-account-dropdown/variables.less

1 of 3: #1822 
2 of 3: #1826 — [diff between 1 and 2](https://github.com/dcos/dcos-ui/compare/john/feature/extend-clipboard-trigger...john/DCOS-12462/new-user-account-menu-components?expand=1)
3 of 3: #1827  — [diff between 2 and 3](https://github.com/dcos/dcos-ui/compare/john/DCOS-12462/new-user-account-menu-components...john/DCOS-12462/sidebar-user-account-menu?expand=1)
This PR introduces a new component, `UserAccountDropdownTrigger`, which will be used to trigger the new user account menu. It also updates the styling of the dropdown itself.
This doesn't make any changes that you can see in the UI immediately; that will come in a follow-up PR.
Here's a sneak peak:

[2 of 3: User Account Menu] DCOS-12462: Create new user account menu components

---

src/styles/views/create-service-modal/styles.less

Fixes a missing `-` to negate the variable's value. This only occurred at the `medium` breakpoint.
Before:
After:

Fix create service modal's navigation divider

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
src/js/components/form/DeleteRowButton.js
src/js/components/form/FormGroupContainer.js
src/styles/components/form-elements/form-row/styles.less

This PR
- vertically centres the delete icons on duplicable rows in the service create
form
- adds a 'delete' tooltip to form group containers in the service create form
Before centering the delete icons:
Before adding tooltips to the group containers:
https://cl.ly/0V46200O1L08

Duplicable row delete button improvements

---

src/styles/components/menu-tabbed/styles.less

This PR uses `width` instead of `flex-basis` to set the menu's width.
This is necessary because we don't want the width of the menu to ever change depending on its content or its siblings' content.

Use width instead of flex-basis for vertical tab menu

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js

This PR unblocks GPUs field for Mesos Runtime as it is the same thing as UCR and confirmed to support GPUs as well.
as GPUs field is still under the Container section we might want to reconsider its location in the form @leemunroe

DCOS-13481: Feature (service form): allow GPUs for Mesos runtime

---

plugins/services/src/js/containers/pod-detail/PodDetail.js

Somehow the action buttons menu on the pod detail page got broken. This PR fixes it.

DCOS-13585: Fix (PodDetail): destructure props not props.pod

---

src/js/components/JSONEditor.js
src/js/components/__tests__/JSONEditor-test.js

This PR fixes an issue with `JSONEditor` where `getNewJsonState` returns `undefined` and breaks `updateLocalJsonState`

Handle `null` cases in `updateLocalJsonState`

---

src/js/components/breadcrumbs/JobsBreadcrumbs.js
src/js/pages/jobs/JobDetailPage.js

This PR adds the schedule icon to the Jobs breadcrumb.
cc @leemunroe

DCOS-13439: Add schedule icon to Jobs breadcrumb

---

plugins/services/src/js/reducers/serviceForm/Containers.js

Two things:
1. Fixing what I've broken in https://github.com/dcos/dcos-ui/commit/4b53578ae8ae8964bbf7b8ff9e47c35104da4056#diff-902ecd3b5705fbea2c5bb83a4a2c703aR185
2. Use hostPort for VIP when container port is undefined
if while testing you encounter the problem that `containerPort: null` throws an error -> there's a fix for that https://github.com/dcos/dcos-ui/pull/1894

DCOS-13586: Fix pods JSON parser

---

src/js/pages/system/RepositoriesTab.js

This PR removes `rightAlignLastNChildren` prop that effectively aligns filter to the left side
http://0.0.0.0:4200/#/settings/repositories

DCOS-12567: Fix RepositoriesTab: left align filter input

---

plugins/services/src/js/components/modals/CreateServiceJsonOnly.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/constants/ServiceErrorTypes.js
plugins/services/src/js/service-configuration/ServiceConfigDisplay.js
plugins/services/src/js/utils/MarathonErrorUtil.js
plugins/services/src/js/utils/__tests__/MarathonErrorUtil-test.js
src/styles/components/alert/styles.less

---
~⚠️  This PR depends on #1833 - ( [See the diff](https://github.com/dcos/dcos-ui/compare/ic/feat/error-message-refactoring-3...ic/feat/error-message-refactoring-4?expand=1) )~
~⚠️ This PR depends on https://github.com/dcos/dcos-ui/pull/1848 (raml-validator-loader v0.1.8)~
---
This commit includes the following:
- Adds NewCreateServiceModal.getAllErrors function that is collecting
all errors, including validation and marathon errors
- Removes validation from NewCreateServiceModalForm & CreateServiceJsonOnly
- Fixes syling of the alert dialog in form and the review screen
**Note that this PR makes the error validation more "aggressive", meaning that you will instantly see an error when you edit a form field. This will be fixed on the next PR**
_This PR implements the `Normalize internal …

DCOS-13362: [4/7] Error Normalisation: Concentrate error handling

---

npm-shrinkwrap.json
package.json
src/js/events/CosmosPackagesActions.js

This PR updates `mesosphere-shared-reactjs` to version 0.0.24 from 0.0.22 (which removes a default timeout of 2 seconds for all requests), and removes the 10 second timeout used in all requests made in `CosmosActions.js`.

Remove default timeout from Cosmos actions

---

.eslintrc
npm-shrinkwrap.json
package.json

This PR enables caniuse check for our js code.
I declared supported browsers to be 2 latest versions of all major browsers + IE11
Major browsers are:
- Chrome for Google Chrome.
- Firefox or ff for Mozilla Firefox.
- Explorer or ie for Internet Explorer.
- Edge for Microsoft Edge.
- iOS or ios_saf for iOS Safari.
- Opera for Opera.
- Safari for desktop Safari.
- ExplorerMobile or ie_mob for Internet Explorer Mobile.
Looks like our code is compatible. I tested by adding `navigator.serviceWorker` in a random file.

DCOS-13660: Feature (eslint): enable caniuse check

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/Residency.js

This PR fixes the situation when a Mesos app with local volumes will be switched to UCR as you edit JSON.
I added additional check into parser so that it looks not only for `container.type === MESOS` but also for `container.docker.image` not to be empty.
In addition to that I added a fix that remove Residency as we remove the last localVolume.
Please refer to the original issue https://mesosphere.atlassian.net/browse/DCOS-12247 to come up with a test plan.

DCOS-12247: Fix for flipping runtime type Mesos to UCR

---

plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/HealthChecks.js
plugins/services/src/js/reducers/serviceForm/MultiContainerHealthChecks.js
plugins/services/src/js/reducers/serviceForm/Volumes.js
src/js/utils/ReducerUtil.js
src/js/utils/__tests__/ReducerUtil-test.js

In some places in the reducers we are using plain `parseInt` when we are processing a value. This results in some unwanted `NaN` values being collected to the output. 
This PR introduces the parseIntValue function that applies parseInt to the given value and it returns it's numerical representation only if it is indeed a number. Otherwise it passes through the value.
It allso replaces `parseInt(value, 10)` in all other places it was used

DCOS-13707: Safer alternative to parseInt for reducers

---

src/styles/components/menu-tabbed/styles.less

This PR fixes a bug I introduced in #1870. These overflow properties should only be applied to vertical tabs.
Before:
After:

Bug: Fix page header tab alignment

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/service-configuration/ServiceConfigDisplay.js

---
⚠️  ~~This PR depends on #1834 - ( [See the diff](https://github.com/dcos/dcos-ui/compare/ic/feat/error-message-refactoring-4...ic/feat/error-message-refactoring-5?expand=1) )~~
---
This commit introduces a series of changes in order to show errors
in the most optimal way. In a bit more detail:
- Marathon errors now persist after the review screen, back to the form, until the user has edited the form.
- The "Review & Run" button is now always enabled, even if there are errors in the form.
- NewCreateServiceModalForm tracks which fields the user has edited and shows real-time validation errors only on them. The rest of the errors are muted.
- When the user clicks "Review & Run", a showAllErrors= bypass flag is set and forces the form to display all errors. Not only in-line, next to the …

DCOS-13362: [5/7] Error Normalisation: Show errors only when needed

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/utils/ServiceConfigUtil.js
plugins/services/src/js/validators/VipLabelsValidators.js
plugins/services/src/js/validators/__tests__/VipLabelsValidators-test.js
src/js/constants/Networking.js

This PR adds a custom validator for VIP labels
Why:
* because there's no other service in the stack that performs that validation but then Minuteman will fail not finding a port
This change addresses the need by:
* I introduced a new custom validator for single and multi container and added it to the form and JSON only editor
DCOS-13519 #close

DCOS-13519: Add vip port validation

---

src/js/pages/system/OverviewDetailTab.js

[DCOS-12416] Use ConfigurationMap in OverviewDetailTab

---

plugins/services/src/js/components/ServiceBreadcrumbs.js

This PR fixes an issue where a variable `id` is reassigned to a JSX object. This is problematic because immediately after this, we URI encode the `id` and then pass it to the `Link` component.

DCOS-13579: Avoid URI encoding JSX in ServiceBreadcrumbs

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Change the container JSON reducer to always output volumes as omitting empty volumes results in wrong patch updates. This change fixes issues with wrong JSON after a volumes was removed.

Fix service form volume handling

---

src/styles/components/form-elements/styles.less

This PR sets a contrasting foreground color for disabled fields.
This should be fixed in CNVS ([here's the issue](https://github.com/mesosphere/cnvs/issues/76)). cc @ashenden 
Before:
After:

Fix .form-control:disabled color

---

.eslintrc
foundation-ui/mount/Mount.js
foundation-ui/stores/DCOSStore.js
npm-shrinkwrap.json
package.json
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js
plugins/services/src/js/components/dsl/FuzzyTextDSLSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/modals/CreateServiceJsonOnly.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/service-configuration/ServiceConfigurationContainer.js
plugins/services/src/js/containers/services/SidebarLabelsFilter.js
plugins/services/src/js/stores/MarathonStore.js
src/js/components/DSLFormWithExpressionUpdates.js
src/js/components/DSLInputField.js
src/js/components/modals/JobFormModal.js
src/js/pages/jobs/JobDetailPage.js
src/js/pages/jobs/JobsTable.js

As we've agreed that we want to keep our class interface as clear as possible it is beneficial to have a name for a param and you can always destructure it in a method body.
It is still okay to destructure in params in higher order functions and in standalone functions.

DCOS-13661: Forbid destructuring in methods

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
src/styles/components/form-elements/form-control-toggle/styles.less
src/styles/components/form-elements/form-control-toggle/variables.less
src/styles/index.less

This PR moves the disabled tooltip notification to the disabled fields, rather than a lock icon near the disabled field.
Before:
After:
_In the above example, a bug in the `Tooltip` prevents us from aligning the tooltip with the left edge of the checkbox. This needs to be fixed in `reactjs-components`._

DCOS-12589: Apply tooltips to disabled fields

---

src/styles/components/expanding-table/styles.less

This PR forces `line-height` inheritance on all children of `.expanding-table td`s. This is necessary to maintain proper alignment among the expanded "rows" in each cell (I was tempted to add an `!important` here but opted not to...).
Before:
After:

Bug: Fix .expanding-table's "row" misalignment

---

src/styles/components/configuration-map/styles.less

I thought I corrected this yesterday, but apparently not...
Before:
After:

Bug: Fix word wrapping in configuration map

---

plugins/nodes/src/js/pages/nodes/NodeDetailTab.js

[DCOS-12416] Use ConfigurationMap in NodeDetailTab

---

src/styles/components/page-header/styles.less

Adds hover effect to page header breadcrumbs. This gives the user immediate feedback making it more obvious that these are clickable. It also gives keyboard users feedback with a focus state. The hover style is consistent with that of the links in tables.
cc @jfurrow

Add hover and focus states to breadcrumbs in page headers

---

src/js/components/JSONEditor.js
src/js/components/__tests__/JSONEditor-test.js

Adjust the JSONEditor state handling to ensure the editor content properly updates if the internal data is different then the input data, even when the input data is the same as the initial input data. This change fixes an issue in which the JSONEditor didn't update if the input value was the same as the initial value.

Adjust JSONEditor state handling

---

src/styles/layout/page-body/styles.less

This PR sets the `min-height` property on `.page-body-content` and any `.flex-item-shrink-1` children to allow them to shrink as needed.
In the screenshots, note the log viewer is expanding beyond the viewport's boundaries in the "Before" screenshot, then notice that it's respecting the available space in the "After" screenshot.
Before:
After:

DCOS-12890: Allow .page-body-content to shrink

---

src/styles/components/user-account-dropdown/variables.less

This PR rounds one of the variables in the user account menu because it was resulting the component's height ending in a half pixel. This in turn causes Gemini to be off by one pixel when it calculates its own height.
Before (note the height of the user account dropdown button is `63.5px`, and the 1px sliver of native scrollbar at the bottom of the scroll panel):
After:

Fix sidebar scrollbar bug

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/constants/DefaultApp.js
plugins/services/src/js/constants/DefaultPod.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js
tests/pages/services/ServiceFormModal-cy.js

This changes the default value for CPU from 1 to 0.1. Users find themselves deploying demo apps with the defaults then quickly run out of resources. This will help with that, as well as educating the user that fractional values are allowed.

Change CPU default from 1 to 0.1 for service create

---

src/js/components/modals/ActionsModal.js

This PR enables collapsing of repeating errors in the ActionsModal
Related plugins-private PR: https://github.com/mesosphere/dcos-ui-plugins-private/pull/543

DCOS-12608: Collapsing repeating errors in ActionsModal

---

plugins/services/src/js/components/ConfigurationMapDurationValue.js
plugins/services/src/js/service-configuration/ServiceHealthChecksConfigSection.js

* Removed COMMAND from the endpoint health checks section
* Hide the whole section if there's no healthchecks
* Hide respective sections if there's no respective health checks
* Fix various visual quirks
Before, jumping values, `0 sec ()`:
After:
**Checklist**

DCOS-11968: Service Health checks visual improvements

---

plugins/services/src/js/components/ServiceStatusWarning.js
plugins/services/src/js/containers/pod-debug/PodDebugContainer.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
plugins/services/src/js/utils/DeclinedOffersUtil.js

This PR prevents showing any declined offer information for a task whose status is `delayed`.
It also adds a warning for apps which have been in the launch queue for over 30 minutes, as discussed in https://mesosphere.atlassian.net/browse/DCOS-13340

DCOS-13340: Update service status warning logic

---

src/js/components/form/FormGroup.js
src/js/components/form/FormGroupHeading.js
src/js/components/form/FormGroupHeadingContent.js
src/js/components/form/index.js
src/styles/components/form-elements/form-group/styles.less
src/styles/components/form-elements/form-group/variables.less
src/styles/components/form-elements/form-row/styles.less
src/styles/components/menu-tabbed/styles.less
src/styles/views/create-service-modal/styles.less

1 of 2: #1886 
2 of 2: #1887
This PR introduces two components: `FormGroupHeading` and `FormGroupHeadingContent`.
`FormGroupHeading` is now responsible for applying the required indicator (`*`) to the fields. This was previously handled by `FormGroup`, so that logic has been removed.
`FormGroupHeading` can take any number of `FormGroupHeadingContent` elements and will render them on a single line. Setting `primary={true}` on a `FormGroupHeadingContent` element allows that element to shrink and for its content to be truncated.
Example usage:
```jsx
<FormGroupHeading>
<FormGroupHeadingContent primary={true}>
I am a piece of content that is reasonably long.
</FormGroupHeadingContent>
<FormGroupHeadingContent>
<Tooltip ... />
</FormGroupHeadingContent>
</FormGroupHeading>
```
In this example, …

[1 of 2: Fix form label wrapping] Introduce FormGroupHeading components

---

src/js/pages/network/virtual-network-detail/VirtualNetworkDetailsTab.js

[DCOS-12416] Use ConfigurationMap in VirtualNetworkDetailsTab

---

npm-shrinkwrap.json
package.json

This PR updates `raml-validator-loader` dependency to `0.1.10`

Updating raml-validator-loader to v0.1.10

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js

This PR re-enables the per-keystroke updates of the JSON editor to the `NewCreateServiceModalForm`

DCOS-13910: Re-enable keystroke-updates to the JSON

---

plugins/services/src/js/containers/volume-detail/TaskVolumeContainer.js
plugins/services/src/js/pages/task-details/TaskDetail.js
plugins/services/src/js/pages/task-details/__tests__/TaskDetail-test.js
plugins/services/src/js/structs/Task.js
plugins/services/src/js/structs/__tests__/Task-test.js

Add a service id getter to the Task struct, which returns the corresponding service id. Refactor `TaskDetail` and `TaskVolumeContainer` to sue the new getter in combination with the
`ServiceTree.findItemById()` method instead of the old `ServiceTree.getServiceFromTaskID()` to retrieve the corresponding service. The change address issues with wrong task health reports and potentially wrong volume mappings which were caused be inexact matches.
**Checklist**

DCOS-397: Adjust serivce task handling

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/constants/ServiceErrorPathMapping.js
plugins/services/src/js/reducers/serviceForm/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/__tests__/EnvironmentVariables-test.js
src/js/constants/DefaultErrorMessages.js

Two things:
- JSON parser has been adjusted to let all the values in the batch so that we don't delete something we don't support in the form
- Form validators moved from the module level inside `getFormErrors` method so that we could apply hooks and extend validators
**Checklist**

DCOS-13152: Add service validators hooks

---

src/js/utils/JobUtil.js
src/js/utils/__tests__/JobUtil-test.js

Always reset the schedule configuration to only create a schedule configuration if activated.
Closes DCOS-13295
**Checklist**

Adjust schedule configuration handling

---

plugins/services/src/js/events/MarathonActions.js
plugins/services/src/js/events/MesosLogActions.js
plugins/services/src/js/events/TaskDirectoryActions.js
plugins/services/src/js/events/__tests__/MarathonActions-test.js
plugins/services/src/js/events/__tests__/MesosLogActions-test.js
plugins/services/src/js/events/__tests__/TaskDirectoryActions-test.js
src/js/events/AuthActions.js
src/js/events/ConfigActions.js
src/js/events/CosmosPackagesActions.js
src/js/events/MesosSummaryActions.js
src/js/events/MetadataActions.js
src/js/events/MetronomeActions.js
src/js/events/NodeHealthActions.js
src/js/events/SystemLogActions.js
src/js/events/UnitHealthActions.js
src/js/events/UsersActions.js
src/js/events/VirtualNetworksActions.js
src/js/events/__tests__/AuthActions-test.js
src/js/events/__tests__/ConfigActions-test.js
src/js/events/__tests__/CosmosPackagesActions-test.js
src/js/events/__tests__/MetronomeActions-test.js
src/js/events/__tests__/NodeHealthActions-test.js
src/js/events/__tests__/SystemLogActions-test.js
src/js/events/__tests__/UnitHealthActions-test.js
src/js/events/__tests__/UsersActions-test.js
src/js/events/__tests__/VirtualNetworksActions-test.js

This is part 1 of several PRs.
This PR alters action files and their associated tests to ensure the xhr object is emitted in action error handlers.
The goal is to allow `<RequestErrorMsg />` to customize the error message based on xhr properties.

[1 of 2] DCOS-12713: Emitting xhr object in action error handlers

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
tests/pages/services/ServiceActions-cy.js

~~Service Modal Routes 1 of 3: https://github.com/dcos/dcos-ui/pull/1828~~ Merged!
Service Modal Routes 2a of 3: https://github.com/dcos/dcos-ui/pull/1853
Service Modal Routes 2b of 3: https://github.com/dcos/dcos-ui/pull/1871
This PR adds a confirm modal to route changes from service create/edit modal and when navigating away if there are any changes to the form.
Diff for review can be found here: https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-12423-add-routes-for-the-new-create-service-modal...mlunoe/feature/DCOS-12423-add-confirm-modals-when-navigating-away-from-route?expand=1

[Service Modal Routes 2b of 3] DCOS-12423: Add confirm modals when navigating away from route

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-configuration/ServiceConfigurationContainer.js
plugins/services/src/js/containers/service-configuration/__tests__/ServiceConfigurationContainer-test.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/service-detail/__tests__/ServiceDetail-test.js
plugins/services/src/js/service-configuration/ServiceConfigDisplay.js
plugins/services/src/js/utils/MarathonErrorUtil.js
plugins/services/src/js/utils/ServiceUtil.js
plugins/services/src/js/utils/__tests__/MarathonErrorUtil-test.js
src/js/components/ErrorsAlert.js
src/js/utils/ErrorMessageUtil.js
src/js/utils/__tests__/ErrorMessageUtil-test.js

~~Service Modal Routes 1 of 3: https://github.com/dcos/dcos-ui/pull/1828~~ Merged!
Service Modal Routes 2a of 3: https://github.com/dcos/dcos-ui/pull/1853
Service Modal Routes 2b of 3: https://github.com/dcos/dcos-ui/pull/1871
This PR ensures that we do display marathon errors on the service configuration page, when they emerge.
~~Diff for review can be found here: https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-12423-add-routes-for-the-new-create-service-modal...mlunoe/feature/DCOS-12423-add-routes-for-the-new-create-service-modal-2?expand=1~~ Merged!

[Service Modal Routes 2a of 3] DCOS-12423: Show marathon errors in service config display 

---

src/styles/components/modal/full-screen/styles.less

This PR fixes the missing service form in Safari. 
To reproduce this, you'll need to make sure that the native macOS scrollbars are visible. You can force this by setting your "Show scroll bar" settings to "Always":
Before:
After:
**Checklist**

DCOS-13474: Fix invisible service form in Safari

---

src/styles/components/modal/styles.less

This PR removes the `margin-bottom` from the last paragraph tags inside `modal-body`. I think it should be safe as it only targets `.modal-body > p:last-child` and `.modal-body > div:last-child > p:last-child`.
Before:
After:
**Checklist**

DCOS-13960: Remove modal body content's bottom margins

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/constants/OperatorTypes.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/serviceForm/Constraints.js
plugins/services/src/js/reducers/serviceForm/MultiContainerConstraints.js
plugins/services/src/js/reducers/serviceForm/__tests__/Constraints-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/MulitContainerConstraints-test.js
plugins/services/src/js/reducers/serviceForm/common/Constraints.js
plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js
plugins/services/src/js/service-configuration/ServicePlacementConstraintsConfigSection.js
plugins/services/src/js/utils/DeclinedOffersUtil.js
plugins/services/src/js/utils/PlacementConstraintsUtil.js
plugins/services/src/js/utils/__tests__/DeclinedOffersUtil-test.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
src/js/components/form/AdvancedSection.js
src/js/utils/ValidatorUtil.js
src/js/utils/__tests__/ValidatorUtil-test.js

Placement constraints was not working for pods and had a few issues.
This PR makes the placement constraints work for pods again with a separate reducer for this (there is a unique items issue that @wavesoft is working on separately). It also introduces form validation for placement constraints and displays `Not Applicable` in the ServiceConfigDisplay for `value`s that are empty.
NB: I encountered an error while working on this that was introduced here: https://github.com/dcos/dcos-ui/commit/31630d08344f2a2d00f2534a9333e084fc459a76
Before:
After:

DCOS-13159: Bug fix: Placement constraints

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js
tests/pages/services/ServiceFormModal-cy.js

This PR fixes the container reducer so that when we switch from the Docker engine to Mesos runtime `container` section goes away from the JSON
**Checklist**

DCOS-14053: Remove container field from JSON when switching to Mesos

---

src/styles/components/user-account-dropdown/styles.less
src/styles/layout/sidebar/styles.less
tests/components/Sidebar-cy.js

This PR changes the sidebar's `max-width` property to `width` to avoid any inconsistent behavior with the its width. Fixes a bug in IE11 where the sidebar container element wasn't as wide as the actual sidebar.
This also fixes a bug where the user account dropdown menu was overflowing its container.
Before:
After:
**Checklist**

DCOS-14088: Fix sidebar styling in IE11

---

plugins/services/src/js/utils/MarathonErrorUtil.js
plugins/services/src/js/utils/__tests__/MarathonErrorUtil-test.js

This PR ensures that the `MarathonErrorUtil` utility properly parses `{message: null}` marathon error responses.
**Checklist**

DCOS_OSS-653: Handle {message: null} marathon response

---

plugins/services/src/js/components/HealthBar.js
plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/pages/services/DeploymentsTab.js
src/js/components/Breadcrumb.js
src/js/components/BreadcrumbCaret.js
src/js/components/BreadcrumbSupplementalContent.js
src/js/components/BreadcrumbTextContent.js
src/js/components/PageHeaderBreadcrumbs.js
src/styles/components/page-header/breadcrumbs/styles.less
src/styles/components/page-header/breadcrumbs/variables.less
src/styles/components/page-header/styles.less
src/styles/components/page-header/variables.less
src/styles/components/status-bar/styles.less
src/styles/index.less
src/styles/views/services/styles.less
src/styles/views/services/variables.less

This is a refactor of the `ServicesBreadcrumbs` components. It adds some new features:
* If the user is navigating through groups, only the last two groups will appear in the breadcrumb. All other breadcrumbs get "collapsed" into the ellipsis. Clicking the ellipsis navigates one level up.
* When there is not enough horizontal space to display the service health, it gets removed from the DOM.
I also introduced four new breadcrumb components:
* `Breadcrumb`: this wraps the rest of the Breadcrumb components
* `BreadcrumbCaret`: this will render a caret
* `BreadcrumbSupplementalContent`: this content will not shrink by default, and is meant for icons or other supplemental content
* `BreadcrumbTextContent`: this is the primary content; it will shrink and display an ellipsis when truncated
A …

[1 of 2: DCOS-12561] Page Header Breadcrumbs

---

plugins/services/src/js/components/forms/VolumesFormSection.js

This PR removes "Variables" from volume form section headers.
Before:
Local Volumes Variables
External Volumes Variables
After:
Local Volumes
External Volumes
**Checklist**

DCOS-14064: Remove "Variables" from volume section headers in service form

---

src/js/pages/jobs/JobRunHistoryTable.js

This PR fixes the way we were passing the `sortBy` props to the `CheckboxTable`.
I can add integration tests when #1654 is fixed up :)
**Checklist**

DCOS-14157: Properly pass the JobRunHistoryTable sort properties

---

src/js/components/Sidebar.js
src/js/components/SidebarHeader.js
src/js/pages/SystemOverviewPage.js
src/js/pages/system/OverviewDetailTab.js
src/js/routes/index.js
src/js/routes/system-overview.js

This PR renames `Cluster` to `System Overview` throughout the app.
Before: Imagine the word "Cluster"
After: Now imagine the words "System Overview" :trollface: 
**Checklist**

DCOS-13445: Rename Cluster to System Overview

---

src/js/components/ReviewConfig.js
src/js/components/__tests__/ReviewConfig-test.js
src/js/components/modals/InstallPackageModal.js
src/styles/components/modal/install-package/styles.less

This PR fixes a bug where the advanced package install modal's review stage wasn't rendering properly in Firefox. The modal's body wasn't shrinking to allow for the modal footer to be visible.
I also reduced the complexity of the displayed configuration by simply passing it to `HashMapDisplay` which improves the consistency of this view.
Before:
After:
**Checklist**

DCOS-14255: Clean up advanced package install review

---

src/js/components/modals/InstallPackageModal.js

This PR applies `.text-align-center` instead of `.horizontal-center` for the contents of the `InstallPackageModal`. This fixes the text wrapping bug in IE11.
Before:
After:
**Checklist**

DCOS-14093: Fix text wrapping in package install notes.

---

src/styles/components/menu-tabbed/styles.less

This PR fixes a bug in IE11 where flex children don't shrink as they should. It's present anywhere we use `.menu-tabbed`, but most notably in the service create form:
Before:
After:
**Checklist**

DCOS-14090: Allow menu tabbed content to shrink in IE11

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
src/styles/views/create-service-modal/styles.less

This PR implements a `flex` workaround to force the service form to fill its parent in IE11.
The workaround is described here: https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items
Before:
After:
**Checklist**

DCOS-14091: Apply flex workaround for service create modal in IE11

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/__tests__/ServiceBreadcrumbs-test.js
plugins/services/src/js/containers/volume-detail/VolumeDetail.js

This PR adds two things:
1. a new param `extra` for the ServiceBreadcrumbs so that one can add some additional crumbs
2. a new breadcrumb on the VolumeDetail page with the Volume name to indicate that we're one level deeper and thus tab nav goes missing.
**Checklist**

DCOS-13415: Volume detail missing tab nav

---

plugins/services/src/js/events/MarathonActions.js
plugins/services/src/js/events/__tests__/MarathonActions-test.js
src/js/utils/Util.js
src/js/utils/__tests__/Util-test.js

This PR adds `patchUpdate=false` to all service edit requests the UI sends to Marathon. So that Marathon doesn't do `patch` but proper `put` update. That hopefully will fix ~it doesn't~ some related issues
**Checklist**

DCOS-13770: Pass patchUpdate=false to Marathon on edit action

---

plugins/services/src/js/components/modals/CreateServiceJsonOnly.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js

This PR ensures that the API errors are removed when the user uses the `CreateServiceJsonOnly` form and there are marathon errors after review.
Without this PR the API errors would always persist, giving the feeling that the JSON is never correct.
**Checklist**

DCOS_OSS-702: Remove API errors on CreateServiceJsonOnly when changed

---

plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js

This PR hides **Service Endpoints** section on the review screen when no endpoints have been specified. 
Sorry @wavesoft I decided to address the issue without doing the complete refactoring of the section. So it makes it faster through the review process. I'd say we separate refactoring and the fix so that we could continue @jfurrow 💪  effort on refactoring after 1.9
**Checklist**

DCOS-13107: Hide empty endpoints table on the review screen

---

plugins/nodes/src/js/routes/nodes.js
plugins/services/src/js/pages/task-details/TaskDetail.js
plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/TaskLogsAPIContainer.js
plugins/services/src/js/pages/task-details/TaskLogsContainer.js
plugins/services/src/js/pages/task-details/TaskSystemLogsContainer.js
plugins/services/src/js/pages/task-details/__tests__/TaskFileViewer-test.js
plugins/services/src/js/routes/services.js
src/js/config/Config.template.js
src/js/constants/MesosLoggingStrategy.js
src/js/routes/factories/network.js
src/js/routes/jobs.js

---
Note: DCOS-14078 will take care of the breadcrumb bug. It is not handled in this PR!
~Dependent on this PR: https://github.com/dcos/dcos-ui/pull/1907~ (merged)
---
This PR adds functionality to choose one of the existing logging APIs. To use Mesos API set this variable in your `Config.dev.js`:
```js
mesos: {
'logging-strategy': 'logrotate'
}
```
To use journald API set this variable in your `Config.dev.js`:
```js
mesos: {
'logging-strategy': 'journald'
}
```
It will limit the files to view to be only `stdout` and `stderr`, when using Mesos API. Other files will still be available to view using the file viewer under the files tab.
Using Mesos API:
Using `journald` API
**Checklist**
~~For reviewers: View diff between PRs [here](https://github.com/dcos/dcos-ui/compare/mlunoe/bug-fix/logs- …

DCOS-14010: Add container to pick logging component and API

---

npm-shrinkwrap.json
package.json
scripts/validate-build
scripts/validate-build.js

This PR introduces the `scripts/validate-build.js` script and the `validate-build` command in `package.json` that checks if the files in `dist/*.js` are minified.
In order to efficiently and correctly process the javscript AST the script uses the `esprima` ecmascript parser and ensures that every comment found in the source is a legit one. Such comments are:
* Source maps
* Comments kept by default by the [UglifyJSPlugin](https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin)

DCOS-14022: Adding validate-build script to ensure minification

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js

This PR addresses the issue when discarding changes would have just closed the form which cause a glitch with Universe install button.
The issue is addressed by resetting the flag `hasChangesApplied` every time we discard changes.
**Checklist**

DCOS-14307: Fix Discard dialogue behavior

---

plugins/services/src/js/components/modals/ServiceModals.js
plugins/services/src/js/components/modals/ServiceResumeModal.js
plugins/services/src/js/constants/ServiceActionItem.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
tests/_fixtures/marathon-1-task/app-suspended-single-instance.json
tests/_fixtures/marathon-1-task/app-suspended.json
tests/_fixtures/marathon-1-task/groups-suspended-single-instance.json
tests/_fixtures/marathon-1-task/groups-suspended.json
tests/_fixtures/marathon-1-task/groups.json
tests/_support/index.js
tests/pages/services/ServiceActions-cy.js

This PR adds a "Resume" option for suspended services (meaning their instance count is 0).
When the modal appears, the user can choose how many instances they'd like to resume to. If the app label `MARATHON_SINGLE_INSTANCE_APP` is present, we do not present the instance count textbox, and instead scale the service back to a single instance.
**Checklist**

DCOS-13386: Add Resume option for suspended services

---

plugins/services/src/js/constants/PodContainerStatus.js
plugins/services/src/js/constants/PodInstanceStatus.js
plugins/services/src/js/structs/PodInstance.js
plugins/services/src/js/structs/__tests__/PodInstance-test.js

This PR fixes a typo in the `PodContainerStatus.js` and introduces the new `PodInstanceStatus.js` state `FINISHED` that will be used when the pod is in `terminal` state, yet all of it's containers are in `FINISHED` state.
Before:
After:
**Checklist**

DCOS-14277: Fix pod container status string

---

plugins/nodes/src/js/routes/nodes.js
plugins/services/src/js/pages/task-details/TaskDetail.js
plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/TaskLogsContainer.js
plugins/services/src/js/routes/services.js
src/js/routes/factories/network.js
src/js/routes/jobs.js

---
~~⚠️ Depends on this PR: https://github.com/dcos/dcos-ui/pull/1954~~ (merged)
---
This PR fixes the log tab not being highlighted for sub-routes
Please set this in your config dev:
```js
mesos: {
'logging-strategy': 'logrotate'
},
```
**Checklist**
For reviewers: View diff between PRs [here](https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-14010-add-container-to-pick-logging-component-and-api...mlunoe/bug-fix/DCOS-14010-fix-tab-not-being-highlighted-for-log-tab-sub-routes?expand=1)

DCOS-14010: Fix tab not being highlighted for log tab sub routes

---

src/js/components/modals/FullScreenModal.js
src/styles/components/modal/install-package/styles.less

This PR fixes the modal height calculation in IE11, which caused some modals to be unusable in short viewports.
_Note_: A release of `reactjs-components` is necessary for this to take place. Please see the corresponding PR here: https://github.com/mesosphere/reactjs-components/pull/393
Before:
After:
**Checklist**

DCOS-14141: Styling fixes for IE11

---

src/js/components/Alert.js
src/js/components/CosmosErrorHeader.js
src/js/components/CosmosErrorMessage.js
src/js/components/modals/InstallPackageModal.js
src/js/components/modals/UninstallPackageModal.js
src/js/components/modals/__tests__/InstallPackageModal-test.js
src/js/pages/universe/PackagesTab.js
src/styles/components/alert/styles.less
tests/pages/universe/packages/PackagesTab-cy.js

… and not use `CollapsibleErrorMessage` component.
This PR updates the cosmos error message handling, so all details are displayed without having to click "view details". It uses `Alert` component rather than the `CollapsibleErrorMessage` component.
PackageTab page:
Install:
Uninstall:
**Checklist**

Refactoring CosmosErrorMessages to be more flexible

---

plugins/services/src/js/components/LogView.js

When I was testing out the log viewer I noticed that if I scrolled up a  little and a new log line would come through, the autoscroll would kick in, thinking that I was at the bottom, but I scrolled up just a bit. This confused me and frustrated me, so I've lowered this buffer that we have to something really small.
**Checklist**

Change LogView container offset

---

tests/pages/services/ServiceActions-cy.js

This PR is an attempt to fix the resume service modal by moving the calls to `configureCluster` to a separate function rather than in the `beforeEach` function. This way each test calls `configureCluster` exactly once, whereas before, the flaky test made two calls to `configureCluster`.
**Checklist**

Fix flaky integration test for resume service modal

---

plugins/nodes/src/js/pages/NodesOverview.js
plugins/services/src/js/components/ServiceItemNotFound.js
plugins/services/src/js/containers/services/EmptyServiceTree.js
plugins/services/src/js/pages/services/DeploymentsTab.js
src/js/components/AccessDeniedPage.js
src/js/components/AlertPanel.js
src/js/components/AlertPanelHeader.js
src/js/pages/NotFoundPage.js
src/js/pages/jobs/JobsTab.js
src/js/pages/network/VirtualNetworksTab.js
src/js/pages/universe/PackagesTab.js
src/js/plugin-bridge/PluginModules.js
src/js/utils/VirtualNetworkUtil.js

---
~~⚠️ Depends on this PR: https://github.com/dcos/dcos-ui/pull/1962~~
---
This PR refactors the `AlertPanel` to just handle children and introduces an `AlertPanelHeader` component to handle headers. No visual change:
**Checklist**
For reviewers: View diff between PRs [here](https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-12433-style-error-cosmos-messages-slightly-better…mlunoe/alert-panel-title-refactor?expand=1)

AlertPanel title refactor

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/components/MesosLogContainer.js
plugins/services/src/js/pages/task-details/TaskSystemLogsContainer.js
plugins/services/src/js/stores/MesosLogStore.js
plugins/services/src/js/stores/__tests__/MesosLogStore-test.js

This PR fixes issues that will corrupt the logs.
To test this out create a task that echos something every 1s, page upwards through the file. If you pause paging upwards and then continue you will see one issue that will corrupt the log files, since the offset would not be updated in the mesos logs.
The second issue emerges at the top. Whenever you have paged all the way to the top you will see corrupt log files since we would not properly update the requested page length at the top.
**Checklist**

DCOS_OSS-733: Corrupted log files

---

npm-shrinkwrap.json
package.json
src/js/pages/universe/__tests__/PackagesTab-test.js
tests/pages/universe/packages/PackagesTab-cy.js

This PR updates `reactjs-components` to `0.16.0-beta.13` which includes the following changes:
1. [Specify c++ version for Travis build](https://github.com/mesosphere/reactjs-components/pull/389)
2. [Update stylelint deps](https://github.com/mesosphere/reactjs-components/pull/388)
3. [Make virtual list bind its onScroll function correctly](https://github.com/mesosphere/reactjs-components/pull/391)
4. [Fix modal height calculations in IE11](https://github.com/mesosphere/reactjs-components/pull/393)
5. [Explicitly set dropdown positioning properties to auto](https://github.com/mesosphere/reactjs-components/pull/394)
6. [Push commit and tags in release script](https://github.com/mesosphere/reactjs-components/pull/395)
7. [Properly remove event …

Update reactjs-components to 0.16.0-beta.13

---

src/js/pages/jobs/JobConfiguration.js

This PR wraps the job's command in a `pre` tag to match the service configuration view.
Before:
After:
**Checklist**

Wrap job command in <pre> tag

---

src/styles/layout/page-body/styles.less

This PR uses `min-height: 1px` instead of `min-height: 0` on a flex child that should shrink. This fixes a flexbox quirk in IE11.
Before (the content expands indefinitely, and scrolling is not possible):
After:
**Checklist**

IE11: Fix bug where log viewer doesn't scroll

---

plugins/services/src/js/pages/task-details/TaskSystemLogsContainer.js
src/js/events/SystemLogActions.js
src/js/events/__tests__/SystemLogActions-test.js
src/js/stores/SystemLogStore.js
src/js/stores/__tests__/SystemLogStore-test.js

Refactor the `SystemLogActions` to improve the log view performance. 
* Introduce a general (un)subscribe functions
* Change the default subscription ID not to change if the URL is the same
* Unify the (un)subscribe handling to make sure event listeners are properly removed
Closes DCOS-14431
**Checklist**

DCOS-14431: Fix memory leak where events would not be closed properly

---

src/styles/components/page-header/styles.less

This PR fixes a weird bug in IE11 where the `.page-header` element would grow a little bit when the `.page-body-content` content changed. I think it's due to the overflowing children of `.page-body-content`; the bug seems to occur when the content was overflowing, then isn't (due to its content changing to a loading indicator), and then back to overflowing (due to the content being loaded).
Reproduction steps (in IE11 only):
1. Navigate to the service detail page
2. Select a task to view the task detail page
3. Navigate between the tabs
Before:
After:
**Checklist**

Don't allow flex shrinking on page header

---

src/js/components/PageHeaderNavigationDropdown.js
src/js/components/PageHeaderTabs.js
src/styles/components/page-header/styles.less
src/styles/components/page-header/variables.less

1 of 3: #1850 
2 of 3: #1872 — [diff between 1 and 2](https://github.com/dcos/dcos-ui/compare/john/DCOS-12558/mobile-page-header-navigation...john/feature/separate-page-header-navigation-styles?expand=1)
3 of 3: #1873 — [diff between 2 and 3](https://github.com/dcos/dcos-ui/commit/83fb381a92b8c2369ac59f3193783ef9c51d63b1)
This PR implements a dropdown menu for the page header navigation at viewports narrower than `768px` (the medium breakpoint).

[1 of 3: Mobile Page Header Navigation] DCOS-12558: Create page header navigation dropdown menu

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/ExternalVolumes.js
plugins/services/src/js/reducers/serviceForm/LocalVolumes.js
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
plugins/services/src/js/reducers/serviceForm/Volumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/ExternalVolumes-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/LocalVolumes-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js
plugins/services/src/js/validators/MarathonAppValidators.js

This PR reverts the introduction of an appValidator introduced here: https://github.com/dcos/dcos-ui/pull/1814
The validator is now out of date and the latest requirement is that it should just be a string: https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/volumes.raml#L80
There was also a bug with parsing, where it would always try to parse an integer if passed to any of the volume fields. Here is where it was introduced:
https://github.com/dcos/dcos-ui/pull/1605/files#diff-7df350c7661c694dcce5e1552dcde9feR53
Before (checks if it contains `/` which is ok now):
After (only validates for string):
**Checklist**

DCOS-14449: Remove outdated volume marathon app validation

---

src/js/components/PageHeaderNavigationDropdown.js

This PR fixes a bug in the `PageHeaderNavigationDropdown` component when it can't find an active tab.
**Checklist**

Fix active navigation item default

---

plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

With this PR we stop counting a framework's child tasks as its instances and properly aggregate their resources instead.
Note! It works only one level deep, so if you run MoM and then Kafka on that MoM and then something on that Kafka - only Kafka's resource will be aggregated.
Testing
Easy mode: start confluent-kafka, wait until broker task starts, verify
Harder: start MoM, start a bunch of tasks on MoM, verify
**Checklist**

DCOS-13032: Aggregate child tasks resources

---

plugins/services/src/js/containers/tasks/TaskTable.js
src/styles/components/icons/styles.less

This PR adds a tooltip to the ambiguous logs icon in the tasks table. We've heard lots of feedback from users that they don't know what this icon means. Adding a tooltip helps add a lot of clarity.

Add tooltip to logs icon

---

plugins/services/src/js/components/ServiceBreadcrumbs.js

Why:
* we don't have any on the loading screen and yet want to render breadcrumbs
This change addresses the need by:
* removing isRequired from the prop

Make serviceID prop not required

---

plugins/services/src/js/service-configuration/ServicePlacementConstraintsConfigSection.js

This PR replaces destructuring syntax with a default with a regular conditional assignment
so that `null` value also gets replaced by the default value
**Checklist**

DCOS-14699: Support null value for placement constraints

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js

This PR cleans up the hierarchy and spacing of headings through the create service flow. Today there are a few examples where the headings are inconsistent, the spacing is off, or it is the wrong type of heading. 
Each tab should follow a H2 > H3 > H4 rule and related headings/objects should visually be grouped together.
Some before and after examples:
Before - Three H2 headings, inconsistent with other tabs
After - One H2 heading, three H3s
Before - Two H2 headings and some minor spacing issues
After - One H2 heading, two H3s, spacing improved
Before - One H2 heading, three H3s
After - One H2 heading, one H3, two H4s
cc @ashenden @jfurrow for visual review.

Clean up create service headings

---

plugins/services/src/js/components/LogView.js
src/js/events/SystemLogActions.js
src/js/events/__tests__/SystemLogActions-test.js
src/js/stores/SystemLogStore.js
src/js/stores/__tests__/SystemLogStore-test.js
src/js/utils/SystemLogUtil.js
src/js/utils/__tests__/SystemLogUtil-test.js

This PR optimises the `LogView` and the SSE stream of logs by throttling the event stream and by being cautious of reading/writing to properties that causes reflow.
Before:             |  After:
:-------------------------:|:-------------------------:
Notice the difference in execution time of the `handleUpdateScrollPosition` function, but also the difference in frequency
**Checklist**

DCOS-14120: Optimise logs (CPU)

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This PR fixes [object Object] issue in the placement constraints tooltips
By passing arguments to `placementConstraintLabel` in the correct way

DCOS_OSS-800: Fix placement constraints tooltips

---

src/js/stores/GetSetBaseStore.js

Since DCOS-5040 has been resolved I removed the workaround.
Moreover `__DEV__` is being used only in tests.

Remove circular reference workaround

---

foundation-ui/utils/ReactUtil.js

This PR refactors the `ReactUtil#wrapElements` method to be more readable. This comes from a comment in a PR: https://github.com/dcos/dcos-ui/pull/1780#discussion_r95982491
**Checklist**

DCOS-13209: Reduce complex logic in #wrapElement

---

Dockerfile
npm-shrinkwrap.json
package.json
scripts/docker-entrypoint
webpack/webpack.dev.babel.js
webpack/webpack.production.babel.js

This PR introduces a `Dockerfile` that is used to build the [dcos-ui docker image](https://hub.docker.com/r/mesosphere/dcos-ui/) for use in development and build environments.
**NOTE:** Due to some bugs on the previous versions of `webpack` and `babel-loader` I also had to update the respective versions to the next available one.
This container **does not contain the dcos-ui sources**. It contains only the tooling required by the developer, the build system or the system integration tests.
In detail the docker image contains:
* Node 4.4.7 & npm 3.9
* The current branch's dependencies pre-installed
* Automatic initialisation script that runs `npm run scaffold` if requested to run on a clean repo
You must mount the `dcos-ui` repository manually under the `/dcos-ui` volume. For example:
``` …
```

[System Tests]: Adding development environment dockerfile

---

plugins/services/src/js/service-configuration/ServiceGeneralConfigSection.js

This PR addresses the inability to create an app with arguments by wrapping the array of `<pre>` in `<div>` so that ServiceConfigDisplayUtil.getDisplayValue won't `JSON.stringify` it.
To test try to launch appDefinition and try without args.
```json
{
"id": "inky", 
"container": {
"docker": {
"image": "mesosphere/inky"
},
"volumes": []
},
"args": ["hello"],
"cpus": 0.2,
"mem": 32.0,
"instances": 1
}
```

DCOS-14733: Fix review screen for app definitions with args

---

plugins/services/src/js/components/forms/ArtifactsSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
src/js/components/form/DeleteRowButton.js
src/js/components/form/FormGroup.js
tests/pages/services/ServiceFormModal-cy.js

This PR cleans up the styling of the `DeleteRowButton` component. It removes all horizontal padding on the delete row button, uses `column-auto` instead of `column-2`, and increases the column width of all sibling `FormGroups` to ensure that the delete button takes up only as much space as is necessary. I also moved all classes to the `FormGroup` element so that we don't have to remember which classes to use in the future.
This adds two new props to the `FormGroup` component:
`isDeleteButton` — when true will apply the correct `column` and `flush` classes
`applyLabelOffset` — when true will apply the correct class, adds padding to the top of the form group so that it aligns vertically with its siblings who have labels
Before (note the real estate used by the button's column and its …

DCOS-14171: Clean up usage and styling of DeleteRowButton

---

src/js/events/SystemLogActions.js
src/js/events/__tests__/SystemLogActions-test.js

Remove unnecessary withCredentials from EventSource. This should only be used for CORS, not for authentication.
I removed functionality, adjusted some tests and removed tests that explicitly was testing for this.
**Checklist**

Remove unnecessary withCredentials from EventSource

---

plugins/services/src/js/constants/HealthSorting.js
plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/utils/TaskTableUtil.js
plugins/services/src/js/utils/__tests__/TaskTableUtil-test.js
src/js/utils/TableUtil.js
src/js/utils/Util.js
src/js/utils/__tests__/Util-test.js

This PR fixes the issue when sorting by health in service table, adds minor refactoring (naming, code structure), unit test improvement based on code changes.
After talking to @mlunoe we decided that code fix was needed for the sorting to work properly as well.
As a effort to move from this [reusable sorting](https://github.com/dcos/dcos-ui/blob/2e63bbbc94875485c6dadfa9298649b42a6f213f/plugins/services/src/js/utils/TaskTableUtil.js#L19) because of reasons, code complexity, hard to follow code flow and hard to create more precise unit tests. 
That being said code refactoring was added, removing the sorting work from the `reusable sorting` function health and created a new method targeting specifically health sorting.
**Checklist**

DCOS-13950: Fix sorting by health

---

plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js

This PR fixes a bug where environment variables weren't displayed on the pod's configuration screen. We were looking for the `environment` key but the environment variables are defined on the `env` key.
I didn't add a test in this PR because I'm currently writing SI tests for this in a subsequent PR.
**Checklist**

Check for the proper key containing environment variables

---

plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/containers/volume-detail/VolumeDetail.js
plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js

This PR changes label from MiB to GiB for external volumes. Please not just review it, test it 🙇 
Marathon treats size value for External volumes as it is in GiB and sends this data to Mesos.
This is going to be fixed (changed to MiB) in 1.10 to align it with other volumes. 
But in the 1.9 we want to show the right label.
https://jira.mesosphere.com/browse/DCOS-14842

DCOS-14842: Change size label from MiB to GiB for external vols

---

src/styles/components/menu-tabbed/styles.less

This PR fixes the container tab's width in the "Run a Service" modal.
Before:
After:
**Checklist**

Fix vertical menu tab width anomalies

---

README.md

This PR fixes the highlight of Sublime Text User Settings in the _Development Setup_ instructions
From:
To:

Change syntax highlight on README.md instructions

---

scripts/pre-install

Adjust the pre-install script to install the Marathon 1.4.2 RAML specs. This change will resolve issues related to wrong validation warnings due
to outdated specs.
Closes DCOS_OSS-858
**Checklist**

DCOS_OSS-858: Update Marathon RAML

---

plugins/services/src/js/containers/services/ServicesTable.js
src/styles/components/service-table/styles.less
tests/pages/services/ServiceActions-cy.js

This PR restyles the actions dropdown for service collection rows and moves it to the right. 
Why? We want a consistent style and location for row actions throughout DC/OS. Using the ellipsis and positioning it to the right will keep us consistent and also keeps us open to adding more actions here. A tooltip has also been added for extra clarity.
Before
After

Restyle table row actions dropdown

---

src/js/plugin-bridge/Loader.js
src/js/plugin-bridge/PluginModules.js

List of PRs: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3AnLight+foundation
This interim PR exposes ResourcesTableUtil on the SDK so that it is available via foundation and SDK. It will eventually go to the SDK here https://github.com/dcos/dcos-ui/pull/2041
We need this to merge plugins and dcos separately.

[foundation 1 of ?] DCOS-14745: Expose ResourcesTableUtil on the SDK

---

system-tests/services/test-apps.js
system-tests/services/tests.yml

---
⚠️  ~~Depends on #2029~~ (Merged)
---
This PR introduces the automated tests for _Create a simple app_
<pre>
docker run -it --rm \
mesosphere/dcos-ui \
dcos-system-test-driver ./.systemtest-dev.sh <strong>$CLUSTER_URL</strong>
</pre>

[System Tests]: DCOS-12807: Adding the 'Create a simple app' test

---

Dockerfile
scripts/docker-entrypoint

This PR modifies the `Dockerfile` in order to accommodate a few situations:
* It now includes `jre` so it can be used as a build agent for Jenkins
* It no longer uses the cached, internal `node_modules`, rather it relies on the user to do `npm install` and `npm scaffold`
**Checklist**

[System Tests]: Modified Dockerfile for Jenkins use

---

plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js
plugins/services/src/js/utils/VipLabelUtil.js

This PR adds custom labels support to pod containers endpoints.
Please test in the Form, _not_ the JSON only Form!
To get you an idea what the minimal definition looks like
```json
{
"id": "/test-pod",
{
"name": "healthtask1",
"exec": {
"command": {
"shell": "sleep 1"
}
},
"resources": {
"cpus": 0.1,
"mem": 32,
"disk": 32,
"gpus": 0
},
"endpoints": [
{
"name": "httpendpoint",
"containerPort": 8080,
"hostPort": 0,
"protocol": [
"tcp"
],
"labels": {
"custom_label": "custom"
}
}
],
"image": {
"id": "alpine"
}
}
],
"networks": [
{
}
]
}
```
**Checklist**

DCOS-14894: Keep endpoint labels in pods

---

plugins/services/src/js/constants/ServiceErrorMessages.js
plugins/services/src/js/constants/ServiceErrorPathMapping.js
plugins/services/src/js/validators/VipLabelsValidators.js
plugins/services/src/js/validators/__tests__/VipLabelsValidators-test.js
src/js/components/ErrorsAlert.js

This PR comes after a testing session with @leemunroe . It fixes the following:
* Adding name aliases in all property paths. (For example "cmd: Missing" -> "Command missing").
* Adding a more user-friendly error message for the `STRING_PATTERN` error on port endpoint name.
* Removing duplicate messages from the `ErrorsAlert.js` component that displays the unanchored messages.
**Checklist**

DCOS-13909: A couple of error fixes

---

src/js/plugin-bridge/__mocks__/Loader.js

This PR adds `foundation-utils` to mocks so that plugins tests pass. Sorry about that 😅 
List of PRs: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3AnLight+foundation

[foundation 1.5 of 4] DCOS-14745: add foundation-utils to mocks

---

plugins/services/src/js/reducers/serviceForm/MultiContainerHealthChecks.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerHealthChecks-test.js

This PR ensures that the `scheme` property is always present in the resulting JSON. This fixes cases where the "scheme" property was initially present in the JSON, since the default behaviour was to remove it.
**Checklist**

DCOS-14890: Always keep the http health checks scheme

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
src/js/components/form/FormGroup.js

This PR fixes the lack of label offset for `DeleteRowButton` and removes a comment I accidentally committed.
Before:
After:

fix(DeleteRowButton): fix alignment of DeleteRowButton instances

---

plugins/services/src/js/events/MarathonActions.js
plugins/services/src/js/events/__tests__/MarathonActions-test.js
src/js/utils/__tests__/Util-test.js

This PR changes the PATCH/PUT update control flag from `patchUpdate` to `partialUpdate`
`patchUpdate` was among the suggestions but never was implemented in fact it always was `partialUpdate`
Using the correct control flag fixes the issue in the ticket... and maybe few other issues.

DCOS-15014: change the name of the control flag

---

tests/pages/services/ServiceActions-cy.js

This PR fixes a flaky integration test where in some cases was failing because the selector is returning multiple elements instead of one in which is causing the test to not being able to click.
**Checklist**

fix(integration-test): Fix flaky integration test.

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/components/modals/ServiceModals.js
plugins/services/src/js/constants/PodActionItem.js
plugins/services/src/js/constants/ServiceActionItem.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/pod-detail/PodHeader.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/service-detail/ServiceInfo.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/pages/__tests__/DeploymentsTab-test.js
plugins/services/src/js/pages/services/DeploymentsTab.js
plugins/services/src/js/reducers/serviceForm/__tests__/Labels-test.js
src/js/components/RepositoriesTable.js
src/js/components/form/DeleteRowButton.js
src/js/components/form/FormGroupContainer.js
src/js/constants/BulkOptions.js
src/js/constants/UserActions.js
src/js/pages/jobs/JobDetailPage.js
src/js/plugin-bridge/PluginModules.js
tests/pages/services/ServiceActions-cy.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js
tests/pages/system/overview/repositories/RepositoriesTab-cy.js

This PR introduces a constants file named `UserActions` which is meant to contain actions that DC/OS UI users can perform. So far this includes `delete`, `deleted`, and `deleting`. This PR implements it in place of every instance of "remove," "destroy," and "delete."
**Checklist**

DCOS-14913: Rename "remove" and "destroy" to "delete"

---

src/js/components/Alert.js
src/styles/components/alert/styles.less

Moves the icon that is part of the alert to the top of the alert so it is not floating arbitrarily in the middle.
Before
After

Move icon to top of alert

---

system-tests/services/test-pods.js
system-tests/services/tests.yml

This PR introduces the automated tests for [Create a simple pod with service address](https://wiki.mesosphere.com/pages/viewpage.action?pageId=99615053)
<pre>
</pre>

[System Tests]: DCOS-12813: Add SI tests for pod with service address

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/serviceForm/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerEnvironmentVariables-test.js
plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js

Turns out multi container environment variables field is `environment` and not `env` as it is for single container services. This PR addresses the issue by splitting reducers and adjusting review screen.
Bonus track: fixing reducers uncovered one more bug in: `plugins/services/src/js/components/modals/NewCreateServiceModal.js`
where we applied single container hooks for multi container reducers 😅
**Checklist**

DCOS-15137: Fix pods environment variables handling

---

system-tests/driver-config/dev.sh

This PR updates the `dev.sh` configuration script in order to automatically start a testing version of webpack and automatically configure `proxy.dev` to use the `CLUSTER_URL`  specified.
Effectively, using the `./system-tests/driver-config/dev.sh` driver configuration script you can serve the current branch's version without the need of building a `dist` first.
For example, you should now use the following to run the tests:
<pre>
-e CLUSTER_URL=<strong>$OPEN_CLUSTER_URL</strong> \
</pre>

[System Tests] Automatically starting `npm testing` on dev.sh

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-configuration/ServiceConfigurationContainer.js
plugins/services/src/js/containers/service-configuration/__tests__/ServiceConfigurationContainer-test.js
plugins/services/src/js/service-configuration/ServiceConfigDisplay.js

PR #1957 wrongly added onEditClick to this view. This PR reverts that effort and adds a test to guard against it
**Checklist**

DCOS-14854: Remove edit link on service config page

---

plugins/nodes/src/js/components/HealthTab.js
plugins/nodes/src/js/components/NodesTable.js
plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/utils/TaskTableUtil.js
plugins/services/src/js/utils/__tests__/TaskTableUtil-test.js
src/js/components/ComponentList.js
src/js/components/__tests__/ComponentList-test.js
src/js/constants/UnitHealthStatus.js
src/js/constants/UnitHealthTypes.js
src/js/pages/system/UnitsHealthTab.js
src/js/structs/__tests__/HealthUnit-test.js
src/js/utils/TableUtil.js
src/js/utils/UnitHealthUtil.js
src/js/utils/__tests__/TableUtil-test.js
src/js/utils/__tests__/UnitHealthUtil-test.js

This PR fixes a variety of health sorting issues included in the Jira ticket (DCOS-14146), where now those places the health sorting weight is based on visibility importance, meaning `Unhealthy, NA, Idle/Warn, Healthy`.
Be aware that some places at first loading the sort is selected to be in another field e.g `name`, that being said you will need to select the health field.
- Dashboard pane
- Node Components tab
- Components page
- Node components
- Services (task detail)
To accomplish the fix a couple of refactoring work was needed to be done around how the higher order functions handle the sorting, In summary I have split/removed the complexity in to smaller functions easier to understand and enabling more precise unit tests.
The work in this PR also refactors the work in #2001 which …

fix(DCOS-14146): Fix sorting for health status in a couple of places.

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/serviceForm/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerEnvironmentVariables-test.js
plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js

⚠️  It's a back port of the https://github.com/dcos/dcos-ui/pull/2091 ⚠️ 
Copy/paste
Turns out multi container environment variables field is `environment` and not `env` as it is for single container services. This PR addresses the issue by splitting reducers and adjusting review screen.
Bonus track: fixing reducers uncovered one more bug in: `plugins/services/src/js/components/modals/NewCreateServiceModal.js`
where we applied single container hooks for multi container reducers 😅

[release 1.9] DCOS-15137: Fix pods environment

---

system-tests/services/test-pods.js
system-tests/services/tests.yml

This PR introduces the automated tests for [Create a simple pod](https://wiki.mesosphere.com/pages/viewpage.action?pageId=99615053)
<pre>
</pre>

[System Tests]: DCOS-12805: Add SI tests for creating a simple pod

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/ServiceList.js
plugins/services/src/js/components/VolumeTable.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServiceTreeView.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/containers/volume-detail/VolumeDetail.js
plugins/services/src/js/pages/ServicesPage.js
plugins/services/src/js/pages/services/DeploymentsTab.js
plugins/services/src/js/pages/task-details/ServiceTaskDetailPage.js
plugins/services/src/js/pages/task-details/TaskDetail.js
plugins/services/src/js/pages/task-details/__tests__/TaskDetail-test.js
plugins/services/src/js/routes/services.js
src/js/components/NestedServiceLinks.js
src/js/components/Sidebar.js
src/js/utils/NavigationServiceUtil.js
system-tests/services/test-apps.js
system-tests/services/test-environment.js
tests/_fixtures/marathon-1-group/groups.json
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/ServiceVersions-cy.js
tests/pages/services/TasksTable-cy.js
tests/pages/services/VolumesTable-cy.js

This PR will split routes into services/overview and services/detail routes, which will allow for different children for these routes, which is necessary when routing tabs.
Route Service Tabs 1 of 2: https://github.com/dcos/dcos-ui/pull/2079
Route Service Tabs 2 of 2: https://github.com/dcos/dcos-ui/pull/2058
**Checklist**

[Route Service Tabs 1 of 2] DCOS-14508: Splitting routes into overview and detail

---

system-tests/driver-config/jenkins.sh

This PR ensures that the locally-served files are correctly found by the `http-server`.
The bugs caused by this are quite tricky, since if `http-server` fails to locate the `dist` folder it will just forward every requests to the upstream server. Until this is merged, the Jenkins job will be effectively using the UI served from the server and not the development version.

[System Tests] Using correct dist folder on jenkins config

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/components/MesosLogContainer.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/TaskSystemLogsContainer.js

Currently prettier can't prettify pieces of code where return statements have comments in it.
```javascript
return (
// Comment
someLogic !== here
);
```
So I decided to fix those as a separate PR so that these changes could be tested separately.

DCOS-13710 [preparation]: Fix the code that prettier can't process 

---

plugins/services/src/js/components/forms/ArtifactsSection.js
plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/components/modals/ServiceFormModal.js
src/js/components/SchemaForm.js
src/js/components/TabForm.js
src/js/components/form/DeleteRowButton.js
src/js/components/form/FormGroupContainer.js

~~**Relies on https://github.com/mesosphere/reactjs-components/pull/399**. The `hold merge` label should remain until a new version of `reactjs-components` is released and the dependency is updated in DC/OS UI.~~ [The update PR](https://github.com/dcos/dcos-ui/pull/2103) landed.
This PR removes the `scrollContainer` prop from the `Tooltip` component, as it is no longer needed due to the way the event listener is added.
**Checklist**

DCOS-14370: Remove scrollContainer prop from Tooltip

---

plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

This PR fixes the resources aggregation issue for Frameworks by taking into account running tasks only.
To test just run MoM and launch a task on Marathon that finishes in 5 seconds or so.
Observe that without the fix it will report growing number of resources in DC/OS UI
**Checklist**

DCOS-14894: Aggregate resources for running tasks only

---

scripts/pre-install

---
⚠️  _This PR back-ports a fix to release/1.9 introduced with #2054._
---
Adjust the pre-install script to install the Marathon 1.4.2 RAML specs. This change will resolve issues related to wrong validation warnings due to outdated specs.

⬅️ DCOS_OSS-858: Update Marathon RAML

---

plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/containers/volume-detail/VolumeDetail.js
plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js

---
⚠️  _This PR back-ports a fix to release/1.9 introduced with #2053._
---
This PR updates the size label for external volumes due to the way marathon handle the value.
> Marathon treats size value for External volumes as it is in GiB and sends this data to Mesos.
> This is going to be fixed (changed to MiB) in 1.10 to align it with other volumes.

⬅️ DCOS-14842: Change size label

---

plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js
plugins/services/src/js/utils/VipLabelUtil.js

---
⚠️  _This PR back-ports a fix to release/1.9 introduced with #2062._
---
Please test the fix using the Form (not the JSON only one) using the following example spec:
```
{
"id": "/test-pod",
{
"name": "healthtask1",
"exec": {
"command": {
"shell": "sleep 1"
}
},
"resources": {
"cpus": 0.1,
"mem": 32,
"disk": 32,
"gpus": 0
},
"endpoints": [
{
"name": "httpendpoint",
"containerPort": 8080,
"hostPort": 0,
"protocol": [
"tcp"
],
"labels": {
"custom_label": "custom"
}
}
],
"image": {
"id": "alpine"
}
}
],
"networks": [
{
}
]
}```

⬅️ DCOS-14894: Keep pod endpoints labels

---

src/js/components/TaskTable.js
src/js/components/__tests__/TaskTable-test.js

This PR is the same as this just pointing to release 1.8: https://github.com/dcos/dcos-ui/pull/2128
This PR fixes a bug that was introduced in this PR: https://github.com/dcos/dcos-ui/pull/2078
Mesos task IDs are not always unique (e.g. an app with a simple sleep will create instances with same ID) and therefore we cannot use this as a unique property in the table.
**Checklist**

[release/1.8] Fix task table keys

---

system-tests/cypress.json
system-tests/jobs/test-jobs.js
system-tests/services/test-apps.js
system-tests/services/test-environment.js
system-tests/services/test-pods.js

This PR fixes a couple of typos and silly mistakes in the system tests. Namely:
* Changing forgotten `services/details` url to `services/overview`
* Adding `{force: true}` to job's `Add Label` click to mitigate the
cypress complaints about zero-height
* Adding the correct timeout when waiting for service/job deployment
* Increased the default command timeout to 1 minute, which seems to fix all the instability issues.
**It's OK to have the following failure. It's addressed on #2088:**
```
✘ Services Applications Create an app with external volume
```
To test, use:
<pre>
-e CLUSTER_URL=<strong>$OPEN_CLUSTER_URL</strong>  \
</pre>

[System Tests]: Fixing a couple of typos

---

plugins/services/src/js/utils/ServiceUtil.js
plugins/services/src/js/utils/__tests__/ServiceUtil-test.js

This PR adds a method to `ServiceUtil` to determine when a service is an SDK service. It does this by checking for the existence of the label `DCOS_COMMONS_API_VERSION`.
cc @mlunoe 
**Checklist**

DCOS-15164: Add #isSDKService to ServiceUtil

---

system-tests/jobs/_scripts/teardown
system-tests/services/test-apps.js

---
~⚠️  Depends on #2114~
---
This PR is fixing the `test-apps` system test that was testing against the previous (buggy) version of the UI where the external volume units were "MiB" instead of "GiB"
To test, use:
<pre>
-e CLUSTER_URL=<strong>$OPEN_CLUSTER_URL</strong>  \
</pre>

[System Tests] Fix external volumes test from "MiB" to "GiB"

---

plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/constants/VolumeConstants.js
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js
plugins/services/src/js/service-configuration/PodStorageConfigSection.js

This PR adds host volumes support for Pods
@leemunroe would you please validate the UI change?
before:
After:
Test json:
```json
{
"id": "/host",
{
"resources": {
"cpus": 0.1,
"mem": 128
},
{
"name": "vol1",
"mountPath": "containerpath"
}
]
}
],
"scaling": {
"kind": "fixed",
"instances": 1
},
"networks": [
{
"mode": "host"
}
],
"volumes": [
{
"host": "hostpath",
"name": "vol1"
}
]
}
```
**Checklist**

DCOS-14384: Add host volumes support for Pods

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/__tests__/ServiceBreadcrumbs-test.js

This bug was introduced in this PR: #2079
This PR makes sure that we display `overview` route for service groups and a `detail` route for a service:
**Checklist**

DCOS-14508: Service breadcrumbs: Use overview route for service groups

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js

This PR fixes a bug where the we redirect to a route with `undefined` after deploying a service.
**Checklist**

DCOS-15229: Fix undefined route redirect

---

plugins/services/src/js/utils/DeclinedOffersUtil.js
plugins/services/src/js/utils/__tests__/DeclinedOffersUtil-test.js

This PR fixes a bug where an offered resource's `scalar` value might be displayed as `NaN` when the API omits this value. Now the `scalar` value is default assigned to `0`.
Before:
**Checklist**

DCOS-14845: Default to 0 for undefined scalar values in DeclinedOffersUtil

---

npm-shrinkwrap.json
package.json
src/styles/components/dropdown-menus/styles.less

This PR updates CNVS to 1.1.8. So far I found that the dropdown caret alignment was broken, which I've fixed in this PR as well.
@ashenden can you provide some information about what's changed since 1.1.6?

Update CNVS to 1.1.8

---

plugins/services/src/js/service-configuration/PodStorageConfigSection.js

This PR fixes the alignment of the "read only" value in `PodStorageConfigSection`. Before we were rendering an element with class `.configuration-map-value` inside a table cell which already has padding, so the padding was doubled up.
Before:
After:
**Checklist**

DCOS-14755: Fix 'read only' value alignment

---

src/styles/components/page-header/navigation/styles.less

This PR fixes a bug where the dropdown menu in the page header didn't fill its `flex` parent. It only applies to the dropdown within the `page-header-content-section` because of its `flex-direction`.
Before
After:

fix(page header navigation): Fix page header navigation flex props

---

plugins/services/src/js/utils/DeclinedOffersUtil.js
plugins/services/src/js/utils/__tests__/DeclinedOffersUtil-test.js

**This is the same commit as https://github.com/dcos/dcos-ui/pull/2110, but now Prettier** 😄 
This PR fixes a bug where an offered resource's `scalar` value might be displayed as `NaN` when the API omits this value. Now the `scalar` value is default assigned to `0`.
Before:
**Checklist**

DCOS-14845: DeclinedOffers now default to 0 for undefined scalar values

---

plugins/services/src/js/containers/pod-debug/PodDebugContainer.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js

This PR changes the behavior of declined offers to always show the declined offers summary & table when the data is available. Previously the summary & table were hidden until the resource had been waiting more than 5 minutes.
**Checklist**

DCOS-14184: Always show declined offers data if available

---

plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/containers/tasks/__tests__/TaskTable-test.js
src/js/components/CheckboxTable.js

This PR is the same as this just pointing to release 1.9: https://github.com/dcos/dcos-ui/pull/2128
This PR fixes a bug that was introduced in this PR: https://github.com/dcos/dcos-ui/pull/2078
Mesos task IDs are not always unique (e.g. an app with a simple sleep will create instances with same ID) and therefore we cannot use this as a unique property in the table.
**Checklist**

↩️ Fix task table keys (Mesos task IDs are not unique)

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/utils/HealthCheckUtil.js
plugins/services/src/js/utils/__tests__/HealthCheckUtil-test.js
plugins/services/src/js/validators/MarathonAppValidators.js

**Checklist**
This PR is deprecating Marathon healthcheck protocols `http`, `https` and `tcp`. And also ensures that unsupported health checks do not break the ui:
For testing purposes here is a JSON:
```JSON
{
"id": "/myapp",
"cmd": "sleep 1000;",
"cpus": 1,
"mem": 2048,
"healthChecks": [
{
"path": "/status",
"portIndex": 0,
"protocol": "HTTP",
"gracePeriodSeconds": 300,
"intervalSeconds": 60,
"timeoutSeconds": 20,
"maxConsecutiveFailures": 3,
"ignoreHttp1xx": false
}
],
"portDefinitions": [
{
"port": 0
}
]
}
```
Closes DCOS-14759

DCOS-14759: deprecate marathon Healthcheck protocols

---

system-tests/services/test-pods.js

This PR introduces the automated tests for [Create a pod with a virtual network](https://wiki.mesosphere.com/pages/viewpage.action?pageId=101253133)
**The following test is expected to fail**, because some volume labels have changed (`MiB` to `GiB`, or vice versa, I can't remember) and they have not yet been released in the DCOS release branches:
```
✘ Services Applications Create an app with external volume
```
<pre>
docker pull mesosphere/dcos-ui && docker run -it --rm --ipc=host \
</pre>

[System Tests]: DCOS-12808: Add SI tests for pod with virtual network

---

system-tests/services/test-pods.js

This PR introduces the automated tests for [Create a pod with a virtual network](https://wiki.mesosphere.com/pages/viewpage.action?pageId=101253133)
**The following test is expected to fail**, because some volume labels have changed (`MiB` to `GiB`, or vice versa, I can't remember) and they have not yet been released in the DCOS release branches:
```
✘ Services Applications Create an app with external volume
```
To run this test use:
<pre>
docker pull mesosphere/dcos-ui && docker run -it --rm --ipc=host \
</pre>

[System Tests]: DCOS-12811: Add SI tests for pod with ephemeral volume

---

plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/containers/tasks/__tests__/TaskTable-test.js

This PR fixes a bug that was introduced in this PR: https://github.com/dcos/dcos-ui/pull/2078
Mesos task IDs are not always unique (e.g. an app with a simple sleep will create instances with same ID) and therefore we cannot use this as a unique property in the table.
**Checklist**

Fix task table keys (Mesos task IDs are not unique)

---

system-tests/services/test-pods.js

This PR introduces the automated tests for [Create a simple pod with environment variables](https://wiki.mesosphere.com/pages/viewpage.action?pageId=101253142)
**The following test is expected to fail**, because some volume labels have changed (`MiB` to `GiB`, or vice versa, I can't remember) and they have not yet been released in the DCOS release branches:
```
✘ Services Applications Create an app with external volume
```
<pre>
docker pull mesosphere/dcos-ui && docker run -it --rm --ipc=host \
</pre>

[System Tests]: DCOS-12812: Add SI tests for pod with environment variables

---

system-tests/jobs/test-jobs.js
system-tests/services/test-apps.js
system-tests/services/test-environment.js
system-tests/services/test-pods.js

This commit adds an afterEach hook to the system tests, that forces
cypress to visit 'about:blank', effectively cleaning-up the previous
state. This way we can avoid stale XHR requests from previous tests
to affect the next tests.
This PR fixes a bug that causes some tests unexpectedly to be blocked by the _Login_ screen.

[System Tests] Adding cleanup after every test

---

plugins/services/src/js/components/LogView.js
src/js/components/Loader.js
src/styles/components/loaders/styles.less

__1 of 3__
[2 of 3](https://github.com/dcos/dcos-ui/pull/2151)
[3 of 3](https://github.com/dcos/dcos-ui/pull/2152)
This PR adds a new loader type and size, for use with the upcoming deployments button. This will be used for the new deployments feature.
**Checklist**

[Deployments 1 of 3]: DCOS-15161: Add new loader type & size

---

system-tests/services/test-pods.js

This PR fixes the underlaying issues that causes the latest nightly buillds to fail.
- Fixes `Create a pod with environment variable` that was checking
for an `env` property instead of `environment` in the definition
- Fixes `Create a pod with ephemeral volume` that was using the old
layout to create an ephemeral volume
To test, use:
<pre>
docker pull mesosphere/dcos-ui && \
-e CLUSTER_URL=<strong>$OPEN_CLUSTER_URL</strong>  \
</pre>

[System Tests]: Fix faulty system tests

---

npm-shrinkwrap.json
package.json

This PR updates reactjs-components to version 0.16.0-beta.18.
PRs in this release of reactjs-components:
https://github.com/mesosphere/reactjs-components/pull/402
**Checklist**

Update reactjs-components 0.16.0-beta.18 (Prettier)

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
plugins/services/src/js/constants/ServiceActionLabels.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/service-detail/ServiceInfo.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
src/js/translations/en-US.json
tests/_fixtures/marathon-1-task/groups-sdk-services.json
tests/_fixtures/marathon-1-task/groups-suspended-sdk-services.json
tests/_fixtures/marathon-1-task/sdk-service-suspended.json
tests/_fixtures/marathon-1-task/sdk-service.json
tests/_support/index.js
tests/components/PageHeader.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

This PR introduces new modals for SDK services and applies them only to the services in the service table.
1 of 2: https://github.com/dcos/dcos-ui/pull/2144
2 of 2: https://github.com/dcos/dcos-ui/pull/2160
Test this by adding this repository for packages and installing the Hello Wolrd package:
https://infinity-artifacts.s3.amazonaws.com/autodelete7d/hello-world/20170501-114415-H2EXdmN1BlhErgpw/stub-universe-hello-world.zip
This PR merges to a feature branch and is not concerned with:
- group actions
- service detail actions
- pod detail actions
- service configuration
These will come in later PRs
(Preview doesn't seem to work 😢  Here is the link: https://cl.ly/kDyf/Screen%20Recording%202017-04-28%20at%2010.22.gif)
**Checklist**
P.S. Don't be scared by the huge amount of additions. I took …

[SDK Actions 1 of 2] DCOS-14910: Disable sdk service actions

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
plugins/services/src/js/constants/ServiceActionLabels.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesTable.js
src/js/translations/en-US.json
src/js/utils/__tests__/ServiceUtil-test.js
tests/_support/index.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js
tests/pages/services/ServiceVersions-cy.js

This PR introduces disabled modals for SDK services in the service and pod detail.
~~1 of 3: https://github.com/dcos/dcos-ui/pull/2144~~ Merged
~~2 of 3: https://github.com/dcos/dcos-ui/pull/2160~~ Merged
3 of 3: https://github.com/dcos/dcos-ui/pull/2163
Test this by adding a service with the two labels:
`DCOS_COMMONS_API_VERSION = "v1"` and
`DCOS_PACKAGE_NAME = "my-package"`
**Checklist**
~~Diff between the two PRs: https://github.com/dcos/dcos-ui/compare/mlunoe/DCOS-14910-disable-sdk-service-actions...mlunoe/DCOS-14910-disable-sdk-group-actions~~ Merged

[SDK Actions 3 of 3] DCOS-14910: Disable SDK service detail actions

---

plugins/services/src/js/routes/services.js
src/js/components/Sidebar.js
src/js/components/SidebarHeader.js
src/js/pages/SystemOverviewPage.js
src/js/pages/system/OverviewDetailTab.js
src/js/routes/system-overview.js

⚠️  Should go together with https://github.com/mesosphere/dcos-ui-plugins-private/pull/586
(**DCOS-15395**) Rename `system-overview` menu to `overview` and rename `Security` to `Secrets`.
How to test it?
On the left sidebar navigation before you would see `system overview` with this PR you will see only `overview`. All links to `system overview` should go to `overview` now.
On the left sidebar navigation before you would see `security` and `secrets` below with this PR you will see only `secrets`. All links to `security` should go to `secrets` now.
**Checklist**

feat(DCOS-15395): Rename menu items

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/IpAddress.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/IpAddress-test.js
plugins/services/src/js/reducers/serviceForm/Network.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/Network-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortDefinitions-test.js
tests/_fixtures/marathon-1-task-with-volumes/groups.json
tests/pages/services/ServiceFormModal-cy.js

**TL;DR** Batch transaction paths `container.docker.network` -> `networks.0.mode`
This PR prepares the base for the new Network API.
Currently Batch transactions paths reflect JSON structure and with this PR we are switching them to be more generic.
As a start of the migration, we switch from a single network to an array of networks hardcoded to handle the first element only.
Currently the UI supports only one network for a single container app, defined in `container.docker.network` there's a migration coming with marathon 1.5, networking API will be unified with Pods allowing a user to have more than one network per app. To achieve this, Marathon team reorganized the app definition moving networking information from `container.docker.network` on the top level and making it to be an …

[marathon 1.5] Make docker network transactions JSON paths agnostic

---

tests/_support/index.js

This PR adjusts the logic in `visitUrl` in our integration tests to set a cookie containing the user ID `ui-bot`. This should allow us to filter out all of the analytics data from running integration tests.
**Checklist**

DCOS-14595: Identify user as ui-bot for integration tests

---

plugins/services/src/js/components/DeploymentsModal.js

This PR removes the actions dropdown for deployments that contain SDK services.
**Checklist**

feature(DeploymentsModal): Hide actions dropdown if for SDK deployments

---

src/js/components/Loader.js
src/styles/components/loaders/styles.less

This PRs allows us to flip the loading indicators horizontally. This is a lot easier than modifying the timing of the animations for each loading indicator.
An example use case...
Without flipping:
With flipping:
**Checklist**

feature(Loaders): Allow flipping loading indicators horizontally

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Networks.js

Disable the networking form if more then one
network is set. If this happens the form section
will only show the JSON from `networks`.
**Checklist**
Closes DCOS-15568

DCOS-15568: show warning on multiple networks

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/Service-test.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js
tests/components/PageHeader.js

This PR...
* introduces a `getTaskCount` method on the `Service` and `ServiceTree` structs which tallies the number of tasks as reported by Marathon
* implements the `getTaskCount` method for the `ServiceTable` and `ServiceBreadcrumbs` components
Before:
After:
**Checklist**

DCOS-15173: Fix incorrect running task count

---

src/js/components/ExpandingTable.js
src/js/components/__tests__/ExpandingTable-test.js
tests/pages/services/DeploymentsModal-cy.js

This PR extends the functionality of `ExpandingTable` by allowing the user to have all rows expanded when the component mounts (and when new rows are added that are not currently collapsed).
**Checklist**

feature(ExpandingTable): Allow rows to be expanded on mount

---

system-tests/services/_scripts/teardown-packages
system-tests/services/test-packages.js
system-tests/services/tests.yml

Removing previously scaffolded test files till we have time to write actual tests.
The teardown file will error out as `kafka` is not a valid app installed - so lets remove! This code was introduced in https://github.com/dcos/dcos-ui/pull/2168
**Checklist**

Remove scaffolded system test files

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js

This fixes a small bug where the text in the `ServiceDestroyModal` didn't reset when closing the modal. It is fixed by calling `this.handleModalClose` instead of `this.props.onClose`.

fix(ServiceDestroyModal): Reset text when closing

---

plugins/services/src/js/components/DeploymentStatusIndicator.js

This PR fixes a bug with the `DeploymentStatusIndicator`.
To reproduce, checkout `master` and do the following:
1. While a deployment is active, click the deployments button to show the deployments modal
2. In a second tab, destroy the deploying service
3. In the second tab, deploy another service. You should see the `DeploymentModal` appear in the first tab.
This PR fixes the bug by resetting the `isOpen` state in `DeploymentStatusIndicator` when the deployment count is 0.
Thanks @nLight for filing this issue!
**Checklist**

fix(DeploymentStatusIndicator): Reset modal open state when deployment count is 0

---

src/js/components/form/AddButton.js
src/js/components/form/AdvancedSectionLabel.js

This PR fixes a regression where the icons in buttons didn't have margins. CNVS applies margins to _all_ adjacent DOM nodes inside buttons, and with the upgrade to React 15, the text nodes were no longer being wrapped in `span` elements. So this PR adds them explicitly.
Before:
After:
**Checklist**

fix(AddButton&&AdvancedSectionLabel): Wrap text nodes in spans for proper margins

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js

This PR fixes a bug in the service create form. When the checkboxes in the "Advanced Settings" section were disabled, they didn't have margins between them.
Before:
After:
**Checklist**

fix(ContainerServiceFormAdvancedSection): Fix adjacent disabled checkbox margins

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js
tests/pages/services/ServiceFormModal-cy.js

How to test this:
Launch a cluster with a custom configuration specifying **`testing/pull/1481`** to use the snapshot release https://github.com/dcos/dcos/pull/1481/files 
This release though doesn't accept the old definition of a BRIDGE network for UCR, 
it supports the new version instead: 
```javascript
{
"networks": [
{
"mode": "container/bridge"
}
]
}
```
and it returns updated definition in the new format.
Host volumes and force Pull Image work as expected.
Having said that we've concluded to run this PR against the integration branch `integrate/marathon-1.5` that will be merged to master once all the respective changes are merged in Marathon/DCOS.

[marathon 1.5] DCOS-14703: UCR Improvements

---

plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js

**DCOS-15234** Display service ports only when available under service configuration tab.
**Checklist**

fix(DCOS-15234): Display service ports only when available

---

plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js

Change the placements constraints validation to not return errors for
optional fields.
Closes DCOS_OSS-1132

DCOS_OSS-1132: Adjust the constraints validation to fix validation errors

---

src/js/components/JobForm.js
src/js/schemas/job-schema/Schedule.js

The issue would occur even if the schedule had been manually disabled.
closes DCOS-15615
**Checklist**

fix (JobForm) Fixes issue where the enabled flag would always be truthy

---

plugins/nodes/src/js/components/HealthTab.js
plugins/nodes/src/js/components/NodesTable.js
plugins/services/src/js/components/DeclinedOffersTable.js
plugins/services/src/js/components/TaskDirectoryTable.js
plugins/services/src/js/components/VolumeTable.js
plugins/services/src/js/containers/service-debug/TaskStatsTable.js
plugins/services/src/js/containers/services/ServicesTable.js
src/js/components/CheckboxTable.js
src/js/components/ExpandingTable.js
src/js/components/RepositoriesTable.js
src/js/components/UnitHealthNodesTable.js
src/js/pages/jobs/JobsTable.js
src/js/pages/network/VirtualNetworksTable.js
src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js
src/js/pages/system/OrganizationTab.js
src/js/pages/system/UnitsHealthTab.js
src/styles/content/tables/styles.less
src/styles/content/tables/variables.less

Proposal to improve table styling.
1. Add a row hover style. Why?  Improves usability by visually highlighting the row the user is looking at so they can see the related data and columns.
2. Remove the highlighted active column. Why? Don't think this is adding value (as the caret already shows the active column) and it looks odd whenever there are just two columns.
3. Show the sorting caret on hover. Why? So the user knows they can interact with and sort the table.
Before
https://cl.ly/3Z40263T2c1y
After
https://cl.ly/0U05022x2M3p
cc @ashenden

Add table row hover and remove highlighted column styling

---

src/js/pages/jobs/JobsTable.js

**DCOS_OSS-1108** Remove class on status label which was blending the color with background and making the text not visible to users.
**before**
**after**
**Checklist**

fix(DCOS_OSS-1108): Fix jobs status display

---

plugins/oauth/hooks.js
src/js/utils/RouterUtil.js
src/js/utils/Util.js
src/js/utils/__tests__/RouterUtil-test.js
src/js/utils/__tests__/Util-test.js

(**DCOS-15332**) This PR removes the ability to use the redirect in the client side for security reasons.
This is like-a-proposal because I personally did not find any use for it yet after looking in the code and in the jira tickets so I'm assuming this is safe to delete.
**Checklist**

fix(DCOS-15332): Validate redirect is the same domain as the original hostname

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/FormReducers/SingleContainerPortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/FormReducers/SingleContainerPortMappingsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortMappingsReducer.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/PortMappings.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortDefinitions-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortMappings-test.js
src/js/utils/NetworkValidatorUtil.js
src/js/utils/__tests__/NetworkValidatorUtil-test.js

This PR adds a field for Load Balanced port that has meaningful default values. For HOST network it will be hostPort and for Bridge/User networks it will be container port

↩️ [release/1.9] DCOS_OSS-956: Implement a field for a load balanced port

---

plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js

---
⚠️  _This PR back-ports a fix to release/1.9 introduced with #2204._
---
Change the placements constraints validation to not return errors for optional fields.
Closes DCOS_OSS-1132

↩️  DCOS_OSS-1132: Adjust the constraints validation

---

scripts/pre-push
scripts/validate-tests

`it.only` has bitten me once again... 😖
Here I'm adding the validate-tests script on pre-push hook. So you can always rebase and remove that `.only` you've forgotten.

Validate tests on pre-push

---

plugins/services/src/js/pages/task-details/TaskFileViewer.js

**DCOS-12849** This PR defaults the logs to `stderr` that way decreasing the number of clicks the user needs to do before seeing the logs.
**Checklist**

feat(DCOS-12849): Defaults services logs to stderr

---

plugins/oauth/hooks.js
src/js/utils/RouterUtil.js
src/js/utils/Util.js
src/js/utils/__tests__/RouterUtil-test.js
src/js/utils/__tests__/Util-test.js

**DCOS-12243** If the user is logged out and try to go to a path e.g `http://localhost:4200/#/services/detail/%2Fsome-service/configuration`
we will redirect the user to login page but after the user log-in we do not send back to where the original path was.
This PR add the feat to redirect the user back to the relative path after logged-in.
**Checklist**

fix(DCOS-12243): Redirect user back to original relative path after logged-in

---

plugins/services/src/js/containers/volume-detail/TaskVolumeContainer.js
plugins/services/src/js/pages/task-details/TaskDetail.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/Task.js
plugins/services/src/js/structs/__tests__/Task-test.js
plugins/services/src/js/utils/ServiceUtil.js
plugins/services/src/js/utils/__tests__/ServiceUtil-test.js

Previously we were inferring a service's name based on the task ID (e.g. for task ID `foo_bar_baz`, we assumed a service name of `baz`), then finding the Marathon service by this name. This caused collisions when services shared the same name at different paths (e.g. `/foo/bar/baz` and `/corgly/baz`).
With this PR, we'll infer a service's full ID based on the task ID (e.g. for task ID `foo_bar_baz`, we assume a service ID of `/foo/bar/baz`) and then find the Marathon service with this ID.
To accomplish this, I did the following:
1. I moved `#getServiceId` from the `Task` struct to the `ServiceUtil` and renamed to `#getServiceIDFromTaskID` (to match the `#getServiceNameFromTaskID` method)
2. I implemented `#getServiceIDFromTaskID` in `ServiceTree#getServiceFromTaskID`
3. I implemented …

fix(ServiceUtil): Fix a bug when matching Mesos task IDs to Marathon services

---

plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

Use data from mesosStateStore to aggregate
healthstatus for a framework.
Closes DCOS-15172
**Checklist**

DCOS-15172: fix(healthBar): Include framework tasks in bar

---

src/styles/content/tables/styles.less

This PR fixes a bug that was introduced in #2162. We accidentally removed the styles for `.table-display-on-row-hover` elements, which should be displayed in all tables once the row is hovered.
Before:
After:
**Checklist**

fix(tables): Fix .table-display-on-row-hover elements

---

src/js/components/charts/TimeSeriesMouseOver.js

This PR hides the mouse coordinate axis lines on initial render and when the cursor leaves the time series graph. Previously the lines were rendered on the graph at all times; at mount they were visible at the top and left edges, and were not hidden when the mouse left the graph.
Before:
After:
**Checklist**

fix(TimeSeriesGraphs): Hide mouse coordinate axis lines on mouse out

---

src/js/components/breadcrumbs/JobsBreadcrumbs.js
src/js/pages/jobs/JobDetailPage.js
src/js/pages/jobs/JobTaskDetailPage.js
src/js/pages/jobs/JobsTab.js

Utilize the  job tree structure for the breadcrumb generation instead of relying on a rather error prone string based mechanism. This change is a prerequisite for the job tree structure   adjustments to align the UI with the way Metronome handles IDs and namespaces.

Adjust job breadcrumb generation

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js

This PR disallows leading & trailing whitespace characters in label keys.
**Checklist**

DCOS-11685: Disallow leading/trailing whitespace chars in label keys

---

plugins/services/src/js/reducers/serviceForm/Container.js

Instead of deleting docker we are now overwriting
docker with null if it should *not* be present. This
will ensure that the base config will be
overwritten.
Error description:
In 1.9, create an app definition with a docker containerizer container such as alpine and a command of sleep 1000, save, then edit, then remove docker image and switch to mesos containerizer. GUI will show error 
There is an error with your configuration
container.type: Must be defined
Switching to json mode and it shows the alpine container still:
```
container": {
"docker": {
"privileged": false,
"forcePullImage": false,
"image": "alpine"
}
},
```
Closes DCOS-14880
**Checklist**

fix(DCOS-14880): Remove docker from container if needed

---

plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/constants/VolumeConstants.js
plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/LocalVolumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/UnknownVolumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/UnknownVolumes-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js
plugins/services/src/js/service-configuration/PodStorageConfigSection.js

ℹ️  **Dependencies**:
1. ~#2221~
2. https://github.com/mesosphere/dcos-ui-plugins-private/pull/601
✅  **Checklist**
This PR adds support for unknown volumes, they won't be shown in the Form, but the Batch now is fully aware of them, parses them and reduces them back.
Decided not to extract chores and Volumes-test move, they are isolated and small. 
**Testing**
Please test along with: https://github.com/mesosphere/dcos-ui-plugins-private/pull/598
and follow the instructions provided there.

DCOS-15999: Support unknown volumes

---

plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/reducers/serviceForm/Volumes.js

This commit disables the possibility to set size
on an external volumes for Docker containers.
Closes DCOS_OSS-1237
**Checklist**

↩️[1️⃣.9️⃣] DCOS_OSS-1237: Remove Size from ExternalVolumes with docker runtime

---

plugins/services/src/js/components/forms/VolumesFormSection.js

This only changes the copy of the tooltip to be more fitting.

fix(externalVolumes): change copy of tooltip

---

plugins/services/src/js/components/MarathonTaskDetailsList.js

This fixes [DCOS-16286](https://jira.mesosphere.com/browse/DCOS-16286) by changing the field name from `status` to `state`, and using the `TaskStates` map to render the proper display name.
**After**:
**Checklist**

fix(DCOS-16286): Fix task detail view marathon task status

---

src/js/components/ConfigurationMapLabel.js
src/js/components/HashMapDisplay.js
src/styles/components/configuration-map/styles.less

**DCOS-15288**: fixes capitalized mesos agent attributes. It does this by introducing a new class `"configuration-map-attribute-label"` that resets the CSS text-transform.
**before**:
**after**:
**Checklist**

fix(DCOS-15288): override uppercase key for mesos agent attributes

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
src/js/translations/en-US.json
tests/pages/services/ServiceActions-cy.js

**DCOS-16008** This PR improve the service confirmation modal where now we only display the path/service.
This PR also adds a couple of minor fixes to typos and input autofocus.
How to test:
Create a service container then click delete de service container which will bring the modal to type the service name. before the entire path was required to be typed now only the service name
e.g `path/to/service/name` in case you are in the name service you will only need to type `name`.
If in the `/service/` path you will need to type only `service` but whatever is under service will also be deleted.
**Checklist**

fix(DCOS-16008): Improve service confirmation modal.

---

system-tests/jobs/test-jobs.js

This PR adds the missing "enable schedule" step. Use the following command to run the test:
```bash 
docker run -it -v $(pwd):/dcos-ui -e CLUSTER_URL=${CLUSTER_URL} mesosphere/dcos-ui dcos-system-test-driver -j=1 ./system-tests/driver-config/dev.sh
```

Adjust the creates job with schedule system test

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
src/js/components/form/FormGroupContainer.js
tests/pages/services/ServiceFormModal-cy.js

Clicking a container in a pod now takes you to that container's config page. This was brought up in user testing [here](https://jira.mesosphere.com/browse/DCOS-13054). 
After:
https://cl.ly/2O1W453N072V
**Checklist**

DCOS-13054: click container in pod takes you to container config

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js

If selecting a version now only a cleaned JSON is given to the
serviceForm.
Closes DCOS-14868
**Checklist**

DCOS-14868: fix(ServicesVersions) Clean VersionsJSON

---

src/js/events/MetronomeActions.js
src/js/stores/MetronomeStore.js
src/js/stores/__tests__/MetronomeStore-test.js

Change the `MetronmeStore` and `MetronmeActions` to fix issue with the data handling. All data received from the respective actions in now stored in a single array to keep the data always up to date and in sync. The store then parses the data into a `JobTree` instead of the actions providing pre-processed data.
BREAKING CHANGE:  The `REQUEST_METRONOME_JOBS_SUCCESS` as well as the `REQUEST_METRONOME_JOB_DETAIL_SUCCESS` event emitted by `MetronomeActions` have changed to fix issue with the data handling.
To migrate event handlers please  follow the example below:
Before:
```
function handleJobsSuccess(event) {
console.log(new JobTree(event.data));
}
```
```
function handleJobDetailSuccess(event) {
console.log(new Job(event.data));
}
```
After:
```
function handleJobsSuccess(event) { …
```

Adjust the Metronome data handling

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/EnvironmentVariables-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/MultiContainerEnvironmentVariables-test.js

This PR makes DC/OS parsers to parse string values for environment variables and let the plugins parse/reduce the rest.
To test: 
Create a secret and give it a hard time with a lot of Env vars and secrets. Switching between JSON editor and form. Add a var in the form edit in the JSON, delete in the form, add in the JSON. You know the grind.

DCOS-16190: Skip non-string values in env var parsers

---

plugins/services/src/js/constants/DefaultApp.js
plugins/services/src/js/utils/CreateServiceModalFormUtil.js
plugins/services/src/js/utils/__tests__/CreateServiceModalFormUtil-test.js
tests/pages/services/ServiceFormModal-cy.js

This is a back port of https://github.com/dcos/dcos-ui/pull/2244
I had to adjust `applyPatch` tests since it uses `stripEmptyProperties` that I had to update so it doesn't remove empty arrays and objects.
To test: launch 1.9 cluster, go and create an app, verify that `portDefinitions: []`. Without the fix you won't see `portDefinitions` at all and because of that Marathon will create a port by default.

↩️ [1.9] DCOS-16147: default portDefinitions to an empty array

---

plugins/services/src/js/reducers/serviceForm/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/__tests__/EnvironmentVariables-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerEnvironmentVariables-test.js

---
ℹ️  This is a back port of #2253 
---
This PR makes DC/OS parsers to parse string values for environment variables and let the plugins parse/reduce the rest.
To test:
Create a secret and give it a hard time with a lot of Env vars and secrets. Switching between JSON editor and form. Add a var in the form edit in the JSON, delete in the form, add in the JSON. You know the grind.

↩️ [1.9] DCOS-16191: Skip non-string values in env var parsers

---

src/js/pages/catalog/PackageDetailTab.js

As mentioned in [DCOS_OSS-1300](https://jira.mesosphere.com/browse/DCOS_OSS-1300), make the install button visible on a small screen. 
This just uses the `media-object-wrap` class. The margin/padding isn't great on the second row. But this is within the flex item, and not sure if we should override this?
**After**:
https://cl.ly/1T2X3N1w0A1U
**Checklist**

fix(DCOS_OSS-1300): Flex wrap so it's visible on small screen

---

src/js/translations/en-US.json

This PR just removes the duplicated word `documentation` in the service actions modal.
Before:
After:
**Checklist**

DCOS-16009: fix(ServiceActionsModal): Remove duplicated word 'documentation'

---

src/js/events/CosmosPackagesActions.js
src/js/events/__tests__/CosmosPackagesActions-test.js
src/js/stores/__tests__/CosmosPackagesStore-test.js
src/js/stores/__tests__/fixtures/MockPackageDescribeResponse.json
tests/_fixtures/cosmos/package-describe.json

New cosmos packages will be built and served over v3 of the describe endpoint.
Only real change is the new version of the API returns the object nested one level deeper in the response under the key "package".
Closes DCOS-16073
Test by navigating to the package detail view and verifying it shows the package.
**Checklist**

feat(CosmosPackagesActions): update cosmos describe API to use v3

---

plugins/services/src/js/containers/services/ServicesTable.js

This PR will render the animated health bar when a service's status is either `deploying` or `waiting`.
I also adjusted the way we determine the `isDeploying` property that's passed to `HealthBar`. Previously, we were comparing the displayed status string to a hard-coded string (`Deploying`). I've changed this to compare the status' `key` property to a constants file that maps to these keys.
It seems like we need to refactor the service status constants, as they are spread across multiple files, but this solves the issue and gets us closer to a more desirable solution, IMO.
Before:
After:
```
```
**Checklist**

DCOS-14185: chore(ServicesTable): Animate Waiting status

---

src/styles/views/packages/styles.less

This PR prevents overflowing text in the post-install notes of the `InstallPackageModal`.
Before:
After:
**Checklist**

DCOS-16010: fix(InstallPackageModal): Prevent overflowing text

---

plugins/services/src/js/containers/tasks/TaskTable.js
src/js/utils/ResourceTableUtil.js
src/styles/components/task-table/styles.less
src/styles/content/tables/styles.less

This PR fixes three small bugs related to table styling:
* toggle `visibility` instead of `display` property of sorting indicator carets
* right-align resource values in `TaskTable`
* remove sorting indicator for `logs` column
Before:
After:
**Checklist**

bug(Tables): Clean up table styling

---

plugins/services/src/js/components/ServiceStatusWarning.js

This PR wraps the service status warning icon in a link to the debug tab. We wanted this from the beginning, but the service detail tabs weren't routed until recently.
**Checklist**

DCOS-12470: feat(ServiceStatusWarning): Link to debug tab

---

plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js

This commit will introduce that only external
volumes in the MESOS container type are allowed to
have a size.
Closes DCOS_OSS-1238
**Checklist**

DCOS_OSS-1238: fix(externalVolumes): Remove size if docker

---

system-tests/services/test-apps.js

This adds system test coverage for a UCR runtime in two scenarios: 
1) using a Docker container and command 
2) using just a command
Most of this is direct copy-paste from the `"should create an app with docker config"` test, and just modifies by adding `selectMesosRuntime()` and changes a couple assertions to expect the mesos runtime. 
Run with:
```
docker run -it --rm --ipc=host \                                                       
-e CLUSTER_URL=$OPEN_CLUSTER \
mesosphere/dcos-ui dcos-system-test-driver --only "apps" -v \
```
**Checklist**

test(DCOS-15049): add two UCR container tests using docker and command

---

src/js/components/modals/InstallPackageModal.js

**Problem:**
Package will attempt to auto-install if window is resized while viewing the package detail page.
**Solution:**
InstallPackageModal `#componentwillReceiveProps` get's called when browser resize occurs. We only care about setting new component state if modal is opening or closing. We do **not** care if the modal is not in a transition. So we return early in the method if the component is not in a state of "transition" [opening/closing].
**Testing:**
Navigate to package detail page from catalog and resize window. Package previously attempted to send an API request for install when resizing but it **should no longer do this**.
**Note:**
I would love to clean this component up including the logic in `#componentwillReceiveProps`, however we don't have time to boy-scout this one. …

fix(InstallPackageModal): add tighter constraints for auto-install

---

plugins/services/src/js/pages/task-details/TaskDetail.js
src/js/components/breadcrumbs/JobsBreadcrumbs.js
src/js/pages/jobs/JobDetailPage.js
src/js/pages/jobs/JobRunHistoryTable.js
src/js/pages/jobs/JobTaskDetailPage.js
src/js/pages/jobs/JobsTab.js
src/js/pages/jobs/JobsTable.js
src/js/routes/jobs.js
src/js/utils/MetronomeUtil.js
src/js/utils/__tests__/MetronomeUtil-test.js
system-tests/jobs/test-jobs.js
tests/pages/jobs/JobActions-cy.js
tests/pages/jobs/JobDetails-cy.js
tests/pages/jobs/JobsFilter-cy.js
tests/pages/jobs/JobsOverview-cy.js

---
ℹ️   _This branch depends on features that will be introduced with ~#2267~ and ~#2268~, thus it will fail until the respective branches get merged._
↩️   _I will back-port the fix to `release/1.9` once the changes are approved._
---
Change the jobs parsing to properly parse jobs into namespaces and adjust the routing and view logic to handle namespaces and jobs properly, so that the routes don't collide. This allows jobs and
namespaces to have the same id without being collapsed into one object. An array of jobs like the following would be parsed into a job named "foo" and a namespace "foo" which will include the "foo.bar" job.
```
[
{ id: "foo" },
{ id: "foo.bar" }
]
```
```
[
{ id: "foo" },
{ id: "foo",
items: [
{ id: "foo.bar" }
]
}
]
```
These changes addresses issues with jobs …

DCOS_OSS-1033: Adjust jobs handling

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
plugins/services/src/js/stores/MarathonStore.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

This PR adresses an issue comming from improper Framework package name resolution.
The reported issue was that one cannot run a catalog app in a group like `/group/blop/kafka`
> Full disclosure: that shouldn't be allowed to do at first place, and you can't run marathon in a group, but for some reason validation for at least `kafka` works the other way.
While working on the fix for groups I discovered that our framework deletion dialog shows wrong information because of a bug in the framework package name discovery. That one is addressed as well.
Go to the Catalog and click on kafka, then click Configure and change its name to something with groups like `/some/group/not-even-kafka` and launch it. It should work (consult the ticket regarding the current state) then try to delete kafka _not_ …

DCOS-15838: Switch to DCOS_PACKAGE_NAME for a Framework package name

---

jest/gen-config.js

Explicitly configure `coverageReporters ` to include the defaults  ("json", "lcov", "text") as well as `cobertura` to generate Cobertura coverage reports. This change will allow us to collect and publish code coverage metrics in Jenkins.
Closes DCOS-16515

Change jest config to generate Cobertura coverage reports

---

plugins/services/src/js/reducers/serviceForm/MultiContainerNetwork.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerNetwork-test.js

... to handle name and mode transactions
The json and form reducer now also handles name and mode transactions which is fixing the behaviour
of the network select field and the name and the mode is set in a container network.
<details>
<summary>TEST this commit</summary>
- To test this commit go to the service create form
- Select Multi container
- Open JSON editor
- go to Network section
- Select Container network
- go to JSON editor change something
- Select field should stay on the `CONTAINER` network
- Go to Review screen
- Return to form
- Select field should still be right
- JSON should still contain mode and name
</details>
Closes DCOS-16589
**Checklist**

DCOS-16589: fix(MultiContainerNetwork): Adjust (JSON|Form)Reducer

---

src/styles/components/form-elements/form-group/styles.less

This PR fixes a spacing issue with form elements with tooltips. 
**Fix:**
I think this is the best solution. It targets the specific use of tooltips in form headings
and sets the max-height to match the label font-size, which looks like it's always 0.9rem set by canvas. 
**Before: (misalignment of service id and container image sections)**
**After:**
**Testing**:
Open create service form. Look around the rest of the UI for regression. Toggle browser window size, and check mobile user agent.
**Checklist**

fix(DCOS-11519): correct alignment of form labels with tooltips

---

src/js/structs/JobTree.js
src/js/structs/__tests__/JobTree-test.js

---
ℹ️   _This branch includes changes that will be introduced with #2251. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/orlandohohmeier/fix/DCOS_OSS-1033-adjust-jobs-handling...orlandohohmeier/chore/remove-unused-method-from-job-tree-struct_ 
---
Remove `findItemById` from JobTree struct as the method is no longer in use.

Remove unused method from job tree struct

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js

Updated using [this](https://github.com/dcos/dcos-website/blob/develop/redirect-files) mapping. Test this PR by navigating to create a service, and hover over the "container image" tooltip, then clicking the link to the docs within this tooltip.
**Checklist**

fix(DCOS_OSS-1287): update broken container docs link

---

plugins/services/src/js/containers/tasks/TaskTable.js

**DCOS-16539**
Fix tooltip on health status when state is `killing`.
Steps to reproduce the issue:
Create a service with a health check where is `healthy` 
Then suspend the service
Now the `status` should be `killing` and the health should be `red dot` but with `Healthy` on the tooltip.
**before**
**after**
**Checklist**

fix(DCOS-16539): Fix incorrect tooltip state on health check

---

plugins/services/src/js/service-configuration/PodNetworkConfigSection.js
tests/pages/services/ServiceFormModal-cy.js

Fix for the multi-container network config edit link.
Network "Edit" links don't work on the Multi-container Review screen.
Closes DCOS-16606
**Checklist**

DCOS-16606: Fix the multi-container network config edit link

---

src/js/components/Image.js
src/js/components/TimeAgo.js

This is a dcos-ui part of addressing react@15 wrong html attributes warnings.
`reactjs-components` part: https://github.com/mesosphere/reactjs-components/pull/407
They can totally go separately.

fix(react@15): Address unsupported attributes warnings

---

plugins/services/src/js/components/forms/ArtifactsSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
src/js/components/form/FieldAutofocus.js
src/js/plugin-bridge/PluginModules.js
src/js/utils/DOMUtils.js
src/js/utils/__tests__/DOMUtils-test.js
tests/pages/services/ServiceFormModal-cy.js

This component is introduced for autofocusing input/ textarea fields.
Usage
```
<FieldAutofocus>
<FieldInput name="id" type="text" value={data.id} />
</FieldAutofocus>
```
Once the FieldInput, FieldTextarea, input or textarea element is mounted, the document will focus on this element.
If another element with the FieldAutofocus container is already focused it won't focus on that element.
The FieldAutofocus is implemented on the NewCreateServiceModalForm for the Services Form Modal.
Closes DCOS-12615, DCOS-12613
**Checklist**

DCOS-12615: autofocus service form

---

plugins/services/src/js/containers/service-instances/ServiceInstancesContainer.js
plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/TasksView.js

This PR fixes the TypeError when selecting a task (via checkbox) on the node tasks page.
**DCOS_OSS-1350**
**Details**:
Remove dependency on the use of service struct for Services and Nodes instead start using require`DCOSStore.serviceTree` in `TasksView`.
When selecting a task on Service/Node page if it's not deploying you should be able to see the `restart` and `stop` buttons, if one of the services selected is deploying `restart` should be disabled. Should not throw a `TypeError`.
**Checklist**

fix(TasksView): improve is deploying to accommodate Node tasks

---

plugins/services/src/js/validators/VipLabelsValidators.js
plugins/services/src/js/validators/__tests__/VipLabelsValidators-test.js
src/js/utils/NetworkValidatorUtil.js
src/js/utils/__tests__/NetworkValidatorUtil-test.js

---
↩️  _This PR back-ports a fix to release/1.9 introduced with #2321_
---
Allow port 0 for vip port.
Closes DCOS-17262

↩️ fix(NetworkValidatorUtil): add support for 0 vip port

---

plugins/services/src/js/utils/MarathonErrorUtil.js
plugins/services/src/js/utils/__tests__/MarathonErrorUtil-test.js

---
↩️  _This PR back-ports a fix to release/1.9 introduced with #2319_
---
Adjust the `parseErrors` util to translates messages with empty or missing detail errors.
DCOS-17242

↩️  DCOS-17242: Adjust MarathonErrorUtil to handle missing detail errors

---

CODEOWNERS

Introduce `CODEOWNERS` file to require reviews from project/area owners.
Closes DCOS-17304

DCOS-17304: Introduce `CODEOWNERS` file

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js

**DCOS_OSS-744** This PR makes the edit button always visible in the service configuration page, this also updates to show apply when the user change to older versions.
**before**
**after**
**Checklist**

feat(ServiceConfiguration) Make edit button in service configuration visible

---

src/js/utils/NetworkValidatorUtil.js
src/js/utils/__tests__/NetworkValidatorUtil-test.js

Add support for 0 at the vip port in the network validator util.
Closes DCOS-17262
**Checklist**

DCOS-17262: fix(NetworkValidatorUtil): add support for 0 vip port

---

jest/gen-config.js

---
↩️  _This PR back-ports the changes introduced with #2296 to release/1.9._
---
Explicitly configure coverageReporters to include the defaults ("json", "lcov", "text") as well as cobertura to generate Cobertura coverage reports. This change will allow us to collect and publish code coverage metrics in Jenkins.
Closes DCOS-16515

↩️  Change jest config to generate Cobertura coverage reports

---

CODEOWNERS

---
↩️  _This PR back-ports a the CODEOWNERS file that was introduces with  #2323 to release/1.9 ._
---
Introduce `CODEOWNERS` file to require reviews from project/area owners.
Closes DCOS-17304

↩️  DCOS-17304: Introduce `CODEOWNERS` file 

---

npm-shrinkwrap.json
package.json

I discovered that our build depends on `compression-webpack-plugin` in a funny manner. And on the `@latest` version which is even funnier. So `compression-webpack-plugin@latest` hit version 1.0.0 and now it depends on `webpack` 2 or 3 Ooops 😊

chore(*): make compression-webpack-plugin a dependency

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/validators/MarathonAppValidators.js

Remove healthcheck validators, since we do not have any warning type and currently the user is not
able to create / edit an app with a marathon healthcheck
**Checklist**

fix(appValidators): Remove Healthchecks validators

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

This PR introduces the support for unknown values in container(s) images. They will now be saved
and not wiped with the next generation.
*How to test*
in the tests there is a good example which can be copied over. Apply it to the service form and try to wipe the custom / unknown value.
Closes DCOS-16705
**Checklist**

DCOS-16705: fix(ServiceForm): allow unknown values for container images

---

plugins/services/src/js/reducers/serviceForm/Container.js

volumes was returning an empty array which resulted in an error of undefined type for non docker
apps
Closes DCOS-17408
**Checklist**

DCOS-17408: fix(serviceForm): do not set container if it is not necessary

---

plugins/services/src/js/utils/MarathonErrorUtil.js
plugins/services/src/js/utils/__tests__/MarathonErrorUtil-test.js

Adjust the `parseErrors` util to translates messages with empty or missing detail errors.
DCOS-17242
**Checklist**

DCOS-17242: Adjust MarathonErrorUtil to handle missing detail errors

---

system-tests/services/test-apps.js

In the ServiceNetworkingConfigSection set the port to "Auto Assign" if requiredPorts is false.
If the requirePorts: true then show the selected port.
This PR will fix the system test errors that appear due to this change.
Closes DCOS_OSS-1272
**Checklist**

fix(ServiceNetworkingConfigSection): fix system-tests for auto-assign port

---

plugins/services/src/js/utils/PodUtil.js

To reproduce
1) Create a multi-container-pod with the following settings
```
{
"id": "/test-multi",
"version": "2017-07-20T20:29:38.654Z",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "nginx"
}
},
{
"name": "container-2",
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "python"
}
}
],
"networks": [
{
"mode": "host"
}
],
"scaling": {
},
"placement": {
}
},
"cpus": 0.1,
"mem": 32,
"disk": 10
},
"volumes": [],
"fetch": []
}
```
2) Once you save, you can click on the services tab, click on the service details and check the containers of the instance.
It should show container-1 and …

DCOS-14469: fix container duplicates for multi-container-pod

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js

This PR removes forgotten `scrollContainer=".gm-scroll-view"` from `Tooltips`. There was a refactoring back then and I think these just snuck in via merge conflicts.
If you go to the `Tooltip` component you won't find `scrollContainer` prop
https://github.com/mesosphere/reactjs-components/blob/master/src/Tooltip/Tooltip.js

[easy] Remove a left over scrollContainer prop

---

src/js/components/Image.js

This PR fixes required `src` type for the `Image` component.

[easy] Correct src prop type declaration in image  component

---

plugins/design-system/components/component-example/CodeExampleTabButton.js
plugins/design-system/components/component-example/CodeExampleTabButtonList.js
plugins/design-system/components/component-example/CodeExampleTabView.js
plugins/design-system/components/component-example/CodeExampleTabViewList.js
plugins/design-system/components/component-example/CodeExampleTabs.js

This PR adds the tab components needed for the design system code example component. It is essentially a rehash of our existing `Tabs` component and its associated subcomponents, but with a different styling.
****To Test:****
- See branch `tommy/design-system/component-example-ace-editor` for the complete implementation.
- In the UI: `Design System` --> `Components` --> `Checkboxes` --> `Code Tab`
- The tabs are working correctly
**Checklist**

DCOS-15921 (2 of 4): Tabs for Design System Code Example

---

plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Remove docker object if no image is provided and the container type is unequal to `"DOCKER"`
For testing create:
```
{
"id": "/sleeper",
"portDefinitions": [],
"container": {
"volumes": [],
"docker": {
"image": "alpine"
}
},
"cpus": 0.1,
"mem": 128,
"networks": [],
"fetch": [],
"constraints": [],
"cmd": "sleep 1000;"
}
```
Wait till the app is deployed then go in remove the `alpine` image and set the container runtime to
MESOS. The Result is positive if in the JSON the docker object is not present anymore. And you
should be able to deploy the new version.
Closes DCOS-17284
**Checklist**

fix(serviceForm): Remove docker object if no image is provided

---

system-tests/services/test-pods.js

This will fix the failing system test in Open DC/OS. It is failing because the container name is partially covered by the main content body. Solution is to force click, and then the test passes.
Example failure: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-ci-master-open/165/artifact/results/results.html
**Checklist**

fix(Pods-Test): force click container because partially covered

---

plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesTable.js
src/js/components/PageHeaderActionsMenu.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

Removes restart action button from services and service detail page when service is SDK.
A code refactoring was also done to follow `ServiceDetail` patterns for the dropdown items, meaning when testing this PR we need to do a sanity check for the other buttons besides `restart`
Closes DCOS-16564
**Checklist**

fix(PageHeaderActions): Remove restart action when is SDK

---

plugins/services/src/js/containers/tasks/TasksView.js

Disable restart in TasksView when is SDK, this is part of #2343
Closes DCOS-16564
**Checklist**

fix(TasksView): disable restart from tasksViews

---

src/js/stores/MesosStateStore.js

If you create a service inside a folder, it won't show all of the tasks under the service.
In the MesosStateStore we had the following check
```
const serviceName = service.getId().split("/").pop();
if(framework.name === serviceName) { ... }
```
with
```
service: { id: "/test/elastic" }
framework { name: "test/elastic" }
```
The problem is that if we have a service in a folder the service id is "/test/elastic" and with the split pop() we lose the full id.
Also the framework's name is "test/elastic". So it would compare framework.name = "test/elastic" with serviceName = "elastic" eventually.
> So you would see this on one DCOS dashboard
> and this on the Mesos dashboard
I created 2 new methods one **getFullId()** to return **"test/elastic"** from the service
and one **getServiceName()** to …

DCOS-17301: not all tasks were shown under the service

---

system-tests/_scripts/setup.sh
system-tests/universe/_scripts/teardown

Change the system test setup script to use the dcos 1.10 cli, to maintain compatibility with the respective DC/OS version, and fix the `appId` condition in the universe teardown script. These changes are needed to uninstall all universe packages launched during a test run.
Closes  DCOS-16636

DCOS-16636: Adjust setup and universe teardown script

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

**Description**:
As described in [DCOS-17205](https://jira.mesosphere.com/browse/DCOS-17205), this modal content on Open DC/OS should be as below:
**Checklist**

fix(ServiceEditModal): show service edit instructions only in enterprise

---

plugins/services/src/js/constants/TaskStates.js
plugins/services/src/js/containers/tasks/TaskTable.js
src/js/stores/MesosStateStore.js

Include unreachable tasks into the task list. Also make them selectable in the Task table in the
Service detail page.
To check the issue you have to deploy an application and then shut down a agent node where one task
is currently running. This does take a couple of steps
- Find out the master IP
- find out the internal agent IP
- ssh into the master best with -A option so that you can ssh into the agent with the same keyfile
- ssh from the master to the agent node
- run `sudo systemctl stop dcos-mesos-slave.service`
- wait about 10 minutes.
Your service will be unreachable at this point and it will still be in the task table.
Also a unreachable tasks are like Schroedingers, completed and active at the same time we decieded to
rather see them as active so we can kill / restart them from …

fix(MesosStateStore): include unreachable tasks

---

plugins/services/src/js/constants/TaskHealthStates.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/utils/GraphQLTaskUtil.js
src/js/stores/MesosStateStore.js

All tasks for an SDK service have been changed to report "healthy" by default, if in RUNNING state and they haven't been reported as "unhealthy". Previously tasks matching this criteria reported "unknown".
This change affects the tasks associated with an SDK service (service detail page for SDK service, and node detail page, where SDK tasks are running on that node).
SDK service detail before:
SDK service detail after:
Node detail before:
Node detail after:
**Checklist**

Adjust Health Reporting for SDK Tasks

---

src/js/components/charts/ResourceTimeSeriesChart.js

In the dashboard, in the cpu card under the percentage the (usedNumber) to (totalTotal) shares wasn't rounding up correctly.
Closes DCOS-17361
**Checklist**

DCOS-17361: round cpu allocation used and total value

---

.gitignore

The `.chrome/` directory is created by the chrome debugger vs plugin.
The `.envrc` file is needed for direnv. I personally use this to set up the right node environment,
this will always execute when I enter the directory. Since this is a very personal thing I thought I
add this to the gitignore.

chore(gitignore): add chrome directory and envrc file to gitignore

---

plugins/services/src/js/components/forms/MultiContainerFormAdvancedSection.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js

Include the forcePull parameter in the image object for the multi-container service.
You can find this option over here => https://mesosphere.github.io/marathon/docs/pods.html#containerizers
Closes DCOS-16280
To reproduce:
1) Open the multi-container create form
2) Once you open the container's options you can see a new option named "Force pull image on launch"
3) There are some interesting cases you can check
a) If the forcePull = false and the containerImageName == "" then the image object should be           
deleted
b) If the forcePull = true and the containerImageName == "" then the image object doesn't show in the JSON Editor but still exists, so if you set something at the container image name it should have forcePull = true.
c) If you first create a container and add only the …

DCOS-16280: include forcePull parameter in image object for multi-pod containers

---

tests/pages/services/ServiceFormModal-cy.js

Protect against regression of [this bug](https://jira.mesosphere.com/browse/DCOS-17566).
This adds a test that clicking the "Install a Package" button will redirect the user to the `/catalog` page.
Button of interest below:
Closes DCOS-17714.
**Checklist**

test(ServiceFormModal): add test for redirect to catalog

---

src/js/constants/JobStates.js
src/js/constants/JobStatus.js
src/js/pages/jobs/JobsTable.js
src/js/structs/Job.js

**Description**: 
Previously, jobs were only able to be sorted by Job Name. Nothing happened when clicking on the "Status" and "Last Run" columns.
This change adds sorting by "Status" and "Last Run". Both these columns are sorted in order of importance to the average user. For example, jobs who's last run failed are higher importance than successful jobs, and will be sorted to the top of the list.
The sort order is determined by the `sortOrder` fields in `JobStates.js` and `JobStatus.js`. This is similar to the existing [HealthSorting.js](https://github.com/dcos/dcos-ui/blob/master/plugins/services/src/js/constants/HealthSorting.js), which helps sort services.
**Testing**:
Go to the jobs page, and turn on fixtures, and click around on the column headers to see the sorting. Demo: …

fix(JobsList): add column sorting for Status and Last Run

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/components/modals/ServiceRestartModal.js
plugins/services/src/js/components/modals/ServiceSuspendModal.js
src/js/translations/en-US.json
tests/pages/services/ServiceActions-cy.js

Improve wording/sentence when deleting/suspending/restarting a service/pod/group
Closes DCOS-17296 and DCOS-17534
Be aware that the wording was updated here in comparison to the Jira comment after I discussed "offline" with @ashenden 
**Now:**
**Checklist**

fix(ServiceDestroyModal): improve wording on delete/restart/suspend

---

src/js/components/HashMapDisplay.js

Really small change, someone reported it to me a few weeks ago. The "features" hash map value was missing commas. 
Before:
After: 
Closes DCOS_OSS-1372.
**Checklist**

fix(HashMapDisplay): if item is array, join into comma seperated string

---

system-tests/_scripts/setup.sh

I ran locally and tests still pass by changing this from string to boolean.
**Checklist**

fix(system-tests): remove quote around false in CLI setup

---

src/js/pages/catalog/PackagesTab.js
tests/pages/catalog/packages/PackagesTab-cy.js

Change "Certified Services" to "Certified", and change "Community Services" to "Community" in the catalog tab. 
Closes DCOS-17527.
**Checklist**

fix(PackagesTab): remove "services" word from section headings

---

src/js/constants/JobConfig.js

historySummary field prevents you from saving a metronome job, so we should just blacklist it as it is a meta information. Please refer to the ticket to come up wit a testing scenario.

DCOS-17939: Blacklist historySummary

---

plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesTable.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

Suspending a SDK service is not supported, so remove its actions from the service table and service actions.
This is very similar to @weblancaster PR from a [few weeks ago](https://github.com/dcos/dcos-ui/pull/2343).
Closes DCOS-17982.
**Checklist**

fix(PageHeaderActions): remove suspend/resume for SDK service

---

plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesTable.js
tests/pages/services/ServiceActions-cy.js

This action is not supported for SDK service, so remove it from three places: two links in the service table row, and one link in the service detail header.
Closes DCOS-17979.
**Checklist**

fix(Services): remove "open service" buttons for SDK services

---

plugins/services/src/js/reducers/JSONSingleContainerParser.js

Remove duplicated fetch parser in the JSONSingleContainerParser.
As it happens the fetch parser was duplicated in the Parser and it was creating duplicated transactions for artifacts.
Closes DCOS-17705

DCOS-17705: fix(JSONSingleContianerParser): remove duplicated fetch parser

---

plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesTable.js
tests/pages/services/ServiceActions-cy.js

Add a `isEnabledSDKAction` filter to dynamically enable/disable SDK actions and enable `OPEN` and `EDTI` by default.
Closes DCOS_OSS-1569

DCOS_OSS-1569: adjust SDK action handling

---

system-tests/driver-config/jenkins.sh

As we'd like to run our system tests for every PR that means running them for 1.9 PRs as well. But 1.9 didn't have any system test, so we need at least the config in place otherwise Jenkins build will fail
The config is a copy/paste from master with one exception:
```
channel: testing/1.9.3
```
Hardcoded channel will ensure that we launch proper cluster in case we want to back port some of the tests.

↩️[release/1.9] chore(jenkins): add system tests config stub

---

src/js/components/charts/Chart.js
src/js/utils/DOMUtils.js
src/js/utils/__tests__/DOMUtils-test.js

Remove the `isElementOnTop` DOM util as the util is only used to check whether the `Chart` component should be updated. The checks performed by the utility force layout/reflow (for a
comprehensive list of properties or methods that force layout/reflow see:  https://gist.github.com/paulirish/5d52fb081b3570c81e3a) and as such shouldn't be used to check whether a component should be updated. The util also always returns true if an element is off the screen which completely renders the utility useless if used as a should component
update condition.

refactor(DOMUtils): remove isElementOnTop util

---

src/js/components/charts/ResourceTimeSeriesChart.js

In the dashboard, in the cpu card under the percentage the (usedNumber) to (totalTotal) shares weren't rounding up correctly.
Closes DCOS-17361, COPS-11, DCOS-18209
**Checklist**

DCOS-17361, COPS-11, DCOS-18209: round cpu allocation used and total value

---

CONTRIBUTING.md
packages/README.md

The missing guidelines on developing a package.

docs(packages): add package development guidelines

---

scripts/pre-install

---
ℹ️   _This PR is related to #2399 and "back-ports" the respective fix_
---
Update the Marathon RAML version to fetch the latest Marathon 1.4.7 API Spec and ensure that the UI is compatible with Marathon.
The latest spec includes `unreachableStrategy` adjustments that if not applied prevents users from creating/editings apps that are configured to expunge immediately or flag apps as inactive.
Closes DCOS_OSS-1609

DCOS_OSS-1609: update Marathon RAML version

---

scripts/pre-install
scripts/utils/marathon

Adjust the Marathon RAML URL pattern and update the version to fetch the latest Marathon 1.5 API Spec and ensure that the UI is compatible with
Marathon.
The latest spec includes `unreachableStrategy` adjustments that if not applied prevents users from creating/editings apps that are configured to expunge immediately or flag apps as inactive.
Closes DCOS_OSS-1582

DCOS_OSS-1582: adjust Marathon RAML install the version

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/constants/ContainerConstants.js
system-tests/services/test-apps.js
system-tests/services/test-external-volumes.js
tests/pages/services/ServiceFormModal-cy.js

In the new marathon service create form, instead of calling the checkbox Mesos Runtime, always call it Universal Container Runtime (UCR).
**Before**:
**After**:
Closes DCOS-18312.
**Checklist**

fix(GeneralServiceFormSection): rename Mesos runtime -> UCR

---

jest/gen-config.js

…s its own root
when using manual mocks for global packages or node modules, you have to place them into
"your root folder", sadly `testPathDir` is poorly named as it actually is defining root folders,
not only folders to search for tests.
this commit adds one root folder per package and plugin instead of just defining
"packages" and "plugins" as roots.
jest also renamed `testPathDir` to `roots` in newer versions which better explains
what this option is doing.

fix(jest-config) changed that every package/plugin has own root

---

packages/recordio/LICENSE
packages/recordio/README.md
packages/recordio/index.js
packages/recordio/package.json
packages/recordio/src/__tests__/read-test.js
packages/recordio/src/read.js

This PR introduces `recordio` package. The format is being used by Apache Mesos to encode events for the Event Stream at the HTTP Operator API. The package will be used to parse Mesos Even Stream.
Closes DCOS-18357

Add recordio reader package

---

plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js

Since we've ditched `applyPatch` but still want to keep in stuff that we don't know about we started copying values via `ADD_ITEM`. The problem here was that the internal representation of `protocol` field was an object wheres the JSON representation is an array. 
That array threw a wrench into the parser-reducer logic, because an array _is_ an object in javascript.
To fix the issue I had to delete `protocol` field for the `ADD_ITEM` event and process it separately. I also added a missing bit to out integrity test to make sure we won't have it again.
Closes DCOS-18694

fix(JSONReducers/Containers): delete protocol field on ADD_ITEM

---

src/js/utils/SchemaUtil.js
src/js/utils/__tests__/SchemaUtil-test.js

We've fixed that in 1.10 as a part of #2411 https://github.com/dcos/dcos-ui/pull/2411/commits/552770ab47e3f849e7e3cabc870682ab0314708f and agreed not to fix on master since the form will be gone in 1.11
But people still stumble upon this bug, so let's fix it just in case.
to test try editing `spark-history` catalog package. Without the fix it throws with the fix it opens the form that looks broken but that's because the package doesn't provide anything to config.

feat(SchemaUtil): parse a partial definition

---

plugins/services/src/js/reducers/serviceForm/FormReducers/SingleContainerPortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortDefinitions-test.js

---
↩️  _This PR back-ports the fix introduced with #2432 to release/1.10._
---
> Change the reducers to properly handle missing protocols as they otherwise throw type errors which results in duplicated JSON definitions and a broken editor experience.
>
> Closes DCOS-18788

↩️  DCOS-18788: adjust port definition protocol handling

---

plugins/services/src/js/reducers/serviceForm/FormReducers/SingleContainerPortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortDefinitions-test.js

---
↩️  _This PR back-ports the fix introduced with #2432 to release/1.10._
---
> Change the reducers to properly handle missing protocols as they otherwise throw type errors which results in duplicated JSON definitions and a broken editor experience.
>
> Closes DCOS-18788

↩️ DCOS-18788: adjust port definition protocol handling

---

src/js/events/CosmosPackagesActions.js
src/js/events/__tests__/CosmosPackagesActions-test.js
src/js/stores/CosmosPackagesStore.js
src/js/stores/__tests__/CosmosPackagesStore-test.js
src/js/stores/__tests__/fixtures/MockServiceDescribeResponse.json

These actions and stores were recently added, and it was a mistake to only return the `package` field of the response. The `package` field is just a static description of the cosmos package. But we also need the up to data options, available in the `resolvedOptions` field of the response. 
This changes these stores/actions to return the entire response from the API. 
**Checklist**

fix(CosmosPackages): return entire response for service/describe

---

.babelrc
jest/preprocessor.js
npm-shrinkwrap.json
package.json
webpack/webpack.dev.babel.js
webpack/webpack.test.js

Stage 3 brings a lot of nice things and means those proposals at the candidate level already which means little to no changes. Full list of stage 3 proposals can be found here https://github.com/tc39/proposals I'm especially looking forward to [rest and spread properties](https://github.com/tc39/proposal-object-rest-spread)

feat(babel): allow stage-3 syntax

---

Dockerfile
system-tests/_scripts/delete-cluster.sh
system-tests/_scripts/launch-cluster.sh
system-tests/driver-config/jenkins.sh

Adjust the system-tests driver configuration to use `dcos-launch` to provision clusters. 
Please Note: That the systems for this PR will fail as the new setup required `dcos-launch` to be installed. You need to build the docker image locally and then run the `dcos-system-test-driver` after you've provided the respective environment variables. 
Closes DCOS-18705

DCOS-18705: change cluster provisioning

---

packages/mesos-client/LICENSE
packages/mesos-client/README.md
packages/mesos-client/index.js
packages/mesos-client/package.json
packages/mesos-client/src/request.js
packages/mesos-client/src/stream/__tests__/parseRecordioRecords-test.js
packages/mesos-client/src/stream/__tests__/readRecordioRecords-test.js
packages/mesos-client/src/stream/index.js
packages/mesos-client/src/stream/parseRecordioRecords.js
packages/mesos-client/src/stream/readRecordioRecords.js

It is a wrapper that uses `http-service` to establish a connection and `recordio` package to parse the incoming data and deliver it as a `Rx.Observable`.
✅ #2407 `recordio` 
✅ #2415 `http-service` (former `resource-service`)
Closes DCOS-18358

Introduce mesos-client package

---

plugins/nodes/src/js/components/NodesTable.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
src/js/constants/NodesTableHeaderLabels.js
src/js/structs/Node.js
src/js/structs/__tests__/Node-test.js

Add a Region column to the nodes overview, displaying the region and zone information of the nodes.
Add Region and Zone information to the nodes detail page.
Closes DCOS-18858, DCOS-18949, DCOS-18859
**Checklist**

DCOS-18858, DCOS-18949: feat(nodes) - Add Region and Zone information

---

npm-shrinkwrap.json
package.json
plugins/services/src/js/components/LogView.js
src/js/components/Sidebar.js

Bump reactjs-components package version to beta.27.
Remove react-addons-css-transition-group as we don't use it anymore in reactjs-components.
Add react-transition-group as this is used now in reactjs-components.
Make adjustments to the code necessary for the react-transition-group library.
**Checklist**

Uninstall 03 | Bump reactjs-components to beta.27

---

plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js

Some frameworks in rare cases have a portDefinition name of null. Change key to index as portDefinition name could be null.
**Checklist**

Change key to index as portDefinition name could be null

---

plugins/nodes/src/js/components/NodesTable.js

This adds some space to the region column to fit the region name in one row.
*Now*:
*B4*:

fix(NodesTable): Add Column to fix column sizing of the region column

---

src/js/components/Banner.js
src/js/components/Page.js

This adds a generic `Banner` component. This component will be used in the [licensing private plugin](https://github.com/mesosphere/dcos-ui-plugins-private/pull/636).
This PR also introduces mounting the banner in the existing `Page` component. This will cause the banner to be shown at the top of each page when enabled (when a breach or expiry).
Closes DCOS-19135.
**Testing:**
Paste the following into `componentDidMount()` of `Page.js` component:
```
const MockBanner = () => {
return (
<Banner>
You have exceeded your 60 day limit by 2 days.
{" "}
<a href="https://mesosphere.com/product" className="message-link">
More Information
</a>
</Banner>
);
};
MountService.MountService.registerComponent(MockBanner, "Page:TopBanner");
```
After pasting this, the banner will render:
**Checklist**

feat(Banner): create Banner component and mount in Page

---

npm-shrinkwrap.json
package.json
src/js/container.js
webpack/webpack.dev.babel.js
webpack/webpack.production.babel.js

In order to loosen coupling in the codebase and set the foundation for the modularization. DI can help with singletons as the container will be the source of truth.
On top of that it's easier to test code with DI, just binding a mock to the container instead of relying on Jest or other tooling that isn't ideal.
So currently there's only npm dependencies and an empty container.
The first citizen of the container's going to be the MesosStream.

Introduce DI/IoC container

---

src/js/utils/Util.js
src/js/utils/__tests__/Util-test.js

During my MesosStream refactoring I stumbled upon the fact that we're just assume that we're always getting an array here, which might not always be true, so I decided adding `isArray` check.

Quickie: feat(Util.js): add isArray check

---

src/js/pages/system/OverviewDetailTab.js

This will mount the two licensing rows to the cluster overview. The row content will come from the licensing plugin.
Closes DCOS-19133.
**Checklist**

feat(OverviewDetailTab): add licensing rows mount point

---

src/js/container.js
src/js/core/MesosStream.js

This PR adds a ready to use `MesosStream` observable one can subscribe to to get the data. 
Opened against `drozhkov/introduce-ioc-container` for your convenience.
The observable is a `ReplaySubject` that will keep all previous values[<sup>1</sup>](#limit) and replay them to every new subscriber ensuring there's no data loss. 
`toConstantValue` IoC container will ensure you're getting the very same instance of the observable. 
`refCount` means that `rxjs` will take care counting subscribers and once there's no subscribers left it will terminate the observable. Once someone subscribes again it will open a new connection.
a bit of manual work need s to be done. `src/js/index.js` could be a good place to add this snippet.
```javascript
import container from "./container";
import …
```

Introduce Mesos Stream connection

---

plugins/services/src/js/containers/services/ServicesTable.js

Add tooltip explaining #/# in service instances column.
Closes DCOS-19370
**before**
**after**
**Checklist**

feat(ServicesTable): service instance column tooltip

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/components/modals/ServiceModals.js

Disable the ability to delete a group that contains services for every case.
Closes DCOS-19266
**Checklist**

DCOS-19266: Disable delete group functionality fully

---

Dockerfile

Remove empty continuation lines as they will become errors in a future docker releases. Run docker build to verify that the build still passes and that docker no longer warns.
Closes DCOS-19026

DCOS-19026: remove empty continuation lines

---

tests/pages/catalog/packages/package/PackageTab-cy.js
tests/pages/services/TasksTable-cy.js

Remove overlooked `only` function to run all the integration tests

chore(TasksTable-cy): remove only to run all tests

---

src/js/components/form/FormGroupContainer.js

This is fixing a regression from 5e2d832 which caused hover on all `FormGroupContainers`. This PR changes it to only apply the outline and cursor pointer when an `onClick` prop is provided.
Currently, the only time an `onClick` prop is provided to `FormGroupContainer` is in the container pods when creating a service. See below the hover classes on the container, but not networking or volumes pods.
@leemunroe can finally stop bugging me about this one now 💯 😄 
Closes DCOS-18317.
**Checklist**

fix(FormGroupContainer): only apply hover styles if onClick provided

---

src/js/pages/system/OverviewDetailTab.js

This fixup splits up the mount point into two to prevent ReactUtil from creating
an additional wrapper - which breaks the styling.
Closes DCOS-19398

fix(Licensing): split mount-point into one for each row

---

plugins/services/src/js/service-configuration/PodContainerConfigSection.js
plugins/services/src/js/service-configuration/PodGeneralConfigSection.js
plugins/services/src/js/service-configuration/PodNetworkConfigSection.js

Add conditionals to only render the actions if onEditClick is not undefined. **Now there should be nowhere with `onEditClick.bind()` without first checking that it's not an undefined reference.**
**Checklist**

fix(PodGeneralConfigSection): fix onEditClick being undefined

---

plugins/services/src/js/containers/service-connection/SDKServiceConnectionEndpointList.js

Open the new SDK edit page and not the disabled modal
**Checklist**

fix(endpoints): open sdk edit page for sdk services and not the disabled modal

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
src/js/translations/en-US.json

The Delete an SDK message in 1.10 tells users to use the framework cleaner script to clean up persistent state. This is no longer necessary in 1.10.
**Checklist**

docs(translation): remove framework cleaner instructions for 1.10

---

scripts/validate-tests

This will ensure that ".only" for integration tests, or "fit" for unit tests don't make it into our codebase.
**Checklist**

fix(validate-tests): throw error and exit 1 when regex match

---

scripts/pre-commit
scripts/pre-push
scripts/utils/test
scripts/validate-tests

Improve test validation by adding a new test util and adjusting the `validate-tests` script as well as the git hooks.
* Add a `find_debug_directives` test util to validate tests and make sure they don't include any debug directives preventing proper test execution.
* Adjust `pre-push` hook using the `find_debug_directives` test utility to bail if tests are invalid.
* Change the `validate-tests` script to validate all test using the `find_debug_directives` test utility. This change also removes the dependency on `egrep` which should no longer be used as it's deprecated binary.
* Introduce a test validation step to make sure that we don't commit any debug directives (e.g., `only`) which could render our test useless.

Improve test validation

---

plugins/services/src/js/components/DeploymentStatusIndicator.js

As per @leemunroe request, this PR replaces loader component with spinner icon introduced in #2475
Deploy an application
In services page on top right side, you should still see a spiner icon
**now:**
Closes DCOS-19372
**Checklist**

feat(DeploymentStatusIndicator): replace loader with spinner

---

npm-shrinkwrap.json
package.json

Bumping `@dcos/mesos-client` to bump `@dcos/recordio` to 0.1.5 to make uglifyjs happy and unblock plugins repository.

🚨 Bump @dcos/mesos-client 0.1.6

---

src/js/pages/catalog/PackagesTab.js

This is a minor UX improvement whenever we navigate to catalog we have to click on the search field before start typing.
I was tired of having to click on the search field.
**Checklist**

feat(PackagesTab): add field autofocus

---

src/js/pages/system/OverviewDetailTab.js

`@dcos/mesos-client#request` had a breaking change so that all requests have to be parsed.

🚨 fix(OverviewDetailTab): parse JSON

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/PlacementSection.js
plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js

Just moving the section from under `More Settings` to the separate tab and wrapping the component with the `<Mount />` so that we could override the partial.
Before:
After:
Closes DCOS-18992

DCOS-18992: Extract placement tab

---

packages/foundation-ui/src/mount/Mount.js
packages/foundation-ui/src/mount/__tests__/Mount-test.js

This allows us to pass an array of children to the Mountservice.
`Mount.render` wraps multiple elements in a div by itself, so it
is able to receive multiple children.
This commit changes the `PropTypes.children` definition to reflect
this.
node vs element because a node is everything which react can render (also strings, numbers and so on)

refactor(Mount): allow array of children for mount service

---

package.json

Change the testing script to bind `webpack-dev-server` to all host so that one can start the "testing" server using the docker environment.

fix(package.json): adjust testing script

---

src/js/components/SchemaField.js
src/styles/components/framework-configuration/styles.less
tests/_fixtures/cosmos/package-describe.json

This renders an `AceEditor` when "application/x-yaml" is encountered in the JSON schema media type. We assume the YAML is base64 encoded.
**Testing**:
1. Checkout this branch
2. Turn on fixtures
3. Navigate to catalog, and click "Review and Run" on any package, then click "Edit Config" and scroll down to the YAML in the form.
**After doing the above three steps you will see this:**
**If an invalid base64 encoded string is pasted into the JSON editor:**
**But since we don't do YAML validation, there are many base64 encoded strings that are not valid YAML, but will still render:**
**If the field is required, it will show the required field error just like other form inputs:**
**Checklist**

feat(SchemaField): render yaml ace editor

---

src/js/components/BatchContainer.js
src/js/components/PlacementConstraintsFrameworkAdapter.js
src/js/components/SchemaField.js
tests/_fixtures/cosmos/package-describe.json

✅   Depends on #2516 
1. Implement `BatchContainer` - a wrapper that takes care of the Batch even cycle
2. Implement an adapter for the `PlacementConstraintPartial`
3. Use the Adapter in the json-schema form 
Would be awesome to have a demo-universe to test this. @orlandohohmeier do you know how to put one together? We need a placement constraints with the media type `placement` and the json
Edit @nlight
This is what I did:
```
+---------------------------------------------------+          
|Adapter                    Batch               <------- String
|                              |                    |          
|  +---------------------------|----------------+   |          
|  |BatchForm                  |                |   |          
|  |                           ↓  Data | …
```

DCOS-19559: Adapt placement constraints widget to the SDK form

---

plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js
plugins/services/src/js/service-configuration/ServicePlacementConstraintsConfigSection.js
src/js/components/PlacementConstraintsPartial.js
tests/pages/services/ServiceFormModal-cy.js

This commit swaps the `operator` and `fieldname`
fields for better usability.
Closes DCOS-19481

DCOS-19481 | fix(placement): swap placement form fields

---

plugins/services/src/js/reducers/serviceForm/FormReducers/Constraints.js
src/js/components/PlacementConstraintsPartial.js

This introduces the possibility to give constraints a type as a optional field which will be used to
prevent jumping to custom fields which will be added later.
To test this basically play around with the Placement section nothing should behave differently.
Closes DCOS-19657

DCOS-19657: add advanced type to constraints input

---

src/styles/components/framework-configuration/styles.less

This resets the YAML gutter to `z-index: 0`, preventing it from rendering on top of the JSON editor when screen narrow and JSON is expanded.
Repro to find the bug:
1. Checkout latest master
2. Turn fixtures on
3. Open the catalog deploy framework form
3. Narrow the window and open JSON so it takes up fullscreen
4. The unpleasant bug is below:
Thanks for @nLight for finding this issue. My bad for not testing this case on the original PR. 
**Checklist**

fix(SchemaField): fix z-index issue with YAML editor

---

npm-shrinkwrap.json
package.json

To remove the 30 seconds timeout so the browser will control timeouts. 
The rxjs timeout has a flaw that it doesn't take into account slow connections and would just close the connection

Bump @dcos/mesos-client 0.1.8

---

npm-shrinkwrap.json
package.json
plugins/services/src/js/components/__tests__/ServiceList-test.js
plugins/services/src/js/components/__tests__/__snapshots__/ServiceList-test.js.snap

More about [snapshots](https://facebook.github.io/jest/docs/en/snapshot-testing.html#content)
Replace "manual" component test to use snapshot instead.
**Before example**:
`expect(componetBlaInstance.props.className).toEqual("someClass")`
**Now**:
You match the expected render result.
**Checklist**

test(ServiceList-test): add jest snapshot

---

src/js/components/FrameworkConfiguration.js
src/js/pages/catalog/PackageDetailTab.js
src/js/structs/UniversePackage.js
src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js
src/styles/components/framework-configuration/styles.less

It is a legal requirement to show the terms and conditions notice on the same page as the action that deploys the service. This change does this by moving the T&C link to the new framework review screen. This will only show when deploying from catalog, not when editing the framework. This change also removes the T&C link from the package detail page.
**Most frameworks have preinstall notes, so we append the T&C to the end:**
**If it doesn't have preinstall notes, we just show the T&C (faked example, couldn't find a service without preinstall notes):**
**The T&C link is now removed from package detail:**
Closes DCOS-19359.
**Checklist**

fix(FrameworkConfiguration): move legal t&c text when installing

---

src/js/components/FrameworkConfigurationForm.js
src/js/components/PlacementConstraintsSchemaField.js
src/js/components/SchemaField.js
src/js/components/YamlEditorSchemaField.js
tests/_fixtures/cosmos/package-describe.json
tests/pages/catalog/packages/package/PackageTab-cy.js

To enable plugins and cleaner extensibility I've refactored the way we add custom media-type specific fields like YamlEditor and PlacementConstraints.
Closes DCOS-19669

DCOS-19669: Add Mount for custom media type fields to FrameworkConfigurationForm

---

plugins/services/src/js/components/ServiceStatusProgressBar.js
plugins/services/src/js/components/__tests__/ServiceStatusProgressBar-test.js

Fix progress bar where it shows fully complete when still deploying.
This commit also improve the logic to always display the tooltip and use less code
for the progress bar.
Closes DCOS-19731
**Scaling/deploying already running service**
**Deploying**
**Deleting**
**Checklist**

fix(ServiceStatusProgressBar): fix progress bar

---

plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/reducers/serviceForm/FormReducers/HealthChecks.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/HealthChecks-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/HealthChecks.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/HealthChecks-test.js
src/styles/components/form-elements/form-control-toggle/styles.less

This introduces IPv6 form support to healthchecks.
To test this you have to set up a http healthcheck on a service with a docker image, so container type needs to be DOCKER. 
**Checklist**

DCOS-19354: add IPv6 healthcheck support

---

plugins/services/src/js/components/HighOrderServiceConfiguration.js
plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationReviewScreen.js
tests/pages/services/ServiceDetail-cy.js
tests/pages/services/ServiceVersions-cy.js

**Description:**
1) Use the `/cosmos/service/describe` data to render the configuration tab on service detail when the service is Framework.
2) Also, change the configuration tab for non-framework services: adding a "Download config" button and "Edit config" button (to make it visually the same as frameworks config tab).
3) Use the new configuration tab partial to render the review screen for framework forms
**Implementation**:
We extract the review screen and edit / download buttons into their own partial called `FrameworkConfigurationReviewScreen`. The component is the area within the red ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) box below.
**1) New config tab for framework:**
**2) Changes to config tab for non-frameworks:**
**3) Review screen for frameworks form now also …

feat(HighOrderServiceConfiguration): Config tab using cosmos for frameworks

---

src/js/components/PlacementConstraintsSchemaField.js

SDK uses handlebars engine to generate JSON definition, and handlebars would escape quotes in partial JSONs so that we cant just parse JSON, we should unescape it first. But since SDK expects it to be escaped we should escape the output back again.
The fastest way to do this was regexp.

fix(PlacementConstraintsSchemaField): escape/unescape output

---

plugins/services/src/js/reducers/serviceForm/FormReducers/Constraints.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Constraints-test.js
plugins/services/src/js/reducers/serviceForm/common/Constraints.js
plugins/services/src/js/reducers/serviceForm/common/__tests__/Constraints-test.js

Fix constraint when changing/editing unique.
**Closes DCOS-19573**
**How to test**:
Create a pod with the config below
Edit the pod and go to `Placement` tab
Then try changing the `operator` in the constraint section
```
{
"id": "/pod",
{
"resources": {
"cpus": 0.1,
"mem": 32,
"disk": 0
},
"image": {
"id": "nginx"
}
}
],
"networks": [
{
"mode": "host"
}
],
"scaling": {
},
"placement": {
"constraints": [
{
"fieldName": "hostname",
"operator": "UNIQUE"
}
]
}
},
"cpus": 0.1,
"mem": 32,
"disk": 10
},
"volumes": [],
"fetch": []
}
```
**Checklist**

fix(Constraints): fix unique constraints operator change

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js

To test:
start confluent-kafka
kill confluent-kafka
start a new one (with the same name)
observe that you see it's tasks
without the fix you wouldn't see `kafka_broker` because MesosStateStore would pick tasks for the killed instance.

DCOS-19832: Filter active frameworks only

---

plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/reducers/serviceForm/FormReducers/HealthChecks.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/HealthChecks-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/HealthChecks.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/HealthChecks-test.js

This fixes the earlier introduced feature for IPv6 Support. The problem was that the field is
setting a string but is providing a boolean. By parsing the JSON we made it possible to have the
value true and IPv6 as valid values for the checkbox to be ticked.
Now it should be impossible to set `true` in JSON and have checkbox to be checked.
How to test: PLEASE give it a hard time. Check the checkbox, set path from JSON, go back and forth from editing JSON to editing form multiple times. Verify that there's no side effects

fix(HealthChecks): use bool as internal representation

---

plugins/services/src/js/components/ServiceList.js
plugins/services/src/js/components/ServiceStatusIcon.js
plugins/services/src/js/components/__tests__/__snapshots__/ServiceList-test.js.snap
plugins/services/src/js/containers/services/ServicesTable.js

Keep the UI consistent by adding tooltip to serviceStatusIcon displaying # of services running
Closes DCOS-19747
The icons in service table (status column) should display tooltips
Same goes for service breadcrumb and panel section in dashboard page
**Checklist**

refactor(ServiceStatusIcon): add tooltip to serviceStatusIcon

---

src/js/stores/MesosStateStore.js
src/js/stores/MesosStream/parsers/__tests__/agents-test.js
src/js/stores/MesosStream/parsers/__tests__/frameworks-test.js
src/js/stores/MesosStream/parsers/agents.js
src/js/stores/MesosStream/parsers/frameworks.js
src/js/stores/__tests__/MesosStateStore-test.js

This PR fixes various bugs in the MesosStream. 
1. Fix FRAMEWORK_REMOVED message format
2. Fix AGENT_REMOVED message format
3. Checking only active frameworks when filtering
Testing :trollface: 
1. Easy: Install `beta-confluent-kafka`, wait until it's fully up and running, then delete it. Install  `beta-confluent-kafka` again. UI should show all the tasks etc _without_ reloading the browser.
2. Hard: You gotta remove an agent to see what happens. I may even have an idea how to do that. Sometimes our precious colleagues from the customer  support team know those tricks better.
3. Nightmare: I don't really know how to test this one. Since we're using this function only when we're fetching tasks that's been launched by Marathon and in theory we can't have killed root Marathon on the cluster …

DCOS-19828: Fix mesos stream parsers 😅

---

src/js/components/SchemaField.js
src/js/pages/catalog/DeployFrameworkConfiguration.js

This is a sort of complicated situation, let me explain:
Marathon has a schema entry like this (notice there's **no** default value and the field is **not** required):
```
group: {
regex: <must-be-two-alphanumeric-characters>,
description: "service group"
}
```
Currently, when fetching this package configuration we were setting `""` as the form value for `group` because no default value was provided by the schema. This caused an error in the framework form like this:
Which makes sense, because `""` does not validate against the regex. It was a bad idea to set `""` as the fallback value when no default is provided and the field is not required.
**What this PR does:**
This PR removes the `""` as the empty state for optional fields. Instead, we will set the field as `undefined`. This affects …

fix(SchemaField): avoid framework regex errors

---

plugins/services/src/js/utils/TaskUtil.js
plugins/services/src/js/utils/__tests__/TaskUtil-test.js
src/js/structs/Node.js
tests/pages/services/TasksTable-cy.js

Fix duplicate local string [(Local) (Local)] if region/ zone doesn't exist in region/ zone task columns.
If no zone/ region exists show "N/A"
Closes DCOS-19869
To test:
- create an open cluster
- create a service with a task
- go to tasks page and see "N/A" in the region/ zone column
**Checklist**

DCOS-19883: fix duplicate local string in region/ zone column

---

Dockerfile
system-tests/_scripts/launch-cluster.sh

Turned out we have to  use `cent-os-7-dcos-prereqs` image that has all the good stuff and the `dcos-launch` link was outdated
Ask for credentials, then:
```
$ docker-compose build
$ docker-compose up -d
$ docker-compose exec toolchain system-tests/_scripts/launch-cluster.sh
```
It should create a cluster, don't forget to tear it down with:
```
$ docker-compose exec toolchain system-tests/_scripts/delete-cluster.sh
```
And shut down the toolchain
```
$ docker-compose down
```

DCOS-19658: Adjust system tests cluster config

---

Jenkinsfile

Introduce Jenkinsfile to use Jenkins Pipelines and track and test different build/test configurations.
The current configuration will provision an agent using the `Dockerfile` and then lint, build and test the UI.
Closes DCOS-12802

DCOS-12802: Introduce Jenkinsfile

---

plugins/services/src/js/structs/PodContainer.js
plugins/services/src/js/structs/PodInstance.js
plugins/services/src/js/structs/__tests__/PodContainer-test.js
plugins/services/src/js/structs/__tests__/PodInstance-test.js

Adjust the `PodContainer.hasHealthChecks` condition to properly flag containers even if there are only health checks for one endpoint.
Closes DCOS-19720

fix(PodContainer): adjust hasHealthChecks condition

---

plugins/services/src/js/components/modals/EditServiceModal.js
tests/pages/services/ServiceActions-cy.js

`$ git revert e5d7402913d0cb7f2aa05a2332f67811b1397209`. The service update API is migrated, so we can reenable this feature. Related PR in private-plugins: https://github.com/mesosphere/dcos-ui-plugins-private/pull/702
Hold merge until this is merged: https://github.com/dcos/dcos/pull/2194
**Test:** 
- use this open cluster: http://ahoskins-elasticl-1dccl5gxjpkxp-1189911906.us-west-2.elb.amazonaws.com/
- make sure you can edit and update a running framework
Closes DCOS-19824
**Checklist**

feat(EditServiceModal): re-enable framework editing

---

plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
plugins/services/src/js/pages/EditFrameworkConfiguration.js
src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationForm.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/js/pages/catalog/DeployFrameworkConfiguration.js

Frameworks that are deployed prior to version 1.10 of DC/OS won't have configuration information saved from `cosmos/service/describe`. This PR handles this in the UI by displaying a warning, and populating the edit flow with default package configuration.
In doing this change, I also refactor this flow a bit by adding some methods to `ServiceUtil` and cleaning up passing props.
**Testing**:
1. Toggle enterprise = true in config.dev.json
2. Since we don't have access to old running services, and I don't want to change the fixture to be this case, manually paste this code into **line 44 of src/js/pages/EditFrameworkConfiguration**:
```
fullPackage.resolvedOptions = null;
```
4. Click the edit on any running framework
5. The form will show the default framework configuration values, and show …

feat(EditFrameworkConfiguration): handle empty resolvedOptions

---

plugins/nodes/src/js/components/NodesGridView.js
plugins/nodes/src/js/components/NodesTable.js
plugins/nodes/src/js/components/dsl/NodesHealthDSLSection.js
plugins/nodes/src/js/filters/NodesHealthFilter.js
plugins/nodes/src/js/pages/NodesOverview.js
plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js
plugins/nodes/src/js/pages/nodes/nodes-grid/NodesGridContainer.js
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js
tests/pages/networking/Networks-cy.js
tests/pages/nodes/NodesPage-cy.js

This adds the DSL filter functionality from the service page to the nodes page. 
Yes Design wise it is not looking the best right now. But I am going to implement the Service filter as well and as  soon as this one is removed I would like to expand the bar over the whole line.
Closes DCOS-19114 DCOS-19108 DCOS-19109 DCOS-19111
**Checklist**

DCOS-19114 DCOS-19108 DCOS-19109 DCOS-19111: add filter nodes by health

---

plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/constants/VolumeConstants.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/MultiContainerResidency.js
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js
plugins/services/src/js/service-configuration/PodStorageConfigSection.js

This introduces the support for persistent volumes in multi container services. 
For testing create a volume and select Persistent type add a name and a size.
In the JSON mode you should see something similar to this:
```JSON
...
"volumes": [
{
"size": 1
},
"name": "home"
}
]
...
```
Closes DCOS-19579

DCOS-19579: add persistent volumes to multicontainer services

---

Jenkinsfile

Some of our jobs take rather long to complete which esp. in combination with retires leads to false negatives. This PR increase the timeout to reduce the number of false negatives due to timeouts. I thought about removing the timeout but decided that we should always investigate what happened if a pipeline runs for longer than 3 hours and thus kept the timeout. The timeout also saves us form rouge builds that run for ever, an issue other teams ran into.

fix(Jenkinsfile): adjust timeout

---

plugins/services/src/js/constants/OperatorTypes.js
src/js/components/PlacementConstraintsPartial.js
src/styles/components/form-elements/form-components/select/styles.less
src/styles/components/form-elements/form-components/select/variables.less
src/styles/index.less
tests/pages/catalog/packages/package/PackageTab-cy.js
tests/pages/services/ServiceFormModal-cy.js

---
~⚠️ Depends on https://github.com/dcos/dcos-ui/pull/2577.~ merged 👍 
---
~⚠️ Since #2531 has copied tests which are affeced by this change, this PR is on hold until #2531 is merged.~ #2531 is merged
---
~I have started to implement the new `<Select>`, unfortunately I wasn't able to find the needed CSS code, maybe someone else can pair up with me tomorrow (or fix it, if it is done in 5min)~ 
~Currently the button is grey (as in `reactjs-components`), but it has to be white and fixed in width~
Button looks as expected now and the dropdown is implemented. If someone knows how to do the css part in a better way - please tell me :) 
--- 
To test this / help with:
1. checkout this branch
2. `npm start`
3. disable placement plugin
4. navigate to services -> create -> placement -> add …

DCOS-18993: implement new select placement

---

system-tests/_scripts/launch-cluster.sh

Add missing `exhibitor_storage_backend` config as the generate config command will otherwise fail.

fix(launch-cluster): add missing exhibitor_storage_backend config

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js

This makes sure that the right external fields are getting set after a JSON has been parsed.
To test create a service with a local volume (persistent, dss, host) and then edit something in the
JSON editor or edit a application with a local volume and try to change that volume to a external
volume. The JSON should now consist of the provider information.

fix(volumes): fix any volume to external conversion

---

gulpfile.js
npm-shrinkwrap.json
package.json
src/js/utils/MesosStateUtil.js

---
✅  This PR depends on changes that are going to be introduced with #2593. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/orlandohohmeier/fix/adjust-mesos-request-stubs...drozhkov/mesos-client-0.1.9 
---
We thought we've resolved the issue, but that time bundle distribution messed up thus the old version persisted in the `dist` folder. With this bump I reassured that the updates went through.
Closes DCOS-19946

Bump @dcos/mesos-client 0.1.9

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/UnknownVolumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js

This fixes the JSON parser for volumes to ignore volumes of type unknown.
To test use this JSON
```
{
"id": "/",
"portDefinitions": [],
"container": {
"volumes": [
{
"hostPath": "s",
"mode": "RW"
},
{
"mode": "RW"
}
]
},
"cpus": 0.1,
"mem": 128,
"networks": [],
"fetch": [],
}
```
If you edit the JSON and then the form and then the JSON again, only one volume should exist in the form.

fix(volumes): fix parser to ignore unknown volumes

---

system-tests/_scripts/launch-cluster.sh

---
⚠️  _This PR includea changes that will be introduced with #2594._ 
---
Adjust the python call to output the "public_ip" to use `sys.stdout` instead of print to make the call compatible with both python2 as well as python3

refactor(launch-cluster): adjust scrip to improve compatibility

---

package.json

The package eslint-config-dcos is not on npm. So we can't use plain version.
It went undetected because `npm install` relies on npm-shrinkwrap.json
Introduced https://github.com/dcos/dcos-ui/commit/d7e679f3df5a69621d71d9baac5f92d50e4b45e8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L88

fix(package.json): use github dep for eslint-config-dcos

---

src/js/components/form/FormGroupContainer.js

A previous consistency change on 44c47001291c15da5ce21b68f00da3d65a60ce6c added an invalid `family` value to the icons on all FormGroupContainers. 
This reverts it, as shown in the examples below. All icons "X" to close should be appearing on forms now.
I believe there is a refactor on the Icon component properties needed, out of the scope of this PR, that is proposed here: https://jira.mesosphere.com/browse/DCOS-20134
Volumes Form:
Health Check Form:
Questions:
@weblancaster - Shouldn't we have a test for that already? @juliangieseke mentioned that you said something about deactivating a test about this topic. I personally believe that it is important to assure that the deletion function is always present, and hence this needs a test.

DCOS-20070 - restores the close X on all form groups

---

plugins/services/src/js/components/modals/DisabledGroupDestroyModal.js
plugins/services/src/js/components/modals/KillPodInstanceModal.js
plugins/services/src/js/components/modals/KillTaskModal.js
plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/components/modals/ServiceGroupFormModal.js
plugins/services/src/js/components/modals/ServiceRestartModal.js
plugins/services/src/js/components/modals/ServiceResumeModal.js
plugins/services/src/js/components/modals/ServiceScaleFormModal.js
plugins/services/src/js/components/modals/ServiceStopModal.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-connection/ServiceNoEndpointsPanel.js
src/js/components/FormModal.js
src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/js/components/Modals.js
src/js/components/RepositoriesTable.js
src/js/components/modals/ActionsModal.js
src/js/components/modals/AddRepositoryFormModal.js
src/js/components/modals/CliInstallModal.js
src/js/components/modals/JobFormModal.js
src/js/components/modals/ModalHeading.js
src/styles/components/modal/styles.less
src/styles/views/services/styles.less
system-tests/universe/test-universe.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

The goal of this PR is to align all modal designs with our UI Kit. In particular:
* Size of modals
* Layout (header, body, footer)
* Heading alignment and size
* Button alignment
* Wording used for headings and actions
This **does not address**:
* Adding a close icon button to each modal (separate feature request)
* Modals that could be full screen (e.g. Jobs)
* Modals that could have tabs instead of sidebars (e.g. LDAP directory)
* Form components or validation within the modals
In order to make this sweeping change, there are updates required in this repo, the private enterprise plugin repo and the reactjs-components repo.

DCOS_OSS 1783 Update modals to match UI Kit

---

plugins/services/src/js/constants/OperatorTypes.js

The current description for the IS operator is a copy and paste from the CLUSTER one. Because of that, based on [Marathon Documentation](https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md) we are providing an adequate description.

DCOS_OSS-2017 - fixes the description of the IS operator

---

src/js/pages/network/VirtualNetworksTable.js
src/js/stores/VirtualNetworksStore.js
src/js/structs/Overlay.js
tests/_fixtures/networking/virtual-networks.json

this adds the functionality to display ipv6 subnets in
the networks overview table
networks now are able to have IPv4 and/or IPV6 subnets, so we need to display both. 
To test this you can turn on fixtures, I've added an IPv6 subnet to one of them.

DCOS_OSS-2011: Add IPv6 to the networks table

---

npm-shrinkwrap.json
package.json

The problem with the `mesos-client` has been resolved. Quick explanation: we're keeping all the messages as strings in Rxjs replay subject, we are getting those strings by slicing one big string which represents the stream. The way V8 optimizes sliced strings got in the way here: V8 just keeps the reference with the original string which in our situation means we kept copying that one gigantic string every time we'd get a message -> huge memory consumption.

DCOS-20156: Fix MesosStream memory leak

---

src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js
src/js/stores/MesosStateStore.js
src/js/utils/MesosStateUtil.js
src/js/utils/__tests__/MesosStateUtil-test.js

This fixes the old `MesosStateUtil.getTasksFromVirtualNetworkName` to only return running tasks, also renames it to `getRunningTasksFromVirtualNetworkName`.
To test this:
1. create a service with network and multiple instances (>=2)
2. wait for deplyment and scale down
3. go to http://localhost:4200/#/networking/networks/dcos
it should only show the currently running tasks (scaled down number), not all.

DCOS-20095: Fix Network Task Table to only show running tasks.

---

src/js/stores/MetronomeStore.js
system-tests/jobs/test-jobs.js

When setting the new jobs, remove the previously deleted jobs from the
`jobMap`.
**Now:**
**Before this change:**
**Testing**:
1. Checkout this branch
2. Create a job
3. Delete the job
4. It will now delete from the jobs table without needing a page reload
Closes DCOS-20118
**Checklist**

fix(MetronomeStore): cleanup deleted jobs

---

src/js/utils/MesosStateUtil.js
src/js/utils/__tests__/MesosStateUtil-test.js

Fixes [DCOS-20051](https://jira.mesosphere.com/browse/DCOS-20051) by ignoring completed tasks when asking for the Host resources grouped by Framework.
**Need help**
- There are two uses of `getHostResourcesByFramework`. IMHO with this function name, it should never return results including resources that are completed (TASK_FINISHED, TASK_FAILED), but I am not sure that the second usage at [MesosStateStore](https://github.com/dcos/dcos-ui/blob/8d619d24b32e06d8b5e734fb31d5aed1142436cf/src/js/stores/MesosStateStore.js#L90) relies on that behavior. No unit tests failed because of that anyway.

DCOS-20051: fixes the infinite increase of CPU usage

---

plugins/services/src/js/components/VolumeTable.js
plugins/services/src/js/constants/VolumeProfile.js
plugins/services/src/js/structs/Volume.js
plugins/services/src/js/structs/__tests__/Volume-test.js
tests/pages/services/VolumesTable-cy.js

The goal is to change the overview table as mentioned in the parent issue.
I am a bit unsure about the design differences, so I changed no CSS so far to not introduce any inconsistencies, please give me feedback if this is okay. 
Also it would be great to get some feedback on the commit messages 😇 
P.S.: There is one test missing about the profile being set, but that is impossible with mesos not being able to schedule these resources. I think it might make sense to add it later

DCOS-19585: Volumes Table Single Container Overview

---

src/styles/content/tables/styles.less

@ashenden Could you take a look? This was the result of the restyling you did for the tables and I am unsure if this is the way it should look now or if the color should be the error color.
**Checklist**

DCOS-20202: failed / error label not showing (white on white)

---

plugins/services/src/js/utils/TaskUtil.js
plugins/services/src/js/utils/__tests__/TaskUtil-test.js

[Fixes DCOS-20244](https://jira.mesosphere.com/browse/DCOS-20244)
**Checklist**

DCOS-20244: Don't show (Local) on zones

---

plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/constants/VolumeConstants.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js

Implements the new select dropdown containing title and description.
Closes DCOS-19581
- Create a new pod
- Go to Volumes, observe the dropdown has changed to a new design (screenshot below)
**PS** whenever it's ready to merge and squash the commits
Please use below as a reference
```
feat(MultiContainerVolumesFor): pod volume new select dropdown
Implements the new select dropdown containing title and description.
Closes DCOS-19581
```
**Checklist**

feat(MultiContainerVolumesFor): pod volume new select dropdown

---

npm-shrinkwrap.json
package.json

This puts the port introduced in https://github.com/dcos/dcos-ui/pull/2631 to the `1.10` release.
**Checklist**

DCOS-20158: Backport marked fix to 1.10

---

npm-shrinkwrap.json
package.json

This puts the port introduced in https://github.com/dcos/dcos-ui/pull/2631 to the `1.9` release.
**Checklist**

DCOS-20158: Backport marked fix to 1.9

---

npm-shrinkwrap.json
package.json

This puts the port introduced in https://github.com/dcos/dcos-ui/pull/2631 to the `1.8` release.
**Checklist**

DCOS-20158: Backport marked fix to 1.8

---

plugins/nodes/src/js/components/NodesTable.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js

JIRA: https://jira.mesosphere.com/browse/DCOS-20252
Not sure if this is the best way to archive this, so please tell me if there is a better way 🤔 
---
I sneaked in a little refactoring of `NodeTables` because I had to touch it anyway 👍 
---
After addressing the comments, this PRs scope increased a little bit. 
On this branch it should display `(Local)` for regions (but not zones) on all of these pages **after reloading on the page** (to clear old state):
- /nodes
- /nodes/<NODE_ID>/tasks
- /nodes/<NODE_ID>/tasks/<TASK_ID>/details [*]
- /nodes/<NODE_ID>/details
[*] this one is broken - go to logs and then back to details, @Fabs already created a ticket for this issue

DCOS-20252: Add (Local) suffix to NodesTable (& Details Tab)

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js

There were cases when working on the same cluster from two machines
where there could be an invalid state in `lastMesosState`. This PR
aims to harden our functions against calls to null/undefined.
Unfortunately I could not reproduce the problems described in [DCOS-20306](https://jira.mesosphere.com/browse/DCOS-20306) on my machine, so I went out to "just" write test for every invalid state there might have been.
**Checklist**

DCOS-20306: invalid state of MesosStateStore causes error

---

plugins/nodes/src/js/components/NodesTable.js
src/styles/components/nodes-table/styles.less
src/styles/components/nodes-table/variables.less
src/styles/content/tables/styles.less
src/styles/index.less
tests/pages/nodes/node/HealthTab-cy.js
tests/pages/nodes/node/NodeDetail-cy.js
tests/pages/services/VolumesTable-cy.js

This fixes the sizing issue in the nodes table. Now the text is rightly abbreviated if the column is to small.

DCOS-20253: Fix Nodes Table Spacing
