dcos/dcos-ui

plugins/services/src/js/components/ServiceList.js
src/js/components/ComponentList.js
src/styles/views/dashboard/styles.less

DCOS-12612: Vertically align dashboard panels

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js

Make sure to sort versions in service configuration

---

plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js

DCOS-12969: Fix container value's vertical alignment

---

plugins/services/src/js/service-configuration/PodContainerConfigSection.js

the data is on container level not on the app level.

Display Pod container image and forcePull param

---

src/styles/components/modal/full-screen/styles.less
src/styles/components/modal/full-screen/variables.less

This PR updates the padding of the full screen modal to match the page content's.

DCOS-12453: Update padding of full scren modal's content

---

src/js/components/modals/JobFormModal.js

DCOS-12842: Fix jobs' JSON view overflow

---

scripts/pre-install

---
~~⚠️  Depends on the fix in https://github.com/dcos/dcos-ui/pull/1687~~ Merged
ℹ️ also fixes: DCOS-13218
---
Upgrade Marathon RAML to 1.4.0-RC4, this version includes some RAML fixes and should improve the form validation.
Closes DCOS-12766

Upgrade Marathon to 1.4.0-RC4

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/pages/task-details/TaskLogsTab.js

~~Logs 1 of 2 PR: https://github.com/dcos/dcos-ui/pull/1736~~ Merged
Logs 2 of 2 PR: https://github.com/dcos/dcos-ui/pull/1745
Also fixes: DCOS-12752
Before:
After:
This task also fixes the problem when losing focus while tailing the log (here it works with the given test case):

[Logs 2 of 2] DCOS-12710: Logs eats up a lot cpu

---

plugins/services/src/js/constants/HealtCheckProtocols.js
plugins/services/src/js/constants/MesosCommandTypes.js
plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/MultiContainerHealthChecks.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerHealthChecks-test.js

This PR fixes the multi-container health-check parsers & reducers

DCOS-12774: [1/2] Fix multi-container health-check parsers & reducers

---

plugins/services/src/js/pages/task-details/TaskDetailsTab.js

This PR moves the resource allocation into the Configuration section.
~~I'm adding `hold merge` because Configuration doesn't seem like the best place for this, so I'm waiting for clarification from @ashenden.~~ This has been blessed!

DCOS-12740: Move task resources to Configuration section

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
src/styles/components/menu-tabbed/styles.less
src/styles/components/menu-tabbed/variables.less
src/styles/views/create-service-modal/styles.less

~~~This PR includes changes from #1753~~ (merged)
Before:
After:

DCOS-13018: Form navigation separator fills modal body

---

.gitignore
jest/setupTestFramework.js

Backport the JUnit reporter fixes as our test otherwise fail due to missing reports.

Backport JUnit reporter fixes

---

plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

---
ℹ️ My hunch is that the problem was introduced here: https://github.com/dcos/dcos-ui/pull/1762
---
This PR fixes some broken tests on master revolving around forcePullIImage

Fixing broken forcePullImage tests in Container-test

---

plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/service-configuration/PodHealthChecksConfigSection.js

---
~~:warning: Depends on https://github.com/dcos/dcos-ui/pull/1725~~
---
This PR introduces the new `MultiContainerHealthChecksFormSection`

DCOS-12774: [2/2] Fix multi-container health-check form

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js

I also reordered the sections to follow design:

DCOS-12398: General errors should show up in all sections

---

foundation-ui/stores/DCOSStore.js
foundation-ui/stores/__tests__/DCOSStore-test.js
plugins/nodes/src/js/pages/nodes/NodeDetailTaskTab.js
plugins/services/src/js/components/MesosLogView.js
plugins/services/src/js/components/ServiceForm.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/volume-detail/ServiceVolumeContainer.js
plugins/services/src/js/containers/volume-detail/TaskVolumeContainer.js
plugins/services/src/js/pages/__tests__/DeploymentsTab-test.js
plugins/services/src/js/pages/services/DeploymentsTab.js
plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/stores/MarathonStore.js
plugins/services/src/js/utils/ResourceValidatorUtil.js
plugins/tracking/actions/Actions.js
src/js/pages/DashboardPage.js
src/js/pages/__tests__/JobsTab-test.js
src/js/pages/jobs/JobRunHistoryTable.js
src/js/pages/jobs/JobsTab.js
src/js/stores/MesosStateStore.js
src/js/stores/MesosSummaryStore.js
src/js/stores/MetronomeStore.js
src/js/stores/VirtualNetworksStore.js
src/js/structs/Job.js

---
⚠️  _This branch depends on changes that will be introduced with #1811._
---
Adjust conditions and assignments to remove all obviously unnecessary boolean casts.

Remove unnecessary boolean casts

---

src/styles/components/deployments-table/styles.less

Align location and start-time in deployments table

---

src/js/pages/jobs/JobRunHistoryTable.js

This pull request adds a run time column to the jobs run history table.

DCOS-8509: Add Run Time column to Jobs run history table

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
src/styles/components/icons/styles.less
src/styles/components/page-header/styles.less
src/styles/components/page-header/variables.less

This PR adds the service icon to the breadcrumb. ~~Let's `hold merge` until the design team has had a chance to review.~~ Ready to go!
Ping @ashenden @leemunroe

DCOS-11269: Add service icon to breadcrumb

---

plugins/services/src/js/utils/CreateServiceModalFormUtil.js
plugins/services/src/js/utils/__tests__/CreateServiceModalFormUtil-test.js

This PR rewrites part of the `CreateServiceModalFormUtil.applyPatch` function in order to cover all possible patch cases. This fixes various issues.

DCOS-13033: Fixing CreateServiceModalFormUtil.applyPatch function

---

plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js

This PR updates the volumes sections to follow the docs with tooltips and help text
Before:
After:

DCOS-12398 Aligning volumes section with docs

---

plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/PodContainerServiceFormSection.js
src/js/components/form/FieldLabel.js

This PR aligns the two container sections according to the docs specification.
Container Section 1 of 2: https://github.com/dcos/dcos-ui/pull/1770
Container Section 2 of 2: https://github.com/dcos/dcos-ui/pull/1771

[Container Section 1 of 2] DCOS-12398: Align container section with doc specification

---

src/js/components/ServiceDetailConfigurationTab.js

---
~~⚠️  _This branch will fail until #1798 is merged._~~
---
Change the apply service configuration handler to clean the JSON before sending it back to Marathon to avoid validation errors.
Fixes DCOS-13243

DCOS-13243: Adjust the apply configuration operation

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js

Make sure to reset activeTab on service picker selection

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js

DCOS-12747: Wrap service configuration version dropdown in tooltip

---

src/styles/views/create-service-modal/styles.less

Adjust the JSON only *form* Ace Editor styling, to fix the Safari rendering.
Closes DCOS-13459

DCOS-13459: Fix Ace Editor styling

---

src/js/pages/jobs/JobRunHistoryTable.js
src/styles/components/jobs-view/styles.less

This PR improves the responsiveness of the `JobRunRunHistoryTable`. This comes from a comment in this PR, which recently merged: https://github.com/dcos/dcos-ui/pull/1766#issuecomment-274155375

Assign column classses & better responsiveness in JobRunHistoryTable

---

README.md

Let's re-add them once we've modularized everything

Remove obsolete links from README

---

src/js/pages/network/VirtualNetworksTable.js
src/js/pages/network/virtual-network-detail/VirtualNetworkDetailsTab.js

Fixes DCOS-12436 and DCOS-12438
EDIT: The `Types` have been moved from here^

DCOS-12436: Adding missing content to networking pages

---

plugins/services/src/js/reducers/serviceForm/PortMappings.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortMappings-test.js

This PR fixes parser for protocol in `portMappings`

DCOS-13458: Properly parse protocol in portMappings

---

plugins/services/src/js/components/modals/CreateServiceJsonOnly.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/components/modals/NewCreateServiceModalServicePicker.js
src/styles/components/modal/full-screen/styles.less
src/styles/layout/container/styles.less
src/styles/layout/container/variables.less

This PR introduces `.container-wide` class and implements it in the CreateService modal.

DCOS-13055: Introduce .container-wide and apply in CreateService modal

---

plugins/services/src/js/components/modals/NewCreateServiceModal.js
src/js/components/ToggleButton.js
src/styles/components/toggle-button/styles.less

This PR updates the toggle button label's alignment, moving it from the right
of the button to the left.
This is implemented as an optional mode as it's still right-aligned in the jobs
modal.
Additionally the button label colour animates grey->black on activation.

Change alignment of services toggle button text

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js

Before to the left; after to the right:

Reorder menu in service create modal

---

src/styles/views/create-service-modal/styles.less

DCOS-13349: Let the form grow freely

---

src/js/components/JSONEditor.js

This PR fixes a tiny bug that slipped through the #1837 review.

DCOS-13526: Properly calling updateLocalJsonState on JSONEditor constructor

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
src/js/components/ClipboardTrigger.js

DCOS-13348: Increase Environment form section column widths

---

plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js

This PR adds placeholders for Health checks in both single and multi container form.

DCOS-12399: Add meaningful placeholder values

---

plugins/services/src/js/utils/CreateServiceModalFormUtil.js
plugins/services/src/js/utils/__tests__/CreateServiceModalFormUtil-test.js

This PR updates `applyPatch` function to handle `NaN` as empty values.

DCOS-13709: Handling `NaN` values in `applyPatch`

---

plugins/services/src/js/pages/task-details/TaskDetailsTab.js

[DCOS-12416] Use ConfigurationMap in TaskDetailsTab

---

plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
plugins/services/src/js/containers/service-detail/__tests__/ServiceDetail-test.js

[DCOS-12416] Use ConfigurationMap in ServiceDebugContainer

---

plugins/services/src/js/constants/ServiceSpecConstants.js
plugins/services/src/js/utils/MarathonUtil.js
plugins/services/src/js/utils/__tests__/MarathonUtil-test.js
src/js/utils/CleanJSONUtil.js
tests/_fixtures/marathon-1-task-with-volumes/groups.json
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/VolumesTable-cy.js

Include volumes in the service spec blacklist as the respective "state" data is generated by the MarathonUtil and shouldn't be part of a service spec. 
**Checklist**

DCOS-13773: Improve service spec blacklist

---

plugins/services/src/js/components/MarathonTaskDetailsList.js

[DCOS-12416] Use ConfigurationMap in MarathonTaskDetailsList

---

plugins/services/src/js/containers/pod-debug/PodDebugContainer.js

[DCOS-12416] Use ConfigurationMap in PodDebugContainer

---

plugins/services/src/js/containers/volume-detail/VolumeDetail.js

[DCOS-12416] Use ConfigurationMap in VolumeDetail

---

src/js/pages/jobs/JobConfiguration.js

[DCOS-12416] Use ConfigurationMap in JobConfiguration

---

plugins/services/src/js/components/ServiceList.js

Update copy in empty dashboard services health panel

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModal.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
plugins/services/src/js/constants/DefaultApp.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
tests/pages/services/ServiceFormModal-cy.js

This PR replaces #1869 since it's base branch got completely out of sync with master.
**Checklist**

DCOS-13451: Simplify the runtime configuration

---

src/js/pages/universe/PackagesTab.js
tests/pages/services/ServiceFormModal-cy.js

This PR fixes the broken ServiceFormModal integration test.

Fix broken ServiceFormModal test

---

src/js/components/modals/ServiceFormModal.js

🚨  **1.8 fix** 🚨 
This PR fixes the way ServiceFormModal detects that VIPs are invalid, so that we disable the form and allow JSON only, os that the Form won't rewrite VIPs.
**Checklist**

DCOS-10426: Disable the Form for custom VIPs

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/components/MesosLogView.js
plugins/services/src/js/pages/task-details/TaskLogsTab.js
src/js/events/SystemLogActions.js
src/js/stores/SystemLogStore.js
src/js/utils/Util.js
src/js/utils/__tests__/Util-test.js

Bug fix: Logs unsubscribing on file load

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js

A property was missing to be added to the `ServiceConfigDisplay`. This PR amends that.
Warning from console:
```
Warning: Failed propType: Required prop `onEditClick` was not specified in `ServiceConfigDisplay`. Check the render method of `ServiceConfiguration`.
warning @ warning.js?8a56:45
checkPropTypes @ ReactElementValidator.js?a599:189
validatePropTypes @ ReactElementValidator.js?a599:208
createElement @ ReactElementValidator.js?a599:242
render @ ServiceConfiguration.js?dc74:283
(anonymous) @ makeAssimilatePrototype.js?c7d8:15
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js?cd59:587
_renderValidatedComponent @ ReactCompositeComponent.js?cd59:607
ReactCompositeComponent__renderValidatedComponent @ ReactPerf.js?ef93:66
_updateRenderedComponent @ …
```

Adding missing property

---

plugins/services/src/js/utils/CreateServiceModalFormUtil.js
plugins/services/src/js/utils/__tests__/CreateServiceModalFormUtil-test.js

This PR ensures that `null` patch value is properly handled in `applyPatch`.
**Checklist**

DCOS-14281: Handle `null` patch values in applyPatch

---

src/js/pages/system/RepositoriesTab.js

This PR renames the the Repositories page to "Package Repositories".
**Checklist**

DCOS-11789: Renaming repositories tab

---

mergebot-config.json

`-it` is no longer required for the `test` and `integrate`. DCOS-11489
**Checklist**

Update mergebot commands.

---

plugins/services/src/js/service-configuration/PodGeneralConfigSection.js

This commit removes a duplication in the resource calcuation
**Checklist**

DCOS-14280: Fix pod general config section resource calculation

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/components/MesosLogView.js
plugins/services/src/js/components/__tests__/MesosLogView-test.js

---
~~⚠️ Depends on this PR: https://github.com/dcos/dcos-ui/pull/1954~~ (merged)
---
This PR fixes the 'Go To Bottom' button not hiding when at the bottom.
Please set this in your config dev:
```js
mesos: {
'logging-strategy': 'logrotate'
},
```
**Checklist**
For reviewers: View diff between PRs [here](https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-14010-add-container-to-pick-logging-component-and-api...mlunoe/bug-fix/DCOS_OSS-714-is-at-bottom-button-not-hiding-at-the-bottom?expand=1)

DCOS_OSS-714: Go To Bottom-button not hiding at the bottom

---

plugins/services/src/js/components/forms/ArtifactsSection.js
plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
src/styles/components/form-elements/form-section/styles.less
src/styles/components/form-elements/form-section/variables.less
src/styles/index.less
tests/_fixtures/marathon-1-task/groups.json
tests/pages/services/ServiceFormModal-cy.js

The `More settings` section went missing during the simplification efforts. I extracted `Artifacts` as a component and added it back. 
**Checklist**

DCOS_OSS-722: Display Artifacts section in the Multi-container form

---

plugins/services/src/js/components/EmptyLogScreen.js
plugins/services/src/js/components/LogView.js
plugins/services/src/js/components/MesosLogView.js
plugins/services/src/js/components/__tests__/MesosLogView-test.js

I couldn't help refactoring a little. I find it's better to have explicit components when we are expecting them as a test result.
This PR addresses hopefully all the something of undefined issues caused by not having a container ref before we use it.
And one more thing: for me go down button will stay on the empty screen so I moved it under the condition as well.
Feel free to drop/rebase -i commits
:bow:
**Checklist**

DCOS_OOS-718: Fix scrollTop of undefined when resizing logs container

---

plugins/services/src/js/components/LogView.js
plugins/services/src/js/components/MesosLogContainer.js
plugins/services/src/js/components/MesosLogView.js
plugins/services/src/js/components/__tests__/LogView-test.js
plugins/services/src/js/components/__tests__/MesosLogContainer-test.js
plugins/services/src/js/components/__tests__/MesosLogView-test.js
plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/TaskSystemLogsContainer.js
plugins/services/src/js/pages/task-details/__tests__/TaskFileViewer-test.js
plugins/services/src/js/stores/MesosLogStore.js
plugins/services/src/js/stores/__tests__/MesosLogStore-test.js

---
~~⚠️ Depends on this PR: https://github.com/dcos/dcos-ui/pull/1954~~ (merged)
---
This PR fixes issues in the MesosLogContainer (former MesosLogView).
- The view would not behave properly and call the right functions when it needed to: I changed the MesosLogStore to go about logs the same way as SystemLogStore does it, and made it also use `LogView` (which has been tested) instead of having its own broken implementation.
- Fixed the search for the logs, which was not working properly before.
Please set this in your config dev:
```js
mesos: {
'logging-strategy': 'logrotate'
},
```
**Checklist**
For reviewers: View diff between PRs [here](https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-14010-add-container-to-pick-logging-component-and-api...mlunoe/feature/DCOS-14010-fix-mesos …

DCOS-14010: Fix MesosLogView -> MesosLogContainer

---

plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/TaskLogsContainer.js
plugins/services/src/js/pages/task-details/TaskSystemLogsContainer.js

This PR addresses [this comment](https://github.com/dcos/dcos-ui/pull/1954#discussion_r104952619). PR #1954 merged a bit early and I didn't have enough time to submit this requested change, so here it is.
cc/ @orlandohohmeier @MatApple 
**Checklist**

Fixes anti-pattern in code

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js

~1 of 2: #1886~
2 of 2: #1887
Here are some screenshots of extremely narrow viewports, showing how it's meant to work:

[2 of 2: Fix form label wrapping] Implement FormGroupHeading components

---

system-tests/Systemtests
system-tests/_scripts/setup.sh
system-tests/_support/index.js
system-tests/_support/utils/ServicesUtil.js
system-tests/_support/utils/StringUtil.js
system-tests/cypress.json
system-tests/services/_scripts/setup
system-tests/services/_scripts/teardown
system-tests/services/test-environment.js
system-tests/services/tests.yml

This PR is the first of many for the System Integration Tests for the DC/OS UI. In detail:
* The `system-tests` folder contain the system integration tests scripts. We are using Cypress for the SI tests.
* The `system-tests/Systemtests` script is the entry point to the integration tests. It's an executable script that echoes a YAML document that [describes the tests](https://github.com/mesosphere/dcos-system-test-driver#configuring-components)
* Detailed test configuration is provided by the `*/tests.yml` file fragment.
* Every test described in the `Systemtests` script will be executed in parallel. Use more than one `--spec` in Cypress if you want to run multiple tests in series.
For demonstration purposes, I have also included a very basic test:
* `services/test-environment.js` - Ensure …

DCOS-12803 [System Tests]: Integration with dcos-system-test-driver

---

package.json

This PR adds command/script in package.json to make easier to watch for tests without the need to figure out any information or change any file.
**relates to** #2003 
**Checklist**

[2 of 2] Add command to watch tests in package.json

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This PR fixes the UCR copy so that it is more accurate.

DCOS-14707: Update UCR copy

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This PR removes the `Preview` label from the UCR option.
**Checklist**

DCOS-14743: Remove  label from the UCR option

---

.gitattributes
CONTRIBUTING.md

Add commit guidelines documenting the commit process and providing a framework for writing commit messages that are easy to comprehend.
/cc @dcos/frontend

Introduce commit guidelines

---

src/styles/components/page-header/navigation/styles.less
src/styles/components/page-header/navigation/variables.less
src/styles/components/page-header/styles.less
src/styles/components/page-header/variables.less
src/styles/index.less

~~1 of 3: #1850~~
2 of 3: #1872
3 of 3: #1873
This PR simply separates the styles for the page header navigation from the rest of the page header styles, as it was getting a little unruly.

[2 of 3: Mobile Page Header Navigation] Separate page header navigation styles

---

plugins/services/src/js/reducers/JSONAppReducers.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/IpAddress.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/IpAddress-test.js

**Checklist**
In the process create tests for the ipAddress
reducer
close DCOS-14695

DCOS-14695: Move IpAddress reducer

---

cypress.json
tests/components/Sidebar-cy.js

This PR introduces more thorough integration tests for the Sidebar component.
**Checklist**

DCOS-14456: Write more thorough tests for sidebar

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/reducers/JSONAppReducers.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Labels.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Labels-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Labels.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Labels-test.js

**Checklist**
Split up the labels reducer. As the JSON part should be together but the Form Reducer should stand alone as it is the logic for the form and not for JSON output.
close DCOS-14696

DCOS-14696: Move Labels reducer

---

plugins/services/src/js/reducers/JSONAppReducers.js
plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Constraints.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Constraints-test.js
plugins/services/src/js/reducers/serviceForm/General.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Constraints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Constraints-test.js

DCOS-14688: split up constraints

---

system-tests/_support/constants.js
system-tests/jobs/_scripts/teardown
system-tests/jobs/test-jobs.js
system-tests/jobs/tests.yml
system-tests/services/test-apps.js
system-tests/services/test-pods.js
system-tests/services/tests.yml

This PR adds all the tests that I had in my stash (some of them might be duplicates) I just wanted to commit everything just in case you want to do any bookkeeping while I am in the plane. ✈️ 
_Don't get intimidated by the many code lines, the tests are quite easy to read through._
- Jobs: Create a simple job (DCOS-12806)
- Jobs: Create a job with docker config (DCOS-12828)
- Jobs: Create a job with labels (DCOS-12827)
- Jobs: Create a job with schedule (DCOS-12826)
- Apps: Create a simple app (DCOS-12807)
- Apps: Creates an app with artifacts (DCOS-12825)
- Apps: Creates an app with command health check (DCOS-12824)
- Apps: Create an app with docker config (DCOS-12823)
- Apps: Create an app with environment variables (DCOS-12812)
- Apps: Create an app with external volume (DCOS-12821)
- …

[System Tests]: Adding the 12 tests that were in my stash

---

plugins/services/src/js/reducers/JSONSingleContainerReducers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/RequirePorts.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/RequirePorts-test.js

**Checklist**
close DCOS-14729

 DCOS-14729: Move require ports reducer

---

plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/JSONSingleContainerReducers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Residency.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Residency-test.js

**Checklist**
close DCOS-14728

DCOS-14728: Move Residency Reducer

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js

**Checklist**
Remove `FormReducer` as the form uses the specific
typed reducers like external volumes, host volumes
and local volumes.
close DCOS-14727

DCOS-14727: Refactor volumes reducer

---

.gitignore

The directory keeps popping up after I test any system test PR. This should stop.

Ignore system tests results

---

.github/gif-instructions.md
CONTRIBUTING.md
README.md

Added helpful links and a gif so that the community can quickly see what it's like to use the UI.
[See updated readme](https://github.com/dcos/dcos-ui/blob/rafa/update-readme/README.md)

Update README file.

---

plugins/services/src/js/components/DeclinedOffersTable.js
plugins/services/src/js/containers/pod-debug/PodDebugContainer.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js

This PR is meant to clean up the readability of the declined offers copy logic, as requested here: https://github.com/dcos/dcos-ui/pull/1721/files#r95681321
and here: https://github.com/dcos/dcos-ui/pull/1721/files#r95681803
**Checklist**

DCOS-13205: Clean up if-else statements for readability

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
src/styles/components/page-header/navigation/styles.less
src/styles/views/create-service-modal/styles.less

~~1 of 3: #1850~~
~~2 of 3: #1872~~
3 of 3: #1873
This PR implements the mobile page header navigation component in the service form.

[3 of 3: Mobile Page Header Navigation] DCOS-12571: Implement mobile page header navigation in Service Form

---

plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/reducers/serviceForm/Volumes.js

**Checklist**
close DCOS-13419

DCOS-13419: Enable Host volumes in all modes

---

tests/pages/services/ServiceFormModal-cy.js

This PR implements integration tests for Service modal.
**Jira:** DCOS-14460
**Tests:**
- Modal is full screen
- Horizontally/Vertically centered
- Panels contain same size (width/height).
**Checklist**

test(DCOS-14460): Implement integration tests for Service modal.

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/JSONSingleContainerReducers.js
plugins/services/src/js/reducers/serviceForm/FormReducers/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/EnvironmentVariables-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/EnvironmentVariables-test.js

DCOS-14690: Move Environment variables reducer

---

tests/pages/jobs/JobDetails-cy.js

⚠️  ~~Depends on a fix for https://mesosphere.atlassian.net/browse/DCOS-11920~~

Fixing integration tests for JobDetails

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js

Looks like it's been overlooked ¯\_(ツ)_/¯

Delete obsolete shoudValidate argument

---

src/js/components/CheckboxTable.js
src/js/pages/universe/__tests__/PackagesTab-test.js
tests/_fixtures/cosmos/packages-search.json
tests/pages/universe/packages/PackagesTab-cy.js

This PR fixes so the bottom packages in the table are always visible:
**Checklist**

DCOS-11781: fix scroll view not set correctly in packages table

---

plugins/services/src/js/reducers/serviceForm/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/__tests__/EnvironmentVariables-test.js

**Checklist**
Ensure that only complete pairs with key and value
set are allowed in the JSON output.
Close DCOS-14758

DCOS-14758: fix(EnvironmentVariables): Only complete pairs

---

npm-shrinkwrap.json
package.json

In this update:
https://github.com/mesosphere/reactjs-components/pull/398
https://github.com/mesosphere/reactjs-components/pull/400
**Checklist**

chore(reactjs-components): update to v0.15.0-beta.7

---

tests/pages/services/ServiceFormModal-cy.js

Add's full integration test coverage for Service Create Modal (Single Container) and closes https://jira.mesosphere.com/browse/DCOS-14461.
Although ~1000 lines added, they're all integration tests and with their nested contexts, it makes sense to land as a single PR to avoid rebase time and loss of context when reviewing. Please let me know if you disagree.
At some point we should consider splitting this file, perhaps once all Service Create integration tests have been committed to master.
**Checklist**

tests(ServiceCreateModal): Integration tests for Single Container

---

plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

Backport of https://github.com/dcos/dcos-ui/pull/2117 to `release/1.9`
**Checklist**

↩️  DCOS-14894: Aggregate resources for running tasks only

---

src/js/components/CheckboxTable.js
src/js/components/TaskTable.js
src/js/components/__tests__/TaskTable-test.js
src/js/pages/universe/__tests__/PackagesTab-test.js
tests/_fixtures/cosmos/packages-search.json
tests/pages/universe/packages/PackagesTab-cy.js

---
~~⚠️ Depends on this PR: https://github.com/dcos/dcos-ui/pull/2120~~ Merged
---
This PR is the same as this just for the 1.8 release: https://github.com/dcos/dcos-ui/pull/2078
This PR fixes so the bottom packages in the table are always visible:
**Checklist**

↩️  DCOS-11781: fix scroll view not set correctly in packages table

---

plugins/services/src/js/pages/task-details/TaskDetail.js
plugins/services/src/js/pages/task-details/__tests__/TaskDetail-test.js

This PR fixes a bug I stumbled upon while testing this PR: https://github.com/dcos/dcos-ui/pull/2131
Steps to reproduce:
1. Create a task that is failing for some reason
2. Go to task table
3. Find an 'old' (I don't know what the bar is) failed task
4. Click the icon to go straight to the logs
5. You'll see the error emerge
**Checklist**

fix(TaskDetail): handling task not being defined

---

tests/_fixtures/marathon-1-task/state.json
tests/_fixtures/mesos/overlay-master.json
tests/_support/utils/testUtil.js
tests/pages/networking/Networks-cy.js

~~**Relies on the changes in #1996** to correctly compare values in the UI to values from the API response.~~
This PR adds integration tests for the Networks section.
**Checklist**

[2 of 2] Add integration tests for networks

---

system-tests/services/test-pods.js

This PR introduces the automated tests for [Create a simple pod with artifacts](https://wiki.mesosphere.com/pages/viewpage.action?pageId=101253131)
<pre>
</pre>

[System Tests]: DCOS-12814: Add SI tests for pod with artifacts

---

plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js

**Checklist**
Remove volume mounts from container if the remove
volume was the last one.
Closes DCOS-15289

DCOS-15289: fix - Reducers - Remove volume mounts correctly

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

**Checklist**
Add Bridge mode network support for ucr
single container apps.
Closes DCOS-12290

DCOS-12290: (UCR) - Add bridge network support

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

**Checklist**
close DCOS-12861

DCOS-12861: Enable force Pull Image setting in UCR

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/JSONSingleContainerReducers.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Container.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Container-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Container.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Container-test.js

**Checklist**
Remove Volumes from Form Reducer
close DCOS-14524

DCOS-14524: Refactor container reducer

---

src/js/components/JSONEditor.js
src/styles/components/ace-editor/styles.less

**Checklist**
Add the Ace editor searchbox to the JSON Editor. So if you press CMD + F on a mac the searchbar of the ace editor is going to open and you will be able to search in the Editor.
Closes DCOS-14976

DCOS-14976: JSONEditor - Add searchbar

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/containers/services/ServicesTable.js
src/js/plugin-bridge/PluginModules.js

This PR adds a mount point for the service status. It also exposes the ServiceUtil in PluginModules.
**Checklist**

DCOS-15165: feat(Service Status): Add mount component for service status

---

plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
tests/_fixtures/1-app-for-each-health/app.json
tests/_fixtures/1-app-for-each-health/groups.json
tests/_fixtures/1-service-with-executor-task/app.json
tests/_fixtures/1-service-with-executor-task/groups.json
tests/_fixtures/1-service-with-executor-task/state.json
tests/_fixtures/healthy-tasks-in-mesos-and-marathon/groups.json
tests/_fixtures/healthy-tasks-in-mesos-and-marathon/state.json
tests/_fixtures/marathon-1-group/kafka.json

Label is being deprecated.
Closes [DCOS-15283](https://jira.mesosphere.com/browse/DCOS-15283).
**Checklist**

Removes DCOS_PACKAGE_IS_FRAMEWORK label

---

src/js/components/modals/AddRepositoryFormModal.js

fix (AddRepositoryFormModal) Loosens up domain validation.

---

plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/pages/__tests__/DeploymentsTab-test.js
src/js/components/UnitHealthNodesTable.js
src/js/pages/__tests__/JobsTab-test.js

This PR converts all the relative `../src` paths that we've overlooked to `#SRC`

Convert outstanding relative ../src paths to #SRC

---

src/js/components/Page.js
src/js/components/PageHeader.js
src/js/components/PageHeaderActions.js
src/styles/components/page-header/styles.less

~~[1 of 3](https://github.com/dcos/dcos-ui/pull/2150)~~
__2 of 3__
[3 of 3](https://github.com/dcos/dcos-ui/pull/2152)
This PR adds the ability to have supplemental content in PageHeaderActions. This will be used for the new deployments feature.
**Checklist**

[Deployments 2 of 3]: DCOS-15161: Add supplemental content to PageHeaderActions

---

src/js/pages/system/OverviewDetailTab.js
src/js/translations/en-US.json

(**DCOS-15151**)This PR adds Mesos details to overview page.
To test, go to overview page and then you should be able to see Mesos details like so.
**Checklist**

feat(DCOS-15151): Add Mesos details to overview page

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
src/js/translations/en-US.json
src/styles/components/code/styles.less

This PR removes the "copy" text to copy a command and instead adds an icon to do this. This was a request from the Design team. I've gone over it with them and gotten sign-off on the implementation.
**Before**
**After**
**Checklist**

feature (ServiceActionDisabledModal) Moves copy text to icon

---

plugins/services/src/js/routes/services.js

This is a fix for a PR was merged with my refactoring.
This removes the nested services tab in the sidebar.
**Checklist**

fix(refactor): Remove nested services tab due to a regression

---

src/js/components/modals/ActionsModal.js

(**DCOS-14289**) This PR improve the wording for the sections under organizations users/groups/services to make the actions more clear.
**Checklist**

fix(DCOS-14289): Improve organization wording

---

system-tests/services/test-apps.js

Improve the app system tests by adjusting and improving the test cases.
* Add additional checks to verify that the Marathon response is as expected. To do so the test will open the service detail, hit edit and check the form content.
* Introduce new test to check that Marathon throws an error in case an app with an existig ID already exists.
* Adjust create simple app test to bail early in case of an error.

DCOS-15287: Improve app tests

---

system-tests/jobs/test-jobs.js

Add additional checks to verify that the Marathon response is as expected. To do so the test will open the service detail, hit edit and check the form content.

DCOS-15287: Add checks to verify marathon response (jobs)

---

src/js/components/charts/ResourceTimeSeriesChart.js

[1.9] Fix incorrect rounding of resource allocation.

---

src/js/components/charts/ResourceTimeSeriesChart.js

[1.8] Fix incorrect rounding of resource allocation.

---

src/js/components/charts/ResourceTimeSeriesChart.js

Fix incorrect rounding of resource allocation.

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/constants/ContainerConstants.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/Docker.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/service-configuration/ServiceGeneralConfigSection.js
system-tests/services/test-apps.js
tests/pages/services/ServiceFormModal-cy.js

This PR removes the UCR option in the service create form. Check out the discussions in these tickets for more context: https://jira.mesosphere.com/browse/DCOS-14851 and https://jira.mesosphere.com/browse/DCOS-15539
**Checklist**

DCOS-14851: Remove UCR option from service create form

---

system-tests/services/test-apps.js

This adds system integration tests for force pull,
bridge network and host volumes.
Closes DCOS-15397
**Checklist**

DCOS-15397: ucr integration tests

---

src/js/components/modals/InstallPackageModal.js
src/js/utils/BetaOptInUtil.js
src/js/utils/__tests__/BetaOptInUtil-test.js

Backport of https://github.com/dcos/dcos-ui/pull/2201 to 1.9.
**Checklist**

↩️ [1.9] Improve UX for Package Install Beta opt-in

---

plugins/services/src/js/reducers/serviceForm/Containers.js
plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js

Remove image if a container id has been removed
but was available earlier.
Closes DCOS_OSS-1050
**Checklist**

DCOS_OSS-1050: Remove image if no id is provided

---

plugins/oauth/hooks.js
src/js/components/modals/CliInstallModal.js

**DCOS-14334** Well, the title explains a lot.
**before**
**after**
**Checklist**

fix(DCOS-14334): Update CLI setup script

---

packages/foundation-ui/src/routing/RoutingService.js
packages/foundation-ui/src/routing/__tests__/RoutingService-test.js
plugins/design-system/components/ComponentsBreadcrumbs.js
plugins/design-system/pages/ui-components/ComponentPage.js
plugins/design-system/routes/ui-components/buttons.js

This PR adds a component page that can be reused for each UI component in the design system.
**Checklist**

refactor(DCOS-15919): Routing with reusable component page

---

plugins/design-system/pages/DesignSystemPage.js
plugins/design-system/pages/IntroductionPage.js

This PR adds the wrapper design system and introduction pages to the design system.
**Checklist**

feat(DCOS-15919): Design System Introduction and Wrapper Pages

---

tests/pages/services/ServiceFormModal-cy.js

This PR adds system integration tests defined in **DCOS-14465**
**Checklist**

test(DCOS-14465): Add multi container tests

---

plugins/design-system/components/PatternsBreadcrumbs.js
plugins/design-system/pages/patterns/CreateEditPage.js
plugins/design-system/pages/patterns/EmptyStatesPage.js
plugins/design-system/pages/patterns/FormsPage.js
plugins/design-system/pages/patterns/HelpFeedbackPage.js
plugins/design-system/pages/patterns/LoadingPage.js
plugins/design-system/pages/patterns/NotificationsPage.js
plugins/design-system/pages/patterns/ValidationPage.js

This PR adds the pages for the Patterns sidebar category in the design system.
**Checklist**

feat(DCOS-15919): Patterns Design System Pages

---

plugins/design-system/components/StyleBreadcrumbs.js
plugins/design-system/pages/style/ColorPage.js
plugins/design-system/pages/style/IconsPage.js
plugins/design-system/pages/style/LayoutPage.js
plugins/design-system/pages/style/MotionPage.js
plugins/design-system/pages/style/TypographyPage.js
plugins/design-system/pages/style/WritingPage.js

This PR adds the pages for the Style sidebar category in the design system.
**Checklist**

feat(DCOS-15919): Style Design System Pages

---

plugins/design-system/routes/ui-components/badges.js
plugins/design-system/routes/ui-components/banners.js
plugins/design-system/routes/ui-components/breadcrumbs.js
plugins/design-system/routes/ui-components/button-groups.js
plugins/design-system/routes/ui-components/charts.js
plugins/design-system/routes/ui-components/checkboxes.js
plugins/design-system/routes/ui-components/dropdowns.js
plugins/design-system/routes/ui-components/loading-indicators.js
plugins/design-system/routes/ui-components/messages.js
plugins/design-system/routes/ui-components/modals.js
plugins/design-system/routes/ui-components/panels.js
plugins/design-system/routes/ui-components/radio-buttons.js
plugins/design-system/routes/ui-components/segmented-bars.js
plugins/design-system/routes/ui-components/selects.js
plugins/design-system/routes/ui-components/tables.js
plugins/design-system/routes/ui-components/tabs.js
plugins/design-system/routes/ui-components/text-fields.js
plugins/design-system/routes/ui-components/toggles.js
plugins/design-system/routes/ui-components/tooltips.js
plugins/design-system/routes/ui-components/type.js

This PR adds routes for the design system.
**Checklist**

feat(DCOS-15919): Design System Routes

---

plugins/design-system/hooks.js

This PR adds the hooks for the design system.
**Checklist**

feat(DCOS-15919): Design System Hooks

---

src/js/components/modals/InstallPackageModal.js
src/js/pages/catalog/PackageDetailTab.js
src/js/utils/BetaOptInUtil.js
src/js/utils/__tests__/BetaOptInUtil-test.js

Last minute UX cleanup with some hacky bits to solve SDK's beta optin issue.
Test by installing any beta packages from the catalog.
[See video for demo](https://cl.ly/300i1i423l1I/Screen%20Recording%202017-05-22%20at%2009.01%20PM.gif)
**Needs tests on Utils but please review in meantime as it's a blocker**
**Also need to backport to 1.9**
**Checklist**

Improve UX for Package Install Beta opt-in

---

system-tests/universe/_scripts/teardown
system-tests/universe/test-universe.js
system-tests/universe/tests.yml

Adds the following cases:
* Install a certified package using quick-install
* Install a community package using quick-install
* install certified package using advanced install
* Install a community package using advanced install
refs: DCOS-15718
```
--only "universe" \
```
**Checklist**

test (Universe) Adds Universe system tests.

---

system-tests/services/test-pods.js

This PR adds the "Create a pod with labels" system test.
**Checklist**

test(DCOS-12810): Create a pod with labels

---

system-tests/services/test-pods.js

Add additional checks to verify that the Marathon response is as expected. To do so the test will open the service detail, hit edit and check the form content.

DCOS-15287: Add checks to verify marathon response (pods)

---

plugins/nodes/src/js/components/NodesTable.js
src/js/constants/NodesTableHeaderLabels.js

fix (NodesTable) Renames Tasks column

---

npm-shrinkwrap.json
package.json

Changes include:
* Improved form-field styling
* New .messages component
* Paragraph tag inherits from body
**Checklist**

DCOS-15805: Update CNVS to 1.1.9

---

system-tests/services/test-apps.js

This PR adds a system test for creating an app with service address.
To run the test:
```
-e CLUSTER_URL=$openCluster \
mesosphere/dcos-ui dcos-system-test-driver --only "apps"  \
```
**Checklist**

test(DCOS-12816): Create an app with service address

---

Authors.md

This PR updates the `Authors.md` file. I think there was talk of removing this entirely, but if not, then it should be updated :)
I hope I didn't miss anyone...
**Checklist**

chore(Authors.md): Update Authors.md

---

plugins/services/src/js/components/HealthBar.js

This PR clarifies the value in the `HealthBar` tooltip, so that users don't confuse it with instances.
**Checklist**

chore(HealthBar): Explicitly label the task count

---

npm-shrinkwrap.json
package.json
src/js/index.js

Add a Intl (ECMA-402) polyfill to fix application failures due to the missing API.
Closes DCOS-16274

DCOS-16274:  Add Intl polyfill

---

src/styles/components/expanding-table/styles.less

**MARATHON_EE-1538** This PR fixes the issue when no host/port available the "table" space will be blank causing misalignment.
To test create a service with the following json config then go to the service and expand the service:
```
{
"id": "/rpgqa/qa1/champion-mastery-memcached",
"version": "2017-06-07T23:43:24.644Z",
{
"name": "sidecar",
"exec": {
"command": {
"shell": "sleep 10000000000"
}
},
"resources": {
"cpus": 0.1,
"mem": 32,
"disk": 0,
"gpus": 0
},
"image": {
"id": "alpine"
}
},
{
"name": "memcached",
"exec": {
"command": {
"shell": "sleep 1000000000"
}
},
"resources": {
"cpus": 0.1,
"mem": 32,
"disk": 0,
"gpus": 0
},
"endpoints": [
{
"name": "main",
"containerPort": 11211,
"hostPort": 11211,
"protocol": [
"tcp"
]
}
],
"image": {
"kind": …
```

fix(MARATHON_EE-1538): Fix service containers host/port empty space.

---

npm-shrinkwrap.json
package.json
src/js/index.js

---
⚠️  _This PR ports a fix to master introduced with #2262._
---
> Add a Intl (ECMA-402) polyfill to fix application failures due to the missing API.
>
> Closes DCOS-16274

⏩  DCOS-16274:  Add Intl polyfill

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

fix(ServiceForm): Remove Typo from prop list

---

src/styles/content/tables/styles.less

This PR wraps content in table cells.
Before:
https://cl.ly/3Z0V3v260Q31
After:
https://cl.ly/3d2h0h2r3X3n
**Checklist**

fix(DCOS-16363): Content in table cells overflowing

---

system-tests/services/test-apps.js

This PR fixes the apps system tests (prior to this, 11/15 were failing).  This PR is a good pre-requisite to my main sprint tasks of adding a couple new system tests. 
The tests were failing because the JSON structure was changed, and a couple text fields on the UI have been re-labeled. **After this change, all these tests should be passing**. However, these tests are still pretty brittle because they depend on JSON structure, and many string values of labels on the pages. They look suspiciously like integration tests, and we should discuss how to approach system tests moving forward.  
**Checklist**

test: fix broken apps system tests

---

system-tests/services/test-apps.js

This PR adds a system test for creating an app with virtual network.
Run the test:
```
-e CLUSTER_URL=$OPEN_CLUSTER \
mesosphere/dcos-ui dcos-system-test-driver --only "apps" \
```
**Checklist**

test(DCOS-12815): Create an app with virtual network

---

system-tests/universe/test-universe.js

Improve the universe system tests in two ways:
1) assert the installed package appearing in the service list
2) add a test for uninstalling a package
Run with:
```
-e CLUSTER_URL=$OPEN_CLUSTER \
mesosphere/dcos-ui dcos-system-test-driver --only "universe" \
```
**Checklist**

test(DCOS-15057): improve universe system tests

---

src/js/index.js

**DCOS-16493** This PR fixes the issue of using the browser language dynamically.
Change your browser language to see the error. (sometimes will only work if the computer/OS language is changed too)
**Checklist**

fix(DCOS-16493): Hard code navigator language

---

src/js/pages/catalog/PackageDetailTab.js
src/js/pages/catalog/__tests__/PackageDetailTab-test.js
src/styles/views/packages/styles.less
tests/pages/catalog/packages/PackagesTab-cy.js

**DCOS-16435** This PR is only for the disclaimer.
Because the button configuration new design isn't implemented yet the button looks a little off when on small screens.
**before**
**after**
**Checklist**

feat(DCOS-16435): Add package disclaimer

---

plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/containers/tasks/__tests__/TaskTable-test.js
src/js/components/CheckboxTable.js
tests/pages/services/TasksTable-cy.js

This PR fixes **DCOS_OSS-1052** and **DCOS-14556** which reverts #2128 where a couple of bugs were introduced including the one in this PR.
Steps to reproduce:
- Create a service
- Navigate to service tasks
- Check all
- Check specific tasks
- Now inactive state is fixed and user should not see the checkbox
```
{
"id": "/nginx",
"acceptedResourceRoles": [
"*"
],
"backoffFactor": 1.15,
"backoffSeconds": 1,
"cmd": "sleep 200",
"container": {
{
"hostPort": 0,
"servicePort": 10002
},
{
"containerPort": 443,
"hostPort": 0,
"servicePort": 10003
}
],
"docker": {
"image": "bitnami/nginx:1.10.3-r1",
"forcePullImage": false,
"privileged": false
},
"type": "DOCKER"
},
"cpus": 1,
"disk": 0,
"healthChecks": [
{ …
```

fix(DCOS_OSS-1052|DCOS-14556): Fix checkbox task behavior

---

src/js/pages/catalog/PackagesTab.js

Definition of community and certified packages needed to be more clearly communicated to users.
**Requirement**: Change description text on Catalog page for Certified and Community subtitles as follows:
- Certified packages are verified by Mesosphere for interoperability with DC/OS.
- Community packages are unverified and unreviewed content from the community.
**Acceptance**: From a running OSS and Enterprise DC/OS cluster
- Show the Service Catalog
- See the text from the requirements under "Certified" and "Community" sections
**Checklist**

chore(PackagesTab): update copy for package types

---

CONTRIBUTING.md

Fix CONTRIBUTING typos

---

system-tests/services/test-pods.js

I've changed the way we remove empty values from JSON our expectations went broken. This PR fixes that.

System tests: adjust JSON expectations to reality

---

plugins/services/src/js/containers/tasks/ServiceTasksContainer.js
plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/TasksView.js
plugins/services/src/js/containers/tasks/__tests__/TaskTable-test.js
src/js/components/CheckboxTable.js
tests/pages/services/TasksTable-cy.js

This is a backport of #2286 and it also fixes the error when selecting a task on the node tasks page.
closes: **DCOS-17241**
**Checklist**

↩️  fix(CheckboxTable): fix checkbox task behavior

---

system-tests/_support/index.js
system-tests/dashboard/_scripts/setup
system-tests/dashboard/_scripts/teardown
system-tests/dashboard/app.json
system-tests/dashboard/test-dashboard.js
system-tests/dashboard/tests.yml

**Overview:**
System tests for dashboard page [DCOS-15059](https://jira.mesosphere.com/browse/DCOS-15059). The tests check if the following five items update when **adding and deleting** a service:
1) CPU allocation (checks if increases/decreases when service added/removed)
2) Memory allocation (checks if increases/decreases when service added/removed)
3) Disk allocation (checks if increases/decreases when service added/removed)
4) Service name in list (checks if service name appears/disappears in list when service added/removed)
5) Task count chart (checks if number of tasks increments/decrements when service added/removed)
**Testing**:
Everyday I usually create an open cluster named "andrew-(random-id)-open". Feel free to use it for testing.
```
-v …
```

test(Dashboard): add dashboard system tests

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
src/js/translations/en-US.json
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

Change the Update Dialog message to the following
"To Update a framework's configuration, please update "options.json" <make this a link to documentation i the service docs?>.  Run the following CLI commands:"
Before
After
Closes DCOS-16225
**Checklist**

DCOS-16225: change the update cli dialog message.

---

src/js/components/modals/CliInstallModal.js

This commit update/improve the cli install displayed in the UI
Closes DCOS-17389
**Before:**
**After:**
**Checklist**

fix(CliInstallModal): improve cli install displayed in the UI

---

src/js/pages/jobs/JobDetailPage.js

Remove `handleMoreDropdownSelection` as it the method isn't used anymore.

refactor(JobDetailPage): remove unused method

---

src/js/pages/jobs/JobsTable.js
src/styles/components/icons/styles.less

Change the schedule icon `Tooltip` and  `Icon` classes so that no conflicting ( `.icon svg`) are applied.
Closes DCOS-17997

DCOS-17997: adjust jobs table styles

---

plugins/services/src/js/components/modals/CreateServiceModal.js
plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/components/modals/CreateServiceModalServicePicker.js
plugins/services/src/js/routes/services.js

Rename everything NewCreateServiceModal(.*) to CreateServiceModal(.*)

refactor(CreateServiceModal): Rename NewCreateServiceModal

---

plugins/design-system/components/component-example/CodeExample.js
plugins/design-system/components/component-example/CodeExampleFooter.js
plugins/design-system/components/component-example/CodeExampleHeader.js
plugins/design-system/components/component-example/CollapseButton.js
plugins/design-system/components/component-example/ComponentExample.js
plugins/design-system/components/component-example/ExpandButton.js
plugins/design-system/styles/components/component-example/styles.less
plugins/design-system/styles/components/component-example/variables.less

**Design System**
This PR adds the `ComponentExample` component, which is made up of the `CodeExampleHeader` and `CodeExampleFooter` components. It is the primary component for the code example component.
To test:
- See branch `tommy/design-system/component-example-ace-editor` for the complete implementation or merge in #2349
- In the UI: Design System --> Components --> Checkboxes --> Code Tab
- React code is shown on one tab and HTML on the other
- Clipboard function works for both tabs
- Collapse/Expand of code
Options:
Implement ComponentExample component used to display code blocks for design system components. Code can either be in React or HTML. Props can be added to the component to override the generated React and HTML Code. These optional props are: reactCode and htmlCode and …

DCOS-15921 (1 of 2): Add ComponentExample component

---

src/resources/grammar/__tests__/SearchDSL-test.js

style(SearchDSL): prettify test suite

---

plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js

Backporting #2416 
Closes DCOS-18696

↩️ fix(JSONReducers/Containers): delete protocol field on ADD_ITEM

---

plugins/services/src/js/reducers/serviceForm/FormReducers/SingleContainerPortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortDefinitions-test.js

Change the reducers to properly handle missing protocols as they otherwise throw type errors which results in duplicated JSON definitions and a broken editor experience.
Closes DCOS-18788

DCOS-18788: adjust port definition protocol handling

---

packages/connections/LICENSE
packages/connections/README.md
packages/connections/index.js
packages/connections/package.json
packages/connections/src/AbstractConnection.js
packages/connections/src/ConnectionEvent.js
packages/connections/src/XHRConnection.js
packages/connections/src/__mocks__/AbstractConnection.js
packages/connections/src/__mocks__/ConnectionEvent.js
packages/connections/src/__tests__/AbstractConnection-test.js
packages/connections/src/__tests__/ConnectionEvent-test.js
packages/connections/src/__tests__/XHRConnection-test.js

---
ℹ️   _The respective features were originally implemented by @juliangieseke as part of #2361. This PR extracts the connections into their own package to enable different use cases and streamline the further development and review process._
---
Add a package that provides different connection types with a unified interface. For a detailed a list and example on how to use them please see: [README](https://github.com/dcos/dcos-ui/blob/898438d8a6ce629d2743672a77bc31fb81b92f88/packages/connections/README.md)

Introduce connections

---

package.json
packages/connection-manager/LICENSE
packages/connection-manager/README.md
packages/connection-manager/index.js
packages/connection-manager/package-lock.json
packages/connection-manager/package.json
packages/connection-manager/src/ConnectionManager.js
packages/connection-manager/src/ConnectionQueue.js
packages/connection-manager/src/ConnectionQueueItem.js
packages/connection-manager/src/__tests__/ConnectionManager-test.js
packages/connection-manager/src/__tests__/ConnectionQueue-test.js
packages/connection-manager/src/__tests__/ConnectionQueueItem-test.js
packages/connections/LICENSE
packages/connections/README.md
packages/connections/index.js
packages/connections/package.json
packages/connections/src/AbstractConnection.js
packages/connections/src/ConnectionEvent.js
packages/connections/src/XHRConnection.js
packages/connections/src/__mocks__/AbstractConnection.js
packages/connections/src/__mocks__/ConnectionEvent.js
packages/connections/src/__tests__/AbstractConnection-test.js
packages/connections/src/__tests__/ConnectionEvent-test.js
packages/connections/src/__tests__/XHRConnection-test.js

---
ℹ️   _The respective features were originally implemented by @juliangieseke as part of #2361. This PR extracts the connection manager to streamline the review process._
_This branch depends on changes that will be introduced with #2418. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/orlandohohmeier/feat/connections...orlandohohmeier/feat/connection-manager_
---
The connection manager provides methods to manage connections by priority. This is useful as browsers can only open a limited amount of connections (http) and you might find you urgent request at the very end of a long queue without a dedicated manager.

Introduce connection manager

---

npm-shrinkwrap.json
package.json
packages/http-service/LICENSE
packages/http-service/README.md
packages/http-service/index.js
packages/http-service/package.json
packages/http-service/src/__tests__/request-test.js
packages/http-service/src/__tests__/stream-test.js
packages/http-service/src/request.js
packages/http-service/src/stream.js

Former `resource-service` is a helper package that leverages the `connection-manager` and `rxjs` to create a managed observable connection.
Exports two functions: `request` and `stream`
For a simple request like loading a `json` file one wants to get it when it's fully loaded.
So `request` fires only one `next` immediately followed by `complete` after the resource has been fully loaded.
```
XHRConnection DATA events
-o--o--o--o--o--|
request
-------------o--|
```
Fires `next` on every `DATA` event coming from the `XHRConnection`. Every value in next will have `XHRConnection#response` that will be growing, so if you need this data chunk by chunk you should run your own logic on top (as we do in `mesos-client`)
```
XHRConnection DATA events
-o--o--o--o--o--|
stream
-o--o--o--o--o--|
```
✅ …

Introduce http-service

---

plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
src/styles/components/code/styles.less
src/styles/components/service-endpoints/styles.less
src/styles/index.less

---
⚠️  _This branch depends on changes that will be introduced with #2422. For a list of changes please see: https://github.com/dcos/dcos-ui/compare/bill/feat/connection-endpoints/04-endpoint-tab-components...bill/feat/connection-endpoints/05-endpoint-route-styles_ 
---
Adds the routes necessary for the tab to appear in the pods and service details page.
Style changes for the endpoints tab.
**Checklist**

Endpoints Tab | 05 | Style, Routes and Copy Command

---

scripts/pre-push

fix(pre-push): adjust message import path

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
tests/pages/services/ServiceActions-cy.js

Trigger the delete command when you click on enter while in the input area.
**Checklist**

Uninstall 02 | DCOS-18198: Trigger destroy with enter key while in input.

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
tests/pages/services/ServiceActions-cy.js

Trigger the delete command when you click on enter while in the input area.
**Checklist**

DCOS-18198: Trigger destroy with enter key while in input

---

plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
src/js/translations/en-US.json

Remove unnecessary inactive delete modal areas since all of these are handled now in the Uninstall modal.
Related to #2402 
**Checklist**

Uninstall 04 | Remove unnecessary inactive delete modal areas

---

plugins/nodes/src/js/components/NodesTable.js
plugins/services/src/js/components/DeploymentsModal.js
plugins/services/src/js/components/HealthBar.js
plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/__tests__/HealthBar-test.js
src/js/components/BreadcrumbSupplementalContent.js
src/js/components/ProgressBar.js
src/js/components/__tests__/StatusBar-test.js

Rename statusBar to progressBar so it can become general and clear for usage.
Closes DCOS-18265S
**Checklist**

refactor(StatusBar): rename statusBar to progressBar

---

plugins/nodes/src/js/components/NodesTable.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/pages/task-details/TaskDetailsTab.js
plugins/services/src/js/utils/GraphQLTaskUtil.js
src/js/structs/CompositeState.js
src/styles/components/task-table/styles.less

Add Region/ Zones in task details.
**Checklist**

DCOS 19137: Region/ Zones in tasks details

---

plugins/nodes/src/js/components/NodesTable.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/services/src/js/constants/TaskTableHeaderLabels.js
plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/pages/task-details/TaskDetailsTab.js
plugins/services/src/js/utils/GraphQLTaskUtil.js
plugins/services/src/js/utils/TaskUtil.js
plugins/services/src/js/utils/__tests__/TaskUtil-test.js
plugins/services/src/js/utils/__tests__/fixtures/MasterNodeLocal.json
plugins/services/src/js/utils/__tests__/fixtures/MasterNodeOffsite.json
plugins/services/src/js/utils/__tests__/fixtures/NodeTask.json
plugins/services/src/js/utils/__tests__/fixtures/SlaveNodes.json
src/js/structs/CompositeState.js
src/js/structs/Node.js
src/styles/components/task-table/styles.less
tests/pages/services/TasksTable-cy.js

Add zone, region in the task Table and Details Page.
Closes DCOS-18171, DCOS-19136, DCOS-19137, DCOS-19138
**Checklist**

DCOS-18171: Add zone, region in the task Table and Details Page

---

npm-shrinkwrap.json
package.json
src/js/components/CosmosErrorMessage.js
src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationForm.js
src/js/components/HashMapDisplay.js
src/js/components/ReviewConfig.js
src/js/components/SchemaField.js
src/js/components/TabButton.js
src/js/components/form/FieldSelect.js
src/js/components/modals/FullScreenModalHeaderSubTitle.js
src/js/stores/CosmosPackagesStore.js
src/js/utils/RouterUtil.js
src/js/utils/StringUtil.js
src/styles/components/buttons/styles.less
src/styles/components/form-elements/form-components/field-input/styles.less
src/styles/components/form-elements/form-components/field-input/variables.less
src/styles/components/form-elements/form-components/field-select/styles.less
src/styles/components/form-elements/form-components/field-select/variables.less
src/styles/components/framework-configuration/styles.less
src/styles/components/menu-tabbed/styles.less
src/styles/components/modal/full-screen/styles.less
src/styles/index.less

This adds a new JSON schema form for editing frameworks. It uses [this](https://github.com/mozilla-services/react-jsonschema-form) Mozilla library for the JSON schema itself.
**Testing**:
Look at #2443 to test edit framework configuration.
Look at #2444 to test deploy framework configuration.
**Description**
1. `FrameworkConfigurationForm.js`: the tabbed form itself, wrapping the Mozilla schema form library and gluing together with `SchemaField.js`, which injects our custom form components (more info below):
2. `FrameworkConfiguration.js`: general coordinator for the configure framework flow. It is a child of the `EditFrameworkConfiguration.js` and `DeployFrameworkConfiguration.js` in the two PRs linked above.
3. `SchemaField.js`: responsible for rendering each form element. We use our …

feat(FrameworkConfiguration): framework configuration components

---

CODEOWNERS

Remove codeowners file

---

src/js/pages/system/OverviewDetailTab.js

This PR replaces MesosStateStore with direct calls to the V1 API. The API lacks `elapsed_time` and `start_time`, there's a ticket for that in mesos.
Closes DCOS-19145

Cluster Overview page MesosStateStore refactoring

---

npm-shrinkwrap.json
package.json

this commit only adds the `http-service` to `package.json`. nothing fancy (yet 😎)

feat(http-service): introduce http-service package

---

plugins/services/src/js/constants/OperatorTypes.js

This introduces the IS operator to the UI and adds it as a constant.
Form Section:
JSON Section:
Configuration view:
Closes DCOS-19483
```
```
**Checklist**

DCOS-19483: add new IS constraint operator constant

---

src/js/components/Sidebar.js
src/js/components/SidebarHeader.js
src/js/pages/SystemOverviewPage.js
src/js/pages/system/OverviewDetailTab.js
src/js/routes/system-overview.js

**⚠️  dependent on https://github.com/mesosphere/dcos-ui-plugins-private/pull/663**
Add linked clusters page and menu link.
Closes DCOS-19345
**Checklist**

DCOS-19345: add linked clusters page and menu link

---

plugins/services/src/js/components/dsl/ServiceStatusDSLSection.js
plugins/services/src/js/components/modals/ServiceActionDisabledModal.js
plugins/services/src/js/components/modals/ServiceModals.js
plugins/services/src/js/components/modals/ServiceResumeModal.js
plugins/services/src/js/components/modals/ServiceStopModal.js
plugins/services/src/js/constants/PodActionItem.js
plugins/services/src/js/constants/ServiceActionItem.js
plugins/services/src/js/constants/ServiceActionLabels.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/pod-detail/PodHeader.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/__tests__/Pod-test.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js
src/js/translations/en-US.json
system-tests/services/test-external-volumes.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

This commit includes a variety of refactoring where we rename suspend to stop across DCOS UI
Closes DCOS-19528
**Checklist**

refactor(*): rename suspend to stop

---

plugins/services/src/js/pages/task-details/TaskDetail.js
src/js/components/Modals.js
src/js/components/SchemaForm.js

Remove InternalStorageMixin when not used

---

plugins/services/src/js/service-configuration/PodContainerArtifactsConfigSection.js
plugins/services/src/js/service-configuration/PodContainerConfigSection.js
plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js
plugins/services/src/js/service-configuration/PodGeneralConfigSection.js
plugins/services/src/js/service-configuration/PodHealthChecksConfigSection.js
plugins/services/src/js/service-configuration/PodLabelsConfigSection.js
plugins/services/src/js/service-configuration/PodNetworkConfigSection.js
plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js
plugins/services/src/js/service-configuration/PodStorageConfigSection.js
plugins/services/src/js/service-configuration/ServiceConfigBaseSectionDisplay.js
plugins/services/src/js/service-configuration/ServiceEnvironmentVariablesConfigSection.js
plugins/services/src/js/service-configuration/ServiceGeneralConfigSection.js
plugins/services/src/js/service-configuration/ServiceHealthChecksConfigSection.js
plugins/services/src/js/service-configuration/ServiceLabelsConfigSection.js
plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
plugins/services/src/js/service-configuration/ServicePlacementConstraintsConfigSection.js
plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js

This PR adds the mountpoints to the service configuration screen to
allow override of default content
Closes DCOS-19541

refactor(Serviceconf): add mountpoints for config screen

---

plugins/services/src/js/components/forms/PlacementSection.js
src/js/components/PlacementConstraintsPartial.js

Edit @nlight:
This is a pure extraction. We want to reuse this partial in the SDK form on the later stage. Please verify that the Service create form still works as expected.

DCOS-19557: Extract placement constraints form partial

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/ServiceStatusIcon.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
src/styles/components/page-header/breadcrumbs/styles.less
tests/components/PageHeader.js

Re-order breadcrumb and update style based on the re-design in service status column.
Closes DCOS-19103
**before**
**after**
**Checklist**

feat(ServiceBreadcrumbs): re-order breadcrumb

---

npm-shrinkwrap.json
package.json

this commit bumps reactjs-components to version ~0.17.0, also bumps
react-gemini-scrollbar to 2.3.4 because it is updated in
reactjs-components.~ 0.17.1

chore(reactjs-components): bump 0.17.1

---

scripts/pre-install
scripts/utils/marathon

This introduces the latest marathon snapshot

chore(RAMLvalidation): add latest marathon snapshot

---

src/js/components/SchemaField.js

Restrict mount to only one component

---

src/js/components/PlacementConstraintsSchemaField.js

To test, enable fixtures, open a framework config check validation for constraints.
**Checklist**

DCOS-19820: Add basic constraint validation to framework form

---

Jenkinsfile

fix(Jenkinsfile): add 1Gb more memory

---

plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js

Based on #2559 (MERGED)
This PR introduces the externalVolumes logic to the now called volumes reducers.
This is the second of three PR's which will merge external and local volumes

DCOS-19401: refactor(externalVolumes): add external volumes logic to volumes

---

tests/_fixtures/1-service-with-executor-task/history-minute.json
tests/_fixtures/1-service-with-executor-task/stream-subscribed.js
tests/pages/services/TasksTable-cy.js

Integration tests for DSL task filters.
This is dependent on https://github.com/dcos/dcos-ui/pull/2472
**Checklist**

DCOS-19140: DSL Tasks Filters Integration Tests

---

plugins/nodes/src/js/components/NodesTable.js
src/js/components/__tests__/ProgressBar-test.js

The api changed and we forgot to rename.
Closes DCOS-20040
**Checklist**

fix(ProgressBar): fix regression in using progress bar

---

npm-shrinkwrap.json
package.json
tests/pages/jobs/JobActions-cy.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceTable-cy.js

bump reactjs-components to the newest version including Modals and Select fixes
test: check this out and run `npm install` - if it passes, everything is ok 👍

chore(reactjs-components): bump to 0.20.1

---

plugins/nodes/src/js/pages/nodes/NodeDetailTaskTab.js
plugins/services/src/js/components/HighOrderServiceInstances.js
plugins/services/src/js/components/dsl/FuzzyTextDSLSection.js
plugins/services/src/js/components/dsl/TaskRegionDSLSection.js
plugins/services/src/js/components/dsl/TaskStatusDSLSection.js
plugins/services/src/js/components/dsl/TaskZoneDSLSection.js
plugins/services/src/js/containers/service-instances/ServiceInstancesContainer.js
plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/TasksView.js
plugins/services/src/js/filters/TaskNameTextFilter.js
plugins/services/src/js/filters/TasksRegionFilter.js
plugins/services/src/js/filters/TasksStatusFilter.js
plugins/services/src/js/filters/TasksZoneFilter.js
plugins/services/src/js/filters/__tests__/TaskNameTextFilter-test.js
plugins/services/src/js/filters/__tests__/TaskRegionFilter-test.js
plugins/services/src/js/filters/__tests__/TaskStatusFilter-test.js
plugins/services/src/js/filters/__tests__/TaskZoneFilter-test.js
src/js/components/DSLFilterField.js
src/js/components/DSLForm.js
src/js/components/DSLFormDropdownPanel.js
src/styles/views/services/styles.less
tests/_fixtures/1-service-with-executor-task/history-minute.json
tests/_fixtures/1-service-with-executor-task/stream-subscribed.js
tests/pages/services/TasksTable-cy.js

Add dsl filter in tasks table page.
Integration test will be added in another PR.
Filter by:
text, zone, region, state
**Checklist**

DCOS 19139: DSL tasks filter

---

plugins/nodes/src/js/components/dsl/NodesRegionDSLFilter.js
plugins/nodes/src/js/components/dsl/NodesZoneDSLFilter.js
plugins/nodes/src/js/filters/NodesRegionFilter.js
plugins/nodes/src/js/filters/NodesZoneFilter.js
plugins/nodes/src/js/filters/__tests__/NodesRegionFilter-test.js
plugins/nodes/src/js/filters/__tests__/NodesZoneFilter-test.js
plugins/nodes/src/js/pages/NodesOverview.js
plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js

Add region/ zone DSL filter in nodes page.
Depends on: https://github.com/dcos/dcos-ui/pull/2472, https://github.com/dcos/dcos-ui/pull/2471
**Checklist**

DCOS-18860: node region zones DSL filter

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js

To test this create an App with a host volume.
Deploy it or change something in JSON editor.
Then change to a External volume.

fix(volumes): fix change to external volumes

---

TESTING.md

Hi there,
I just noticed that the docs had broken images, possibly through the renaming in the organisation.
I hope I followed the contributing guidelines correctly, if not please let me know 👍 
Happy Holidays ❄️

docs(testing): fix image paths

---

plugins/dss/hooks.js
plugins/services/src/js/components/forms/VolumesFormSection.js

The issue which is fixed with this PR:

fix(volumes): add default value to known values

---

plugins/services/src/js/constants/OperatorTypes.js
src/js/components/PlacementConstraintsPartial.js
tests/pages/catalog/packages/package/PackageTab-cy.js
tests/pages/services/ServiceFormModal-cy.js

Improve advanced constraints with minor UX/design changes and refactor the code to
a new file that way making easier to understand what is going on.
Closes DCOS-19719
**Checklist**

refactor(PlacementConstraintsFields) Improve advanced constraints

---

src/js/components/PlacementConstraintsSchemaField.js

https://jira.mesosphere.com/browse/DCOS-19882

DCOS-19882: fix(PlacementConstraintsSchemaField): remove escaping from output

---

Jenkinsfile

chore(Jenkinsfile): remove unused stage

---

src/js/components/PlacementConstraintsPartial.js

fix(PlacementConstraintsPartial): align file and class name

---

tests/_fixtures/mesos/overlay-master.json
tests/pages/networking/Networks-cy.js

Add mock framework data to fix failing test.

fix(Networks): add mock framework data to fix failing test

---

plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js

This PR fixes Pod Environment variable config section.
1. Create a pod with an env var
2. Click Review and run
3. Without the fix you should get an exception
extracted from #2562

fix(PodEnvironmentVariablesConfigSection): fix props

---

plugins/nodes/src/js/pages/NodesOverview.js
plugins/services/src/js/components/FilterByService.js
plugins/services/src/js/containers/pod-instances/PodViewFilter.js
plugins/services/src/js/containers/tasks/TasksView.js
src/js/components/PrimarySidebarLink.js
src/js/components/modals/ActionsModal.js
src/js/mixins/TabsMixin.js
src/js/pages/catalog/PackageDetailTab.js
src/js/pages/catalog/PackagesTab.js
src/js/pages/system/UnitsHealthTab.js
src/styles/components/badges/styles.less

This is a new PR for an old already merged one, it looks like some rebasing went wrong 🤔 
Old PR: https://github.com/dcos/dcos-ui/pull/2451

DCOS-19033: Update Badges to match UI Kit (2nd try)

---

src/js/components/PageHeader.js
tests/pages/services/ServiceActions-cy.js

This was done to provide users with an alternative Edit button to help then easily perform this common task.
Thanks for the pariring @Poltergeist

DCOS-19292 - adds an extra edit button to Services

---

plugins/dss/hooks.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/constants/VolumeConstants.js
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js

This will add the support for DSS volumes for Pods
---
Add to your Config.dev.js
```
dss: { enabled: true }
```

DCOS-19580: Add DSS volumes to pods.

---

src/styles/components/form-elements/form-row/styles.less

DCOS-20094: space button 

---

plugins/services/src/js/constants/OperatorTypes.js
src/js/components/PlacementConstraintsPartial.js

This PR changes the behavior of the help text like described in [DCOS-20094](https://jira.mesosphere.com/browse/DCOS-20094)
**Checklist**

DCOS-20094: help texts

---

plugins/dss/hooks.js
plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/constants/VolumeDefinitions.js
plugins/services/src/js/constants/VolumeTypes.js
plugins/services/src/js/structs/__tests__/Volume-test.js
plugins/services/src/js/utils/MarathonUtil.js
src/styles/components/form-elements/form-components/select/styles.less
tests/pages/services/ServiceFormModal-cy.js

Implements the new select dropdown containing title and description.
Closes DCOS-19404
- Create a service
- Go to Volumes, observe the dropdown has changed to a new design (screenshot below)
**Checklist**

feat(VolumesFormSection): volume new select dropdown

---

npm-shrinkwrap.json
package.json

There were security fixes added in the last versions of marked see
- https://nvd.nist.gov/vuln/detail/CVE-2017-17461
- https://nvd.nist.gov/vuln/detail/CVE-2017-1000427
This PR should fix them on master, after that I will use this commit to backport the fix to older versions.
**Checklist**

DCOS-20158: update marked package

---

system-tests/_scripts/launch-cluster.sh
system-tests/dashboard/_scripts/setup
system-tests/dashboard/test-dashboard.js
system-tests/services/test-apps.js
system-tests/services/test-external-volumes.js
system-tests/services/test-pods.js
system-tests/universe/test-universe.js
tests/pages/networking/Networks-cy.js

System tests have diverged, let's fix them 💪

DCOS-19658: Adjust system-tests discrepancies

---

plugins/services/src/js/containers/pod-instances/PodInstancesView.js

This PR got degraded to a refactoring only PR, but it's a small one ;)
**Checklist**

Refactor: Pod Instances

---

plugins/services/src/js/components/modals/CreateServiceModal.js
plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/PlacementsValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
plugins/services/src/js/validators/__tests__/PlacementsValidators-test.js
src/js/components/ErrorsAlert.js
src/js/components/JSONEditor.js
src/styles/components/form-elements/form-components/select/styles.less

1) Add placement constraint validator to make sure the operator/ field combo is unique.
2) These errors are "permissive" meaning that you can post the form without them being satisfied. And they are hidden from the ErrorsAlert by default.
Closes DCOS-19648
**Checklist**

DCOS-19648: add placement constraint validator

---

plugins/nodes/src/js/components/NodesGridDials.js
plugins/nodes/src/js/components/__tests__/NodesGridDials-test.js

Testing:
Have at least one (or many) app running with no Disk usage.
Before:
After:
Closes DCOS-20317
**Checklist**

Fix NaN in NodesGridDials percentage calculation

---

plugins/services/src/js/containers/tasks/TasksContainer.js

Add NULL check for tasks container region/zone.
Closes DCOS-20382
**Checklist**

fix(TasksContainer): add null check for tasks container region/zone

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/ServiceList.js
plugins/services/src/js/components/ServiceStatusProgressBar.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/Pod-test.js
plugins/services/src/js/structs/__tests__/Service-test.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js

DCOS-18784: pod instance

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js

While working on PR 2650 I kept seeing the warning so removing it.
**Checklist**

fix(ServiceDestroyModal) remove for in markup

---

Jenkinsfile

this adds a check for PRs not opened by us.
---
This PR is basically the baseline which allows us to enable our Pipeline and to debug it.

fix(Jenkinsfile): adds authorization to jenkinsfile

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Constraints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Constraints-test.js
plugins/services/src/js/reducers/serviceForm/MultiContainerConstraints.js
plugins/services/src/js/reducers/serviceForm/__tests__/MulitContainerConstraints-test.js
plugins/services/src/js/reducers/serviceForm/common/Constraints.js
plugins/services/src/js/reducers/serviceForm/common/__tests__/Constraints-test.js
plugins/services/src/js/validators/PlacementsValidators.js
plugins/services/src/js/validators/__tests__/PlacementsValidators-test.js
src/js/components/PlacementConstraintsSchemaField.js
src/js/components/__tests__/PlacementConstraintsSchemaFields-test.js
src/js/components/__tests__/__snapshots__/PlacementConstraintsSchemaFields-test.js.snap
src/js/constants/TransactionTypes.js

This is an alternative approach to solve the form problem with placement constraints being on an invalid format. It was inspired by the way it is handled in volumes and health check.
The current code of two branches combined achieves that:
Solution idea:
To make the parsers add an ERROR type transaction to the batch, that could be validated down on the line only by the component who needs it. Combined to handling incorrect complicate JSON the same way volumes and health check does. It is achieved in 4 steps.
1. Enhance TransactionTypes with ERROR type (on dcos-ui-plugins-private)
2. Enhance the parser to add those ERROR transactions to the batch when needed
3. Create a validator that detects the presence of ERROR transactions in the batch
4. Use that validator on the responsible component …

DCOS-20465 - OSS Placement constraints format

---

plugins/nodes/src/js/components/dsl/NodesHealthDSLSection.js
plugins/nodes/src/js/components/dsl/NodesRegionDSLFilter.js
plugins/nodes/src/js/components/dsl/NodesZoneDSLFilter.js
plugins/services/src/js/components/dsl/TaskRegionDSLSection.js
plugins/services/src/js/components/dsl/TaskStatusDSLSection.js
plugins/services/src/js/components/dsl/TaskZoneDSLSection.js
plugins/services/src/js/components/forms/PlacementSection.js
plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/js/components/PlacementConstraintsSchemaField.js
src/js/components/YamlEditorSchemaField.js

chore(prop-types): migrate leftover files

---

.eslintrc
npm-shrinkwrap.json
package.json
plugins/services/src/js/structs/__tests__/Volume-test.js
plugins/services/src/js/validators/__tests__/PlacementsValidators-test.js
system-tests/jobs/test-jobs.js
system-tests/services/test-apps.js
system-tests/services/test-environment.js
system-tests/services/test-pods.js
tests/pages/catalog/packages/PackagesTab-cy.js
tests/pages/nodes/NodesPage-cy.js
tests/pages/services/DeploymentsModal-cy.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceDetail-cy.js
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/ServiceTable-cy.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js
tests/plugins/tracking/TrackingPlugin-cy.js
tests/smoke-cy.js
webpack/plugins/svg-compiler-plugin.js

@orlandohohmeier did a PR to move the notation in tests away from `should`.
I wrote a small eslint plugin/rule to make sure we don't introduce these again 👍 
**Checklist**

Add eslint rule for should in tests

---

src/styles/vendor/cnvs/components/button-collection/variables.less
src/styles/vendor/cnvs/styles.less

Very minor style tweak to support changes needed for the oAuth UI.
Review and merge this related PR: https://github.com/mesosphere/dcos-ui-plugins-private/pull/722

Update button-collection component spacing

---

CONTRIBUTING.md

Add the newest version of cypress to the documentation

docs(CONTRIBUTING): fixes cypress version

---

CONTRIBUTING.md

Change logical mistake in contribute doc.
**Checklist**

fix(Contributing.md): fix logical mistake in contribute doc

---

Jenkinsfile

This PR enables the System Tests for our Jenkinsfile 👍

Enable system tests (Jenkinsfile/Node 4)

---

webpack/webpack.config.babel.js

chore(webpack): adds #TESTS alias for ./tests

---

src/js/components/DSLFilterField.js
src/js/components/DSLInputField.js

DCOS-20332: DSL show dropdown on focus

---

src/js/utils/JobUtil.js
src/js/utils/__tests__/JobUtil-test.js

fix(JobUtil): need to preserve schedule id and concurrency policy

---

src/js/components/DSLFormDropdownPanel.js

Update DSL filter results in real time.
**Checklist**

DCOS-20331: Update DSL filter results in real time

---

src/js/components/modals/CliInstallModal.js

[backport 1.11] DCOS-20978: Fix CLI install link

---

plugins/services/src/js/reducers/serviceForm/FormReducers/Networks.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Networks.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Networks-test.js

Keep unknown networks attributes

---

plugins/services/src/js/containers/tasks/TasksContainer.js

This commit adds a default value for task DSL filters
**To Test this please contact me**
Closes DCOS-21063

fix(taskDSLFilters): set default value for dsl Filters

---

src/js/components/modals/CliInstallModal.js

Test this by opening the install cli modal and switching to windows
**Checklist**

DCOS-20976: fix(CliInstall): renames terminal to command prompt

---

src/js/structs/UniversePackage.js
src/js/structs/__tests__/UniversePackage-test.js

backport of #2719 
**Checklist**

[backport 1.11] fix(UniversePackage): fallback to type: "object" for config

---

scripts/find-broken-links

Quick fix for find broken links script
Testing: regex101.com/r/KwvvN5/1
**Checklist**

Fix: Find broken links

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js
src/js/utils/MesosStateUtil.js
src/js/utils/__tests__/MesosStateUtil-test.js

Backport of #2727 
Closes DCOS-21044

fix(MesosStateStore): flag all SDK tasks

---

src/js/pages/system/OverviewDetailTab.js
tests/_fixtures/v1/get_flags.json
tests/_fixtures/v1/get_master.json
tests/_fixtures/v1/get_version.json
tests/_support/index.js
tests/pages/system/overview/ClusterDetails.js

⚠️ Backport me to 1.11
Closes DCOS-21135

DCOS-21135: display mesos start and elected time 

---

plugins/services/src/js/pages/EditFrameworkConfiguration.js
src/js/components/FrameworkConfiguration.js
system-tests/universe/test-universe.js
tests/pages/catalog/packages/package/PackageTab-cy.js

backport of #2698
**Checklist**

[backport 1.11] feat(FrameworkConfiguration): open to form when deploying

---

README.md

Add docker development flow to docs

---

plugins/services/src/js/reducers/serviceForm/FormReducers/Networks.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Networks.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Networks-test.js

1.10 Backport of #2714 
Closes DCOS-20948

DCOS-20948: keep unknown network attributes

---

plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/utils/TaskTableUtil.js
tests/_fixtures/marathon-1-task/mesos-subscribe.js
tests/_fixtures/marathon-1-task/summary.json
tests/_fixtures/marathon-pods/groups.json
tests/pages/nodes/NodesPage-cy.js
tests/pages/services/TasksTable-cy.js

Closes DCOS-21229
Backport: https://github.com/dcos/dcos-ui/pull/2737
**Checklist**

Master: DCOS-21229: fix(TaskTable): fix sorting in tables

---

src/js/components/modals/CliInstallModal.js

Backport of this PR: https://github.com/dcos/dcos-ui/pull/2711
**Checklist**

Backport: DCOS-20976

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
tests/_fixtures/marathon-1-pod-group/groups.json
tests/_fixtures/marathon-1-pod-group/summary.json
tests/_support/index.js
tests/pages/services/PodDetail-cy.js

This PR aims to write integration tests for sorting pod instances and add the functionality which seems to be missing
**Checklist**

DCOS-21229: Sorting in pods table

---

Dockerfile

I hope this will fix the fails on the jenkinsfiles
**Checklist**

Fix system tests for jenkinsfile

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
tests/_fixtures/marathon-1-pod-group/groups.json
tests/_fixtures/marathon-1-pod-group/summary.json
tests/_support/index.js
tests/pages/services/PodDetail-cy.js

Backport 1.11: DCOS-21229: Sort pods with zones & regions

---

plugins/services/src/js/service-configuration/PodStorageConfigSection.js
tests/pages/services/ServicePodReviewScreen-cy.js

This commit fixes a variable reference which lead to have multiple lines in the volume mount table
with the same values.
Before:
After:
To test:
```JSON
{
"id": "/host-volume",
"volumes": [
{
"name": "etc",
"host": "/etc"
}
],
"scaling": {
"kind": "fixed",
"instances": 1
},
"upgrade": {
"minimumHealthCapacity": 0,
"maximumOverCapacity": 0
}
},
{
"name": "container1",
"exec": {
"command": {
"shell": "sleep 5000"
}
},
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0,
"gpus": 0
},
"image": {
"id": "alpine",
"forcePull": false
},
{
"name": "etc",
"mountPath": "/mnt/etc1",
"readOnly": true
}
],
"lifecycle": {
"killGracePeriodSeconds": 60
}
},
{
"name": "container2",
"exec": {
"command": {
"shell": "sleep 5000"
}
}, …
```

[Backport 1.11] fix(PodStorageConfigSection): fix variable reference

---

plugins/services/src/js/service-configuration/PodStorageConfigSection.js
tests/pages/services/ServicePodReviewScreen-cy.js

This commit fixes a variable reference which lead to have multiple lines in the volume mount table
with the same values.
Before:
After:
To test:
```JSON
{
"id": "/host-volume",
"volumes": [
{
"name": "etc",
"host": "/etc"
}
],
"scaling": {
"kind": "fixed",
"instances": 1
},
"upgrade": {
"minimumHealthCapacity": 0,
"maximumOverCapacity": 0
}
},
{
"name": "container1",
"exec": {
"command": {
"shell": "sleep 5000"
}
},
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0,
"gpus": 0
},
"image": {
"id": "alpine",
"forcePull": false
},
{
"name": "etc",
"mountPath": "/mnt/etc1",
"readOnly": true
}
],
"lifecycle": {
"killGracePeriodSeconds": 60
}
},
{
"name": "container2",
"exec": {
"command": {
"shell": "sleep 5000"
}
}, …
```

fix(PodStorageConfigSection): fix variable reference

---

plugins/services/src/js/components/ServiceStatusProgressBar.js
plugins/services/src/js/components/__tests__/ServiceStatusProgressBar-test.js

DCOS_OSS-2063: show progress of deployments

---

CONTRIBUTING.md

Just wanted to add a paragraph about the wepack aliases, seems like I also trimmed the whitespaces 🙈

docs(CONTRIBUTING): add note for webpack aliases in vscode

---

scripts/ci/run-integration-tests

fix(run-integration-tests): set path for xml

---

plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/__tests__/TaskFileViewer-test.js
src/js/utils/RouterUtil.js
src/js/utils/__tests__/RouterUtil-test.js

I originally wanted to write integration tests, but this part was pretty hard to fixture away, so I wrote unit tests instead.
1. Refactor to have the function testable
2. Write tests reflecting current state of function
3. Fix the functionality
**Checklist**

DCOS-21266: Files UI breaks after navigating through the switch button

---

plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js
src/js/structs/Node.js
src/js/structs/__tests__/Node-test.js
src/js/utils/ResourcesUtil.js

Fix issue when trying to convert undefined or null to object.
Closes DCOS-21367
**Checklist**

fix(ResourcesUtil): fix undefined or null object

---

npm-shrinkwrap.json
package.json

Backports https://github.com/dcos/dcos-ui/pull/2793.

[1.11] update package to 0.20.3 DCOS-21362

---

Dockerfile
Jenkinsfile
scripts/ci/run-integration-tests

We now get the results of all successful test runs combined.

Merge junit results of individual runs to one output

---

plugins/services/src/js/components/modals/CreateServiceModal.js
system-tests/services/test-apps.js
system-tests/services/test-external-volumes.js
system-tests/services/test-pods.js
tests/pages/services/ServiceFormModal-cy.js

Reverts dcos/dcos-ui#2766
Closes DCOS-21564

DCOS-21564: Revert "fix(createServiceModal): disabled review and run button"

---

plugins/nodes/src/js/components/NodeBreadcrumbs.js
plugins/nodes/src/js/components/__tests__/NodeBreadcrumbs-test.js
plugins/nodes/src/js/components/__tests__/__snapshots__/NodeBreadcrumbs-test.js.snap

DCOS-21370: NodeBreadcrumbs fail with node being undefined

---

.conventional-changelog-lintrc
commitlint.config.js
npm-shrinkwrap.json
package.json
scripts/post-commit

The old packages were deprecated. This uses the new packages, and changes the config
file to the new way.
**Checklist**

fix(commitlint): update the commit linting to new versions

---

scripts/pre-push

We replaced this package with an updated package with a different name.
**Checklist**

fix(pre-push): fix old reference to commit lint tool

---

.gitignore
jest.config.js
package.json

It just bothered me and I gave it 5 minutes, seems to work just fine 👍 
**Checklist**

Low Prio: do not generate the jest config on every run

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

This PR enables Service Endpoints partials for the UCR runtime. Previously it wasn't possible to have a Service endpoints running on UCR.
Please test JSON to Form and Form to JSON. Launching and editing the app.
Choose UCR as a runtime
Give it a hard time testing permutations
Closes DCOS_OSS-1550
**Checklist**

Enable service endpoints on UCR

---

npm-shrinkwrap.json
package.json
src/js/pages/catalog/PackageDetailTab.js
tests/_fixtures/dcos/dcos-version.json
tests/pages/catalog/packages/PackagesTab-cy.js

Backport of https://github.com/dcos/dcos-ui/pull/2786

[Backport 1.11] DCOS-21305: Respect DC/OS min required version when installing a package.

---

plugins/services/src/js/components/modals/CreateServiceModal.js
system-tests/services/test-apps.js
system-tests/services/test-external-volumes.js
system-tests/services/test-pods.js
tests/pages/services/ServiceFormModal-cy.js

Revert "fix(createService): Fix disabled review and run button"

---

tests/_fixtures/cosmos/package-describe.json

Add so we can test [this feature in EE](https://github.com/mesosphere/dcos-ui-plugins-private/pull/766).
**Checklist**

feat(package-describe): add fixture for x-region:string

---

plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortMappingsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/PortMappings.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortMappings-test.js
plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js

Backport without refactoring https://github.com/dcos/dcos-ui/pull/2830
Closes DCOS-21440

1.11 Backport: keep VIP label

---

npm-shrinkwrap.json
package.json
src/js/structs/__tests__/JobRunList-test.js
src/js/structs/__tests__/JobTaskList-test.js
src/js/utils/DateUtil.js

The current version has a security vulnerability: CVE-2017-18214
Closes DCOS-21571
**Checklist**

DCOS-21571: update moment

---

src/js/stores/MesosStateStore.js

[Backports 1.11] Fabs/1.11/fix/dcos 21784 mesos stream microtask

---

tests/_fixtures/cosmos/package-describe.json

[1.11] feat(package-describe): add fixture for x-region:string

---

npm-shrinkwrap.json
package.json
src/js/core/MesosStream.js

Backport https://github.com/dcos/dcos-ui/pull/2832 + Cypress 2.1.0 = pass from the first run \o/

Mesos Stream repeat (with cypress update)

---

npm-shrinkwrap.json
package.json

Bumping it helped release/1.11 let's see if it makes any difference on master.
Closes DCOS-21896
**Checklist**

DCOS-21896: Cypress 2.1.0

---

webpack/webpack.config.js

extracted from Bills PR: https://github.com/dcos/dcos-ui/pull/2859
Closes DCOS-21846

DCOS-21846: fix(build): stop browser from opened automatically

---

scripts/inline-bootstrap-css.js

extracted from Bills PR: https://github.com/dcos/dcos-ui/pull/2859
Closes DCOS-21845

DCOS-21845: chore(build): inmprove bootstrap css script

---

packages/data-service/README.md

Presents an example of the mediator API and some documentation.
An implementation of the Settings > Package Repository page using this api is on the go here.
This documentation will be merged into `data-layer`. And once we are ok with all the pieces we will merge this integration in master

DCOS-21752 DOCUMENTATION describes the mediator api

---

plugins/services/src/js/filters/TaskNameTextFilter.js

Change indexOf to includes
**Checklist**

fix(tasknametextfilter): change indexOf to includes

---

Dockerfile

These are unnecessarily verbose and don't add a lot of value
**Checklist**

DCOS-21574: remove comments about versions

---

Jenkinsfile

this stops jenkins from asking us in the channel every time we merge a PR on that branch 👍

chore(ci): add feature/data-layer to Jenkinsfile

---

plugins/services/src/js/constants/ServiceTableHeaderLabels.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js
plugins/services/src/js/utils/ServiceTableUtil.js
plugins/services/src/js/utils/__tests__/ServiceTableUtil-test.js
src/js/utils/ResourceTableUtil.js
src/styles/components/service-table/styles.less

Add GPU field in services table
**Checklist**

DCOS-21932: GPU services

---

Dockerfile
Jenkinsfile
package.json
scripts/ci/bump-version
scripts/ci/release-latest
scripts/ci/release-version
scripts/ci/utils/create-bump-pr
scripts/ci/utils/update-dcos-repo
system-tests/driver-config/jenkins.sh

I _knew_ it 🤷‍♂️ 
Not exactly sure what causes Cypress to hang sometimes, but it could be related to IO. This PR tries to Limit IO a bit.
If this doesnt help the next Idea is … no idea 😅
(first I thought its hanging every time, but this assumption seems to be false)

DCOS-22110: CI refactoring Day1 patch

---

plugins/services/src/js/components/modals/EditServiceModal.js
plugins/services/src/js/components/modals/__tests__/EditServiceModal-test.js
plugins/services/src/js/routes/services.js

To test this you can visit the edit page of a service and change the name in the URL you should see an error page
**Checklist**

DCOS_OSS-2355: show error if service was not found

---

plugins/nodes/src/js/filters/NodesTextFilter.js
plugins/nodes/src/js/filters/__tests__/NodesTextFilter-test.js
plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js

Add text filter in nodes page.
Closes DCOS-22127
**Checklist**

Add text filter in nodes

---

src/js/pages/system/OverviewDetailTab.js
tests/_fixtures/v1/get_flags.json
tests/_fixtures/v1/get_master.json
tests/_fixtures/v1/get_version.json
tests/_support/index.js
tests/pages/system/overview/ClusterDetails-cy.js

Fixes never ending loaders for start and elected time.
Closes DCOS-22170

fix(OverviewDetailTab): display mesos start and elected time

---

npm-shrinkwrap.json
package.json
plugins/nodes/src/js/pages/NodesOverview.js
plugins/services/src/js/components/FilterByService.js
plugins/services/src/js/components/__tests__/FilterByService-test.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/tasks/TasksView.js
src/js/components/FilterButtons.js
src/js/components/PrimarySidebarLink.js
src/js/components/TabButton.js
src/js/components/modals/ActionsModal.js
src/js/mixins/TabsMixin.js
src/js/pages/catalog/PackageDetailTab.js
src/js/pages/catalog/PackagesTab.js
src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap
src/js/pages/system/UnitsHealthTab.js
src/styles/components/badges/styles.less
tests/pages/services/ServiceActions-cy.js

This is the work to remove the "custom" badge component and start using the `badge` component from the UI Kit.
**Checklist**

feat: use badge from UI Kit

---

src/js/components/UserAccountDropdown.js

Backport to 1.11 https://github.com/dcos/dcos-ui/pull/2906
Closes DCOS-21989
**Checklist**

[backport 1.11] fix(UserAccountDropdown): fix menuItems data type

---

src/js/stores/MesosStateStore.js

Revert 2858 fabs/1.11/fix/dcos 21784 mesos stream microtask

---

plugins/services/src/js/components/DeclinedOffersTable.js
plugins/services/src/js/components/RecentOffersSummary.js
plugins/services/src/js/constants/DeclinedOffersReasons.js

Needed to add some default values, because GPU is not yet pr, because GPU is not
yet provided
Closes DCOS-21935
**Checklist**

DCOS-21935: add gpu to debug screen

---

plugins/services/src/js/utils/DeclinedOffersUtil.js
plugins/services/src/js/utils/__tests__/DeclinedOffersUtil-test.js

Add GPU to declined offers util.
Closes DCOS-21935
**Checklist**

DCOS-21935: add gpu to declinedoffersutil

---

src/js/components/charts/HostTimeSeriesChart.js
src/js/pages/DashboardPage.js

Change Dashboard charts to purple.
**Checklist**

DCOS-22362: change dashboard charts to purple

---

src/js/components/Sidebar.js

I wanted to do it within the next sprint, but my #2907 pushed me to do the refactoring searching a solution to a problem I stumbled onto.
I dug into the DC/OS UI history and discovered that the internal storage not being used since 3 years. We set the state but never read it.
Closes DCOS-22293
**Checklist**

refactor(sidebar): es6 class & remove mixin

---

plugins/services/src/js/constants/TaskTableHeaderLabels.js
plugins/services/src/js/containers/tasks/TaskTable.js
src/js/stores/MesosStateStore.js
src/styles/components/task-table/styles.less

Add GPU to task table.
Closes DCOS-21933
To test properly first run a cluster with GPU support. And then create a task that uses GPU.
https://github.com/dcos/dcos-launch/blob/master/dcos_launch/sample_configs/aws-terraform-with-gpus.yaml#L18
**Checklist**

feat(taskstable): add gpu to task table

---

jest.config.js

tests are green with this and test time reduced from ~180s to ~70s on my machine 🤔

DCOS-22444: remove ignore override

---

plugins/nodes/src/js/components/NodesTable.js
src/js/constants/NodesTableHeaderLabels.js
src/js/utils/ResourcesUtil.js
src/js/utils/__tests__/ResourcesUtil-test.js

Add GPU in nodes table.
Closes DCOS-22349
**Checklist**

DCOS-22349: add gpu in nodes table

---

Dockerfile

one (hopefully) last small thing…

DCOS-22459: add aws cli to Dockerfile

---

plugins/services/src/js/components/PodVolumeTable.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/volume-detail/PodVolumeContainer.js
plugins/services/src/js/containers/volume-detail/PodVolumeDetail.js
plugins/services/src/js/routes/services.js
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/PodSpec.js
plugins/services/src/js/structs/Volume.js
plugins/services/src/js/utils/MarathonUtil.js
plugins/services/src/js/utils/__tests__/MarathonUtil-test.js

<details><summary><strong>feat(PodVolumeTable): add a volume table for a pod</strong></summary><hr/>
Add Volume table component for pods
</details>
---
Commit:
ffd0eeb49aef3a5ee52a6e4312020d6f1f68478b
<details><summary><strong>feat(PodVolumeDetail): add detail component for pod volumes</strong></summary><hr/>
</details>
---
Commit:
9a68a1b86daa01e0a9b0a2ba362aeb0b20fe53a1
<details><summary><strong>feat(podDetail): add volume views to podDetail</strong></summary><hr/>
This introduces the Pod volume table and pod volumes detail views efforts to the pod detail view.
======
feat(MarathonUtil): add parse pod function
add a function to extract the volume information from a pod
======
feat(structs): add functions to access volume data on pod strcuts
Closes DCOS-19586
</details>
---
Commit: …

DCOS-22130 DCOS-22259: Add Pod Volume Table

---

plugins/oauth/hooks.js
plugins/tracking/hooks.js
src/js/components/modals/UserFormModal.js
src/styles/components/modal/login/styles.less
src/styles/components/modal/login/variables.less
src/styles/layout/alignment-utilities/styles.less
src/styles/layout/styles.less

Update styles for privacy policy.
Closes DCOS-22402
**Checklist**

feat(loginmodal): update styles for privacy policy (master)

---

npm-shrinkwrap.json
package.json

chore: update dcos/tslint-config

---

.eslintrc
packages/data-service/src/__tests__/graphqlObservable-test.js
packages/data-service/src/__tests__/reference/starWarsData.js
packages/data-service/src/__tests__/reference/starWarsQuery-test.js
packages/data-service/src/__tests__/reference/starWarsSchema.js
packages/data-service/src/graphqlObservable.js
plugins/catalog/src/js/repositories/RepositoriesList.js

This PR ports a group of tests form graphql-js wrapping them into Observable so they are compatible with our implementation. We believe that by making sure the reference implementation tests pass on our implementation is a great first step.
We also refactored part of the code to be easier to understand.
HOW DO I REVIEW?
My suggestion would be to run checkout and run `npm test -- --watch graphql star`. You can write more test cases or modify the current if you can think of a case where it would break. You can also come up with queries by playing on any query explorer (like the github one on notes), and trying to map then to the starwars example.
NOTES:
When testing manually, we are validating our queries structure here: https://developer.github.com/v4/explorer/
The graphql specs: …

DCOS-22332 Graphql spec compliance for field values and aliases

---

plugins/oauth/hooks.js
plugins/tracking/hooks.js
src/js/components/modals/UserFormModal.js
src/styles/components/modal/login/styles.less
src/styles/components/modal/login/variables.less
src/styles/layout/styles.less

Update styles for privacy policy.
Closes DCOS-22401
**Checklist**

feat(loginmodal): update styles for privacy policy (1.11)

---

plugins/oauth/hooks.js
plugins/tracking/hooks.js
src/js/components/modals/UserFormModal.js
src/styles/components/modal/login/styles.less
src/styles/layout/styles.less

Add privacy policy CSS.
Closes DCOS-22399
**Checklist**

feat(loginmodal): update styles for privacy policy (1.9)

---

plugins/oauth/hooks.js
plugins/tracking/hooks.js
src/js/components/modals/UserFormModal.js
src/styles/components/modal/login/styles.less
src/styles/layout/styles.less

Update styles for privacy policy.
Closes DCOS-22400
**Checklist**

feat(loginmodal): update styles for privacy policy (1.10)

---

src/js/components/FrameworkConfigurationReviewScreen.js

https://github.com/dcos/dcos-ui/pull/2913 got merged a bit too fast, this adds the requested comment for later reference and (hopefully) to prevent us from copying invalid code.

PR-2913: add comment and link ticket about invalid usage

---

CODEOWNERS

Let's remove it 💪 
**Checklist**

chore(*): remove CODEOWNERS

---

src/js/structs/CompositeState.js

**Checklist**
**How to review**
- Check that we did not break the tasks list by accident (or anything else using the composite state store (e.g. Nodes View))
- Add `console.count` to the getter and see the amount of calls before and after the change

DCOS-37423: improve performance of composite store nodes list getter

---

src/js/stores/MesosStateStore.js

Adjust the `flagSDKTask` utility to only flag tasks that aren't already flagged to improve the overall performance.
Backport of https://github.com/dcos/dcos-ui/pull/2672/commits/fd9943b626ab919f89906f7d716d389b4cf644ab
**Checklist**

DCOS-37422: adjust flagSDKTask to improve performance

---

src/js/structs/CompositeState.js

[1.11] DCOS-37424: remove unnecessary reconstructions of nodes List

---

src/js/stores/DCOSStore.js
src/js/stores/__tests__/DCOSStore-test.js

DCOS-37475: Cache Service Tree

---

scripts/ci/utils/update-dcos-repo

this should fix our latest build.
test this: no need to test, the stage was successful and DC/OS PR is (was, if we merge anything else) green 👍
Successful stage: https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/jgieseke%2Fadd-build-to-latest/2/pipeline/77
PR: https://github.com/dcos/dcos/pull/2741/files

fix(ci): add build script to fix latest builds

---

src/js/stores/DCOSStore.js
src/js/stores/__tests__/DCOSStore-test.js

[1.10] DCOS-37585: fix marathon health checks by caching right task data

---

src/js/stores/DCOSStore.js

[master] DCOS-37477: Cache Service Tree

---

src/js/stores/DCOSStore.js

[1.11] DCOS-37476: Cache Service Tree

---

plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/Pod.js

Adjust the service structs to defer the service spec creation to avoid unnecessary instantiations.
Closes DCOS-37478
**Checklist**

[1.11] DCOS-37479: defer service spec creation

---

plugins/catalog/src/js/repositories/RepositoriesAdd.js
plugins/catalog/src/js/repositories/RepositoriesDelete.js
plugins/catalog/src/js/repositories/RepositoriesList.js
plugins/catalog/src/js/repositories/__tests__/repositoriesModel-test.js
plugins/catalog/src/js/repositories/data/repositoriesModel.js

Go to Settings > Package Repositores and add / remove repositories. Should work exactly the same like before.
**Checklist**

DCOS-22014: Add and remove repos with graphql mutations

---

Jenkinsfile
scripts/ci/release-latest
scripts/ci/utils/update-dcos-repo
scripts/ci/utils/upload-build

- what happens, if you update a file which is cached for ages? -> added git sha to filename -> had to remove "force upload" flag in order to prevent overwriting of the file.
- cleaned up the scripts after ee changes…
I spun up multiple clusters from this branch and it worked… lets see what breaks this time once its on master… 🤯

DCOS-37721: Latest PR 2

---

plugins/services/src/js/containers/tasks/TasksView.js
plugins/services/src/js/utils/TaskMergeDataUtil.js
src/js/stores/DCOSStore.js
src/js/stores/__tests__/DCOSStore-test.js

This is the porting of the 1.10 performance improvement #2960. 
Please note that on 1.11 we changed the name of the class, and stop getting the hostname on mergeData. I would test this with more care and see if we still showing the right data. 
**Checklist**

DCOS-37432 - [1.11] improve merge data

---

plugins/services/src/js/containers/pod-instances/PodInstancesContainer.js
plugins/services/src/js/containers/pod-instances/PodInstancesView.js
plugins/services/src/js/containers/tasks/TasksView.js
plugins/services/src/js/utils/TaskMergeDataUtil.js
src/js/stores/DCOSStore.js
src/js/stores/__tests__/DCOSStore-test.js

This is the porting of the 1.10 performance improvement #2960, to master.
Please note that on master we changed the name of the class, and stop getting the hostname on mergeData. I would test this with more care and see if we still showing the right data. 
**Checklist**

DCOS-37434- [master] improve merge data

---

jest.config.js
npm-shrinkwrap.json
package.json
packages/extension-kid/LICENSE
packages/extension-kid/README.md
packages/extension-kid/examples/Application.ts
packages/extension-kid/index.ts
packages/extension-kid/package.json
packages/extension-kid/src/Container.ts
packages/extension-kid/src/ExtensionProvider.ts
packages/extension-kid/src/__tests__/Container-test.ts
packages/extension-kid/src/__tests__/ExtensionProvider-test.ts

This is a refined extraction from #2907 I decided shipping plugins in smaller bits so that it's easier to focus on all the important things reviewing. The downside of it - you can't really test it, but it comes with tests \o/
---
The PR introduces a new package `extension-kid 👶` formerly known as `plugin-baby`. Please look around, read the doc, vent the naming 🙇 
**Checklist**
Closes DCOS-22072

DCOS-22072: Extension Kid 👶 - came here to modularize the UI

---

plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.ts
src/js/constants/JobStates.ts
src/js/constants/JobStatus.ts
src/js/events/MetronomeClient.ts
src/js/events/__tests__/MetronomeClient-test.ts
tsconfig.json
tslint.json

Goal of this PR is to provide a Typescript and GraphQL definition for the jobs endpoint and to implement the resolvers for it
**Checklist**

DCOS-38118: Add a job model

---

.gitignore
src/styles/content/tables/styles.less

**Issue:**
The label is collapsed on Firefox, breaking the ui.
**Fix:**
Removes the `max-width: 0;` which was causing the ui to be `width 0`.
**Result:**
FF and Chrome tested.
**Test:**
Please test on Chrome and FF to make sure is wor
**Before**
**After**
**Checklist**
Closes DCOS-38114

DCOS-38114 : fix(tables/styles): fix FF collapsed table td 

---

plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/jobs/src/js/types/Job.ts
plugins/jobs/src/js/types/JobHistorySummary.ts
src/js/events/MetronomeClient.ts
src/js/events/__tests__/MetronomeClient-test.ts

This PR is about the jobs resolver who allows us to fetch a list of jobs. 
In order to make it compliant to the Job schema, we needed to do an N + 1 query. We have to fix that soon since it is far from prod ready. https://jira.mesosphere.com/browse/DCOS-38201
Testing this is tricky since it is not connected to any view yet. But you can trust my world on it 😄 or play with the tests to convince yourself.
**Checklist**

DCOS-38126 - list of jobs resolver

---

packages/data-service/package.json

types in `data-service` had no `main` entry. dima fixed it on my branch but I cant keep the commit there because my local working copy heavily changed and rebasing would be a pain. So I cherry-picked his commit into this PR 👍

chore(data-service): specify main entry point

---

plugins/jobs/src/js/components/Breadcrumbs.js
plugins/jobs/src/js/components/__tests__/Breadcrumbs-test.js
plugins/jobs/src/js/components/__tests__/__snapshots__/Breadcrumbs-test.js.snap
plugins/jobs/src/js/components/breadcrumbs/Schedule.js
plugins/jobs/src/js/components/breadcrumbs/Status.js
plugins/jobs/src/js/components/breadcrumbs/__tests__/Schedule-test.js
plugins/jobs/src/js/components/breadcrumbs/__tests__/Status-test.js
plugins/jobs/src/js/components/breadcrumbs/__tests__/__snapshots__/Schedule-test.js.snap
plugins/jobs/src/js/components/breadcrumbs/__tests__/__snapshots__/Status-test.js.snap

This is work extracted from #3016 to ship small chunks. It is needed to unblock the job overview PR, not as part of this work, but preparing this.
**Checklist**

DCOS-38479: Implement new breadcrumb based on job objects

---

plugins/jobs/src/js/__tests__/jobsRunNow-test.js
plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/jobs/src/js/jobsMenu.js
plugins/jobs/src/js/jobsRunNow.js
plugins/jobs/src/js/types/JobLink.ts
src/js/pages/jobs/JobDetailPage.js

This is the replacement of #2999 and #3020.
This PR has 2 goals:
- The groundwork to detach the menu from the JobsDetails page.
- Add the Run Job with the new Data Layer pattern.
Checklist
**Checklist**

DCOS-37612 - Run Jobs Menu Item

---

plugins/jobs/src/js/__tests__/jobsToggleSchedule-test.js
plugins/jobs/src/js/jobsDelete.js
plugins/jobs/src/js/jobsMenu.js
plugins/jobs/src/js/jobsRunNow.js
plugins/jobs/src/js/jobsToggleSchedule.js
src/js/pages/jobs/JobDetailPage.js

**SCOPE**
Refactor the menu in the shape of DCOS-37612.
**HOW TO TEST**
Checkout, run against the cluster and test that all menu items are the same.
Check this new format for reviews, see if you need more info.
TEMPLATE MVP: https://gist.github.com/Fabs/1e107028a5578a706061d41e29523060
**WHAT WAS TAKEN OUT OF SCOPE**
I pointed out the tickets as TODO
- Integrate with the graphql model
https://jira.mesosphere.com/browse/DCOS-37617
- The Delete menu with the modal
https://jira.mesosphere.com/browse/DCOS-38492

DCOS-37618 Edit and Schedule Toggle

---

plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/jobs/src/js/types/Job.ts
plugins/jobs/src/js/types/JobConnection.ts
plugins/jobs/src/js/types/JobRunStatusSummary.ts

This PR extracts the work from #3016 which is related to the JobModel. It prepares the introduction of the Overview Mediator, which will be one of the next things extracted from the old PR.
**How to Review/Test**
The JobModel isnt in use yet, in order to test this PR run `npm test -- JobModel`

DCOS-38453: update jobmodel to fit overview mediator needs

---

plugins/jobs/src/js/components/Breadcrumbs.js
plugins/jobs/src/js/pages/JobDetailPage.js

Please apply this diff in the `src/js/routes/jobs.js` file
```diff
-import { JobDetailPageContainer } from "../pages/jobs/JobDetailPageContainer";
+import JobDetailPageContainer from "#PLUGINS/jobs/src/js/pages/JobDetailPageContainer";
```
After that check out the Job Detail Page and see if the Breadcrumb works
This is the follow up on https://github.com/dcos/dcos-ui/pull/3032 and it depends on https://github.com/dcos/dcos-ui/pull/3029
**Checklist**

DCOS-38481: Add breadcrumb to Job Detail Page

---

plugins/jobs/src/js/JobDetailPageContainer.js
plugins/jobs/src/js/components/Breadcrumbs.js
plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/jobs/src/js/pages/JobConfiguration.js
plugins/jobs/src/js/pages/JobDetailPage.js
plugins/jobs/src/js/pages/JobDetailPageContainer.js
plugins/jobs/src/js/pages/JobRunHistoryTable.js
plugins/jobs/src/js/types/JobRun.ts
src/js/pages/jobs/JobDetailPageContainer.js

Please apply this diff in the `src/js/routes/jobs.js` file
```diff
-import { JobDetailPageContainer } from "../pages/jobs/JobDetailPageContainer";
+import JobDetailPageContainer from "#PLUGINS/jobs/src/js/JobDetailPageContainer";
```
After that check out the Job Detail Page, it should work except for the missing pieces described below.
- No menu items except edit
- No breadcrumb at all
This is the follow up on https://github.com/dcos/dcos-ui/pull/3024
**Checklist**

DCOS-37615:  add JobDetail page with mediator pattern

---

src/js/stores/MesosStateStore.js
src/js/utils/__tests__/rxjsUtils-test.js
src/js/utils/rxjsUtils.js

This forward-ports Orlandos work from https://github.com/dcos/dcos-ui/pull/3026 - have a look over there for more information. No code was changed 👍

DCOS-38400: forward port mesos stream backoff strategy

---

src/js/stores/MesosStateStore.js
src/js/utils/__tests__/rxjsUtils-test.js
src/js/utils/rxjsUtils.js
src/js/utils/rxjsUtils.ts

DCOS-38709 change linearBackoff interface

---

plugins/jobs/src/js/types/Job.ts

this unblocks #3046 - to test it you need to rebase that one on top of this branch.
**HOW TO TEST**
`git fetch && git checkout jg/DCOS-37752-refactor-jobs-ui-comps && git pull -r && git rebase -i origin/jg/DCOS-38892-fix-job-schedulestatus-resolver && npm run integration-tests -- JobsOverview`:
> ==> Running Tests for ./tests/pages/jobs/JobsOverview-cy.js
> ===> Executing Cypress (1/3)
> ====> Successfully finished tests for pages/jobs/JobsOverview-cy.js

DCOS-38892: fix job schedulestatus resolver

---

src/js/schemas/JobSchema.js
src/js/schemas/job-schema/Docker.js
src/js/schemas/job-schema/Parameters.js
src/js/structs/Job.js
src/js/utils/JobUtil.js

Support docker parameters.
This is based on @kensipe PR https://github.com/dcos/dcos-ui/pull/3037
*Testing:*
To really test this you need a special cluster. Maybe someone from the Marathon team will be able to help. In general we should verify if the shape of the JSON the form produces is in line with JIRA and switching from JSON and the Form back and forth doesn't mess up JSON.
Closes DCOS_OSS-3687
**Checklist**

[1.9] feat: support docker parameters

---

plugins/jobs/src/js/JobDelete.js
plugins/jobs/src/js/JobStopRun.js
plugins/jobs/src/js/__tests__/jobsToggleSchedule-test.js
plugins/jobs/src/js/components/JobStopRunModal.js
plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/jobs/src/js/jobsToggleSchedule.js

Ressurect #3043 because CI wont build it anymore

DCOS-37617: Jobs / refactor: move logic from the mediator to graphql

---

npm-shrinkwrap.json
package.json
packages/ui-kit-stage/HeaderBar.tsx
packages/ui-kit-stage/README.md
src/js/components/HeaderBar.tsx
src/js/pages/Index.js
src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap
src/styles/layout/sidebar/styles.less
src/styles/layout/styles.less

**DESCRIPTION**
This PR prepares UI for the HeaderBar (1. commit) and adds the bar itself (2. commit)
---
**HOW TO REVIEW**
`npm install` because ui-kit was updated, then make sure everything works as expected. I changed styles for sidebar and content, so please verify that sidebar collapses, expands, sticks and unsticks correctly. also check different browsers,  windows sizes and some modals please :)
---
**KNOWN ISSUES**
Well, Headerbar only contains foobar text… 
---
**HOW TO ENABLE**
In `src/js/components/HeaderBar.tsx`:
```diff
export default function HeaderBar() {
-  //remove this to activate component
-  if (arguments) {
-    return null;
-  }
-
return (
```

DCOS-38939: Branding / Add Empty Header Bar

---

src/js/components/HeaderBar.tsx
src/styles/components/header-bar/styles.less
src/styles/components/header-bar/variables.less
src/styles/index.less

Add the images and responsive styling for the Mesosphere logo on the header bar.
Show just the logo if the viewport is small. Otherwise, show the full logo with the label
"Mesosphere DC/OS".
Closes DCOS-38943
Browser
Mobile (excuse bad crop)
**Checklist**

DCOS-38943: Add Logo to Header Bar

---

.github/PULL_REQUEST_TEMPLATE.md

This is our draft to a new PR template, please take a look 👍 
Please also do not merge after 2 approvals so everybody can take a look.

Rewrite pull request template

---

plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js
src/js/stores/DCOSStore.js
src/js/stores/__tests__/DCOSStore-test.js

Backporting #3055 
If you testing with soak keep in mind that some data job may "blink" switching from all zeros to a value. Please verify with mesos UI that is an expected behavior.
Closes DCOS-39106

DCOS-39106: Show allocated resources for frameworks

---

plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx

Change this line in the `NodesTableContainer.js`:
```diff
```
Please take a look at the nodes table and see if the zones column behaves the same as before (except for the sort direction, which got fixed)
None
None

DCOS-38820: add zones column

---

plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx

Add old column tasks functionality to new refactored table.
Closes DCOS-38821

 refactor(NodesTable): tasks column

---

plugins/nodes/src/js/columns/NodesTableMemBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemColumn.tsx

Add two columns for memory usage - progress bar and number value.
Closes DCOS-38823

DCOS-38823: refactor(NodesTable): Add two columns for Mem

---

plugins/nodes/src/js/columns/NodesTableDiskBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx

Add two columns for disk usage - progress bar and percent value.
Closes DCOS-38824

DCOS-38824: refactor(NodesTable): add two columns for disk

---

src/js/components/ClusterDropdown.d.ts
src/js/components/ClusterDropdown.js
src/js/components/HeaderBar.tsx
src/js/structs/SummaryList.js
src/styles/components/header-bar/styles.less
src/typings/reactjs-components.d.ts

Please change the following lines in `src/js/components/HeaderBar.tsx`
```diff
export default function HeaderBar() {
// remove this to activate component
- if (arguments) {
-  return null;
- }
```
- I choose to refactor the dropdown instead of moving and changing it as that allows me to do a lot of small refactoring commits moving into the right direction and I think these are easier to review. Please give me feedback on this assumption 🙏 
None

DCOS-38941: Implement cluster header dropdown 

---

plugins/nodes/src/js/columns/NodesTableHostnameColumn.tsx
src/js/components/Icon.d.ts
src/typings/reactjs-components.d.ts

refactor(NodesTable): add old functionality
Add old column name functionality to new refactored table
Closes DCOS-38819
**Checklist**

DCOS-38819: new table column name

---

src/js/components/HeaderBar.tsx

This PR adds a Link to Dashboard to the Logo in our new header bar.
- 🔖 JIRA: [DCOS-39457](https://jira.mesosphere.com/browse/DCOS-39457)
- 🚫 This blocks #3084 & #3085 
- ⚠️ Header bar is not enabled yet. will happen in #3084 
- ⚠️ Wasnt able to test it yet, cluster is still starting… 😅 
To enable Headerbar in UI, in `HeaderBar.tsx`
```diff
-  if (arguments) {
-    return null;
-  }
+  // if (arguments) {
+  //   return null;
+  // }
```
After it is enabled, logo should link to dashboard

DCOS-39457: Branding / Add link to logo in header bar

---

src/js/pages/Index.js

there is a typo in master -> ee master is broken -> ee ci is broken -> we cant merge a thing :(
ci should be green…

fix(index): fix typo in removeEventListener function name

---

scripts/ci/upload-release

this makes master red every time we dont have a new release to publish 😢

ci(fupload-build): gracefully exit if file exists already

---

Dockerfile

Closes DCOS-22381
CI will test it

DCOS-22381: use our fork of http-server

---

plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
plugins/nodes/src/js/components/NodesTable.tsx

- Check if tasks are back in the Nodes Table
- went for a simple revert of the commit in the previous PR: b20961eb0cc9bc0043428e4462187e84af0adac6
None

DCOS-40039: add tasks column again

---

npm-shrinkwrap.json
package.json

they fixed a bug which lead to no comments below PRs 👍 
🤷‍♂️

chore(semantic-release): bump semantic-release package to 15.9.5

---

plugins/nodes/src/js/components/NodesTable.tsx

Changes the "Name" column to "Host" for Nodes Table.
* Check Nodes Table

DCOS-40037: change name column label to host

---

plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

only adds info to struct: `npm test`
None
None

DCOS-39905: add package version information to framework struct

---

src/js/pages/catalog/PackageDetailTab.js
src/js/pages/catalog/__tests__/PackageDetailTab-test.js
src/js/pages/catalog/__tests__/__snapshots__/PackageDetailTab-test.js.snap
src/styles/views/packages/styles.less

1. Go to "Catalog"
2. Click a service
3. Go back to Catalog
4. Select another service
None
Nothing
Before:
After:

Better loading state for package detail tab

---

npm-shrinkwrap.json
package.json

Close DCOS-39675, DCOS-39674, DCOS-39677

chore(ui-kit): upgrade ui-kit to 1.8.0

---

src/js/pages/DashboardPage.js
src/js/utils/ResourcesUtil.js
src/js/utils/__tests__/ResourcesUtil-test.js
src/styles/components/charts/styles.less
src/styles/components/status-bar/styles.less

Go to the Dashboard, look at the colors of the charts
None that I can think of
It would be nice if this [ui-kit PR](https://github.com/dcos-labs/ui-kit/pull/199) merges first. Whether it merges or not, these changes will still work as expected.

DCOS-39944 : Color resources charts on Dashboard

---

npm-shrinkwrap.json
package.json

The PR bumps mesos-client to include the fix for UTF8 chars in the mesos stream.
Closes DCOS_OSS-3968
Try creating an app with a UTF8 symbol in a label.
Smoke test the UI. That services are being created/updated/deleted

DCOS_OSS-3968: update @dcos/mesos-client to 0.2.4

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/EnvironmentVariables-test.js

DCOS-40525: enable empty env vars

---

npm-shrinkwrap.json
package.json
system-tests/_scripts/setup.sh
system-tests/cypress.json

If CI is green it should be good to go!
Closes DCOS-38652
1. Pull
2. npm install
3. npm run build-assets
4. npm run integration-tests
5. Maybe run system tests locally as well

DCOS-38652: update to 3.1.0

---

plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/components/NonLeadersGrid.js
plugins/nodes/src/js/components/__tests__/LeaderGrid-test.js
plugins/nodes/src/js/components/__tests__/NonLeaderGrid-test.js
plugins/nodes/src/js/components/__tests__/__snapshots__/NonLeaderGrid-test.js.snap
plugins/nodes/src/js/data/MesosMasters.js
plugins/nodes/src/js/data/MesosMastersHealth.js
plugins/nodes/src/js/data/MesosMastersLeader.js
plugins/nodes/src/js/data/__tests__/MesosMasters-test.js
plugins/nodes/src/js/data/__tests__/MesosMastersHealth-test.js
plugins/nodes/src/js/data/__tests__/MesosMastersLeader-test.js
plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap

Please test this on a single master and a multi master cluster. You can try soak if you just wanna read data. To kill master you need to be able to ssh into a master node and do `systemctl stop dcos-mesos-master`. Please ask around if you need help with that.
**Single master problem**
@lilysamimi I had two ideas to resolve the problem of not having more than one master in a cluster. I ended up doing Idea 1 because it is simpler.
Idea 1
https://cl.ly/402E30092Y1Z
It is the simples idea, but I dont like that we have 3 masters, andthen we figure the leader, drop to 2. On a single node cluster you will never see the Non-Leader
Idea 2
Multi Master: https://cl.ly/381d2o0E180H
Single Master: https://cl.ly/2H0z031x1j0V
**TICKETS**
this ticket also closes DCOS-39853, that was a way I could finish …

DCOS-40046 - Non Leader Masters

---

plugins/nodes/src/js/components/NodesTable.tsx

Go to the Nodes tab and check that it's sorted by "Health"
None
None

DCOS-40506: sort Nodes table by health

---

plugins/services/src/js/reducers/serviceForm/FormReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
src/js/utils/ContainerUtil.js
src/js/utils/__tests__/ContainerUtil-test.js

Backport of #3181 
Closes DCOS-40579

DCOS-40579: do not duplicate container names

---

.github/PULL_REQUEST_TEMPLATE.md

n/a
n/a
n/a
Wasn't sure how to title this PR since there's no JIRA ticket. Feel free to edit as you see fit

Update PR template with screenshot section

---

plugins/nodes/src/js/pages/NodesAgents.js
src/styles/components/buttons/styles.less

Go to the Nodes view, interact with the toggle buttons at the top-right of the screen
This is done by extending CNVS button component styles inside of dcos-ui
None
Before:
After:

DCOS-40353: update grid/list toggle visual design

---

jest/gen-config.js

- Run `npm test` and see if it works
- For me the execution time did not drop by a lot, but removing unnecessary config lead me to still do the PR
None

DCOS-22446: remove ignore override

---

src/js/components/modals/CliInstallModal.js

The new DC/OS CLI is designed to work for any version of DC/OS >= 1.10.
We can thus safely use the latest release for the current and upcoming
versions of DC/OS.

Updated DC/OS CLI installation link to latest.

---

tests/_fixtures/marathon-1-task/groups-region.json
tests/_fixtures/marathon-1-task/groups-two-regions.json
tests/_support/index.js
tests/pages/services/ServiceTable-cy.js

Since this PR just includes test in general ci will test this.
This is based on this branch `feature/DCOS-39895-services-region-info`

DCOS-40645: add integration test region column

---

plugins/index.js
plugins/intercom/SDK.js
plugins/intercom/__tests__/IntercomPlugin-test.js
plugins/intercom/constants/EventTypes.js
plugins/intercom/hooks.js
plugins/intercom/index.js
plugins/intercom/stores/IntercomStore.js
plugins/intercom/stores/__tests__/IntercomStore-test.js
src/js/config/Config.template.ts
src/js/pages/Index.js
src/js/pages/system/OverviewDetailTab.js
src/js/stores/MetadataStore.js

Adds intercom plugin.
Closes DCOS-40519
* Add the bits from https://github.com/dcos/dcos-ui/pull/3206/files#diff-33ee3a011e0fc7f6816d74252110fedd to your `Config.dev.ts` and make sure `useUIConfigFixtures` set to `true`
* Test on Open and EE cluster
* Intercom widget appears when logged in
* Intercom widget disappears when logged out
* Send a message on intercom
* Check on intercom everything was updated (Inbox -> Messages)

DCOS-40519: Add Intercom plugin

---

plugins/services/src/js/constants/ServiceTableHeaderLabels.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
plugins/services/src/js/containers/services/__tests__/__snapshots__/ServicesTable-test.js.snap
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/PodInstance.js
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/Pod-test.js
plugins/services/src/js/structs/__tests__/PodInstance-test.js
plugins/services/src/js/structs/__tests__/Service-test.js
src/styles/components/service-table/styles.less
tests/_fixtures/marathon-1-task/groups-region.json
tests/_fixtures/marathon-1-task/groups-two-regions.json
tests/_support/index.js
tests/pages/services/ServiceTable-cy.js

This is a feature branch and code already was reviewed, this PR has to be checked for overall functionality
when this is done there are region information on services table
(only region column in this PR)

DCOS-39895: Region Information in Services Table

---

npm-shrinkwrap.json
package.json
plugins/catalog/src/js/repositories/data/__tests__/repositoriesModel-test.js
plugins/catalog/src/js/repositories/data/repositoriesModel.js
plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/nodes/src/js/data/MesosMastersHealth.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
src/js/events/MetronomeActions.js
src/js/events/MetronomeClient.ts
src/js/events/__tests__/MetronomeClient-test.ts
src/js/pages/system/OverviewDetailTab.js
src/js/stores/MesosStateStore.js
src/typings/dcos__http-service.d.ts

1. Install new module `$ npm i`
2. Check out the corresponding plugin branch
3. Check the UI and see if this change introduced a bug in the areas touched by the update.
- Decided to keep the MetronomeClient open, so that it consumers can decide if they want to get the status code
None
No visual change

DCOS-40469: update http service

---

npm-shrinkwrap.json
package.json

make sure that the toggle element from #3218 has a dotted line
See https://github.com/dcos-labs/ui-kit/pull/217

DCOS-40048: update ui-kit to v1.10.3 (adds dashed line for toggle)

---

plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap

DCOS-41229: update snapshots

---

src/js/components/modals/AddRepositoryFormModal.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js

This removes the regex validation of the url field and lets rather the backend decide if a url is
valid or not.
Close DCOS_OSS-526
```
```
**Checklist**

[1.10] Backport: fix(packagerepository): remove url validation on add

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js

Go to the Service form and open the JSON editor. Create invalid JSON. Admire the error message being shown on the left side and the review button not doing anything on click
- Decided against system tests, as this is a UI only issue IMHO
None

DCOS-41500: show JSON parsing errors as top level errors

---

src/js/components/PlacementConstraintsPartial.js

* Test on Open Cluster
* Go on Catalog Page and click on Cassandra
* Click Review and Run
* Click Nodes Tab and scroll down to Placement Constraints

DCOS-40644: wrap text for constraint field tooltip

---

src/js/components/PlacementConstraintsPartial.js

Backport. See #3255 for test instructions.

[1.11] DCOS-40644: wrap text for constraint field tooltip

---

npm-shrinkwrap.json
plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js

Go to the Service form and open the JSON editor. Create invalid JSON. Admire the error message being shown on the left side and the review button not doing anything on click
- Decided against system tests, as this is a UI only issue IMHO
None
From 1.12:

DCOS-41501: show JSON parsing errors as top level errors

---

src/js/utils/MesosStateUtil.js
src/js/utils/__tests__/MesosStateUtil-test.js

See https://github.com/dcos/dcos-ui/pull/3262 for instructions.

[1.11] DCOS-41661: include executor in getHostResourcesByFramework

---

src/js/utils/MesosStateUtil.js
src/js/utils/__tests__/MesosStateUtil-test.js
tests/_fixtures/1-app-for-each-health/summary.json

See https://github.com/dcos/dcos-ui/pull/3262 for instructions.

[1.10] DCOS-41660: include executor in getHostResourcesByFramework

---

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js

Go to the Service form and open the JSON editor. Create invalid JSON. Admire the error message being shown on the left side and the review button not doing anything on click
- Decided against system tests, as this is a UI only issue IMHO
None
From 1.12:

DCOS-41503: show JSON parsing errors as top level errors

---

plugins/services/src/js/containers/pod-instances/PodInstancesContainer.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/tasks/TasksContainer.js

See https://github.com/dcos/dcos-ui/pull/3284.

[1.11] DCOS-41862: remove undefined fetchData method call

---

npm-shrinkwrap.json
package.json
src/js/components/FrameworkConfiguration.js
src/js/utils/FrameworkConfigurationUtil.js
src/js/utils/__tests__/FrameworkConfigurationUtil-test.js

[1.11] DCOS_OSS-4118: support minimal schema

---

src/js/structs/UniversePackagesList.js
src/js/structs/__tests__/HealthUnitsList-test.js
src/js/structs/__tests__/List-test.js
src/js/structs/__tests__/UniversePackagesList-test.js
src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js
src/js/utils/__tests__/search-test.js
src/js/utils/search.js

1.11 Backport of #3309
I had added a ts module and had to convert it to js for the backport. Is this normal? Seems like an unfortunate fork.

[1.11] DCOS-44243 Better text filtering

---

src/js/components/charts/ResourceTimeSeriesChart.js

Change text shares to cores in ResourceTimeSeriesChart.js
Closes Issue #3335

Fix(ResourceTimeSeriesChart.js): change shares-> cores

---

plugins/services/src/js/pages/EditFrameworkConfiguration.js
tests/pages/services/EditFrameworkConfiguration-cy.js

Cherry-pick of #3342 
Closes: DCOS_OSS-4273

DCOS_OSS-4273: show cosmos errors. [cherry pick to master]

---

plugins/services/src/js/containers/pod-detail/PodDetail.js

should check podDetail page actions menu.

fix(PodDetail.js): deleted the restart menu item Closes DCOS_OSS-4270

---

Jenkinsfile

No special testing is needed. You may want to check if the `INSTALLER_URL` link is working.

Switch Jenkinsfile to release/1.12

---

scripts/ci/upload-release

[1.12] general ci fixes

---

scripts/ci/upload-release

[1.11] general ci fixes

---

scripts/ci/upload-release

[master] general ci fixes

---

src/js/pages/Index.js
tests/smoke-cy.js

Closes DCOS-42504
Check the Network tab on the Dashboard page. UI should be connected to the `v1?subscribe` endpoint

[backport] DCOS-42504: connect to the Mesos Stream on all pages

---

plugins/jobs/src/js/pages/JobDetailPage.js
plugins/nodes/src/js/pages/nodes/NodeDetailPage.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/pages/ServicesPage.js
src/js/mixins/TabsMixin.js
src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js

Noticed this translation opportunity while working on adding translation to enterprise plugins.
There should be no visual differences or markup changes as a result of merging this PR

DCOS-43820: Mark and translate tab labels

---

Dockerfile
scripts/run-integration-tests
system-tests/driver-config/jenkins.sh

It wasn't enough just switching package.json since we were using a global installation :)
Closes DCOS-42974

DCOS-42974: use local http-server installation

---

locale/en/messages.json

Just the messages file that are included in https://github.com/mesosphere/dcos-ui-plugins-private/pull/863. This may be necessary for that PR to pass system tests.

chore(L10n): Extract messages that include plugins-private

---

Jenkinsfile

See that there is the same name in building the artifact, uploading it and using it. 
- Choose to do this quick fix instead of going the extra mile of proper versioning of the stub universe package without a JIRA ticket

Fix Universe deploy by renaming the artifact to match the archive name

---

locale/en/messages.json

Update messages catalog to accompany #3406 
Same as 3406

chore: update messages catalog

---

package.json
src/js/index.js
webpack/webpack.config.js

Reverts dcos/dcos-ui#3405
this breaks webpack server

Revert "DCOS-43779: Move webpack output to assets directory, except index.html"

---

package.json
src/js/index.js
webpack/webpack.config.js
webpack/webpack.dev.js
webpack/webpack.production.js

Reverts dcos/dcos-ui#3410
When testing let's test both dev and prod setup + make sure your browser cache is busted.

DCOS-43779: Move webpack output to assets directory, except index.html

---

locale/en/messages.json
locale/zh/messages.json

Update translation catalogs to accompany LDAP anonymous bind feature. (See [DCOS-43815](https://jira.mesosphere.com/browse/DCOS-43815))
There should be no visual changes as a result of this PR.
N/A.
This should be merged with mesosphere/dcos-ui-plugins-private#882

chore(messages.json): update translation messages

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/components/DeclinedOffersTable.js

Fix Host, Constraint, and Received columns which were being truncated with content cut off. Update messages catalogs. Backport (forwardport?) of #3415 
Closes DCOS-45574.
See #3415 (use 1.13 soak cluster instead).
None
None
See #3415

[1.13] DCOS-45574: fix truncated columns

---

plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js

Backporting #3420 
Closes DCOS-45698

fix(JSONMultiContainerParser): fully support scheduling

---

locale/zh/messages.json
tests/components/Translation-cy.js

Revert chinese translation file.
Change language in UI and ensure text content changes language.
N/A
N/A

fix(messages.json): revert chinese translations

---

src/js/events/MetronomeClient.ts
src/js/events/__tests__/MetronomeClient-test.ts

DCOS-46056: Metronome client to stop sending Content-Type header with GET requests

---

Jenkinsfile

- Open a PR with a failing integration test and see if it still makes the build red
- We won't have any information known to Jenkins about flakiness, except for the archived reports themselves, but flaky tests runs will be green, allowing us to have some air to breathe.

DCOS-46127: mark flaky tests as success

---

Jenkinsfile
cypress.json

ci: bump timeouts

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
tests/pages/services/ServiceDetail-cy.js

Cherry-picking #3431 
Just checking @natmegs I _should_ recompile the translations as I'm touching the code, right? Basically I should be recompiling them always?

DCOS-45801: handle cosmos errors

---

Jenkinsfile
cypress.json

[1.12] CI improvements train 🚄

---

src/js/components/FrameworkConfigurationForm.js
src/js/components/__tests__/FrameworkConfigurationForm-test.js

- See #3454 
- See [COPS-3907](https://jira.mesosphere.com/browse/COPS-3907)

DCOS-46093 COPS-3907

---

Jenkinsfile

Reverts dcos/dcos-ui#3418
it checks way to deep

Revert "DCOS-21600: Lint every commit on CI"

---

src/js/components/FrameworkConfigurationForm.js
src/js/components/__tests__/FrameworkConfigurationForm-test.js

- See #3454 
- See [COPS-3907](https://jira.mesosphere.com/browse/COPS-3907)

DCOS-46094 COPS-3907

---

Jenkinsfile
cypress.json

ci improvements train

---

locale/zh/messages.json

Make sure `Certified (已认证)` is used for headline & labels on catalog packages

DCOS-46279: align certified trasnlation with community

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/styles/views/services/styles.less

I accidentally pushed my backport before checking out a new branch

[1.12] - Revert accidental push directly to release/1.12

---

Jenkinsfile

- See the CI build
- We need to do a full new clone now, but this will make git based tooling easier. This choice eliminates the chance for some settings in Jenkins to effect the setup, that's the bad part about it.

DCOS-21600: Lint every commit in a PR

---

Jenkinsfile

- See in the jenkins log that the branch of this PR is checked out:
**Before**
This is the part on https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/PR-3509/7/pipeline/46
```
[cos-ui-oss-pipeline_PR-3509-L5OARLBWBH65RUTYTLUT6BX7NYIOMZI3YZ22NNM7Q52R62N4MONA] Running shell script
++ '[' -z master ']'
++ echo master
+ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```
**After**
This is the part on https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/PR-3531/1/pipeline
```
[cos-ui-oss-pipeline_PR-3531-4RGCRZ6VLVYNQFTUHQTRTU2SUOJZ643PFPWSNWHBI4RFUZI5RGXA] Running shell script
++ '[' -z danielmschmidt/DCOS-47182 ']'
++ echo …
```

DCOS-47182: checkout right branch before running tests

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/components/SDKPlans.tsx
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/routes/services.js
src/js/components/Page.d.ts
src/js/components/Page.js
system-tests/universe/test-universe.js

This introduces the plans tab to the detail page for sdk packages
Closes DCOS-45813
1. Install a SDK package e.g. `Cassandra`
2. Visit the Detail page.
3. Visit the Plans tab
*N/A*
This is depending on #3503

DCOS-45813: Implement basic plans tab ("v0")

---

package.json
src/js/index.js

1. run `npm run build-assets`
2. start dcos-ui locally
3. open ui
4. ensure icons are loaded
N/A
N/A

DCOS-47374 fix: icons for local development

---

Dockerfile
Jenkinsfile
Jenkinsfile.reruns
package-lock.json
package.json

Let's see if it speeds up the build
Number to beat `npm --unsafe-perm install : 3m 34s`

Update npm / use npm ci

---

system-tests/universe/test-universe.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceDetail-cy.js
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/TasksTable-cy.js

PR for testing and fixing muted flakes:
* ~Deployments Modal~ 🎉 
* Service Actions

Integration Flakes

---

npm-shrinkwrap.json
package.json
system-tests/universe/test-universe.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceDetail-cy.js
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/TasksTable-cy.js

Making 1.12 CI more stable just in case.

[1.12] Backport unflakes

---

.babelrc
jest/preprocessor.js
package-lock.json
package.json
webpack/webpack.config.js

Resolves https://github.com/dcos/dcos-ui/issues/3510

babel-preset-es2015 is deprecated, use babel-preset-env

---

README.md

As i stumbled upon setting up the private-plugins, here's a suggestion to update the README.md.

add instructions for setting up private-plugins

---

package-lock.json
package.json

Smoke testing UI and monitoring console if there're any errors.

Fix react@16 ref related bugs in reactjs-components

---

README.md
plugins/oauth/components/LoginPage.js
src/js/components/charts/Chart.js

- See that the Charts on the dashboard still work while resizing

DCOS-48298: findDomNode does not work with this

---

packages/dcos-ui-update-client/LICENSE
packages/dcos-ui-update-client/index.ts
packages/dcos-ui-update-client/package.json
packages/dcos-ui-update-client/src/DCOSUIUpdateClient.ts
packages/dcos-ui-update-client/src/__tests__/DCOSUIUpdateClient-test.ts
packages/dcos-ui-update-client/src/utils.ts
src/js/data/ui-update/UIMetadata.ts
src/js/data/ui-update/__tests__/index-test.ts
src/js/data/ui-update/index.ts

Adding client and data-layer for making queries and requests to the
dcos-ui-update-service.
Run unit tests, this will be used and testable by an upcoming feature.

DCOS-47965 UI-Update Service client & data-layer

---

src/js/components/ClickToSelect.js

Install CLI => click on the text area it shouldn't throw

fix: ClickToSelect.js ref

---

package-lock.json
package.json

Without the fix:
open the login page and inspector
login hitting enter
watch an exception being thrown

Fix input blur exception

---

src/js/components/SchemaField.js

see https://github.com/dcos/dcos-ui/pull/3595

DCOS-48521: [1.12] Volume type toggle buttons do not toggle on.

---

scripts/utils/integration-tests

Some documentation on how to run integration tests locally.

docs: npm run integration-tests

---

plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js

Closes DCOS_OSS-4840
See [DCOS_OSS-4840](https://jira.mesosphere.com/browse/DCOS_OSS-4840)

fix(JSONMultiContainerParser): fully support scheduling.placement

---

.releaserc
package-lock.json
package.json

Prerequirement for #3632 , would like to be able to test a couple things with assets before moving forward. 🙇

[spike] add assets to GH releases

---

Jenkinsfile

CI was failing because it got stale config values from earlier runs…

fix: unset externalplugins config var on ci

---

system-tests/universe/test-universe.js

fix: universe plan system test workaround

---

package-lock.json
package.json

update typescript to 3.3.3333

---

package-lock.json
package.json

Closes #3680 #3681
turns out both packages are unused…

chore(deps): remove unused @commitlint packages

---

renovate.json

* **remove automatic rebase**
we can merge master if necessary or just force-merge PRs…
* **enable automerge**
it should automatically merge after all checks are green
* **enable grouping for certain packages**
this should reduce noise
* **enable limit of concurrent PRs (5)**
also should reduce noise

ci: update renovate to reduce noise

---

Dockerfile

trying this approach https://askubuntu.com/a/746429

chore: fix jdk package

---

plugins/services/src/js/structs/PodContainer.js
plugins/services/src/js/structs/__tests__/Pod-test.js
plugins/services/src/js/structs/__tests__/PodContainer-test.js
plugins/services/src/js/structs/__tests__/PodInstance-test.js
tests/_fixtures/pods/PodFixture.js

Update the health checks endpoint to get accurate health checks.
Closes https://jira.mesosphere.com/browse/DCOS_OSS-1665
1. Go to services tab
2. Create a valid pod (with a command for the container, for examlpe `sleep 1000`)
3. Go to health checks tab and add a health check for that container that returns true (example: `echo 1`)
4. Start the pod, and check the instances table for that pod - the health should be green and upon expanding the container should be green
5. Edit the pod
6. Add a second container with a command and a health check that returns false (example: `exit 1`)
7. Start the pod, and check the instances table for that pod - the health should be red and upon expading the first container should be green and the second one should be red
Example JSON:
```
{
"id": …
```

DCOS_OSS-1665: Successful pod healthcheck not reported in DC/OS UI

---

plugins/services/src/js/components/SearchLog.js
plugins/services/src/js/pages/task-details/ServiceTaskDetailPage.js

Open a task log page with react dev tools and [flash on rerender](https://blog.logrocket.com/make-react-fast-again-part-3-highlighting-component-updates-6119e45e6833) enabled and see that there are less then before this change
Before and after (the better one is after 😇 )

DCOS-51364: use PureComponent to avoid re-renders

---

package-lock.json
package.json
plugins/nodes/src/js/components/NodesTable.tsx
src/js/components/ProgressBar.js

same as in https://github.com/dcos/dcos-ui/pull/3789

DCOS-51370: remove dependencies we can do with lodash

---

plugins/jobs/src/js/JobsOverview.tsx
plugins/jobs/src/js/components/JobsOverviewList.tsx

Check that the jobs page looks and behaves the same, and flashes less in the react flash update UI

DCOS-51478: Jobs: apply distinctuntilchanged to avoid rerenders

---

plugins/services/src/js/structs/PodContainer.js
plugins/services/src/js/structs/__tests__/PodContainer-test.js

view an unhealthy pod. On SOAK try `pull-image-auth` or `pull-image-cert` and verify UI doesnt crash

fix(PodContainer): ensure conditions exists

---

package-lock.json
package.json
tests/pages/jobs/JobDetails-cy.js
tests/pages/services/PodDetail-cy.js
tests/pages/services/ServiceDetail-cy.js
tests/pages/services/TasksTable-cy.js
tests/pages/services/VolumesTable-cy.js
tests/pages/system/overview/repositories/RepositoriesTab-cy.js

- Check if all old tables work faster or equally fast

DCOS-51547: only use VirtualList for tables with large data sets

---

locale/en/messages.json
locale/zh/messages.json
src/js/components/RequestErrorMsg.js

Revert "[spike] DCOS-46215: Error requesting UI Configuration message email is shown as {0}"

---

plugins/services/src/js/reducers/JSONSingleContainerParser.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/UnknownVolumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/UnknownVolumes-test.js
src/js/structs/Transaction.d.ts

Gave UnknownVolumesParser function a unique name so that it could be
replaced by a plugin.

DCOS-51384 name unknownvolumes parser

---

plugins/services/src/js/containers/services/ServicesTable.js

this is a prototypical commit message for a series of spikes.
find specific things to pay attention to on the end of this message. also there's a general bunch of things that might be in here: 
* remove dead code and its dependencies
* convert stuff to ES6-syntax
* convert imports/exports to ES6
* move functions out of classes (to emphasize that they are not methods)
* simplification of boolean expressions
* usage of early returns to decrese indentation level
i grep every function/method and try to find out whether it is still in use. if not, it is deleted. at the end i browse the UI to see whether stuff still works. 
convince yourself that no functionality has been broken. on a mechanical level this can be done by also greping for stuff or digging through history using `git blame`. on …

DCOS-52770 - ServicesTable: remove dead code

---

plugins/jobs/src/js/components/JobsForm.tsx
plugins/jobs/src/js/components/form/helpers/DefaultFormData.ts
plugins/jobs/src/js/components/form/helpers/JobFormData.ts

Some type additions and clarifying renames that will be needed for Jobs File Based Secrets.
Should not change any behavior.
Hold merge until companion PR is ready

[DCOS-53141] Jobs File Based Secrets Dependencies

---

src/styles/components/secret-value/styles.less

https://github.com/mesosphere/dcos-ui-plugins-private/pull/900

[spike] DCOS-21195

---

src/js/i18n.ts

Should fix dcos-ui-plugins-private CI
Two issues:
- messages.json was being resolved by jest
- require statement was not interoperable with node/jest

fix: messages.json was being resolved by jest

---

scripts/ci/rerun-integration-tests.sh
scripts/run-integration-tests
scripts/run-system-tests

cause it seems to not be used anywhere. 
waiting for CI to be green.

remove `PLUGINS_PATH`

---

Dockerfile
Jenkinsfile
tests/pages/nodes/NodesPage-cy.js

fixes 1.11 branch CI until jessie is EOL (june 2020)
credits: https://www.reddit.com/r/docker/comments/baunkt/failed_to_fetch/ekh1b3u/

ci: fix jessie backports

---

Dockerfile

[1.12] ci: fix jessie backports

---

plugins/nodes/src/js/pages/NodesAgents.js
plugins/nodes/src/js/pages/nodes/NodeDetailHealthTab.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/services/src/js/components/forms/MultiContainerFormAdvancedSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
src/js/components/Breadcrumb.js
src/js/components/FormModal.js
src/js/components/form/FormGroupHeadingContent.js
src/js/components/modals/FullScreenModalHeaderActions.js

[spike] [DCOS-53713] Fix errors & warnings

---

package-lock.json
package.json

DCOS-48818: translate text

---

plugins/services/src/js/components/modals/CreateServiceModal.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js
plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerVolumes-test.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/MarathonPodValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
plugins/services/src/js/validators/__tests__/MarathonPodValidators-test.js

---
↩️  _This PR back-ports the fix introduced with #3920 to release/1.13 ._
---
Please see https://github.com/dcos/dcos-ui/pull/3920 for instructions on how to test the resp. changes.

DCOS-43777: provide default volume type for DSS volumes

---

src/js/config/Config.template.ts
src/js/config/Config.ts

Introduce feature flag for quota. Feature flag will be used to develop
Quota Management UX and then removed when feature is complete.
- Closes DCOS-55629
N/A

chore: create quota feature flag

---

plugins/services/src/js/pages/ServicesPage.js
plugins/services/src/js/pages/ServicesPage.tsx
src/typings/reactjs-mixin.d.ts

Move ServicesPage from createReactClass to es6 class.
Go to services page, tab around and make sure nothing breaks.
I 90% converted this to TS but got hung up on the mixin types 😞 
N/A

[Spike] Refactor ServicesPage: update with es6 class

---

plugins/services/src/js/columns/ServicesTableNameColumn.tsx
plugins/services/src/js/containers/services/ServiceTreeView.js
plugins/services/src/js/data/groups/resolvers.ts
plugins/services/src/js/utils/QuotaUtil.ts
plugins/services/src/js/utils/__tests__/QuotaUtil-test.ts

0. Ensure fixtures are off.
1. Create a top-level group
2. Using the Mesos API set quota for a role with the same name as your group
```
$ ## Set Quota
curl -X "POST" "<CLUSTER_URL>/mesos/api/v1?SET_QUOTA" \
-H 'Authorization: token=<token>' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d $'{
"type": "SET_QUOTA",
"set_quota": {
"quota_request": {
"force": true,
"guarantee": [
{
"scalar": {
"value": 1
},
"name": "cpus",
"role": "*",
"type": "SCALAR"
},
{
"scalar": {
"value": 512
},
"name": "mem",
"role": "*",
"type": "SCALAR"
}
],
"role": "<group_name>"
}
}
}'
```
3. Navigate to Quota tab Services -> Quota tab
4. Verify the group you created is displayed in the list.

DCOS-56638 Quota UI - Feature Flag Removal

---

plugins/nodes/src/js/components/NodesTable.tsx
plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js
src/js/config/Config.template.ts
tests/_fixtures/config/no-plugins.json

This needs to be included in the MWT alpha and must be included in the release tomorrow
- Visit nodes table and ensure you can see status column and status filters
- Visit node details tab and ensure you can see Status section

chore: remove maintenance feature flag for readonly features

---

plugins/services/src/js/utils/__tests__/ServiceTableUtil-test.js

Updating unit tests to match code changes in #3988 
run unit tests and they pass.

fix: service sorting unit tests

---

Dockerfile

Updating to a newer base image, the current one is failing to `apt-get
update` since debian-stretch is no longer supported.
N/A see if PR checks pass, this change is to fix CI.

chore(Dockerfile): update base image

---

plugins/services/src/js/columns/QuotaOverviewCPUConsumedColumn.tsx
plugins/services/src/js/columns/QuotaOverviewDiskConsumedColumn.tsx
plugins/services/src/js/columns/QuotaOverviewGPUConsumedColumn.tsx
plugins/services/src/js/columns/QuotaOverviewMemoryConsumedColumn.tsx
plugins/services/src/js/components/ServicesQuotaOverviewDetail.tsx
plugins/services/src/js/types/ServiceGroup.ts
plugins/services/src/js/utils/QuotaUtil.ts
tests/pages/services/QuotaOverview-cy.js

DCOS-56963 - fix(Quota): ensure quota values are properly truncated for display

---

plugins/jobs/src/js/components/JobsOverviewTable.js
system-tests/jobs/test-jobs-cy.js
tests/_fixtures/metronome/jobs.json
tests/pages/jobs/JobsOverview-cy.js

Backport for https://github.com/dcos/dcos-ui/pull/4024

[1.13] [COPS] DCOS-54937: Jobs list shows job twice if name matches group

---

plugins/jobs/src/js/components/JobsOverviewTable.js
tests/_fixtures/metronome/jobs.json
tests/pages/jobs/JobsOverview-cy.js

Backport for https://github.com/dcos/dcos-ui/pull/4024

[1.12] [COPS] DCOS-54937: Jobs list shows job twice if name matches group

---

src/js/structs/Node.d.ts
src/js/structs/Node.js
src/js/structs/__tests__/Node-test.js

some random find. 
IMHO good to merge once CI is green.
make sure no code calls `sumTaskTypesByState`.

chore: remove sumTaskTypesByState

---

plugins/services/src/js/data/MarathonClient.ts

Create a group
Edit group
Save and ensure there is not an error.

fix(MarathonClient): use PATCH to update group

---

src/styles/views/packages/styles.less

I accidentally broke this while adding the catalog filter.
1. Go to Components tab and verify that the filter looks as expected.
2. Go to Catalog tab and verify that the filter looks as expected.
None.
None.

Components filter styling

---

Jenkinsfile
package.json
scripts/lingui-ensure-extracted

chore: test extraction-check

---

package-lock.json
package.json
plugins/services/src/js/pages/task-details/TaskDetail.js
webpack/webpack.config.js

This is an enabler PR see EE counterpart

DCOS-12206: TTY Spike

---

plugins/services/src/js/constants/MesosConstants.js
plugins/services/src/js/constants/VolumeConstants.ts
plugins/tracking/constants/PluginConstants.js
plugins/tracking/hooks.js
src/js/constants/AuthConstants.js
src/js/constants/PluginConstants.js
src/js/constants/PluginConstants.ts
src/js/plugin-bridge/AppReducer.js
src/js/plugin-bridge/PluginSDK.js
src/js/plugin-bridge/__tests__/ActionsPubSub-test.js
src/js/plugin-bridge/__tests__/AppReducer-test.js
src/js/schemas/job-schema/General.js
src/js/utils/CookieUtils.js

as constants-files should be easy to convert to typescript, i'll create small PRs inbetween meetings to convert some.
sometimes it's easier and more straightforward to inline constants than to convert the file.

tsify constants

---

plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

1. Create a single container service with
```json
{
"id": "/app1",
"container": {
"linuxInfo": {"ipcInfo": {"mode": "PRIVATE", "shmSize": 128}}
},
"cpus": 0.1,
"mem": 32,
"cmd": "df -m /dev/shm && sleep 1000"
}
```
2. Change the form and see that it does not exist
I was unsure about testing, so I just went with a unit test for this. Do you think we need more?

DCOS-57932: Allow unknown values in container

---

.linguirc
locale/en/messages.json
locale/zh/messages.json
src/js/utils/DefaultErrorUtil.tsx

Messages from utils were not extracted thus ignored by lingui
I also reused a translation key removing `:`
https://jira.mesosphere.com/browse/DCOS-59680

fix: extract messages from utils

---

plugins/nodes/src/js/stores/NodeHealthStore.js
plugins/services/src/js/stores/MarathonStore.js
plugins/services/src/js/stores/MesosLogStore.js
plugins/services/src/js/stores/SDKEndpointStore.js
plugins/services/src/js/stores/TaskDirectoryStore.js
src/js/stores/AuthStore.js
src/js/stores/ConfigStore.js
src/js/stores/CosmosPackagesStore.js
src/js/stores/LanguageModalStore.js
src/js/stores/MesosSummaryStore.js
src/js/stores/MetadataStore.js
src/js/stores/SidebarStore.js
src/js/stores/SystemLogStore.js
src/js/stores/UnitHealthStore.js
src/js/stores/UserStore.js
src/js/stores/UsersStore.js
src/js/stores/VirtualNetworksStore.js

it does not seem so be used anywhere...

chore: remove dispatcherIndex

---

cypress.json
package-lock.json
package.json
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
scripts/run-system-tests
system-tests/dashboard/_scripts/setup
system-tests/dashboard/test-dashboard-cy.js
system-tests/services/_scripts/setup
tests/_support/index.js
tests/pages/services/ServiceFormModal-cy.js

cypress is now aware of failing network requests and does not want them to
happen. we therefore need to add a route here.

chore: upgrade cypress and fix tests

---

plugins/services/src/js/columns/ServicesTableActionsColumn.tsx
plugins/services/src/js/components/modals/ServiceResumeModal.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js

[Backport 1.13] DCOS-5626

---

renovate.json

...cause in 90% of the cases it makes more sense to upgrade single packages as a
group is more likely to break some tests.

chore: don't group renovate upgrades

---

src/js/__tests__/tslint-test.ts
src/js/__tests__/typecheck-test.ts

it looks like the ee-ci needs more than a minute to get those tasks done.

chore: increase ts-related jest-timeouts for ee-CI

---

package-lock.json
package.json

chore: remove react-hot-loader

---

package-lock.json
package.json

chore: remove style-loader

---

package.json
plugins/banner/__tests__/BannerPlugin-test.ts
plugins/intercom/stores/__tests__/IntercomStore-test.ts
plugins/services/src/js/stores/__tests__/MarathonStore-test.ts
plugins/services/src/js/stores/__tests__/MesosLogStore-test.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/plugin-bridge/__tests__/ActionsPubSub-test.ts
src/js/plugin-bridge/__tests__/AppReducer-test.ts
src/js/plugin-bridge/__tests__/Hooks-test.ts
src/js/plugin-bridge/__tests__/PluginSDK-test.ts
src/js/stores/__tests__/AuthStore-test.ts
src/js/stores/__tests__/ConfigStore-test.ts
src/js/stores/__tests__/CosmosPackagesStore-test.ts
src/js/stores/__tests__/MesosSummaryStore-test.ts
src/js/stores/__tests__/NotificationStore-test.ts
src/js/stores/__tests__/UsersStore-test.ts
src/js/utils/__tests__/SystemLogUtil-test.ts
src/js/utils/__tests__/Util-test.ts

chore: prepare jest-upgrade

---

src/js/__tests__/tslint-test.ts
src/js/__tests__/typecheck-test.ts

the ee-CI seems to need about a minute. let's give it some leeway without being
too permissive.

chore: adjust the ts-test-timeouts

---

package-lock.json
package.json

we don't plan to include the remote-terminal as is. let's drop this dep as it's
not needed until we have a plan.

chore: remove xterm

---

src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/components/form/FieldError.tsx
src/js/components/form/FieldInput.tsx
src/js/components/form/FormGroup.tsx

by typing a couple central components we get rid of a lot of type errors.

chore: fix some type errors around forms

---

package-lock.json
package.json

chore: remove tv4

---

locale/en/messages.json
locale/zh/messages.json
src/js/components/HeaderBar.tsx
src/js/config/Config.test.ts
src/js/config/Config.ts
src/styles/components/header-bar/styles.less

Change you refresh rate setting to be not the default value of `2 seconds`. Ensure it is only showing if that applies.

feat(refreshratee): add refreshrate to the header

---

plugins/nodes/src/js/columns/NodesTablePublicIPColumn.tsx
plugins/services/src/js/structs/LogBuffer.ts
plugins/services/src/js/structs/PodInstanceList.ts
plugins/services/src/js/structs/PodTerminationHistoryList.ts
plugins/services/src/js/structs/ServicesList.ts
plugins/services/src/js/structs/TaskDirectory.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/structs/HealthUnitsList.ts
src/js/structs/JobTaskList.ts
src/js/structs/Node.ts
src/js/structs/NodesList.ts
src/js/structs/OverlayList.ts
src/js/structs/RepositoryList.ts
src/js/structs/UniversePackagesList.ts
src/js/structs/__tests__/Node-test.ts

well, there's actually a tiny refactoring in here as well.
also we remove some dead code. that's due to the fact that we're trying to clean
things up as fast as possible and CI takes quite some time.

chore: add types to all lists

---

src/js/utils/ReducerUtil.ts

they emerged during a pairing with Philipp and i think it would be a pity to
just throw them away.

chore: cosmetics on a random reducer

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.tsx
plugins/services/src/js/components/forms/NetworkingFormSection.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
tests/pages/services/ServiceFormModal-cy.js

👉 https://jira.mesosphere.com/browse/DCOS-62535
adds a select-option for calico for single- and multicontainer-forms.

DCOS-62535 support calico networking in service forms

---

plugins/nodes/src/js/routes/nodes.ts
plugins/services/src/js/routes/services.ts
src/js/routes/catalog.ts
src/js/routes/components.ts
src/js/routes/factories/network.ts
src/js/routes/jobs.ts
src/js/utils/RouterUtil.ts

it's not used anywhere (anymore).

chore: remove hideHeaderNavigation

---

src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/components/Modals.tsx

it's a test-balloon for the other 22 components...

refactor: replace createReactClass with React.Component

---

renovate.json

let's have a look at everything ourselves...

chore: disable renovates automerge

---

Jenkinsfile

chore: dry up cred-usage in Jenkinsfile

---

Jenkinsfile
src/js/__tests__/__snapshots__/tslint-test.ts.snap
src/js/__tests__/tslint-test.ts

chore: consume tslint via file

---

src/js/pages/network/VirtualNetworksTable.tsx
src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.tsx
src/js/routes/factories/network.ts

fix: don't render multiple tabs active in VirtualNetworkDetail

---

tests/_support/index.js
tests/pages/services/GroupCreate-cy.js

we're using cy.log's now to add some metadata about what exactly is happening
right now and batch all the tests in order to speed up the suite.
looks like these changes bring down the test from about 100sec to about 40sec.

chore: speed up slow integration test

---

tests/pages/services/ServiceActions-cy.js

this is the last of the biggies currently and should go from about 100sec to
about 30 sec now.

chore: speed up ServiceActions integration test

---

Jenkinsfile

run jest-tests sequentially while making it a parallel stage in CI

chore: speed up CI

---

jest.config.js
plugins-ee/licensing/components/__tests__/__snapshots__/LicensingExpirationRow-test.tsx.snap
plugins/services/src/js/constants/DeclinedOffersHelpText.tsx
src/js/config/Config.ts
src/js/pages/catalog/PackagesTab.tsx
src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.tsx.snap
src/js/stores/MetadataStore.ts

also fix the single instance that made me notice that all of our links are
broken.

fix: fix links to docs

---

src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/typings/reactjs_mixin.d.ts
tsconfig.json

chore: type stores more correctly

---

jest/setupEnv.ts
package-lock.json
package.json

speeds up the tests a slight bit.

chore: remove explicit dependency babel-polyfill

---

CONTRIBUTING.md
plugins/services/src/js/components/SDKPlanTable.tsx
plugins/services/src/js/components/SDKPlans.tsx
scripts/utils/load_auth_env_vars
system-tests/_support/index.js
system-tests/universe/test-universe-cy.js

waiting a bit longer for plans to show up.

chore: get rid of our main flake in CI

---

system-tests/universe/test-universe-cy.js

moving the plan-inspection test down a little for the service to get up and
running. also cleaning up stuff to not have multiple visitURLs one after
another.

chore: fix a flake

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/columns/ServicesTableCPUColumn.tsx
plugins/services/src/js/columns/ServicesTableMemColumn.tsx
plugins/services/src/js/containers/services/ServicesTable.tsx
plugins/services/src/js/structs/Pod.ts
plugins/services/src/js/structs/Service.ts
plugins/services/src/js/structs/ServiceTree.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
tests/_fixtures/resource-limits/groups.json
tests/_support/index.js
tests/pages/services/ServiceTable-cy.js

This introduces the virtual bursting information to the services table.

DCOS-62251 add reservations to service table

---

plugins/services/src/js/reducers/serviceForm/Container.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/structs/Transaction.ts
src/js/utils/ParserUtil.ts

chore: rudimentarilly type the parserUtil

---

plugins/placement/components/RegionSelection.tsx
plugins/placement/utils/PlacementUtil.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

refactor: region selection

---

plugins/placement/components/JobPlacementSection.tsx

refactor: boil down some logic in JobPlacementSection

---

tests/_support/index.js
tests/_support/utils/router.js
tests/_support/utils/tests/router-test.js
tests/pages/networking/Networks-cy.js
tests/pages/services/DeploymentsModal-cy.js

chore: remove getAPIResponse

---

Jenkinsfile
scripts/terraform/main.tf
scripts/utils/load_auth_env_vars
system-tests-ee/ee-services/_scripts/setup
system-tests-ee/ee-services/test-apps-secrets-cy.js

chore: parameterize dcos download paths

---

README.md
package.json
plugins/services/src/js/columns/ServicesTableVersionColumn.tsx
plugins/services/src/js/components/modals/ServiceRootGroupModal/index.tsx
plugins/services/src/js/containers/services/ServiceTreeView.tsx
plugins/services/src/js/containers/services/ServicesQuotaView.tsx
plugins/services/src/js/containers/services/ServicesTable.tsx
plugins/services/src/js/utils/QuotaUtil.ts
plugins/services/src/js/utils/__tests__/QuotaUtil-test.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/stores/dcos-version.ts
src/js/utils/Version.ts
src/js/utils/__tests__/Version-test.ts
tests/_fixtures/dcos/dcos-version.json

Please merge #4568 first as this builds upon it.
We hide quota-related features in case we're on a 1.13.x-cluster. That way we can create a 4.x channel that supports 1.13 as well as 2.0 and allows us to backport all features/improvements/bugfixes to those versions all at once.

Feature Flag Quota

---

scripts/ci/dcos-bump

no feature parity yet. still feels more automated as it does CHANGES.md by
itself. (which might be a bad thing when not paying close attention to what
exactly is changed. let's see in the future how that turns out.)

chore: make the bump-script work again

---

Jenkinsfile

interestingly integration and OSS shared a proxy till now...

chore: make oss/ee tests more similar and fix a proxy-issue

---

Jenkinsfile
scripts/utils/tests-functions
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

chore: test vs 1.13.7 and 2.0.2

---

plugins/secrets/components/SecretFormModal.tsx

prevent stuff from breaking when user chooses to hit the enter key in an input
inside that form...
closes D2IQ-14964

fix: don't use native submit on secrets form

---

package-lock.json
package.json
plugins/organization/submodules/directories/components/__tests__/DirectoryFormModal-test.tsx
src/js/__tests__/__snapshots__/tslint-test.ts.snap
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

- chore: fix some type and linting errors
- chore(deps): update dependency typescript to v3.9.2

fix some types

---

plugins/services/src/js/containers/pod-debug/PodDebugContainer.tsx
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.tsx

https://jira.d2iq.com/browse/D2IQ-69020

D2IQ-69020 update docs-links

---

plugins/auth/hooks.tsx
plugins/services/src/js/containers/pod-debug/PodDebugContainer.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

we used to show the infobox in any case. even when all was well.
closes D2IQ-57756

D2IQ-57756 don't show empty infobox on pod debug

---

package-lock.json
package.json
plugins/services/src/js/components/modals/ServiceDestroyModal.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/components/modals/CliInstallModal.tsx
src/js/components/modals/__tests__/CliInstallModal-test.tsx

review commit-by-commit. this adds to 0b94de1165c7d5ae17c553b1005bd0230de9444a in that the download now also works on 1.13 clusters.

Remove dead code

---

package.json
src/js/config/Config.test.ts
tests/pages/services/ServiceActions-cy.js

chore: fix a common flake

---

system-tests/universe/test-universe-cy.js

chronos is a community package now

chore: fix integration tests

---

plugins/jobs/src/js/components/JobsOverviewTable.tsx
plugins/jobs/src/js/components/form/GeneralFormSection.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
tests/pages/jobs/JobActions-cy.js

you may want to spin up a cluster and see that the current job is not in the list of suggestions anymore
commit-by-commit

DCOS_OSS-5990

---

scripts/pre-install

we automatically validate our ServiceSpecs with marathons RAML definitions.
let's update those to know about CSI Volumes.
Closes D2IQ-71945

chore: update marathon RAMLs

---

plugins/jobs/src/js/components/form/helpers/ErrorUtil.ts
plugins/services/src/js/components/forms/VolumesFormSection.tsx
plugins/services/src/js/constants/ServiceErrorMessages.ts
plugins/services/src/js/reducers/serviceForm/FormReducers/Volumes.ts
plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.ts
plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.ts
src/js/__tests__/__snapshots__/tslint-test.ts.snap
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

during the exploration of why our json editor rejects a valid CSI volume these
changes emerged.
they should not change behaviour and are just of structural nature with the goal
of improving workability and type safety of the code around.

chore: refactor volume related code in service form

---

plugins/services/src/js/components/modals/ServiceRootGroupModal/index.tsx
plugins/services/src/js/containers/services/ServiceTreeView.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/stores/dcos-version.ts

from now on we'll only support clusters >= 2.0 and thus can skip this check

chore: remove quota-flag

---

plugins/secrets/validators/SecretsValidators.ts
plugins/secrets/validators/__tests__/SecretsValidators-test.ts

Closes: https://jira.d2iq.com/browse/D2IQ-72705
- [] Integration tests
- [] System tests
- [] Does it need a feature flag?

Do not prevent abolute path in container secret

---

plugins/services/src/js/components/ServicesQuotaOverviewDetail.tsx
plugins/services/src/js/components/forms/GeneralServiceFormSection.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/utils/Units.ts
tests/_fixtures/quota-management/roles.json

https://jira.d2iq.com/browse/COPS-6589

COPS-6589 - show "0" instead of "N/A" when quota limit is 0
