dcos/dcos-ui

src/js/components/modals/InstallPackageModal.js, src/js/components/modals/__tests__/InstallPackageModal-test.js
=> Remove -default from service names

jest/setupEnv.js, package.json, src/js/index.js
Previously introduced by @aldipower into our unified-ui feature branch and now being introduced into master in anticipation of `_`-free project
=> Introduce Babel Polyfill

src/js/components/modals/InstallPackageModal.js, src/js/components/modals/__tests__/InstallPackageModal-test.js, src/js/structs/UniversePackage.js
=> Feature - Show PreInstall Notes on Install Modal

src/js/stores/MesosSummaryStore.js, src/js/stores/__tests__/MesosSummaryStore-test.js
=> DCOS-6177 Fix case where history server returns empty Object

src/styles/layout/sidebar.less
=> DCOS-6165: Force user email address to wrap

npm-shrinkwrap.json, package.json
source-map-loader@latest webpack@latest node-libs-browser@latest
=> Upgrade deps

src/js/components/ServicesTable.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js
=> Add #getWebURL method to Service struct

src/js/components/Sidebar.js, src/styles/layout/sidebar.less
=> DCOS-5994: Move logo to menu container and apply flex properties as needed

src/js/structs/Service.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/Service-test.js, src/js/structs/__tests__/ServiceTree-test.js
This is based on #16 only the last commit(78a385a) is new.
=> Rename getInstances to getInstancesCount

src/js/components/charts/AnimationCircle.js
=> Make sure not to animate circles in graphs into position on first render

jest/setupTestFramework.js, npm-shrinkwrap.json, package.json
Because we upgraded `jest`, this upgraded Jasmine and I forgot to upgrade the `jasmine-reporters` dep.
=> Fixes unit test reporter.

src/styles/components/charts/dialchart.less
=> DCOS-3619 fix dial chart spacing

src/js/components/modals/AddRepositoryFormModal.js
This will handle resetting state appropriately after errors have occurred in the modal
=> Resetting state appropriately after errors

src/js/components/StatusBar.js, src/js/components/__tests__/StatusBar-test.js
This does add a optional prop to the Status bar which may
contain a number. This number is then held for the 100%.
This feature adds the option to show a bar which is not filled.
=> Add the optional total prop to StatusBar component

src/js/components/FilterHealth.js, src/js/pages/NodesPage.js, src/js/pages/ServicesPage.js, src/js/pages/system/UnitsHealthTab.js, src/styles/components/filter-bar.less, src/styles/index.less
Creating specific styles for filter-bar situations.
=> Introduce filter-bar styles

src/js/components/ReviewConfig.js, src/js/components/modals/InstallPackageModal.js, src/js/components/modals/__tests__/InstallPackageModal-test.js, src/js/events/CosmosPackagesActions.js, src/js/events/__tests__/CosmosPackagesActions-test.js
=> Remove default service name and appId from default install, ref. DCOS-6411

src/js/components/charts/Bar.js
=> Making sure bar charts show 1px when value is 0

gulpfile.js, src/js/vendor/dygraph-combined.js
We're now using the a non-minified Dygraphs release, with a patched `Legend.prototype.select` method. Gets minified at build.
=> DCOS-6095: Use patched version of Dygraphs and minify it on build

src/js/utils/DOMUtils.js, src/js/utils/__tests__/DOMUtils-test.js
This method returns false if there are any elements covering it.
=> (1/2 optimize charts) Create DOMUtils#isElementOnTop

src/js/components/ServerErrorModal.js
=> Add close button to server error modal

src/js/components/PackageUpgradeOverview.js, src/js/components/PackagesTable.js, src/js/components/charts/UpgradeProgressBar.js, src/js/components/modals/UpgradePackageModal.js, src/js/structs/UniversePackage.js, src/styles/components/buttons.less, src/styles/components/dropdown-menus.less, src/styles/components/progressbar.less, src/styles/components/tables.less
=> DCOS-5673: Upgrade package confirmation

src/js/components/HealthTab.js, src/js/components/TaskView.js, src/js/pages/NodesPage.js, src/js/pages/ServicesPage.js, src/js/pages/system/OrganizationTab.js, src/js/pages/system/RepositoriesTab.js, src/js/pages/system/UnitsHealthTab.js, src/js/plugin-bridge/PluginModules.js
Wrapping all filter bars with `FilterBar` component for consistent handling of wrapping and margins.
Depends on https://github.com/dcos/dcos-ui/pull/47.
=> Use FilterBar component

src/styles/layout/panel.less
Explicitly set height on dashboard panels for IE to render the graphs.
=> DCOS-6128: Fix dashboard panel graphs

src/js/components/FilterButtons.js, src/js/components/ServiceDetail.js, src/js/components/TaskTable.js, src/js/components/TaskView.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/TaskTable-test.js, src/js/stores/MesosStateStore.js, src/js/stores/__tests__/MesosStateStore-test.js
Add a service detail task list which either displays a list of framework tasks including the scheduler tasks or a list of Marathon application tasks.
=> Feature - Add service detail task list

src/js/pages/NodesPage.js, src/js/pages/system/UnitsHealthTab.js
|  Before 	|  After  	|   
|:-:	|:-:	|
|  <img width="798" alt="screen shot 2016-04-27 at 18 24 31" src="https://cloud.githubusercontent.com/assets/647035/14859655/6988059c-0ca5-11e6-8718-0de949f6246d.png"> 	|  <img width="799" alt="screen shot 2016-04-27 at 18 22 35" src="https://cloud.githubusercontent.com/assets/647035/14859654/696fb154-0ca5-11e6-8a5d-77e4a087a5d7.png">
|
=> Fix nodes and units filter button styling

src/js/components/HealthBar.js, src/js/components/StatusBar.js, src/js/components/__tests__/HealthBar-test.js, src/js/constants/HealthBar.js
This adds a `HealthBar` component which wraps the `StatusBar` with a `Tooltip` and generates the text content for the tooltip.
The styling is part of #61
=> Feature - add healthbar component

src/js/utils/DOMUtils.js, src/js/utils/__tests__/DOMUtils-test.js
Going to use this instead of `offsetTop` for cross browser compatibility
=> Implement DOMUtils#getDistanceFromTopOfParent

src/js/plugin-bridge/PluginTestUtils.js
NOTE: Tests will fail till we merge into feature branch
=> [4] Remove deprecated testutil

src/js/components/Header.js, src/js/components/PageHeader.js
Introducing a `Header` component to wrap a very common layout pattern: icon aligned with title and subtitle and divider bar.
=> [Feature] Introduce Header layout component

src/js/pages/ServicesPage.js, src/js/pages/services/ServicesTab.js, src/js/stores/MarathonStore.js, src/js/structs/Tree.js, src/js/structs/__tests__/ServiceTree-test.js
Bring the filter properties into a better location.
Separation of concerns.
=> Remove filter propeties from marathon store

src/js/pages/DashboardPage.js, tests/pages/dashboard/ComponentsList-cy.js, tests/pages/dashboard/ServicesList-cy.js
Fixes integration tests that broke in #97
=> Fix ServiceList and ComponentList integration tests

src/js/components/FilterByTaskState.js, src/js/components/HealthTab.js, src/js/components/TaskTable.js, src/js/components/TaskView.js, src/js/components/UnitHealthDropdown.js
Allows for more control over component classes, requested here: https://github.com/dcos/dcos-ui/pull/56#discussion_r61338091
Depends on https://github.com/dcos/dcos-ui/pull/56
=> Remove inverseStyle Prop

webpack/webpack.dev.babel.js
Trigger the webpack notifier on rebuilds, not only on initial build.
The new setup is working fine on Linux btw! Thx @MatApple
=> Trigger webpack notify on rebuilds

src/js/components/charts/Rect.js, src/js/components/charts/TimeSeriesChart.js
=> Do not make masks slow to show

src/js/components/__tests__/ServiceInfo-test.js
The failing tests lacked some initializing data.
=> Fix service info test

src/js/config/Config.js, tests/_fixtures/secrets/backend.json, tests/_fixtures/secrets/policies.json, tests/_fixtures/secrets/policy.json, tests/_fixtures/secrets/secret.json, tests/_fixtures/secrets/secrets.json, tests/_fixtures/secrets/store-initialization-status.json, tests/_fixtures/secrets/store-seal-status.json, tests/_fixtures/secrets/stores.json
created fixtures according to [this](https://github.com/mesosphere/dcos-security/blob/master/secrets/docs/apispec-swagger.yaml)
=> Create fixtures for secrets

src/js/components/ServiceOptions.js, src/js/components/modals/InstallPackageModal.js, src/js/components/modals/UpdateConfigModal.js, src/js/structs/UniversePackage.js, src/js/structs/__tests__/UniversePackage-test.js
=> [2 of n] DCOS-6523: Add config modal

src/js/components/CheckboxTable.js, src/js/plugin-bridge/PluginModules.js
Creating a reusable table for tables with checkboxes
=> Create checkbox table

.webpack.config.js, jest/gen-config.js, npm-shrinkwrap.json, package.json, plugins/tracking/actions/Actions.js, src/js/components/NodesGridView.js, src/js/components/ServiceList.js, src/js/components/__tests__/NodesGridDials-test.js, src/js/components/charts/BarChart.js, src/js/components/charts/TasksChart.js, src/js/components/charts/TimeSeriesChart.js, src/js/components/charts/TimeSeriesLabel.js, src/js/pages/Index.js, src/js/plugin-bridge/__tests__/AppReducer-test.js, src/js/plugin-bridge/__tests__/PluginSDK-test.js, src/js/stores/MetadataStore.js, src/js/utils/__tests__/StructUtil-test.js
What it says on the box. Also removes underscore package (!!!)
Depends on https://github.com/dcos/dcos-ui/pull/90, review that first please! The last ~~two~~ three commits of this PR are the relevant ones.
=> Replace underscore isEqual with deepEqual

src/js/utils/__tests__/Util-test.js
=> Add Util tests

src/js/structs/ServicePlanBlocks.js, src/js/structs/ServicePlanPhase.js, src/js/structs/__tests__/ServicePlanBlocks-test.js, src/js/structs/__tests__/ServicePlanPhase-test.js
This will be used in a future PR
=> Add ServicePlanBlocks struct

src/js/plugin-bridge/PluginModules.js, src/styles/layout/media-object.less
This PR makes dropdown work for media-object items and adds `Tree` to the plugin bridge
=> Permissions builder, ref. DCOS-6724

src/js/components/ServiceOverlay.js, src/js/components/ServicesBreadcrumb.js, src/js/components/Sidebar.js, src/js/pages/DashboardPage.js, src/js/pages/ServicesPage.js, src/js/routes/services.js
NB: this PR depends on #153
Before:
After:
=> Fix services/deployments tab highlighting

src/js/constants/ServicePlanStatusDisplayText.js, src/js/structs/ServicePlanBlock.js, src/js/structs/__tests__/ServicePlanBlock-test.js
* Return human readable display text
* Default to the server-returned status
=> [3 of 5: Configuration Updates] Add getStatus to ServicePlanBlock structs

src/js/pages/services/ServicesTab.js
This PR depends on https://github.com/dcos/dcos-ui/pull/172
Please merge #172 first!
edit from kenny: #172 is merged
=> Add CTA buttons when browsing an empty service group

gulpfile.js, npm-shrinkwrap.json, package.json
We are avoiding dependencies with a GPL license.
This PR adds a way to programmatically check and ensure we don't have any with a GPL license.
=> Test dependencies for licenses that we don't want.

src/js/components/ToggleButton.js, src/js/plugin-bridge/PluginModules.js, src/styles/components/toggle-button.less, src/styles/index.less, src/styles/variables/variables-toggle-button.less
This introduced a toggle button to use as a module in external plugins
=> Add ToggleButton

src/js/components/ServicePlanBlockDetails.js, src/js/components/modals/ServicePlanProgressModal.js, src/js/components/modals/ServicePlanProgressModalContents.js, src/styles/components/service-plan-progress-modal.less, src/styles/index.less
This modal will display the progress of a plan (which is present for both service upgrade and configuration update plans), including the phases of the plan and the individual blocks within each phase.
=> [4 of 8: Service Updates & Upgrades] Introduce ServicePlanProgressModal

src/js/stores/DCOSStore.js, src/js/stores/__mocks__/MesosSummaryStore.js, src/js/stores/__tests__/DCOSStore-test.js
Pull the data from the stores, as the` MesosSummaryStore` doesn't provide the state summary as payload.
=> Fix DCOSStore data handling

src/js/components/Breadcrumb.js, src/styles/components/breadcrumbs.less
This is largely inspired by the awesome Marathon Breadcrumb component but abstracted to work dynamically on top of react-router.
=> Breadcrumb Component

src/js/utils/DOMUtils.js, src/js/utils/__tests__/DOMUtils-test.js
=> Fix isElementAtTop

src/js/stores/DCOSStore.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js
Integrate the Marathon version/config data. This will lay the foundation for the service detail configuration tab. These commits are cherry picked from #155 in order to reduce the PR size.
=> Integrate Marathon version/config data

src/js/stores/DCOSStore.js, src/js/stores/__tests__/DCOSStore-test.js
Process and merge service version data. This commit is cherry picked from #155 in order to reduce the PR size.
=> Incorporate service version data

src/js/components/ConfigurationView.js, src/js/components/__tests__/ConfigurationView-test.js, src/js/utils/StringUtil.js, src/js/utils/__tests__/StringUtil-test.js, src/styles/components/description-list.less, src/styles/index.less
---
ℹ️   _This branch depends on changes that will be introduced with #236, thus it will fail until the respective branch is merged._
---
Introduce a config/version view. This component will be used in the service detail configuration tab. These commits are cherry picked from #155 in order to reduce the PR size.
_Integrated config view_
=> Add a configuration view

src/js/components/ServiceDetail.js, src/js/components/ServiceDetailConfigurationTab.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceDetailConfigurationTab-test.js
---
ℹ️   _This branch depends on changes that will be introduced with #221, thus it will fail until the respective branch is merged._
---
Introduce a service detail configuration tab. These commits are cherry picked from #155 in order to reduce the PR size.
_Integrated config view_
=> Add service detail configuration tab

src/js/components/Sidebar.js, src/js/mixins/TabsMixin.js, src/js/pages/SystemPage.js, src/styles/components/tabs.less
you won't be able to reproduce this on your own, but that's what it looks like. i'd be open to comments on the implementation. sidebar badge still needs help with css
=> Show notifications in tabs

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
Introduce basic job struct – this struct will be used to type and abstract the Chronos API response.
=> Introduce job struct

src/js/components/NodesGridDials.js, src/js/components/SidePanelContents.js, src/js/components/TaskDetail.js, src/js/components/__tests__/NodesGridDials-test.js, src/js/components/charts/ResourceBarChart.js, src/js/components/charts/ResourceChart.js, src/js/constants/ResourceTypes.js, src/js/utils/ResourcesUtil.js, src/js/utils/__tests__/ResourcesUtil-test.js
Mesos will be adding support for GPU resource, which breaks the UI.
This pull request introduces support for any resource that Mesos adds in the future. Currently it doesn't actually show the unknown resources anywhere in the UI. So this is the minimal amount of work needed so that the UI doesn't crash when new resources are added.
=> Adds support for any resource type that mesos supports now and in the future

src/js/structs/List.js, src/js/structs/ServiceTree.js, src/js/structs/Tree.js, src/js/utils/UnitHealthUtil.js, src/js/utils/Util.js, src/js/utils/__tests__/Util-test.js
Remove `Util.isArray` and `Util.find` as there is no longer any need for them.
=> Remove obsolete util methods

npm-shrinkwrap.json, package.json, src/js/components/SidebarFilter.js
Additions:
mesosphere/reactjs-components#180 – Adds ability to render disabled checkbox.
mesosphere/reactjs-components#260 - Add FieldSelect component
mesosphere/reactjs-components#257 - Added support for focus for input fields with type "text" in the Form component
Changes
mesosphere/reactjs-components#180 – Moved FieldCheckbox to FieldCheckboxMultiple, and created a new FieldCheckbox that only renders one checkbox.
=> Updating reactjs components

src/js/stores/NodeHealthStore.js
=> [ES6 class] Update NodeHealthStore to es6 class

src/js/stores/CosmosPackagesStore.js
=> [ES6 class] Update CosmosPackagesStore to es6 class

src/js/components/MarathonTaskDetailsList.js
Display the local time in the task detail list
=> Use timefield for date

src/js/stores/MesosLogStore.js
=> [ES6 class] Update MesosLogStore to es6 class

src/js/stores/MetadataStore.js
=> [ES6 class]  Update MetadataStore to es6 class

src/js/stores/UnitHealthStore.js
=> [ES6 class] Update UnitHealthStore to es6 class

src/js/stores/NotificationStore.js
=> [ES6 class] Update NotificationStore to es6 class

src/js/stores/ConfigStore.js
=> [ES6 class] Update ConfigStore to es6 class

src/js/stores/UsersStore.js
=> [ES6 class] Update UsersStore to es6 class

src/js/components/MarathonTaskDetailsList.js
=> Adjust task detail styles

src/js/components/MarathonTaskDetailsList.js, src/js/components/TaskDetail.js
This is a preliminary PR to be able to extend the Marathon task details in a meaningful and clean way.
Please merge https://github.com/dcos/dcos-ui/pull/263 before.
=> Refactor Marathon task details into own component

src/js/stores/TaskDirectoryStore.js
=> [ES6 class] Update TaskDirectoryStore to es6 class

src/js/components/Sidebar.js, src/js/mixins/TabsMixin.js, src/js/pages/SystemPage.js, src/styles/components/tabs.less, src/styles/layout/page.less, src/styles/layout/sidebar.less
=> Style notifications

src/js/stores/UserStore.js
=> [ES6 class]  Update UserStore to es6 class

src/js/stores/SidebarStore.js
=> [ES6 class] Update SidebarStore to es6 class

src/js/stores/MesosStateStore.js
=> [ES6 class] Update MesosStateStore to es6 class

src/styles/components/login-modal.less, src/styles/index.less, src/styles/layout/modal.less
This separates the login modal styles from the generic modal.
=> Move Login Modal styles to separate component

src/js/stores/MarathonStore.js
=> [ES6 class] Update MarathonStore to es6 class

src/js/stores/HistoryStore.js
=> [ES6 class] Update HistoryStore to es6 class

src/js/stores/AuthStore.js
=> [ES6 class] Update AuthStore to es6 class

src/js/stores/VisibilityStore.js
=> [ES6 class] Update VisibilityStore to es6 class

src/js/stores/ChronosStore.js
Adjust the ChronosStore visibility change handling to fix reference errors.
=> Fix ChronosStore visibility change handling

src/js/stores/MarathonStore.js, src/js/stores/__tests__/MarathonStore-test.js
Add getter for storeID on MarathonStore
=> Add getter for storeID on MarathonStore

src/js/stores/MesosSummaryStore.js
=> [ES6 class] Update MesosSummaryStore to es6 class

npm-shrinkwrap.json, package.json
Changes:
- https://github.com/mesosphere/reactjs-components/pull/275 - Pass through all data on change in Form FieldSelect
- https://github.com/mesosphere/reactjs-components/pull/276 - Change Form updating to delete fields that are no longer part of the definition.
=> Updating reactjs-components to 0.14.0-beta.24

src/js/stores/__tests__/MarathonStore-test.js
=> Fix MarathonStore test linting errors

src/js/constants/VolumeStatus.js, src/js/constants/VolumeTypes.js, src/js/structs/Volume.js, src/js/structs/VolumeList.js, src/js/structs/__tests__/Volume-test.js
These structs they will be used to provide a nice API to deal with service volumes.
=> Introduce volume structs

src/js/components/ClipboardTrigger.js, src/js/components/ClusterHeader.js, src/js/plugin-bridge/PluginModules.js
Everything works the same. It is now a component that can be reused.
=> Create ClipboardTrigger component

src/js/structs/__tests__/Service-test.js
=> Fix service struct test linting

src/js/components/modals/ServiceFormModal.js
This is a refactoring to make the edit form acceptable.
=> Refactor edit implementation

src/js/structs/ServiceTree.js, src/js/structs/Tree.js
This is a follow-up to #330 
While not being an exhaustive solution, it introduces a slightly more meaningful separation of concerns between Tree and ServiceTree.
=> Extract method from Tree for decoupling

tests/_fixtures/OpenIDAuthProviders/provider.json
Minor edit to fixture for consistency.
=> Fix fixture

src/styles/components/buttons.less, src/styles/layout/modal.less
=> Add styles for modal button icons

src/styles/components/multiple-form.less
=> Add common styles for multiple-form, permission-form and review-config

src/js/components/ServiceDetail.js, src/js/components/ServiceInfo.js, src/js/components/modals/ServiceFormModal.js, src/js/constants/ServiceActionItem.js
This opens the service edit modal if I click on the edit button.
@Poltergeist Thanx!
=> Feature - 1066 Service actions - Open edit modal

src/js/components/SchemaForm.js, src/js/components/TabForm.js
you can now create a form with tabs on the left and a selected form on the right without having to do anything with a schema.
=> Refactor SchemaForm into SchemaForm/TabForm

src/js/components/AccessDeniedPage.js
=> Fix Access Denied page auth documentation link

src/js/events/MarathonActions.js, src/js/structs/Service.js, src/js/structs/TaskStat.js, src/js/structs/TaskStats.js, src/js/structs/__tests__/Service-test.js, src/js/structs/__tests__/TaskStat-test.js, src/js/structs/__tests__/TaskStats-test.js
Introduce service task stats - this is needed to implement the service debug tab.
/cc @mlunoe
=> Introduce service task stats

src/js/components/ServiceDetail.js, src/js/components/ServiceDetailVolumesTab.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceDetailVolumesTab-test.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js
--- 
~~⚠️  This branch is still work in progress – don't merge! It also depends on features that will be introduced with #327, thus it will not work until the respective branch is merged.~~
---
Introduce a service volumes tab to display all the volumes that are linked to a service. 
/cc @kennyt
=> Introduce service volumes tab

src/styles/components/buttons.less
Split's button text and the :after.
=> Split button content

src/js/plugin-bridge/PluginModules.js
Add ProgressBar to PluginModules
=> Expose progressbar

src/js/structs/Job.js, src/js/structs/JobTree.js, src/js/structs/__tests__/Job-test.js, src/js/structs/__tests__/JobTree-test.js
---
ℹ️  You will need the updated parsing introduce in #360 to properly test this update.
---
Adjust the Job and JobTree id/name handling, to reflect the latest API advancements.
/cc @jfurrow
=> Update Job and JobTree id/name handling

src/js/components/modals/ServiceScaleFormModal.js
This enables the service scale dialog and triggers the actual scale action. Engage!
=> 1066 - Enable service scale action with error handling

src/js/components/modals/JobFormModal.js, src/js/pages/jobs/JobsTab.js
---
ℹ️ This branch depends on features that will be introduced with #374, thus it will fail until the respective branch is merged.
---
Introduce the a first version of the create job modal. This version only features the json editor. I'll add the missing features during the next iteration.
=> Introduce create job modal

src/js/schemas/service-schema/ContainerSettings.js, src/js/utils/ServiceUtil.js
Add the `Parameters` section to the container settings section.
=> Add container parameters to the create modal

src/js/schemas/ServiceSchema.js, src/js/schemas/service-schema/Labels.js, src/js/utils/ServiceUtil.js
This adds the functionality to add Labels in the create modal.
=> Add labels section to the service form modal

src/js/structs/Job.js, src/js/structs/JobActiveRun.js, src/js/structs/JobActiveRunList.js, src/js/structs/JobTask.js, src/js/structs/JobTaskList.js, src/js/structs/__tests__/Job-test.js, src/js/structs/__tests__/JobActiveRun-test.js, src/js/structs/__tests__/JobActiveRunList-test.js, src/js/structs/__tests__/JobTask-test.js, src/js/structs/__tests__/JobTaskList-test.js, src/js/utils/DateUtil.js, src/js/utils/__tests__/DateUtil-test.js
Tests pass locally, but Jenkins is grumpy.
Integration tests:
Unit tests:
=> [Job Details] Add job structs for job detail page

src/js/components/PageHeader.js, src/js/pages/nodes/NodeDetailPage.js
Updating Node detail page to use `PageHeader` for component standardization \o/
=> Use PageHeader in Node Detail Page

src/js/utils/ServiceUtil.js
=> Fix labels error if no label is provided

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
=> Add memory getter to the Job struct

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
=> Add disk getter to Job struct

npm-shrinkwrap.json, package.json
=> Bump rjsc to beta.27

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
Handle undefined run configuration properly.
/cc @jfurrow
=> Fix Job command getter

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
=> Add Job lables getter

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
=> Add Job cpus getter

src/js/components/ConfigurationView.js, src/js/components/DescriptionList.js, src/js/components/ServiceDetail.js, src/js/components/ServiceDetailDebugTab.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/pages/nodes/NodeDetailPage.js, src/js/pages/services/ServicesTab.js, src/styles/components/description-list.less
Desktop:
Mobile:
Task with no statistics (the scenario will happen for each section, when information is not available):
Note: The table in the images will be added in an upcoming PR.
=> [1 of 2 Debug Tab] Add service debug tab

tests/pages/services/ServiceActions-cy.js
This adds the integration tests for edit, scale, suspend and destroy actions buttons…
Related PR #390
=> 1066 - Integration tests for edit, scale, suspend and destroy actions

src/js/pages/services/DeploymentsTab.js, src/styles/components/deployments-table.less
Context: https://github.com/dcos/dcos-ui/pull/412#discussion_r66895216
=> [10] Deployments Table - Replace breadcrumbs with nested services links

src/js/pages/services/DeploymentsTab.js
Context: https://github.com/dcos/dcos-ui/pull/412#discussion-diff-66894844
=> [11] Deployments Table - Use store mixin forced updates instead of react lifecycle

src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
=> Add Job docker getter

src/js/structs/__tests__/Job-test.js
=> Fix job struct test styling

src/js/components/ServiceList.js, src/js/components/__tests__/ServiceList-test.js, src/js/pages/DashboardPage.js, src/js/pages/__tests__/DashboardPage-test.js, src/js/pages/__tests__/fixtures/MockMarathonResponse.json, src/js/routes/services.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/ServiceTree-test.js
---
ℹ️ Follow up PR for this PR: https://github.com/dcos/dcos-ui/pull/418
---
=> Bug: make service list show services and link to their detail page

src/js/plugin-bridge/PluginModules.js
Allow plugins to use `TabForm`
=> Expose TabForm

src/js/components/TabForm.js
Allow these static classes to be overridden.
=> Use classnames/dedupe in TabForm

src/js/utils/JobUtil.js, src/js/utils/__tests__/JobUtil-test.js
---
ℹ️   _This branch depends on features that will be introduced with #396 and #420, thus it will fail until the respective branches get merged._
---
This util is used to create job specs from job structs as well as to create from models from jobs and respective form schemas.
=> Introduce job util

src/js/constants/JobStates.js, src/js/constants/TaskStates.js, src/js/events/ChronosActions.js, src/js/pages/__tests__/JobsTab-test.js, src/js/pages/jobs/JobConfiguration.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/jobs/JobsTab.js, src/js/pages/jobs/JobsTable.js, src/js/routes/jobs.js, src/styles/components/buttons.less, src/styles/components/jobs-view.less, src/styles/components/typography.less, src/styles/index.less, tests/_fixtures/chronos/job.json, tests/_fixtures/chronos/jobs.json, tests/_support/spec_helper.js, tests/pages/jobs/JobDetails-cy.js
=> [Job Details] Job Detail View

src/js/components/modals/JobFormModal.js, src/js/schemas/JobSchema.js, src/js/schemas/job-schema/Docker.js, src/js/schemas/job-schema/General.js, src/js/schemas/job-schema/Labels.js, src/js/schemas/job-schema/Schedule.js
---
ℹ️   _This branch depends on features that will be introduced with ~~#396~~ merged, ~~#420~~ merged, ~~#421~~, ~~#422~~ merged, and ~~#423~~ merged thus it will fail until the respective branches get merged._
---
Integrate job form and add job form schemas to provide ans easy to use form alongside the json editor.
=> Integrate job form

src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobRunHistoryTable.js
Add condition to handle undefined properties.
=> Handle undefined properties

src/js/components/SchemaForm.js, src/js/components/ServiceForm.js, src/js/plugin-bridge/PluginModules.js, src/js/schemas/ServiceSchema.js, src/js/schemas/service-schema/EnvironmentVariables.js, src/js/utils/FormUtil.js, src/js/utils/ServiceUtil.js
Depends on https://github.com/dcos/dcos-ui/pull/428
=> Environment variables tab

src/js/components/SchemaForm.js, src/js/components/TabForm.js, src/styles/layout/foundation.less
README:
The reason that we don't have the 100% correct icons for these is because we're going to be doing an icon overhaul soon and we'll use the correct ones then :)
=> Style duplicable rows

src/js/components/modals/ServiceFormModal.js
This adds a performance hotfix which has been created by @orlandohohmeier.
=> Add performance boost

src/js/config/Config.js, src/js/events/MarathonActions.js, src/js/events/MesosSummaryActions.js, src/js/events/MetadataActions.js, src/js/events/__tests__/MarathonActions-test.js, src/js/events/__tests__/MesosSummaryActions-test.js, src/js/plugin-bridge/AppHooks.js, src/js/stores/DCOSStore.js
This gets Alice a bit closer to accessing DCOS UI.
We still need to figure out how we redirect the a user who doesn't have access to the dashboard.
=> Get Alice closer to accessing the services page.

src/js/pages/universe/PackageDetailTab.js, src/js/routes/universe.js
=> Add breadcrumbs to universe

src/js/components/modals/JobFormModal.js
=> Improve job modal styling

src/js/constants/JobStates.js, src/js/constants/TaskStates.js, src/js/stores/__tests__/ChronosStore-test.js, tests/_fixtures/chronos/job.json, tests/_fixtures/chronos/jobs.json, tests/pages/jobs/JobDetails-cy.js, tests/pages/jobs/JobsOverview-cy.js
Align fixtures with latest API advancements.
/cc @daiyiwhale @jfurrow
=> Update chronos fixtures

src/js/components/SchemaForm.js, src/js/components/modals/ServiceFormModal.js, src/js/constants/VolumeConstants.js, src/js/schemas/ServiceSchema.js, src/js/schemas/service-schema/Volumes.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
This adds the support for the volumes tab.
=> Add Volumes section to the service form

src/js/plugin-bridge/Loader.js
This PR creates loaders that will expose the icon directories for consumption by plugins in the near future.
=> Create plugin loaders for icons

src/js/pages/services/ServicesTab.js, tests/_fixtures/chronos/jobs.json, tests/pages/services/ServicesTab-cy.js
=> Show service not found

src/js/components/Sidebar.js, src/js/pages/NetworkPage.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/VirtualNetworksTable.js, src/js/routes/factories/network.js, src/js/routes/index.js
=> Adding Network Page and Virtual Networks Overview

src/js/components/modals/JobFormModal.js, src/js/pages/jobs/JobDetailPage.js, tests/pages/jobs/JobActions-cy.js
=> Introduce edit job modal

src/js/pages/jobs/JobDetailPage.js
Use the proper method to suspend a job (schedule). Let me add that we have to and will revisited the Chronos actions as their partially confusing.
=> Fix suspend job action

src/js/components/modals/__tests__/InstallPackageModal-test.js, src/js/utils/SchemaFormUtil.js
=> Fix schema form warnings

src/js/config/Config.js, src/js/events/MetronomeActions.js, src/js/events/__tests__/MetronomeActions-test.js
Adjust the Metronome URLs to match the latest configuration adjustments.
=> Update metronome URLs

src/js/components/HealthBar.js, src/js/components/TabForm.js
=> Make necessary tooltips interactive

src/js/pages/services/DeploymentsTab.js
=> Dont capitalize deployments table

src/js/components/SchemaForm.js, src/js/schemas/service-schema/Volumes.js, src/js/utils/ServiceUtil.js, src/styles/components/multiple-form.less
=> Polish volumes section

npm-shrinkwrap.json, package.json, src/js/components/SchemaForm.js, src/js/components/ServiceForm.js, src/js/components/TabForm.js, src/js/components/modals/ServiceFormModal.js, src/js/schemas/ServiceSchema.js, src/js/schemas/service-schema/HealthChecks.js, src/js/utils/SchemaFormUtil.js, src/js/utils/SchemaUtil.js, src/js/utils/ServiceUtil.js, src/styles/components/multiple-form.less
- Has issues with preserving order of healthchecks. Altering the last healthcheck will re-render that healthcheck at the top. @kennyt is working on a fix for this.
- Haven't added required fields/client-side validation. cc/ @orlandohohmeier @pierlo-upitup. If it needs it, lets create a follow up PR for that.
=> Add Health Checks to ServiceFormModal

src/js/components/DescriptionList.js, src/js/constants/StoreConfig.js, src/js/pages/SystemPage.js, src/js/pages/system/OverviewDetailTab.js, src/js/routes/factories/system.js
=> Add system details tab

src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/routes/jobs.js
---
ℹ️   _This branch depends on features that will be introduced with ~~#494~~, thus it will fail until the respective branches get merged._
---
Add the necessary routes and links for the jobs task detail view.
=> Implement jobs task detail

src/js/components/ServiceInfo.js
=> Fix ServiceInfo actions margins

src/js/components/Icon.js, src/js/components/SidebarLabelsFilter.js
=> Use x icon for ServiceTable label filter instead of 'x' character

src/js/components/SchemaForm.js, src/js/utils/ServiceUtil.js
This also fixes the problem of adding a new row at the top of the form if no row was present.
=> Fix docker volumes

src/js/schemas/ServiceSchema.js, src/js/schemas/service-schema/Networking.js, src/js/structs/Service.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
This PR builds on the work done by me and @Poltergeist on the apps modal. 
Recent work includes the transform from networking modal model to service.
=> Virtual Networks

src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/jobs/JobsTab.js, src/js/routes/jobs.js
---
⚠️    _This branch includes features that will be introduced with #495, please only review 830a63f, 	2981a41, and c0af0a4_
---
Add breadcrumbs to the job views.
=> Integrate breadcrumbs into the job views

src/js/components/ServicesTable.js, src/styles/components/service-table.less, src/styles/components/side-list.less, src/styles/components/statusbar.less, src/styles/components/tables.less, src/styles/index.less, src/styles/layout/sidebar.less
I consulted with @ashenden and this is where I landed:
Integration tests:
=> DCOS-7884: Adjust responsiveness of ServicesTable layout

src/js/components/BreadcrumbSegmentLink.js, src/js/components/Breadcrumbs.js, src/js/components/ManualBreadcrumbs.js, src/js/pages/task-details/TaskFilesTab.js
=> Create ManualBreadcrumbs and use for task directory

src/js/components/SchemaForm.js, src/js/schemas/service-schema/ContainerSettings.js, src/js/schemas/service-schema/Volumes.js, src/js/utils/SchemaUtil.js
This also makes it so that the `Add New X` button isn't completely flush against the bottom
=> Allow duplicable rows to have titles

src/js/components/ServicesTable.js, src/js/pages/services/ServicesTab.js
=> Implement service search/filter view

src/js/schemas/service-schema/ContainerSettings.js, src/js/schemas/service-schema/Networking.js
=> Add titles to labels in service form - ref: DCOS-7978

src/js/components/modals/ServiceFormModal.js
This fixes the failing ci test on master.
=> Fix service Versions edit form to contain right values

src/js/schemas/service-schema/HealthChecks.js, src/js/utils/ServiceUtil.js
CI passes except one test which I will address in another PR. => #538
=> Fix command healthchecks

src/js/pages/services/ServicesTab.js
=> Include breadcrumbs in empty service view

src/js/schemas/service-schema/ContainerSettings.js, src/js/schemas/service-schema/Networking.js, src/js/structs/Service.js, src/js/structs/__tests__/Service-test.js, src/js/utils/ServiceUtil.js
=> Fix parsing of service to form in networking section

src/js/components/StatusBar.js, src/js/components/__tests__/StatusBar-test.js, src/styles/components/statusbar.less
This fixes the issue in the image:
Images of the solution:
=> DCOS-7627 Fix healthbar transform bug

src/js/pages/task-details/TaskDetail.js, src/js/pages/task-details/TaskLogsTab.js, src/js/pages/task-details/__tests__/TaskLogsTab-test.js, src/js/routes/factories/network.js, src/js/routes/jobs.js, src/js/routes/nodes.js, src/js/routes/services.js
=> Clicking on the magnifying glass links to logs again

src/styles/components/dropdown-menus.less
=> Fix transparent inverse dropdown background

src/js/components/SchemaForm.js, src/js/utils/SchemaUtil.js
=> Allow SchemaForm to render tooltip in subheader

src/js/schemas/service-schema/Volumes.js
=> Add titles for each type of volume

src/styles/components/deployments-table.less, src/styles/layout/page.less
Explicitly set flex properties of `page-navigation`.
=> Prevent page-navigation element from shrinking

npm-shrinkwrap.json, package.json, plugins/oauth/components/UserDropup.js, src/js/components/modals/ImageViewerModal.js, src/js/components/modals/InstallPackageModal.js, src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js, src/styles/components/login-modal.less
This updates `reactjs-components` and changes all implementations of the `Modal` as needed.
I removed a bunch of custom CSS for the login form, which was but there to remove padding from the outer container and add it to the inner container. The new `Modal` component does this out of the box.
=> Update reactjs-components & affected components

src/js/pages/ServicesPage.js, src/js/stores/DCOSStore.js
=> Update notification count on change

src/js/pages/task-details/TaskDetail.js, src/js/routes/factories/network.js, src/js/routes/jobs.js, src/js/routes/nodes.js, src/js/routes/services.js
=> Store directory path in params

src/js/components/SchemaForm.js, src/js/utils/SchemaUtil.js
=> Deleting duplicable rows and re-adding them works

src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/styles/components/page-header.less
Before:
After:
The health icon needs some love and will be fixed in a separate PR.
=> Replace icon on UnitsHealthDetail

src/js/components/KillTaskModal.js, src/js/components/TaskTable.js, src/js/components/TaskView.js
This is just the view part. Actions will come next
=> [#1 Kill Tasks functionality] Create task kill views

src/js/components/SchemaForm.js, src/js/components/ServiceForm.js, src/js/schemas/service-schema/Networking.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
=> Fetch service network options

src/js/events/TaskDirectoryActions.js, src/js/pages/task-details/TaskDetail.js
Fixed some javascript errors. Also the error screen wasn't being rendered, oops
(DCOS-7859)
=> Bug - Task Detail view errors

src/js/components/HealthTab.js
=> Remove redundant health check title

src/js/components/SchemaForm.js, src/js/schemas/service-schema/HealthChecks.js, src/js/utils/SchemaFormUtil.js, src/js/utils/SchemaUtil.js, src/styles/components/multiple-form.less
=> Add option for title between duplicable rows

src/js/components/ServerErrorModal.js, src/js/events/MesosLogActions.js, src/js/events/TaskDirectoryActions.js, src/js/events/__tests__/MesosLogActions-test.js, src/js/stores/MarathonStore.js, tests/_fixtures/1-service-with-executor-task/browse.json, tests/_fixtures/1-service-with-executor-task/slave-state.json, tests/_support/spec_helper.js
=> Rename /slave to /agent

src/js/components/HealthBar.js, src/js/constants/HealthBarStates.js, src/js/structs/Service.js, src/js/structs/ServiceTree.js, src/js/structs/__tests__/Service-test.js, src/js/structs/__tests__/ServiceTree-test.js, src/styles/components/badges.less, src/styles/components/progressbar.less
‼️ Caution the image does not represent real data !!
This adds the functionality for over capacity to the code.
I had to adjust some tests and fix some strings.
18 * 💯 
Waiting for ci
=> Add over capacity to tasksSummary

src/js/schemas/job-schema/Schedule.js
=> Add checkbox to enable job schedules

src/js/pages/Index.js
=> Do not unmount store on Index unmount

src/js/pages/JobsPage.js, src/js/pages/jobs/JobsTab.js
=> Force Job log viewer to fit window height

src/js/utils/HostUtil.js, src/js/utils/__tests__/HostUtil-test.js
Port [this script](https://github.com/dcos/mesos_state/blob/master/src/mesos_state.erl#L101-L118) to a util
=> Add Host Util to parse valid hostnames

src/js/pages/jobs/JobConfiguration.js
=> Add job configuration sections

src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js
This adds the error message parsing from the service form also to the jobs form
=> DCOS-8168: Copy Error message parsing from service to job

src/js/components/modals/ServiceFormModal.js
This enables force update while in JSON mode.
=> Fix JSON mode force deploying in edit modal

src/js/components/modals/JobFormModal.js, src/js/utils/JobUtil.js
=> Let server validate job schedules

src/js/constants/JobStates.js, src/js/structs/Job.js, src/js/structs/__tests__/Job-test.js
=> Create unscheduled status for jobs

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
=> Revert "Ensure ports are only added if either name or lbPort is set"

src/js/utils/ServiceUtil.js, src/js/utils/__tests__/ServiceUtil-test.js
=> Revert "Revert "Ensure ports are only added if either name or lbPort is set""

cypress.json, tests/_fixtures/marathon-1-task/app-version-2.json, tests/_fixtures/mesos/overlay-master.json, tests/_support/spec_helper.js, tests/pages/jobs/JobDetails-cy.js, tests/pages/jobs/JobsOverview-cy.js, tests/pages/services/ServiceActions-cy.js, tests/pages/services/ServiceVersions-cy.js
This fixes some of the integration tests \o/
=> Fix integration tests

src/js/components/SchemaForm.js
=> Tooltips created from schema stay open

src/js/utils/DOMUtils.js, src/js/utils/__tests__/DOMUtils-test.js
Adds #closest from DOMUtil in [reactjs-components](https://github.com/mesosphere/reactjs-components/blob/master/src/Util/DOMUtil.js#L28-L40).
=> [1 of 2] Add DOMUtil#closest

src/js/components/SchemaForm.js
This will only improve the Advanced Install for Universe, but this improves performance by a huge amount
=> Validate on blur not change

src/js/pages/ServicesPage.js, tests/_fixtures/deployments/one-deployment.json, tests/_fixtures/marathon-1-group/kafka.json, tests/_support/spec_helper.js, tests/pages/services/DeploymentsTab-cy.js, tests/pages/services/ServicesTab-cy.js
=> Service page tabs become active correctly

src/js/components/modals/ServiceScaleFormModal.js
=> DCOS-8102: Change size of the scale Modal input field.

src/js/schemas/service-schema/ContainerSettings.js
=> Add helper text for configuring docker volumes and ports

src/js/components/SecretValue.js, src/js/components/__tests__/SecretValue-test.js, src/js/plugin-bridge/PluginModules.js, src/styles/components/secret-value.less, src/styles/index.less
Creating SecretValue component to be used internally and externally.
Reviewer: See external plugin branch of same name
=> Add secret value component

src/js/components/MarathonTaskDetailsList.js
This adds the missing Health Check Results table to the task detail page as is available in Marathon UI.
=> DCOS-8068 Add health check results table to task page

src/js/utils/SchemaFormUtil.js
This line of code does exactly the same thing as the one above it. I suspect rebase mistake
=> Remove duplicated code

src/js/pages/jobs/JobRunHistoryTable.js, tests/_fixtures/metronome/job.json, tests/pages/jobs/JobDetails-cy.js
Adjust the default sort behaviour and fix the job run history integration tests.
=> Fix job detail run history integration tests

src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/services/ServicesTab.js
=> Hide breadcrumb when Services Page is empty

src/js/components/TaskTable.js, src/js/constants/TaskStates.js, src/styles/components/badges.less, src/styles/components/tables.less, src/styles/components/typography.less
This adds the right coloring for task states:
=> DCOS-8071: Fix status dots in task detail

src/js/components/TaskTable.js, src/js/utils/ResourceTableUtil.js
Add an icon that links directly to logs tab.
=> DCOS-8098: Add log link to task table

src/js/pages/services/DeploymentsTab.js
This adds the deployment action to the deployment table.
=> DCOS-8447: Add deployment action to deployment table

src/js/constants/MesosConstants.js, src/js/structs/Job.js
Add dedicated Mesos constants, to have them all in one place.
=> Introduce Mesos constants

src/js/components/charts/TimeSeriesChart.js
=> Add a more unique key onto mask to fix weird mask animation

src/js/components/ServiceForm.js, src/js/components/TabForm.js, src/js/utils/FormUtil.js, src/js/utils/SchemaFormUtil.js, src/js/utils/SchemaUtil.js, src/js/utils/__tests__/FormUtil-test.js
This depends on:
https://github.com/mesosphere/reactjs-components/pull/303
This adds the functionality of validation for the schema forms. You'd create a field called `externalValidator` on the schema like this:
=> Service form validation foundation

src/js/schemas/service-schema/ContainerSettings.js, src/js/schemas/service-schema/EnvironmentVariables.js, src/js/schemas/service-schema/General.js, src/js/schemas/service-schema/HealthChecks.js, src/js/schemas/service-schema/Labels.js, src/js/schemas/service-schema/Networking.js, src/js/schemas/service-schema/Volumes.js
Note: I didn't add the edits for the following two fields because I didn't see them in the ContainerSettings file.
Tab: Container Settings
Heading: Container Image
Description: Configure your Docker container. Use DockerHub to find popular repositories.
Link: https://hub.docker.com/explore/
Tab: Container Settings
Heading: Docker Parameters
Description: Supply options for the `docker run` command executed by the Mesos containerizer.
Link: https://docs.docker.com/engine/reference/commandline/run/
=> Edits to Deploy modal

plugins/tracking/hooks.js, src/js/components/Modals.js, src/js/components/modals/CliInstallModal.js, src/js/components/modals/__tests__/CliInstallModal-test.js, src/styles/components/code.less, tests/_fixtures/1-service-with-executor-task/slave-state.json
=> Update CLI Instructions

npm-shrinkwrap.json, package.json
We are adding this package to the project for our typeahead needs: https://www.npmjs.com/package/react-bootstrap-typeahead
=> Add react-bootstrap-typeahead package

src/js/components/MesosLogView.js, src/js/components/modals/CliInstallModal.js, src/js/pages/task-details/TaskDetailsTab.js, src/styles/components/code.less, src/styles/layout/modal.less, src/styles/variables/variables-code.less
Integration tests passing on a frankie branch, which includes this branch:
=> Fix styling for pre code blocks

src/js/components/NestedServiceLinks.js
Capitalises 'Service' in deployment tab `location` column and also services tab search filter.
=> DCOS-8420 & DCOS-8446: Capitalise ‘Service’

src/js/components/SchemaForm.js, src/js/components/TabForm.js, src/styles/components/multiple-form.less
=> Adjust multiple-form headings

src/js/components/ServicesTable.js
=> Making sure services always show an icon in service table

src/js/components/ServicesTable.js, src/styles/components/service-table.less, src/styles/utilities/responsive-utilities.less
Additional responsiveness refactoring for the `ServicesTable` status bar.
https://cl.ly/0G1p1j0D2F2N
=> Refactor ServicesTable status bar responsiveness

src/js/components/TaskTable.js, src/js/constants/TaskTableHeaderLabels.js
Rename State to Status in TaskTable, for consistency across application.
=> DCOS-8430: Rename State to Status in TaskTable

src/styles/components/form-elements.less, src/styles/index.less
=> Increase textarea height

src/js/components/TaskTable.js, src/js/constants/TaskTableHeaderLabels.js
Reverts dcos/dcos-ui#701
This broke the Nodes UI.
=> Revert "DCOS-8430: Rename State to Status in TaskTable"

src/js/components/ServicesTable.js, src/js/components/TaskDirectoryTable.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/jobs/JobsTable.js, src/styles/components/jobs-view.less
Jobs icons:
3 integration tests failing on mater, same 3 failing here.
This branch:
Master:
=> Implement jobs icon and fix grey icon color

src/js/components/Sidebar.js, src/styles/components/application-loading-indicator.less, src/styles/components/user-dropdown-menu.less, src/styles/layout/foundation.less, src/styles/layout/sidebar.less
This PR changes the way we handle the sidebar's layout and animation. It animates the `transform` property instead of the `left` property for better performance.
I tested this in all of our supported browsers and it should be good, but please try to break it!
=> DCOS-8002: Use less hacky method of positioning the sidebar

src/js/components/StatusBar.js
Test Data and Results:
```
{
className: 'unknown',
value: 50
},
{
className: 'healthy',
value: 47
},
{
className: 'over-capacity',
value: 1
},
{
className: 'unhealthy',
value: 1
},
{
className: 'staged',
value: 1
}
```
```
{
className: 'unknown',
value: 99
},
{
className: 'healthy',
value: 1
},
{
className: 'over-capacity',
value: 0
},
{
className: 'unhealthy',
value: 0
},
{
className: 'staged',
value: 0
}
```
```
{
className: 'unknown',
value: 25
},
{
className: 'healthy',
value: 25
},
{
className: 'over-capacity',
value: 25
},
{
className: 'unhealthy',
value: 20
},
{
className: 'staged',
value: 5
}
```
```
{
className: 'unknown',
value: 91
},
{
className: 'healthy',
value: 6
},
{
className: 'over-capacity',
value: 1
},
{
className: 'unhealthy',
value: 1
},
{
className: 'staged',
value: …
```
=> Algorithm to ensure small healthbar portions are visible

src/js/components/SchemaForm.js, src/js/components/TabForm.js, src/js/utils/SchemaUtil.js
=> Schema top level header h2

src/js/components/SchemaForm.js, src/js/utils/SchemaUtil.js, src/styles/layout/media-object.less
depends on https://github.com/dcos/dcos-ui/pull/693
=> Have schema checkbox labels on the right

src/js/components/ReviewConfig.js, src/js/components/modals/InstallPackageModal.js
Integration tests passing on a frankie branch, which includes this:
=> Improve text color contrast in package install modal

src/js/schemas/service-schema/General.js, src/js/schemas/service-schema/Optional.js
Holding merge until Friday afternoon in case anyone wants to chime in with other grammatical fixes.
=> DCOS-8067: Adjust grammar of tooltips

.eslintrc, src/js/components/ConfigurationView.js, src/js/components/TabForm.js, src/js/components/VolumeTable.js, src/js/pages/jobs/JobConfiguration.js, src/js/schemas/service-schema/ContainerSettings.js, src/js/structs/Service.js, src/js/utils/JobUtil.js
=> Enable no comma dangle

.eslintrc, src/js/components/HostTable.js, src/js/pages/nodes/NodeDetailPage.js, src/js/pages/services/DeploymentsTab.js
=> Eslint no duplicate imports

.eslintrc, src/js/components/FilterButtons.js, src/js/components/ServiceInfo.js, src/js/schemas/job-schema/General.js, src/js/structs/Service.js
Correct comma spacing. We obviously want this
=> Enable eslint comma spacing

src/js/components/ServiceDetail.js, src/js/components/modals/ServiceScaleFormModal.js
This PR adds the same error message as in the serviceModalForm and reuses the same logic.
=> DCOS-8372: Fix dialog actions in service detail to handle force updates

src/js/components/StatusBar.js, src/js/components/__tests__/StatusBar-test.js
Fixes Stack overflow bug when stealing portions in the case where there is no portion to steal from.
=> Fix Stack overflow for case where statusbar is scaled

src/js/components/TaskTable.js, src/js/components/TaskView.js, src/js/constants/TaskTableHeaderLabels.js, tests/pages/services/TasksTable-cy.js
=> DCOS-8427 Show task ids instead of name in Task List

src/js/constants/ServiceTableHeaderLabels.js
=> DCOS-8084 Set correct table header

webpack/proxy.template.js
Let's you develop on the mesos ui from the dcos ui repository
=> Adding description to develop on mesos ui

src/js/components/ReviewConfig.js, src/js/components/SchemaForm.js, src/js/components/modals/InstallPackageModal.js
=> Using image component in install package modal as well

src/js/schemas/service-schema/General.js, src/js/utils/ResourceValidatorUtil.js, src/js/utils/__tests__/ResourceValidatorUtil-test.js
Align the method names with the other validator utils.
=> Adjust the resource validator util method names

src/js/components/TaskTable.js, src/js/constants/TaskTableHeaderLabels.js
Reverts dcos/dcos-ui#724
@daiyiwhale I merged and reverted your PR after I noticed that it broke the nodes UI. This is a revert of my revert. So your original code. Please fix it up!
=> Revert "Revert "DCOS-8430: Rename State to Status in TaskTable""

src/js/components/ComponentList.js, src/js/components/ServiceList.js
=> Vertically align 'empty' dashboard panel messages

src/js/pages/services/ServicesTab.js
=> Global services search is global

src/js/components/ServicesTable.js, src/js/components/modals/ServiceScaleFormModal.js, src/js/events/MarathonActions.js
DEPENDS ON #681  (Merged)
jash wanted the icon to be a gear with a caret
=> [#2 Action dropdown service row] Add action dropdown on service rows

src/js/schemas/service-schema/General.js, src/js/utils/ServiceValidatorUtil.js, src/js/utils/__tests__/ServiceValidatorUtil-test.js
=> DCOS-8058: Add client side service id validation

src/js/components/ServicesTable.js
=> Right align service actions on table

src/js/components/modals/ServiceFormModal.js
Herein contains changes to `ServiceFormModal`, henceforce disabling the `Deploy` button betwixt submission of a request and receiving of a response.
=> DCOS-8063: Disable deploy button during pending request

src/js/components/TabForm.js, src/styles/components/multiple-form.less
Before:
After:
Integration tests:
=> Remove padding from non-scrolling portion of TabForm modal

src/js/components/ServiceDetailDebugTab.js, src/js/components/TaskDirectoryTable.js, src/js/components/TaskStatsTable.js, src/js/components/TimeAgo.js, src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/services/DeploymentsTab.js, src/js/utils/DateUtil.js, src/js/utils/MomentJSConfig.js, src/js/utils/ResourceTableUtil.js, src/js/utils/__tests__/DateUtil-test.js, tests/pages/jobs/JobDetails-cy.js
=> Update time component

src/js/components/HealthTab.js, src/js/components/TaskView.js, src/js/pages/NodesPage.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthTab.js
~~⚠️ Depends on https://github.com/dcos/dcos-ui/pull/660~~ merged
=> DCOS-8052: Show "Clear" while filtering even if all items are shown

src/js/components/ServicesTable.js
If this doesn't get merged, this warning will show:
=> Always have children for confirm modal

src/js/utils/SchemaFormUtil.js, src/js/utils/__tests__/SchemaFormUtil-test.js, tests/_fixtures/cosmos/package-describe.json
=> Bug fix: Schema form accepting default empty arrays

src/js/components/modals/ServiceFormModal.js
Text original said “Deploy new Service” and I’ve updated it to say “Deploy New Service”
https://mesosphere.atlassian.net/browse/DCOS-8700
Original: https://cl.ly/2i0Y1c3Q432N
Updated: https://cl.ly/08223o3S3Y2O
=> Fixed Deploy New Service Text

npm-shrinkwrap.json, package.json, src/js/pages/jobs/JobsTable.js
=> Implement prettycron in Jobs table

src/js/components/PageHeader.js, src/js/components/RepositoriesTable.js, src/js/components/__tests__/ConfigurationView-test.js, src/js/components/__tests__/NodesGridDials-test.js, src/js/components/__tests__/NodesGridView-test.js, src/js/components/__tests__/ServiceDetail-test.js, src/js/components/__tests__/ServiceDetailTaskTab-test.js, src/js/components/__tests__/ServiceInfo-test.js, src/js/components/__tests__/ServicesTable-test.js, src/js/components/__tests__/TaskTable-test.js, src/js/pages/__tests__/DeploymentsTab-test.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/services/DeploymentsTab.js, src/js/plugin-bridge/PluginModules.js, src/styles/components/jobs-view.less, tests/pages/services/TasksTable-cy.js
I implemented this everywhere I could think of that wouldn't be too performance intensive, as there are `resize` and `focus` handlers on `window` for each instance of the component.
=> [3 of 3: CollapsingString] DCOS-8072: Implement CollapsingString component

src/js/components/ServiceDetail.js, src/js/components/ServiceInfo.js, src/js/components/ServicesTable.js, src/js/constants/ServiceActionItem.js, src/js/stores/MarathonStore.js
=> Add restart service views.

src/js/components/SchemaForm.js, src/js/schemas/service-schema/Networking.js, src/js/utils/NetworkValidatorUtil.js, src/js/utils/SchemaUtil.js, src/js/utils/__tests__/NetworkValidatorUtil-test.js, src/styles/components/multiple-form.less
---
ℹ️  You will see the validation errors only on the second click or after switching the tabs. This is know issue which will hopefully be fixed with https://github.com/mesosphere/reactjs-components/pull/303.
=> DCOS-8058: Add client side network validation

src/js/constants/BulkOptions.js, src/js/pages/jobs/JobDetailPage.js
We will make users contemplate the severity of their actions:
=> DCOS-8580: Make destructive action buttons red

src/js/pages/jobs/JobRunHistoryTable.js, src/styles/components/collapsing-string.less, src/styles/components/tables.less
=> Fix JobsRunHistoyrTable icon + CollapsingString wrap

BEST_PRACTICES.md
[Check it out here](https://github.com/dcos/dcos-ui/blob/33434c5f825c7fdc4dee6c538e93bb81058586f5/BEST_PRACTICES.md)
=> Start Best Practices file

src/js/components/MesosLogView.js
=> Making sure to check compare string, rather than an object

src/js/components/SidebarLabelsFilter.js
=> Adding more describing text

src/js/pages/JobsPage.js, src/js/routes/jobs.js
We only have a single tab so we don't need this navigation. [DCOS-8578](https://mesosphere.atlassian.net/browse/DCOS-8578)
=> Remove header navigation on Jobs page

src/js/schemas/job-schema/Schedule.js
=> DCOS-8259 Remove brackets from labels

src/js/constants/StoreConfig.js, src/js/pages/task-details/__tests__/TaskDetail-test.js, src/js/stores/MarathonStore.js, src/js/stores/MesosLogStore.js, src/js/stores/MesosSummaryStore.js, src/js/stores/MetadataStore.js, src/js/stores/MetronomeStore.js
This PR moves registering of stores their respective constructors instead of it being handled in StoreConfig.
Functionally there is no change from this PR.
Includes the following stores:
- MarathonStore
- MesosLogStore
- MesosSummaryStore
- MetadataStore
- MetronomeStore
=> -> [Store config 2 of 4] MarathonStore, MesosLogStore, MesosSummaryStore, MetadataStore, MetronomeStore

tests/_fixtures/cosmos/package-describe.json, tests/pages/services/SidebarFilter-cy.js
=> Making sure to update test with updated label text

src/js/components/modals/ActionsModal.js
Breaking apart the methods a bit for ease of inheritance.
=> Lightly refactor ActionsModal

Authors.md
=> Change contributor status

src/js/schemas/job-schema/General.js, src/js/schemas/service-schema/General.js, src/js/utils/SchemaUtil.js
=> DCOS-8753 Autofocus ID field when creating Service, Job

src/js/pages/jobs/JobDetailPage.js, src/js/schemas/job-schema/General.js, src/js/utils/JobUtil.js, src/js/utils/__tests__/JobUtil-test.js
=> Make Job Description optional

README.md
Before: ![](http://velocity.mesosphere.com/service/velocity/buildStatus/icon?job=public-dcos-ui-master)
After: ![](https://jenkins.mesosphere.com/buildStatus/icon?job=public-dcos-ui-master)
=> Update URL for build status badge

src/js/pages/jobs/JobsTab.js
Correcting button state
Before:
After:
=> Fix button state on empty jobs page

src/js/components/MesosLogView.js, src/js/components/__tests__/MesosLogView-test.js
Discussed with @mlunoe and design and decided to remove link.
=> Removing unnecessary Dead Link when no logs found

src/js/pages/jobs/JobsTable.js
=> Making sure to default to an object to avoid errors

src/js/components/TaskTable.js, src/js/constants/TaskTableHeaderLabels.js
And fixing some issues with the current usage
Before:
After:
=> Updating task table to leverage col definition

src/js/components/charts/ResourceChart.js
=> DCOS-8575: Fix resource icon spacing

src/js/pages/jobs/JobDetailPage.js, src/js/utils/StringUtil.js, src/js/utils/__tests__/StringUtil-test.js, tests/pages/jobs/JobDetails-cy.js
Worst-case scenario:
Sweet spot:
cc @leemunroe as we discussed, we're moving the schedule text below the heading. Here you go!
=> DCOS-8352 Show pretty cron schedule in job detail page

src/js/stores/MesosSummaryStore.js
This code wasn't used anywhere
=> Remove unused code in MesosSummaryStore

src/js/components/FilterInputText.js
=> DCOS-8109 Add spacing between icon and text

src/js/components/JobForm.js, src/js/components/SchemaForm.js, src/js/components/ServiceForm.js, src/js/components/TabForm.js, src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js, tests/pages/services/ServiceFormModal-cy.js
=> DCOS-8064 Remember the selected form section

src/js/components/MarathonTaskDetailsList.js, src/js/components/TaskEndpointsList.js, src/js/components/TaskTable.js, src/js/components/TaskView.js, src/js/components/__tests__/TaskEndpointsList-test.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/task-details/TaskDetailsTab.js, src/js/structs/Node.js, src/js/utils/TaskUtil.js, src/js/utils/__tests__/TaskUtil-test.js
BRIDGE network:
HOST network:
Virtual Networks is still missing
=> Fixing endpoint displays, ref. DCOS-8975

src/js/schemas/job-schema/Schedule.js
@sascala & @leemunroe any comments?
Edit (@mlunoe): Updated image to reflect the recruirements from @sascala, and worked with @joel-hamill to finalize it with your suggestions.
=> Add link to docs for cron format

src/js/utils/__tests__/ApplicationUtil-test.js
=> Give unit test a 100ms interval to pass within

src/js/pages/services/DeploymentsTab.js, src/js/utils/ResourceTableUtil.js
=> Align deployment rollback link right

src/js/utils/NetworkValidatorUtil.js, src/js/utils/ValidatorUtil.js, src/js/utils/__tests__/NetworkValidatorUtil-test.js, src/js/utils/__tests__/ValidatorUtil-test.js
Add a few general validator utils to check if a value is a number, an integer or in in a specific range.
=> Introduce general validator utils

Authors.md
=> Update contributor status

src/js/components/CollapsibleErrorMessage.js, src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js, src/styles/components/collapsible-error-message.less, src/styles/components/multiple-form.less, src/styles/index.less, src/styles/variables/variables-z-index.less
This component is now used by the `ServiceFormModal` and `JobFormModal` for rendering the error messages.
=> DCOS-8454: Introducing a re-usable CollapsibleErrorMessage component

src/js/constants/TaskTableHeaderLabels.js
=> Correct heading for task table ID column

src/js/components/Sidebar.js
This has been driving me nuts for a while now.
=> Only collapse sidebar when no modifier key is pressed.

src/js/schemas/job-schema/Schedule.js
:abc:
Follow up PR to https://github.com/dcos/dcos-ui/pull/914
=> Follow up Pr to #914

src/js/components/ServiceForm.js
---
⚠️ Linked to enterprise functionality
---
Before:
After:
=> Make sure to reset model for secrets after update

src/js/components/SideTabs.js, src/styles/components/side-tabs.less
This pull request makes `SideTabs` aware of errors in it's fields.
=> Making the SideTabs aware of errors in the fields

src/js/components/MarathonTaskDetailsList.js, src/js/components/TaskTable.js, src/js/components/VolumeDetail.js, src/js/pages/task-details/TaskDetail.js, src/js/stores/MarathonStore.js, src/js/structs/ServiceTree.js, src/js/utils/ServiceUtil.js
Moving appropriate functionality from `MarathonStore` to `ServiceTree`.
=> DCOS-8237: Refactor MarathonStore

src/js/components/MesosLogView.js
This PR fixes the logic for when to display the `Go to Bottom` button and handles the window resize event.
=> Fix logic for #checkIfAwayFromBottom and handle window resize

package.json, scripts/validate-engine-versions, scripts/validate-tests
This check will run on `npm preinstall` and `npm start`
=> Adding node and npm version check

src/js/events/TaskDirectoryActions.js, src/js/pages/task-details/TaskDetail.js, src/js/pages/task-details/TaskFilesTab.js, src/js/stores/TaskDirectoryStore.js
=> Make sure to only emit directory events when response matches request

npm-shrinkwrap.json, package.json
Changes in this update:
- Auto expanding FieldTextarea (https://github.com/mesosphere/reactjs-components/pull/314)
- onChange called on setState-callback for form events (https://github.com/mesosphere/reactjs-components/pull/329)
- Doc updates (https://github.com/mesosphere/reactjs-components/pull/331, https://github.com/mesosphere/reactjs-components/pull/324)
=> Updating reactjs-components v0.15.1-0

.editorconfig
=> Added JS and less props for editorconfig

src/js/pages/task-details/TaskLogsTab.js, src/js/structs/DirectoryItem.js
Select stdout as default:
Display all files as viewable (not directories, of course):
=> Make all files viewable in log viewer

src/js/components/KillTaskModal.js
=> Cleaned up Kill task modal. refs: DCOS-9101

src/js/components/modals/AddRepositoryFormModal.js
refs: https://dcosjira.atlassian.net/browse/DCOS-289
=> Fix validation when adding a new repository to cosmos.

CONTRIBUTING.md
=> Make sure to render list, with newline before list

src/js/utils/ValidatorUtil.js, src/js/utils/__tests__/ValidatorUtil-test.js
Improve is number checks and use util to test is integer and is number in range input.
=> Improve general validation rules

src/js/schemas/service-schema/HealthChecks.js
=> DCOS-8058: Add client side health check validation

.eslintrc
This PR adds the no-new eslint rule
=> [Eslint] Add no-new linting override

.eslintrc, src/js/components/FilterInputText.js, src/js/components/ServiceDetailConfigurationTab.js, src/js/components/SidebarLabelsFilter.js, src/js/components/Typeahead.js, src/js/components/__tests__/StatusBar-test.js, src/js/pages/services/ServicesTab.js, src/js/plugin-bridge/AppHooks.js, src/js/plugin-bridge/PluginTestUtils.js, src/js/stores/MesosSummaryStore.js, src/js/utils/ServiceUtil.js, src/js/utils/TabsUtil.js
This PR adds the rule and corrects files to abide by it
=> [Eslint] Add eslint arrow parens rule

.eslintrc, src/js/components/MesosLogView.js, src/js/components/ServiceForm.js, src/js/components/TaskTable.js, src/js/components/charts/BarChart.js, src/js/components/charts/ChartStripes.js, src/js/components/charts/DialChart.js, src/js/components/charts/TasksChart.js, src/js/components/charts/TimeSeriesMouseOver.js, src/js/components/charts/__tests__/ChartStripes-test.js, src/js/components/modals/ServiceFormModal.js, src/js/pages/task-details/TaskLogsTab.js, src/js/stores/MetadataStore.js, src/js/utils/DOMUtils.js, src/js/utils/Maths.js, src/js/utils/ResourceTableUtil.js, src/js/utils/ServiceUtil.js, src/js/utils/ValidatorUtil.js
This PR activates the `no-mixed-operators` linting rule and makes files obey it
=> [Eslint] Activate no-mixed-operators linting rule

.eslintrc, src/js/components/DescriptionList.js, src/js/schemas/job-schema/Schedule.js, src/js/stores/NotificationStore.js, src/js/structs/LogBuffer.js, src/js/utils/FormUtil.js, src/js/utils/RouterUtil.js, src/js/utils/StructUtil.js, src/js/utils/Util.js, src/js/utils/ValidatorUtil.js
This PR activates the `no-prototype-builtins linting rule, and makes files obey the rule
=> [Eslint] Activate no-prototype-builtins linting rule

.eslintrc
Fix `.eslintrc` linting errors
=> [Eslint] Fix .eslintrc linting

.eslintrc, src/js/components/NodesGridView.js, src/js/pages/universe/__tests__/PackageDetailTab-test.js, src/js/pages/universe/__tests__/PackagesTab-test.js, src/js/utils/MesosStateUtil.js
Activate newline after imports linting rule and adjust files to follow the linting rule.
=> [Eslint] Activate newline after imports linting rule

.eslintrc
Activate semi spacing linting rule
=> [Eslint] Activate semi spacing linting rule

plugins/banner/SDK.js, plugins/banner/__tests__/BannerPlugin-test.js, plugins/banner/hooks.js, plugins/oauth/SDK.js, plugins/oauth/components/LoginPage.js, plugins/oauth/components/__tests__/UserDropup-test.js, plugins/oauth/hooks.js, plugins/tracking/SDK.js, plugins/tracking/__tests__/TrackingPlugin-test.js, plugins/tracking/actions/Actions.js, plugins/tracking/actions/__tests__/Actions-test.js, plugins/tracking/hooks.js
Fixing linting rules on './plugins' folder
=> [Esint] Fixing linting on './plugins'

src/js/pages/NodesPage.js
Follow up PR to https://github.com/dcos/dcos-ui/pull/985.
This PR corrects a require that was not transferred correctly to an import destructuring assignment.
=> Importing HashLocation correctly

src/js/components/modals/CliInstallModal.js
=> Updating CLI instructions per DCOS-8814

src/js/events/TaskDirectoryActions.js, src/js/events/__tests__/TaskDirectoryActions-test.js, src/js/pages/task-details/TaskDetail.js, src/js/stores/TaskDirectoryStore.js
=> Bug fix: tasks directory view after viewing another task

src/js/components/JobForm.js, src/js/schemas/job-schema/Schedule.js, src/js/utils/JobUtil.js, src/js/utils/__tests__/JobUtil-test.js
---
~~⚠️ Related PR: https://github.com/mesosphere/reactjs-components/pull/329~~ Merged
~~⚠️ Updating reactjs-components needed for this to work properly https://github.com/dcos/dcos-ui/pull/960~~ Merged
---
=> Add show/hide field to schedule for jobs create modal

src/js/components/TaskTable.js
=> Displaying hostname under host, and not endpoints

src/styles/components/user-dropup-menu.less
=> Fix text overflow in UserDropup

src/js/components/FilterInputText.js, src/js/components/HealthTab.js, src/js/components/TaskView.js, src/js/pages/NodesPage.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/system/OrganizationTab.js, src/js/pages/system/RepositoriesTab.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthTab.js, src/js/pages/task-details/TaskLogsTab.js, src/js/pages/universe/InstalledPackagesTab.js, src/js/pages/universe/PackagesTab.js
Was hitting a warning with this property being required, where it should not be
=> Defaulting to string, where it is set to not change value type

src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js, src/js/constants/JobConfig.js, src/js/structs/Job.js, src/js/structs/Service.js, src/js/structs/__tests__/Job-test.js, src/js/structs/__tests__/Service-test.js, src/js/utils/CleanJSONUtil.js, src/js/utils/JobUtil.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/JobUtil-test.js
This adds the support which has been added to services recently to support unknown attributes in the jobs ui.
=> DCOS-9170: Add support for unknown values in jobs

src/js/utils/SchemaUtil.js
=> Adding descriptions to rendering of subheader

src/js/components/CosmosErrorMessage.js, src/js/components/modals/InstallPackageModal.js
Make sure error responses are handled gracefully, even if they don't obey the standard.
=> Increasing the durability of CosmosErrorMessage on invalid responses

src/js/stores/UnitHealthStore.js
Fixes link! Clicking the download button actually initiates a download now.
note: DCOS-9440 is the internal tracking number.
dcos ref: https://dcosjira.atlassian.net/browse/DCOS-335
=> DCOS-9440: Fix component health download snapshot link

src/js/components/modals/ServiceScaleFormModal.js
=> Handle marathon group error response in scale modal

src/js/components/SchemaForm.js
=> DCOS-9200: Expose SchemaForm first level subtitle

src/js/components/modals/CliInstallModal.js, src/js/stores/MetadataStore.js
Before:
---
After:
---
Will fallback on `/latest` if version is not available.
=> Update cli download urls dynamically

src/js/components/MesosLogView.js, src/js/components/__tests__/MesosLogView-test.js, src/js/pages/task-details/TaskLogsTab.js, src/js/structs/LogBuffer.js
=> [Loader 1 of 2] Adding fetch previous log loader to mesos log

.gitignore
This just ignores the cypress folder and its contents
=> Ignore cypress folder

src/js/pages/jobs/JobRunHistoryTable.js
These both variables are not used in that function.
=> Remove unused variables from the jobRunHistoryTable

src/js/components/modals/JobFormModal.js, src/js/components/modals/ServiceFormModal.js, src/js/structs/Item.js, src/js/structs/Job.js, src/js/structs/Service.js, src/js/structs/__tests__/Job-test.js, src/js/structs/__tests__/Service-test.js
Making sure `toJSON` on structs returns an object and moving the JSON
clean-up functions to the them.
=> [Pods] Making sure toJSON is properly used throughout the structs

src/js/events/MarathonActions.js, src/js/utils/MarathonUtil.js, src/js/utils/ServiceUtil.js, src/js/utils/__tests__/MarathonUtil-test.js, tests/_fixtures/marathon-pods/groups.json
---
⚠️  ~~Depends on #1014~~
---
Also adding some fixtures for testing until we have real API.
=> [Pods] Handling new pod structures in the marathon groups response

src/js/components/ServiceDetail.js, src/js/components/ServiceDetailConfigurationTab.js, src/js/constants/PodContainerStatus.js, src/js/constants/PodInstanceStatus.js, src/js/structs/Application.js, src/js/structs/ApplicationSpec.js, src/js/structs/Framework.js, src/js/structs/FrameworkSpec.js, src/js/structs/Pod.js, src/js/structs/PodContainer.js, src/js/structs/PodInstance.js, src/js/structs/PodInstanceList.js, src/js/structs/PodSpec.js, src/js/structs/Service.js, src/js/structs/ServiceSpec.js, src/js/structs/ServiceTree.js, src/js/utils/ServiceUtil.js, src/js/utils/ServiceValidatorUtil.js, src/js/utils/__tests__/ServiceUtil-test.js, tests/_fixtures/marathon-pods/groups.json
---
⚠️ Depends on #1033 
---
Working on implementing the core functionality to the Pod struct
=> [Pods] Fleshing out pod struct

src/js/utils/ServiceUtil.js
This removes an old comment which is not used anymore
=> Remove unused code

src/js/components/ConfigurationView.js, src/js/schemas/service-schema/HealthChecks.js, src/js/utils/ServiceUtil.js
=> DCOS-9588: Remove Port type from the output

src/js/components/ComponentList.js
Fron this:
To this:
And just for fun:
[http://i.imgur.com/ReAyeol.gifv](http://i.imgur.com/ReAyeol.gifv)
=> Fixes component health sorting. refs: DCOS-9674

src/js/components/KillTaskModal.js, src/js/components/ServerErrorModal.js, src/js/events/MarathonActions.js, src/js/stores/MarathonStore.js
The behaviour seems a bit off here. But the kill and scale does work now with the force option.
=> DCOS-9162: Add force setting to kill and scale if application is currently locked

plugins/oauth/hooks.js, src/js/pages/SystemPage.js, src/js/plugin-bridge/Loader.js, src/js/plugin-bridge/PluginModules.js, src/js/routes/factories/system.js
This PR makes organization routes being added dynamically when sub-routes are defined.
=> Add organization routes dynamically

npm-shrinkwrap.json, package.json
Only change in this update is: https://github.com/mesosphere/reactjs-components/pull/345
=> Updating reactjs-components to v0.15.0-beta.3

src/js/components/ConfigurationView.js, src/js/components/ServiceForm.js, src/js/constants/Networking.js
VIP and Bridge port definition
Host port definition
=> Add port definitions for VIPs and DNS address for load balanced services. refs: DCOS-9191

src/js/components/JobForm.js
Introduce the `shouldUpdateDefinition` method from the service form to properly detect changes that require an update. This change resolves an issue where it was impossible to add more than one label.
/closes DCOS-9678
=> DCOS-9678: Update the job form change handling

src/js/components/NodesTable.js, src/js/components/Sidebar.js, src/js/constants/NodesTableHeaderLabels.js, src/js/pages/NodesPage.js, src/js/pages/__tests__/NodeDetailPage-test.js, src/js/pages/nodes/NodeDetailHealthTab.js, src/js/pages/nodes/NodeDetailPage.js, src/js/pages/nodes/NodeDetailTab.js, src/js/pages/nodes/NodeDetailTaskTab.js, src/js/routes/nodes.js
This PR introduces routes for tabs on the node detail page
Before:
After:
=> Cleanup nodes routes

src/js/components/ConfigurationView.js, src/js/components/Loader.js, src/js/components/MesosLogView.js, src/js/components/NodesGridView.js, src/js/components/NodesTable.js, src/js/components/ServiceList.js, src/js/components/TaskView.js, src/js/components/modals/InstallPackageModal.js, src/js/components/modals/__tests__/InstallPackageModal-test.js, src/js/pages/NetworkPage.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobsTab.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/nodes/NodeDetailPage.js, src/js/pages/services/DeploymentsTab.js, src/js/pages/services/ServicesTab.js, src/js/pages/system/OverviewDetailTab.js, src/js/pages/system/RepositoriesTab.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/UsersTab.js, src/js/pages/task-details/TaskDetail.js, src/js/pages/universe/InstalledPackagesTab.js, src/js/pages/universe/PackageDetailTab.js, src/js/pages/universe/PackagesTab.js, src/js/plugin-bridge/PluginModules.js, src/styles/components/loaders.less
---
⚠️ Followup PR to this: https://github.com/dcos/dcos-ui/pull/1007
---
This PR introduces a Loader component to be used around the application, centralizing code in one place. It is also exposing the component as a module to be used by plugins!
=> [Loader 2 of 2] Add loader component

src/js/structs/PodContainer.js, src/js/structs/PodInstance.js
Exposing some additional information on the pods struct.
=> [Pods] Exposing additional information to the pods struct

src/js/components/PodViewFilter.js
This introduces a re-usable filter bar component that contains plain text search and buttons.
Example usage:
```jsx
// Required UI State properties
this.setState({
filter: {
text: '',
status: ''
}
});
...
// Status mapper is a function that receives an
// item from the `items` array and returns
// a string that represents the status of this item
var statusMapper = function(item) {
if (!item.active) {
return 'inactive';
}
return 'active';
}
...
<PodViewFilter
filter={this.state.filter}
inverseStyle={inverseStyle}
items={items}
onFilterChange={this.handleFilterChange}
statusChoices={['all', 'active', 'inactive']}
statusMapper={statusMapper}
/>
```
=> [Pods] Adding PodViewFilter

src/js/components/SidebarFilter.js, src/js/components/SidebarLabelsFilter.js, src/js/pages/services/ServicesTab.js, src/styles/components/badges/styles.less, src/styles/components/buttons/styles.less, src/styles/components/dropdown-menus/styles.less, src/styles/components/panel/styles.less, src/styles/components/service-sidebar/styles.less, src/styles/components/side-list/styles.less, src/styles/index.less
This is just the filter sidebar, not the filter headline.
=> [CNVS Upgrade] Style services filter sidebar

src/styles/components/page-header/styles.less, src/styles/components/page-header/variables.less, src/styles/index.less
This PR introduces the preliminary CSS for the new page headers. There is currently no component which generates the expected markup.
Here's the expected markup. You can paste this as the return value for the [`#getPageHeader` method in `Page.js`](https://github.com/dcos/dcos-ui/blob/master/src/js/components/Page.js#L75) to see it in action!
```jsx
<div className="page-header">
<div className="page-header-inner pod pod-short">
<div className="page-header-heading">
<ul className="page-header-breadcrumbs list list-unstyled list-inline flush">
<li className="page-header-breadcrumb-primary h3 flush-top flush-left">
<Dropdown
buttonClassName="button dropdown-toggle"
dropdownMenuClassName="dropdown-menu"
dropdownMenuListClassName="dropdown-menu-list"
dropdownMenuListItemClassName="clickable" …
```
=> [CNVS Upgrade] PageHeader styling

tests/_fixtures/marathon-pods/groups.json
Fix inconsistencies in the Marathon groups (pod) fixture
=> [Pods] Adjust Marathon groups (pod) fixture

src/js/structs/PodInstance.js, src/js/utils/PodUtil.js, src/js/utils/__tests__/PodUtil-test.js
This introduces the `PodUtil` helper that for now contains free-text filter functions.
=> [Pods] Introducing PodUtil

src/js/components/PodDetail.js, src/js/components/PodHeader.js, src/js/pages/__tests__/ServicesTab-test.js, src/js/pages/services/ServicesTab.js
This is only a placeholder view for the pods UI. (Breakdown of #1048 )
=> [Pods] Skeleton pods view with placeholders

src/js/components/Sidebar.js
Depends on a series of additional PRs where the routes and components get adjusted:
#1087 
#1088
=> [CNVS Upgrade: 1 of 3] Create nested sidebar logic

src/js/structs/__tests__/Application-test.js
Adjust the application test description.
=> [Pods] Fix application test description

src/js/components/ServiceDetailConfigurationTab.js
Adjust the service detail config (version) edit operation, to provide open a form with the correct service version.
=> [Pods] Fix service config edit

package.json, plugins/tracking/__tests__/TrackingPlugin-test.js
I've adjusted the eslint file pattern to lint plugins by default. Fixed a linting error along the way.
=> Lint plugins by default

src/js/components/PodInstancesTable.js, src/js/components/PodInstancesView.js, src/js/components/__tests__/PodInstancesTable-test.js, src/js/components/__tests__/PodInstancesView-test.js, src/js/components/__tests__/fixtures/PodFixture.js
---
~~⚠️  Requires #1069 to be merged~~ Merged!
~~⚠️  Requires #1077 to be merged~~ Merged!
~~⚠️  Requires #1078  to be merged~~ Merged!
---
This PR integrates the `PodViewFilter` to the `PodDetailInstancesTab`
=> [Pods] Adding filter bar to PodInstancesView

src/js/components/CheckboxTable.js
---
Follow up PR to this one: https://github.com/dcos/dcos-ui/pull/1097
---
This just fixes some 80 character rules
=> 80 character rule nit fixes

src/js/components/PodDetail.js, src/js/components/modals/ServiceFormModal.js
Fixing some minor issues on the `ServiceFormModal`, as detected during testing.
=> [Pods][Testing] Fixing ServiceFormModal issues

src/js/pages/ClusterPage.js, src/js/pages/ComponentsPage.js, src/js/pages/OrganizationPage.js, src/js/pages/SettingsPage.js
=> [CNVS Upgrade: 2 of 3] Create parent wrapping pages

src/js/pages/styles/components/ButtonCollectionsTabContent.js, src/js/pages/styles/components/ButtonsTabContent.js, src/js/pages/styles/components/ModalsTabContent.js, src/js/pages/styles/components/PanelsTabContent.js, src/js/pages/styles/layout/ResponsiveUtilitiesTabContent.js
@ashenden This fixes all of the lint warnings from the in-app style guide.
=> [CNVS Upgrade] Fix Javascript lint errors in styleguide

src/js/constants/PodContainerState.js, src/js/constants/PodContainerStatus.js, src/js/constants/PodInstanceState.js, src/js/constants/PodState.js, src/js/structs/Pod.js, src/js/structs/PodContainer.js, src/js/structs/PodInstance.js, src/js/structs/__tests__/Pod-test.js, src/js/structs/__tests__/PodContainer-test.js, src/js/structs/__tests__/PodInstance-test.js, tests/_fixtures/pods/PodFixture.js
Moved all the state strings from the `Pod`, `PodInstance` and `PodContainer`  to a constants file.
=> [Pods] Moving raw strings to constants files

src/js/components/modals/ActionsModal.js
Bug fix https://mesosphere.atlassian.net/browse/DCOS-9805.
Reverting this https://github.com/dcos/dcos-ui/commit/030ca0806c8c49517e090eeaa0e54d8c2929cee2 as the StoreMixin is actually required on ActionsModal.
=> Reverting removal of StoreMixin

src/js/components/PodInstancesView.js
Adding the `Showing X of X Pods` headline on the pod instances talble.
=> [Pods] DCOS-9960: Adding filter headline

src/js/components/PodConfigurationTabView.js, src/js/components/PodDetail.js, src/js/components/PodSpecView.js, src/js/structs/PodSpec.js, src/js/structs/__tests__/PodSpec-test.js, tests/_fixtures/marathon-pods/groups.json, tests/_fixtures/pods/PodFixture.js
This PR introduces pod configuration tab view with basic sections:
Env vars, labels, version, user, secrets, volumes and scaling.
Part of the ticket: https://mesosphere.atlassian.net/browse/DCOS-9823
=> [Pods Configuration 1 of 3] Basic

tests/_fixtures/marathon-pods/groups.json, tests/_fixtures/pods/PodFixture.js
Adjust the pod fixtures to use the correct VIP label annotation.
=> [Pods] Adjust VIP labels

src/js/structs/Pod.js
---
⚠️ Needs #1110 to be merged
---
Fixing a small bug on `getTasksSummary`
=> [Pods] Fixing source of definedInstances on taskSummary

src/js/utils/__tests__/MesosStateUtil-test.js
Adjust the MesosStateUtil test description.
=> Correct MesosStateUtil test description

src/js/components/ServiceSidebarFilters.js, src/js/constants/ServiceOther.js, src/js/constants/ServiceOtherLabels.js, src/js/constants/ServiceOtherTypes.js, src/js/structs/ServiceTree.js
This PR introduces the `Pods` filter on the services tab.
=> [Pods] Adding Pod type filter on Others on ServicesTab

jest/setupEnv.js
This PR implements an actual polyfill for `requestAnimationFrame` for jsdom.
=> [CNVS Upgrade] Implement a better requestAnimationFrame polyfill

src/js/components/AccessDeniedPage.js, src/js/components/AlertPanel.js, src/styles/index.less, src/styles/layout/alignment-utilities/styles.less
=> [CNVS Upgrade] Fix up the AccessDenied page

src/js/components/charts/ResourceBarChart.js
I must have messed up a rebase; this is what the `ResourceBarChart` should look like:
=> [CNVS Upgrade] Fix rebase mistake in ResourceBarChart 

src/js/components/ServiceSidebarFilters.js, src/js/pages/services/ServicesTab.js, src/styles/index.less, src/styles/views/services/styles.less, src/styles/views/services/variables.less
This PR makes the `ServiceSidebarFilter` behave responsively as expected.
=> [CNVS Upgrade] Fix ServiceSidebarFilters width and margins

src/js/components/FilterByService.js, src/js/components/PodViewFilter.js, src/js/components/Sidebar.js, src/js/components/SidebarFilter.js, src/js/components/SidebarLabelsFilter.js, src/js/components/TaskView.js, src/js/components/__tests__/FilterByService-test.js, src/js/mixins/TabsMixin.js, src/js/mixins/__tests__/TabsMixin-test.js, src/js/pages/NodesOverview.js, src/js/pages/system/UnitsHealthTab.js, src/js/pages/universe/PackageDetailTab.js, src/styles/components/badges/styles.less, src/styles/components/badges/variables.less, src/styles/components/service-sidebar/styles.less, src/styles/layout/sidebar/styles.less, src/styles/layout/sidebar/variables.less
Depends on #1182 to merge first
This PR corrects the use of `.badge` throughout the application.
=> [CNVS Upgrade: Tabs & Badges, 2 of 2] Fix badge styling

src/js/components/ServicesTable.js, src/styles/content/tables/styles.less
This PR removes the dependency on flex-specific classes for this element.
=> [CNVS Upgrade] Fix table-cell-flexbox container

src/js/pages/network/VirtualNetworksTab.js, src/js/routes/factories/network.js
This PR adds Networking sub-children routes.
=> [CNVS Upgrade] Add Networking routes

src/js/components/PodInstancesTable.js, src/js/components/PodInstancesView.js, src/js/components/PodViewFilter.js, src/js/components/__tests__/PodInstancesTable-test.js, src/js/components/modals/KillPodInstanceModal.js
---
⚠️ Requires #1174 to be merged
---
This PR introduces the `KillPodInstanceModal` that can be used to process the kill instance request from the user.
Only the last commit is relevant to this PR: https://github.com/dcos/dcos-ui/pull/1176/commits/be706ae05cb4d95c6c38c53af69c62a77a36d083
=> [Pods] DCOS-10108 [3/3]: Adding KillPodInstanceModal

api/networking/minuteman-api-spec.raml
@rcorral 
* ui changes, https://mesosphere.atlassian.net/browse/DCOS-10584
* minuteman changes, https://mesosphere.atlassian.net/browse/DCOS-9917
=> vip name tag

src/js/components/PodDetail.js, src/js/components/PodInstancesTabView.js, src/js/components/__tests__/PodInstancesTabView-test.js
Making sure we properly follow the pattern.
=> DCOS-10299: Renaming PodInstancesView to PodInstancesTabView

src/js/components/PodDetail.js, src/js/components/PodHeader.js
Addressing these outstanding comments:
https://github.com/dcos/dcos-ui/pull/1080/files#r79456792
https://github.com/dcos/dcos-ui/pull/1080/files#r79456685
=> [Pods] DCOS-9840: Using explicit methods instead of handleAction

src/js/pages/DashboardPage.js
This fixes an issue with the responsiveness of panels on the dashboard.
=> [CNVS Upgrade] Fix dashboard panels

src/js/components/ReviewConfig.js, src/js/components/modals/InstallPackageModal.js, src/styles/components/modal/install-package/styles.less, src/styles/components/modal/variables.less, src/styles/components/multiple-form/styles.less
I missed this when cleaning up the Packages view the first time around.
You'll notice the offset `DescriptionList`; this will be fixed in CNVS.
=> [CNVS Upgrade] Clean up InstallPackage, ReviewConfig modal

src/styles/components/dropdown-menus/styles.less
=> [CNVS Upgrade] Fix Dropdown transparent styles

src/js/components/ServiceInfo.js, src/js/components/__tests__/ServiceInfo-test.js, src/js/pages/jobs/JobDetailPage.js
This PR just adds spacing for the items in the `ServiceInfo` subheader and removes margin on a `p` tag in the `JobDetailPage` subheader.
`ServiceInfo`:
=> [CNVS Upgrade] Adjust detail view subheaders

src/js/components/DetailViewHeader.js, src/js/components/FilterInputText.js, src/js/components/MesosLogView.js, src/js/components/Page.js, src/js/components/ServiceDetail.js, src/js/pages/services/ServicesTab.js, src/js/pages/task-details/TaskDetail.js, src/js/pages/task-details/TaskFileViewer.js, src/styles/components/buttons/styles.less, src/styles/components/form-elements/styles.less
This PR applies the correct classes for the log viewer.
=> [CNVS Upgrade] Fix task log viewer

src/js/components/NestedServiceLinks.js, src/js/components/NodesTable.js, src/js/components/PackagesTable.js, src/js/components/RepositoriesTable.js, src/js/components/ServicesTable.js, src/js/components/TaskTable.js, src/js/components/UnitHealthNodesTable.js, src/js/pages/jobs/JobRunHistoryTable.js, src/js/pages/jobs/JobsTable.js, src/js/pages/network/VirtualNetworksTable.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskTab.js, src/js/pages/services/DeploymentsTab.js, src/js/pages/system/UnitsHealthTab.js, src/styles/components/dashboard-health-list/styles.less, src/styles/components/expanding-table/styles.less, src/styles/content/tables/styles.less
This implements two `table-cell-link-*` classes throughout the application.
The `...-primary` class is bold link and the `...-secondary` class is the normal weight.
=> [CNVS Upgrade] Style table cell links

npm-shrinkwrap.json, package.json
=> [CNVS Upgrade] Update CNVS to 1.0.7

src/js/components/modals/FullScreenModal.js, src/js/components/modals/FullScreenModalHeader.js, src/js/components/modals/FullScreenModalHeaderActions.js, src/js/components/modals/FullScreenModalHeaderTitle.js, src/styles/components/modal/full-screen/styles.less, src/styles/components/modal/full-screen/variables.less, src/styles/components/modal/styles.less, src/styles/index.less, src/styles/layout/container/styles.less, src/styles/layout/container/variables.less
This will be implemented for the create service workflow.
=> [CNVS Upgrade] Introduce the full screen modal

src/styles/components/page-header/styles.less
=> [CNVS Upgrade] Fix page header tab margins

plugins/services/src/js/components/PodHeader.js
=> [CNVS Upgrade] Fix pod's detail view header spacing

foundation-ui/stores/__tests__/DCOSStore-test.js
I broke this import in my recent rebase :(
=> [CNVS Upgrade] Fix broken import

src/js/pages/universe/PackageDetailTab.js, src/styles/views/packages/styles.less
This PR: 
* Fixes a rebase error that got in the header in the `PackagesDetailTab`
* Adds spacing to the `selected` badge
* Removes the leftover `Breadcrumb`
Before:
After:
=> [CNVS Upgrade] Fix PackagesDetailTab header

plugins/services/src/js/services/EmptyServiceTree.js, plugins/services/src/js/services/ServiceItemNotFound.js, plugins/services/src/js/services/ServiceTreeView.js, src/js/pages/system/units-health-node-detail/NodeInfoPanel.js
This PR removes some inverse classes that shouldn't be present
=> [CNVS Upgrade] Fix inverse classes

src/js/components/ConfigurationMap.js, src/js/components/ConfigurationMapHeading.js, src/js/components/ConfigurationMapLabel.js, src/js/components/ConfigurationMapRow.js, src/js/components/ConfigurationMapSection.js, src/js/components/ConfigurationMapValue.js, src/styles/components/configuration-map/styles.less, src/styles/components/configuration-map/variables.less, src/styles/index.less
This introduces the first iteration of the `ConfigurationMap` family of components (name probably needs work, I've spoken to the design team about this and it's TBD)
Here's some example JSX:
```jsx
<ConfigurationMap>
<ConfigurationMapSection>
<ConfigurationMapHeading level={1}>
General
</ConfigurationMapHeading>
<ConfigurationMapRow>
<ConfigurationMapLabel>
Service ID
</ConfigurationMapLabel>
<ConfigurationMapValue>
shopping-web
</ConfigurationMapValue>
</ConfigurationMapRow>
<ConfigurationMapRow>
<ConfigurationMapLabel>
Instances
</ConfigurationMapLabel>
<ConfigurationMapValue>
3
</ConfigurationMapValue>
</ConfigurationMapRow>
<ConfigurationMapRow>
<ConfigurationMapLabel>
Artifcats
</ConfigurationMapLabel>
<ConfigurationMapValue stacked={true}>
<ConfigurationMapValue> …
```
=> Introduce ConfigurationMap family of components

src/js/events/AuthActions.js, src/js/events/UsersActions.js
This will be properly fixed by #1283. But this is a fix for 1.8 only.
=> Temporarily fixes timeout on login and user actions.

src/js/components/modals/UninstallPackageModal.js
=> Remove duplicated attribute

src/js/structs/List.js, src/js/structs/__tests__/List-test.js, src/js/utils/ObjectUtil.js, src/js/utils/__tests__/ObjectUtil-test.js
This PR introduces the `combine` function to the `List` that creates a new list using the items from itself and the passed one, discarding all possible duplicates.
=> List.js: Adding combine function to merge and remove duplicates

src/js/structs/Batch.js, src/js/structs/__tests__/Batch-test.js
This PR adds improvements to the Batch to keep the amount of events minimal, to optimize for reducer iterations.
=> Batch improvements

src/styles/content/tables/styles.less
=> DCOS-11286: Force dropdown trigger buttons to stay visible when open

src/styles/components/checkbox-table/styles.less
=> Remove margin on checkboxes in checkbox-tables

mergebot-config.json, owners.json
This integrates @mesosphere-mergebot  to dcos-ui repo. 
The commands and the configuration are documented here:
https://github.com/mesosphere/mergeservice/blob/mergebot-0.1/README.rst
This is a follow-up from PR https://github.com/dcos/dcos-ui/pull/1310 and addresses the review comments posted there.
=> dcos-ui mergebot integration.

plugins/services/src/js/components/forms/EnvironmentFormSection.js, plugins/services/src/js/reducers/serviceForm/EnvironmentVariables.js, plugins/services/src/js/reducers/serviceForm/Labels.js
This is removing some remains from the implementation of the multiple items. As the concept of the form reducers changed once but not all the associated code has been removed this is fixed now.
=> Fix environment section

scripts/pre-commit
Add command to the `pre-commit` hook to test staged files before committing.
=> Test staged files before committing

src/js/components/form/FieldSelect.js
Usage:
```
<FieldSelect name="protocol"
value="http">
<option value="">Select Protocol</option>
<option value="http">HTTP</option>
<option value="https">HTTPS</option>
</FieldSelect>
```
Will look like:
=> Add the FieldSelect Component

src/js/components/Alert.js, src/styles/components/alert/styles.less, src/styles/components/alert/variables.less, src/styles/index.less
This PR introduces the `Alert` component. It will be implemented in the upcoming rejected offers PR.
=> Introduce Alert component

src/js/utils/JSONUtil.js, src/js/utils/__tests__/JSONUtil-test.js
This PR introduces the `JSONUtil` class that contains a tokenizer capable of tracking useful information about a JSON string. With this utility:
* We can resolve error paths to JSON line numbers
* We can detect which variable was changed by the user
* We can automatically focus on the UI field the user is editing in JSON
For example, running `JSONUtil.getObjectInformation` with the given input:
```js
{
"ram": null,
"env": [
{"key": "name", "value": "test"}
]
}
```
Will return:
```js
[
{
"path": [ "instances" ],
"line": 2,
"value": 1,
"type": "literal"
},
{
"path": [ "ram" ],
"line": 3,
"value": null,
"type": "literal"
},
{
"path": [ "env" ],
"line": 4,
"type": "array"
},
{
"path": [ "env", 0 ],
"line": 5,
"type": "object"
},
{
"path": [ "env", 0, "key" ],
"line": 5, …
```
=> DCOS-10978 [1/2]: Introducing the JSONUtil

src/js/components/CollapsibleContainer.js
With this component it is possible to create a
section which is collapsible and is hidden behind
a label this label can be configured with the
label prop. The label prop expects a string
Example:
```
<CollapsibleContainer label="Advanced Setting">
... Some Content
</CollapsibleContainer>
```
Closed:
Open:
=> Add collapsible component

src/js/components/JSONEditor.js, src/js/utils/JSONEditorUtil.js, src/js/utils/__tests__/JSONEditorUtil-test.js
---
~⚠️  Needs https://github.com/dcos/dcos-ui/pull/1361 merged~
---
This is a high-order component on top of `AceEditor` that abstracts the JSON
string manipulation and allows object-level access to the underlaying data.
It's features are:
* Solve some bugs and peculiarities of AceEditor component
* Maintain visual coherence between object updates
* Callback on per-property updates as the user types
* Receive errors through properties and show them in the gutter
```js
handleChange(newObject) {
console.log('New object:', newObject);
}
handlePropertyChange(path, value) {
console.log('Property /'+path.join('/'), 'changed to', value);
}
render() {
let value = {
some: {value: 'object'}
};
let errors = [
{path: ['some'], message: 'An error on object `some`'}
];
return (
<JSONEditor …
```
=> DCOS-11481: Introducing high-level JSON Editor component

jest/preprocessor.js, plugins/services/src/js/components/modals/ServiceModals.js, scripts/pre-install
This PR activates the new create/edit service flow:
=> Activating new create/edit service flow

mergebot-config.json
Ref: https://github.com/dcos/dcos-ui/pull/1368#issuecomment-260797423
=> Let's enable other mergebot features

plugins/services/src/js/components/forms/HealthChecksFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/JSONParserReducers.js, plugins/services/src/js/reducers/serviceForm/HealthChecks.js, plugins/services/src/js/reducers/serviceForm/__tests__/HealthChecks-test.js, src/js/components/form/FormGroupContainer.js, src/styles/components/form-elements/styles.less
This introduces the health check section.
notes:
- Endpoints is not introduced yet since ports is not available yet.
=> Health Checks Section

plugins/services/src/js/reducers/serviceForm/LocalVolumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/LocalVolumes-test.js
This adds the local Volumes reducer which is part
of DCOS-10991
=> DCOS-10991 [1 of 4] Add LocalVolumes reducer

npm-shrinkwrap.json, package.json
This update includes changes from https://github.com/dcos/mesosphere-shared-reactjs/pull/24
=> Update mesosphere-shared-reactjs to 0.0.24

plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/EnvironmentVariables-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/Labels-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/LocalVolumes-test.js, src/js/structs/Batch.js, src/js/structs/__tests__/Batch-test.js
This PR makes the `Batch` immutable, making it possible to detect batch changes on the `shouldComponentUpdate` function.
=> DCOS-11582: Make Batch immutable

plugins/services/src/js/components/forms/HealthChecksFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/JSONParserReducers.js, plugins/services/src/js/reducers/serviceForm/HealthChecks.js, plugins/services/src/js/reducers/serviceForm/__tests__/HealthChecks-test.js, src/js/components/form/FormGroupContainer.js, src/styles/components/form-elements/styles.less
#1364 got merged onto the wrong branch it should have gone to master.
This is my bad since I changed the target of the other PR and did not communicated this right.
=> pull rerequest for Healtchecks duplicate of 1364

src/styles/components/buttons/styles.less
This PR adds `button-transparent` which does exactly what you'd expect! ;)
=> Add .button-transparent

npm-shrinkwrap.json, package.json, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/components/modals/ServiceModals.js, plugins/services/src/js/constants/NewApplicationDefaults.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/serviceForm/General.js, src/js/utils/DataValidatorUtil.js, src/js/utils/__tests__/DataValidatorUtil-test.js
---
~⚠️  Needs this https://github.com/dcos/dcos-ui/pull/1387 merged~
~⚠️  Needs this https://github.com/dcos/dcos-ui/pull/1386 merged~
~⚠️  Needs this https://github.com/dcos/dcos-ui/pull/1384 merged~
~⚠️  Needs this https://github.com/dcos/dcos-ui/pull/1379 merged~
~⚠️  Needs this https://github.com/dcos/dcos-ui/pull/1366 merged~
~⚠️  Needs this https://github.com/dcos/dcos-ui/pull/1392 merged~
---
This PR combines the new `JSONEditor` and the new data validation mechanism. Trying to normalise the different concepts and create a clean base were we can work on. Since this was quite big change, it was separate in the PRs above.
=> DCOS-10975: New JSON editor & Fine-grained error validation

plugins/services/src/js/reducers/serviceForm/ExternalVolumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/ExternalVolumes-test.js
This is part of DCOS-10991 and adds the reducer
and parser for external volumes.
=> DCOS-10991 [2 of 4] Add ExternalVolumes Reducer

plugins/services/src/js/reducers/serviceForm/Volumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js
This is part of DCOS-10991 and introduces the
volumes reducer which handles External and Local
volumes.
=> DCOS-10991 [3 of 4] Add Volumes reducer

plugins/services/src/js/components/forms/VolumesFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/JSONParserReducers.js, plugins/services/src/js/reducers/serviceForm/Volumes.js, src/js/utils/ReducerUtil.js, src/js/utils/__tests__/ReducerUtil-test.js
This adds the form component to add volumes.
=> DCOS-10991 [4 of 4]: Volumes form section

plugins/services/src/js/components/LogView.js, plugins/services/src/js/components/MesosLogView.js, plugins/services/src/js/components/SearchLog.js, plugins/services/src/js/pages/task-details/TaskDetail.js, plugins/services/src/js/pages/task-details/TaskFileBrowser.js, plugins/services/src/js/pages/task-details/TaskFileViewer.js, plugins/services/src/js/pages/task-details/TaskFilesTab.js, plugins/services/src/js/pages/task-details/TaskLogsTab.js, plugins/services/src/js/routes/services.js, src/js/events/SystemLogActions.js, src/js/events/__tests__/SystemLogActions-test.js, src/js/stores/SystemLogStore.js, src/js/utils/DOMUtils.js, src/js/utils/MesosStateUtil.js
[System logs 1 of 2](https://github.com/dcos/dcos-ui/pull/1421)
[System logs 2 of 2](https://github.com/dcos/dcos-ui/pull/1422)
This PR introduces the view for the streaming log:
You need to start a cluster with `testing/pull/971` to test it out.
=> [2 of 2 System logs] Add new stream log view

plugins/services/src/js/components/forms/VolumesFormSection.js, plugins/services/src/js/reducers/serviceForm/LocalVolumes.js, plugins/services/src/js/reducers/serviceForm/Volumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/LocalVolumes-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js, plugins/services/src/js/service-configuration/StorageServiceConfigSection.js
As noted here: https://github.com/dcos/dcos-ui/pull/1409#issuecomment-263444396
This PR adds the following features:
- Host Volume
- Remove External Volumes Drop down
This also adds Host Volumes to the review table:
=> DCOS-10991: Add host volume

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/JSONParserReducers.js, plugins/services/src/js/reducers/serviceForm/General.js
This PR implements GPUs support in the form.
---
---
=> DCOS-11761: Add gpus support

plugins/services/src/js/components/ServiceConfigDisplay.js, plugins/services/src/js/components/ServiceConfigPlacementConstraintsSectionDisplay.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/JSONParserReducers.js, plugins/services/src/js/reducers/serviceForm/Constraints.js, plugins/services/src/js/reducers/serviceForm/General.js, plugins/services/src/js/reducers/serviceForm/__tests__/Constraints-test.js, src/js/utils/JSONEditorUtil.js, src/js/utils/__tests__/JSONEditorUtil-test.js
This PR introduces placement constraints:
⚠️  I moved "Container Runtime" section from the foldable Advanced Settings as it is supposed to be according to the design. So it's always visible, while Placement Constraints go under Advanced Settings section
=> dcos-11760: Placement constraints

plugins/services/src/js/pages/task-details/TaskLogsTab.js
=> Adding download button to log page

plugins/services/src/js/components/ServiceConfigDisplay.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/service-configuration/PodConfigDisplay.js, plugins/services/src/js/service-configuration/PodContainerArtifactsConfigSection.js, plugins/services/src/js/service-configuration/PodContainerConfigSection.js, plugins/services/src/js/service-configuration/PodContainersConfigSection.js, plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js, plugins/services/src/js/service-configuration/PodGeneralConfigSection.js, plugins/services/src/js/service-configuration/PodHealthChecksConfigSection.js, plugins/services/src/js/service-configuration/PodLabelsConfigSection.js, plugins/services/src/js/service-configuration/PodNetworkConfigSection.js, plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js, plugins/services/src/js/service-configuration/PodStorageConfigSection.js, plugins/services/src/js/utils/ServiceConfigDisplayUtil.js, src/styles/components/configuration-map/variables.less
---
⚠️ ~~Needs #1436 merged first~~
---
This PR introduces the new set of components for the `PodConfigDisplay`.
=> DCOS-11738,DCOS-11736: Implementing review screen for pods

src/js/components/modals/FullScreenModal.js
This PR applies the class that will make the content of `FullScreenModal` fill its container properly.
=> Fix FullScreenModal display

src/js/components/UserAccountDropdown.js
Relies on https://github.com/dcos/dcos-ui/pull/1448
=> Fix user account dropdown button capitalization

src/styles/components/menu-tabbed/styles.less, src/styles/components/menu-tabbed/variables.less
This PR prevents the vertical tabbed menu from shrinking and increases its width.
=> Prevent vertical tab menu from shrinking and increase its width

plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalServicePicker.js
=> Use JSON only editor when editing a pod

plugins/nodes/src/js/pages/NodesOverview.js, plugins/services/src/js/components/ServiceItemNotFound.js, plugins/services/src/js/containers/services/EmptyServiceTree.js, plugins/services/src/js/containers/services/ServicesContainer.js, plugins/services/src/js/containers/volume-detail/ServiceVolumeContainer.js, plugins/services/src/js/containers/volume-detail/TaskVolumeContainer.js, plugins/services/src/js/pages/services/DeploymentsTab.js, src/js/components/AccessDeniedPage.js, src/js/components/AlertPanel.js, src/js/pages/NotFoundPage.js, src/js/pages/jobs/JobsTab.js, src/js/pages/network/VirtualNetworksTab.js, src/js/utils/VirtualNetworkUtil.js, src/styles/components/alert-panel/styles.less, src/styles/components/alert-panel/variables.less, src/styles/index.less
Dependent on this PR as well https://github.com/mesosphere/dcos-ui-plugins-private/pull/467
=> Updated alert panel styling and messaging

plugins/services/src/js/components/modals/AppLockedMessage.js, plugins/services/src/js/components/modals/KillPodInstanceModal.js, plugins/services/src/js/components/modals/KillTaskModal.js, plugins/services/src/js/components/modals/ServiceDestroyModal.js, plugins/services/src/js/components/modals/ServiceModals.js, plugins/services/src/js/components/modals/ServiceRestartModal.js, plugins/services/src/js/components/modals/ServiceScaleFormModal.js, plugins/services/src/js/components/modals/ServiceSuspendModal.js, plugins/services/src/js/events/MarathonActions.js, plugins/services/src/js/events/__tests__/MarathonActions-test.js, src/js/components/ServerErrorModal.js
Fixing force action and error handling on modals.
=> Fix force action and error message handling for modals

plugins/services/src/js/containers/services/EmptyServiceTree.js
Add missing onCreateGroup property.
=> Fix empty service tree view

plugins/services/src/js/containers/services/ServiceTreeView.js, tests/pages/services/ServiceFormModal-cy.js
It's `Run a Service` everywhere, Service running, Review & Run
So I changed this button as well
=>>>>
=> Rename Deploy Service -> Run a service

src/js/components/Alert.js
This PR brings back an icon in the Alert component that went missing after the icons update
=> Fix icon leftover in the Alert component

src/styles/components/dropdown-panels/styles.less, src/styles/components/dropdown-panels/variables.less, src/styles/index.less
This PR introduces the `.dropdown-panel-group` class that is needed in order to implement the drop-down styling options for the DSL.
=> DCOS-10470: [1/4] Introducing the . dropdown-panel-group class

src/js/components/PrimarySidebarLink.js, src/js/components/Sidebar.js, src/styles/layout/header/styles.less, src/styles/layout/sidebar/styles.less, src/styles/layout/sidebar/variables.less
This PR includes commits from ~~#1412, #1417~~, and ~~#1419~~. It introduces the expanding/collapsing sidebar sections. 🔽 🔼
=> [Sidebar: 4 of 4] Expanding/collapsing sidebar sections

plugins/services/src/js/components/forms/EnvironmentFormSection.js, plugins/services/src/js/components/forms/HealthChecksFormSection.js, plugins/services/src/js/components/forms/VolumesFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/containers/services/__tests__/ServicesContainer-test.js, plugins/services/src/js/reducers/serviceForm/Volumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js
In this PR I took care of errors in
Environment
Health checks
Volumes
ℹ️  I took the risk and used some lenses here and there, slap my hands if I should stop doing this.
=> DCOS-11871: Pass Create Service Form errors to all the missing partials

src/js/index.js, src/js/pages/Index.js, src/js/routes/index.js
This PR addresses the issue when a user hits 404 and goes back Navigation would re-register all the routes.
=> DCOS-11875: Fix 404 -> multiple sidebar registrations

src/js/components/NewPageHeaderActions.js
Fix the header actions prop types and use the class name prop to allow proper item styling.
/cc @philipnrmn
=> Fix new page header actions prop types

plugins/services/src/js/components/DeleteRowButton.js, plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/forms/EnvironmentFormSection.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, src/js/components/form/DeleteRowButton.js, src/js/components/form/index.js
⚠️  WIP because it doesn't implement the hover state as proposed by Lee. Feel free to review/merge it if you don't think this functionality is crucial.
This PR replaces DELETE links with crosses
=> [wip] DCOS-11726: Replace DELETE links with crosses

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/forms/VolumesFormSection.js
Using `FormGroupContainer` in volumes:
Before:
After:
And adding keys to elements to avoid these in container section:
=> Bug fixes: Minor clean up warning and error fixes in the create service form

plugins/services/src/js/components/forms/HealthChecksFormSection.js, plugins/services/src/js/reducers/serviceForm/HealthChecks.js, plugins/services/src/js/reducers/serviceForm/__tests__/HealthChecks-test.js, scripts/pre-install
Update Marathon RAML dependencies and align health checks with latest spec. The latest Marathon release includes the following fixes: 
* https://github.com/mesosphere/marathon/issues/4766
* https://github.com/mesosphere/marathon/issues/4767
=> Update Marathon RAML

src/js/pages/UniversePage.js, src/js/pages/universe/InstalledPackagesTab.js, src/js/pages/universe/PackageDetailTab.js, src/js/pages/universe/PackagesTab.js, src/js/pages/universe/__tests__/PackageDetailTab-test.js, src/js/pages/universe/__tests__/PackagesTab-test.js
---
⚠️   _This branch depends on features that will be introduced with #1482_
---
=> [3/11] Implement new header in Packages pages

src/js/pages/ComponentsPage.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/UnitsHealthTab.js, src/js/pages/system/units-health-node-detail/UnitsHealthNodeDetailPanel.js
---
~~⚠️   _This branch depends on features that will be introduced with #1482_~~ Merged
---
=> [4/11] Page Header for components health

scripts/pre-install, scripts/pre-push
---
⚠️ This PR depends on changes that will get introduced with #1298 
---
Add a pre-push hook to run the unit test before pushing stuff to origin.
=> Add a pre-push hook

src/js/components/NewPageHeader.js, src/js/components/NewPageHeaderActions.js, src/js/components/Page.js
This is a continuation from #1509. Github had a brain fart and wouldn't see the commit that I added to this branch...so now I need to put up another PR...
=> Renamed function. More stringent prop types.

plugins/services/src/js/service-configuration/NetworkingServiceConfigSection.js
This PR introduces network name and type for the review page:
=> Adding Network name and network type

plugins/services/src/js/pages/task-details/ServiceTaskDetailPage.js, plugins/services/src/js/pages/task-details/TaskDetail.js, plugins/services/src/js/routes/services.js, src/js/components/breadcrumbs/JobsBreadcrumbs.js, src/js/pages/JobsPage.js, src/js/pages/__tests__/JobsTab-test.js, src/js/pages/jobs/JobDetailPage.js, src/js/pages/jobs/JobTaskDetailPage.js, src/js/pages/jobs/JobsTab.js, src/js/routes/jobs.js
---
~~⚠️   _This branch depends on features that will be introduced with #1482_~~ Merged!
---
This is a WIP PR which adds headers to the jobs section. 
The TaskDetail section is still missing, this is awkward because there are several valid routes for the view via services, jobs, and apparently network also. The answer to this is probably to write individual pages for each route which share the common component.
=> [5/11] Headers for jobs

src/js/routes/index.js
As being said… Routes are super confusing, so I broke them while trying to fix.
This PR addresses all the cases:
- normal routes
- plugins
- 404
- login
- logout
- open cluster
🙇
=> Fix login route

src/js/pages/ClusterPage.js, src/js/pages/NetworkPage.js, src/js/pages/SettingsPage.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/system/OverviewDetailTab.js, src/js/pages/system/RepositoriesTab.js
---
~~⚠️   _This branch depends on features that will be introduced with #1482_~~ Merged!
---
=> [6/11] Implements Page header in Networks, Cluster and Repositories pages

plugins/services/src/js/containers/services/ServiceTreeView.js, plugins/services/src/js/containers/services/ServicesContainer.js, plugins/services/src/js/containers/services/__tests__/ServicesContainer-test.js, plugins/services/src/js/filters/__tests__/ServiceAttribHealthFilter-test.js, plugins/services/src/js/filters/__tests__/ServiceAttribIsFilter-test.js, plugins/services/src/js/filters/__tests__/ServiceNameTextFilter-test.js, src/js/components/DSLFilterField.js, src/js/structs/DSLExpression.js, src/js/structs/DSLFilterList.js, src/js/structs/__tests__/DSLExpression-test.js, src/js/structs/__tests__/DSLFilterList-test.js, src/resources/grammar/__tests__/SearchDSL-test.js
---
⚠️  ~~Depends on #1496~~ Merged
---
[Diff between 1496 & This](https://github.com/dcos/dcos-ui/compare/ic/feat/DCOS-10470-new-dsl-components-5...ic/feat/DCOS-10470-new-dsl-components-6)
This PR introduces the `DSLFilterField` and it integrates it in the `ServiceTreeView`:
=> DCOS-10470: [6/10] Integrating plain-text DSL input field

plugins/nodes/src/js/components/NodeBreadcrumbs.js, plugins/nodes/src/js/pages/NodesOverview.js, plugins/nodes/src/js/pages/NodesPage.js, plugins/nodes/src/js/pages/__tests__/NodeDetailPage-test.js, plugins/nodes/src/js/pages/nodes/NodeDetailPage.js, plugins/nodes/src/js/pages/nodes/NodeDetailTaskTab.js, plugins/nodes/src/js/pages/nodes/NodesTaskDetailPage.js, plugins/nodes/src/js/routes/nodes.js
=> [9/11] Nodes headers 

plugins/oauth/hooks.js, src/js/components/ClusterName.js
This PR replaces the cluster name with the user's full name if the cluster name is `undefined`. (In this case the user's full name is actually `Restricted Username 🚫`)
Before:
After:
=> DCOS-11817: Handle undefined cluster name

plugins/nodes/src/js/pages/NodesOverview.js, plugins/services/src/js/pages/services/DeploymentsTab.js, src/js/pages/JobsPage.js, src/js/pages/jobs/JobsTab.js
This PR is the outcome of a design review of `feature/page-header` before #1520 is ready for merge.
=> [10/11] Page header finesse

plugins/services/src/js/containers/service-detail/ServiceDetail.js, plugins/services/src/js/containers/services/ServicesTable.js, plugins/services/src/js/structs/Application.js
We no longer show the scale button for services containing a label `service.labels.MARATHON_SINGLE_INSTANCE_APP`.
https://mesosphere.atlassian.net/browse/DCOS-9284
=> Removing scale button for SINGLE_INSTANCE_APPS

plugins/services/src/js/components/ServiceConfigBaseSectionDisplay.js, plugins/services/src/js/components/ServiceConfigDisplay.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/constants/ContainerConstants.js, plugins/services/src/js/reducers/serviceForm/Container.js, plugins/services/src/js/service-configuration/GeneralServiceConfigSection.js, plugins/services/src/js/service-configuration/HealthChecksServiceConfigSection.js, plugins/services/src/js/service-configuration/LabelsServiceConfigSection.js, plugins/services/src/js/service-configuration/NetworkingServiceConfigSection.js, plugins/services/src/js/service-configuration/PodContainerArtifactsConfigSection.js, plugins/services/src/js/service-configuration/PodContainerConfigSection.js, plugins/services/src/js/service-configuration/PodContainersConfigSection.js, plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js, plugins/services/src/js/service-configuration/PodGeneralConfigSection.js, plugins/services/src/js/service-configuration/PodHealthChecksConfigSection.js, plugins/services/src/js/service-configuration/PodLabelsConfigSection.js, plugins/services/src/js/service-configuration/PodNetworkConfigSection.js, plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js, plugins/services/src/js/service-configuration/PodStorageConfigSection.js, plugins/services/src/js/service-configuration/StorageServiceConfigSection.js, plugins/services/src/js/utils/ServiceConfigDisplayUtil.js
=> Clean up: config display files

plugins/services/src/js/components/ServiceBreadcrumbs.js, src/styles/views/services/styles.less, src/styles/views/services/variables.less
This PR adds the `HealthBar` component to `ServiceBreadcrumbs`.
=> Add service status to ServiceBreadcrumbs

plugins/services/src/js/containers/service-detail/ServiceDetail.js, plugins/services/src/js/containers/services/ServicesTable.js
https://mesosphere.atlassian.net/browse/DCOS-9723
=> Removing Destroy action for DCOS Frameworks

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/modals/CreateServiceJsonOnly.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/serviceForm/IpAddress.js, plugins/services/src/js/reducers/serviceForm/PortDefinitions.js, plugins/services/src/js/validators/MarathonAppValidators.js, plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
---
~⚠️  This PR is based on #1371 and will need a rebase~
---
This PR introduces the `MarathonAppValidators` validator that will provide the high-level marathon validation errors. For this purpose, I am importing the validations from the [`AppDefinition.scala`](https://github.com/mesosphere/marathon/blob/08bc0aed722ad9f3e989a597cb264a994387756f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala) on marathon.
The following functions are so far imported:
=> DCOS-11642: High-level marathon error handlers

plugins/services/src/js/components/modals/KillPodInstanceModal.js, plugins/services/src/js/components/modals/KillTaskModal.js, plugins/services/src/js/containers/pod-instances/PodInstancesView.js, plugins/services/src/js/containers/tasks/TasksView.js
Task/instance action buttons changed from "Kill" and "Kill and Scale" to "Restart" and "Stop".
https://mesosphere.atlassian.net/browse/DCOS-10693
=> Update button copy and style for task restart/stop

plugins/services/src/js/containers/pod-instances/PodInstancesContainer.js
This PR fixes a regression by passing `pod` to modals.
Quickfix™ ✨
=> DCOS-11962: Pass pod to modals

plugins/nodes/src/js/components/NodeBreadcrumbs.js, plugins/services/src/js/components/ServiceBreadcrumbs.js, plugins/services/src/js/pages/services/DeploymentsTab.js, src/js/components/breadcrumbs/JobsBreadcrumbs.js, src/js/pages/NetworkPage.js, src/js/pages/network/VirtualNetworksTab.js, src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskPage.js, src/js/pages/system/OrganizationTab.js, src/js/pages/system/OverviewDetailTab.js, src/js/pages/system/RepositoriesTab.js, src/js/pages/system/UnitsHealthDetail.js, src/js/pages/system/UnitsHealthNodeDetail.js, src/js/pages/system/UnitsHealthTab.js, src/js/pages/system/UsersPage.js, src/js/pages/universe/InstalledPackagesTab.js, src/js/pages/universe/PackageDetailTab.js, src/js/pages/universe/PackagesTab.js
This PR adds a leading slash to breadcrumbs, because otherwise one can notice a jump in the address bar.
=> DCOS-11960: Add missing leading slash

src/js/utils/DSLUpdateUtil.js, src/js/utils/DSLUtil.js, src/js/utils/__tests__/DSLUpdateUtil-test.js, src/js/utils/__tests__/DSLUtil-test.js
This PR introduces the `DSLUtil` for processing prop types and high-level DSL AST operations and the `DSLUpdateUtil` that provides the utilities for dynamically updating DSL expressions.
=> DCOS-10470: [8/10] Introducing utilities to operate on DSL expressions

plugins/services/src/js/components/forms/HealthChecksFormSection.js, plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js, plugins/services/src/js/components/forms/PodContainerServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/serviceForm/Containers.js, plugins/services/src/js/reducers/serviceForm/MultiContainerHealthChecks.js
This introduces HealthChecks for Multi Containers
This does include commits from #1502
=> DCOS-10982:  Add healthchecks for multi containers

plugins/services/src/js/components/forms/MultiContainerEnvironmentFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/components/modals/NewCreateServiceModalServicePicker.js
---
ℹ️   _This branch depends on features that will be introduced with ~~#1502~~ and ~~#1506~~._
---
This reintroduces the pod option in the picker and excludes the mount point for multi containers.
=> [multiContainer] add service picker and env vars

plugins/nodes/src/js/pages/nodes/NodesTaskDetailPage.js, plugins/nodes/src/js/routes/nodes.js, plugins/services/src/js/components/LogView.js, plugins/services/src/js/components/MesosLogView.js, plugins/services/src/js/pages/task-details/ServiceTaskDetailPage.js, plugins/services/src/js/pages/task-details/TaskLogsTab.js, plugins/services/src/js/routes/services.js, src/js/components/Page.js, src/js/pages/jobs/JobTaskDetailPage.js, src/js/pages/network/virtual-network-detail/VirtualNetworkTaskPage.js, src/js/routes/factories/network.js, src/js/routes/jobs.js
This PR fixes the task detail routes
NB: @jfurrow @rcorral You should be added to an _open_ cluster that has logs, if you want to check it out
=> Bug fix: Fixing log and file viewer routes, ref. DCOS-11948

plugins/services/src/js/components/dsl/FuzzyTextDSLSection.js, plugins/services/src/js/components/dsl/ServiceHealthDSLSection.js, plugins/services/src/js/components/dsl/ServiceStatusDSLSection.js, plugins/services/src/js/containers/services/ServiceTreeView.js, src/js/components/DSLFilterField.js, src/js/components/DSLForm.js, src/js/components/DSLFormDropdownPanel.js, src/js/components/DSLFormWithExpressionUpdates.js, src/js/components/DSLInputField.js, src/js/constants/DSLUpdatePolicy.js, src/js/structs/DSLExpression.js, src/js/utils/DSLUpdateUtil.js, src/js/utils/DSLUtil.js, src/js/utils/__tests__/DSLUpdateUtil-test.js, src/styles/components/dropdown-panels/styles.less, src/styles/components/dsl-dropdown-panel/styles.less, src/styles/components/dsl-dropdown-panel/variables.less, src/styles/components/form-group/styles.less, src/styles/components/form-group/variables.less, src/styles/index.less
This PR introduces the form UI to the `DSLFilterField`
=> DCOS-10470: [9/10] Introducing form-dropdown to DSLFilterField

plugins/services/src/js/components/forms/VolumeMountFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/JSONParser.js, plugins/services/src/js/reducers/JSONReducers.js, plugins/services/src/js/reducers/serviceForm/Containers.js, plugins/services/src/js/reducers/serviceForm/VolumeMounts.js, plugins/services/src/js/reducers/serviceForm/__tests__/VolumeMounts-test.js, plugins/services/src/js/utils/ServiceConfigDisplayUtil.js
~~based on https://github.com/dcos/dcos-ui/pull/1528~~ Merged
=> DCOS-10984: volume mounts

src/js/components/CosmosErrorMessage.js
https://mesosphere.atlassian.net/browse/DCOS-11610
cc/ @wavesoft - looks like you updated this last and I want to make sure I'm not missing something!
=> DCOS-11610: Fix uninformative Cosmos Respository Errors

scripts/pre-install
Upgrade to the latest Marathon release, which includes fixes for 
mesosphere/marathon#4817 and mesosphere/marathon#4811.
=> Upgrade Marathon to 1.4.0-RC2

plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, src/js/components/modals/FullScreenModal.js, src/js/utils/ScrollbarUtil.js, src/styles/components/modal/styles.less
~~This depends on #1567.~~
This PR separates the scrolling of the two containers.
=> [2 of 3]: DCOS-11542: Independent scrolling of form and JSON editor in ServiceCreateModal

plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerNetwork-test.js
Follow up PR to: https://github.com/dcos/dcos-ui/pull/1584
This PR fixes test descriptions to better describe expected results
=> Updating test descriptions

plugins/services/src/js/pages/__tests__/DeploymentsTab-test.js, src/js/components/Page.js, src/js/pages/universe/__tests__/PackageDetailTab-test.js, src/js/pages/universe/__tests__/PackagesTab-test.js, src/js/plugin-bridge/PluginModules.js
~~Depends on #1567.~~ This just implements `FluidGeminiScrollbar` in `Page`
=> [3 of 3] Implement FluidGeminiScrollbar in Page

plugins/services/src/js/components/RecentOffersSummary.js, src/styles/components/funnel-graph/styles.less, src/styles/components/funnel-graph/variables.less, src/styles/index.less
This PR implements the new design for the declined offers summary:
=> DCOS-12045: New funnel graphic for declined offers summary

plugins/services/src/js/components/modals/NewCreateServiceModal.js
=> DCOS-12145: Fix force edit for service

plugins/services/src/js/components/ConfigurationMapMultilineValue.js, plugins/services/src/js/service-configuration/PodContainerConfigSection.js, plugins/services/src/js/service-configuration/PodGeneralConfigSection.js
This PR fixes the resource display in the pod container review section (and it also does some minor clean-ups in other places too)
=> DCOS-11844: Fixing resources in pod containers

scripts/post-rewrite, scripts/pre-install, scripts/pre-push, scripts/utils/git
Let's liberate `git push` and address the problem of rebase artifacts the right way 💪 
PS. don't forget to unlink `pre-push` afterwards
=> DCOS-12288: Replace pre-push with post-rewrite

plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js, plugins/services/src/js/components/forms/PodContainerServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/components/modals/ServiceModals.js, plugins/services/src/js/reducers/serviceForm/Containers.js, src/js/utils/ParserUtil.js
This pr contains changes which @mlunoe requested in another PR.
#1524
=> [Multi Container] stylistic adjustments

plugins/services/src/js/containers/services/ServicesTable.js, plugins/services/src/js/structs/ServiceTree.js
~Boy-scout clean-up went wrong :rotating_light:~
Boy-scout clean-up done right 👮
=> Restoring '!!service.getQueue' in ServicesTable.js

plugins/services/src/js/containers/tasks/TaskTable.js
Fixing previously broken link.
=> Fix broken link to logs

src/styles/components/form-group/styles.less, src/styles/components/form-group/variables.less, src/styles/index.less
This PR removes a file that I erroneously added yesterday.
I added two `form-group` stylesheets yesterday; one at `styles/form-group` and one at `styles/form-elements/form-group`. I meant to remove this one. :(
=> Bug: Fix form field margins

plugins/services/src/js/components/LogView.js, src/js/stores/SystemLogStore.js
=> Handle empty log by sending update if nothing has happened

plugins/services/src/js/reducers/JSONMultiContainerReducers.js, plugins/services/src/js/reducers/JSONParser.js, plugins/services/src/js/reducers/serviceForm/MultiContainerScaling.js, plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerScaling-test.js
This PR adds the missing scaling reducers for the multi-container form.
=> DCOS-12335: Fix pod scaling

plugins/services/src/js/constants/DefaultPod.js
Add Default scaling value for pods.
=> [Multi container]: add default scaling

plugins/services/src/js/containers/tasks/TasksView.js
=> Fix task view indentation

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js, plugins/services/src/js/reducers/serviceForm/Containers.js, plugins/services/src/js/reducers/serviceForm/MultiContainerNetwork.js, plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerNetwork-test.js
This fixes the network reducer to work with an array structure.
close DCOS-12336 DCOS-12341
=> DCOS-12336, DCOS-12341: networks reducer fix

plugins/services/src/js/service-configuration/ServiceConfigDisplay.js
This PR adds support for top-level error messages with an empty path.
=> DCOS-12292: Display all errors on the review screen

plugins/services/src/js/components/ConfigurationMapEditAction.js, plugins/services/src/js/components/ConfigurationMapTable.js, plugins/services/src/js/components/__tests__/ConfigurationMapTable-test.js, plugins/services/src/js/service-configuration/PodContainerArtifactsConfigSection.js, plugins/services/src/js/service-configuration/PodContainerConfigSection.js, plugins/services/src/js/service-configuration/PodContainersConfigSection.js, plugins/services/src/js/service-configuration/PodEnvironmentVariablesConfigSection.js, plugins/services/src/js/service-configuration/PodGeneralConfigSection.js, plugins/services/src/js/service-configuration/PodHealthChecksConfigSection.js, plugins/services/src/js/service-configuration/PodLabelsConfigSection.js, plugins/services/src/js/service-configuration/PodNetworkConfigSection.js, plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js, plugins/services/src/js/service-configuration/PodStorageConfigSection.js
~~1. https://github.com/dcos/dcos-ui/pull/1597~~ Merged
~~2. https://github.com/dcos/dcos-ui/pull/1598~~ Merged
3. https://github.com/dcos/dcos-ui/pull/1599 <--
This is the final PR of the three. This adds the the edit link to the pod review sections.
For reviewers here is [the diff](https://github.com/dcos/dcos-ui/compare/mlunoe/feature/DCOS-11676-clean-up-pod-review-sections...mlunoe/feature/DCOS-11676-add-edit-field-to-pod-review-page?expand=1) to review!
=> [Service Review Edit link 3 of 3] Add edit field to pod review page, ref. DCOS-11676

src/js/pages/system/OverviewDetailTab.js
This PR adds the version number to the cluster config screen.
=> DCOS-12279: Display product version in cluster configuration page

plugins/services/src/js/components/forms/VolumesFormSection.js, plugins/services/src/js/reducers/JSONConfigReducers.js, plugins/services/src/js/reducers/serviceForm/Container.js, plugins/services/src/js/reducers/serviceForm/ExternalVolumes.js, plugins/services/src/js/reducers/serviceForm/Volumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/ExternalVolumes-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/Volumes-test.js
This introduces size to external volumes.
Fixes volumes on root level in the reducer.
And also fixes container type to be set with external volumes.
=> DCOS-11750: add size to external volumes

tests/pages/services/ServiceVersions-cy.js
=> Fixing integration tests for ServiceVersions

src/js/schemas/job-schema/Schedule.js
Adjust the create job form CRON example.
Closes DCOS-11887
=> DCOS-11887: Fix job schedule CRON example

tests/pages/services/ServiceFormModal-cy.js
=> Fixing integration tests for ServiceFormModal

tests/pages/jobs/JobActions-cy.js
=> Fixing integration tests for JobActions

.eslintrc, gulpfile.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js, plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js, plugins/services/src/js/components/forms/MultiContianerVolumesFormSection.js, plugins/services/src/js/components/forms/PodContainerServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModal.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/reducers/serviceForm/Containers.js, plugins/services/src/js/reducers/serviceForm/MultiContainerNetwork.js, plugins/services/src/js/reducers/serviceForm/MultiContainerScaling.js, plugins/services/src/js/reducers/serviceForm/MultiContainerVolumes.js, plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerNetwork-test.js, plugins/services/src/js/reducers/serviceForm/__tests__/MultiContainerScaling-test.js, src/resources/grammar/__tests__/SearchDSL-test.js, tests/pages/services/ServiceFormModal-cy.js, tests/pages/system/overview/repositories/RepositoriesTab-cy.js, webpack/plugins/svg-compiler-plugin.js, webpack/webpack.config.babel.js, webpack/webpack.dev.babel.js, webpack/webpack.production.babel.js, webpack/webpack.test.js
This PR fixes some eslint issues in the multiple container feature branch
=> Eslint fix up

tests/pages/services/VolumesTable-cy.js
=> Fixing integration tests for VolumesTable

plugins/services/src/js/service-configuration/PodNetworkConfigSection.js, plugins/services/src/js/utils/__tests__/TaskUtil-test.js, src/js/components/modals/ImageViewerModal.js
=> Fix some creative spellings of container

plugins/services/src/js/components/forms/MultiContianerVolumesFormSection.js
For your convenience, here's the [wiktionary page on ephemeral](https://en.wiktionary.org/wiki/ephemeral).
=> Fix spelling of 'Ephemeral'

plugins/services/src/js/service-configuration/ServiceHealthChecksConfigSection.js
=> [review screen] Healthchecks: Add fallback text to max failures column

src/js/pages/UniversePage.js
It does what it says on the tin!
=> Update 'Packages' sidebar label to 'Universe'

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js, plugins/services/src/js/components/forms/PodContainerServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/constants/DefaultApp.js, plugins/services/src/js/constants/DefaultPod.js, plugins/services/src/js/reducers/serviceForm/Containers.js, plugins/services/src/js/reducers/serviceForm/__tests__/Containers-test.js, tests/pages/services/ServiceFormModal-cy.js
This PR fixes an inconsistency issue, where we would toggle `Enabled`/`Disabled`, instead of having it be `Enabled` all the time.
It fixes the interaction with numbers to be a little more user-friendly, and an issue, where users could not enter a small number like 0.03.
Finally, it passes down errors to container sub-sections correctly.
=> Bug fix: Minor issues in multiple container feature branch

src/js/components/FilterInputText.js
This is what was throwing the error on the packages page.
=> Make unrequired field not required anymore

plugins/services/src/js/components/forms/ContainerServiceFormSection.js, plugins/services/src/js/components/forms/PodContainerServiceFormSection.js, plugins/services/src/js/components/forms/VolumesFormSection.js, src/styles/components/typography/styles.less
=> Make sure to not uppercase resource labels

tests/pages/universe/packages/PackagesTab-cy.js
=> Reenable integration tests for PackagesTab

foundation-ui/utils/ResourceTableUtil.js, plugins/services/src/js/components/modals/KillTaskModal.js, plugins/services/src/js/containers/tasks/TasksView.js
Here are the places that have been changed:
=> Using lower case when using task in a sentence, ref. DCOS-11931

tests/pages/universe/installed/InstalledPackagesTab-cy.js
=> Fix integration tests for InstalledPackagesTab

tests/pages/universe/packages/package/PackageTab-cy.js
=> Fix integration tests for PackageTab

tests/pages/universe/packages/InstallPackageModal-cy.js
=> Fix integration tests for InstallPackageModal

jest/gen-config.js, tests/pages/services/ServiceSearchFilter-cy.js, tests/utils/__tests__/testUtil-test.js, tests/utils/testUtil.js
=> Fix integration tests for ServiceSearchFilter

plugins/oauth/hooks.js, src/js/components/modals/CliInstallModal.js
Splice `dcos auth login` command step into the CLI Install instructions when authentication is enabled.
https://mesosphere.atlassian.net/browse/DCOS-10878
=> DCOS-10878: Update CLI Install Instructions

tests/pages/dashboard/ComponentsList-cy.js
=> Reenable a disabled test

plugins/services/src/js/components/modals/ServiceDestroyModal.js, plugins/services/src/js/containers/service-detail/ServiceDetail.js, plugins/services/src/js/containers/services/ServicesTable.js
Restored destroy action for Frameworks. Also adjusts message in the destroy service modal according to https://mesosphere.atlassian.net/browse/DCOS-12269
=> Restore destroy action for frameworks

plugins/services/src/js/components/DeclinedOffersTable.js, plugins/services/src/js/containers/tasks/ServiceTasksContainer.js, src/js/events/MesosStateActions.js, src/js/plugin-bridge/PluginModules.js, src/js/stores/MesosStateStore.js
=> Adding filter for mesos state error in Services

src/js/components/modals/JobFormModal.js
Fix the wipe of unknown values from the job form.
Closes DCOS-11482
=> DCOS-11482: Backport fix for unknown values wipe

src/js/schemas/job-schema/Schedule.js
Adjust the job schedule CRON example.
Closes DCOS-11887
=> DCOS-11887: Backport job schedule CRON example fix

plugins/services/src/js/utils/ServiceUtil.js
=> Fix newline before return linting error

plugins/services/src/js/components/ServiceBreadcrumbs.js
https://mesosphere.atlassian.net/browse/DCOS-12457
=> DCOS-12457: Remove header summary for empty group

plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
=> DCOS-12640: Remove network name if not available review screen

plugins/services/src/js/components/forms/EnvironmentFormSection.js, plugins/services/src/js/components/forms/GeneralServiceFormSection.js, plugins/services/src/js/components/modals/NewCreateServiceModalForm.js, plugins/services/src/js/constants/OperatorTypes.js, plugins/services/src/js/reducers/serviceForm/Constraints.js
This PR updates the copy, so it aligns with documentation requirements.
Make environment variable fields bigger:
Only show "service" in plural if there are multiple containers:
Update copy for service ID:
Update copy and order og container runtimes:
Update placement constraints copy and show/hide copy and parameter field when needed/not needed
=> DCOS-12646: Update help text copy in service create form

plugins/services/src/js/components/forms/VolumesFormSection.js
Align the add volume button labels with the rest of the form.
=> Adjust add volume button labels

tests/pages/services/ServiceActions-cy.js
=> Fix ServiceActions integration tests
