dcos/dcos-ui

plugins/services/src/js/components/modals/ServiceModals.js

Fix intermittent error when deleting a service and the page throws an error blocking
the user from navigating/using the application and forcing to refresh
Closes DCOS-19743 (https://jira.mesosphere.com/browse/DCOS-19743)
**Checklist**

fix(ServiceModals) error on delete

---

plugins/services/src/js/components/ServiceStatusIcon.js
src/styles/components/tooltip/styles.less

Tooltips on running service icons had a fixed width which meant there was extra unwanted space in the tooltip.
This PR removes the fixed width for these status tooltips and introduces a max-width for .tooltip components.
Before
After

DCOS_OSS-2058: Fix running service tooltip width

---

plugins/services/src/js/components/forms/ContainerServiceFormAdvancedSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerFormAdvancedSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/PlacementSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/components/modals/CreateServiceModal.js
plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/service-configuration/PodPlacementConstraintsConfigSection.js
plugins/services/src/js/service-configuration/ServiceGeneralConfigSection.js
plugins/services/src/js/service-configuration/ServicePlacementConstraintsConfigSection.js
src/js/components/CreateServiceModalServicePickerOptionContent.js
tests/pages/services/ServiceFormModal-cy.js

With the new CNVS update and UI Kit alignment we've decided to focus on using h1,h2,h3.
This PR updates the headings in the run service flow and review screens. It also fixes other minor bugs.
* H2s > H1s
* H3s > H2s
* H4s > H3s
* Fixed cancel button alignment on dismiss alert
* Fixed uppercase placement labels
It does not fix the hierarchy issues with package configuration (this is slightly more complicated and will be tracked separately).
Before
After

Improve visual hierarchy in new service config and review screens

---

src/styles/components/status-bar/styles.less

Add `backface-visibility` property to address jitter in Google Chrome. The property does not affect 2D transforms, which have no perspective in any other browser but Google Chrome. It's the least intrusive way to force Chrome to render the respective layers properly.
| Before | After |
| - | - |
| ![](https://user-images.githubusercontent.com/647035/35150571-2c4223a8-fd1b-11e7-8772-d0e01dda5e01.gif) | ![jitter-after mov](https://user-images.githubusercontent.com/647035/35150579-358b12da-fd1b-11e7-8399-6f79a199d625.gif) |
Closes DCOS-20392

fix(status-bar): adjust styling to address jitter

---

plugins/services/src/js/containers/tasks/TaskTable.js

Problem: Table columns that have links should not have purple styling. Too overwhelming to have all links colored purple. In service detail views the task list has purple links. [See example](https://cl.ly/1D0z0e2d0C2y)
What was changed: Made the "table-cell-link-primary" the first class on the link. [Here's what it looks like now. ](https://cl.ly/3N3s443R0T1E)
Closes [DCOS_OSS-2057 ](https://jira.mesosphere.com/browse/DCOS_OSS-2057)
**Checklist**

refactor(tables): fix purple links in table

---

plugins/services/src/js/components/modals/CreateServiceModal.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Residency.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Residency-test.js
plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js

This fixes a legacy issue which was introduced into marathon a very long time ago. The issue was when you wanted to create a app with a persistent volume you needed to also define the residency setting, otherwise the volume would be present but not persistent ... unfortunately there was only one residency setting and changing it did not have any other purpose. With the latest changes Marathon is going to set residency if there is a persistent volume defined. So it is not mandatory to add it via the ui. 
With this PR we are removing the validators which were checking if the residency was set. And also we are removing the logic which was adding residency if a persistent volume was added. This has been done for single container and multi container services.
To test this take this JSON: …

DCOS-20475: Fix residency validators

---

system-tests/Systemtests
system-tests/_scripts/launch-cluster.sh
system-tests/_scripts/sandbox-setup.sh
system-tests/_scripts/setup.sh
system-tests/cypress.json
system-tests/dashboard/tests.yml
system-tests/jobs/tests.yml
system-tests/services/tests.yml
system-tests/universe/tests.yml

NB! System tests won't be green with the fix. The PR just fixes the setup!
Cypress recommends installing 1.4.1 as a dependency. In previous releases of dcos-ui we had cypress installed globally. To keep backward compatibility I managed to symlink cypress in the test environment.
**Why having a separate `sandbox-setup` script?**
`setup` is being executed _inside_ the shell isolation and doesn't have a way out I could find. `sandbox-setup` is being executed outside of isolation and has all the info about the sandbox. So I construct link to cypress and symlink it into sandbox.
I also fixed various bugs here and there.
Please go to Jenkins and check logs for the system-tests job. It should run cypress 1.4.1
Should look like something like this:
```
DEBUG 2018-01-24 15:42:35 …
```

DCOS-20493: fix system-tests cypress

---

plugins/services/src/js/constants/StatusSorting.js
plugins/services/src/js/utils/ServiceTableUtil.js
plugins/services/src/js/utils/__tests__/ServiceTableUtil-test.js

Fix Service status column sorting
Closes DCOS-19732
- Go to service page
- Start a couple services with different statuses (Deploying, Running, Recovering, etc)
- Click the status name/header column
- You will see the service page sort by the order below
_ps: be aware that sometimes they can have the same status but might have the warning icon which is expected and shouldn't change anything._
Order:
```
Recovering
Deploying
Deleting
Stopped
Running
NA
```
**Checklist**

fix(ServiceTableUtil): fix status sorting

---

src/js/stores/MesosStateStore.js
tests/pages/services/ServiceReviewScreen-cy.js

This PR addresses the duplicated tasks ids issue.
`this.stream` went missing but we're using it as a check whether we have to subscribe or not here https://github.com/dcos/dcos-ui/compare/drozhkov/fix-mesos-stream-resubscribe?expand=1#diff-22eec13077e445e982cd1a9232667028R65
Closes DCOS-20625

🚨 Save stream to prevent resubscribes

---

tests/pages/services/ServiceActions-cy.js

This test has been flaky for a while, due to the keyboard input on cypress being unreliable. This changes the test to be more simple and no longer flaky (hopefully!!).
**Checklist**

fix(ServiceActions): rewrite flaky test

---

.dockerignore

We currently send too much information into our docker container.
This ignores the most basic folders to reduce the amount needed to be
send to the docker deamon.
Effects:
Before: ```Sending build context to Docker daemon  862.8MB``` (super slow)
After: ```Sending build context to Docker daemon   24.3MB``` (super fast)

chore(Docker): add dockerignore

---

plugins/services/src/js/structs/ApplicationSpec.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/ApplicationSpec-test.js
plugins/services/src/js/structs/__tests__/Framework-test.js

Default missing resource declaration to 0 to fix framework resource aggregation.
Spotted on soak cluster when there are few frameworks running in a group group would report 0 Disk even though frameworks inside the group report some disk usage.
Closes DCOS-20672

DCOS-20672: fix(structs): add defaults to resources

---

plugins/services/src/js/structs/Framework.js
src/js/stores/ConfigStore.js
src/js/stores/GetSetBaseStore.js
src/js/stores/MesosStateStore.js
src/js/stores/MesosStream/parsers/__tests__/fixtures/getTasksMessage.json
src/js/stores/MesosStream/parsers/__tests__/tasks-test.js
src/js/stores/MesosStream/parsers/state.js
src/js/stores/MesosStream/parsers/subscribed.js
src/js/stores/MesosStream/parsers/tasks.js
src/js/stores/__tests__/MesosStateStore-test.js
src/js/utils/MesosStateUtil.js

This PR adds a simple memoize utility and memoize the `cleanJobJSON`, `cleanServiceJSON` and `copyRawObject` utils to address performance issues due to very frequent invocations. It also adjusts the `flagSDKTask` utility to only flag tasks that aren't already flagged to further improve the performance. 
Closes DCOS-20485

DCOS-20485: Adjust implementation to improve performance

---

src/styles/components/loaders/styles.less
src/styles/components/modal/full-screen/styles.less

This fixes the flashes of dark-grey when opening and closing full screen modals. 
Two parts:
1) Make the loader background white. This because the background of DC/OS is now dark-grey, so now we must manually set the loader background to white. 
2) Removing animations from the full screen modal. This is smoother, and prevents short flashing of the dark-grey background.
**Before**:
**After**:
Closes DCOS-20343
Thanks for @ashenden for direction on this.
**Checklist**

fix(FullScreenModal): remove animation and fix loader

---

plugins/services/src/js/containers/pod-debug/PodDebugContainer.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js

When a deployment has issues we show a yellow yield icon next to the service to indicate there is an issue. When user clicks on the icon for more info they are shown a red danger message. It is not obvious that these are related given that red has different permutations to yellow. This has come up in a few usability tests.
Red indicates something has failed or is definitely wrong. In this situation it hasn't failed and we can't tell for sure if it is definitely wrong e.g. resources may become available or an offer is eventually accepted.
This PR changes the message from danger (red) to warning (yellow). It also removes the yield icon to align with our other use of warning messages.
Before 
After

DCOS_OSS-2062: Change debug message from danger to warning

---

Dockerfile
Jenkinsfile.release
scripts/ci/upload-build

With this PR a new jenkinsfile is introduced that only handles a build of our UI together with an upload to S3. This is only triggered once you triggered a build with the checkmark on:
What happens is that later stages are excluded, see second build by default. If its  triggered by hand we go off to build a release:
The release is send to the downloads.mesosphere.io bucket for later use in the main repo. See docs/docs#2367 as an example.
**Checklist**

DCOS-20468: upload build to S3 bucket

---

cypress.json
system-tests/cypress.json

Cypress isn't able to open self signed HTTPS pages unless this option is disabled. https://github.com/cypress-io/cypress/issues/771
Blocks https://github.com/mesosphere/dcos-ui-plugins-private/pull/729

Disable chrome security to allow self signed https

---

src/js/pages/catalog/PackageDetailTab.js

Fix missing version query lost in latest changes made in PackageDetailTab
Closes DCOS-20939
- Go to catalog page
- select a package
- on package detail choose an older version in the dropdown located at the top by the package name
- Go to Review & Run
- Run the package and go to package detail > configuration tab and note the version installed
**Checklist**

fix(PackageDetailTab) add version query

---

src/js/pages/catalog/PackageDetailTab.js

---
↩️  _This PR back-ports a fix to release/1.11 introduced with #2705._
---
> Fix missing version query lost in latest changes made in PackageDetailTab
> 
> Closes DCOS-20939
> 
> How to test:
> 
> * Go to catalog page
> * select a package
> * on package detail choose an older version in the dropdown located at the top by the package name
> * Go to Review & Run
> * Run the package and go to package detail > configuration tab and note the version installed

↩️  fix(PackageDetailTab): add version query

---

plugins/services/src/js/validators/MarathonAppValidators.js
plugins/services/src/js/validators/__tests__/MarathonAppValidators-test.js
src/js/utils/ErrorMessageUtil.js

JIRA: https://jira.mesosphere.com/browse/DCOS-14753
---
This adds a new `unanchored` property to errors which enable the `ErrorMessageUtil` to remove the path from the displayed message.
This change will allow the ErrorAlert to de-duplicate these messages.
Example:
```
cmd: You must specify a command, an argument or a container
args: You must specify a command, an argument or a container
container.docker.image: You must specify a command, an argument or a container
```
becomes
```
You must specify a command, an argument or a container
```

DCOS-14753: adds unanchored property to marathon errors

---

docker-compose.yml

This PR makes `AWS_PROFILE` created by `maws` to be useful inside `docker-compose`
1. Just do `$ maws`
2. export given `AWS_PROFILE`
3. launch docker-compose

Use AWS_PROFILE instead of credentials

---

Jenkinsfile.release
scripts/ci/upload-build

this commit changes the filename of a release to a, what we hope, more rubust one.
the new name is built up with different parts:
1. dcos-ui branchname
DCOS introduces new features so old versions which can lead to
an updated minor version, for this reason and to prevent
conflicts, we have chosen to prepent the "DCOS Target" as the
first name of the filename
2. dcos-ui-variant
This will define the variant of the built UI.
3. package version
the package version taken from the package.json
4. package version metadata
semver compliant metadata to define the git sha
this release is built from

chore(build): changes filename of release

---

system-tests/services/test-apps.js

Skip failing test. Not possible to verify without having MesosStream working in cypress thus no point in running the test ATM.

chore(system-tests): skip test involving MesosStream

---

Jenkinsfile.release
scripts/ci/upload-build

This PR creates a ready-to-be-copied `buildinfo.json` to speed up the bump-process and make it "less manual", whoever creates a bump doesnt have to check for the correct sha or something, just fire up the jenkinsjob and copy & paste the buildoinfo to DCOS.
In the Future we want to automate this even more - step by step 👍

feat(Jenkinsfile.release): creates artifact with correct buildinfo

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Labels.js

This pull request is fixing the labels reducer to support labels with an empty string value.
**To Test:**
You should be able to create an app with:
```JSON
{
"labels": {
"Label": ""
}
}
```
Closes DCOS-19693

fix(labelsReducer): fix labels reducer to accept empty strings

---

src/js/pages/system/ComponentsUnitsHealthNodeDetailPage.js

Fix error when navigating to a node in components page then visiting the node detail
and trying to click on the node link in the breadcrumb throws an error
Closes DCOS-20975
**How to test**
- Go to components
- Click on a service
- In the service detail click on the active node
- **test** click on the node ip on the breadcrumb
**expected result:** Stay in the same page and don't throw error on console
**Checklist**

fix(UnitsHealthNodeDetail) node link throwing error

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Constraints.js
plugins/services/src/js/reducers/serviceForm/common/Constraints.js
plugins/services/src/js/reducers/serviceForm/common/__tests__/Constraints-test.js
src/js/components/PlacementConstraintsSchemaField.js

Fixes the mistakes that were introduced by:
https://github.com/dcos/dcos-ui/pull/2671
- The Error type is more precise to detect than {error: true}
- Better naming

style(PlacementConstraintsSchemaField): fixes naming and error handling

---

src/js/structs/UniversePackage.js
src/js/structs/__tests__/UniversePackage-test.js

⚠️ backport me
When there is no type, use `type: "object"`. This fixes an issue with mysql and postgres not including this field in their schema and then breaking our form data init because of the missing type. We use [this code](https://github.com/mozilla-services/react-jsonschema-form/blob/51d403ab448326183f58b5cc7c2c750c200f0242/src/utils.js#L139) to parse the initial form data and it expects a type. 
**Testing**:
1. Deploy mysql and postgres from catalog. There should be no issues rendering the form. The configuration tab of these running services should also render properly.
2. Try deploying a few other services to become confident there is no regression. 
Closes DCOS-21115
**Checklist**

fix(UniversePackage): fallback to type: "object" for config

---

src/js/pages/system/ComponentsUnitsHealthNodeDetailPage.js

Back port of #2717 
Fix error when navigating to a node in components page then visiting the node detail
and trying to click on the node link in the breadcrumb throws an error
Closes DCOS-20975

fix(UnitsHealthNodeDetail): node link throwing error

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js

When deleting a group inside a group, instead of staying inside that group you're being thrown back to the root of the namespace.
Closes DCOS_OSS-1341
**Checklist**

DCOS_OSS-1341: stay in group view when service/group deleted

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

Disable the id input field in the edit form to prevent the user to change a exisiting id.
Closes DCOS-20956

feat(serviceID): disable id field on service edit

---

system-tests/_scripts/setup.sh

I think this has to be done. Hopefully will fix some cluster creation issues on system test.

chore(system-tests): bump to 1.11 for system tests cluster

---

scripts/pre-install
scripts/utils/marathon

looks like the marathon team has changed the folder structure.
to test this run `npm install` and watch for something saying "updating raml files" (looks like there was a `npm run update-raml` command, but it is gone :( )

fix(raml-scripts): updates the download link for the raml files

---

scripts/pre-install
scripts/utils/marathon

1.11 / fix(raml-scripts): updates the download link for the raml files

---

scripts/pre-install
scripts/utils/marathon

Backport 1.10: fix(raml-scripts): updates the download link for the raml files

---

Jenkinsfile

this prevents the pipeline from asking us in the channel.

1.11 / chore(Jenkinsfiles): changes release branch to "master" in jenkinsfile

---

src/js/pages/catalog/PackagesTab.js
src/js/pages/catalog/__tests__/PackagesTab-test.js
src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap

To test it remove all the package repositories of a cluster and go to the Catalog (save your universe url). Add packages back and go look the Catalog again.
Also, anyone know how to make the snapshot smaller, It would be by reducing the number of packages for that particular test, there are about 100 packages and 3500 lines of snapshot :/.
closes DCOS-20309.
If you replace those two components on the PackageTab render method, you can get your snapshot.
**To the finish line**

DCOS-20309 Empty state for catalog

---

scripts/find-broken-links

Previously was broken and it would stop matching after the port number. This fixes it. Now it simply matches http|https followed by an unlimited amount of (sane) valid URL characters.
Testing:
https://regex101.com/r/KwvvN5/1
**Checklist**

[backport 1.11] fix(find-broken-links): fix regex in script

---

plugins/services/src/js/pages/EditFrameworkConfiguration.js
src/js/components/FrameworkConfiguration.js
system-tests/universe/test-universe.js
tests/pages/catalog/packages/package/PackageTab-cy.js

Based on feedback from users, we want to open the service to the form when deploying. This also makes it the same as when editing a running framework.
Closes DCOS-19301
**Checklist**

feat(FrameworkConfiguration): open to form when deploying

---

plugins/services/src/js/components/modals/DisabledGroupDestroyModal.js

Before: 
After: 
Changed width and button style of the modal to be consistent with our modal and button styles. 
**Checklist**

refactor(deletegroupmodal): fix width and button style

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Endpoints-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
tests/pages/services/ServiceFormModal-cy.js

Add the vip port input field to the virtual networks of pods Multi container services.
Closes DCOS_OSS-1553

feat(PodEndpoints): Add vip input to virtual networks

---

plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js
plugins/services/src/js/structs/ServiceEndpoint.js
plugins/services/src/js/structs/__tests__/ServiceEndpoint-test.js

Remove spaces from the comma delimited list of endpoints.
This is a big problem for people that want to copy and paste to the terminal. They extra space that we add between the information (address, dns, vip e.t.c), throws errors in some cases when using them as raw input.
**Checklist**

fix(Endpoints): remove spaces from the comma delimited list of endpoints

---

plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js
plugins/services/src/js/structs/ServiceEndpoint.js
plugins/services/src/js/structs/__tests__/ServiceEndpoint-test.js

Remove spaces from the comma delimited list of endpoints.
This is a big problem for people that want to copy and paste to the terminal. They extra space that we add between the information (address, dns, vip e.t.c), throws errors in some cases when using them as raw input.
Backport of https://github.com/dcos/dcos-ui/pull/2754
**Checklist**

[1.11 Backport] DCOS-21304: Remove spaces from endpoints list

---

system-tests/_scripts/setup.sh

[backport 1.11] chore(system-tests): bump to 1.11 for system test cluster

---

plugins/services/src/js/containers/tasks/TaskTable.js
plugins/services/src/js/utils/TaskTableUtil.js
tests/_fixtures/marathon-1-task/mesos-subscribe.js
tests/_fixtures/marathon-1-task/summary.json
tests/_fixtures/marathon-pods/groups.json
tests/pages/nodes/NodesPage-cy.js
tests/pages/services/TasksTable-cy.js

The sorting of the service task tables was broken, this PR aims to fix this. Namely fields that are not in the original JSON of the task type but fetched from other sources to be displayed are not being considered while sorting. As the "tie breaker" argument resorts the table anyways and we normally don't have nice test data for region and zone no one spotted the mistake earlier.
I added stubs for our integration tests for this part, the real change is much smaller than 500 lines.
I also did not refactor the table but let the leaky abstraction be as we plan to rewrite that part soon.
\cc @nLight pinging you so that you are aware of this problem for the next iteration 👍 
**Checklist**

1.11: DCOS-21229: fix sorting in tables

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Endpoints-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
tests/pages/services/ServiceFormModal-cy.js

Add the vip port input field to the virtual networks of Multi container services.
Closes DCOS_OSS-1553

[1.11 Backport] feat(PodEndpoints): Add vip input to virtual networks

---

src/js/components/FrameworkConfigurationForm.js
src/js/components/PlacementConstraintsSchemaField.js
src/js/components/SchemaField.js
src/js/components/__tests__/PlacementConstraintsSchemaFields-test.js
src/js/components/__tests__/__snapshots__/PlacementConstraintsSchemaFields-test.js.snap
src/js/constants/FrameworkConfigurationConstants.js
src/styles/components/form-elements/form-group/styles.less

The purpose of this is to make the framework forms more visually parsable. Changes:
1. Give each TitleField it sizing appropriate to it's location in the json schema. Previously, they were all rendered as `<h2>` for simplicity, but this made it hard to notice which were nested fields.
2. Bigger sizing on Placement Constraints widget label.
3. Capitalize each word in all field labels
4. Extra margin below Placement section to visually separate from rest of form
**Testing**:
1. Turn enterprise off
2. Open the catalog for beta-kafka. Notice the form differences. H1 and H2 and H3 for layers of config headings, and Placement Constraints label is proper size.
Thanks to @leemunroe for suggestions and assistance. 
**Before**:
**After**:
**Checklist**

refactor(SchemaField): improve framework heading sizes

---

plugins/services/src/js/components/modals/CreateServiceModal.js
src/js/components/FrameworkConfiguration.js

This PR adds `button-flush-horizontal` to secondary buttons in the full screen modals. Whenever there is a text button we should remove padding like this so alignment is flush with other grid elements. This can be seen when running a service or configuring a package (Back and Cancel buttons).

DCOS-21158: Add flush horizontal to secondary buttons in full screen form flows

---

Jenkinsfile
scripts/ci/run-integration-tests

This is a proof of concept, please be aware that there is no intention of getting this exact code to master.
**Question**: Will running the tests one by one help us switch back to a smaller jenkins node label? (Currently we use one which is way too big for what we do)
**Other Metrics**:
- How long does the test run take opposed to "normal"?
- Will the flackiness be positively effected by retrying individual files instead of everything?
**How to move forward if this is a success**:
My idea would be to discuss the findings in the team and identify what we need to change in our system test runner to have a similar experience
**How to move forward if this is a failure**:
If we can't get under the 1GB threshold we should discuss about different testing frameworks and see if we can somehow get …

Run integration tests file by file

---

src/styles/components/status-bar/styles.less
src/styles/layout/page-header/breadcrumbs/styles.less

We have some old legacy styles from the dark UI in the status bars. This PR removes the dark line on status bars and removes the CSS that was making the bar smaller in headers. Making these more inline with our UI kit vision.
Before
After
Closes DCOS-21173

DCOS 21173: Update status bar styles

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/ServicePodReviewScreen-cy.js
tests/pages/services/ServiceReviewScreen-cy.js

---
ℹ️ Backport of: #2761  
---
This ~commit~ PR changes the onChange handler of the ServiceForm so that
it no longer implicitly sets state.editingFieldPath, instead a new
internal function `handleFormFocus` is introduced.
Closes DCOS-21122

[Backport:1.11] DCOS-21122: fix(ServiceForm): fixes focus/change/blur behaviour

---

plugins/services/src/js/components/modals/CreateServiceModal.js
system-tests/services/test-apps.js
system-tests/services/test-external-volumes.js
system-tests/services/test-pods.js
tests/pages/services/ServiceFormModal-cy.js

This commit reintroduces the functionality to disable the `Review & Run` Button if an error is
present.
Closes DCOS-20080
**Checklist**

fix(createServiceModal): disabled review and run button

---

plugins/services/src/js/components/ConfigurationMapBooleanValue.js
plugins/services/src/js/components/ConfigurationMapDurationValue.js
plugins/services/src/js/components/ConfigurationMapMultilineValue.js
plugins/services/src/js/components/ConfigurationMapSizeValue.js
plugins/services/src/js/components/ConfigurationMapTable.js
plugins/services/src/js/components/ConfigurationMapValueWithDefault.js
plugins/services/src/js/components/__tests__/ConfigurationMapTable-test.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/service-configuration/PodGeneralConfigSection.js
plugins/services/src/js/service-configuration/ServiceHealthChecksConfigSection.js
plugins/services/src/js/utils/ServiceConfigDisplayUtil.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/js/constants/EmptyStates.js
tests/pages/services/ServiceExternalVolumes-cy.js
tests/pages/services/ServicePodReviewScreen-cy.js
tests/pages/services/ServiceReviewScreen-cy.js

We have changed the design pattern to use unicode 2014 character (&mdash;) to denote the empty state of value in tables. Frameworks already use this pattern because the forms were recently built. This PR changes pods and services to use the same pattern.
**Testing**:
1. Deploy a service. The review screen should should long dash for unconfigured values.
2. Deploy a pod. The review screen should should long dash for unconfigured values.
3. Deploy a framework. The review screen should should long dash for unconfigured values.
4. Look at the configuration tab of service, pod, and framework. They should all have long dash in this view also.
**Before**:
**After**:
**Checklist**
@leemunroe for visibility.

feat(EmptyStates): consolidate config value empty states

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/ServicePodReviewScreen-cy.js
tests/pages/services/ServiceReviewScreen-cy.js

---
ℹ️ Backport: #2762 
---
This ~commit~ PR changes the onChange handler of the ServiceForm so that
it no longer implicitly sets state.editingFieldPath, instead a new
internal function `handleFormFocus` is introduced.
Closes DCOS-21122

DCOS-21122: fix(ServiceForm): fixes focus/change/blur behaviour

---

tests/pages/services/ServicePodReviewScreen-cy.js

looks like two simultaneously merged PRs introduced a regression on master…
FYI: this is just a quick fix for the regression, we should refactor the tests to use the EmptyStates constants file at some point. JIRA: https://jira.mesosphere.com/browse/DCOS-21358

[Regression] fix(integrationTests): fixes empty state of tests

---

plugins/services/src/js/components/modals/CreateServiceModal.js
system-tests/services/test-apps.js
system-tests/services/test-external-volumes.js
system-tests/services/test-pods.js
tests/pages/services/ServiceFormModal-cy.js

This pull-request reintroduces the functionality to disable the `Review & Run` Button if a error is
present.
**Before**
**After**
Closes DCOS-20080

fix(createService): Fix disabled review and run button

---

plugins/services/src/js/components/TaskDirectoryTable.js
plugins/services/src/js/components/forms/ArtifactsSection.js
plugins/services/src/js/components/forms/ContainerServiceFormSection.js
plugins/services/src/js/components/forms/EnvironmentFormSection.js
plugins/services/src/js/components/forms/GeneralServiceFormSection.js
plugins/services/src/js/components/forms/HealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.js
plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/components/forms/PlacementSection.js
plugins/services/src/js/components/forms/VolumesFormSection.js
plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/service-connection/EndpointClipboardTrigger.js
plugins/services/src/js/containers/tasks/TaskTable.js
src/js/components/SchemaField.js
src/js/components/SchemaForm.js
src/js/components/TabForm.js
src/js/utils/ResourceTableUtil.js
src/styles/components/icons/styles.less

With the UI Kit update our icons got very dark which makes the UI more dense. This was not the intent. This PR makes logs icons in tables and help icons with tooltips a lighter shade of grey with hover. 
Note: Associated private plugin PR.
Before
After

DCOS_OSS-2054: Make icons light grey

---

src/js/structs/Node.js
src/js/structs/__tests__/Node-test.js

JIRA - https://jira.mesosphere.com/browse/DCOS-21361
Guards against resources being empty.
CLOSES DCOS-21361
This is tough to reproduce, especially because mesos team tells us it is a state that does not happen, but somehow we get to this problem, and it causes the NodeTable to render infinitely.
I would go by adding the following lines on Nodes.js:42
```
this._itemData["resources"] = null;
this._itemData["used_resources"] = null;
```
No need for integration tests.
**Checklist**

fix(struct/Node): does not throw exception when resources are empty

---

plugins/services/src/js/components/TaskDirectoryTable.js

Expand modified column to accommodate wider content and
not break to the line below
Closes DCOS-21366
**Before:**
**After:**
**Checklist**

fix(TaskDirectoryTable) expand modified column

---

plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/__tests__/ServicesContainer-test.js

This PR adds a `getCleanModalProps` method to the `ServicesContainer`
which cleans and updates the `modalProps` object which is passed down to
the modals.
Before this change it was possible to have an invalid state in `modalProps`
like this: { service: undefined, id: "delete" }. This should be fixed now so
that `service` is always set, if `id` is. If anything is wrong the method
tries to correct the object as good as possible.
--- 
Reproduction of the Issue / Test this PR
Open DevTools & try this on Services "/" and in a Group:
1. create a Service/Pod/Package witl multiple instances (>10)
2. open delete modal for the Service/Pod/Package
3. copy the name (you will need it)
4. quickly delete it again (you have 2s)
=> if the modal says "cant delete" everything is good, if something breaks …

DCOS-21359: fix(ServicesContainer): checks and updates modalProps if needed

---

src/js/components/SchemaField.js

The FrameworkForm fires two change events when something is changed.
This commit ignores the `initial` one.
---
Maybe this can help solving the cypress flakiness issue..
---
This PR is mostly to check if it breaks anything on Jenkins, not sure if we actually need to merge it.
edit: I'm referring to the "elast" issue we had a while back, it was somehow related to a "wrong re-render" of the form which could be initiated by this "double change"

fix(FrameworkForm): dont update state if form field is `initial`

---

plugins/services/src/js/components/modals/ServiceDestroyModal.js
plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js

---
ℹ️ Cherry-picked backport of #2702 - no actual work was done here.
---
When deleting a group inside a group, instead of staying inside that group you're being thrown back to the root of the namespace.
Closes DCOS_OSS-1341
Regarding the Backport: Closes DCOS_OSS-2004

feat(ServiceTree): stay in group view when service deleted

---

npm-shrinkwrap.json
package.json

The new version of VirtualList on 0.20.3 does not cause
react to render infinitely when, while rendering the list
there is an exception.
This fixed behavior helps prevent a few bugs we had in the ui.
**Testing**
The new version of reacts components have changed on the virtual list. You can check some of the lists around the app.
More specifically, you can go on the struct/Node and make it throw an exception by adding an error in any of the methods that are used on the Nodes Table. There you should see there is an error in console, but the list does not render wrong content.
**Checklist**

chore(reactjs-components): update package to 0.20.3

---

CONTRIBUTING.md
npm-shrinkwrap.json
package.json
src/js/core/MesosStream.js
src/js/stores/MesosStateStore.js
src/js/utils/__tests__/rxjsUtils-test.js
src/js/utils/rxjsUtils.js

We have a retry in the https://github.com/dcos-labs/mesos-client but it will catch only the Network errors and in a very stubborn fashion. This PR addresses all the parsing errors that can happen when processing messages and  consuming the stream.
`linearBackoff` ensures that we don't bombard the server with retries.
To enable easier testing I added `rxjs-marbles` library that provides some helpers.
To test this in the browser you could emulate the network split and monitor the Networking tab in the Inspector. You could also add some `throw` and `console.log` if that pleases you.
**Checklist**
Closes DCOS-21337

DCOS-21337: Add linearBackoff retry to the Mesos stream

---

plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/__tests__/ServicesContainer-test.js

---
ℹ️Cherry-picked backport from #2777 - please review the other one 👍
---
This PR adds a `getCleanModalProps` method to the `ServicesContainer`
which cleans and updates the `modalProps` object which is passed down to
the modals.
Before this change it was possible to have an invalid state in `modalProps`
like this: { service: undefined, id: "delete" }. This should be fixed now so
that `service` is always set, if `id` is. If anything is wrong the method
tries to correct the object as good as possible.
Closes DCOS-21359

[Backport 1.11] DCOS-21359: fix(ServicesContainer): checks and updates modalProps if needed

---

plugins/services/src/js/containers/tasks/TasksView.js

Small fix which assures that service is set before accessing its childnodes.
Closes DCOS-21369

DCOS-21369: fix(TasksView): fix undefined service in TasksView

---

scripts/post-checkout
scripts/pre-install

This adds a small notice after you changed the branch, this should come in handy once we introduced the node upgrade but still have to work on older releases 👍 
Example with correct Node version:
And wrong one:

DCOS-21520: check node version on checkout

---

package.json
plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/components/PageHeader.js
tests/pages/services/ServiceFormModal-cy.js

ℹ️ Backport of https://github.com/dcos/dcos-ui/pull/2761
---
This commit changes the onChange handler of the ServiceForm so that
it no longer implicitly sets state.editingFieldPath, instead a new
internal function `handleFormFocus` is introduced.
The old implementation was broken and also was one of the reasons
why our tests were flaky, in fact some tests had to be fixed
after changing the form - they were expecting the broken state.
Also the previous implementation caused the form to lose information
when a radio or checkbox inpout was changed last in some situations.
Firefox for Example doesnt focus a radio input and therefore
never fires a blur event.

[Backport 1.10] DCOS-19865 fix focus/change/blur behaviour

---

scripts/post-checkout

returning `1` breaks rebasing, we dont want this, so it will always return `0` in future

fix(githooks): fix post-checkout-hook

---

plugins/services/src/js/service-configuration/PodStorageConfigSection.js

This commit fixes a variable reference which lead to have multiple lines in the volume mount table
with the same values.
Closes DCOS-19219 DCOS-21412

[Backport] - fix(PodStorageConfigSection): fix variable reference

---

plugins/services/src/js/pages/task-details/TaskDetailsTab.js

This removes the endpoints Row from the Task Detail Table because it was misleading (Discussion over there: https://jira.mesosphere.com/browse/DCOS_OSS-1554 )
To test this create a service or pod, go to Services > <SERVICENAME> > <TASK> and check that Endpoints is not listed anymore.
A follow-up ticket will implement a new "IP Addresses" row which is what this should have been in the first place: https://jira.mesosphere.com/browse/DCOS_OSS-2244

DCOS_OSS-2243: fix(taskdetails): remove misleading endpoints row from config table

---

package.json
src/js/pages/catalog/PackageDetailTab.js
tests/_fixtures/dcos/dcos-version.json
tests/pages/catalog/packages/PackagesTab-cy.js

This disables the install button when the current dcos
version is incompatible
**Checklist**

DCOS-21305: Respect DC/OS min required version when installing a package.

---

package.json
scripts/post-checkout
scripts/validate-engine-versions

the current version of this check complains about node version 9.x being incorrect (it needs 8.9.4). this fixes this issue and also moves the checks into our validate-engines script.
to test this, please checkout this branch with latest node version (should NOT complain), then downgrade node to v4 and try `npm start` (should complain)

refactor(githooks): move and improve post-checkout checks into validate-engines

---

src/js/components/PlacementConstraintsSchemaField.js

An overlooked place of React.PropTypes -> PropTypes react 16 enablement.

chore(prop-types): use "prop-types"

---

plugins/services/src/js/service-configuration/PodStorageConfigSection.js

Three fixes for the volumes pod review screen:
1. Show type as DSS
2. Show a size column
3. Fix the edit button (previously the ID was wrong)
**Before**:
**After**:
Closes DCOS-20258
**Checklist**

fix(PodStorageConfigSection): display DSS type and size

---

src/js/core/MesosStream.js

This PR adds `repeat()` operator that will re-connect to the stream in case Mesos closes the connection.
To test this I wrote a simple mock server and pointed MesosStream.js to the `http://localhost:3000`. Server yields messages with the minimum possible payload that RecordIO is able to parse. Without that fix UI would try connecting once. 
NB! In the Networking tab you will see two calls because one of them is OPTIONS
```js
const http = require('http')
const port = 3000
const requestHandler = (request, response) => {
console.log("Connected")
response.setHeader("Access-Control-Allow-Origin", "*")
response.setHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
response.write("2\n{}")
setTimeout(function() {
response.write("2\n{}")
}, 5000) …
```

feat(mesos-stream): repeat the stream

---

plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
plugins/services/src/js/containers/services/__tests__/__snapshots__/ServicesTable-test.js.snap

This PR removes the service status if the status is N/A.
For testing I would recommend to remove everything from this functions except for the line I highlighted:
- https://github.com/dcos/dcos-ui/blob/danielmschmidt/DCOS-21190-remove-n-a/plugins/services/src/js/structs/Pod.js#L142
- https://github.com/dcos/dcos-ui/blob/danielmschmidt/DCOS-21190-remove-n-a/plugins/services/src/js/structs/Application.js#L158
**Checklist**

DCOS-21190: hide service status if it's N/A

---

plugins/services/src/js/components/HighOrderServiceConfiguration.js
plugins/services/src/js/components/modals/EditServiceModal.js

Edit all services installed with cosmos in the json-schema form. Previouly we only showed `Framework`s. 
We detect if something is installed from cosmos if had has either of two labels `DCOS_PACKAGE_DEFINITION` and `DCOS_PACKAGE_METADATA`. Frameworks are a subset of all services from cosmos and will also have these labels. This also changes the "Configuration" tab to show the `cosmos/service/describe` config for all services installed from cosmos.
Closes DCOS-21614
**Testing**:
1. install package "Registry" from the catalog.
2. click edit on the running framework (it will show in json-schema form, previously showing in marathon form).
3. go to the configuration tab for registry in service detail (it will be cosmos config, previously was the marathon config).
**Checklist**

feat(EditServiceModal): show cosmos services in json-schema form

---

src/js/components/FrameworkConfigurationForm.js
src/styles/components/framework-configuration/styles.less

This is the lowest hanging fruit on improving schema validation errors for Frameworks. This commit merely improves styling, and not the content of the error.
We have talked with cosmos and data services about this general issue, and in the future someone will work on a solution to improve the contents of this error message. Currently this disappointingly obscure message is delivered by the mozilla json-schema library. Data services would like to use these json-schema clauses like oneOf, allOf - but the challenge is mapping this onto a good UX for the UI and CLI. The improved messages in the future might come directly from a "validate" endpoint in cosmos. This would be ideal because then CLI can also get good errors.
Closes DCOS-19740
**It looks like this now**:
**Testing**:
1. Deploy …

fix(FrameworkConfigurationForm): improve schema errors

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortDefinitionsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/PortMappingsReducer.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
plugins/services/src/js/reducers/serviceForm/PortDefinitions.js
plugins/services/src/js/reducers/serviceForm/PortMappings.js
plugins/services/src/js/reducers/serviceForm/__tests__/PortMappings-test.js
plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js

This PR fixes the way the UI supports VIPs. 
UI used to be very opinionated about the way VIPs should be. It would require a VIP to be `VIP_<enpoint_index>` but that's not the way backend expects them. Backend allows anything that starts with `vip|VIP` to be a valid VIP label. Because of that we need to keep vip label that we're getting from JSON.
Please create an app with a few Service Endpoints and override VIP_* to anything valid:
- vipBla
- VIPblop
- VIP_129312
Please check different network modes along with single and multi container.
NB! `Vip` `vIp` etc are invalid.
Closes DCOS-21440
**Checklist**

DCOS-21440: keep VIP label

---

scripts/ci/upload-build

this PR fixes a small issue with our new jenkinsfile by changing our release file names from `tag+name-tag.tar.gz` to `name-tag.tar.gz`. Jenkins passes the tag name as `BRANCH_NAME` to the script which caused theses names 👍

DCOS-21766: fix(ci): fix release file name

---

plugins/services/src/js/components/PodVolumeTable.js
plugins/services/src/js/containers/pod-detail/PodDetail.js
plugins/services/src/js/containers/volume-detail/PodVolumeContainer.js
plugins/services/src/js/containers/volume-detail/PodVolumeDetail.js
plugins/services/src/js/routes/services.js
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/PodSpec.js
plugins/services/src/js/structs/Volume.js
plugins/services/src/js/utils/MarathonUtil.js

This introduces a port of the volumes table from the single container applications to multi container applications.
To test deploy a Pod with a persistent volume (only these will / should show up in the table),
or just take the following JSON:
```JSON
{
"id": "/pod-with-volume",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "nginx"
},
"endpoints": [
{
"name": "http",
"hostPort": 0,
"protocol": [
"tcp"
]
}
],
{
"mountPath": "/etc/log"
}
]
}
],
"volumes": [
{
"size": 10,
}
}
],
"networks": [
{
}
],
"scaling": {
}, …
```

DCOS-19586 - (feat): volume table and volume detail for pods

---

npm-shrinkwrap.json
package.json
src/js/structs/__tests__/JobRunList-test.js
src/js/structs/__tests__/JobTaskList-test.js
src/js/utils/DateUtil.js

Backport of https://github.com/dcos/dcos-ui/pull/2843
The current version has a security vulnerability: CVE-2017-18214
Closes DCOS-21571
**Checklist**

Backport(1.11): update moment

---

src/js/stores/MesosStateStore.js

Use `Promise.resolve().then()` to trigger the stream subscription asynchronously on the same macrotask (by using a microtask). Events emitted by the strean, trigger `onStreamData` which is used to emit an event (using EventEmitter) called `MESOS_STATE_CHANGE`. This change will mitigate issues in which errors in view components lead to stale data because the error propagation broke the stream.
N.B. `EventEmitter` is synchronous meaning that every delay in an event handler effects the `emit` execution time and errors propagate up to the `emit` call which sometimes leads to undesireable behavior.
Closes DCOS-21784
**how to test?**
You want to test this against an enterprise cluster that does not have regions. An example of that cluster is the `nuc` cluster sitting on @fabs desk (sorry SF). …

fix(MesosStateStore): adjust stream data handling

---

npm-shrinkwrap.json
package.json
plugins/catalog/src/js/repositories/__tests__/repositoriesStream-test.js
plugins/catalog/src/js/repositories/repositoriesStream.js
src/js/events/CosmosPackagesActions.js
src/js/events/__tests__/CosmosPackagesActions-test.js

This PR refactors Settings -> Package Repositories page APIs wrapping them with `http-service`. This is a stepping stone in the data-layer effort.
So listing/deleting/adding repository should just work. 
~Beware that verbose error messages will be broken! Therefore `hold merge`
There's an [issue](https://github.com/dcos-labs/http-service/issues/4) for that and a [JIRA](https://jira.mesosphere.com/browse/DCOS-21727)~
Closes DCOS-21640
**Checklist**

DCOS-21640: Wrap cosmos repository API with http-service

---

plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js

Adjust the `ServiceStorageConfigSection.getDefinition` default to align the return a type with the superclass.
Closes DCOS-20949

fix(ServiceStorageConfigSection): adjust getDefinition default

---

plugins/services/src/js/filters/TaskNameTextFilter.js
plugins/services/src/js/filters/__tests__/TaskNameTextFilter-test.js

Include ID search in task text filter.
The neat new search does not work against the id field of the task table.
https://cl.ly/1c0l3H3x3236
**Checklist**

DCOS-20260: Include id search in task text filter

---

plugins/services/src/js/filters/TaskNameTextFilter.js
plugins/services/src/js/filters/__tests__/TaskNameTextFilter-test.js

BACKPORT Include ID search in task text filter.
**Checklist**

[Backport 1.11 ] fix(tasknametextfilter): include id search in task text filter

---

plugins/services/src/js/components/modals/EditServiceModal.js
plugins/services/src/js/components/modals/__tests__/EditServiceModal-test.js

1. Add a new service with this configuration:
```
{
"id": "/do-not-delete-me",
"version": "2018-03-22T11:28:46.456Z",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "nginx"
},
"endpoints": [
{
"name": "http",
"hostPort": 0,
"protocol": [
"tcp"
]
}
],
{
"mountPath": "/etc/log"
}
]
}
],
"volumes": [
{
"size": 10,
}
}
],
"networks": [
{
}
],
"scaling": {
},
"placement": {
}
},
"cpus": 0.1,
"mem": 32,
"disk": 10
},
"fetch": []
}
```
2. Visit the edit page of this service …

DCOS-21798: render empty modal if the service is not loaded

---

jest/setupTestFramework.js
npm-shrinkwrap.json
package.json

I just added enzyme to the 1.11 branch without porting all the tests over (massive merge conflicts there).
You can test it by doing `npm install && npm test`.
I flag it as a blocker as it blocks a blocker, I hope this is OK
**Checklist**

DCOS_OSS-2206: Add enzyme to 1.11

---

.babelrc
jest/preprocessor.js
npm-shrinkwrap.json
package.json
plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Labels.js
webpack/webpack.dev.babel.js
webpack/webpack.test.js

This commit is fixing the labels reducer to support labels with an empty string value.
Closes DCOS-19693

[Backport 1.10] - fix(labelsReducer): fix labels reducer to accept empty strings

---

plugins/services/src/js/components/HighOrderServiceConfiguration.js
plugins/services/src/js/components/modals/EditServiceModal.js
plugins/services/src/js/components/modals/__tests__/EditServiceModal-test.js

[Backport to 1.11 of this PR](https://github.com/dcos/dcos-ui/pull/2871)
1. Add a new service with this configuration:
```
{
"id": "/do-not-delete-me",
"version": "2018-03-22T11:28:46.456Z",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "nginx"
},
"endpoints": [
{
"name": "http",
"hostPort": 0,
"protocol": [
"tcp"
]
}
],
{
"mountPath": "/etc/log"
}
]
}
],
"volumes": [
{
"size": 10,
}
}
],
"networks": [
{
}
],
"scaling": {
},
"placement": {
}
},
"cpus": 0.1,
"mem": …
```

DCOS-21798 & DCOS-21614:  Backport to 1.11 

---

Dockerfile
Jenkinsfile
npm-shrinkwrap.json
package.json
scripts/ci/run-integration-tests
scripts/run-integration-tests

Jenkins complained about `**` after its restart, this fixes the issue by replacing the globbing by `find`
also we moved `junit-merge` from the dockerfile to our package.json because it is part of the project - we want to make the `run-integration-tests` script our entrypoint also for local testing in a follow-up PR 👍 
---
I have decided to put a bit more effort into this to allow us to backport this ASAP to 1.11 👍 After we backported this we should be able to drasticly reduce `run integration tests` calls on 1.11 branch 🎉 
Also we are able to run single tests in an easy way with a command like this `npm run integration-tests -- Sidebar` 🎉

DCOS-21768: Improve Integration Test Script (prepares backport to 1.11)

---

commitlint.config.js

Disable `scope-case` rule to align the configuration with our contributing docs.

fix(commitlint): adjust configuration

---

plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
src/js/components/FrameworkConfigurationReviewScreen.js

The cosmos `config.json` doesn't have the name and version for frameworks.
This change adds the name and version to the top of this page, so users can easily view
this information without clicking the package to edit.
Closes DCOS-19913
**Checklist**

feat(FrameworkConfiguration): show name and version in config tab

---

src/js/stores/MesosStateStore.js

Use `sampleTime` instead of `debounceTime` to reduce the frequency of events. Debounce emits values from the source Observable only after a particular time span has passed *without* another source emission – which in case the source update frequency is higher than the `dueTime` would mean that we don't receive any updates. The `sampleTime` operator emits the last emitted value from the source Observable within time intervals.
Closes DCOS_OSS-2340

fix(MesosStateStore): adjust stream event sampling

---

plugins/services/src/js/utils/MarathonUtil.js

This fixes the parsePod function in the case that a pod with a similar configuration as:
```
{
"id": "/test",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 1000"
}
},
{
"mountPath": "/var/log"
}
]
},
{
"name": "container-2",
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 1500"
}
},
"volumeMounts": []
}
],
"volumes": [
{
"name": "home"
}
],
"networks": [
{
"mode": "host"
}
],
"scaling": {
},
"placement": {
}
},
"cpus": 0.1,
"mem": 32,
"disk": 10 …
```

DCOS-22128 - fix(marathonUtil): fix parsePod function

---

src/js/components/DSLInputField.js

Remove the change event debouncing to resolve issues in which we lost the filter expression data.
The component was designed to be _stateless_ meaning that the hosting component is responsible for updating the `expression` property. Debouncing the event potentially leads to data loss as the hosting component might overwrite the expression before the change event was fired.
Closes DCOS-21928

fix(DSLInputField): adjust change event handling

---

plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/__tests__/TasksContainer-test.js

Not having new zones or regions prevented the state
of the component to be updated causing the default filter
to load with an empty value.
**Checklist**

 DCOS_OSS-2397: shows filter default on task page loading

---

CONTRIBUTING.md
npm-shrinkwrap.json
package.json
src/js/stores/MesosStateStore.js
src/js/utils/__tests__/rxjsUtils-test.js
src/js/utils/rxjsUtils.js

Adjust the `MesosStateStore` to use a linear backoff strategy when re-connecting to Mesos (`retry`), as this otherwise leads to a rather high CPU load and an unresponsive UI due to a rather high number of connection attempts.
Closes DCOS-22301

fix(MesosStateStore): add linearBackoff retry to the stream

---

plugins/services/src/js/containers/tasks/TasksContainer.js
plugins/services/src/js/containers/tasks/__tests__/TasksContainer-test.js

Backport of https://github.com/dcos/dcos-ui/pull/2915
**Checklist**

[Backport 1.11] DCOS_OSS-2398: shows filter default on task page loading

---

npm-shrinkwrap.json
package.json

To get few important updates in. `http-service@0.3.0` would emit error on connection ABORT so that repeat could catch and reconnect to the stream.
Closes DCOS_OSS-2400
**Checklist**

[1.11] chore(*): bump mesos-client and http-service

---

src/js/stores/MesosStateStore.js

---
↩️  _This PR back-ports a fix to release/1.11 introduced with #2890._
---
Use `sampleTime` instead of `debounceTime` to reduce the frequency of events.
Debounce emits values from the source Observable only after a particular time span has passed *without* another source emission – which in case the source update frequency is higher than the `dueTime` would mean that we don't receive any updates. The `sampleTime` operator emits the last emitted value from the source Observable within time intervals.
Closes DCOS_OSS-2386

↩️ fix(MesosStateStore): adjust stream event sampling

---

src/js/stores/MesosStateStore.js

---
↩️  _This PR back-ports a fix to release/1.11 introduced with #2888._
---
Use `Promise.resolve().then()` to schedule a micro tasks and asynchronously  trigger `onStreamData` which is used to emit the `MESOS_STATE_CHANGE`. This change will mitigate issues in which errors in view components lead to stale data as the error propergation broke the stream.
N.B. `EventEmitter` is synchronous meaning that every delay in an event handler effects the `emit` execution time and errors propagate up to the `emit` call which sometimes leads to undesireable behavior.
Closes DCOS-22189

↩️ fix(MesosStateStore): adjust stream data handling

---

package.json

The latest version of compression-webpack-plugin doesn't support webpack 1.x
I have specified the last version that supports webpack 1.x
**Checklist**

fix(package): fix compression version

---

src/js/core/MesosStream.js

Delay reconnection attempts to reduce load on Mesos and improve the UI performance. Without this adjustment, the UI will attempt to re-connect immediately which results in a rather high number of connection attempts which leads to a high CPU load if Mesos is unable to establish the stream (XHR).
Closes DCOS-22303

fix(MesosStream): delay reconnections

---

npm-shrinkwrap.json
plugins/catalog/src/js/repositories/RepositoriesAdd.js
plugins/catalog/src/js/repositories/components/AddRepositoryFormModal.js
plugins/catalog/src/js/repositories/components/RepositoriesTabUI.js

~Depends on #2870, and then we can switch base to `feature/data-layer`. This was a split of that one to make it simpler.~
Moves add repositories away from mixings and flux stores by using the new data-layer patterns (streams and mediators). This is also done in a preparation to use graphql.
TESTING
Just open the Settings > Repositories and try to add, remove and filter packages.
AUTOMATED TESTING
No new tests were added since this is a refactor and rely on the current tests.
**Checklist**

DCOS-22058: change package repositories ADD to the new data-layer patterns

---

npm-shrinkwrap.json
packages/data-service/src/__tests__/graphqlObservable-test.js
packages/data-service/src/graphqlObservable.js
plugins/catalog/src/js/repositories/RepositoriesAdd.js
plugins/catalog/src/js/repositories/components/AddRepositoryFormModal.js
plugins/catalog/src/js/repositories/components/RepositoriesTabUI.js

Our homemade graphql rxjs implementation only supported queries, we have added now also the support for mutations. 
To test it:
> npm test -- --watch graphql query
and then play with the provided test.
NOTES
There is a follow up PR addressing issues regarding graphql spec compliance. That PR will also bring up many tests from the graphql-js lib.
**Checklist**

DCOS-22327 feat: add support to mutations

---

Jenkinsfile
npm-shrinkwrap.json
package.json
scripts/run-integration-tests

this should help us to investigate and identify flaky tests on 1.11 🙇

DCOS-22309: chore(package): backport integration-test script to 1.11

---

Jenkinsfile

waiting for EE Pipeline occupies the executer for quote some time, we dont really need the feedback on OSS Pipeline, so there's no reason to wait…
**Checklist**

DCOS-22414: do not wait for ee pipeline

---

src/js/utils/MesosSummaryUtil.js

This should fix our NodePage flaky test… There was a Stacktrace all the time btw :(
https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/PR-2930/5/tests/

DCOS-22443: guard host.framework_ids before accessing it

---

src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/js/components/HashMapDisplay.js

Problem: Configuration headings for SDK and Marathon apps are inconsistent. 
1. "Services" heading with underline
Marathon
SDK
2. "Configuration" label on review screen 
Marathon
SDK
Solution:
1. Made Services heading the same 
2. Got rid of the Configuration title on SDK confirmation page 
**Checklist**

DCOS_OSS-2059 Update Config Headings

---

src/js/events/MesosStateActions.js

Everything appears to be working except our dashboard looks interesting :)
Connect to a i.e. soak 1.10 and switch network to Slow 3G. Without the fix UI won't be able to ever load state.json
**Checklist**
Closes DCOS-35757

DCOS-35757: remove 2 seconds timeout

---

src/js/stores/ConfigStore.js
src/js/stores/GetSetBaseStore.js

Adjust the `GetSetBaseStore` to not dispatch `APP_STORE_CHANGE` event on every "set" operation.
This greatly reduces the number of events and resolves performance issues with our `AppReducer` by only dispatching events on config change.
Closes DCOS-37421

DCOS-37421: Adjust GetSetBaseStore to stop dispatching events on every change

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js

Introduce a `schedulerTasksMap`  to improve lookups when assigning the scheduler task field. This change drastically improves the performance as `assignSchedulerTaskField`  was using the `some` operator to check whether there is a matching scheduler task resulting in n*m iterations.
Closes DCOS-37436
**Checklist**

DCOS-37436: Adjust mesos state store

---

plugins/services/src/js/containers/services/ServicesTable.js
src/js/components/NestedServiceLinks.js
src/js/components/__tests__/NestedServiceLinks-test.js

Fix group link when searching/filtering by name
on services.
Closes DCOS-28721
**Before**
**After**
**Checklist**

[Backport 1.11] fix(NestedServiceLinks): group link

---

plugins/services/src/js/containers/services/ServicesTable.js
src/js/components/NestedServiceLinks.js
src/js/components/__tests__/NestedServiceLinks-test.js

Fix group link when searching/filtering by name
on services.
Closes DCOS-28721
**Before**
**After**
**Checklist**

fix(NestedServiceLinks): group link

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js

As we don't _need_ to run `assignSchedulerTaskField` over and over again it makes sense to run it once when data changes.
Then we have a chicken and egg problem because `getSchedulerTasksMap` needs `frameworks` and  `assignSchedulerTaskField` needs the map. To resolve this I had to make other functions pure and pass `frameworks` as an argument rather then `getting` it.
**Checklist**
Closes DCOS-37461

DCOS-37461: Run assignSchedulerTaskField once

---

src/js/stores/MesosStateStore.js
src/js/stores/__tests__/MesosStateStore-test.js
src/js/utils/MesosStateUtil.js

Introduce a `schedulerTasksMap`  to improve lookups when assigning the scheduler task field. This change drastically improves the performance as
`assignSchedulerTaskField`  was using the `some` operator to check whether there is a matching scheduler task resulting in n*m iterations.
Closes DCOS-37437
**Checklist**

[master] DCOS-37440: schedulerTasksMap with lookups

---

plugins/services/src/js/components/ServiceBreadcrumbs.js
plugins/services/src/js/components/__tests__/ServiceBreadcrumbs-test.js

<details><summary><strong>fix: prevent service breadcrumb to update without changes</strong></summary><hr/>
This adds a `shouldComponentUpdate` function to the `ServiceBreadcrumb` component. This ensures the
component is only updated if any of the props has changed.
To test you can use the following service config:
```JSON
{
"id": "/volumes",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 1000;"
}
},
{
"mountPath": "/var/home"
},
{
"name": "nothome",
"mountPath": "/var/nothome"
}
]
}
],
"volumes": [
{
"size": 1,
}
},
{
"name": "nothome", …
```

DCOS-37556: prevent unnecessary updates in ServiceBreadcrumb

---

plugins/services/src/js/components/ServiceBreadcrumbs.js

<details><summary><strong>fix: prevent service breadcrumb to update without changes</strong></summary><hr/>
This adds a `shouldComponentUpdate` function to the `ServiceBreadcrumb` component. This ensures the
component is only updated if any of the props has changed.
To test you can use the following service config:
```JSON
{
"id": "/volumes",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 1000;"
}
},
{
"mountPath": "/var/home"
},
{
"name": "nothome",
"mountPath": "/var/nothome"
}
]
}
],
"volumes": [
{
"size": 1,
}
},
{
"name": "nothome", …
```

[1.10] DCOS-37555: prevent unnecessary updates in ServiceBreadcrumb

---

plugins/tracking/hooks.js

**Testing**
**Checklist**
Closes DCOS-37560

DCOS-37560: Remove track.js

---

plugins/tracking/hooks.js

**Testing**
**Checklist**
Closes DCOS-37561

DCOS-37561: remove track.js

---

plugins/tracking/hooks.js

**Testing**
**Checklist**
Closes DCOS-37557

DCOS-37557: Remove track.js

---

plugins/tracking/hooks.js

**Testing**
**Checklist**
Closes DCOS-37558

DCOS-37558: remove track.js

---

plugins/tracking/hooks.js

**Testing**
**Checklist**
Closes DCOS-37559

DCOS-37559: remove track.js

---

plugins/services/src/js/components/ServiceBreadcrumbs.js

<details><summary><strong>fix: prevent service breadcrumb to update without changes</strong></summary><hr/>
This adds a `shouldComponentUpdate` function to the `ServiceBreadcrumb` component. This ensures the
component is only updated if any of the props has changed.
To test you can use the following service config:
```JSON
{
"id": "/volumes",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 1000;"
}
},
{
"mountPath": "/var/home"
},
{
"name": "nothome",
"mountPath": "/var/nothome"
}
]
}
],
"volumes": [
{
"size": 1,
}
},
{
"name": "nothome", …
```

[1.11] DCOS-37554: prevent unnecessary updates in ServiceBreadcrumb

---

src/js/stores/MesosStateStore.js

Copying the task information over creates additional overhead, that is
not needed. We can safely set the flag directly.
Closes DCOS-37516
**Checklist**

[1.10] DCOS-37516: assign field directly to task

---

plugins/services/src/js/pages/task-details/TaskFileViewer.js
plugins/services/src/js/pages/task-details/__tests__/TaskFileViewer-test.js

Backport of https://github.com/dcos/dcos-ui/pull/2790
1. Launch a Service with a Task
2. View a file (e.g. Stdout)
3. Switch to other files, the UI should not break then
**Checklist**

[1.10] DCOS-22145: Backport of "File UI breaks using the switch button"

---

plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/Pod.js

Adjust the service structs to defer the service spec creation to avoid unnecessary instantiations.
Closes DCOS-37480
**Checklist**

[master] DCOS-37480: Defer service spec creation

---

npm-shrinkwrap.json
package.json

As far as I can see we are not using this plugin (anymore?) and it just broke `npm install` on my machine due to python version conflicts… 
Zopfli Readme says you have to call this via `ZopfliPlugin` in you webpack confiug, but we are calling `CompressionPlugin`. not sure why the dependency is still there 🤷‍♂️ 
```
> node-zopfli@2.0.2 install /Users/Julian/Code/dcos-ui/master/dcos-ui/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Python …
```

chore(package): remove zopfli-webpack-plugin

---

src/js/pages/Index.js
tests/smoke-cy.js

On a bigger clusters fetching state can take a while. With this fix we connect to the stream as soon as we can so that when a user opens a page that requires the data it's already there (or half way there at least)
Remember that the UI doesn't connect to the stream on the Dashboard - now it will. Please keep in mind that even in the current version once we connect to the stream we never unsubscribe.
Closes DCOS-37791

DCOS-37791: Connect to MesosStream on all pages

---

Jenkinsfile
scripts/ci/release-latest
scripts/ci/utils/update-dcos-repo
scripts/ci/utils/upload-build

This backports our latest pr fixes to 1.11.
**How to review:**
I had to remove this branch from the Jenkinsfile before we actually can merge this, so to review this, can to look into this Jenkins run: https://jenkins.mesosphere.com/service/jenkins/job/Frontend/job/dcos-ui-oss-pipeline/job/jg%252FDCOS-37722-fix-latest-pr/2/
You also can create a cluster from `testing/pull/2919` which is the corresponding update from the Run above in our Latest DC/OS OSS PR: https://github.com/dcos/dcos/pull/2919

[1.11] DCOS-37722: Fix latest pr

---

npm-shrinkwrap.json
package.json
packages/data-service/package.json
packages/data-service/src/data-service.d.ts

This PR adds type annotations for `data-service` so that we could use it in typescript.
Small extraction from a rather big issue.
Closes DCOS-38361
**Checklist**

DCOS-38361: Add type annotations for data-service

---

src/js/stores/MesosStateStore.js
src/js/utils/__tests__/rxjsUtils-test.js
src/js/utils/rxjsUtils.js

Adjust the backoff strategy to allow _unlimitted_ retries, reduce the start delay and limit the delay to 5 seconds.
The adjusted strategy should make the Mesos data stream more resilient to connection issues and basically falls back to polling for changes in cases where chunked streaming doesn't work.
This change also improves the perceived performance as delaying the first retry longer than 500ms results in users thinking that nothing is happening at all.
Closes DCOS-38399

DCOS-38399: Improve mesos backoff strategy

---

plugins/jobs/src/js/JobsOverview.tsx
src/js/events/MetronomeClient.ts

This is part 2 of the new overview page, to play around with this, you can navigate to http://localhost:4200/#/jobs/overview2
in order to test this, apply this patch to `jobs.js`:
```diff
@@ -3,7 +3,7 @@ import React from "react";
/* eslint-enable no-unused-vars */
import { IndexRoute, Redirect, Route } from "react-router";
-import JobsTabContainer from "#PLUGINS/jobs/src/js/JobsTabContainer";
+import JobsOverview from "#PLUGINS/jobs/src/js/JobsOverview";
import TaskDetailsTab from "#PLUGINS/services/src/js/pages/task-details/TaskDetailsTab";
import TaskFileBrowser from "#PLUGINS/services/src/js/pages/task-details/TaskFileBrowser";
import TaskFileViewer from "#PLUGINS/services/src/js/pages/task-details/TaskFileViewer";
@@ -28,12 +28,12 @@ const jobsRoutes = [
children: [
{
type: Route,
- …
```

DCOS-37751: Add new JobOverview meditator which uses data layer

---

plugins/jobs/src/js/JobStopRun.js
plugins/jobs/src/js/__tests__/JobStopRun-test.js
plugins/jobs/src/js/components/JobStopRunModal.js
src/js/pages/jobs/JobRunHistoryTable.js

**SCOPE**
- Extract the JobStopAction into the mediator pattern
- Minor changes to existing JobStopModal component
**HOW TO TEST**
Scenario 1: A job
Go to the Job History page, run a job, and then selected it on the list (via the checkbox), a Stop button appears, you can stop the job there.
**WHAT WAS TAKEN OUT OF SCOPE**
- Not using graphql yet.

DCOS-38641 stop action

---

plugins/jobs/src/js/JobsOverview.tsx

Check out and build. If it builds without:
```
ERROR in /Users/ahoy/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx
[tsl] ERROR in /Users/fabs/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx(158,18)
TS2352: Type 'Observable<any>' cannot be converted to type 'Observable<{ data: { jobs: JobConnection; }; }>'.
ERROR in /Users/ahoy/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx
[tsl] ERROR in /Users/fabs/ship/dcos-ui/plugins/jobs/src/js/JobsOverview.tsx(158,18)
TS2352: Type 'Observable<any>' cannot be converted to type 'Observable<{ data: { jobs: JobConnection; }; }>'.
Property 'buffer' is missing in type 'Observable<any>'.
```
Yay!

DCOS-38900 - Fix build by removing type declaration.

---

plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js
src/js/stores/DCOSStore.js
src/js/stores/__tests__/DCOSStore-test.js

**TL;DR** This PR removes all the resources aggregation logic and replaces it with the `used_resources` for Frameworks.
**Tell me more**
Looks like we've mistakenly assumed that allocated resources for Frameworks should be aggregated from their tasks as with Marathon Services. Turned out that there's a special metadata on the Framework protobuf that has `used_resources` information.
**Checklist**
Closes DCOS-21723

DCOS-21723: use metadata instead of calculation

---

npm-shrinkwrap.json
package.json
src/js/core/MesosStream.js
tests/_fixtures/1-service-with-executor-task/summary.json

💁‍♂️ Forward port of #3048
> Update the mesos-client to 0.2.3 as this version great reduces the memory footprint and adjust `MesosStream` to stop multicasting the stream using the replay subject. This change allows the browser to garbage collect dependent/sliced strings created while processing the Mesos response.
> 
> _Please note that this is a temporary adjustment as it would result in multiple open connections if consumed by more than one component. We're going to revert this change once the `http-service`  to emit event objects instead of the response as well as changed the `mesos-client` to output parsed JSON._
> 
> **Testing**
> 
> * Checkout the code and verify that the number of open mesos subscribe connections is correct and the updates are flowing through. 
> * Make memory …

DCOS-38340: Address unbound memory use in Mesos Stream

---

plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/__tests__/Framework-test.js

After lengthy discussions with many parties we've decided to include scheduler resources into report. To make data more sensible from the stand point of *DCOS*. 
So now on the Services view for frameworks we show allocated resources + scheduler resources:
Which is now aligned with the way we display Framework Tasks:
💁‍♂️  DCOS is not Mesos. (Duh..)
In DCOS we have a concept of root Marathon that we don't really reflect on the DCOS UI.
This root Marathon runs all the pods, services as well as scheduler tasks for frameworks.
We display Pods and Services on the Services view on the top level, like the `blip` task on the screenshot, wheres in Mesos they go under the root Marathon.
We display frameworks on the top level as well as they would go under Marathon, `cassandra` and `hello-world`, …

DCOS-21723: Include scheduler resources 

---

plugins/nodes/src/js/columns/NodesTableCPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
src/js/components/ProgressBar.d.ts

Change this line in `NodesTableContainer.js`
```diff
```
After that please take a look at the nodes table and see if the health column looks right and sorts correctly
- CPU percentage and resource bar are two different columns, once we have finished DCOS-39147, we can merge them and hide the bar on smaller screens
None

DCOS-38822: NodesTable / CPU Columns

---

plugins/nodes/src/js/columns/NodesTableHealthColumn.tsx
plugins/nodes/src/js/columns/__tests__/NodesTableHealthColumn-test.js
plugins/nodes/src/js/columns/__tests__/__snapshots__/NodesTableHealthColumn-test.js.snap
plugins/nodes/src/js/columns/__tests__/fixtures/node-healthy.json
plugins/nodes/src/js/columns/__tests__/fixtures/node-unhealthy.json
plugins/nodes/src/js/columns/__tests__/fixtures/node-warn.json
plugins/nodes/src/js/columns/__tests__/fixtures/node-without-health.json
src/js/utils/UnitHealthUtil.d.ts

Change this line in `NodesTableContainer.js`
```diff
```
After that please take a look at the nodes table and see if the health column looks right and sorts correctly
- I decided not to move the sorting utils to typescript, because for me this would be out of scope
- I choose to use table driven tests because the test cases looked very similar to me
None

DCOS-38827: add health column

---

plugins/nodes/src/js/columns/NodesTableGPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx

Progress bar for GPU column + minor tweaks to align with CPU cols.
Closes DCOS-38825
`nodes/nodes-table/NodesTableContainer.js`
```diff
```

DCOS-38825: GPU columns

---

packages/ui-kit-stage/SortableColumnHeaderCellIcon.tsx

💁‍♂️ JIRA Link: https://jira.mesosphere.com/browse/DCOS-39067
In `NodesTableContainer.js`: 
```diff
```
Not directly related to this PR, but I noticed that there was a right-aligned icon in the old table. Did we drop this with the new table component? 🤔  /cc @weblancaster @leemunroe @lilysamimi 
There is a Bug with the Table, after you clicked on a header to change sorting, you need to resize your Browserwindow 😅 Bug is already fixed in UI Kit but we still need to fix another issue to create a new UI Kit Release
None

DCOS-39067: add correct sort icon to table header icon component

---

plugins/jobs/src/js/data/JobModel.ts
plugins/jobs/src/js/data/__tests__/JobModel-test.js

Please visit the Jobs Overview page and try to use a lot of filters and sorting. You should see a nearly instantly UI.
- There might be situations where we cancel network requests becasue of bad timing. To solve this we would need to have a `refCountWithDelay` function build in. This should be part of DCOS-38161.
None 🎉

DCOS-38850: use existing data to update the jobs overview UI instantly

---

plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
plugins/nodes/src/js/components/NodesTable-new.tsx

Change this line in the `NodesTableContainer.js`:
```diff
```
Please take a look at the nodes table and see if the regions column behaves the same as before (except for the sort direction, which got fixed)
- We need to use a different version of the renderer because we need to
pass in an extra parameter coming from the props. I decided to bind a partial application to the scope of the nodes table instead of loosening up the entire API, I am open to change here if you think there is a nicer solution or if there are more examples of props being needed there.
All is ready 👍

DCOS-38826: add region column

---

packages/ui-kit-stage/HeaderBar.tsx
src/js/components/AccountDropdown.d.ts
src/js/components/AccountDropdown.js
src/js/components/AccountDropdownTrigger.js
src/js/components/HeaderBar.tsx
src/js/stores/AuthStore.d.ts
src/js/stores/AuthStore.js
src/js/stores/BaseStore.d.ts
src/js/stores/GetSetBaseStore.d.ts
src/styles/components/header-bar/styles.less
src/styles/components/header-bar/variables.less

Creates AccountDropdown as the menu list and AccountDropdownTrigger as the
dropdown display. Adds accompanying typescript files. Adds truncation and
responsive sizing.
Closes DCOS-38940
* Checkout `origin/tommy/feature/DCOS-38940-user-dropdown-header-bar`
* Enable the header bar by commenting out the following lines in `HeaderBar.tsx`
```
// remove this to activate component
if (arguments) {
return null;
}
```
* Comment out `<span>toggle component here</span>` in `HeaderBar.tsx`
@DanielMSchmidt I added a placeholder for the cluster dropdown, you should be able to drop what you do in there.

DCOS-38940: Add User Account Dropdown on Header Bar

---

npm-shrinkwrap.json
package.json
packages/ui-kit-stage/SortableColumnHeader.tsx

Change this line in `NodesTableContainer.js`
```diff
```
After that please take a look at the nodes table and see if the headlines of the table look correctly
- The content spacing is a separate issue (DCOS-39265), therefore it looks a bit off
None

DCOS-39069: use headercell from ui-kit

---

src/js/schemas/JobSchema.js
src/js/schemas/job-schema/Docker.js
src/js/schemas/job-schema/Parameters.js
src/js/structs/Job.js
src/js/utils/JobUtil.js
tests/pages/jobs/JobJSONEditor-cy.js

Support docker parameters in Metronome jobs.
This is based on @kensipe PR https://github.com/dcos/dcos-ui/pull/3037
Closes DCOS_OSS-3801
Test job JSON that UI shouldn't change when you switch back and forward between JSON view and Form view.
```js
{
"description": "Example Application",
"id": "docker-param",
"run": {
"cmd": "sleep inf",
"cpus": 0.2,
"mem": 32,
"docker": {
"image": "ubuntu",
"parameters": [
{
"key": "cap-drop",
"value": "ALL"
},
{
"key": "cap-add",
"value": "SYSLOG"
}
]
}
}
}
```

DCOS_OSS-3801: 1.11 / Support Docker Parameters in Jobs

---

src/js/structs/Node.d.ts
src/js/structs/Node.js
src/js/structs/__tests__/Node-test.js

- See the tests that we wrote and verify that they handle each edge case
- Read through [the docs](https://docs.mesosphere.com/1.11/overview/architecture/node-types/#public-agent-nodes) and see if we are misusing the API
- We chose to not use the "public_agent" role, because of what we found [here](https://docs.mesosphere.com/1.11/overview/architecture/node-types/#public-agent-nodes)
> The Mesos agents on public agent nodes also have the public_ip:true agent attribute to assist in their discovery.
It seemed to us like this is more precise
None

DCOS-39331: Add isPublic to node api

---

plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js

`DCOS_PACKAGE_IS_FRAMEWORK` has been [deprecated](https://jira.mesosphere.com/browse/DCOS-15283) and we haven't backported. Checking it causes false positives, i.e. detecting `marathon-lb` as it would be a framework. Switching to `service instanceof Framework` check fixes the issue.
Closes DCOS-22291
Co-authored-by: Orlando Hohmeier <orlando@mesosphere.com>
Look into soak19 with `release/1.9` UI verify that `marathon-lb` doesn't show anything under `Recent Resource Offers` section on the Debug tab.
Verify that with the fix you see the offers and rejections.

fix(ServiceDebugContainer): stop using deprecated label

---

package.json
plugins/nodes/src/js/columns/NodesTableCPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableHealthColumn.tsx
plugins/nodes/src/js/columns/NodesTableHostnameColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemColumn.tsx
plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx
plugins/nodes/src/js/columns/__tests__/__snapshots__/NodesTableHealthColumn-test.js.snap

The Cell Component from @dcos/ui-kit was added to all columns in the new (refactored) table.
Closes DCOS-39265
run npm install
In `NodesTableContainer.js`:
```diff
```
I have decided to add a `<span>` element inside the Cell for some files that didn't have it (for example NodesTableGPUColumn.tsx). Some other files already had such a `<span>` and I wanted to be consistent.
None

DCOS-39265: Use Cell from UI Kit for the content of the tables

---

src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationForm.js
src/js/components/__tests__/FrameworkConfigurationForm-test.js

This fixes FrameworkConfigurationForm to gracefully handle an invalid
`formData` and provide an error message.
Close DCOS-38595
Please have a look at the issue it has all the information to set up the cluster with the breaking state.
The trade-off is that currently in case of an invalid solution you can't disable the json-editor in the edit form.
This change has no dependencies.

Close DCOS-38595: fix framework configuration form

---

plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js

After fixing #3092 @orlandohohmeier and I decided to propagate the check forward so that we don't regress in the code base in the way we're checking if a service is a Framework or not.
---
Service has already been wrapped into a Framework struct at this point. No need in re-checking its type via labels.
Closes DCOS-39661
Deploy a Framework from the Catalog, check to see if Debug tab still works.

1.10 DCOS-39661: Check instance type instead of labels

---

plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js

After fixing #3092 @orlandohohmeier and I decided to propagate the check forward so that we don't regress in the code base in the way we're checking if a service is a Framework or not.
---
Service has already been wrapped into a Framework struct at this point. No need in re-checking its type via labels.
Closes DCOS-39662
Deploy a Framework from the Catalog or go to soak there are plenty of Frameworks running and failing, check to see if Debug tab still works.

refactor(ServiceDebugContainer): check instance type

---

plugins/nodes/src/js/components/NodesGridDials.js
plugins/nodes/src/js/components/NodesGridView.js
plugins/nodes/src/js/components/__tests__/NodesGridDials-test.js
plugins/nodes/src/js/pages/nodes/nodes-grid/NodesGridContainer.js

In "Grid" view of the table removed the "Show services by share checkbox" and enabled automatic display by share
Closes DCOS-23826
In the `Nodes` tab, click on `Grid` view.
The tests were initially failing because of the changed flow. I decided to remove the tests that were no longer relevant.
None.

DCOS-23826: Always display services by share

---

npm-shrinkwrap.json
package.json
plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableHostnameColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemColumn.tsx
plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx
src/typings/array-sort.d.ts

Change this line in the `NodesTableContainer.js`:
```diff
```
Please take a look at the nodes table and see if all the sortings look correct (especially the ones with numbers, like mem, cpu, and disk. I also fixed that the carret should now be shown while sorting every column (except for the bars which are not sortable
- I decided to use an external library which provided the tiebreaker feature we want instead of writing something my own, because the contract it provided looked clear and it seems to solve the problem. Given the experience with my last try on designing an API for this problem I also wanted to cut discussions about the API and expected or unexpected …

DCOS-39112: Fix comparison of numeric values in Nodes Table

---

src/js/schemas/JobSchema.js
src/js/schemas/job-schema/Docker.js
src/js/schemas/job-schema/Parameters.js
src/js/structs/Job.js
src/js/utils/JobUtil.js

Support docker parameters in Metronome jobs.
This is based on @kensipe PR https://github.com/dcos/dcos-ui/pull/3037
Closes DCOS_OSS-3800
Test job JSON that UI shouldn't change when you switch back and forward between JSON view and Form view.
```js
{
"description": "Example Application",
"id": "docker-param",
"run": {
"cmd": "sleep inf",
"cpus": 0.2,
"mem": 32,
"docker": {
"image": "ubuntu",
"parameters": [
{
"key": "cap-drop",
"value": "ALL"
},
{
"key": "cap-add",
"value": "SYSLOG"
}
]
}
}
}
```

DCOS_OSS-3800: 1.10 / Support Docker Parameters in Jobs

---

.releaserc
Jenkinsfile
npm-shrinkwrap.json
package.json
scripts/ci/upload-release

No chance to test from this PR… but semantic release worked locally on my machine (https://github.com/dcos/dcos-ui/releases/tag/master%2Bv2.0.1) and I tested some dry runs on CI (https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/jg%2FDCOS-22340-semantic-release/3/pipeline/48).
- I decided to add a `retry(3)` to the system-tests to make our pipeline a bit more robust… 🤷‍♂️ 
- also, because CI is the whole idea of semantic release, I decided to do a quick update to the way we upload binaries for dcos - we already made the filename unique before, but we've overriden the version number…
=> from now on, we can use them for our releases 💃 (I'll update our wiki once this is stable)
EE part should be merged (almost) at the same time.

DCOS-22340: semantic release

---

plugins/nodes/src/js/columns/NodesTableCPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableHealthColumn.tsx
plugins/nodes/src/js/columns/NodesTableHostnameColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
plugins/nodes/src/js/columns/NodesTableTypeColumn.tsx
plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx
plugins/nodes/src/js/components/NodesTable.tsx

A new `Type` Column was added to the table. It shows correct information (i.e. Public/Private).
Closes DCOS-39265
I decided to use compareValues for the sorting, there might be a better option.
~~https://github.com/dcos/dcos-ui/pull/3094~~

DCOS-39158: Add Type Column

---

plugins/nodes/src/js/pages/NodesAgents.js
plugins/nodes/src/js/pages/NodesMasters.js
plugins/nodes/src/js/routes/nodes.js

Closes DCOS-39153
navigate to http://localhost:4200/#/nodes/agents to see tabs. Agents page should work as before. masters tab is filled by #3117

DCOS-39153: add tabs to NodesPage

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/EnvironmentVariables-test.js

This fixes the environment variables reducer to support empty values.
Close DCOS-38433
Try to create a service with the following config:
```JSON
{
"env": {
"key": ""
}
}
```
I worked together with @tnguyen0 on this issue.

fix(serviceForm): fix environment variable reducer

---

system-tests/_scripts/launch-cluster.sh

system tests are not cleaning up properly, so if they fail once, all following runs will fail because cluster-info.json still exists…
we need a CI run where system test fail and then succeed…

ci(system-tests): remove stale cluster info if it exists

---

Jenkinsfile

Cypress kept dying and with retry mechanisms in place there is no need anymore for running tests in parallel.
verify that jenkins isnt running stages in parallel anymore 😢
Ci will take longer now… but IMHO thats better than having killed runs 🤷‍♂️

refactor(ci): change timeout behaviour

---

packages/ui-kit-stage/SortableColumnHeader.tsx

Checkout the nodes page and take a look if the column header behaves the same as before (having the carret being displayed when hovering and the mouse being a pointer.
- Decided to add state because it is just little, contained and the easiest solution.
None

DCOS-39862: Add hover state and cursor styles to column header

---

src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationForm.js
src/js/components/__tests__/FrameworkConfigurationForm-test.js

This fixes FrameworkConfigurationForm to gracefully handle a invalid
formdata and provide an Error message.
Close DCOS-38595
Backport form #3101

[1.11] Backport framework form fix.

---

plugins/nodes/src/js/components/NodesTable.tsx
plugins/nodes/src/js/pages/NodesOverview.js
plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js

The NodesTable only showed two rows as this container was too small
Closes DCOS-39901
Run this branch against soak and see if the nodes table has the entire height of the leftover space of the screen and also if there are not two scroll bars
- We had to add a display: flex to one of the main gemini scrollbar components. If there is a different solution I am not aware of, please tell.
None

DCOS-39901: NodesTable height of container should fill remaining space

---

plugins/nodes/src/js/columns/NodesTableCPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableHealthColumn.tsx
plugins/nodes/src/js/columns/NodesTableHostnameColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemBarColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemColumn.tsx
plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
plugins/nodes/src/js/columns/NodesTableSpacingColumn.tsx
plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx
plugins/nodes/src/js/components/NodesTable.tsx

This adds a new spacing column to strech the whole table to 100% width.
Adding a new column instead of just using the last one helps preventing sizing issues
when that last column hast left and right aligned content.
Closes https://jira.mesosphere.com/browse/DCOS-39797
Resize window and verify that table always has 100% and content stays left.
None
None

DCOS-39797: refactor(nodes): make table always 100% wide

---

src/styles/components/user-account-dropdown/styles.less

Remove extra margin on cluster dropdown
Closes DCOS-39963
1. `npm start`
2. Create a non-admin user (instruction below)
**How to create a user without metadata access**
**Before:**
**After**

fix: cluster dropdown extra margin

---

plugins/nodes/src/js/components/NodesGridView.js
src/styles/components/filter-bar/styles.less
src/styles/components/header-bar/styles.less
src/styles/components/nodes-grid-view/styles.less

* Fixes the spacing between node dials and filter row when the size of the screen is changed
* Fixes the header bar shrinking issue
* Adds a dot for "Other" in the side list
* Adds scrolling for the nodes grid view
Closes DCOS-39972
* To see a large number of nodes, set the cluster to a soak cluster
* Verify that the aforementioned points are fixed/added

DCOS-39972: fix spacing between node dials and filter

---

plugins/nodes/src/js/components/NodesTable.tsx
src/styles/content/tables/styles.less

> I started to build a new component in the UI Kit called `Link` to wrap the `Link` component from React Router but because it's out of scope I returned to the original fix.
Fix link in NodesTable to add consistency
across tables.
Closes DCOS-39959
1. `npm start`
2. Go to Nodes page and note the fix in the column name
**Before**
**After**

fix(NodesTable): add consistency to link

---

plugins/nodes/src/js/components/NodesTable.tsx
plugins/nodes/src/js/components/__tests__/NodesTable-test.js

When changing the sorted column, it always sorts by descending order.
related jira: https://jira.mesosphere.com/browse/DCOS-39889
In `Nodes` tab, sort some column by descending order (the caret pointing down) 
and then click another column to sort it - the second column should also be sorted by descending order.
Decided for a concise check.
None.

DCOS-39889: SortDirection isnt resetted when changing sortColumn

---

plugins/services/src/js/components/dsl/FuzzyTextDSLSection.js
tests/pages/services/ServiceDetail-cy.js

- Check the tasks page for a service and verify that the fuzzy search loses it's content if "apply" is not pressed directly
- Check this branch out and verify that the content of the fuzzy search is directly applied
- There might have been a way to fix the bug without applying the fuzzy search directly to the search, but this was inconsistent with the buttons already (they apply directly) I decided to fix forward here and change the behavior (from my point of view) to the benefit of the customer.
- Decided for integration tests as there were no tests at all for this area. I thought system tests might not be necessary as it's more of a UI-only problem.

DCOS-39877: apply changes in fuzzy search directly

---

.gitignore
plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/components/__tests__/LeaderGrid-test.js
plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
plugins/nodes/src/js/data/MesosMasters.js
plugins/nodes/src/js/data/__tests__/MesosMasters-test.js
plugins/nodes/src/js/pages/NodesMasters.js
src/js/stores/MesosStateStore.js
src/js/stores/MesosStream/parsers/__tests__/master-test.js
src/js/stores/MesosStream/parsers/master.js

This is a replacement of #3117, due to CI issues.
Launch a multi-master cluster. Look at the data it shows, go on the control panel for your cluster (AWS) and kill the machine that is, running.
Go to: http://localhost:4200/#/nodes/masters
**GET_MASTER quickfix** 
The state store only updates the MesosState once it
parsed the entire state, which means that we wait seconds
on a large cluster, before we are able to show a piece
of information, we get almost instantly (GET_MASTER).
**GET_MASTER parser elected and started**
I added code to the parser to add elected and started time to the master_info object. Not quite sure I like adding those there but do not have any better idea. I considered another structure like master_events with both. I also do not like to add them flatten to the mesos …

DCOS-39832 elected leader tab

---

plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/__tests__/Service-test.js

This PR only adds the getter to our struct - `npm test`
I decided to sort the regions by taskcount and generate & store the array on first read

DCOS-39896: add region information getter to struct

---

package.json

We discovered that it was possible to commit code with linting errors. I figured that `--fix` would try fixing everything instead of raising errors.

chore(eslint): raise all warnings instead of fixing them

---

plugins/nodes/src/js/pages/NodesOverview.js
src/js/components/Page.js

This fixes an issue that on a no scroll page the content is not able to span to the bottom of the
page.
Go to the nodes table on cluster with a lot of nodes. Check if the table reaches the end of the page.
All pages with dontScroll attributes do not have a padding anymore
This is part of DCOS-39956

DCOS-39956: fix(page): flush bottom on no scroll pages 

---

src/styles/components/resource-switch-dropdown/styles.less

* Remove the hacky method of centering for something proper :)
* Check resource switch dropdown items are centered

refactor(styles.less): center resource switch dropdown items properly

---

plugins/services/src/js/components/dsl/FuzzyTextDSLSection.js
src/js/components/DSLFormDropdownPanel.js
tests/pages/services/ServiceDetail-cy.js

- Check the tasks page for a service and verify that the fuzzy search loses it's content if "apply" is not pressed directly
- Check this branch out and verify that the content of the fuzzy search is directly applied
- There might have been a way to fix the bug without applying the fuzzy search directly to the search, but this was inconsistent with the buttons already (they apply directly) I decided to fix forward here and change the behavior (from my point of view) to the benefit of the customer.
- Decided for integration tests as there were no tests at all for this area. I thought system tests might not be necessary as it's more of a UI-only problem.

[1.11] DCOS-39877: remove flickering filter bug

---

plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx

Right-align the tasks column using the new NumberCell from the ui kit.
Closes DCOS-39960
Go to `Nodes` tab. In `List` view see if the `Tasks` column is right-aligned.
I think it looks good, but we can also consider adding a 10-20% margin (see screenshots), what does everyone else think?
None.

DCOS-39960: Tasks column in the nodes table should be right aligned

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/EnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/MultiContainerEnvironmentVariables.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/EnvironmentVariables-test.js

---
↩️  _This PR back-ports a fix to release/1.0 introduced with https://github.com/dcos/dcos-ui/pull/3106._
---
This fixes the environment variables reducer to support empty values.
Try to create a service with the following config:
```json
{
"env": {
"key": ""
}
}
```

DCOS-40523: Enable empty env vars

---

plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/PodInstance.js
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/__tests__/Pod-test.js
plugins/services/src/js/structs/__tests__/PodInstance-test.js

Closes DCOS-40526
ui isnt implemented yet - `npm run test` it is.
I decided to just duplicate the code instead of extracting something into a util. I dont think that extracting it would add much value.
Also, this is a fixup commit for the last one, we're on a feature branch here which I'll have to rebase anyway - it _should_ work. I'm aware that this messes up our JIRAs a bit because there is no commit closing DCOS-40526 - lets see 🤷‍♂️

DCOS-40526: add region information getter to pod struct

---

plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemColumn.tsx
src/js/utils/ResourcesUtil.d.ts
src/styles/components/status-bar/styles.less

- Go to the Nodes page
- See the new colors in the progress bars
If any bars are at 0%, manually add the bar markup:
```
<span class="bar color-{color id}" style="width: 25%;"></span>
```
I checked for other uses of `ProgressBar`, and they will not be affected by the style changes in `src/styles/components/status-bar/styles.less`
None that I can think of
Nothing because the ticket for DCOS-39944 has already merged

DCOS-39945: Re-add colors to NodesTable progress bars

---

plugins/services/src/js/reducers/serviceForm/FormReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
src/js/utils/ContainerUtil.js
src/js/utils/__tests__/ContainerUtil-test.js

After navigating to the Services tab:
1. Tap the "plus" in the upper-right corner to add a new service
2. Select "Multi-container (Pod)"
3. Add two new containers, so you have "container-1", "container-2", and "container-3"
4. Delete "container-2"
5. Add another new container; it should be named "container-4". Before these changes, it would have a duplicate name, "container-3"
No
Nothing
**Before**
**After**

DCOS-21183: no duplicate names when adding containers to service

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Enables Service endpoints on UCS for overlay networks: `dcos` and `dcos6`
Backport of #2800 
Closes DCOS-39720
Try creating an app running UCR with `dcos` network and a service endpoint.

DCOS-39720: enable service endpoints on ucr

---

src/js/components/ImageViewer.js

On a package catalog page:
* Enlarges the "Media" heading
* Wrapping for catalog screenshots
Closes DCOS-20340
* Can't load images on local, so go to `PackageDetailTab.js` and replace:
```
<ImageViewer images={cosmosPackage.getScreenshots()} />
```
with (and add the Cluster URL below):
```
<ImageViewer
images={cosmosPackage
.getScreenshots()
.map(image =>
image.replace(
"https://localhost:4200",
"<Cluster URL goes here>"
)
)}
/>
```
* Go to **weavescope** catalog page

DCOS-20340: enlarge heading and wrap catalog screenshots

---

Jenkinsfile

Problem: I can'e operate PR numbers, though our branch names are rather informative. This PR is an attempt to make `#frontend-ci-status` more helpful for me and maybe for everyone else.
I'll re-run the PR couple of times to kick in flaky tests and see if slack message improves.
I decided not investing any time in a research whether we have PR title as an env var. I believe we should though. So I wen with a branch name for starters.

Add branch name to the slack message

---

plugins/services/src/js/constants/ServiceTableHeaderLabels.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/__tests__/Framework-test.js
plugins/services/src/js/structs/__tests__/Pod-test.js
src/styles/components/service-table/styles.less

ℹ️ This is a Feature Branch, all code already go reviewed on its own, but please make sure that this branch also works as expected 👍 
--- 
When this is done there are Package Version Information on Services Table, like this:
We decided to just plain display the full given version string, there is a feature request against packaging to add the base tech as dedicated field to the API - currently we do not have a reliable data source to take the information from :(

DCOS-39900: Service Version on Services Table

---

tests/pages/services/ServiceFormModal-cy.js

Fix integration test for service form modal > create layout > placement > add placement to detect that field value is disabled when unique selected.
Run integration test for ServiceFormModal-cy.js and ensure that  **Service: Placement > Add Placement Constraint > Should disable the field "Value" when Unique is selected in operator dropdown** test passes
Not sure if prettier/linting rules have changed since this file was last worked on, but the pre-commit linting checks were failing which is why the diff shows a huge number of lines changed. If there's another way to get around this please let me know. The only non-formatting changes here are lines 821-832. https://github.com/dcos/dcos-ui/pull/3190/files#diff-0796ef68862d3b5d45e239ff56ee5be7R821

DCOS-20273: Detect that field value is disabled when unique selected

---

src/styles/components/dropdown-menus/styles.less
src/styles/components/header-bar/styles.less
src/styles/layout/sidebar/styles.less

Chrome on macOS has had issues with macOS' native subpixel antialising for a long time, and it's especially problematic for light text on a dark background
1. In the header bar, click either of the dropdowns in the top-right corner - the dropdown trigger text should no longer flicker.
2. Go to any view with a dropdown in the main content area - for example, Services has a filter dropdown in it's search input, and Nodes has a dropdown labeled "Filter by Service". The text in the sidebar should no longer flicker.
Try these on your laptop monitor as well as an external monitor if you have one.
`text-rendering: optimizeLegibility`
- 👍 will prevent text quirks without affecting the perceived thickness of the type
- ❓ will change the text rendering however each browser handles it
- 👎 has …

DCOS-40019: fix UI text flicker

---

.gitignore
plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/components/NonLeadersGrid.js
plugins/nodes/src/js/components/__tests__/LeaderGrid-test.js
plugins/nodes/src/js/components/__tests__/NonLeaderGrid-test.js
plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
plugins/nodes/src/js/components/__tests__/__snapshots__/NonLeaderGrid-test.js.snap
plugins/nodes/src/js/data/MesosMasters.js
plugins/nodes/src/js/data/MesosMastersHealth.js
plugins/nodes/src/js/data/MesosMastersLeader.js
plugins/nodes/src/js/data/__tests__/MesosMasters-test.js
plugins/nodes/src/js/data/__tests__/MesosMastersHealth-test.js
plugins/nodes/src/js/data/__tests__/MesosMastersLeader-test.js
plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap
plugins/nodes/src/js/pages/NodesAgents.js
plugins/nodes/src/js/pages/NodesMasters.js
plugins/nodes/src/js/routes/nodes.js
src/js/stores/MesosStateStore.js
src/js/stores/MesosStream/parsers/__tests__/master-test.js
src/js/stores/MesosStream/parsers/master.js

This Feature branch introduces Agents and Masters tabs. In its first iteration it will only contain a list of Details for the current leader.
Resolves  http://jira.mesosphere.com/browse/DCOS-39712
- https://github.com/dcos/dcos-ui/pull/3118
- https://github.com/dcos/dcos-ui/pull/3127
- https://github.com/dcos/dcos-ui/pull/3156
Before merging this branch: Navigate through the application, make sure all links pointing to nodes are still working and that agents and masters tabs are also working as expected. 
Due to lack of APIs, we decided not to implement a table yet, but go with a quick first implementation that only displays some data regarding the fcurrent leader. more info in JIRA.
**Update: 2018-08-14**: We'd like to merge this as-is and later add #3156 to master directly, reason is …

DCOS-39712: Nodes Masters Tab

---

plugins/nodes/src/js/pages/nodes-overview/HostsPageContent.js
plugins/services/src/js/containers/tasks/TasksView.js
src/styles/components/filter-bar/styles.less

Removes the left padding for left filter bar.
Closes DCOS-40158
* Go to Nodes and Service Tasks page
* Filter bar should be aligned

DCOS-40158: remove left-padding for left filter bar

---

src/js/pages/system/UnitsHealthTab.js
src/styles/components/form-elements/form-group/styles.less

Add width to the input to fix overflow after text is entered in Firefox.
Closes DCOS-21235
In Firefox, in `Components` tab type something in the search bar. The magnifying glass and the cancel icon shouldn't move when something is typed (see screenshots).
Also, if possible, test this change in other browsers as well - I tested in Chrome to make sure it still works correctly.
I spend some time looking and wondering where to put my css change. If someone has better place in mind, please tell me.
None.

DCOS-21235: [Firefox] Form control icons overflow issue

---

plugins/services/src/js/constants/ServiceTableHeaderLabels.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
plugins/services/src/js/containers/services/__tests__/__snapshots__/ServicesTable-test.js.snap
plugins/services/src/js/structs/ServiceTree.js
src/styles/components/service-table/styles.less

⚠️ this PR now also includes DCOS-39898 - it completely finishes the feature 👍 
---
Go to `Services` Tab and make sure that the new `Region` column is displayed and it works correctly.
Run `npm run test /plugins/services/src/js/containers/services/__tests__` to vertify that the new tests that I added run successfully.
I've updated the tests as well as the snapshots.
The current behavior is that if the regions array is empty, the cell will display "N/A", if there is more than one region they will be shown separated with commas, for example "Region 1, Region 2" and if a region is the same as the local region, it will be shown as "Region (Local)"
For the width of the column for different screen sizes, check out `src/styles/components/service-table/styles.less`, the values I used are slightly …

DCOS-39897: Add Region Column to Services Table

---

plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/utils/FrameworkUtil.js
plugins/services/src/js/utils/__tests__/FrameworkUtil-test.js

Closes [DCOS-40646](https://jira.mesosphere.com/browse/DCOS-40646)
check various frameworks to see that version is displayed correctly (parsed in table, full in tooltip)
Please see the linkes JIRA Issue for more details. I parsed all packages in the current universe and also shared the result in JIRA
None
Before:
After:

DCOS-40646: add base tech version parsing to services table 

---

plugins/services/src/js/pages/ServicesPage.js
plugins/services/src/js/stores/MarathonStore.js
plugins/services/src/js/structs/Framework.js
plugins/services/src/js/utils/FrameworkUtil.js
src/js/events/CosmosPackagesActions.js
src/js/events/__tests__/CosmosPackagesActions-test.js
src/js/stores/CosmosPackagesStore.js
src/js/stores/__tests__/CosmosPackagesStore-test.js
tests/_fixtures/marathon-1-task/groups-sdk-services.json
tests/pages/services/ServiceTable-cy.js
tests/pages/services/ServicesFilter-cy.js

* Uses the existing CosmosPackagesStores to retrieve the specific package from the availablePackages.
* Fetch its icons and display on the Services Page.
Closes DCOS-20989
* Deploy a package from the catalog
* Check that the icon appears for the framework in the services table
* Go to the framework details page and check that its icon is in the breadcrumbs
* Decided to fetch all the icons for all packages at once instead of having to make a request per service to get the icons
* Opted to use the existing mechanisms for fetching the available packages
* Opted for the simpler approach to update the packages when the services page is rendered instead of using the data layer

DCOS-20989: use CosmosPackagesStores icons for Services Page

---

plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx

Remove the (Local) addition when the local region is "N/A"
jira: https://jira.mesosphere.com/browse/DCOS-40495
In `Nodes` tab, in `Region` column, if there is no local region, the name should be shown just as `N/A` instead of `N/A (Local)`.
Alternatively, to test it, try replacing the function `regionRenderer` in `/plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx` the following way:
```
export function regionRenderer(
masterRegion: string,
data: Node
): React.ReactNode {
data;
masterRegion = "N/A";
const regionString = "N/A";
const regionName =
regionString +
(masterRegion === regionString && masterRegion !== "N/A"
? " (Local)"
: "");
return (
<TextCell>
<span title={regionName}>{regionName}</span>
</TextCell>
);
}
```
None that I am aware of.
None.

    DCOS-40495  Nodes Table Region Column shows "N/A (Local)"

---

src/js/pages/system/UnitsHealthTab.js
src/styles/components/form-elements/form-group/styles.less

Backport changes that fixed the form control icon overflow issues in Firefox for 1.11. This PR takes the approved changes from [#3186](https://github.com/dcos/dcos-ui/pull/3186) and adds them to the 1.11 branch.
Closes DCOS-40638
In Firefox, go to the Components tab and start typing in the filter input. The icons to the left and right of the text should remain aligned. Try also in Chrome to make sure the behaviour remains as expected there as well. 
I noticed that the cancel (x) icon to the right of the filter text was aligned noticeably lower than in the screenshots for [#3186](https://github.com/dcos/dcos-ui/pull/3186). `font-size: 0` was added to align the icon within its container. I'm keen for feedback on this, and whether the new alignment is correct (maybe we do not need it at …

DCOS-40638: Backport form control overflow fix for Firefox

---

plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/__snapshots__/ServicesTable-test.js.snap

In the first pass at adding the Regions table, we used a span element with a title attribute to show a native tooltip in order to side-step text wrapping issues we were seeing when using the Tooltip component
Closes: DCOS-40691
- Hard-code an array of region names in the "renderRegions" method in `/plugins/services/src/js/containers/services/ServicesTable.js`
- Go to the Services view
- Hover the text in the cells of the "Region" column
The tooltip should be hovering in the center of the cell, and the tooltip content text should be wrapping, not  overflowing the tooltip bubble or being chopped off
Nothing I can think of
None
**Before** (in `feature/DCOS-39895-services-region-info`):
**After:**

 DCOS-40691: in Services table, region column to use Tooltip component

---

src/js/schemas/JobSchema.js
src/js/schemas/job-schema/Docker.js
src/js/schemas/job-schema/Parameters.js
src/js/structs/Job.js
src/js/utils/JobUtil.js
tests/pages/jobs/JobJSONEditor-cy.js

Support docker parameters in Metronome jobs.
This is based on @kensipe PR https://github.com/dcos/dcos-ui/pull/3037
Closes DCOS_OSS-3802
Make sure you are using a cluster that has the feature. Latest `master` does have it.
I also created a cluster for today. You can find the link in the frontend channel.
try creating/editing a job
```
{
"description": "Example Application",
"id": "docker-param",
"run": {
"cmd": "sleep inf",
"cpus": 0.2,
"mem": 32,
"docker": {
"image": "ubuntu",
"parameters": [
{
"key": "cap-drop",
"value": "ALL"
},
{
"key": "cap-add",
"value": "SYSLOG"
}
]
}
}
}
```

DCOS_OSS-3801: Support docker parameters in Metronome jobs

---

.releaserc
Jenkinsfile
npm-shrinkwrap.json
package.json
plugins/tracking/hooks.js
scripts/ci/upload-release
src/index.html
src/js/stores/MetadataStore.js
webpack/webpack.production.js

Track errors with [Sentry](https://sentry.io)
Closes DCOS-20689
- Enable `tracking` plugin in your Config.dev.ts
- Add an exception to any place in code
- Reach this place on the UI
- Verify that the error is reflected and all tags (environment, variant, version) are set.
We track two versions: DCOS and DCOS-UI. DCOS-UI version will be set as a `release` in Sentry where dcos version as a tag. I did this because we are going to be shipping UI as a package thus having the same UI release running on different DCOS versions. Plus I'm going to connect Sentry and Github to provide better dev experience.

DCOS-20689: introduce Sentry bug tracking SaaS

---

plugins/services/src/js/containers/services/ServicesTable.js

1. Add a service that is not a framework
2. Check the entry Services table - the cell in the "Version" column should be empty
Not that I can think of
None
Before:
After:

DCOS-40897: show a blank version cell if service is not a framework

---

plugins/nodes/src/js/components/NodesTable.js

In 1.11 remove the (Local) addition when the local region is "N/A"
Closes https://jira.mesosphere.com/browse/DCOS-40893
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`. Then run `npm install`.
https://stackoverflow.com/a/33575448
2. In `Nodes` tab, in `Region` column, if there is no local region, the name should be shown just as `N/A` instead of `N/A (Local)`.
Alternatively, to test it, try replacing the …

DCOS-40893: Nodes Table Region Column shows "N/A (Local)" backport 1.11

---

scripts/ci/upload-release

turns out that `sed -i ''` is only supported on macOS, its `sed -i''` or `sed -i` on GNU sed…
launch our `mesosphere/dcos-ui` docker container and try both variants of the command, `sed -i '' s/…/…/ dist/index.html` works on macOS, but fails on linux. the space is misinterpreted as "next argument" which means that the search expression is empty…
current error on master:
https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/master/421/pipeline#step-86-log-110
reproduced and fixed commands in docker instance:
```
root@2566f4489bf9:/dcos-ui# sed -i '' s/0.0.0-dev+semantic-release/master+v2.15.0/ dist/index.html
sed: can't read s/0.0.0-dev+semantic-release/master+v2.15.0/: No such file or directory
root@2566f4489bf9:/dcos-ui# sed -i …
```

DCOS-20689: remove space before value for sed -i flag

---

src/js/pages/system/UnitsHealthTab.js
src/styles/components/form-elements/form-group/styles.less

In 1.11 add min-width to the input to fix overflowing icons in Firefox.
Closes https://jira.mesosphere.com/browse/DCOS-40779
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`. Then run `npm install`.
https://stackoverflow.com/a/33575448
2. Verify that the icons are fixed for all input bars (see screenshots). If possible, verify that the icons look good in other browsers.
I added `{display: block}}` to the …

    DCOS-40779: [Firefox] Form control icons overflow issue (for other components) backport 1.11

---

src/styles/components/form-elements/form-group/styles.less

In 1.10 add min-width to the input to fix overflowing icons in Firefox.
Closes https://jira.mesosphere.com/browse/DCOS-40881
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`.
https://stackoverflow.com/a/33575448
2. Verify that the icons are fixed for all input bars (see screenshots). If possible, verify that the icons look good in other browsers.
I added `display: block` to the icons …

DCOS-40881: [Firefox] Form control icons overflow issue (for other components) backport 1.10

---

system-tests/nodes/test-nodes.js

Add a system test for the Masters tab on the Nodes page to check that Leader info gets displayed.
Closes DCOS-40051
Run the nodes system test and ensure that it passes (maybe a few times to ensure that it's not 'flaky').
To simulate no data, change line 39 in /plugins/nodes/src/js/data/MesosMasters.js to:
```
leader: mastersInitialState().leader
```
This will result in the component not getting the leader information and will get stuck with loader spinners beside IP and Port, Region, etc. Tests run with this change should NOT pass.
To run system tests against local code:
```
#!/bin/bash
set -ex
USER_AUTH_INFO="<your dcos-acs-info-cookie>"
npx cypress open --project './system-tests' --env CLUSTER_URL="http://127.0.0.1:4200",CLUSTER_AUTH_TOKEN="<your …
```

DCOS-40051: Write one system test for the Nodes Master Tab

---

Dockerfile

Adjust Dockerfile to use local docs-launch instead of installing it from
a remote location. This changes is a hot fix to workaround issues with
the latest dcos-launch release which broke out system tests.
With this change our CI should be able to spin up a cluster for out system test again.
We need to revert this change once we've agreed on a release and integration process with the respective team to always integrate with latest release when possible.

ci: use local dcos-launch bin

---

plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap
src/js/utils/DateUtil.js
src/js/utils/__tests__/DateUtil-test.js

JIRA: [DCOS-40048](https://jira.mesosphere.com/browse/DCOS-40048)
Navigate to `/nodes/masters` and click on the text stating `X Something ago` - it should toggle to a Date. Verify that that Date is formatted correctly.
* When using the `<ToggleContent />` component there is no dotted line, is this line supposed to be added in dcos-ui or should it be part of the `<ToggleContent />` component? 🤔 
* I decided to change the diplayed format of `DateUtil.msToDateStr` to our desired format, the function is only used on Nodes Details page and since we're on Master Detail here, I think it is good thing to have them aligned.

DCOS-40048: add toggle to date information on leader tab

---

scripts/ci/upload-release
scripts/ci/utils/update-dcos-repo
scripts/ci/utils/upload-build
scripts/post-checkout
scripts/post-commit
scripts/post-rewrite
scripts/pre-commit
scripts/pre-install
scripts/pre-push
scripts/run-integration-tests
scripts/utils/git
scripts/utils/marathon
scripts/validate-engine-versions
scripts/validate-tests

I've messed up my new laptop setup and now I have a space in my home directory name 😩 
Because of that I realized that our scripts don't support that. So I double quoted everything that `shellcheck` asked me to double quote and what made sense to me.
On top of that I followed its advice and added `:?` to `rm -rf ${VAR}` so it become `rm -rf ${VAR:?}` so that if `$VAR` for whatever reason empty we don't kill `/`
Try running those scripts from a path that has a space in it.
There are some more stuff `shellcheck` complains about. I decided keeping the scope rather small.

chore: double quote paths so that it allows spaces

---

src/js/utils/Units.js
src/js/utils/__tests__/Units-test.js

Jobs details was showing NaN value for the gpu resource if it wasn't provided (ie if job did not use gpu resources). Ensure Units `formatResource` utility handles undefined input by returning 0 as default for undefined cpu, gpu.
Closes DCOS-37789
Start a job that doesn't use gpu resources (ie a basic command like `sleep 60`). Check the Configuration details for that run and ensure that the gpu resource does not appear as NaN.
The Units utility (specifically the `formatResource` method) is used in many other components in the Services plugin. None of them currently handle undefined values (from what I could tell) except for the DeclinedOffersTable, which defaults to "N/A". This change would affect everywhere that uses this method, which means the "N/A" default will be overridden. 
I have …

DCOS-37789: Fix gpu NaN in Jobs details

---

src/styles/components/framework-configuration/styles.less

navigate to package detail and package config review screens for multiple packages and verify that package description and orange-ish box is displayed correctly.
(remember to `npm install` after you checked out the branch)
~I decided to refactor the way we inject markdown because the old one used `dangerouslySetInnerHTML` which - by its name - should be replaced ASAP and it was an easy win. 
If it causes any trouble in this PR, I'm happy to remove or extract it.~ tests failed, data isnt in shape, removed it from this PR.
**Before:**
**After:**

DCOS-21187: fix preinstall styling and markdown usage

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js

This fixes an issue which happens when you create a multi container service with a volume mount and
you later in the process remove the last volume mount. The volume will get removed from the json but
the volumemount stays in the json.
Close DCOS-15289
To test this 
- Go to `/#/services/overview/create`.
- Select `Multi-Container (Pod)`
- Go to `Volumes`
- Click `Add Volume`
- Open JSON editor 
Your container should look like this:
```JSON
{
"resources": {
"cpus": 0.1,
"mem": 128
},
"volumeMounts": []
}
```
- Now click `Add Volume` 
- Add a name `volume`
- In the Container path section next to `container-1` add a container path: `containerPath`
- In the JSON editor you should see:
```JSON
{
"resources": {
"cpus": 0.1,
"mem": 128
}, …
```

DCOS-15289: fix(serviceform): fix containers reducer

---

plugins/services/src/js/components/DeclinedOffersTable.js
plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
src/styles/content/tables/styles.less

Removes truncation and wraps content for "Load Balanced Address" column under the Networking section on the review service screen.
Closes DCOS-40685
* Open Create Service Form and paste the following in JSON Editor:
```
{
"id": "/truncation-test",
"container": {
{
"hostPort": 0,
"labels": {
"VIP_0": "/truncation-test:10101"
},
"name": "test"
}
],
"volumes": [],
"docker": {
"image": "nginx"
}
},
"cpus": 0.1,
"mem": 128,
"networks": [
{
"mode": "container/bridge"
}
],
"fetch": [],
}
```
* Click "Review & Run"
* "Load Balanced Address" column content is not truncated
* When the header is truncated, the caret does not show on the column, I …

DCOS-40685: remove text truncation for load balanced address

---

src/js/components/charts/HostTimeSeriesChart.js
src/js/pages/DashboardPage.js

Match the design team's mocks with the nodes chart green
Closes DCOS-40899
Go to the dashboard
The Nodes chart should be green
Probably not
None
Before:
After:

DCOS-40899: make the graph in the Nodes chart green

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This fixes an issue which blocked the user from switching from Mesos runtime to docker runtime if
they provided a 0 gpu setting.
Close DCOS-21464
To test this:
- go to: `/#/services/overview/create`
- Select `Single Container`
- In the General Section click `More Settings`
- Select `Universal Contianer Runtime (UCR)`
- Go to GPUs and enter a value bigger as `0`
- The Docker Runtime should get disabled here
- Change the value of GPUs to `0`
- Select Docker Runtime 
This solution will have the trade of that in the case of a 0 gpu value the `gpus` in the JSON will be `0` which is mostly a cosmetic drawback as Marathon will accept it anyways.

DCOS-21464: fix(serviceform): fix 0 gpu runtime block

---

src/js/pages/network/VirtualNetworksTab.js

Fix filter function to allow filtering of networks table. Previously, you could only type one character into the filter and the rest wouldn't appear, and the table contents weren't filtering as expected.
Closes DCOS-40780
Go to networks table and try filtering based on Name and IP Subnet. Ensure that you try a search string that matches the subnet in both entries (if you're testing with the regular shared cluster).
None that are obvious to me.

DCOS-40780: Fix filter on networks table

---

plugins/intercom/hooks.js
plugins/intercom/stores/IntercomStore.js
plugins/intercom/stores/__tests__/IntercomStore-test.js

This PR adds a UUID part to intercom user ID so intercom could tell between different users.
Closes DCOS-41283
1. Read the thread https://mesosphere.slack.com/archives/C03UXUVH7/p1535963672000100
2. Verify that all the history is available on the daily cluster
3. Checkout the PR
4. Verify that _all_ the history is not available anymore, but only messages sent from your user and that very cluster.
5. Create a new user under `Organization -> Users`
6. Verify that the history of the default user in not available for the new user
1. Listed in the above mentioned Slack thread
2. I decided to add `user_id` post intercom boot so that we don't need to wait for all metadata before we boot

DCOS-41283: Add zbase to user_id in Intercom

---

plugins/catalog/src/js/repositories/components/AddRepositoryFormModal.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js

This removes the regex validation of the url field and lets rather the backend decide if a url is
valid or not.
Close DCOS_OSS-526
For Review, you may look at 65a30cfa341e771d216a1a1037504455df8c5be1 this is the commit which if filtered of the code style changes.
To Test this:
- go to `Settings > Package Repository`
- Click the `+`
- Add a random Repository Name
- Add a url like `http://0.0.0.1:8080`
- Add a priority `1`
- Click `Add`
Now you should be presented with the error from the server instead of the error on the input field.
A Trade off is that we are showing the error from the Server which can be unexpected long for example with the url `http://0.0.0.0:8080` it will show some long message which is not really helpful.
*Before*:
*After*:

DCOS_OSS-526: fix(package repository settings): remove url validation on add

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
tests/pages/services/ServiceFormModal-cy.js

For pods, fixes the issue where when adding a service endpoint in host mode, there was no fields shown to enable VIP (load balanced address).
Closes DCOS_OSS-1551
* Go to pod create service form
* Click Networking tab
* Click Add Service Endpoint _("Enable Load Balanced Address" checkbox shows)_
* Click the checkbox _(Open JSON editor and labels:VIP_0 shows)_
* Enter a load balanced port _(labels:VIP_0 is updated with the port)_
* Decided to remove the checks for network type based on the assumption that any network type can have VIP properties set.
None

DCOS_OSS-1551: show VIP fields in host mode

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
tests/pages/services/ServiceFormModal-cy.js

- Go to the pods / service form
- Go to the environment section
- Create a label without a key
- See that it is shown as an error
None that I am aware of
None

DCOS-20222: add error for environment values without keys

---

src/js/pages/catalog/PackagesTab.js
tests/pages/catalog/packages/PackagesTab-cy.js

Provide a message indicating when no results were found when searching Catalog page.
Closes DCOS-40781
Go to Catalog page and try searching using strings that will match as well as strings that won't. Ensure regular filtering happens as expected and ensure non-matching strings show the empty message. Ensure 'view all' clears the filter as expected.
Seems a little convoluted to handle the search results from within `getCommunityPackagesGrid`. Maybe this could eventually be refactored into its own function.
Before: 
After:

DCOS-40781: Provide empty message for catalog search

---

plugins/services/src/js/components/DeclinedOffersTable.js
plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
src/styles/content/tables/styles.less

Backport of DCOS-40685
https://github.com/dcos/dcos-ui/pull/3222
* Open Create Service Form and paste the following in JSON Editor:
```
{
"id": "/truncation-test",
"container": {
{
"hostPort": 0,
"labels": {
"VIP_0": "/truncation-test:10101"
},
"name": "test"
}
],
"volumes": [],
"docker": {
"image": "nginx"
}
},
"cpus": 0.1,
"mem": 128,
"networks": [
{
"mode": "container/bridge"
}
],
"fetch": [],
}
```
* Click "Review & Run"
* "Load Balanced Address" column content is not truncated

[1.11] DCOS-41282: remove text truncation for load balanced address

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This fixes an issue which blocked the user from switching from Mesos runtime to docker runtime if
they provided a 0 gpu setting.
Close DCOS-21464
```
```
**Checklist**

[1.11] fix(serviceform): fix 0 gpu runtime block

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js

This fixes an issue which happens when you create a multi container service with a volume mount and
you later in the process remove the last volume mount. The volume will get removed from the json but
the volumemount stays in the json.
Close DCOS-15289

[1.10] BACKPORT: Ph/backport/dcos 41280 1.10

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js

This fixes an issue which blocked the user from switching from Mesos runtime to docker runtime if
they provided a 0 gpu setting.
Close DCOS-21464
```
```
**Checklist**

[1.10] fix(serviceform): fix 0 gpu runtime block

---

plugins/services/src/js/containers/services/ServicesTable.js

Overflowing text was causing the tooltip to misalign
Closes DCOS-41121
Add filler text in the `Tooltip` returned by the `renderVersion()` method to cause an ellipsis
Go to Services tab
Hover the version cell
No
No
Before:
After:

DCOS-41121: version cell tooltip alignment

---

src/js/components/modals/AddRepositoryFormModal.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js

This removes the regex validation of the url field and lets rather the backend decide if a url is
valid or not.
Close DCOS_OSS-526
```
```
**Checklist**

[1.11] BACKPORT: fix(packagerepository): remove url validation on add

---

src/js/pages/catalog/PackagesTab.js
tests/pages/catalog/packages/PackagesTab-cy.js

Backport changes from #3231 that provide a message indicating when no results were found when searching Catalog page.
Closes DCOS-41391
Go to Catalog page and try searching using strings that will match as well as strings that won't. Ensure regular filtering happens as expected and ensure non-matching strings show the empty message. Ensure 'view all' clears the filter as expected.

[1.11] Backport: fix(PackagesTab): provide empty message for catalog search

---

src/js/pages/network/VirtualNetworksTab.js

Backport changes to fix filter function to allow filtering of networks table.
DCOS-41514 should not be closed until #3252 is merged as well.
See #3221

[1.11] Backport: fix(VirtualNetworksTabContent): fix filter on networks table

---

src/js/pages/network/VirtualNetworksTab.js

Backport changes to fix filter function to allow filtering of networks table.
Do not close DCOS-41514 until #3251 is merged as well.
See #3221

[1.10] Backport: fix(VirtualNetworksTabContent): fix filter on networks table

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/FormReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Containers-test.js
plugins/services/src/js/reducers/serviceForm/FormReducers/__tests__/Endpoints-test.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/Endpoints.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Endpoints-test.js
plugins/services/src/js/utils/ValidatorUtil.js
plugins/services/src/js/utils/VipLabelUtil.js
tests/pages/services/ServiceFormModal-cy.js

Backport for 1.10. See: https://github.com/dcos/dcos-ui/pull/3233
* In 1.10, the load balanced port is the same as the container port when network type is set to container (Virtual Network: dcos in the UI)
* To add load balanced port for network type "Host", it did not make sense to me to set the load balanced port to be the same as host port, therefore I added the load balanced port field.

[1.10] DCOS_OSS-4034: show VIP fields in host mode

---

src/js/components/ResourceSwitchDropdown.js
src/styles/components/dropdown-menus/styles.less

The style to highlight a selected item was not applied on the ResourceSwitchDropdown of the Nodes chart view
Closes: DCOS-40507
Navigate to the "Nodes" page
Toggle the chart view by clicking the donut icon on the right side of the view
Change the selected item in the dropdown to the left of the list icon (initial state is "CPU")
The text and icon of the selected item in the dropdown should be purple (see screenshots below)
The styling change in this PR could have also been made in [reactjs-components](https://github.com/mesosphere/reactjs-components/), but I saw other style overrides happening directly in dcos-ui. **Please let me know if we'd prefer the `.is-selected` style update to be made in reactjs-components instead**
None
Before:
After:

DCOS-40507: style selected state for ResourceSwitchDropdown items

---

src/styles/components/task-table/styles.less

Even at fullscreen, the Health column header was being truncated in Firefox
Closes: DCOS-40649
Use Firefox to test this change
Add a framework from the Catalog (I used Kafka)
Navigate to the "Services" page
Click on the new service
The health column header should not be truncated
A better way to fix this would be to rendered this table with the components from ui-kit. However, that would take a little more time in order to support the checkbox selection of table rows ([ticket created here](https://jira.mesosphere.com/browse/DCOS-41571))
None
Before:
After:

DCOS-40649: Health column header truncated in FF

---

src/js/pages/catalog/PackagesTab.js
tests/pages/catalog/packages/PackagesTab-cy.js

Backport changes from #3231 that provide a message indicating when no results were found when searching Catalog page.
Closes DCOS-41396
Go to Catalog page and try searching using strings that will match as well as strings that won't. Ensure regular filtering happens as expected and ensure non-matching strings show the empty message. Ensure 'view all' clears the filter as expected.

[1.10] Backport: fix(PackagesTab): provide empty message for catalog search

---

src/js/pages/system/units-health-node-detail/NodeInfoPanel.js

Check if link is empty and if yes, do not show it.
Closes https://jira.mesosphere.com/browse/DCOS-41015
It turns out that the id that should show the link here (see `/src/js/components/UnitsHealthNodeDetail.js`) doesn't exist in `/src/js/constants/UnitSummaries.js`. Until now, this meant that the default documentation page was shown, however this is broken in 1.12. @juliangieseke and I decided to hide the link if no page is given and fix the id and the links in another issue.
Go to `Nodes`
Click a Node
Click Health
Click any of the links in the `Health Check` column
Verify that the page doesn't contain an unclickable link
Althouth I considered deleting it, I decided to keep `documentationURI` in `Config.ts`, because I think we will need it later.
None

DCOS-41015: Nodes Health missing link

---

src/js/pages/system/units-health-node-detail/NodeInfoPanel.js

1.11 backport for https://github.com/dcos/dcos-ui/pull/3264
Half of https://jira.mesosphere.com/browse/DCOS-41016
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`. Then run `npm install`.
2.Go to `Nodes`
Click a Node
Click Health
Click any of the links in the `Health Check` column
Verify that the page doesn't contain an unclickable link

DCOS-41016: Nodes Health missing link (backport 1.11)

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
tests/pages/services/ServiceFormModal-cy.js

Go to the Service form and open the JSON editor. Create invalid JSON. Admire the error message being shown on the left side and the review button not doing anything on click
- Decided against system tests, as this is a UI only issue IMHO
None
From 1.12:

DCOS-41502: show JSON parsing errors as top level errors

---

src/js/pages/system/units-health-node-detail/NodeInfoPanel.js

1.10 backport for https://github.com/dcos/dcos-ui/pull/3264
Half of https://jira.mesosphere.com/browse/DCOS-41016
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`. Then run `npm install`.
2.Go to `Nodes`
Click a Node
Click Health
Click any of the links in the `Health Check` column
Verify that the page doesn't contain an unclickable link

DCOS-41016: Nodes Health missing link (backport 1.10)

---

packages/data-service/README.md

Just a link to the google docs for the data layer so it is not lost in space.

Add link to data-layer core document

---

src/js/utils/MesosStateUtil.js
src/js/utils/__tests__/MesosStateUtil-test.js

The resources shown on the nodes table and nodes grid view were not in sync. The difference is accounted for by including the resources used by the executor. This was not included in the calculation for the nodes grid view.
Closes DCOS-39800
* Deploy Kafka from the Catalog
* Click on Nodes Tab
* Check between the List/Grid view _(The resources (CPU/Mem/Disk) match between the two views)_
* First I looked to NOT use the tasks in computing the framework resource usage per slave
* From looking at the data returned in `lastMesosState` and `CompositeState`, I could see no good way to relate frameworks with slaves
* I decided to simply just include executors along with tasks in `getHostResourcesByFramework`
None

DCOS-39800: include executor in getHostResourcesByFramework

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Volumes.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Volumes-test.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

This ensures that persistent volumes do contain a field with a non null value. This is needed so
that the rendered JSON does contain a persistent attribute in the volume.
Close DCOS-14757

DCOS-14757: Fix Volumes reducer [1.10]

---

src/js/pages/catalog/__tests__/__snapshots__/PackageDetailTab-test.js.snap
src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js
tests/_fixtures/cosmos/package-describe.json
tests/pages/catalog/packages/package/PackageTab-cy.js

Ensure links on package detail page rendered from markdown open in new tab.
Closes DCOS-8601.
- Go to catalog page
- Click on spark
- Ensure link in Description section opens in new tab
- Back to catalog page
- Click on kubernetes
- Ensure link in pre install section opens in new tab
Some links were opening in new tabs already and some were not - the ones that were not were being rendered from markdown. This makes wrapping the individual links in a component difficult since they are not separated from other text. We are currently using a package called `marked` to parse the markdown in the StringUtil `parseMarkdown` method. I've modified the `marked` renderer to add target="_blank" to links. This affects links in the Description, Pre Install notes, and Post Install notes sections.
For a …

DCOS-8601: Ensure package detail links open in new tab

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js
tests/_fixtures/marathon-1-pod-group/groups.json
tests/_fixtures/marathon-1-task/groups.json
tests/pages/services/ServiceFormModal-cy.js
tests/pages/services/ServicesFilter-cy.js

This change allows the VIP port to be edited on the UI even when the VIP hostname is not the same value as the app-id.
- Deploy an app with a VIP label [0]
- Go to edit the app definition
- Go to Networking
- Find the field Load Balanced Port, and test it.
- No refactoring just bug fixing, but I believe the VIP logic could be refactored to a better shape so logic is removed from the UI Component
None.
Before and after.
https://cl.ly/e769ee2d9a50
```
{
"id": "/abc",
"container": {
{
"containerPort": 10,
"labels": {
"VIP_0": "asbc:9033"
},
"name": "ping"
}
],
"volumes": [],
"docker": {
"image": "nginx"
}
},
"cpus": 0.1,
"mem": 128,
"networks": [
{
}
],
"fetch": …
```

DCOS-21307 allows VIP to have custom formats

---

src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js
tests/_fixtures/cosmos/package-describe.json
tests/pages/catalog/packages/package/PackageTab-cy.js

Backport changes that ensure links on package detail page rendered frmo markdown open in new tab.
Closes DCOS-41667.
- Go to catalog page
- Click on spark
- Ensure link in Description section opens in new tab
- Back to catalog page
- Click on kubernetes
- Ensure link in pre install section opens in new tab
See #3263

[1.11] Backport: fix(PackageDetailTab): package detail links open in new tab

---

src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js
tests/_fixtures/cosmos/package-describe.json
tests/pages/catalog/packages/package/PackageTab-cy.js

Backport changes that ensure links on package detail page rendered from markdown open in new tab.
Closes DCOS-41668.
- Go to catalog page
- Click on spark
- Ensure link in Description section opens in new tab
- Back to catalog page
- Click on kubernetes
- Ensure link in pre install section opens in new tab
See #3263

[1.10] Backport: fix(PackageDetailTab): package detail links open in new tab

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js
tests/_fixtures/marathon-1-pod-group/groups.json
tests/_fixtures/marathon-1-task/groups.json
tests/pages/services/ServiceFormModal-cy.js

This change allows the VIP port to be edited on the UI even when the VIP hostname is not the same value as the app-id.
Closes DCOS-41700
- Deploy an app with a VIP label [0]
- Go to edit the app definition
- Go to Networking
- Find the field Load Balanced Port, and test it.
- No refactoring just bug fixing, but I believe the VIP logic could be refactored to a better shape so logic is removed from the UI Component
None.
Before and after.
https://cl.ly/e769ee2d9a50
```
{
"id": "/abc",
"container": {
{
"containerPort": 10,
"labels": {
"VIP_0": "asbc:9033"
},
"name": "ping"
}
],
"volumes": [],
"docker": {
"image": "nginx"
}
},
"cpus": 0.1,
"mem": 128,
"networks": [
{
}
], …
```

1.11 DCOS-41700: allows VIP to have custom formats

---

src/js/components/FrameworkConfigurationReviewScreen.js
src/js/components/HashMapDisplay.js

I was resolving some React warnings in the Services section and ran across https://jira.mesosphere.com/browse/DCOS-35756 (which was not prioritized) and decided to implement @juliangieseke proposed fix from the discussion here https://github.com/dcos/dcos-ui/pull/2913#discussion_r184711525
While I was in there, I refactored HashMapDisplay a little for complexity and fixed another warning related to using a prop named "key"
1. Add kafka service
2. Visit  kafka service detail
3. Click configuration tab
4. It should look the exact same
One drawback of the HashMapDisplay component is that it begins with &lt;h2&gt; if there is no top level headline defined. An alternative implementation could deduct 1 from the headlineLevel prop if no headline is given.
None
Warnings seen here

DCOS-35756: Fix Headings levels in Config Screens

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js
tests/_fixtures/marathon-1-pod-group/groups.json
tests/_fixtures/marathon-1-task/groups.json
tests/pages/services/ServiceFormModal-cy.js

Allows the VIP port to be edited in the UI even when the VIP host name is not the same as the app-id.
1.10 backport for https://github.com/dcos/dcos-ui/pull/3256
Closes https://jira.mesosphere.com/browse/DCOS-41699
- Deploy an app with a VIP label [0]
- Go to edit the app definition
- Go to Networking
- Find the field Load Balanced Port, and test it.
none

DCOS-41699: [1.10] Changing custom VIP port from the form doesn't work

---

plugins/services/src/js/containers/pod-instances/PodInstancesContainer.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/tasks/TasksContainer.js

* There is no `fetchData` method defined in `TasksContainer.js`, so it makes sense to remove the method call 😏 
* Deploy a service with command `sleep 100`
* Go to its service detail page
* Check the task and click delete to delete it
* Check there are no errors in the console
* I went ahead and removed other calls for fetchData in other files.

DCOS-21986: remove undefined fetchData method call

---

plugins/services/src/js/components/forms/NetworkingFormSection.js
plugins/services/src/js/reducers/serviceForm/Container.js
plugins/services/src/js/reducers/serviceForm/__tests__/Container-test.js

Allows adding service endpoints when Container Runtime is UCR and Network Type is Virtual Network: dcos
Closes https://jira.mesosphere.com/browse/DCOS-41903
1.10 backport for https://github.com/dcos/dcos-ui/pull/2800
1. Switch to branch 1.10 and set up node to use version 4.4.7 and npm to use version 3.9.6
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`.
2. Go to Services
3. Create a new Single Container Service
4. In the first tab click `More …

DCOS-41903: [1.10] COPS-2911 affecting cnidcos-uimarathon-lb: Expose CNI task via Marathon-LB

---

plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
plugins/services/src/js/containers/service-connection/ServicePodConnectionEndpointList.js
src/styles/components/code/styles.less

1. We were often passing in port values as numbers, which were triggering PropType warnings
2. I added a style fix for something that may or may be intentional. @lilysamimi can you confirm that this was an unintentional background color or perhaps a padding issue?
1. Add nginx service
2. Visit service detail, Endpoints tab
3. No warning, no floating background
I could have alternatively loosened the proptype requirements for EndpointClipboardTrigger to accept numbers/strings.
Warnings visible here
Look closely and you can see the floating shadow/background
1.12
1.11
And here is the after: (tooltip not changed)

DCOS-41769: Clipboard icon background fix / React warning

---

plugins/services/src/js/components/modals/CreateServiceModal.js
src/js/components/FrameworkConfiguration.js
src/js/components/FrameworkConfigurationForm.js
src/js/components/SchemaField.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceFormModal-cy.js

Form controllers that are affected by this change are FramworkConfiguration and CreateServiceModal. They now need to trigger validation after submitting and not at all times.
Unfortunately, these two forms have different lifecycles with respect to real time validation:
CreateServiceModal:
1. Create a single container service
2. clear Service ID
3. observe no validation errors
4. click Review & Run
5. observe validation errors
FrameworkConfiguration:
1. Create a cassandra service
2. clear name
3. observe no validation errors
4. click Review & Run
5. observe validation errors
This change introduces some damage and workarounds in FrameworkConfigurationForm due to the limitations of react-jsonschema-form
1. On FrameworkConfiguration, the JSONEditor does not display errors until Review & Run …

DCOS-22126: Don't validate forms until submit

---

plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js

Fixes React proptype warning
It is possible for this component to receive an Application instance from `js/components/HighOrderServiceConfiguration`
1. Add nginx service
2. Navigate to nginx service details, Configuration tab
No React warning
Should there be an ApplicationConfigurationContainer added to the various containers delegated to by  `js/components/HighOrderServiceConfiguration` ?
None
Warning seen here:

chore(FrameworkConfigurationContainer): fix react warning

---

plugins/services/src/js/components/ServiceBreadcrumbs.js

Unused prop on this react-router component was triggering a React proptype warning
1. Add hello-world service from catalog
2. Visit service details, container-1 logs tab
3. Observe no warnings
Warnings here:

chore(ServiceBreadcrumbs): Remove unused prop

---

src/styles/components/modal/full-screen/styles.less
src/styles/components/modal/full-screen/variables.less
tests/pages/services/ServiceFormModal-cy.js

We get complaints that the width of the JSON editor makes it hard to use, especially for catalog packages
Closes DCOS-19300
This is a good start, but I've filed a [follow-up issue](https://jira.mesosphere.com/browse/DCOS-42072) to make the editor resizable, per @leemunroe's suggestion
1. Go to Catalog and select a framework
2. Tap "Review & Run"
3. Toggle the JSON editor using the toggle switch in the modal header
The JSON editor should be a comfortable width to work with, and the form on the left should still be scannable
Note: The JSON editor also appears when adding a new service (go to Services tab and tap the "+" icon in the upper right). I checked it in both places before submitting this PR
None
None
Before:
After:

DCOS-19300: make the JSON editor wider

---

src/styles/components/scrollbar/styles.less

Looks like new node/npm version has something to do with the way we bundle our build. We've fixed the issue for 1.12 in https://github.com/dcos/dcos-ui/pull/3018 and after upgrading node/npm on 1.11 it popped up.
Closes DCOS-42132
0. Connect to the VPN if not in the office 😅 
1. check out release/1.11
2. make sure you are running node@8.9.4 npm@5.6.0
3. npm run build-assets
4. ./node_modules/.bin/http-server ./dist --proxy-secure=false -P https://soak111.testing.mesosphe.re
5. http://0.0.0.0:8080 - verify that UI doesn't scroll on any pages. I.e. Nodes page
6. Checkout the branch
7. Repeat the steps verifying that the change fixes the issue.

DCOS-42132: Fix scrolling on the UI

---

src/styles/components/framework-configuration/styles.less

Long labels were allowed to flow outside of <fieldset>s because most browsers set a useragent style on <fieldset> like  min-width: [min-content](https://developer.mozilla.org/en-US/docs/Web/CSS/width#min-content)
Closes DCOS-42157
1. Go to "Catalog"
2. Add the Elastics services
3. Go to the "Elasticsearch" tab
4. Toggle the JSON editor open
5. Resize your viewport width to somewhere between 991px and 1050px
Any labels in the form should be truncated with an ellipsis, not overflowing out of the width
It doesn't feel quite right to truncate a form label, but we at least provide a `title` attribute, and labels long enough to be truncated are an edge case
This issue will be more easier to reproduce once #3293 merges and makes the JSON editor wider
Before:
After:

DCOS-42157: truncate FrameworkConfigurationForm labels instead of overflowing

---

Jenkinsfile
npm-shrinkwrap.json
package.json
scripts/ci/upload-release
scripts/ci/utils/upload-sourcemaps

This PR adds a script to our release pipeline that uploads source maps to sentry.io to improve dev experience.
1. Get Sentry token in Onelogin secure notes
2. Make a build `npm run build-assets`
3. Run the script 
```
SENTRY_AUTH_TOKEN="<token>" \
RELEASE_NAME="test-<any salt>" \
./scripts/ci/utils/upload-sourcemaps
```
1. It's a shell script, sorry
2. Decided to go with a CLI lib instead of cURL https://docs.sentry.io/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry to spare some time debugging
3. This very PR won't trigger a release since we don't release `chore` commits

DCOS-40650: upload source maps to sentry.io

---

package.json
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/utils/ServiceTableUtil.js
plugins/services/src/js/utils/__tests__/ServiceTableUtil-test.js

Fix sorting on versions column in Services table.
Closes DCOS-21233.
Run some services that have displayed versions (ex: kafka, cassandra) and some that don't (nginx). Go to services page and sort table on versions column.
- Added the [compare-versions](https://github.com/omichelsen/compare-versions) npm package (MIT license) to handle determining sort order of dot separated version numbers
- Extracted the logic involved in getting displayed version numbers out from the `ServicesTable` component to the `ServiceTableUtil` so it could be reused in the version sort function as well
None
Before video in [Jira ticket](https://jira.mesosphere.com/browse/DCOS-21233). 
After:

DCOS-41973: Fix sorting on services table (versions column)

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
src/styles/components/form-elements/styles.less
tests/pages/services/ServiceFormModal-cy.js

Show error when a label has a value but no key
Closes https://jira.mesosphere.com/browse/DCOS-42054
1. Switch to branch 1.10 and set up node to use version 4.4.7 and npm to use version 3.9.6
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`.
2. Test the changes
Click on Single Container
Click on Environment
Click on `Add Label`
Enter a `Value` without entering `Key`
Verify that …

DCOS-42054: [1.10] Invalid labels have no error and are simply ignored

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
src/styles/components/form-elements/styles.less
tests/pages/services/ServiceFormModal-cy.js

backport for https://github.com/dcos/dcos-ui/pull/3234 with some minor fixes
Half of https://jira.mesosphere.com/browse/DCOS-42035
This branch was created using @DanielMSchmidt 's tool https://github.com/DanielMSchmidt/backporter which works great.
1. Switch to branch 1.10 and set up node to use version 4.4.7 and npm to use version 3.9.6
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 4.4.7` in the directory. Setting up npm is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v4.4.7/lib` and run `npm install npm@3.9.6`.
2. Test the changes
Click `+` or `Run a …

DCOS-42035: Invalid Environment variables have no error and are simply ignored (1.10 backport)

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
src/styles/components/form-elements/styles.less
tests/pages/services/ServiceFormModal-cy.js

Show error when a label has a value but no key
Closes https://jira.mesosphere.com/browse/DCOS-42055
1. Switch to branch 1.11 and set up node to use version 8.9.4 and npm to use version 5.6.0
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 8.9.4` in the directory. Setting up npm should happen automatically in this case, but if it doesn't, it is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v8.9.4/lib` and run `npm install npm@5.6.0`.
2. Test the changes
Click on Single Container
Click on Environment
Click on `Add Label`
Enter a …

DCOS-42055: [1.11] Invalid labels have no error and are simply ignored

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js

Before, 'name' was the only part of the updated value being pushed into newState
Closes DCOS_OSS-1961
1. Go to "Services"
2. Add a new service by clicking "+" icon or "Run a Service"
3. Click "Multi/container (Pod)"
4. Toggle the JSON editor open
5. Replace the first object in the `containers` array with:
```
{
"resources": {
"cpus": 0.1,
"mem": 128
},
"lifecycle": {
"killGracePeriodSeconds": 600
},
"image": {
"id": "nginx",
"kind": "DOCKER"
}
}
```
6. Focus any field in the form
7. Add a Service ID
8. Tap "Review & Run"
9. Tap "Review & Run" on the confirmation screen
10. When you land back on the services screen, click the service you just added
11. Click the "Edit" button
12. Toggle the JSON editor open
The JSON editor should still contain `"lifecycle": { …

DCOS_OSS-1961: don't swallow container fields added in JSON editor

---

plugins/services/src/js/components/forms/GeneralServiceFormSection.js
src/styles/components/advanced-section/styles.less

We're going to change default containerizer from Docker to UCR soon, to prepare our customers, we're recommending UCR
Closes DCOS-41914
1. Go to "Services"
2. Add a new service by clicking "+" icon or "Run a Service"
3. Click "Single container"
4. Click the "More Settings" dropdown
5. Scroll to the "Container Runtime" section
The radio label for "Universal Container Runtime (UCR)" should have a badge 
Very minor: had to add some markup to vertically center the Badge
None
Before:
After:

DCOS-41914: add a 'recommended' label to UCR containerization option

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/Containers.js
plugins/services/src/js/reducers/serviceForm/JSONReducers/__tests__/Containers-test.js

1. Go to "Services"
2. Add a new service by clicking "+" icon or "Run a Service"
3. Click "Multi/container (Pod)"
4. Toggle the JSON editor open
5. Replace the first object in the `containers` array with:
```
{
"resources": {
"cpus": 0.1,
"mem": 128
},
"lifecycle": {
"killGracePeriodSeconds": 600
},
"image": {
"id": "nginx",
"kind": "DOCKER"
}
}
```
6. Focus any field in the form
7. Add a Service ID
The JSON editor should still contain `"lifecycle": { "killGracePeriodSeconds": 600 }` after you focus on the service ID input
None
None
Before:
https://cl.ly/3c8722d63b9a
After:
https://cl.ly/99add280d670

DCOS-42326: don't swallow container fields added in JSON editor

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
plugins/services/src/js/utils/PodUtil.js
plugins/services/src/js/utils/__tests__/PodUtil-test.js

Clarify to users what the breakdown of the resources is on the pod instances table.
Added tooltips to the resource cells in the PodInstancesTable. If it is an expandable row (has child containers), it gives a breakdown of the resource summary as "Containers: X, Executor: Y". If is a non-expandable row (child container), it indicates how much of the allocated resource is being used as "Using X/Y".
Closes DCOS-42230.
- Run a service from JSON config which can be found in [JIRA ticket comment](https://jira.mesosphere.com/browse/DCOS-17436?focusedCommentId=174971&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-174971). 
- Go to services, click on the service you just started, hover over the resource cells on the parent (expandable) row. They should give breakdown …

DCOS-42230: Clarify resource totals on pod instances table

---

plugins/services/src/js/components/MesosLogContainer.js
plugins/services/src/js/stores/MesosLogStore.js
tests/_fixtures/1-service-with-executor-task/files-read.json
tests/_support/index.js
tests/pages/services/TasksTable-cy.js

Look at a task and go to Log. Now open the network tab and search for "files/read". Block that URL. Reload. See an error message instead of infinite loading.
- Decided to use the very same error page for both errors as the origin of this issue is unclear in both occasions.
- Decided to directly show the error, might lead to blinking if it's first not there and then there, but this is really an upstream bug (if it even exists) and I am willing to do this tradeoff
None
Not so interesting here 🤷‍♂️

DCOS-42349: Show error page when the log file won't load

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/utils/PodUtil.js
plugins/services/src/js/utils/__tests__/PodUtil-test.js

Backport changes that clarify to users what the breakdown of the resources is on the pod instances table.
Closes DCOS-42365.
- Run a service from JSON config.
```
{
"id": "/podtest",
"version": "2018-09-06T16:24:51.764Z",
{
"resources": {
"cpus": 0.1,
"mem": 64,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 100;"
}
}
},
{
"name": "container-2",
"resources": {
"cpus": 0.1,
"mem": 64,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 10000;"
}
}
}
],
"networks": [
{
"mode": "host"
}
],
"scaling": {
},
"placement": {
}
},
"cpus": 0.1,
"mem": 32,
"disk": 10
}, …
```

[1.11] Clarify resource totals on pod instances table

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
src/styles/components/form-elements/styles.less
tests/pages/services/ServiceFormModal-cy.js

backport for https://github.com/dcos/dcos-ui/pull/3234 with some minor fixes
Half of https://jira.mesosphere.com/browse/DCOS-42035
1. Switch to branch 1.11 and set up node to use version 8.9.4 and npm to use version 5.6.0
Setting up node is easy: just use a node version manager (I used https://github.com/creationix/nvm) and run (if you are using nvm) `nvm install 8.9.4` in the directory. Setting up npm should happen automatically in this case, but if it doesn't, it is a bit trickier - navigate to the nvm directory, for example `cd ~/.nvm/versions/node/v8.9.4/lib` and run `npm install npm@5.6.0`.
2. Test the changes
Click on Single …

DCOS-42035: Invalid Environment variables have no error and are simply ignored (1.11 backport)

---

src/js/structs/UniversePackagesList.js
src/js/structs/__tests__/HealthUnitsList-test.js
src/js/structs/__tests__/List-test.js
src/js/structs/__tests__/UniversePackagesList-test.js
src/js/utils/StringUtil.js
src/js/utils/__tests__/StringUtil-test.js
src/js/utils/__tests__/search-test.js
src/js/utils/search.ts

https://jira.mesosphere.com/browse/DCOS-21232
StringUtil#filterByString now sorts matches by relevance score. This change affects node health checks and universe packages. Here's how scoring is calculated:
- Search phrase are tokenized and each term is evaluated individually, with multiple scores summed together. So if you type "foo bar baz" a package named "foo baz" would appear before "foo" or "bar"
- Exact term matches are scored very very high
- Otherwise, longer terms appearing closer to the beginning of the string are scored higher than shorter terms closer to the end
- Additionally, universe packages are re-ranked to show certified packages first.
The "string" being searched is the concatenated values of "filterProperties"... For universe packages, that would be the name, …

DCOS-21232: Better text filtering

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
tests/pages/services/ServiceFormModal-cy.js

Update error message when a environment variable has a value but no key
Closes https://jira.mesosphere.com/browse/DCOS-42394
Relevant discussion: https://github.com/dcos/dcos-ui/pull/3298#issuecomment-422834336
Click on Single Container
Click on Environment
Click on `Add Environment Variable`
Enter a `Value` without entering `Key`
Verify that there is an error message and it says "The key cannot be empty."
Test the same thing for a Multi-Container
None
None

DCOS-42394: Fix error message for environment variables

---

plugins/services/src/js/components/forms/EnvironmentFormSection.js
tests/pages/services/ServiceFormModal-cy.js

Update error message when a environment label has a value but no key
Closes https://jira.mesosphere.com/browse/DCOS-42395
Relevant discussion: https://github.com/dcos/dcos-ui/pull/3298#issuecomment-422834336
Click on Single Container
Click on Environment
Click on `Add Label`
Enter a `Value` without entering `Key`
Verify that there is an error message and it says "The key cannot be empty."
Test the same thing for a Multi-Container
None
None

DCOS-42395: Fix error message for labels

---

plugins/services/src/js/utils/FrameworkUtil.js
plugins/services/src/js/utils/__tests__/FrameworkUtil-test.js

The PR adds a type check for the fields skipping all non-string fields.
Relevant slack discussion linked in the ticket: https://jira.mesosphere.com/browse/DCOS-42317
Closes DCOS-42317
1. Try installing `grafana` from the Catalog without the patch.
2. See UI went broken
3. With the patch you should be able using the UI normally
We do extraction in prod even though we don't need it there.

DCOS-42317: skip non-string fields in Universe response

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/utils/PodUtil.js
plugins/services/src/js/utils/__tests__/PodUtil-test.js

Backport changes that clarify to users what the breakdown of the resources is on the pod instances table.
Closes DCOS-42366.
- Run a service from JSON config.
```
{
"id": "/podtest",
"version": "2018-09-06T16:24:51.764Z",
{
"resources": {
"cpus": 0.1,
"mem": 64,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 100;"
}
}
},
{
"name": "container-2",
"resources": {
"cpus": 0.1,
"mem": 64,
"disk": 0
},
"image": {
"id": "alpine"
},
"exec": {
"command": {
"shell": "sleep 10000;"
}
}
}
],
"networks": [
{
"mode": "host"
}
],
"scaling": {
},
"placement": {
}
},
"cpus": 0.1,
"mem": 32,
"disk": 10
}, …
```

[1.10]: Clarify resource totals on pod instances table

---

plugins/services/src/js/components/MesosLogContainer.js
plugins/services/src/js/stores/MesosLogStore.js
tests/_fixtures/1-service-with-executor-task/files-read.json
tests/_support/index.js
tests/pages/services/TasksTable-cy.js

Look at a task and go to Log. Now open the network tab and search for "files/read". Block that URL. Reload. See an error message instead of infinite loading.
- Decided to use the very same error page for both errors as the origin of this issue is unclear in both occasions.
- Decided to directly show the error, might lead to blinking if it's first not there and then there, but this is really an upstream bug (if it even exists) and I am willing to do this tradeoff
None
Not so interesting here 🤷‍♂️

DCOS-42347: Show error page when the log file won't load

---

plugins/services/src/js/components/MesosLogContainer.js
plugins/services/src/js/stores/MesosLogStore.js
tests/_fixtures/1-service-with-executor-task/files-read.json
tests/_support/index.js
tests/pages/services/TasksTable-cy.js

Look at a task and go to Log. Now open the network tab and search for "files/read". Block that URL. Reload. See an error message instead of infinite loading.
- Decided to use the very same error page for both errors as the origin of this issue is unclear in both occasions.
- Decided to directly show the error, might lead to blinking if it's first not there and then there, but this is really an upstream bug (if it even exists) and I am willing to do this tradeoff
None
Not so interesting here 🤷‍♂️

DCOS-42348: Show error page when the log file won't load

---

src/js/components/modals/CliInstallModal.js

Both #3325 and #3312 confuse Jenkins. Let's try 3rd time 💪 
This reverts commit 3a1f67d23ede05c0a06e2032b415b3e507177891.
Closes DCOS_OSS-4208
Installing cli should work

DCOS_OSS-4208: REVERT: update DC/OS CLI installation link to latest

---

scripts/pre-commit

Update pre-commit script to lint typescript files
Closes https://jira.mesosphere.com/browse/DCOS-38653
Open a test branch
Open a `.ts` file, a `.tsx` file and a `.d.ts` file from the project
Make some linting errors like adding a whitespace at the end of a line
Try to commit
Verify that you can't and the linter is working
1. The script test for `.ts*` files to test both `.ts` and `.tsx` which means that if we have `.tsj` file or something like that it will also test them.
2. This will test the `d.ts` files which are otherwise not test when we run `npm run lint`, I think we should decide if we want to lint them everywhere or nowhere (I would vote for everywhere).
None.

DCOS-38653: fix ts file linting in githooks

---

.linguirc

I initially neglected the plugins/ folder and added some new exclusions to slightly speed up the process of extraction. @natmegs

chore(lingui): Reconfig to include/exclude more paths

---

Jenkinsfile
system-tests/_scripts/sandbox-setup.sh
system-tests/_scripts/setup.sh

With this PR we will be re-using cached Cypress installation that should reduce the build time.
Closes DCOS-40640
CI should pass. 
Go inside the build and make sure we're not installing cypress for every set of tests.
This is what should not be present in the logs

 DCOS-40640: reuse Cypress cache

---

plugins/services/src/js/pages/EditFrameworkConfiguration.js
tests/pages/services/EditFrameworkConfiguration-cy.js

Properly handle Cosmos errors.
Closes: DCOS_OSS-4222
1. Install something from the Catalog i.e. Kafka
2. Try editing the service
3. It should open the Editing form
4. Block `/cosmos/service/describe` URL in Chrome inspector
5. Refresh the Form
6. It now should show an error
Without the fix error would not appear. UI would keep showing loading bubble.
I added some markup to fix the styling of the message. Otherwise it would be black on black and left-aligned.

DCOS_OSS-4222: Show cosmos errors

---

locale/en/messages.json
src/js/pages/DashboardPage.js
src/js/pages/NetworkPage.js
src/js/pages/NotFoundPage.js
src/js/pages/catalog/PackageDetailTab.js
src/js/pages/catalog/PackagesTab.js
src/js/pages/catalog/__tests__/__snapshots__/PackageDetailTab-test.js.snap
src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap
src/js/pages/network/VirtualNetworksTab.js
src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js
src/js/pages/network/virtual-network-detail/VirtualNetworkDetailsTab.js
src/js/pages/network/virtual-network-detail/VirtualNetworkTaskPage.js
src/js/pages/system/ComponentsUnitsHealthNodeDetailPage.js
src/js/pages/system/OrganizationTab.js
src/js/pages/system/OverviewDetailTab.js
src/js/pages/system/UnitsHealthDetail.js
src/js/pages/system/UnitsHealthTab.js
src/js/pages/system/UsersPage.js
src/js/pages/system/units-health-node-detail/NodeInfoPanel.js
tests/pages/catalog/packages/PackagesTab-cy.js

These changes should result in no visible changes to the UI. There may be some additional `<span>` tags rendered from using the `<Trans>` macro. But we would also be able to remove that once we upgrade to React 16 as string's will become valid return results from a component.
There was at least one place where the current code could be simpler and allow easier translation (see comment), but I left the current code in place to not increase the scope of these changes.

DCOS-43055: Wrap text resources in app (src/js/pages)

---

locale/en/messages.json
src/js/components/FrameworkConfiguration.js
src/js/constants/RepositoriesTableHeaderLabels.js
src/js/utils/ResourceTableUtil.js

Add POC for wrapping const text resources outside of React components. Covers 2 cases:
- Constants marked for translation but not immediately translated. These are used in conjunction with `<Trans>` component.
- Strings that need to be pre-translated (not just marked for translation)
Closes DCOS-43050.
- Run `npx lingui extract` and ensure that both text wrapped in `i18nMark()` from `RepositoriesTableHeaderLabels.js` and text wrapped in `i18n._(t``)` from `FrameworkConfiguration.js` has been added to `locale/en/messages.json`
- Run app 
- Ensure table in Settings > Package Repositories displays as expected
- Go to Catalog > cassandra > Review & Run > Cancel > ensure that `Cancel` and `Discard` button text on confirmation popup is visible as expected
Constants must be marked for …

DCOS-43050: add POC for wrapping const text resources

---

scripts/pre-install

Housekeeping PR.
We bundle Marathon raml files so that we can validate app definition JSONs in the Form. Judging from https://github.com/mesosphere/marathon/compare/f24b03af3..da9365d80 I can't spot anything that could be considered a blocker for 1.12.
Just smoke test Single container Form and Multi Container Form that validation still works.

Bump Marathon version

---

npm-shrinkwrap.json
package.json

Closes DCOS-43041
1. Run `npm i`
2. Since the main change in 0.21.0 is the way we integrate Portals I'd suggest checking modals if they still work.

 DCOS-43041: bump reactjs-components@0.21.0

---

src/js/pages/catalog/DeployFrameworkConfiguration.js

Remove black screen transition when loading form after clicking Review & Run from catalog. Used same loader from Catalog and other pages.
Closes DCOS-41626.
Go to Catalog > Any package > click Review & Run. There should be no partial black screen when loading form.
None I'm aware of.
Before:
After:
Catalog loader (for comparison):

DCOS-41626: Remove black screen transition

---

.dcosrc
.releaserc
scripts/ci/upload-release

This removes .dcosrc file in order to consolidate all version strings in .releaserc file
🤷‍♂️ 
its just a first step to forward port the changes we did to fix 1.12 branch, later we'll go ahead and change .releaserc file from JSON to javascript.
see this for reference: https://github.com/dcos/dcos-ui/pull/3349

DCOS-43340: remove .dcosrc file

---

webpack/webpack.dev.js
webpack/webpack.production.js

Why are we bundling and loading all the package dependencies separately? It seems to me that we only need to load what we import through index.js. Our app size may be 2.5MB too large?
Before (Production build)
Before (Bundle Analysis)
After

Discussion: Is this vendor.js bundle useful?

---

plugins/jobs/src/js/components/JobsOverviewTable.js
plugins/jobs/src/js/constants/JobStates.ts
plugins/jobs/src/js/constants/JobStatus.ts
plugins/jobs/src/js/constants/JobTableHeaderLabels.js
plugins/jobs/src/js/pages/JobRunHistoryTable.js
src/js/structs/Job.d.ts
src/js/structs/Job.js
src/js/structs/__tests__/Job-test.js

There should be no visual differences or markup changes after this PR is merged.
Once the dust settles we need to run `npm run lingui-extract-with-plugins` and commit the message catalog.
I was able to remove some unused job methods that depended on some unused job status constants

DCOS-43373: Mark and translate jobs plugin constants

---

src/styles/components/header-bar/styles.less
src/styles/components/header-bar/variables.less
src/styles/layout/sidebar/styles.less

This PR addresses the following visual issues:
1. Replaces the logo graphic with the 2x logo so it isn't blurry on retina screens.
2. Moves the logo down 2px so it is better aligned with the text in the header.
3. Adds some padding to the sidebar for better alignment as per DCOS-40327
Before
After

Fix logo quality and alignment

---

.releaserc

its `release/1.11` in our repo and `1.11` in dcos/dcos repo… got confused 🤦‍♂️

fix(ci): fix release branch name

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js
src/js/components/ErrorsAlert.js
src/js/utils/ErrorMessageUtil.js
src/js/utils/__tests__/ErrorMessageUtil-test.js

Updated `ErrorMessageUtil` functions to take the `i18n` instance object as an optional
parameter. If given,`i18n` will be used to translate the error message
before replacing variables and returning result. 
The two components that use `ErrorMessageUtil` are also updated to pass `i18n` as a parameter by wrapping them in the `withI18n` higher-order component.
I also added unit tests for `getUnanchoredErrorMessage` since I was updating it and there were not any tests for this function currently.
*Note* This PR is base on #3359 and should not be merged until it has been merged first.
There should be no visible changes to the UI from this change until the error messages have been translated and the local switch is implemented. There are new unit tests for the additions to `ErrorMessageUtil`
I …

DCOS-43637 Translate messages in ErrorMessageUtil

---

src/js/pages/network/virtual-network-detail/VirtualNetworkDetail.js

Removed one of the imports.
Closes DCOS-44138
The localhost site should work after `npm start`.
None.
None.

DCOS-44138: i18n Mark is imported twice in VirtualNetworkDetail

---

plugins/services/src/js/components/modals/ServiceRestartModal.js

Noticed this while smoke testing. Hard to see that we needed a literal space between two container expressions.

fix(ServiceRestartModal): Missing space

---

renovate.json

We want to introduce renovate, so that we can spare one manual task,
the bump and creation of a PR for each new package version.
Please see https://github.com/DanielMSchmidt/test-renovate-for-one-dependency for a test of the one rule application of renovate
- Only update packages we own, so that we remove some friction
- Label updates so that we can quicker spot them and understand the impact of our merge better.

Enable renovate for organisation packages

---

locale/en/messages.json
plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap

Rename Version to Mesos Version in master tab.
Closes DCOS-44017.
- Go to Nodes > Master tab
- You should see "Mesos Version" in the Leader grid
None

DCOS-44017: rename Version to Mesos Version

---

locale/en/messages.json
plugins/services/src/js/components/ServiceStatusProgressBar.js

Ensure status bar tooltip shows correct pluralized message from translation catalog instead of bare id.
Closes DCOS-46676.
- Create production build with `npm run build-assets`
- Serve with `npx http-server -p 4200 --proxy-secure=false -P https://frontend-ElasticL-15A1BH9DJMPZ6-380004668.us-west-2.elb.amazonaws.com ./dist` (use up to date cluster url)
- Go to Catalog - run Cassandra
- Go (quickly) to services page and hover over the status bar in the services table while it's deploying
- Should see tooltip with a regular looking sentence instead of translation message syntax
Had to import `Trans` despite not using it in `ServiceStatusProgressBar` because otherwise the `Plural` message is not extracted. See lingui [issue](https://github.com/lingui/js-lingui/issues/382)
See before …

DCOS-44676: fix status bar tooltip

---

plugins/services/src/js/service-configuration/ServiceEnvironmentVariablesConfigSection.js
plugins/services/src/js/service-configuration/ServiceLabelsConfigSection.js
src/styles/components/configuration-map/styles.less

Removed min-width table-cell truncation hack because most browsers will obey the min-width: 0 style, causing the layout to break.
Tested in Firefox, Edge, Safari, and Chrome. Also tested to ensure text truncation still works.
**Test in Firefox or Edge**
0. Check out `mp/fix/DCOS-43897-ff-table-cell` from dcos-ui-plugins-private
1. Create a new service
2. Go to the "Environment" tab
3. Click "+ Add Environment Variable" and enter a key and a value
4. Click "+ Add " and enter a key and a value
5. Click "+ Add " and enter a key and a value
6. Go to "Networking" tab
7. Click "+ Add Service Endpoint"
8. Go to "Health Checks" tab
9. Click "+ Add Health Check" and add enter dummy info
10. Click "Review & Run"
No columns in the table should be collapsed
This solution is a little bit of a table …

1.12 backport: don't allow table cell containing label to collapse

---

plugins/services/src/js/containers/pod-debug/PodDebugContainer.js

Looks like we've overlooked one rouge `}`
run `npm run lingui-extract-with-plugins && npm start` 
without this fix it won't start
I haven't included recompiled `messages.json` not quite sure what is our process here @natmegs @brandonc

fix: remove extra curly brace

---

locale/zh/messages.json
src/js/index.js

- Before starting, run `npx lingui compile`
- Switch to chinese locale in profile menu or UI settings
Including in the webpack build is probably not a good idea because each catalog is quite large (100 KB minified). Asynchronous loading can be added separately.

feat(locale): Adds initial chinese catalog

---

src/js/components/modals/CliInstallModal.js

It currently points to a deprecated URL format we don't publish to
(starting from 1.13).
Eventually it will be replaced by a "latest" URL, but for now as DC/OS
1.13 is still in development we'll use the testing/master URL (the
latest commit).
https://jira.mesosphere.com/browse/DCOS_OSS-4509

DCOS_OSS-4509: 1.13 CLI URL in the UI is broken

---

plugins/nodes/src/js/pages/nodes/NodeDetailTab.js

Added GPU information to the node detail tab table.
Closes DCOS-45393
Go to Nodes tab.
Click a node.
Open the Details tab.
Verify that the GPU row is there.
Unless I am missing something, I think this should be a 1-story point ticket.
None.

DCOS-45393: Add GPU to Nodes Detail Page

---

plugins/services/src/js/components/DeclinedOffersTable.js

[COPS ticket](https://jira.mesosphere.com/browse/COPS-4160) reported that the Host IP addresses were being truncated, but the Constraint header as well as the Received content was also being truncated. Fix Host, Constraint, and Received columns which were being truncated with content cut off. Added a tooltip to the Host column.
Closes DCOS-45494.
- Use a 1.12 soak cluster and go to Services 
- Choose a pod that's deploying 
- Debug tab 
- Look at table under Recent Resource Offers > Details and check that above mentioned columns are not truncated
None that I'm aware of
None
Before
After

[1.12] DCOS-45494: fix truncated columns on DeclinedOffersTable

---

plugins/services/src/js/reducers/JSONMultiContainerParser.js
plugins/services/src/js/reducers/JSONMultiContainerReducers.js
plugins/services/src/js/reducers/__tests__/JSONMultiContainer-test.js

Closes DCOS-43620
1. Create a pod.
2. Add/modify it's `scheduling` field
```js
scheduling: {
placement: {
constraints: [{ fieldName: "hostname", operator: "UNIQUE" }]
},
backoff: {
backoff: 1,
backoffFactor: 1.15,
maxLaunchDelay: 30
},
upgrade: {
minimumHealthCapacity: 1,
maximumOverCapacity: 1
},
killSelection: "YOUNGEST_FIRST",
unreachableStrategy: {
inactiveAfterSeconds: 0,
expungeAfterSeconds: 0
}
}
```
3. Verify that the form doesn't truncate the scheduling definition.
in line parser/reducer otherwise I'd write it in TS. Please tell me if I should.

DCOS-43620: Fully support scheduling in pods

---

plugins/jobs/src/js/components/JobsOverviewTable.js
plugins/jobs/src/js/pages/JobRunHistoryTable.js
plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/services/src/js/components/MarathonTaskDetailsList.js
plugins/services/src/js/components/TaskDirectoryTable.js
plugins/services/src/js/containers/pod-configuration/PodConfigurationContainer.js
plugins/services/src/js/containers/pod-instances/PodInstancesTable.js
plugins/services/src/js/containers/pod-instances/__tests__/PodInstancesTable-test.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/containers/service-configuration/__tests__/ServiceConfigurationContainer-test.js
plugins/services/src/js/containers/service-debug/ServiceDebugContainer.js
plugins/services/src/js/containers/service-debug/TaskStatsTable.js
plugins/services/src/js/containers/tasks/TaskTable.js
src/js/stores/SystemLogStore.js
src/js/structs/__tests__/JobRunList-test.js
src/js/structs/__tests__/JobTaskList-test.js
src/js/utils/DateUtil.d.ts
src/js/utils/DateUtil.ts
src/js/utils/JestUtil.js
src/js/utils/__tests__/DateUtil-test.js

Localize dates using DateFormat macro. Does not include relative dates.
Closes DCOS-41719.
There should be no visual changes as a result of this PR.
Lingui `DateFormat` macro uses `Intl.DateTimeFormat` instead of `Date` functions like `toLocaleString` (not so much a tradeoff as just something to be aware of).
None
N/A

DCOS-41719: localize dates

---

plugins/services/src/js/containers/framework-configuration/FrameworkConfigurationContainer.js
tests/pages/services/ServiceDetail-cy.js

This PR adds cosmos error handling for the configuration tab
Please refer to the ticket. Some private info involved.

DCOS-45800: Handle Cosmos Errors in configuration tab

---

src/js/events/MetronomeClient.ts
src/js/events/__tests__/MetronomeClient-test.ts

As this behaviour breaks proxying requests. More background in the issue.
1. Verify that `fetchJobs` and `fetchJobDetail` stopped sending Content-Type on respective pages.
Fixed a typo in a sep commit 🤷‍♂️

DCOS-46053: Metronome client to stop sending Content-Type header with GET requests

---

src/styles/components/code/styles.less
src/styles/components/code/variables.less

Allow the logs to be scrollable in Firefox.
Closes DCOS-43091
1. Test in both Firefox and Chrome
2. Start a service
3. Go to Services Tab, click the service.
4. Click a task
5. Open the logs tab
6. Verify that Error(stderr) and Output(stdout) are scrollable
7. Go to Nodes
8. Click a node
9. Click a task
10. Open the logs tab
11. Verify that Error(stderr) and Output(stdout) are scrollable
Firefox need an explicit height (so not `100%` or `auto`) for `overflow: auto` or `overflow: scroll` to work.
None.

DCOS-43091: [COPS] Logs view / Nodes view don't scroll in Firefox

---

plugins/services/src/js/components/DeploymentsModal.js
tests/_fixtures/deployments/two-deployments-one-stale.json
tests/pages/services/DeploymentsModal-cy.js

Ensure status is retrieved from deployments, even when getStatus method is not available.
Closes DCOS-46088.
Not sure if this will hold up as deployments change over time, but for me I tested using the 1.12 soak cluster.
- Go to Services
- Click on "X Deployments" in top right corner
- List of deployments in modal should match X
Compare this to same set of steps on soak cluster (not using this branch, just soak url). For me, it was 3 deployments but only 2 would show up in the modal (+ errors in dev console).
Code trade-offs, none that I can see. But it is weird that the format of the deployment items is not consistent. This issue came up because most of the items had all the regular "Service" properties, but there was one that only had 
```js
{
deployment: {...},
isStale: true, …
```

[1.12] DCOS-46088: get status for all deployments

---

plugins/nodes/src/js/pages/NodesAgents.js

Changed the message when there are no nodes to be more accurate.
Closes https://jira.mesosphere.com/browse/DCOS-46049
1. In `plugins/nodes/src/js/pages/NodesAgents.js` change line 306 to be `if (true) {`
2. Click on Nodes tab.
3. Verify that the message shown is changed.
Also changed "a" to "are".
None.

DCOS-46049: [1.12] COPS-3759 affecting dcos-ui: When no nodes are in the cluster the message should have different wording

---

plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
src/js/components/FrameworkConfigurationReviewScreen.js
src/styles/views/services/styles.less

1. In `plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js`, on line 143, change the `<DateFormat />` component to just be a span with a long string
2. Open a service from the "Services" tab
3. Go to the "Configuration" tab
4. Click the dropdown at the top of that screen
The long string you replaced `<DateFormat />` with should not overflow the container - it should appear truncated
None
None
Before:
After:
Note: I tested this in Chrome, FF, Safari, and Edge

DCOS_OSS-4597: [1.12] service config dropdown content overflows

---

src/js/components/FrameworkConfigurationForm.js

Use a browser other than Chrome.. With your browser and OS in locale that uses "," as a decimal separator  (de-DE, ru, fr-FR, etc...).
1. Go to Catalog and add a new service
2. Go to the "Nodes" tab
3. Change CPUs to another floating point
The field should not be considered invalid
- Setting `novalidate` on this form makes us miss out on browser validation (e.g.: people can put letters into an `input[type="number"]`)
- We're setting `novalidate` on this form, but there may be other forms where we have this issue that we just haven't caught yet
None
Before:
After:

DCOS_OSS-4579: [1.12] accept floating points in FrameworkConfigurationForm

---

src/js/components/FrameworkConfigurationForm.js
src/js/components/SchemaField.js

Use a browser other than Chrome.. With your browser and OS in locale that uses "," as a decimal separator  (de-DE, ru, fr-FR, etc...).
1. Go to Catalog and add a new service
2. Go to the "Nodes" tab
3. Change CPUs to another floating point
The field should not be considered invalid
- Setting `novalidate` on this form makes us miss out on browser validation (e.g.: people can put letters into an `input[type="number"]`)
- We're setting `novalidate` on this form, but there may be other forms where we have this issue that we just haven't caught yet
None
Before:
After:

DCOS_OSS-4582: [1.11]  accept floating points in FrameworkConfigurationForm

---

npm-shrinkwrap.json
package.json

- update @dcos/mesos-client to 0.2.6
- update @dcos/http-service to 1.1.0
Closes [DCOS-46294](https://jira.mesosphere.com/browse/DCOS-46294), See [COPS-4205](https://jira.mesosphere.com/browse/COPS-4205)
- `npm i`
- make sure that /mesos/api/v1 endpoints have timestamp part `_ts=<number>`

DCOS-46294 - COPS-4205: No tasks show for a service 

---

plugins/services/src/js/data/ServicePlansClient.ts
plugins/services/src/js/data/__tests__/ServicePlansClient-test.ts
plugins/services/src/js/data/__tests__/_fixtures/service-plan-in-progress.json

Created the client for querying a service's plans from the API and
associated types. This will be used by a data-layer GraphQL connection that will be written after this. That is why I placed it in the data folder for the services plugin.
There are unit tests to run.
Otherwise this client will be used by a data-layer connection that will be written in another ticket.
I wasn't 100% sure where these files should live. I actually moved them 3 times while developing this. If you think there is a better place for this to live I am open to suggestions.

DCOS-43909 SDK Plans Client

---

scripts/utils/test

You can add a bash file like this on the top-level and call it:
```bash
#!/bin/bash
set -e
source "./scripts/utils/test"
echo "$(find_files_with_debug_directives './tests')"
```
It should exit with status code 1 if there is no file in ./tests to contain `.only`. If you change that it should display each file name in a new line
- Wrote it in bash as we wanted to reuse the code that is already there, so that we can rewrite it later together, rather then having two versions, one for bash and one for JS

DCOS-44818: add script that detects .only statements

---

plugins/services/src/js/data/ServicePlansClient.ts
plugins/services/src/js/data/__tests__/ServicePlansClient-test.ts
plugins/services/src/js/data/__tests__/index-test.ts
plugins/services/src/js/data/index.ts
plugins/services/src/js/types/Service.ts
plugins/services/src/js/types/ServicePlan.ts
plugins/services/src/js/types/ServicePlanPhase.ts
plugins/services/src/js/types/ServicePlanStatus.ts
plugins/services/src/js/types/ServicePlanStep.ts

Introducing data-layer for the services plugin. We are adding this to
support querying for a SDK service's plans. These will be displayed in
the UI. To support querying other service information through the
data-layer the root query object is the `Service` even though currently
this only supports a name and the plans.
For now just run the unit tests, but component coming soon!
A graphql query that includes `plans` will result in `n+1` requests to the API. A service should have a limited number of plans and 🤞 never more then 100, but this is something we should be aware of when building service queries. We should be mindful of the performance implications of the `graphqlobservalble` polling with `n+1 `queries as well.

DCOS-43910 SDK Service Plan data-layer

---

src/js/components/modals/CliInstallModal.js

This reverts commit 810b475.
Creating this on the behalf of @ArmandGrillet , because his fork https://github.com/dcos/dcos-ui/pull/3535 can't get merged right now.
On 1.13 cluster, open the dropdown in the top right corner, click "Install CLI", click "OSX" or "Linux" if they aren't selected and verify that the link in the second row contains "1.13".
None.
None.

Revert "fix: update CLI URL in the installation instruction"

---

package.json
scripts/validate-tests

- Check this branch out
- Configure an external plugin
- Add a `it.only` in a test case
- run `npm build` from this repo and see it fail
- Use already existing tools now also for external plugins

DCOS-45214: enable validate test script to run on external plugins

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/constants/VolumeStatus.js
plugins/services/src/js/utils/__tests__/MarathonUtil-test.js

For services with external volumes, change the unavailable status
to be N/A to make it more descriptive and less misleading.
Closes https://jira.mesosphere.com/browse/DCOS-47514
1. Open postgresql from the catalog
2. In the edit configuration screen, select the Storage tab and enable persistent storage and persistent storage properties using the two checkboxes
3. Click Review and Run
4. Open the service, open the Volumes tab and verify that the status is shown as "N/A"
None.
None.

DCOS-47514: [1.13] COPS-4345 affecting dcos-ui: Change "Unavailable" status text for External Volumes

---

scripts/utils/integration-tests
tests/pages/services/DeploymentsModal-cy.js
tests/pages/services/ServiceActions-cy.js
tests/pages/services/ServiceFormModal-cy.js

As commit messages suggest:
1. Mute terrible flakes
2. Record video only on 3rd re-run
3. Helper function that is not being used atm
4. Helper flags to run tests in the Headed mode
5. Fixed some `skipped` tests to reserve skip for flakes

Fix integration tests

---

package-lock.json
package.json
plugins/nodes/src/js/columns/NodesTableCPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableDiskColumn.tsx
plugins/nodes/src/js/columns/NodesTableGPUColumn.tsx
plugins/nodes/src/js/columns/NodesTableHealthColumn.tsx
plugins/nodes/src/js/columns/NodesTableIpColumn.tsx
plugins/nodes/src/js/columns/NodesTableMemColumn.tsx
plugins/nodes/src/js/columns/NodesTableRegionColumn.tsx
plugins/nodes/src/js/columns/NodesTableSpacingColumn.tsx
plugins/nodes/src/js/columns/NodesTableTasksColumn.tsx
plugins/nodes/src/js/columns/NodesTableTypeColumn.tsx
plugins/nodes/src/js/columns/NodesTableZoneColumn.tsx
plugins/nodes/src/js/columns/__tests__/__snapshots__/NodesTableHealthColumn-test.js.snap
plugins/nodes/src/js/components/NodesTable.tsx
src/js/pages/catalog/__tests__/__snapshots__/PackagesTab-test.js.snap

Use the new version of the ui-kit to enable the nodes table
to auto resize columns based on their content width.
Closes https://jira.mesosphere.com/browse/DCOS-47175
~Currently blocked by https://github.com/dcos-labs/ui-kit/pull/276~
1. Go to Nodes tab
2. Verify that the table doesn't jump as the data is loaded
3. Verify that the table works and the columns are as wide as the content
~I don't think that the new table looks better. I considered adding some minimal width to the columns, but then we would have the old table in almost every case (as the health column for example will never be wider than the old value of 120px). @lsamimi , @mperrotti , what do you think?~
I added a loader if the data array is empty, but some of the values in the table are slower to load, which causes it to …

DCOS-47175: Update Table component in nodes page

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
tests/_fixtures/mesos/overlay-master.json
tests/pages/networking/Networks-cy.js
tests/pages/services/ServiceFormModal-cy.js

Make the virtual network dcos6 unavailable
when UCR is chosen as a container.
Closes DCOS_OSS-4632
1. Go to Services tab
2. Create a new Single Container service
3. On the Service tab, click "More Settings" at the bottom and select "Universal Container Runtime (UCR)" for Container Runtime.
4. Go to Networking type, open the Network Type dropdown and verify that "dcos6" is not shown.
None.
None.

[COPS] DCOS_OSS-4632: [1.12] dcos6 network is shown as available for UCR in the UI.

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js
plugins/services/src/js/components/forms/NetworkingFormSection.js
tests/_fixtures/mesos/overlay-master.json
tests/pages/networking/Networks-cy.js
tests/pages/services/ServiceFormModal-cy.js

Make the virtual network dcos6 unavailable
when UCR is chosen as a container.
Closes https://jira.mesosphere.com/browse/DCOS_OSS-4631
1. Go to Services tab
2. Create a new Single Container service
3. On the Service tab, click "More Settings" at the bottom and select "Universal Container Runtime (UCR)" for Container Runtime.
4. Go to Networking type, open the Network Type dropdown and verify that "dcos6" is not shown.
None.
None.
See https://github.com/dcos/dcos-ui/pull/3555 .

[COPS] DCOS_OSS-4631: [1.11] dcos6 network is shown as available for UCR in the UI.

---

src/js/structs/Node.js

Add a check to prevent trying to read a property from something that
is not defined.
Closes https://jira.mesosphere.com/browse/DCOS-46611
Not sure how to test this.
None.
None.
None.

[spike] DCOS-46611: [1.12] Cannot read property 'stateTypes' of undefined

---

src/js/pages/catalog/PackageDetailTab.js

It currently points to `dcos service`, it'd be more useful to show the
`dcos package install` command instead.
Closes https://jira.mesosphere.com/browse/DCOS-47685
For testing, screenshots, etc. see https://github.com/dcos/dcos-ui/pull/3550

DCOS-47685: [1.11] DC/OS Enterprise CLI description is wrong

---

system-tests/driver-config/dev.sh

Few adjustments to enable system-tests on dev env.
1. `$ docker-compose toolchain run bash`
1. create cypress cache dir `mkdir /root/.cache/Cypress`
1. install cypress binary `/dcos-ui/node_modules/cypress/bin/cypress install`
2. remove node from node_modules `rm -rf /dcos-ui/node_modules/node`

chore(system-tests): fix dev.sh config

---

src/js/pages/catalog/PackageDetailTab.js

It currently points to `dcos service`, it'd be more useful to show the
`dcos package install` command instead.
Closes https://jira.mesosphere.com/browse/DCOS-47684
For testing, screenshots, etc. see https://github.com/dcos/dcos-ui/pull/3550

DCOS-47684: [1.12] DC/OS Enterprise CLI description is wrong

---

plugins/services/src/js/components/ServiceStatusIcon.js

Changed delpoyment bubble text to be more accurate.
Closes https://jira.mesosphere.com/browse/DCOS-47444
In `dcos-ui/plugins/services/src/js/components/ServiceStatusIcon.js`
change `getUnableToLaunchWarning` function to:
```
return this.getTooltip(
`There are tasks in this queue that DC/OS has failed to deploy for ${DateUtil.getDuration(
Date.now(),
null
)}.`
);
```
and `render` function to:
```
const { service } = this.props;
return this.getUnableToLaunchWarning(service);
```
Start a service and hover over the message on the left of the status.
It should say "There are tasks in this queue that DC/OS has failed to deploy for".
None.
None.

[spike] DCOS-47443: [1.12] Deployment bubble-help shows confusing numbers.

---

src/js/pages/catalog/PackageDetailTab.js

It currently points to `dcos service`, it'd be more useful to show the
`dcos package install` command instead.
Closes https://jira.mesosphere.com/browse/DCOS-47686
For testing, screenshots, etc. see https://github.com/dcos/dcos-ui/pull/3550

DCOS-47686: [1.10] DC/OS Enterprise CLI description is wrong

---

src/js/pages/catalog/PackageDetailTab.js
src/js/pages/jobs/JobsTab.js

Make the Job string to be pluralized only once
Closes https://jira.mesosphere.com/browse/DCOS-47801
In Jobs tab search something when two or more jobs exist and verify that "Job" isn't pluralized twice.
When I updated the catalog messages, two lines unrelated to this PR appeared, we probably forgot them before.
None.
See https://github.com/dcos/dcos-ui/pull/3568

DCOS-47801: [1.11] Typo: "Jobss" on jobs page search

---

src/js/pages/jobs/JobsTab.js

Make the Job string to be pluralized only once
Closes https://jira.mesosphere.com/browse/DCOS-47798
In Jobs tab search something when two or more jobs exist and verify that "Job" isn't pluralized twice.
When I updated the catalog messages, two lines unrelated to this PR appeared, we probably forgot them before.
None.

DCOS-47798: [1.10] Typo: "Jobss" on jobs page search

---

plugins/jobs/src/js/components/JobsOverviewList.tsx

Make the Job string to be pluralized only once
Closes https://jira.mesosphere.com/browse/DCOS-47799
In Jobs tab search something when two or more jobs exist and verify that "Job" isn't pluralized twice.
When I updated the catalog messages, two lines unrelated to this PR appeared, we probably forgot them before.
None.

DCOS-47799: [1.12] Typo: "Jobss" on jobs page search

---

universe/package.json

Not really testable as this is done on merge
N/A
[dcos-ui-update-service #24](https://github.com/dcos/dcos-ui-update-service/pull/24) will need to merge and land before these nightly versions can be installed. but that shouldn't prevent this from merging
N/A

DCOS-47960 Publish nightly dcos-ui as "nightly" instead of "2.24.4"

---

CONTRIBUTING.md
Jenkinsfile
Jenkinsfile.reruns
package.json
scripts/ci/rerun-integration-tests.sh

- Check if this branch has a job with `head` that was triggered automatically without a manual check and ran successfully without rerunning the tests
- Check if this branch has a job with `head` that was triggered automatically without a manual check and ran successfully with rerunning a subset of tests
- Check if a `.only` in an integration test can be commited without a warning, renders the `merge` test red, but triggers the `branch` test to run reruns
- Decided that ~10min of work for not running is okay, compared to maintaining an extra check before the tests run. As always, feel free to challenge me on this 😇

DCOS-47925: remove manual trigger for rerun script

---

plugins/nodes/src/js/data/NodesNetworkClient.ts
plugins/nodes/src/js/data/__tests__/NodesNetworkClient-test.ts

This adds a http client which connects to the `/net/v1/nodes` endpoint and is returning a observable
Closes DCOS-44840
You can test it by running the test and sanity check the code. Also you could do the following changes
```diff
diff --git a/plugins/nodes/src/js/components/NodesTable.tsx b/plugins/nodes/src/js/components/NodesTable.tsx
index 867ca1b3d..6b7aedbe9 100644
--- a/plugins/nodes/src/js/components/NodesTable.tsx
+++ b/plugins/nodes/src/js/components/NodesTable.tsx
@@ -29,6 +29,10 @@ import {
spacingRenderer
} from "../columns/NodesTableSpacingColumn";
+import * as NetworkNodesClient from "../data/NetworkNodesClient";
+
+console.log(NetworkNodesClient);
+
interface NodesTableProps {
hosts: NodesList;
nodeHealthResponse: boolean;
diff --git …
```

DCOS-44840: feature public ip add network nodes endpoint client

---

plugins/jobs/src/js/data/__tests__/JobModel-test.js
plugins/services/src/js/data/__tests__/index-test.ts

Ensure all test assertions are being called correctly, even when relying on an async observable subscription.
This is an issue in unit tests using `rxjs-marbles` with non-marble tests that rely on `subscribe` calls.
Unit tests pass.
N/A
N/A
N/A

Fix RxJS tests: ensure all assertions are called

---

plugins/nodes/src/js/data/NodesNetworkClient.ts
plugins/nodes/src/js/data/NodesResolver.ts
plugins/nodes/src/js/data/__tests__/NodesResolver-test.ts

This adds the nodes resolver using the nodes network client to generate nodes. This is a workaround
since the nodes resolver does not actually return nodes yet.
CLOSES DCOS-44841
Check the tests for plausibility 
N/A
This is depending on #3579 
N/A

DCOS-44841: add network node resolver

---

src/js/pages/catalog/PackageDetailTab.js
src/styles/views/packages/styles.less

- Open a package from the Catalog
- Check that the layout is updated
None
None
Before:
After:

DCOS-19295: make "select version" in package detail more obvious

---

plugins/catalog/src/js/repositories/RepositoriesAdd.js
plugins/catalog/src/js/repositories/data/repositoriesModel.js
src/js/structs/RepositoryList.js

Fix repository priority when adding a new repository.
Closes https://jira.mesosphere.com/browse/DCOS-48014
Thanks to @nLight for helping me realize that priority is called index in the API.
1. Go to Settings > Package Repositories
2. Add a new Package Repository with priority 0, for example using the name "Universe2" and the uri "https://downloads.mesosphere.com/universe/repo/repo-up-to-1.13.json.gz"
3. Verify that the new package was added at the top
None.
None.

[spike] DCOS-48014: [1.12] Adding Package Repository with priority 0, does not push all packages 1 priority down

---

package-lock.json
package.json

run `npx tsc --noEmit -p tsconfig.json | grep error` before and after this commit and see the number of type errors decreasing. you can also check whether the version of `react` and `@types/react` are matching... 😄  
kudos to @Poltergeist for this finding!

update type-defs to match our react-version

---

src/js/stores/MetronomeStore.js
system-tests/jobs/test-jobs.js

Change job existence check because of jobTree structure bug.
Closes https://jira.mesosphere.com/browse/DCOS-48984
1. Go to jobs tab and create a new job, for example using the configuration from the jira:
```
{
"id": "check",
"labels": {},
"run": {
"cpus": 0.01,
"mem": 128,
"disk": 0,
"cmd": "sleep 3600;",
"env": {},
"placement": {
},
"artifacts": [],
"maxLaunchDelay": 3600,
"volumes": [],
"restart": {
"policy": "NEVER"
},
"secrets": {}
},
"schedules": []
}
```
2. Click it, run it and wait for it to be running
3. Click the checkbox next to running instance table row, click the stop button and verify that the modal closes, the job stops and the table row shows "Failed"
4. Verify that the new system test makes sense
While investigating this, @nLight and I discovered it was …

DCOS-48984: [1.13] Unable to stop running Metronome job

---

src/js/stores/MetronomeStore.js
system-tests/jobs/test-jobs.js

Change job existence check because of jobTree structure bug.
Closes https://jira.mesosphere.com/browse/DCOS-48983
1. Go to jobs tab and create a new job, for example using the configuration from the jira:
```
{
"id": "check",
"labels": {},
"run": {
"cpus": 0.01,
"mem": 128,
"disk": 0,
"cmd": "sleep 3600;",
"env": {},
"placement": {
},
"artifacts": [],
"maxLaunchDelay": 3600,
"volumes": [],
"restart": {
"policy": "NEVER"
},
"secrets": {}
},
"schedules": []
}
```
2. Click it, run it and wait for it to be running
3. Click the checkbox next to running instance table row, click the stop button and verify that the modal closes, the job stops and the table row shows "Failed"
4. Verify that the new system test makes sense
While investigating this, @nLight and I discovered it was …

DCOS-48983: [1.12] Unable to stop running Metronome job

---

src/js/components/modals/CliInstallModal.js

Change the CLI install modal instuctions to always show latest version.
Closes https://jira.mesosphere.com/browse/DCOS-48976
1. Open CLI install modal from the dropdown in the top right corner
2. Verify that the code snippet for OS X and Linux contains "latest" and not "dcos-1.13" (at the end of the second line)
I couldn't find an easy way to unit test that the installation instructions contain "latest".
None.

DCOS-48976: [1.13] Download cli modal shows wrong version if user has no permission

---

src/js/components/modals/CliInstallModal.js

Change the CLI install modal instuctions to always show 1.12 version.
Closes https://jira.mesosphere.com/browse/DCOS-48975
1. From Organization > Users, create a new user account and give it some permissions (using Add Permission > Insert Permission String) in order to be able to access the UI with it.
For example, the permissions from the jira:
```
dcos:adminrouter:ops:mesos full 
dcos:adminrouter:ops:slave full 
dcos:adminrouter:package full 
dcos:adminrouter:service:marathon full 
dcos:adminrouter:service:metronome full 
dcos:service:marathon:services:/ds full 
dcos:service:metronome:metronome:jobs full
```
2. Login with that user
3. Open the CLI instruction modal from the top right corner
4. Verify that the code snippet for OS X and Linux contains "dcos-1.12" and not "latest" (at the …

DCOS-48975: [1.12] Download cli modal shows wrong version if user has no permission

---

plugins/nodes/src/js/components/LeaderGrid.js
plugins/nodes/src/js/components/__tests__/__snapshots__/LeaderGrid-test.js.snap
plugins/nodes/src/js/data/__tests__/__snapshots__/MesosMasters-test.js.snap
src/js/translations/en-US.json

Label the Mesos version in Nodes Tab as "Mesos Version".
Closes https://jira.mesosphere.com/browse/DCOS-49072
1. Go to Nodes tab, open Masters sub-tab and verify that Mesos version is shown as "Mesos Version".
None.
None.

DCOS-49072: [1.12] The nodes tab, masters sub tab shows mesos version but does not label it as mesos

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/pages/task-details/TaskFileViewer.js

Add a check to prevent infinite loading
and a message for missing files.
Closes https://jira.mesosphere.com/browse/DCOS-49577
1. Start a service.
2. Open the service and click on an instance.
3. In `plugins/services/src/js/pages/task-details/TaskFileViewer.js`, change line 150 from `const files = this.getLogFiles();` to `const files = []`, to mock missing files.
4. Open the logs tab for that instance.
5. Verify that it doesn't load forever and a message is shown.
None.
None.

DCOS-49577: [1.13] MesosLogContainer / TaskFileViewer never loads logs for failed tasks

---

Jenkinsfile
plugins/services/src/js/pages/task-details/TaskFileViewer.js

Add a check to prevent infinite loading
and a message for missing files.
Closes https://jira.mesosphere.com/browse/DCOS-49578
1. Start a service.
2. Open the service and click on an instance.
3. In `plugins/services/src/js/pages/task-details/TaskFileViewer.js`, change line 149 from `const files = this.getLogFiles();` to `const files = []`, to mock missing files.
4. Open the logs tab for that instance.
5. Verify that it doesn't load forever and a message is shown.
Something broke while rebasing and it shows that @nLight also commited.
None.

DCOS-49578: [1.12] MesosLogContainer / TaskFileViewer never loads logs for failed tasks

---

tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js

I believe the test was just broken and passed because of the transition group quirks.
The test is to ensure that the modal is _closed_ but checks for the modal to _exist_ `cy.get(".modal").should("exist");`
Switching it to `cy.get(".modal").should("not.exist");` makes it green and actually makes sense
This is how we test closed modal in other cases `cy.get(".modal").should("to.have.length", 0);` but the `not.exist` reads better to my taste.

fix: assert for what is expected

---

plugins/jobs/src/js/components/JobsOverviewTable.js
src/js/utils/DateUtil.js
src/js/utils/__tests__/DateUtil-test.js

Check the dates of last successful and last unsuccessful run
and show no tooltip if they are not valid.
Closes https://jira.mesosphere.com/browse/DCOS-48028
In `dcos-ui/plugins/jobs/src/js/components/JobsOverviewTable.js`, replace the first line in the `renderLastRunStatusColumn` method with:
```
let { lastFailureAt, lastSuccessAt, status } = row[prop];
lastSuccessAt = "foo";
```
Go to jobs tab, create a job (that doesn't fail), run it and wait for it to finish.
From the jobs table, hover over the value for the "Last Run" column for this job.
You should see no tooltip.
I am not sure how to reproduce an actual invalid date, so I am mocking one.
None.

[spike] DCOS-48028: [1.12] Metronome JOBs show "Invalid Date".

---

package-lock.json
package.json

re-enabling renovate led to an update of babel-plugin-macros.
babel-plugin-macros changed the ways it resolves macro-plugins internally (we require something outside the project-root) in
2.4.2, thus we go back to 2.4.1 for now and can try to use the
`customResolve`-options that was introduced in 2.5.0 in the future.

fix the ee-build

---

src/js/components/modals/CliInstallModal.js

Follow-up from https://github.com/dcos/dcos-ui/pull/3615
While "latest" (which contains the latest stable release of the CLI)
will be usable on stable DC/OS versions starting from 1.13 and beyond,
this URL doesn't cover the alpha, beta and RC timecycle of DC/OS 1.13.
Specifically, when DC/OS 1.13 becomes alpha or beta, we want users
to download a preview of our yet to be released CLI, not the current
stable CLI which is released for DC/OS 1.12.
As such, we're using the DC/OS 1.13 specific URL. It currently contains
the dev version of our CLI and we'll push a stable release to it while
DC/OS 1.13 is in beta or RC.
We'll reconsider using "latest" for DC/OS 1.14.
cc @ArmandGrillet @rgo3

Use dcos-1.13 instead of latest in the CLI modal URL

---

scripts/pre-install
scripts/utils/marathon

We download raml definitions to compile App definition validators for the Service Create Form
Marathon version 1.8.143-7c07b88f9
1. Check out
2. npm i
3. Verify service form still works and validates JSON

DCOS-51008: Bump marathon version

---

plugins/jobs/src/js/components/JobsOverviewTable.js
src/js/utils/DateUtil.ts
src/js/utils/__tests__/DateUtil-test.js

Check the dates of last successful and last unsuccessful run
and show no console errors if they are not valid.
Closes https://jira.mesosphere.com/browse/DCOS-48029
In 1.13 it doesn't show "Invalid date", because we use format options, but instead it shows console errors.
In `dcos-ui/plugins/jobs/src/js/components/JobsOverviewTable.js`, replace the first line in the `renderLastRunStatusColumn` method with:
```
let { lastFailureAt, lastSuccessAt, status } = row[prop];
lastSuccessAt = "foo";
```
Go to jobs tab, create a job (that doesn't fail), run it and wait for it to finish.
From the jobs table, open the console.
You should see no date errors.
I am not sure how to reproduce an actual invalid date, so I am mocking one.
None.

DCOS-48029: [1.13] Metronome JOBs show "Invalid Date"

---

src/js/structs/CompositeState.js
src/js/structs/__tests__/CompositeState-test.js
src/js/utils/Util.js
src/js/utils/__tests__/Util-test.js
tests/_fixtures/marathon-1-task/summary.json
tests/_fixtures/v0/summary.js
tests/pages/services/TasksTable-cy.js

There is no need to merge mesos summary data now that we are no longer merging stream with summary. CompositeState#addState now (mostly) replaces internal data with the exception of master_info and node health data, which is now memoized and used to update new incoming summaries.
Without a deep merge operation, addState becomes much faster. Using fixtures, the speedup is around ~10x~ 100x for incoming summary data.
Nodes and node details should continue to operate as before with no obvious change. The only exception is that region information is now visible when using fixtures.
~Currently based on https://github.com/dcos/dcos-ui/pull/3771~

[DCOS-51179] Don't merge mesos summary with older summary data

---

plugins/nodes/src/js/pages/NodesAgents.js
plugins/nodes/src/js/pages/nodes/NodeDetailPage.js
plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js
plugins/services/src/js/components/DeploymentsModal.js
plugins/services/src/js/containers/service-detail/ServiceDetail.js
plugins/services/src/js/pages/ServicesPage.js
src/js/components/Page.js
src/js/components/charts/Chart.js
src/js/pages/DashboardPage.js
tests/pages/services/DeploymentsModal-cy.js

- Please click through all pages that might be affected (I don't want to give detailed pages, because if I miss one you miss them too) and see if they still operate like normal. 
- Decided to only change this on a level in the component tree that effects a lot of element on rerenders, this should maximize the impact of this PR
- I could not trace back every removed `forceUpdate`, but I still think we should ship them. If they hide an obscure bug, then we need to create better integration tests to catch that in the future. I see no other way, except keeping them and limiting the performance for all users in the future.
- I choose to use the component state in a very trivial way, as this is IMHO also about removing magic
|  Page | Before  | After  |
|---|---|---|
| Dashboard  |  <img …

DCOS-19315: remove force updates

---

plugins/services/src/js/components/modals/CreateServiceModalForm.js

Added the ability for a plugin to add a tab to the create service
modals, single and multi-container. This was done using
Hooks.applyFilter so that plugins could add additional navigation items
and TabView items to the CreateServiceModalForm component.
Ensure tabs and navigation doesn't break. The Hook filters created here will be used by plugins and nothing else to be tested here.

DCOS-49871 Support service tabs from plugins

---

plugins/jobs/src/js/components/form/RunConfigFormSection.tsx
plugins/jobs/src/js/components/form/ScheduleFormSection.tsx
plugins/jobs/src/js/components/form/helpers/DefaultFormData.ts

Add API defaults for optional fields as placeholders.
Closes DCOS_OSS-4955
Go to jobs form, ensure fields specified in [JIRA](https://jira.mesosphere.com/browse/DCOS_OSS-4955) have default as placeholder (see also screenshots).
N/A
N/A

DCOS_OSS-4955: add api defaults as placeholders

---

plugins/catalog/src/js/repositories/RepositoriesDelete.js
tests/pages/system/overview/repositories/RepositoriesTab-cy.js

Change data layer command so that deleting repositories works.
Closes https://jira.mesosphere.com/browse/DCOS-51221
~This is still work in progress. I still need to figure out how our integration tests work right now and add one for deleting.~
1. Go to Settings > Package Repositories
2. Add a new repository, for example:
```
name: universe 2
url: https://downloads.mesosphere.com/universe/repo/repo-up-to-1.13.json.gz
priority: 0
```
3. Try to delete it
4. Verify that it gets successfully deleted
None.
None.

DCOS-51221: Delete Repositores button not working for Package Repository

---

plugins/nodes/src/js/components/HealthTab.js
plugins/services/src/js/components/TaskDirectoryTable.js
src/js/components/CheckboxTable.js
src/js/components/UnitHealthNodesTable.js
src/js/pages/system/OrganizationTab.js
src/js/pages/system/UnitsHealthTab.js

reactjs-components Table was expecting `.gm-scroll-view` to raise scroll events in order to update it's virtual list of items. These events were not being raised because this is not the scrollable element in gemini. The new selector is the one added to &lt;GeminiScrollbar&gt; component in our FluidGeminiScrollbar wrapper.
There is another separate issue of the entire &lt;tbody&gt; getting replaced on the DOM when the event is raised, but this fixes the "giant blank screen" issue after scrolling ends and reveals a "janky scroll because the browser is too busy manipulating the DOM" issue.
Go to the jobs history page on SOAK to see a long list and start scrolling.

[DCOS-51247] fix: gm-scroll-view does not trigger onScroll events

---

Jenkinsfile

- Our integration tests are now red if there was a flake, not only if there is an error. If the reporting in data dog shows the right data we have almost no flake anymore, so this should not make anything worse.

CI: enable flakiness reporting

---

src/js/stores/DCOSStore.d.ts
src/js/stores/DCOSStore.js

Metronome data was being kept up to date but not used in the DCOSStore. Without this subscriber, MetronomeStore will no longer poll metronome when visiting unrelated pages.
When visiting the dashboard or other non-jobs page, you can see a request to the metronome API for jobs data. With this branch, you won't.

[DCOS-49688] Remove metronome subscriber from DCOSStore

---

src/index.html

To mitigate Android closing the keyboard because of Modal being redrawn.
When there's not enough space for a modal on the screen it tries adjusting its dimensions causing a repaint. For some reason repaint closes Android keyboard.
So the solution is to scale down the UI so that the modal fits :)
Closes DCOS-42386
1. Install Android Studio :)
2. Open Android emulator
3. Navigate to you local UI
4. Verify that you can focus login and password inputs without the keyboard being closed
The proper way to fix it would be fixing https://github.com/mesosphere/reactjs-components/blob/master/src/Modal/ModalContents.js#L112 so that id doesn't repaint the screen on Android devices. But that could have side effects on the Desktop version.
Working version:

DCOS-42386: downscale mobile viewport

---

locale/en/messages.json
locale/zh/messages.json
src/js/components/RequestErrorMsg.js

Change the error message function in order to show the email.
Closes https://jira.mesosphere.com/browse/DCOS-46215
1. In `proxy.dev.js` use an outdated cluster url and run `npm start`.
2. Verify that the email is shown on the error page
The message appears in English, even when the language is changed to Chinese, I am not sure why.
https://github.com/mesosphere/dcos-ui-plugins-private/pull/926

[spike] DCOS-46215: Error requesting UI Configuration message email is shown as {0}

---

src/js/components/charts/TimeSeriesArea.js

Camelcase svg attributes strokeLinecap and strokeDasharray to avoid console warnings when running app locally.
Closes DCOS-51672
Hard refresh on dashboard page with console open. You should not see these warnings:
N/A
N/A

[Spike] DCOS-51672: camelcase svg attributes

---

plugins/services/src/js/components/ServiceStatusIcon.tsx
plugins/services/src/js/structs/Service.d.ts
scripts/pre-commit

Jest was always returing `1` when running with pre-commit. This ended up being an issue loading a module from an incorrect path. I had to upgrade jest-cli locally just to see this error. We should work on updating jest too.
Additionally once the module path was fixed this exposed a few TS errors. 
I also updated the pre-commit script to look for tests for both JS & TS* files.
make a change and try to commit something, ensure you can commit without `--no-verify`

DCOS-51670 fix: pre-commit

---

Jenkinsfile
scripts/ci/rerun-integration-tests.sh

Reruns work again as you can see in https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-reruns/detail/PR-3810/8/pipeline/53
The current run is a run without a `.only` and you can see it also works.

Make reruns work again

---

src/js/utils/crypto/__tests__/index-test.js
src/js/utils/crypto/index.ts

Generates and extracts printable public/private RSA keypairs, with hardcoded defaults.
`generateRSA*` functions return a promise that resolves to a 2-tuple of strings: [privateKey, publicKey]
These strings are base64 encoded, with line breaks (\n) added for better printability.
This API is not available in IE <= 10, nor Firefox < 34. Callers should check  supportsWebCryptography(), which simply checks for the existence of a global crypto.subtle object.
IE11 _should_ work with this API usage according to the docs, but it should be tested because supportsWebCryptography() will return true currently.
jsdom does not ship with webcrypto API at all, so I had to mock out the most important functions. We must browser test keypair generation in order to fully test the API usage. I smoke tested …

[DCOS-49716] feat: util to generate RSA keypairs w cli defaults

---

locale/en/messages.json
locale/zh/messages.json
src/js/components/OfflineBanner.tsx
src/js/components/Page.js

Note to reviewers: the design team changed their mind - they wanted to show a page banner instead of a toast. See comments on the Jira ticket.
I recommend testing with Chrome so you can toggle the connection in the browser instead of turning your WiFi on and off
- Open the dev tools and go to the Network tab
- Toggle the "Offline" checkbox in the top of the Network tab
A warning banner should appear when "Offline" is checked, and disappear when it's not checked
If you're in a state where we show the `LicenseBanner` and you go offline, both banners will be displayed.
This could have been avoided by using extension-kid to create a Banner service (like the Toast service), but that would be well out of the scope of a 2-point ticket.

DCOS-5080: notify users if connection drops

---

system-tests/_scripts/setup.sh

CLI team dropped `.dcos.toml` config file support a while back and we've been using 1.11 cli for our tests
Closes DCOS-46178
System tests should pass

DCOS-46178: update dcos-cli in system tests

---

package.json

Adding `--forceExit` flag when we call `jest` in `npm test` to try and ensure jest exits when all tests are completed. We are seeing some issues in CI where jest will failed to exit. This flag will hopefully resolve this issue.
```
$ npm run test
```

fix(jest): add --forceExit to resolve issue with jest hanging

---

.gitignore
.linguirc
.vscode/settings.json
package.json
scripts/lingui-extract-with-plugins
tsconfig.json

This adds package support for what seems to be the best method of integrating our dev tooling with external plugins: symlinking ../dcos-ui-plugins-private
Here are the changes:
1. adds `npm run util:env:link-externalplugins` and `npm run util:env:unlink-externalplugins` which simply creates and removes the symlink.
2. the symlink is now used to extract lingui messages (a temporary one was created before), and without it, an error message is displayed.  I think this is a good simplification.
3. the symlink is used as a typescript "includes" so that modules can be resolves and other tooling works with our own settings
4. vscode workspace settings have been added to allow the symlink to be ignored by git, but not ignored by the editor. I had to add new entries to search exclude in order to …

Improve typescript integration with externalplugins

---

src/js/data/ui-update/UIMetadata.ts
src/js/data/ui-update/__tests__/index-test.ts
src/js/data/ui-update/__tests__/utils-test.ts
src/js/data/ui-update/index.ts
src/js/data/ui-update/utils.ts
tests/_fixtures/ui-settings/default-version.json
tests/_fixtures/ui-settings/version-010.json
tests/_fixtures/ui-settings/version-011.json

Updated the ui-update data-layer to parse the build version from string
provided instead of relying on semver.coerce. We currently use the
template of `<branch>+<build_version>(+<build_hash>)?` when branch is
`master` coercing the value gives use the build version, but if the
build is made from a release branch, `1.13` then `1.13` is returned from
semver.coerce instead of our desired build verions after the first `+`.
I added a `parseVersion` utility to the ui-update data-layer to handle
getting the build version from the string assuming the template is
followed. Unit tests for the utility and data-layer were added as well.
- Closes DCOS-53296
- running locally update `src/index.html` line 34 from `window.DCOS_UI_VERSION = "0.0.0-dev+semantic-release";` to `window.DCOS_UI_VERSION = …

[DCOS-53296] fix(ui-update): parse build version in data-layer

---

plugins/services/src/js/constants/ServiceStatus.ts

updating a service status as the result of a small pairing with design.
"degraded awaiting resources" is considered an error now.

make "degraded awaiting resources" an error

---

plugins/services/src/js/stores/MarathonStore.js
plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/__tests__/Application-test.js

1.13 backport of https://jira.mesosphere.com/browse/DCOS-51269 .
When testing, don't forget to use `release/1.13` in the private plugins.

[1.13] COPS-4710 affecting : Package-specific icons not showing for some services installed from Universe

---

src/js/config/Config.template.ts

Disable tracking so that we don't send
localhost errors to Sentry from our development.
Closes https://jira.mesosphere.com/browse/DCOS-53725
No testing needed.
None.
None.
None.

[spike] DCOS-53725  Disable tracking in the Config

---

cypress.json
package.json
scripts/utils/tests-functions

if you open cypress and change a test file, it actually reruns that file. when
paired with `.only` on a single test case, it looks like writing integration
tests will be waaaay more convenient for me, as the feedback cycle actually
feels quite convenient.
without the `fixtures` config in place a `npx cypress open` would fail for me on most tests.
this also enables snapshots in development mode!

add crypess:open to make better use of cypress during development

---

cypress.json
tests/_support/index.js
tests/pages/system/overview/repositories/AddRepositoryFormModal-cy.js
tests/pages/system/settings/UISettings-cy.js

it looks like someone had the plan to rely on stubs to speed up local testing.
unfortunately that idea has not been shared enough that we make good use of
this. in fact we don't seem to make use of this at all anymore.
under the assumption that `FULL_INTEGRATION_TEST` is never truthy, then unreachable code has been removed as well. that's why `clusterCleanup` had to go as well.
you might want to **review without whitespace changes**!

remove `FULL_INTEGRATION_TEST`

---

src/js/utils/JobUtil.js
src/js/utils/__tests__/JobUtil-test.js

Closes DCOS-54087
Closes COPS-4884
If you create a Job with the concurrencyPolicy set to "FORBID", and then edit the job in the UI, the JSON editor shows the policy as "ALLOW"
I was able to reproduce this issue on DC/OS 1.11.2 (customer version), as well as DC/OS 1.11.10.  I was not able to reproduce it on DC/OS 1.12.2 or 1.13, so it looks like maybe something was fixed in the interim. 
Steps to reproduce:
1. Submit the job (below) using:  dcos job add job.json
2. Navigate to the Jobs tab in the UI and edit the 'test-job' job
3. In the edit panel, click on the JSON editor
Expected result:
JSON editor shows the concurrencyPolicy as "FORBID"
Observed result:
JSON editor shows the concurrencyPolicy as "ALLOW"
```
{
"id": "test-job",
"description": "A job that sleeps regularly",
"run": { …
```

fix: preserve concurrencyPolicy and scheduleId in job json

---

plugins/jobs/src/js/components/form/helpers/MetronomeJobValidators.ts

because it crashes browsers for longer strings with a trailing -.

fix: short-circuit the JobID-validation if it ends with a `-`

---

package-lock.json
package.json
plugins/nodes/src/js/columns/__tests__/__snapshots__/NodesTableHealthColumn-test.js.snap
src/styles/components/form-elements/form-components/field-input/styles.less

Supporting changes for mesosphere/dcos-ui-plugins-private#1007. Updates ui-kit version (to be able to use Typeahead) and adjusts a form input style so that it does not need to be applied directly to an input element. See EE PR for more details.

DCOS-53692: supporting changes

---

src/js/stores/MesosStateStore.js

marathon changed task name which break 1.13 UI on tasks that are started from 1.12 marathon

[1.13] fix: adapt task id for 1.12

---

plugins/services/src/js/stores/MarathonStore.js
plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/__tests__/Application-test.js

1.12 backport of https://github.com/dcos/dcos-ui/pull/3820 .
When testing, don't forget to use `release/1.12` in the private plugins.

[1.12] COPS-4710 affecting : Package-specific icons not showing for some services installed from Universe

---

plugins/jobs/src/js/components/JobsForm.tsx
plugins/jobs/src/js/components/JobsFormModal.tsx
plugins/jobs/src/js/components/config/GeneralConfigSection.tsx
plugins/jobs/src/js/components/form/ArgsSection.tsx
plugins/jobs/src/js/components/form/EnvVarPartial.tsx
plugins/jobs/src/js/components/form/GeneralFormSection.tsx
plugins/jobs/src/js/components/form/ParametersSection.tsx
plugins/jobs/src/js/components/form/PlacementPartial.tsx
plugins/jobs/src/js/components/form/RunConfigFormSection.tsx
plugins/jobs/src/js/components/form/ScheduleFormSection.tsx
plugins/jobs/src/js/components/form/VolumesFormSection.tsx
plugins/jobs/src/js/components/form/helpers/JobFormData.ts
plugins/jobs/src/js/components/form/helpers/JobParsers.ts
plugins/jobs/src/js/components/form/helpers/MetronomeJobValidators.ts
plugins/jobs/src/js/components/form/helpers/__tests__/JobParsers-test.ts
plugins/jobs/src/js/components/form/helpers/__tests__/MetronomeJobValidators-test.ts
plugins/jobs/src/js/components/form/reducers/JobReducers.ts
plugins/jobs/src/js/components/form/reducers/JsonReducers.ts
plugins/jobs/src/js/components/form/reducers/ScheduleReducers.ts
plugins/jobs/src/js/components/form/reducers/__tests__/JobReducers-test.ts
plugins/jobs/src/js/data/JobModel.ts
src/js/events/MetronomeClient.ts
tests/pages/jobs/JobJSONEditor-cy.js

Make the JSON editor contents of the job form appear to be in metronome V0 spec format. Send payload to the API in V1 format.
**Note**: Please read/consider tradeoffs
Closes DCOS-52843
Try interacting with the jobs form and all of its sections. Try adding jobs, editing jobs, etc. Try editing using form only, JSON editor only, a combination of both.
This is a fairly major change so the potential for bugs is high.
I'm hesitant about these changes so here are some points to consider:
- This is not a typical "bug fix." This changes the behaviour of the jobs form in a non-trivial way
- These changes are designed to allow users to continue using V0 formatted jobs despite the fact that we've moved on to V1 format behind the scenes. This could raise the questions: what benefit are we getting from …

DCOS-52843: make json editor fit v0 spec

---

plugins/services/src/js/service-configuration/PodStorageConfigSection.js
plugins/services/src/js/service-configuration/ServiceStorageConfigSection.js

Closes DCOS-53645
On the services review screen, secret volume mounts show up as unknown volumes. These should be omitted from the display.
https://github.com/mesosphere/dcos-ui-plugins-private/pull/1019 adds the ability to review file and env secrets 
Before:
After:
Add some volumes and some secrets exposed as files in pods or single containers. Verify only the secret volumes are omitted.

DCOS-53645: omit secret volumes from service display section

---

plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/Pod.js
plugins/services/src/js/structs/__tests__/Application-test.js
plugins/services/src/js/structs/__tests__/Pod-test.js

Add isDelayed method to applications and pods
using the marathon endpoint.
Closes https://jira.mesosphere.com/browse/DCOS_OSS-4052
1. In `dcos-ui/plugins/services/src/js/structs/Application.js` add `console.log(this.isDelayed())` in the `getName` method.
2. Start a service with normal resource requirements and when it is running, open it and verify that 'true' is shown in the console (because it is not delayed).
3. Start a service with huge resource requirements, open it and verify that `false` is shown in the console (because it is delayed).
Example JSON from the jira:
```
{
"id": "/delayed",
"backoffFactor": 10,
"backoffSeconds": 1,
"cmd": "exit 1",
"container": {
"volumes": []
},
"cpus": 0.1,
"disk": 0,
"instances": 10,
"maxLaunchDelaySeconds": 3600,
"mem": 10,
"gpus": …
```

DCOS_OSS-4052: Add isDelayed method of Application and Pod

---

src/styles/components/menu-tabbed/styles.less

1. Open Firefox version 63 or older on a Windows or Linux machine (if you need an invite to our BrowserStack account, ping me)
2. Go to the Catalog, pick a framework, and click "Review & Run" to open the framework configuration form
The tabs on the left should all be clickable
I wasn't able to find what exactly changed between 1.12 and 1.13 that surfaced this bug, so this is just a quick fix
Before:
After:

[1.13] DCOS-54491: Framework configuration form tab bug on Firefox <=63 on Windows/Linux

---

plugins/services/src/js/constants/ServiceStatus.ts
plugins/services/src/js/structs/Application.js
plugins/services/src/js/structs/Pod.js
src/js/stores/__tests__/DCOSStore-test.js
src/styles/components/service-table/styles.less
tests/_fixtures/marathon-1-pod-group/groups-delayed.json
tests/_fixtures/marathon-1-task/delayed/queue.json
tests/_support/index.js
tests/pages/services/ServiceTable-cy.js

Add delayed status to service overview.
Closes https://jira.mesosphere.com/browse/DCOS_OSS-4053
1. Start a service with very large resource requirements.
Example JSON from the jira:
```
{
"id": "/delayed",
"backoffFactor": 10,
"backoffSeconds": 1,
"cmd": "exit 1",
"container": {
"volumes": []
},
"cpus": 0.1,
"disk": 0,
"instances": 10,
"maxLaunchDelaySeconds": 3600,
"mem": 10,
"gpus": 0,
"networks": [
{
"mode": "host"
}
],
"portDefinitions": [],
"upgradeStrategy": {
"maximumOverCapacity": 1,
"minimumHealthCapacity": 1
},
"killSelection": "YOUNGEST_FIRST",
"unreachableStrategy": {
"inactiveAfterSeconds": 0,
"expungeAfterSeconds": 0
},
"fetch": [],
}
```
1.5 (Optional) Check the marathon UI …

DCOS_OSS-4053: Add Delayed Status to Service overview & Service Detail Breadcrumb

---

plugins/services/src/js/components/modals/CreateServiceModal.js
tests/pages/services/ServiceFormModal-cy.js

Fix reappeaing JSON errors for better user experience.
Closes https://jira.mesosphere.com/browse/DCOS-52108
1. Go to service tab.
2. Try to add a new service with the default configuration (it will produce errors).
3. Open the JSON.
4. Go back.
5. Open the service form again.
6. Verify that there are no errors in the JSON.
7. Verify the same for Pod and JSON (for Pod you have to introduce an error, for example by deleting the ID).
8. Verify that the added tests make sense.
Sometimes clicking the back button triggers `onChange` in the form, which shows the errors. This is not introduced by this PR.
I created a jira to track this: https://jira.mesosphere.com/browse/DCOS-54264 .
None.

[spike] DCOS-52108: JSON erros in service creation are not being reset

---

plugins/services/src/js/columns/ServicesTableRegionColumn.tsx

1. Navigate to the Services table
2. If there aren't already any rows with "N/A" in the region column, add a group from the ellipsis button in the page header
3. Hover the "N/A" text in the region column
No tooltip should be shown
Before:
After:

DCOS-41120: don't show tooltip on services table region cell if it's "N/A"

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/constants/ServiceErrorMessages.js

[DCOS-54437](https://jira.mesosphere.com/browse/DCOS-54437) was written as an error exposing a secret as an env variable for a pod, but when testing I found the provided env variable `1234` was not valid for Marathon. Updated ServiceErrorMessages to treat `evironment.[key]` error paths as an invalid environment variable name and not "must be defined"
Define a pod or service with an invalid env variable name:
```json
{
"environment": {
"123": "TEST"
},
"id": "/",
{
"resources": {
"cpus": 0.1,
"mem": 128
},
"exec": {
"command": {
"shell": "sleep 1000"
}
}
}
],
"scaling": {
},
"networks": [
{
"mode": "host"
}
],
"volumes": [],
"fetch": [],
"placement": {
}
}
}
```
2. click review & run, …

fix: improve error message for invalid env variable name

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/constants/ServiceErrorPathMapping.js

Added a ServuceErrorPathMapping for pod volumeMount mountPath errors so
that the path is not printed in the errors info box, but instead a
configured name that is more user friendly.
- Closes DCOS-55113
- Open Service Create and choose Multi-container
- Select secrets tab
- select or enter a secret
- choose expose as file
- enter an invalid container path: `test/` | `/secret` | `secert<test` | ...
- Click `Review & Run`
- Verify Error in infobox begins with `Volumes mount path` and not `containers.0.volumeMounts.0.mountPath`
Before:
After:

fix: name pod volumeMount path errors

---

plugins/services/src/js/components/DeploymentsModal.js
plugins/services/src/js/components/__tests__/DeploymentsModal-test.js

We have seen errors in Sentry where the item being rendered into the
deployments table does not have a getStatus function. This doesn't make
a lot of sense since the item _should_ be an Application, Service or
ServiceTree. And all of those structs have a getStatus function. But
adding a guard against an unhandled exception here regardless.
- Closes DCOS-55175
I added unit tests for this case as I was never able to reproduce the actual event from Sentry.

DCOS-55175 - fix: ensure getStatus exists before calling

---

plugins/services/src/js/components/DeploymentsModal.js
plugins/services/src/js/components/__tests__/DeploymentsModal-test.js

We have seen errors in Sentry where the item being rendered into the
deployments table does not have a getStatus function. This doesn't make
a lot of sense since the item _should_ be an Application, Service or
ServiceTree. And all of those structs have a getStatus function. But
adding a guard against an unhandled exception here regardless.
- Closes DCOS-55176

DCOS-55176 - fix: ensure getStatus exists before calling

---

plugins/services/src/js/components/DeploymentsModal.js
plugins/services/src/js/components/__tests__/DeploymentsModal-test.js

We have seen errors in Sentry where the item being rendered into the
deployments table does not have a getStatus function. This doesn't make
a lot of sense since the item _should_ be an Application, Service or
ServiceTree. And all of those structs have a getStatus function. But
adding a guard against an unhandled exception here regardless.
- Closes DCOS-55177

DCOS-55177 - fix: ensure getStatus exists before calling

---

plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/__tests__/Service-test.js

Include executor resources when showing
pods in the services table.
Closes https://jira.mesosphere.com/browse/DCOS-43588
This PR is work in progress and is still missing tests.
2. Create a pod.
3. In the services table, verify that the resource columns also show executor resources. Compare them with the resources when clicking on the pod. In my example:
4. Verify that the added tests make sense.
None.
None.

DCOS-43588: UI doesn't reflect executor's resources for Pods on the Services page

---

plugins/services/src/js/columns/ServicesTableVersionColumn.tsx
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/containers/services/__tests__/ServicesTable-test.js
plugins/services/src/js/utils/Version.ts
plugins/services/src/js/utils/__tests__/Version-test.ts
tests/_fixtures/marathon-1-task/groups-sdk-services.json
tests/pages/services/ServiceTable-cy.js

Show full version for frameworks.
Closes https://jira.mesosphere.com/browse/DCOS-49181
1. Go to the services tab.
2. Start some services.
3. Go to catalog.
4. Start some frameworks.
5. Go to services table.
6. Verify that for services we show no version and for frameworks we show the full version (when hovering the cell, the tooltip should show the same version).
7. Verify that the added test makes sense.
None.
None.

DCOS-49181: Version column in service table shows misleading information

---

locale/zh/messages.json

Update Chinese message catalog
to include a more accurate translation.
Closes https://jira.mesosphere.com/browse/DCOS-48718
1. Start a service.
2. Change it once so that we have more than one task.
3. Switch to Chinese.
4. Open the service and verify that the text above the filter bar looks something like `显示2个任务s中的1个`.
I consider removing the pluralization "s" out of scope here as this is a ticket about the translation.
None.

DCOS-48718: i18n exhibition error for task list of UI in Chinese

---

plugins/services/src/js/service-configuration/ServiceNetworkingConfigSection.js
tests/pages/services/ServiceReviewScreen-cy.js

Show host port for services when it is configured.
Closes https://jira.mesosphere.com/browse/DCOS_OSS-1766
1. Start a service that has endpoints with manual host port.
Example JSON (from jira):
```
{
"id": "/statsd-server",
"container": {
{
"hostPort": 0,
"labels": {
"VIP_0": "/statsd-server:80"
},
"name": "nginx"
},
{
"containerPort": 8125,
"hostPort": 8125,
"protocol": "udp",
"name": "statsd"
}
],
"docker": {
"image": "hopsoft/graphite-statsd",
"forcePullImage": false
}
},
"cpus": 1,
"mem": 1024,
"gpus": 0,
"networks": [
{
"mode": "container/bridge"
}
],
"healthChecks": [
{
"portIndex": 0,
"protocol": "MESOS_HTTP"
}
]
}
```
2. In the review screen, verify that a manual host port is shown only when …

DCOS_OSS-1766: Service config page mislabels host ports in dcos-ui

---

package-lock.json
package.json

Update `reactjs-components` to resolve issue with permissions builder
- Closes DCOS-48704
- Create a user account
- Open the permissions builder for the new user
- Select `Mesos` -> `Master` -> `Quota`
- Select both `read` & `Update`
- Change `Quota` -> `Executor`
- Verify modal doesn't crash

fix: permission builder exception

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/components/SDKPlans.tsx
src/styles/components/service-endpoints/styles.less

Check if service is ready before polling
in order to avoid 404 errors in the console.
Closes https://jira.mesosphere.com/browse/DCOS-50657
2. Start a service with very high resource requirements, so that our SDK service can't start.
3. Go to catalog.
4. Start an SDK service, for example `portworx-kafka`.
5. Open its Plans tab in Chrome.
6. Verify that the new messages is shown.
7. Verify that we don't have any polling errors in the console.
System testing for this will be flaky and I couldn't figure out how to unit test this. If someone wants to pair on writing tests for this, I will be happy to.
None.

DCOS-50657: SDK Plans - 404 errors in console until scheduler exists

---

src/js/utils/JobUtil.js
src/js/utils/__tests__/JobUtil-test.js

Docker params are now preserved although no docker image has been provided.
CLOSES DCOS-39298
1. Add new jobs and enter docker parameters. Open edit page of the job. The docker parameter fields are blank.
2. Open add job or edit job page. Enter data in the docker parameters fields. Switch to json mode. The entered parameter are not visible. Switch back to forms view. The docker parameters fields are blank.

DCOS-45226: fix(jobsform): fix jobs form to preserve docker params

---

plugins/jobs/src/js/components/JobsForm.tsx
plugins/jobs/src/js/components/JobsFormModal.tsx
plugins/jobs/src/js/components/form/ArgsSection.tsx
plugins/jobs/src/js/components/form/GeneralFormSection.tsx
plugins/jobs/src/js/components/form/ParametersSection.tsx
plugins/jobs/src/js/components/form/RunConfigFormSection.tsx
plugins/jobs/src/js/components/form/ScheduleFormSection.tsx
plugins/jobs/src/js/components/form/helpers/JobFormData.ts
plugins/jobs/src/js/components/form/helpers/JobParsers.ts
plugins/jobs/src/js/components/form/helpers/MetronomeJobValidators.ts
plugins/jobs/src/js/components/form/helpers/__tests__/JobParsers-test.ts
plugins/jobs/src/js/components/form/helpers/__tests__/MetronomeJobValidators-test.ts
plugins/jobs/src/js/components/form/reducers/JobReducers.ts
plugins/jobs/src/js/components/form/reducers/JsonReducers.ts
plugins/jobs/src/js/components/form/reducers/ScheduleReducers.ts
plugins/jobs/src/js/components/form/reducers/__tests__/JobReducers-test.ts
plugins/jobs/src/js/data/JobModel.ts
src/js/events/MetronomeClient.ts
tests/pages/jobs/JobJSONEditor-cy.js

Make the JSON editor contents of the job form appear to be in metronome V0 spec format. Send payload to the API in V1 format.
Backport of #3866. See original PR for more details and testing instructions. Please do still smoke test jobs form as this was not a direct cherry-pick.
Closes DCOS-55586

DCOS-55586: make json editor fit v0 spec

---

src/js/pages/DashboardPage.js

Sort services by severity in the dashboard tab.
Closes https://jira.mesosphere.com/browse/DCOS-21186
2. Start some services, at least one deploying, one running, and one stopped.
Examples:
```
{
"id": "/running",
"portDefinitions": [],
"container": {
"volumes": []
},
"cpus": 0.1,
"mem": 128,
"networks": [],
"fetch": [],
"constraints": [],
"cmd": "sleep 1000"
}
```
```
{
"id": "/delayed",
"portDefinitions": [],
"container": {
"volumes": []
},
"cpus": 0.1,
"mem": 12800000000,
"networks": [],
"fetch": [],
"constraints": [],
"cmd": "sleep 1000"
}
```
```
{
"id": "/stopped",
"instances": 0,
"portDefinitions": [], …
```

DCOS-21186: Service status panel on dashboard should sort by severity

---

src/js/components/JSONEditor.js
src/js/components/__tests__/JSONEditor-test.js

Don't crash the UI if getNewJsonState
inside handleChange is null
Closes https://jira.mesosphere.com/browse/DCOS-50792
1. In `/src/js/components/JSONEditor.js` in `getNewJsonState` change line 313 from `if (this.jsonText === jsonText) {` to `if (this.jsonText !== jsonText) {`.
2. Open the JSON editor in the jobs form.
3. Change something in the editor.
4. Verify that no console error is shown.
5. Verify that the added test makes sense.
None.
None.

DCOS-50792: TypeError: Cannot read property 'jsonValue' of null

---

plugins/nodes/src/js/pages/nodes/NodeDetailTab.js
tests/_fixtures/marathon-1-task/summary.json
tests/pages/nodes/node/NodeDetail-cy.js

There is a bug that prevents the mesos state store from loading when useFixtures is true (this does not seem to affect integration tests?) Let me know if you are affected by the same issue. If so, just bypass the state store loading by changing NodeDetailPage line 41 from `mesosStateLoaded: false` to `mesosStateLoaded: true`
Visit the node details page (details tab) and see the drain status and new section there
This PR is currently based on #3960

[DCOS-55014] add drain status to node details

---

plugins/services/src/js/containers/pod-instances/PodInstancesTable.js

Closes DCOS_OSS-2208
<details><summary>Launch this pod</summary>
<p>
```
{
"id": "/ports-test",
"version": "2019-07-05T08:57:46.306Z",
{
"resources": {
"cpus": 0.1,
"mem": 128,
"disk": 0,
"gpus": 0
},
"exec": {
"command": {
"shell": "sleep infinity;"
}
},
"endpoints": [
{
"name": "ping",
"containerPort": 9000,
"hostPort": 0,
"protocol": [
"tcp"
]
},
{
"name": "test",
"containerPort": 8000,
"hostPort": 0,
"protocol": [
"tcp"
]
}
]
}
],
"networks": [
{
}
],
"scaling": {
},
"backoff": {
"backoff": 1,
"backoffFactor": 1.15,
"maxLaunchDelay": 300
},
"upgrade": {
"minimumHealthCapacity": 1,
"maximumOverCapacity": 1
},
"killSelection": "YOUNGEST_FIRST", …
```

DCOS_OSS-2208: add space between ports

---

src/js/pages/network/virtual-network-detail/VirtualNetworkDetailsTab.js

Show IP Subnet on the virtual network detail tab if is is a ipv6 value.
Closes https://jira.mesosphere.com/browse/DCOS-56244
1. Go to Networking > Networks page.
2. Open an ipv6 network, for example dcos6 on our daily cluster.
3. Open the details tab.
4. Verify that the ip subnet is shown and is correct (same as the ip subnet on the Networks page).
None.
None.

DCOS-56244: Networks empty IP subnet

---

plugins/services/src/js/components/MarathonTaskDetailsList.js
plugins/services/src/js/containers/service-configuration/ServiceConfiguration.js
plugins/services/src/js/service-configuration/ServiceGeneralConfigSection.js

Turned out `version` in Marathon [has always been](https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/app.raml#L318) `datetime` and we though it could be a free form string that is happen to be datetime in dcos.
Given we've thought it was a freeform string we still would parse it in the versions dropdown, but only for the active version
Create any _app_ and edit it couple of times to get several versions in history
Before | After
-- | --

[COPS-4214] Parse datetime in Service version

---

system-tests/jobs/test-jobs-cy.js
system-tests/services/test-apps-cy.js
system-tests/services/test-pods-cy.js
tests/pages/jobs/JobJSONEditor-cy.js
tests/pages/services/ServicePodReviewScreen-cy.js
tests/pages/services/ServiceReviewScreen-cy.js

All I did was enabling `TODO: Due to a bug in cypress you cannot type values with dots` everything else is prettier.
CI should pass
Closes DCOS-14972

DCOS-14972: Enable dot separated values in Cypress tests

---

src/styles/components/charts/styles.less

Change line 101 of plugins/nodes/src/js/components/NodesGridDials.js to `if (!node.isActive()) {`
Confirm the yield icon is center-aligned.
**Before:**
**After:**

DCOS-56383: center aligns alert icon for inactive nodes

---

plugins/nodes/src/js/components/NodesTable.tsx
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js

make sure you're using the maintenance feature in `Config.dev.ts`:
```
useFixtures: false,
useUIConfigFixtures: true,
uiConfigurationFixture: {
uiConfiguration: {
features: {
maintenance: true,
},
```
Is a bit tricky. Either follow the instructions in https://jira.mesosphere.com/browse/DCOS-56382. Create a cluster via ccm with channel `testing/pull/6158` and use the curl-commands given in the JIRA to initiate the draining/reactivation of a Node (make sure you add a cookie-header and adapt the agent-ID).
OR 
apply this patch, if you think it makes sense:
```
curl https://gist.githubusercontent.com/pierrebeitz/94dc57b43f3702f9464856cf0271c2b6/raw/727f75cc6ef28b328bd2e7f2b0415ddb101af363/gistfile1.txt | git apply
```
It makes use of the randomized `drain_info` that now changes for each node …

DCOS-56382 Fix Maintenance Status Change in NodesTable

---

plugins/services/src/js/data/groups/__tests__/_fixtures/roles-all.json
plugins/services/src/js/data/groups/__tests__/_fixtures/roles-dev.json
plugins/services/src/js/types/MesosRoles.ts
plugins/services/src/js/utils/QuotaUtil.ts
plugins/services/src/js/utils/__tests__/QuotaUtil-test.ts
tests/_fixtures/quota-management/roles.json

Small fix to use `consumed` as the quota key instead of `consumption`. `consumed` is what we're seeing on the final API but `consumption` was used in original design doc. This PR also updates our tests and fixtures to use the same key.

fix(quota): consumption -> consumed

---

package-lock.json
plugins/services/src/js/components/ServicesQuotaOverviewDetail.tsx
src/styles/components/quota/variables.less
tests/pages/services/QuotaOverview-cy.js

Add a banner to quota detail page
showing how many services do not have quota enforced.
Closes https://jira.mesosphere.com/browse/DCOS-55634
0. Start localhost and login.
1. Update your `Config.dev.ts`
```
uiConfiguration: {
...
features: {
quota: true
}
},
useFixtures: true,
...
```
2. Go to services page and open the quota tab.
3. Open a group that has services without quota (for example "2_apps")
4. Verify that the infobox is shown.
5. Verify that the added test makes sense.
None.
None.

DCOS-55634: Group quota detail page - No limit services banner

---

plugins/services/src/js/constants/ServiceStatus.ts
tests/_fixtures/marathon-pods/groups.js

Add delayed service status with 208 HTTP code.
Closes https://jira.mesosphere.com/browse/DCOS-56452
1. In `Config.dev.ts` make `useFixtures` to be `true`.
2. Find the service `208-hello-world` and verify that it has a "Delayed" status.
I left the status name as it is, but maybe we want to change it to "Delayed (Failed to launch tasks)"?
None.

DCOS-56452: DCOS UI to recognize DELAYED state of SDK services

---

plugins/services/src/js/columns/ServicesTableNameColumn.tsx
plugins/services/src/js/containers/services/ServiceTreeView.js
plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js
plugins/services/src/js/data/groups/resolvers.ts
plugins/services/src/js/data/groups/schema.ts
plugins/services/src/js/data/schema.ts
plugins/services/src/js/utils/QuotaUtil.ts
plugins/services/src/js/utils/__tests__/QuotaUtil-test.ts
tests/pages/services/ServiceTable-cy.js

Removed usage of `enforceRole` for showing information related to Quota. Introduced checking roles for quota on the serviceTree instead.
Quota and no limit banners should continue to work.
1. Create a top-level group
2. Using the Mesos API set quota for a role with the same name as your group
```
$ ## Set Quota
curl -X "POST" -k "<CLUSTER_URL>/mesos/api/v1?SET_QUOTA" \
-H 'Authorization: token=<token>' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d $'{
"type": "SET_QUOTA",
"set_quota": {
"quota_request": {
"force": true,
"guarantee": [
{
"scalar": {
"value": 1
},
"name": "cpus",
"role": "*",
"type": "SCALAR"
},
{
"scalar": {
"value": 512
},
"name": "mem",
"role": "*",
"type": "SCALAR"
}
],
"role": "<group_name>"
}
}
}'
```
3. Navigate to Quota tab Services -> …

Quota UI Clean-up

---

system-tests/_support/constants.js

we want to ship something really badly right now but jenkins appears to be slow
so that new services are not "running" in the time we expect them to. this is a
desperate measure to get master green again by just waiting longer for services
to be up and running!

test: quickfix flakes

---

src/js/components/modals/CliInstallModal.js

This removes the need to have `sudo` 2 times, by running `chmod`
before moving the file.
It also removes the creation of `/usr/local/bin` directory, it should be
present in any UNIX installation. Having this line is not really useful,
if the directory is missing it's most likely not in the $PATH either,
so the subsequent `dcos cluster setup` command would still fail anyways.

Simplify CLI installation instructions on UNIX

---

plugins/jobs/src/js/components/JobsForm.tsx
plugins/services/src/js/components/modals/CreateServiceModalForm.js
src/js/components/FrameworkConfigurationForm.js
src/js/components/SplitPanel.tsx
src/js/components/__tests__/SplitPanel-test.js
src/js/components/__tests__/__snapshots__/SplitPanel-test.js.snap
src/js/utils/WindowResizeUtil.ts
src/js/utils/__tests__/WindowResizeUtil-test.js
src/styles/components/modal/full-screen/styles.less
src/styles/components/modal/full-screen/variables.less
src/styles/components/split-panel/styles.less
src/styles/components/split-panel/variables.less
src/styles/index.less
src/styles/views/create-service-modal/styles.less

1. Go to either the create service form, create job form, or framework configuration form
2. Toggle the JSON editor open
3. Drag the handle on the left of the editor to resize the editor
The component I made (`SplitPanel`) to handle this only supports a side panel on the right. I can easily support it being on the left or right, but we don't have any cases where the side panel appears on the left.

DCOS-42072: make JSON editors resizable

---

plugins/nodes/src/js/columns/NodesTableActionsColumn.tsx
plugins/nodes/src/js/components/NodeActionsDropdown.tsx
plugins/nodes/src/js/pages/nodes/NodeDetailPage.js
plugins/nodes/src/js/pages/nodes/nodes-table/NodesTableContainer.js
src/js/utils/DefaultErrorUtil.tsx
tests/pages/nodes/node/NodeDetail-cy.js

1. add this key to the "uiConfiguration" key in Config.dev.ts
```
features: {
maintenance: true
},
```
2. enable useUIConfigFixtures
3. Visit the node details page
4. Choose the details tab for more status clarity
5. Try deactivating & reactivating nodes
6. Ensure feature is not present unless feature flag is set
Should exhibit the same behaviors as nodes overview table. #4008 & #4004 
Suggest reviewing commit-wise

[DCOS-55020] Drain/Deactivate actions on node details

---

src/js/config/Config.ts
src/js/data/ui-update/index.ts
src/js/utils/crypto/index.ts
src/typings/dcos-ui.d.ts

we already stub the plugins-setting of ui-config.json in our tests.
if we load a developers usual fixture here, the followin happens:
* the (ee-)plugins specified in that fixture will be loaded
* those plugins might make requests
* those requests might not be stubbed
* unstubbed requests return a bad status code
* the router points us to #/access-denied
* the test is broken :(
i'm usually not a fan of changing production-code so the tests don't break, but
this change seems to be worth it, as devs don't need to figure out what's going
on when integration-tests fail.
IF WE WANTED TO SOLVE THIS PROPERLY
we would need to change the way cypress and `RequestUtil.stubRequest` interact,
because it currently hides stubbed requests from cypress completely, directly
firing (flux- or redux-)actions. …

don't let useUIConfigFixtures interfere with cypress

---

plugins/services/src/js/columns/ServicesTableActionsColumn.tsx
plugins/services/src/js/constants/ServiceActionItem.ts
plugins/services/src/js/constants/ServiceActionLabels.ts
plugins/services/src/js/containers/services/ServicesTable.js

This adds a view plans action to sdk services action menu.
CLOSES DCOS-49719
Run a SDK Service
Visit the Service Table
Check if the action menu of the SDK service is containing "View Plans"
Click the Action the Service Plans table should be shown now.
N/A
N/A

DCOS-49719: feat(servicetable): add view plans action for sdk

---

src/styles/components/modal/full-screen/styles.less
src/styles/views/create-service-modal/styles.less

1. Create a new service
2. Set up a configuration that will cause the "Review & Run" screen to scroll. [Here's what I used](https://gist.github.com/mperrotti/165dd5cb887992c20afe1954d28fb75f)
Confirm you can scroll the Review & Run screen

DCOS-57387: Review & Run Service page in edit mode cannot be scrolled

---

plugins/nodes/src/js/actions/NodeMaintenanceActions.ts
plugins/nodes/src/js/components/NodesTable.tsx
plugins/nodes/src/js/pages/nodes/NodeDetailPage.js
tests/_fixtures/config/no-plugins.json

- Node maintenance actions and node status column should work without the feature flag present
- Fixed: Decommissioning a node when draining it should remove the node from the list and actually decommission it.

Remove feature flag for Node Maintenance

---

plugins/services/src/js/structs/Pod.js

Added a getRole override on Pod struct to support returning the role
value from a Pod using the Pod.spec instead of looking for the role at
the root of the Pod object like it is on the Service object.
- Closes DCOS-57466
See JIRA for steps to reproduce.
- Create Group with Quota & use group roles
- Create pod inside group
- Ensure Pod is not seen as "no limit" (no badges or banners displayed with pod is running in group with quota)

DCOS-57466 fix(quota): support pods in quota limit

---

plugins/services/src/js/columns/ServicesTableNameColumn.tsx
plugins/services/src/js/containers/services/ServiceTreeView.js
plugins/services/src/js/containers/services/ServicesTable.js
tests/pages/services/ServiceTable-cy.js

Remove from ServiceTreeView the infobox and the
badge that inform the user that a service is not enforced.
Closes https://jira.mesosphere.com/browse/DCOS-57482
2. Create a group with at least one quota field, but with a legacy role (expand the advanced settings to change the role).
3. Run a service inside this group.
4. Verify that no infobox and badge are shown.
5. Switch branch to master and verify that they are shown there.
None.
https://github.com/dcos/dcos-ui/pull/4034

DCOS-57482: Quota - Remove "no limit" badges & banner from ServicesTable

---

Jenkinsfile
locale/en/messages.json
locale/zh/messages.json

we frequently have non-extracted things on master. let's add a CI-check!
N.B. i also feel that `npm build` and the jenkins-build-stage have totally weird semantics but let's clean that up some other time!
see that red cross right below this box? (it's not here anymore. it's still in [jenkins](https://jenkins.mesosphere.com/service/jenkins/blue/organizations/jenkins/frontend%2Fdcos-ui-oss-pipeline/detail/PR-4053/1/pipeline/)... 🤦‍♂) that's the run that failed because of translatables not being extracted 🎉 	(i improved the error message as a fixup)
so it's red when there are strings to extract. afterwards i added a commit adding the most recent extractions - if CI is now green that would mean that the check does not fail and stuff works as expected. :shipit:!

add an lingui-things-extracted-check

---

plugins/services/src/js/containers/services/ServicesQuotaView.tsx

Add group id when creating a service from
the quota tab.
Closes https://jira.mesosphere.com/browse/DCOS-57522
2. Create a group with at least one quota limit (CPU, memory, etc.) set.
3. Open the quota detail page for that group.
4. Use the + button in the top right corner to open the dropdown and open the create service modal.
5. Open the single container service modal.
6. Verify that the group name is shown in the id.
7. Verify the same for pods.
None.
None.

DCOS-57522: Creating a service inside quota group does not create it in the group

---

plugins/services/src/js/utils/VipLabelUtil.js
plugins/services/src/js/utils/__tests__/VipLabelUtil-test.js

Add a non-object check and a null check
to the findVip function.
Closes https://jira.mesosphere.com/browse/DCOS-50331
2. Open the create service modal.
3. Open the single container service form.
4. Go to the Networking tab.
5. Click "Add Service Endpoint".
6. Click "Enable Load Balanced Service Address" checkbox.
7. Manually change portDefinitions.labels to null in the JSON Editor.
8. Verify that no console error is shown.
9. Verify the same thing for pods.
10. Verify that the added test makes sense.
None.
None.

DCOS-50331: TypeError: Cannot convert undefined or null to object

---

plugins/services/src/js/components/forms/MultiContainerNetworkingFormSection.js

Align "Auto Assigned" checkbox in the Networking tab for pods.
Closes https://jira.mesosphere.com/browse/DCOS-21165
2. Open the create service modal.
3. Select Pod.
4. Go to the networking tab.
5. Click "Add Service Endpoint".
6. Verify that the "Assign Automatically checkbox is aligned with the other checkboxes.
7. Verify that it's still aligned after zooming in and out and using different browsers (I tested it in Chrome and Firefox).
~There might be better solutions using css magic, but I think this is good enough.~
None.

    DCOS-21165  Assign Automatically Host port checkbox is not in line for multi container apps

---

plugins/jobs/src/js/components/JobsFormModal.tsx
plugins/jobs/src/js/components/form/reducers/ContainerReducers.ts
plugins/jobs/src/js/components/form/reducers/PlacementReducers.ts
plugins/jobs/src/js/components/form/reducers/VolumesReducers.ts
plugins/nodes/src/js/components/modals/DrainNodeModal.tsx
plugins/services/src/js/components/modals/ServiceRootGroupModal/utils.tsx
plugins/services/src/js/data/MesosClient.ts
plugins/services/src/js/data/__tests__/extension-test.ts
plugins/services/src/js/utils/QuotaUtil.ts
plugins/ui-update/components/InstalledVersion.tsx
src/js/utils/crypto/index.ts
tslint.json

while reviewing i noticed that we have this enabled for eslint, but not for
tslint. i personally like that rule a lot because it reduces the mental overhead
necessary for me to understand code.
don't know if a public poll is necessary as somewhen it was already decided to use that for `.js`-files.

enable prefer-const in tslint as well

---

locale/en/messages.json
locale/zh/messages.json
plugins/services/src/js/containers/service-connection/ServiceConnectionEndpointList.js
plugins/services/src/js/structs/Service.js
tests/_fixtures/marathon-1-task/groups.json
tests/pages/services/ServiceDetail-cy.js

This adds the weburl from a service to the endpoints tab as a click to copy function
CLOSES DCOS-57645
Start a  package with a frontend (marathon) for example.
visit the endpoints tab on the detail page and check if the url is present there.
N/A
N/A

DCOS-57645: feat(endpointstab): add weburl to endpoints tab

---

locale/en/messages.json
locale/zh/messages.json
package-lock.json
plugins/services/src/js/columns/ServicesTableActionsColumn.tsx
plugins/services/src/js/constants/ServiceActionItem.ts
plugins/services/src/js/constants/ServiceActionLabels.ts
plugins/services/src/js/containers/services/ServicesTable.js

This adds a link to the endpoints tab to the action menu of sdk's pods and apps.
CLOSES DCOS-57643
Visit the Service Table
Check if the action menu of a service(SDK, app or/and pod) is containing "View Endpoints"
Click the Action the Endpoints tab should be shown now.
N/A
N/A

DCOS-57643: feat(servicetable): add endpoints link to action menu

---

src/js/structs/UniversePackage.js

while having a look at some universe-related things i noticed that packages
bring postInstallNotes. curious where we use them i noticed that we don't.
so `getPostInstallNotes` is removed here. afterwards i grepped for every method
in this struct and found a couple more dead ends that are removed as well.
Despite ongoing discussion this PR is ready to be :eyes: and 🚢.
grep for those methods (in OSS and EE). try smoke testing some places that could potentially make use of those methods. (i also tried grepping for parts of those methods in case they are created dynamically, e.g. `"get" + preOrPost + "InstallNotes"` - could not find anything).

remove dead code

---

src/styles/components/modal/styles.less

This only happens on low-resolution screens, so test this on an external monitor if you use a Macbook Pro or some other high-end machine.
1. Open up a dialog modal (for example: the "Repositories" modal under Settings > Package Repositories)
2. Confirm the text and text input borders aren't blurry
3. Click around to other dialog modals and confirm they don't look blurry either
The fix is a little hacky to avoid having to do a CNVS upgrade
**Before**
**After**

DCOS-49193: fix blurry dialog modals on lo-res screens

---

plugins/jobs/src/js/pages/JobRunHistoryTable.js
tests/pages/jobs/JobDetails-cy.js

1. Go to jobs tab.
2. Create a long-running job, for example:
```
{
"id": "new-job-1",
"run": {
"cpus": 1,
"mem": 128,
"disk": 0,
"gpus": 0,
"cmd": "sleep 1000",
"artifacts": [],
"maxLaunchDelay": 3600,
"restart": {
"policy": "NEVER"
},
"ucr": {
"image": {
"id": "nginx",
"kind": "docker",
"forcePull": false
},
"privileged": false
}
},
"schedules": []
}
```
3. Click it and start it at least once.
4. Open the stop job run modal from the actions dropdown.
5. Verify that the modal can be closed by either clicking on the "Cancel" button or outside the modal.
None.
None.

Close stop job run modal

---

CONTRIBUTING.md
README.md
jest.config.js
scripts/lingui-extract
tsconfig.json

by making the following change in plugins-ee, we should be able to evade the
need for .babelrc-handling.
```diff
- { "extends": "../dcos-ui/.babelrc" }
+ { "extends": "../.babelrc" }
```
This change makes use of the fact that we now work with a symlink at plugins-ee.
To enable the aforementioned change, we need to change a couple details in our build-phase. Please review commit-by-commit to best be able to think about implications i might have missed.
Make sure you checked out the [according ee-branch](https://github.com/mesosphere/dcos-ui-plugins-private/pull/1048).
Test that the extraction still works properly. OSS and EE each have their own localization-files.

simplify lingui-extraction-script

---

plugins/services/src/js/columns/QuotaOverviewLimitColumn.tsx

- Closes DCOS_OSS-5510
1. Create a group with "Use Legacy Role"
2. Assign quota to group
3. Create service inside group
4. navigate to group's quota page
5. verify service quota limit status displays "Not Enforced"

DCOS_OSS-5510: use getRootGroupName not getRole

---

scripts/utils/test

we want to call `xterm.fit()` for the debug terminal. unfortunately this thing
here complains about `fit` being a debug-directive.
this is rather a quickfix making use of the fact the jest does not even have
`fit` or `fdescribe` but goes with `.only`
see https://github.com/mesosphere/dcos-ui-plugins-private/pull/914

enable xterm for ee

---

src/js/components/ClusterHeader.js

problem: navigate `http://localhost:4200/#/dashboard123` and see the app crashing.
fix: not registering things multiple times on the MountService. it looks like this was the only place we chose to dynamically register a component and relied on the header only being instantiated once.
TODO: follow up with an integration test, making sure PageNotFound is correctly rendered when a page is not found...

fix: don't error on pageNotFound

---

README.md
package.json

with directly cloning plugins-private to ./plugins-ee, we save a bit of
complexity and duplicated config-files. i see no apparent tradeoff (having worked for a couple weeks with this setup now).

update setup-docs and remove obsolete helpers

---

.prettierignore
package-lock.json
package.json
plugins/services/src/js/containers/services/ServiceTreeView.js
plugins/services/src/js/containers/services/ServicesQuotaView.tsx
src/styles/views/services/styles.less
tests/pages/services/GroupCreate-cy.js
tests/pages/services/QuotaOverview-cy.js

Replacing `+` icon with suggested dropdowns for Service/Quota screens
Please check empty states when group is empty
also top level group, 1 level, 2 levels deep
1. I had to leverage supplemental content and completely drop `addButton` prop on the header component
2. Overrode CNVS `button:hover` style in a nasty way 😅

[GA BLOCKER] DCOS-58445: Replace the "plus icon" dropdown with two separate dropdowns

---

plugins/services/src/js/components/dsl/TaskStatusDSLSection.js
plugins/services/src/js/constants/TaskStates.js
plugins/services/src/js/filters/TasksStatusFilter.js
tests/pages/services/TasksTable-cy.js

Add the option to filter tasks that have the status
failed or killed. This allows for easier debugging.
Closes https://jira.mesosphere.com/browse/DCOS-7157
1. Start a service with failed and killed tasks.
To have failed tasks, the command of the service could be something like `sleep 10 && exit 1`.
2. Open that service.
3. Click the button that opens the filter dropdown menu.
4. Verify that it contains checkboxes for failed and killed statuses.
5. Verify that these filters work as expected.
6. Verify that the old filters still work as expected.
7. Verify that the added tests make sense.
I am not sure if it's possible for pods to have a failed status. I will leave the filter as it is, though.
None.

[spike] DCOS-7157: Filter tasks by Failed/Killed status

---

plugins/services/src/js/columns/QuotaOverviewLimitColumn.tsx
plugins/services/src/js/components/ServicesQuotaOverview.tsx
plugins/services/src/js/components/ServicesQuotaOverviewDetail.tsx
plugins/services/src/js/components/modals/ServiceRootGroupModal/index.tsx
plugins/services/src/js/data/groups/__tests__/index-test.ts
plugins/services/src/js/data/groups/resolvers.ts
plugins/services/src/js/structs/Service.d.ts
plugins/services/src/js/structs/Service.js
plugins/services/src/js/structs/ServiceTree.d.ts
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js
plugins/services/src/js/types/ServiceQuotaRolesStats.ts

Closes DCOS-59786
I am not proud of this change. A bug was affecting the quota summary ("Applied", "Partially Applied", etc) where tasks started by services outside of Marathon were not subject to quota: https://jira.mesosphere.com/browse/DCOS-59786
To solve it, I needed to consult the mesos stream in order to locate tasks started by a service and count those against the quota stats. The UI was not really prepared for task-level stats, so I changed the tooltip for partially applied quotas to read "# services or tasks"
I had to make some awkward incursions into the stream. I added it to the graphql context in groups queries and awaited loading those pages that use them until the stream was received.  I drew the line at "getQuotaRoleStats" which consumes the stream by instead having it …

🚨1.14 blocker: account for non-marathon tasks when checking quota

---

src/js/components/modals/CliInstallModal.js

Starting with DC/OS 2.0 we're confident that the CLI is now cluster-version agnostic.
As such we can stick to the `latest` tagged version.
https://jira.mesosphere.com/browse/DCOS-59799

Update CLI URL in UI installation instructions

---

plugins/services/src/js/containers/services/ServicesContainer.js

Go to ui Settings, 
Change the setting to something different then 2 seconds  ( bigger is better )
Reload the page.
Open network tab.
Open services page.
Check in the network tab that the endpoints are only requested at about the changed refresh rate setting.
You can also check this on various pages in the app.
If you select the 60 sec. setting make sure that the service page or any other page loads in a reasonable time and not only 60 sec. later.

backport: fix: don't let users wait `refreshRate` before rendering services

---

plugins/services/src/js/containers/services/ServicesContainer.js

context: https://github.com/dcos/dcos-ui/pull/4142 (refreshRate)
there's another race condition that prevents the serviceContainer from
rendering: all data is already loaded. in that case we don't get an
onStoreChange-event and will not update `isLoading` until some requests triggers
a rerender (after 60 seconds).
we now trigger the `onStoreChange` at least once in the constructor to ensure we
either have the data or will be notified once the DCOS_STORE is ready to go.
it would be awesome to have promises for that. it would be even more awesome to
remodel that for a simpler data flow in that the container takes the stuff to
render as a prop and thus rerenders automatically on change. we should not need
to fear for a loss in performance as the cell-renderers of the table memoize …

fix: show serviceTable when all data is already loaded

---

src/js/mixins/StoreMixin.ts

there's not a single Listener that's specified as a string - so let's remove
related functionality.
`events` seems to always be present - so there's no need to null-check.
the args-slice is limited by the amount of args we pass to onStoreChange - which
is two. so args would always be the empty array. let's get rid of that.

refactor: remove some cruft from StoreMixin

---

scripts/utils/tests-functions

...to get a feeling for what's taking out tests so long.

chore: add a timestamp before each test run

---

plugins/services/src/js/containers/services/ServicesContainer.js
plugins/services/src/js/containers/services/ServicesTable.js

This changes the lifeCycleMethod on the `ServicesContainer` from
`componentWillRecieveProps` to `getDerivedStateFromProps` which is more fitting.
Select a very high refresh rate from the ui configurations, and visit the services page.
N/A
N/A

fix(servicescontainer): change to getderivedstatefromprops

---

plugins/services/src/js/columns/ServicesTableActionsColumn.tsx
plugins/services/src/js/components/modals/EditServiceModal.js
plugins/services/src/js/components/modals/ServiceResumeModal.js
plugins/services/src/js/structs/ServiceTree.js
plugins/services/src/js/structs/__tests__/ServiceTree-test.js

Due to the way we handle `Application`, `Service`, `Pod`, `ServiceTree` el al.
in the ServiceTable we aggregate all labels under all ServiceTrees (or "Groups")
multiple times.
We know for sure now that on some installations we got a lot of really large
labels, which lets browsers run out of memory, thus we now pay attention not to
compute labels for `ServiceTree`s too often.
To test this fix you might want to put a debugger in the `ServiceTree`'s
`getLabels`-method to see it's not called during the rendering of the table.
* be on master
* get the groups-response posted by Ben, put a `module.exports = ` in front and palce it at `tests/_fixtures/marathon-pods/groups.js`. 
* open the services tab and observe your browser crashing.
* check out this branch and see how your browser does not …

DCOS-61439 don't compute labels for ServiceTrees so often

---

package-lock.json
package.json
src/js/core/MesosStream.ts
src/js/mesos-proto.js
src/js/stores/MesosStateStore.js
tests/_fixtures/1-service-with-executor-task/mesos-subscribe.js
tests/_fixtures/healthy-tasks-in-mesos-and-marathon/mesos-subscribe.js
tests/_fixtures/marathon-1-task/mesos-subscribe.js
tests/_support/index.js
tests/_support/xhrfetch.js
tests/pages/nodes/node/tasks/NodesTaskDetailPage-cy.js

TL;DR
* savings in Mesos (cause it does not need to serialize to JSON)
* saving 40% (SOAK) to 70% (small cluster) bandwidth. might be worse for clusters with huge payloads (e.g. labels).
* saving ~15% in parsing time (on SOAK 2.0.0)
* A service's tasks show up after ~6 seconds now instead of ~16 seconds (on SOAK
from HH-office, 5 quite consistent samples each) after initial app load.
-------------------
using protobuf seems like a good idea, as mesos does not need to serialize its
state to json and does not need to send as much data over the wire.
on the our side it looks like parsing protobut is faster than parsing JSON -
apart from the savings on bandwidth.
we're evading @dcos/recordio, @dcos/mesos-client, @dcos/connection-manager,
@dcos/copychars and @dcos/http-service. :tada:
This …

DCOS-61253 - consume mesos state stream as protobuf

---

package.json
plugins/banner/SDK.js
plugins/banner/__tests__/BannerPlugin-test.js
plugins/banner/hooks.js
plugins/banner/index.js
plugins/example/hooks.js
plugins/index.js
plugins/intercom/SDK.js
plugins/intercom/__tests__/IntercomPlugin-test.js
plugins/intercom/hooks.js
plugins/intercom/index.js
plugins/oauth/SDK.js
plugins/oauth/components/LoginPage.js
plugins/oauth/hooks.js
plugins/oauth/index.js
plugins/services/index.js
plugins/tracking/SDK.js
plugins/tracking/__tests__/TrackingPlugin-test.js
plugins/tracking/actions/Actions.js
plugins/tracking/actions/__tests__/Actions-test.js
plugins/tracking/hooks.js
plugins/tracking/index.js
plugins/ui-update/SDK.js
plugins/ui-update/hooks.js
plugins/ui-update/index.js
scripts/pre-commit
src/js/components/modals/ModalHeading.js
src/js/events/__tests__/MesosSummaryActions-test.js
src/js/plugin-bridge/Loader.js

also NODE_PATH is not needed anymore as plugins-ee now is within the
dcos-ui/-path.
also making jest noisy in the precommit-hook again to better see errors.

chore: convert module.exports

---

src/js/pages/DashboardPage.jsx

This removes this.mesosState and puts it into the component state.
Test the dashboard and ensure that it still works as expected.
N/A
N/A

refactor(dashboard): omit the use of custom state

---

locale/en/messages.json
locale/zh/messages.json
src/js/__tests__/__snapshots__/tslint-test.ts.snap
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/pages/catalog/PackageDetailTab.tsx
src/js/structs/UniversePackage.ts
tests/_fixtures/cosmos/community-package-describe.json
tests/pages/catalog/packages/package/PackageTab-cy.js

We now have an icon (with a tooltip) indicating that a package has known issues.
`/package/describe` will get new fields in the future to indicate that a package has issues. the implementation in this PR currently assumes that there will be a boolean flag `hasKnownIssues` and is blocked until DataServices decided on an exact implementation.
Closes DCOS-58031

DCOS-58031 show a warning for packages with known issues

---

plugins/services/src/js/utils/FrameworkUtil.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
tests/_fixtures/cosmos/old-package-describe.json
tests/_fixtures/cosmos/older-package-describe.json

there's no need to crawl the mustache-template anymore as most packages now have
a `lastUpdated` set. (i'd prefer `lastUpdatedAt`)
this makes for way more packages showing that warning and also decouples the
frontend from SDK-internals (using a regex to parse a PACKAGE_BUILD_TIME_STR
out of a base64-encoded mustache template seemed suboptimal).
Closes DCOS-62284

DCOS-62284 use packages' lastUpdated to show an according warning

---

.gitignore
package.json
tsconfig.json

we enable the incremental-flag here.
because of the reasoning here
https://github.com/microsoft/TypeScript/issues/30661, we need to also need to
emit stuff. we'll have an __out-dir until there's a better option.

chore: speed up tsc

---

plugins/catalog/src/js/repositories/RepositoriesAdd.tsx
src/js/__tests__/__snapshots__/tslint-test.ts.snap
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
tslint.json

* `"one-variable-per-declaration": false`
as i see no real value in having one declaration per line.
* `"prefer-const": [true, { "destructuring": "all" }],`
let's mute tslint in case we have a destructuring going on that's using a let
but contains some consts. it will complain if all of those values are consts.

chore: change some tslint-rules

---

plugins/nodes/src/js/pages/nodes/NodeDetailPage.tsx
plugins/nodes/src/js/routes/nodes.ts
plugins/services/src/js/pages/task-details/TaskDetail.tsx
plugins/services/src/js/routes/services.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/routes/factories/network.ts
src/js/routes/jobs.ts

at some point in time Page.Header was introduced, which can handle tabs really
well as long as those are navigable via routes.
the instances here ARE navigable via routes and thus don't need to be complected
with the TabsMixin anymore.
in order to have tabs be active at the right point in time the tabs on the
NodesDetailPage have been transformed to use `routePath` instead of custom
handlers.
the rest of the changes is stuff that does not seem to be referenced anywhere
anymore.

refactor: remove TabsMixin from places that do not use it

---

webpack/webpack.config.js

This disables es Modules for images which fixes the issue where all images in the `index.html` woudl
have a source which is `[Object Module]`.

fix(build): disallow es modules for images

---

.releaserc

JIRA Was moved to new URL, old links seem to be valid, but some housekeeping cant be bad :)

chore: update JIRA API URL

---

plugins/services/src/js/columns/ServicesTableNameColumn.tsx
plugins/services/src/js/components/LogView.tsx
plugins/services/src/js/components/dsl/ServiceHealthDSLSection.tsx
plugins/services/src/js/components/dsl/ServiceOtherDSLSection.tsx
plugins/services/src/js/components/dsl/ServiceStatusDSLSection.tsx
plugins/services/src/js/components/modals/ServiceModals.tsx
plugins/services/src/js/containers/services/ServiceTreeView.tsx
plugins/services/src/js/containers/services/ServicesContainer.tsx
plugins/services/src/js/pages/ServicesPage.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/components/DSLInputField.tsx
src/js/components/Loader.tsx
src/js/components/NestedServiceLinks.tsx
src/js/components/PageHeaderActions.tsx
src/js/config/Config.ts
tests/_support/index.js
tests/pages/services/ServiceTable-cy.js

sorry for the big ball of mud-commit, but:
the primary goal of it is to reduce the amount of time the serviceTable-test
spends on CI. in order to properly debug it all the runtime errors now have
gone! along the way some cosmetic changes came up...
we're grouping some test-cases that are easy to test together and won't cause a
lot of harm if we need to tell the apart (since cypress will show the exact step
that went wrong in the video anyway).
test times should be down from ~160 sec to ~50 sec.

fix: speed up ServiceTable integration test

---

plugins/services/src/js/containers/services/ServicesTable.tsx
tests/pages/services/GroupCreate-cy.js
tests/pages/services/ServiceTable-cy.js

Services table columns were being unfortunately truncated. I increased their min width
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>

fix: "Allocated" min widths on services table

---

Jenkinsfile
scripts/ci/finalize-release

it looks like the upload recently broke. maybe because of change credentials?
as we currently do not use that latest-package we evade figuring out what's
going on by just NOT uploading the package to S3 and relying on github-releases
instead.

chore: do not upload a latest-release to universe

---

plugins/placement/components/PlacementSchemaField.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/components/BatchContainer.tsx
src/js/components/PlacementConstraintsSchemaField.tsx
src/js/components/SchemaField.tsx

fields with one of the following media-types now react to the specified field's
type.
* SchemaField:application/x-region-zone-constraints+json
* SchemaField:application/x-zone-constraints+json
if you set the type of the field to "string" it will render a stringified
version of the input into that field as before. if you use any other type,
you'll now get the raw data injected into that field.
a particular feature request was to change the placement_constraints-portion in
the JSON from the former to the latter format:
```
// with `type: 'string'`:
"placement_constraints": "[[\"@zone\",\"GROUP_BY\",\"1\"]]"
// with any other (or no) type:
"placement_constraints": [["@zone","GROUP_BY","1"]]
```
Closes COPS-5814

COPS-5814 - allow to toggle the way placement-info is stored

---

plugins/services/src/js/columns/ServicesTableNameColumn.tsx
src/js/components/NestedServiceLinks.tsx

if you entered a search term, long service names would be truncated to a mere
`...`.
Now we truncate to as wide as the column let's us:
`long-service-na...`
Closes D2IQ-66083

D2IQ-66083 - properly truncate service names while searching

---

cypress.system-tests.json
system-tests-ee/ee-services/test-apps-secrets-cy.js
system-tests/_support/index.js
system-tests/dashboard/test-dashboard-cy.js
system-tests/services/test-apps-cy.js
system-tests/services/test-external-volumes-cy.js
system-tests/services/test-pods-cy.js
system-tests/universe/test-universe-cy.js
tests/enterprise-plugins/dss/DSS-cy.js
tests/pages/nodes/node/NodeDetail-cy.js
tests/pages/services/ServiceExternalVolumes-cy.js
tests/pages/services/ServicePodReviewScreen-cy.js
tests/pages/services/ServiceReviewScreen-cy.js

we are often greeted by something like this:
`cy.visitUrl is not a function Because this error occurred during a 'before
each' hook we are skipping the remaining tests in the current suite: 'LDAP
users'`.
this try to fix it is just something out of the blue. apparently there seems to
be something wrong in cypress, as that command should have been added from the
support file. to get a better feel for how exactly things go wrong, we now load
this stuff ONLY ONCE.

chore: fix CI-flakes

---

scripts/utils/tests-functions

we seem to have tested the UI that the cluster brings in our system tests for
quite a while...

chore: run CI against the current build

---

plugins/services/src/js/containers/pod-instances/PodInstancesContainer.tsx
plugins/services/src/js/containers/pod-instances/PodInstancesTable.tsx
plugins/services/src/js/filters/PodInstanceStatusFilter.ts
plugins/services/src/js/filters/PodInstanceTextFilter.ts
plugins/services/src/js/filters/PodInstancesRegionFilter.ts
plugins/services/src/js/filters/PodInstancesZoneFilter.ts
plugins/services/src/js/filters/__tests__/PodInstanceStatusFilter-test.ts
plugins/services/src/js/filters/__tests__/PodInstanceTextFilter-test.ts
plugins/services/src/js/filters/__tests__/PodInstancesRegionFilter-test.ts
plugins/services/src/js/filters/__tests__/PodInstancesZoneFilter-test.ts
plugins/services/src/js/structs/PodContainer.ts
plugins/services/src/js/structs/PodInstance.ts
plugins/services/src/js/structs/PodSpec.ts
plugins/services/src/js/structs/Service.ts
plugins/services/src/js/structs/ServiceSpec.ts
plugins/services/src/js/structs/__tests__/PodSpec-test.ts
plugins/services/src/js/utils/InstanceUtil.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/structs/Node.ts

while trying to consolidate implementations for the ServicesTable and the
PodInstancesTable (we'll also later need to have a look at the
ServicesInstancesContainer) these changes emerged.
They help in comprehending what's going on and will be utterly helpful when
fixing the FilterBar on that Table (which has several bugs, as i learned during
this exercise).

chore: refactor PodInstancesTable

---

plugins/services/src/js/columns/ServicesTableCPUColumn.tsx
plugins/services/src/js/columns/ServicesTableMemColumn.tsx
plugins/services/src/js/columns/resourceLimits.ts
plugins/services/src/js/containers/pod-instances/PodInstancesTable.tsx
plugins/services/src/js/containers/tasks/TaskTable.tsx
plugins/services/src/js/filters/PodInstanceTextFilter.ts
plugins/services/src/js/structs/Pod.ts
plugins/services/src/js/structs/PodInstance.ts
plugins/services/src/js/structs/Service.ts
plugins/services/src/js/structs/ServiceTree.ts
src/js/__tests__/__snapshots__/tslint-test.ts.snap
src/js/__tests__/__snapshots__/typecheck-test.ts.snap
src/js/components/ExpandingTable.tsx
tests/pages/nodes/node/HealthTab-cy.js

due to the former implementation calculating resource limits in a couple places
there were inconsistencies in display.
we now calculate and display the allocated resource along with its aggregated
limit (as we formerly ignored the number of instances in one place and did not
properly multiply it in another case...).
also i could not help it and added a couple signatures to reduce the number of
type errors.
closes D2IQ-66986

fix: calculation of resource limits for pods/service table

---

system-tests/_support/index.js
tests/pages/services/ServiceActions-cy.js

we're seeing weird test results stating that cypress sees things like "east"
instead of "elast". let's try to clear the input every time before entering
something new. it should not make a difference with missed characters but the
past has proven that it does... cypress... :shrug:

chore: get rid of most common flake

---

webpack/webpack.production.js

turns out we only ever used the version-env for sentry. as we recently got rid
of sentry, we can now get rid of that version-env.
we also do some syntactic trickery here to reduce noise and remove some default
args to the compression plugin.

chore: slim down webpack config

---

plugins/services/src/js/reducers/serviceForm/FormReducers/resourceLimits.ts

if you deleted a cpu limit via the service form it would actually be removed
from the JSON but the value cached in the form state would still re-appear
again.
i consider this an ugly, yet the only feasible (due to time constraints)
solution as we don't have a proper representation of the form within the "state"
(which is called a "Batch" holding "Transactions"). thus we now
figure out that while reducing a new state, we're at a "Transaction" that represents unchecking the "unlimited" checkbox (that's what
`value === false` represents). only in this case we'll now reintroduce the value
that's been stored in the state - which has formerly been put in whenever the parsing function did not succeed - like when you want to delete a value from the form.
what i actually want to say here is that …

fix: actually hide cpu limits removed via the forms

---

plugins/services/src/js/reducers/serviceForm/JSONReducers/resourceLimits.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

while the form would show you the resource limits you set for a service, the
JSON editor is not picking those up. this ultimately leads to those values being
forgotten if you just hit "edit service" -> "save".
this change helps the JSON editor pick up the current values.

D2IQ-69177 fix: restore limits when editing a service

---

plugins/secrets/reducers/Container.ts

the JSON-editor somehow shows duplicated volumes in the production environment.
yes, that's right: you can't reproduce this in the usual development setup.
you could (currently) run a prod build locally on port 4201 like so:
```
npm run build && cd dist && npx http-server -sp "4201" --proxy "http://localhost:4200" --proxy-secure=false
```
to reproduce, create a file based secret with the name "keytab" and start the
following service:
```
{
"id": "secret-file",
"cmd": "cat $MESOS_SANDBOX/secret_file ; sleep 600; echo ''",
"container": {
"volumes": [
{
"containerPath": "secret_file",
"secret": "super_secret"
}
]
},
"secrets": {
"super_secret": {
"source": "keytab"
}
}
}
```
------------------------------
this fixes the issue by deduping the volumes by `containerPath` (as at …

fix: quickfix COPS-6085

---

plugins/jobs/src/js/types/JobConnection.ts
tests/_fixtures/metronome/jobs.json
tests/pages/jobs/JobsFilter-cy.js
tests/pages/jobs/JobsOverview-cy.js

https://jira.d2iq.com/browse/COPS-6139
before we render jobs, we expect our graphql-server to only give us jobs that
are considered to be within the group we're currently looking at. we're grouping
by spliting job-ids by "." - everything except for the last segment is a group,
while the last segment is the jobs "name" (in the context of this code).
unfortunately our graphql-server (yes, we have a graphql-server bundled with our
application. i don't think it's making code more maintainable btw) filtered jobs
like so:
imagine there're the jobs `foo.bar.baz.blorgh` and `foo.barbar.blorgh` and we're
currently looking at the `foo.bar` group. we're now filtering out all jobs that
don't start with that `path` (`["foo", "bar"]`). we did that with a
`startsWith`, so `foo.barbar.blorgh` was be …

COPS-6139 don't make up job-groups

---

src/js/components/modals/CliInstallModal.tsx

Bug was introduced in 00a2d7ca33a5fdb16322b4a7abb951c2ee183689 (#4133)
because download path was changed to not backward compatible path.
https://jira.d2iq.com/browse/COPS-6360

fix: invalid CLI download URL

---

tests/pages/services/ServiceActions-cy.js

this STILL can fail. aparently react-json-schemaform does some async stuff that
might only come back after we inserted the "elast" value and is subsequently
corrupting the fields state. updating to v2 might be an option.

chore: take 2 on fixing a common flake

---

system-tests/services/_scripts/teardown
system-tests/universe/_scripts/teardown
system-tests/universe/test-universe-cy.js

as we try to install the same services multiple times, there are race
conditions.
also there's a common error when trying to look at the plan. therefore we now
install confluent-kafka right in the first step, so it has some time to spin up
before the test.

chore: fix yet another common flake

---

tests/enterprise-plugins/organization/service-accounts/ServiceAccounts-cy.js

in case the account or secret could not be created, we show a generic error.
if the account could be created but the secret creation fails with a 404, we get
a more specific error (which we don't want here!).
now we always fail with the account creation right away.
the test was failing for good reason - i wonder how that can be a flake.
i suspect the nested beforeEach-blocks that override each others routes may be
troublesome and "broke" because of the recent cypress update. i saw a note about
fixtures now being loaded async. maybe that effects the order in which the
route-calls register. last one wins :/

chore: fix another flake

---

Jenkinsfile
cypress.json
cypress.system-tests.json
scripts/utils/tests-functions

we're currently merging all system-test-results into a big mess that makes our
reporting within jenkins inaccurate.
this is rather a POC that i intent to make cleaner later.

chore: separate junit-files per env

---

plugins/jobs/src/js/JobDetailPageContainer.tsx
plugins/jobs/src/js/components/JobsFormConfig.tsx
plugins/jobs/src/js/components/JobsOverviewTable.tsx
plugins/jobs/src/js/components/config/DependenciesConfigSection.tsx
plugins/jobs/src/js/components/config/EnvVarConfigSection.tsx
plugins/jobs/src/js/components/form/helpers/JobFormData.ts
plugins/jobs/src/js/types/Job.ts
src/js/events/MetronomeClient.ts
src/mocks/handlers.ts
src/styles/components/list/styles.less
tests/_fixtures/metronome/job.json
tests/_fixtures/metronome/jobs.json

this paves the way to display dependencies on the job-list and job-details view.
we currently display those and while i'm almost happy with the links in the
config-map (a.k.a. the detail view), i think we'll need to make another pass on
the list-view.
choosing to go with another icon here seemed reasonable for two reasons:
* ease of implementation: we only show this icon when a job brings dependencies,
which it only can do on a dcos >= 2.2. thus we don't need to introduce
feature-flagging here.
* we don't waste table-space in case a customer does not work with dependencies.
i'm totally open to changing this to a separate column that is only shown on
clusters >= 2.2 OR if at least one job is configured to have a dependency.
in order to play around with the changes in here, you'll want to …

feat: display dependencies on job list and detail view

---

plugins/jobs/src/js/components/config/DependenciesConfigSection.tsx

removing something that used to be a debug-statement.

fix: don't display deps when there are none

---

plugins/dss/components/DSSInput.tsx
plugins/dss/components/DSSVolumeConfig.tsx
plugins/services/src/js/components/forms/HealthChecksFormSection.tsx
plugins/services/src/js/components/forms/MultiContainerHealthChecksFormSection.tsx
plugins/services/src/js/components/forms/MultiContainerVolumesFormSection.tsx
plugins/services/src/js/components/forms/VolumesFormSection.tsx
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

the errors lens for volumes was not correct in that it did not looks at the
correct path. there's a `volume` portion in the errors.
while correcting that, we also converted one other trivial errorLens in the
healthchecks form section, as we want to get rid of Objektiv, which even has a
special place in our webpack config, because it needs to be compiled (as the
ONLY node_module).

fix: volume error validation

---

plugins/services/src/js/columns/ServicesTableCPUColumn.tsx
plugins/services/src/js/columns/ServicesTableMemColumn.tsx
plugins/services/src/js/columns/__tests__/resourceLimits-test.ts
plugins/services/src/js/columns/resourceLimits.ts
plugins/services/src/js/containers/tasks/TaskTable.tsx
plugins/services/src/js/structs/Service.ts
src/js/__tests__/__snapshots__/typecheck-test.ts.snap

this fixes a couple places that fomerly presented misleading information:
when deploying a single app and scaling it, we might run into the case that our
former calculations came to the conclusion to display some limits (because of
unintended side effects of default values).
when having a look at the tasks of either such an app or a scaled pod, we would
also see wrong information for the tasks. they would each claim to reserve / be
limited at their `own claim * scale` because the calculation did not distinguish
the `ServicesTable` from the `TasksTable`.
We now got some unit tests that you can look at to get a feeling for what values
we show!

COPS-6555 calculate limits correctly

---

Jenkinsfile
cypress.json
scripts/utils/tests-functions

we currently suffer a lot from almost always having yellow builds that are
reported as failures to github.
as there seems to be no way to convince jenkins to report a success easily, we
now go for this solution and now only have "green" and "red".
as a downside you now have to look at the test bubbles if you want to find
flakes and they are not reported in the upper right corner of jenkins anymore.
but currently it seems to be well worth that change.

chore: disable flake-reporting

---

tests/_fixtures/quota-management/roles.json
tests/pages/services/QuotaOverview-cy.js

follow up on https://github.com/dcos/dcos-ui/pull/4983#discussion_r513308130
the integration test now checks for `N/A` AND `0%`.

chore: add test to ensure 0 is not handle as N/A

---

src/styles/hacks.less
src/styles/index.less

we have a situation in that SOME osx users don't see tooltips and the dependency
toggle on the services form.
this is a workaround that always keeps poppers visible - where they would
usually be hidden once their reference elements are scrolled out of the
viewport.
note that i can not reproduce the issue, so this is a best effort commit/PR.
closes COPS-6624

COPS-6624 always keep ui-kit poppers visible
